### ISSUE TITLE
[GoodFirst] Ignore karmada-interpreter-webhook-example binary

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1005]
**Task description**:

Ignore karmada-interpreter-webhook-example binary in `.gitignore` file.

**Solution**:

```diff
diff --git a/.gitignore b/.gitignore
index 279676e9..32b83ef2 100644
--- a/.gitignore
+++ b/.gitignore
@@ -25,3 +25,4 @@
 /karmadactl
 /kubectl-karmada
 /karmada-scheduler-estimator
+/karmada-interpreter-webhook-example
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Haleygo** [comment]
I will work on this :)
/assign

**Comment by XiShanYongYe-Chang** [comment]
Welcome!
