### ISSUE TITLE
[GoodFirst] Add import alias for config/v1alpha1

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1008]
**Task description**:

We add a new API group `config.karmada.io` with the proposal https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-interpreter-webhook, we need to regulate the importing with it.

**Solution**:

modify hack/.import-aliases file:
```diff
diff --git a/hack/.import-aliases b/hack/.import-aliases
index 0f924614..51c69802 100644
--- a/hack/.import-aliases
+++ b/hack/.import-aliases
@@ -57,6 +57,7 @@
     "sigs.k8s.io/mcs-api/pkg/apis/v1alpha1": "mcsv1alpha1",

     "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1": "clusterv1alpha1",
+    "github.com/karmada-io/karmada/pkg/apis/config/v1alpha1": "configv1alpha1",
     "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1": "policyv1alpha1",
     "github.com/karmada-io/karmada/pkg/apis/work/v1alpha1": "workv1alpha1"
 }
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by feeltimeQ** [comment]
I will work on this :)
/assign

**Comment by XiShanYongYe-Chang** [comment]
@feeltimeQ  Welcome!
