### ISSUE TITLE
Is it possible to add the provider field when managing the cluster?

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#1023]
**What would you like to be added**:
Is it possible to add the provider field when managing the cluster?can be field by self.

**Comment by gf457832386** [comment]
I know Karmada has the plan，but now the code may need some time.

**Comment by 2hangchen** [comment]
@RainbowMango @lonelyCZ 
I'm sorry, can I reopen this issure？
Based on this, I think of an extended scenario: If the user needs to add some special info to the managed cluster for some identification, can I write the information in Annotations or other fields?
