### ISSUE TITLE
Another join cluster scenario.

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#1036]
**What would you like to be added**:
Through #1023，which was closed yesterday, I thought of another scene today: 
If the user needs to add some special info to the managed cluster for some identification, can I write the information in Annotations or other fields?
I think add the 'Annotations' field during join can solve a lot of user-defined nees.
Do you have any comments or suggestions？/cc @RainbowMango @lonelyCZ

**Comment by lonelyCZ** [comment]
It is indeed a requirement. How to customize member clusters when they are joining? 

Now we can edit member clusters when they have been joined by kubectl, but it is unfriendly for users.

We can add flag to assign these fields(like `Region`, `Zone`, `ProxyURL`) when execute `karmadactl join`.

But I don't think `Annotations` field is too much demand, like we use `kubeadm join` that doesn`t need to assign it.

**Comment by 2hangchen** [comment]
> It is indeed a requirement. How to customize member clusters when they are joining?
> 
> Now we can edit member clusters when they have been joined by kubectl, but it is unfriendly for users.
> 
> We can add flag to assign these fields(like `Region`, `Zone`, `ProxyURL`) when execute `karmadactl join`.
> 
> But I don't think `Annotations` field is too much demand, like we use `kubeadm join` that doesn`t need to assign it.

Region, Zone, and other fields can be declared resource related, but for example, I want to mark the cluster and declare the remarks of the cluster, such as how long the cluster on the public cloud has to expire...

**Comment by lonelyCZ** [comment]
> Users want to see all cluster information clearly on the control panel,whether need to leave a fiexible field.

We can directly use `kubectl annotate` to add `Annotations` to a member cluster if necessary.

Of course, adding this flag is not difficult that can be a flexible field.

What do you think? @RainbowMango

**Comment by 2hangchen** [comment]
> 
Yes, add this flag is not difficult, and I am wondering if we can add this flag during join a member cluster by `karmadactl jon`.

**Comment by 2hangchen** [comment]
> > Users want to see all cluster information clearly on the control panel,whether need to leave a fiexible field.
> 
> We can directly use `kubectl annotate` to add `Annotations` to a member cluster if necessary.
> 
> Of course, adding this flag is not difficult that can be a flexible field.
> 
> What do you think? @RainbowMango

Yes, add this flag is not difficult, and I am wondering if we can add this flag during join a member cluster by karmadactl join.

**Comment by RainbowMango** [comment]
For any requirements, I'd ask two questions:
- What's the (real) user case? 
- What's the benefit to the users?

**Comment by 2hangchen** [comment]
> 



> For any requirements, I'd ask two questions:
> 
> * What's the (real) user case?
> * What's the benefit to the users?

1.This is a scenario and assumption that I have come across in my use, and kubesphere and Rancher both provide additional information and comments when join cluster,I think it's a great experience for users, so I ask this question.
2.If Karmada is positioned as a command line management plug-in, I think this feature is dispensable, and if there are plans to launch dashboards, I think it will greatly improve the user experience.

These are just personal suggestions.

**Comment by RainbowMango** [comment]
> and kubesphere and Rancher both provide additional information and comments when join cluster,I think it's a great experience for users, so I ask this question.

Does the `additional information and comments ` added by UI or command line?

**Comment by RainbowMango** [comment]
> If Karmada is positioned as a command line management plug-in, I think this feature is dispensable, and if there are plans to launch dashboards, I think it will greatly improve the user experience.

Karmada's UI dashboard will be ready soon.  @gf457832386 is working on it.

**Comment by 2hangchen** [comment]
> > and kubesphere and Rancher both provide additional information and comments when join cluster,I think it's a great experience for users, so I ask this question.
> 
> Does the `additional information and comments ` added by UI or command line?

Both by UI,como Kubesphere, can add describe ,and rancher can add annotations.

**Comment by gf457832386** [comment]
Yes, our team is working hard to implement Dashboard V1 and we will document every suggestion from the community and iterate as soon as possible after the first release.

**Comment by 2hangchen** [comment]
> Yes, our team is working hard to implement Dashboard V1 and we will document every suggestion from the community and iterate as soon as possible after the first release.

Thank you so much!
