### ISSUE TITLE
Introduce bash auto-completion on Linux

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1046]
After we update `github.com/spf13/cobra` to `v1.2.1`(#1029, @iawia002), our `kubectl-karmada` and `karmadactl` introduced a `completion` command which will generate the autocompletion script for the specified shell.
```bash
# kubectl karmada completion --help 

Generate the autocompletion script for karmada for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  karmada completion [command]

Available Commands:
  bash        generate the autocompletion script for bash
  fish        generate the autocompletion script for fish
  powershell  generate the autocompletion script for powershell
  zsh         generate the autocompletion script for zsh

```

The `completion` command is added in favor of [the completion feature of cobra](https://github.com/spf13/cobra/releases/tag/v1.2.0). That's a wonderful feature I think, but I found it works for `karmadactl` but not for `kubectl-karmada`.

My testing:
```
# karmadactl completion bash >/etc/bash_completion.d/karmadactl
# <reconnect the bash>
# karmadactl joi<tab> // then the `join` command will be completed automatically.
```
I also tried `kubectl-karmada completion bash >/etc/bash_completion.d/kubectl-karmada`, but not works.

**What would you like to be added**:
- Figure out why this completion does not work for `kubectl-karmada`. 
- Add one documentation for this completion just like [Kubernetes doc bash auto-completion on Linux](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/)

**Why is this needed**:

**Comment by lonelyCZ** [comment]
It look like an interesting feature, I would like to research it.

/assign

**Comment by lonelyCZ** [comment]
Hi, @RainbowMango 
The command of autocompletion script seem created according `cmdUse`
https://github.com/karmada-io/karmada/blob/bc8c4008e624a81285744458b0b0c5f11ee16f05/cmd/kubectl-karmada/kubectl-karmada.go#L15-L17

https://github.com/karmada-io/karmada/blob/bc8c4008e624a81285744458b0b0c5f11ee16f05/pkg/karmadactl/karmadactl.go#L22-L30

When executing `kubectl-karmada completion bash >/etc/bash_completion.d/kubectl-karmada`, the autocompletion command created is `karmada`

$ cat  /etc/bash_completion.d/kubectl-karmada
```

# bash completion V2 for karmada                              -*- shell-script -*-

__karmada_debug()
{
    if [[ -n ${BASH_COMP_DEBUG_FILE:-} ]]; then
        echo "$*" >> "${BASH_COMP_DEBUG_FILE}"
    fi
}

# Macs have bash3 for which the bash-completion package doesn't include
# _init_completion. This is a minimal version of that function.
__karmada_init_completion()
{
    COMPREPLY=()
    _get_comp_words_by_ref "$@" cur prev words cword
}
...
```

If we change the name of `kubectl-karmada` to `karmada` and the name `/etc/bash_completion.d/kubectl-karmada` to `/etc/bash_completion.d/karmada`, the autocompletion can be used correctly.

```
$ karmada joi<tab> // then the `join` command will be completed automatically.
```

**Comment by RainbowMango** [comment]
So, what's next? What we expect is the completion could support `kubect karmada` plugin.
How can we do that?

**Comment by lonelyCZ** [comment]
> So, what's next? What we expect is the completion could support `kubect karmada` plugin. How can we do that?

This feature seems to be a work in progress.  [Command line completion for kubectl plugins](https://github.com/kubernetes/kubernetes/issues/74178)

There is a draft, but hasn't been merged. [Framework for shell completion for plugins (phase 1)](https://github.com/kubernetes/kubernetes/pull/105867)

**Comment by RainbowMango** [comment]
Nice finding. But it seems to take a long time.

**Comment by lonelyCZ** [comment]
> Nice finding. But it seems to take a long time.

Yes, too slow. But if there is official support, it is easier for users  to use the feature. Should we await for it?

**Comment by RainbowMango** [comment]
I guess so. Let's wait for a while.

**Comment by jwcesign** [comment]
We can close this issue now as the feature is ready.

/close
