### ISSUE TITLE
support run e2e tests locally

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#1047]
**What would you like to be added**:

We should provide a way to run e2e locally,so that e2e test can be add or debug locally before trigger a GitHub e2e action.

**Why is this needed**:

**Comment by RainbowMango** [comment]
I think the process would be :
```
hack/local-up-karmada.sh
hack/run-e2e.sh
```

not right? I haven't run it locally in a while.

**Comment by lonelyCZ** [comment]
It consumes virtual machine resources and may affect development. I only two 2c/4G virtual machines. :(

There are a [project](https://github.com/nektos/act) that can run github action locally. It looks good.

**Comment by pigletfly** [comment]
> I think the process would be :
> 
> ```
> hack/local-up-karmada.sh
> hack/run-e2e.sh
> ```
> 
> not right? I haven't run it locally in a while.

local-up-karmada.sh doesn't produce a karmada cluster,will dig into why it fails.

**Comment by pigletfly** [comment]
> It consumes virtual machine resources and may affect development. I only two 2c/4G virtual machines. :(
> 
> There are a [project](https://github.com/nektos/act) that can run github action locally. It looks good.

I don't think port github action locally is a right direction.The GitHub action is just a way to run e2e,or provide a environment.If e2e tests could be run locally,they could be run anywhere which provides a same environment(kind clusters etc.).

**Comment by lonelyCZ** [comment]
> If e2e tests could be run locally,they could be run anywhere which provides a same environment(kind clusters etc.).

Right, I agree it.

> local-up-karmada.sh doesn't produce a karmada cluster,will dig into why it fails.

It means failure of  deployment by `local-up-karmada.sh`? But indeed, this script is prone to errors locally, it rarely succeeds at once.

**Comment by RainbowMango** [comment]
I just run the E2E on my side, it works for me.
https://github.com/karmada-io/karmada/issues/1047#issuecomment-981587977

**Comment by pigletfly** [comment]
it's better to show what's going on during the setup? https://github.com/karmada-io/karmada/blob/master/hack/util.sh#L342

**Comment by pigletfly** [comment]
It stuck at `Waiting for kubeconfig file /Users/adam/.kube/karmada.config and clusters karmada-host to be ready...`,then clusters created by kind disappeared.

**Comment by pigletfly** [comment]
finally, kind clusters are up and running.But,failed to load karmada images to kind.
```
Can't open /usr/local/etc/openssl@1.1/openssl.cnf for reading, No such file or directory
4520461824:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/usr/local/etc/openssl@1.1/openssl.cnf','r')
4520461824:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
```

**Comment by RainbowMango** [comment]
Seems the OpenSSL is not well installed?
running it on Linux or Mac? I'm using Linux.

**Comment by pigletfly** [comment]
> Seems the OpenSSL is not well installed? running it on Linux or Mac? I'm using Linux.

yes,seems my OpenSSL is broken after MacOS upgrade,Reinstallation fixed this.

**Comment by RainbowMango** [comment]
/close
As I think we can run e2e test locally already.

**Comment by halfcrazy** [comment]
> It stuck at `Waiting for kubeconfig file /Users/adam/.kube/karmada.config and clusters karmada-host to be ready...`,then clusters created by kind disappeared.I'm using kind version 0.11.1.

I'm stuck at this line too, where is `KUBECONFIG_PATH}/karmada.config` coming from?

**Comment by RainbowMango** [comment]
Please make sure if your `kind` works well on your machine.
You can test that by :
```
kind create cluster --name <clustername>
```

**Comment by halfcrazy** [comment]
> Please make sure if your `kind` works well on your machine. You can test that by :
> 
> ```
> kind create cluster --name <clustername>
> ```

I can confirm the cluster has been created, but the kubeconfig does not exist. After some time, the cluster disappeared.
```bash
$ kind get clusters
using podman due to KIND_EXPERIMENTAL_PROVIDER
enabling experimental podman provider
karmada-host
member1
member2
member
```
