### ISSUE TITLE
Join cluster repeatedly failed

### ISSUE THREAD

**Issue by fanzhihai0215** [karmada-io/karmada#1059]
**What happened**:
One member cluster named bj-47 is joined to karmada successfully. Then unjoin it. When joining again, it failed. The cluster status is `False`. But if I only change the cluster name, such as 'bj-48', (command: `karmadactl join bj-48 ...`), it looks like successful again. The cluster status is `True`. The karmada kubeconfig and the member cluster kubeconfig is unchanged. The error log is below:
```
I1202 02:24:46.846388       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:46.852257       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:46.862960       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:46.883673       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:46.924279       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:47.004606       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:47.165385       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:47.486381       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:24:47.615992       1 cluster_controller.go:247] Created execution space(karmada-es-bj-47) for cluster(bj-47).
I1202 02:24:47.626912       1 detector.go:206] Reconciling object: v1, kind=Namespace, karmada-es-bj-47
I1202 02:24:47.627070       1 detector.go:381] attempts to match cluster policy for resource(v1, kind=Namespace, karmada-es-bj-47)
I1202 02:24:47.627143       1 detector.go:388] no propagationpolicy find.
I1202 02:24:47.627246       1 detector.go:699] Add object(v1, kind=Namespace, karmada-es-bj-47) to waiting list, length of list is: 186
E1202 02:24:48.234422       1 cluster_status_controller.go:195] Failed to update health status of the member cluster: bj-47, err is : Operation cannot be fulfilled on clusters.cluster.karmada.io "bj-47": the object has been modified; please apply your changes to the latest version and try again
I1202 02:25:20.697594       1 detector.go:206] Reconciling object: v1, kind=Namespace, karmada-es-bj-47
I1202 02:25:20.697755       1 detector.go:381] attempts to match cluster policy for resource(v1, kind=Namespace, karmada-es-bj-47)
I1202 02:25:20.697778       1 detector.go:388] no propagationpolicy find.
I1202 02:25:20.697793       1 detector.go:699] Add object(v1, kind=Namespace, karmada-es-bj-47) to waiting list, length of list is: 186
I1202 02:25:26.072849       1 detector.go:206] Reconciling object: v1, kind=Namespace, karmada-es-bj-47
I1202 02:25:26.072995       1 detector.go:381] attempts to match cluster policy for resource(v1, kind=Namespace, karmada-es-bj-47)
I1202 02:25:26.073025       1 detector.go:388] no propagationpolicy find.
I1202 02:25:26.073123       1 detector.go:699] Add object(v1, kind=Namespace, karmada-es-bj-47) to waiting list, length of list is: 186
I1202 02:25:26.146467       1 detector.go:206] Reconciling object: v1, kind=Namespace, karmada-es-bj-47
I1202 02:25:31.000311       1 cluster_controller.go:181] execution space(karmada-es-bj-47) no longer exists
I1202 02:26:34.480692       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:26:34.486694       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:26:34.493041       1 cluster_controller.go:247] Created execution space(karmada-es-bj-47) for cluster(bj-47).
I1202 02:26:34.498464       1 cluster_status_controller.go:101] waiting finalizer present for member cluster: bj-47
I1202 02:26:34.498390       1 detector.go:206] Reconciling object: v1, kind=Namespace, karmada-es-bj-47
I1202 02:26:34.498770       1 detector.go:381] attempts to match cluster policy for resource(v1, kind=Namespace, karmada-es-bj-47)
e, karmada-es-bj-47
I1202 02:26:34.498770       1 detector.go:381] attempts to match cluster policy for resource(v1, kind=Namespace, karmada-es-bj-47)
I1202 02:26:34.498820       1 detector.go:388] no propagationpolicy find.
I1202 02:26:34.498850       1 detector.go:699] Add object(v1, kind=Namespace, karmada-es-bj-47) to waiting list, length of list is: 186
E1202 02:26:34.521184       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:34.521253       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:35.036648       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:35.036694       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:35.536552       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:35.537129       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:36.036235       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:36.036297       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:36.539001       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:36.539178       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:36.554093       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:36.554142       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
I1202 02:26:36.554165       1 cluster_status_controller.go:136] Cluster(bj-47) still offline after retry, ensuring offline is set.
......
E1202 02:27:12.740943       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:27:12.740992       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
I1202 02:27:12.741014       1 cluster_status_controller.go:136] Cluster(bj-47) still offline after retry, ensuring offline is set.
I1202 02:27:17.129730       1 cluster_controller.go:375] cluster bj-47 hasn't been updated for 40.010235448s. Last Ready is: &Condition{Type:Ready,Status:False,ObservedGeneration:0,LastTransitionTime:2021-12-02 02:26:36 +0000 UTC,Reason:ClusterNotReachable,Message:cluster is not reachable,}
......
```
**Anything else we need to know?**:
It means a member cluster may only join karmada once. Unless you change the cluster name when joining.
I try to join cluster repeatedly in karmada v0.8.0. It works very well. I think there may be something that hasn't been cleaned up in etcd or elsewhere in v0.10.1.

**Environment**:
- Karmada version: v0.10.1
- K8s version : v1.20.1

**Comment by RainbowMango** [comment]
> I try to join cluster repeatedly in karmada v0.8.0. It works very well. I think there may be something that hasn't been cleaned up in etcd or elsewhere in v0.10.1.

I guess so.
@lonelyCZ Can you help investigate this issue?

**Comment by lonelyCZ** [comment]
> > I try to join cluster repeatedly in karmada v0.8.0. It works very well. I think there may be something that hasn't been cleaned up in etcd or elsewhere in v0.10.1.
> 
> I guess so. @lonelyCZ Can you help investigate this issue?

ok

**Comment by lonelyCZ** [comment]
I just tested it in `v0.10.1` and `master`,  but the error seemed not encountered in my environment.

I executed the following command
```
$ karmadactl join member68 --cluster-kubeconfig=/root/.kube/config

$ karmadactl unjoin member68 --cluster-kubeconfig=/root/.kube/config
```

What is your deployment type, `kind cluster` or `real cluster`?

It is unauthorized to check member cluster `/health` from your logs, I guess that is a problem of certificate. Could you give me more information? For example, more complete logs or other information. @fanzhihai0215 

> E1202 02:26:34.521184       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
I1202 02:26:34.521253       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
E1202 02:26:35.036648       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized

**Comment by fanzhihai0215** [comment]
> I executed the following command
> 
> ```
> $ karmadactl join member68 --cluster-kubeconfig=/root/.kube/config
> 
> $ karmadactl unjoin member68 --cluster-kubeconfig=/root/.kube/config
> ```

So, after the above two commands, if you execute the command(`karmadactl join member68 --cluster-kubeconfig=/root/.kube/config`) again, can you succeed? My complete steps are like this:
```
$ karmadactl join bj-47 --cluster-kubeconfig=/opt/deploy/cluster.config --cluster-context=external --kubeconfig=/opt/deploy/host.config
$ karmadactl unjoin bj-47 --cluster-kubeconfig=/opt/deploy/cluster.config --cluster-context=external --kubeconfig=/opt/deploy/host.config
$ karmadactl join bj-47 --cluster-kubeconfig=/opt/deploy/cluster.config --cluster-context=external --kubeconfig=/opt/deploy/host.config
```
The first join, the cluster is True. And the second join, the cluster status will be False.
Then I unjoin the bj-47 and execute `karmadactl join bj-48 --cluster-kubeconfig=/opt/deploy/cluster.config --cluster-context=external --kubeconfig=/opt/deploy/host.config`, it works.

> What is your deployment type, `kind cluster` or `real cluster`?

A real cluster.

> It is unauthorized to check member cluster `/health` from your logs, I guess that is a problem of certificate. Could you give me more information? For example, more complete logs or other information. @fanzhihai0215
> 
> > E1202 02:26:34.521184       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized
> > I1202 02:26:34.521253       1 cluster_status_controller.go:129] Cluster(bj-47) is offline.
> > E1202 02:26:35.036648       1 cluster_status_controller.go:289] Failed to do cluster health check for cluster bj-47, err is : Unauthorized

Log just repeat Unauthorized and offline. And repeat ClusterNotReachable every 40s. The certificate has not been changed. But why did I just change the cluster name and it works. Does this mean there is no certificate problem? thx~ @lonelyCZ

**Comment by lonelyCZ** [comment]
Thanks for your feedback. Perhaps the problem is that `clusterName` is conflict with `--cluster-context`. I will investigate it, please wait a moment.

**Comment by lonelyCZ** [comment]
It seem no problem in my environment(v0.10.1). Is it the problem of k8s version? Could you test it of `master` version in your environment? Thank you! @fanzhihai0215 
```
[root@master67 .kube]# kubectl get clusters
No resources found in default namespace.
[root@master67 .kube]# karmadactl join bj-47 --cluster-kubeconfig=/root/.kube/members.config --cluster-context=external --kubeconfig=/root/.kube/config
[root@master67 .kube]# kubectl get clusters
NAME    VERSION   MODE   READY   AGE
bj-47   v1.22.3   Push   True    3s
[root@master67 .kube]# karmadactl unjoin bj-47 --cluster-kubeconfig=/root/.kube/members.config --cluster-context=external --kubeconfig=/root/.kube/config 
I1203 17:55:45.720557   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:46.718153   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:47.719105   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:48.719072   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:49.717926   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:50.718844   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:51.718385   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:52.717686   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:53.717757   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
I1203 17:55:54.719056   10910 unjoin.go:286] Waiting for the cluster object bj-47 to be deleted
[root@master67 .kube]# kubectl get clusters
No resources found in default namespace.
[root@master67 .kube]# karmadactl join bj-47 --cluster-kubeconfig=/root/.kube/members.config --cluster-context=external --kubeconfig=/root/.kube/config
[root@master67 .kube]# kubectl get clusters
NAME    VERSION   MODE   READY   AGE
bj-47   v1.22.3   Push   True    11s
```

**Comment by fanzhihai0215** [comment]
Ok, please wait a moment. I deploy a `master` version karmada and test it.

**Comment by fanzhihai0215** [comment]
**The reason for the error may be that I didn't use a matching version of `karmadactl`**. 
I build all binaries and images from `master` version, and it works well. But if i use the old version of karmadactl, i don't know the version, maybe before `v0.8.0` or earlier, the error will reappear. 
Finally, i build a `v0.10.1` version of `karmadactl`. It works well. 
At present, it doesn't seem to be a issue. However, it is better if there is a prompt that the version is not uniform, because this may lead to this problem. @lonelyCZ

**Comment by lonelyCZ** [comment]
Thank you for pointing  this problem. In newer versions, we add `version` subcommand to check the version of tools, like `karmadactl version`. @fanzhihai0215 

Perhaps, we need to add some prompts in quick start document to let users to use newer version. @RainbowMango

**Comment by RainbowMango** [comment]
I think we can add an item in https://github.com/karmada-io/karmada/blob/master/.github/ISSUE_TEMPLATE/bug-report.md for users provide `kubectl-karmada` or `karmadactl` version. 

@fanzhihai0215 Are you willing to send a PR for this?

**Comment by fanzhihai0215** [comment]
Sure. I can improve this.
