### ISSUE TITLE
Support ARM and x86 arch

### ISSUE THREAD

**Issue by haiker2011** [karmada-io/karmada#1064]
**Please provide an in-depth description of the question you have**: 
Does kamada both support arm and x86 cluster ? we have some k8s clusters, some are arm64, some are x84, need something like kamada manage both cluster .

**What do you think about this question?**:

**Environment**:
- Karmada version: latest
- Kubernetes version: v1.19

**Comment by RainbowMango** [comment]
Theoretically, Karmada is insensitive to cluster hardware architecture(Karmada manages Kubernetes by standard API, I guess it'll work.), but there is no test coverage for arm64.

Please feel free to let us know if it is not.

**Comment by haiker2011** [comment]
@RainbowMango in arm64 node,  Is kamada agent and kamada schedule need arm docker image? I not find arm arch docker images for kamada.

**Comment by RainbowMango** [comment]
Yes, you might have to build the arm image by yourself. :(
We'd like to host arm docker images, looking forward to your feedback.

**Comment by cmicat** [comment]
Do you really mean arm & x86, not arm64 & x86-64?

Go runtime has known issues on 32-bit systems. See the [Go issue](https://github.com/golang/go/issues/599) and [atomic package](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) for more information.

**Comment by RainbowMango** [comment]
@cmicat,  @haiker2011 means the arm64 I guess.

And, now we have arm64 images on Docker hub([see this job](https://github.com/karmada-io/karmada/blob/master/.github/workflows/dockerhub-released-image.yml)). I think we can close it now.

/close
