### ISSUE TITLE
Work status reflection is too slow because of async worker enqueue rate limit

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#1068]
**What happened**:
I found it is very slow to reflect status from member cluster object to `work` because the slow enqueue of async worker. Now I have a cluster with thousands of objects. Their status need to be reflected by `karmada-agent`. The queue is almost empty most of time, and the reflection may be more than 30min later when the `work-status-controller` has gotten a object from the queue. I added some logs and found the enqueue rate limit has a slow effect on reflection.

**What you expected to happen**:
Taken [sample-controller](https://github.com/kubernetes/sample-controller)as an example, we will see when receiving a event from api-server the object will be immediately added into the queue by calling [workqueue.Add](https://github.com/kubernetes/sample-controller/blob/44e50f65ab823a51b4a73c343db79607f3075dc5/controller.go#L335-L346). Only if the processor has returned errors, we should enqueue object by calling [workqueue.AddRateLimited](https://github.com/kubernetes/sample-controller/blob/44e50f65ab823a51b4a73c343db79607f3075dc5/controller.go#L220-L224).

The similar code is everywhere in `k/k`. Like [here](https://github.com/kubernetes/kubernetes/blob/da503883d697bb971ed3bf3592538fe6faf75aa1/pkg/controller/cronjob/cronjob_controllerv2.go#L336-L345) and [here](https://github.com/kubernetes/kubernetes/blob/da503883d697bb971ed3bf3592538fe6faf75aa1/pkg/controller/ttl/ttl_controller.go#L195-L203).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
We are using the [DefaultControllerRateLimiter](https://github.com/karmada-io/karmada/blob/9fc9c5a0e899102d3e7fc4f5570c4b5cb9cffa1c/pkg/util/worker.go#L56) which takes a limiter(`10 qps, 100 bucket size`) suitable for controller retry, but not for our cases. 
right?

**Comment by Garrybest** [comment]
> We are using the [DefaultControllerRateLimiter](https://github.com/karmada-io/karmada/blob/9fc9c5a0e899102d3e7fc4f5570c4b5cb9cffa1c/pkg/util/worker.go#L56) which takes a limiter(`10 qps, 100 bucket size`) suitable for controller retry, but not for our cases. right?

No, `DefaultControllerRateLimiter` does not have any problems. The way we enqueque object is not reasonable.
