### ISSUE TITLE
Do we provide a way to migrate from KubeFed

### ISSUE THREAD

**Issue by iawia002** [karmada-io/karmada#1071]
**Please provide an in-depth description of the question you have**:

Will we provide a way to migrate from KubeFed to Karmada, such as automatically converting the `KubeFedCluster` object to Karmada's `Cluster` object, or is there any solution in the community for reference?

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
We are discussing how to migrate from a standalone cluster at https://github.com/karmada-io/karmada/discussions/1039, but not for KubeFed yet.

What you are asking is very interesting and I guess it'll be greatly helpful.

**Comment by GitHubxsy** [comment]
This feature looks great.
```
kubefedcluster-->karmada cluster
federateddeployment --> propationpolicy + deployment
federatedconfigmap --> propattionpolicy + configmap
```

**Comment by RainbowMango** [comment]
/close 
In favor of https://karmada.io/docs/next/administrator/migration/migration-from-kubefed/.
