### ISSUE TITLE
Enhance helm chart to support more scenes

### ISSUE THREAD

**Issue by JackZxj** [karmada-io/karmada#1072]
**What would you like to be added**:
1. support to install karmada host into any namespace of cluster
I only have one host cluster for testing Karmada, but I want to test different configurations. So I would like to install it into different namespaces.

2. support other service type of Karmada-apiserver, such as NodePort, LoadBalancer

3. ETCD might need multiple replicaCount, and PVC to storage data
**Why is this needed**:

**Comment by RainbowMango** [comment]
/assign @JackZxj 
Since I see you filed a PR(#1074) for it.
Thanks by the way.
