### ISSUE TITLE
Enable multi replicas in CI

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1078]
**What would you like to be added**:
Enable multi replicas for Karmada components in CI environments. 
| Component | current replica | desired replica | Note |
| --- | --- | --- | --- |
| karmada-controller-manager| [1](https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/artifacts/deploy/controller-manager.yaml#L9) | 2 | |
| karmada-scheduler | [1](https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/artifacts/deploy/karmada-scheduler.yaml#L9) | 2 | |
| karmada-webhook | [1](https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/artifacts/deploy/karmada-webhook.yaml#L9) | 2 | |
| karmada-agent | [1](https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/artifacts/agent/karmada-agent.yaml#L9) | 2 | |
| karmada-scheduler-estimator | [1](https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/artifacts/deploy/karmada-scheduler-estimator.yaml#L9) | 2 | |

**Why is this needed**:
Now, most Karmada components run only `1` replica in our CI environment, but users might deploy more than one replicas in the industry environment. 

Enable multi-replica in the CI environment that may help find some issues.

**Comment by RainbowMango** [comment]
@Garrybest @mrlihanbo How do you think?
Should we enable more replicas for `karmada-apiserver` and `karmada-etcd`?

**Comment by Garrybest** [comment]
The only difference is the leader election step. I suppose just 2 replicas are enough. One is one, two is multiple. 

And I don't think we need to add more replicas for apiserver and etcd. They are components of `k/k` and proved to be stable no matter how many replicas there are.

**Comment by RainbowMango** [comment]
OK. description updated.

**Comment by RainbowMango** [comment]
/help

This task might be more involved than it looks like because some updates might be needed for our testing process.
