### ISSUE TITLE
The status of the member cluster changes suddenly.

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#1082]
**Please provide an in-depth description of the question you have**:

When I run the command `kubectl get cluster` to obtain the cluster status for many times, the cluster status changes frequently and repeatedly. What is the reason?  
![image](https://user-images.githubusercontent.com/31329928/145188327-00b39b18-9bf2-4158-8680-4a901f75ad8d.png)

**What do you think about this question?**:

**Environment**:
- Karmada version:v0.9.0
- Kubernetes version:v1.21.0
- Others:

**Comment by RainbowMango** [comment]
The `kubectl get cluster` won't change cluster status I guess.

And why is the cluster in `Not Ready` state, you might check if any event/conditions on the `Cluster` object?
You can check the log of `karmada-controller-manager` too.

**Comment by 2hangchen** [comment]
> The `kubectl get cluster` won't change cluster status I guess.
> 
> And why is the cluster in `Not Ready` state, you might check if any event/conditions on the `Cluster` object? You can check the log of `karmada-controller-manager` too.

Well, LET me keep watching. This problem only recurs once or twice a day, and I haven't found the cause yet.

**Comment by 2hangchen** [comment]
One more piece of information:
![image](https://user-images.githubusercontent.com/31329928/145191294-fd2cca70-c83a-4d4c-8dec-3c4c4c239d63.png)

**Comment by RainbowMango** [comment]
> This problem only recurs once or twice a day, and I haven't found the cause yet.

That would be a serious issue. From the conditions, I guess it is due to karmada can't access the member cluster.

**Comment by 2hangchen** [comment]
I repeated a similar situation to this problem  
steps：  
1. After cluster 'cluster' is joined to the control plane, the status is
   
![32b4190d7519d5c450337ae21a4e225](https://user-images.githubusercontent.com/31329928/149074255-e1be01cd-983f-4c4b-afe9-0b3f7128af9f.png)

2.  I then restarted karmada-controller-manager and all cluster states became unknown
    
![image](https://user-images.githubusercontent.com/31329928/149074417-8a41f089-2edd-462b-9940-4565409ccc60.png)

controller-manager logs：
![image](https://user-images.githubusercontent.com/31329928/149074781-2ec715f1-ebca-43d2-ab33-ce05afcf55e5.png)


Karmada version:v0.10.0
Kubernetes version:v1.21.0

**Comment by RainbowMango** [comment]
That's weird, did you restart(not stopp) the `karmada-controller-manager`? From the log I can see, the controller stop working for 12 minutes.

**Comment by 2hangchen** [comment]
> That's weird, did you restart(not stopp) the `karmada-controller-manager`? From the log I can see, the controller stop working for 12 minutes.

I executed `kubectl delete pod Karmada-controller-manager`.  
And I have a question. What is the reason for stopping working? Or at what point does it stop working?

**Comment by RainbowMango** [comment]
> What is the reason for stopping working? Or at what point does it stop working?

No idea yet. Can you reproduce this issue?

**Comment by 2hangchen** [comment]
> > What is the reason for stopping working? Or at what point does it stop working?
> 
> No idea yet. Can you reproduce this issue?

I mean what would cause karmada-controller-manager to stop working？

**Comment by RainbowMango** [comment]
> I mean what would cause karmada-controller-manager to stop working？

Not clear yet.
From the log you posted above, `clusterController` says `cluster status controller stopped posting cluster status`, don't know why.

I think we should try to reproduce it.

**Comment by 2hangchen** [comment]
> > I mean what would cause karmada-controller-manager to stop working？
> 
> Not clear yet. From the log you posted above, `clusterController` says `cluster status controller stopped posting cluster status`, don't know why.
> 
> I think we should try to reproduce it.

ok, I'll try to reproduce it again

**Comment by xkkker** [comment]
same problem. did u fix it ? I test with the Karmada in my local environment and join a member cluster to karmada.

I can see that my cluster is joined but the status of cluster is Unknown, and sometimes went to False..
Describe the cluster and I get this Message:` Cluster status controller stopped posting cluster status.`

Then I check the controller-manager's log but it seems not errror in it .
Any ideas? Or where can I get more log or message about the joined cluster to help me find what the problem is ? 
Thanks !

**Comment by RainbowMango** [comment]
@xkkker Which [cluster modes](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md#overview-of-cluster-mode) do you select for your member cluster? `Pull` or `Push`? 

> Then I check the controller-manager's log but it seems not errror in it .

If you are using `Pull` mode, you should get the log from `karmada-agent`.

**Comment by xkkker** [comment]
> 

Hi~
I use Push mode to join the cluster.
```
kubectl --kubeconfig=/etc/karmada/karmada-apiserver.config get clusters
NAME      VERSION   MODE   READY     AGE
member1             Push   Unknown   65m
```

**Comment by xkkker** [comment]
And I tried to deploy a deployment to the member cluster. And it report that `no clusters fit`, so, I guess the cluster is really not ready...
```
  Normal   SyncWorkSucceed         25s (x3 over 25s)  binding-controller  Sync work of resourceBinding(default/nginx-deployment) successful.
  Normal   ApplyPolicySucceed      25s (x2 over 25s)  resource-detector   Apply policy(default/example-policy) succeed
  Normal   AggregateStatusSucceed  25s (x3 over 25s)  binding-controller  Update resourceBinding(default/nginx-deployment) with AggregatedStatus successfully.
  Warning  ScheduleBindingFailed   4s (x13 over 25s)  karmada-scheduler   no clusters fit
```

**Comment by RainbowMango** [comment]
> Then I check the controller-manager's log but it seems not errror in it .

Yes, we should check logs of `karmada-controller-manager` for a cluster in `Push` mode. 
How many replicas do you set for your deployment which holds the `karmada-controller-manager`? Have you checked all the pods? 
Can you post the logs you get?

**Comment by xkkker** [comment]
> > Then I check the controller-manager's log but it seems not errror in it .
> 
> Yes, we should check logs of `karmada-controller-manager` for a cluster in `Push` mode. How many replicas do you set for your deployment which holds the `karmada-controller-manager`? Have you checked all the pods? Can you post the logs you get?
Oh.. I found the error in the log now. Thanks for your help.
It seems that my cluster network has some problem and the karmada controller manager can not connect to the apiserver of the member cluster.
I will try to fix the network issue.

**Comment by jwcesign** [comment]
This problem has not occurred again, and it appears to have been caused by a network connection issue.   
Therefore, we will consider this issue closed. Please do not hesitate to open a new issue if the problem reoccurs.
/close
