### ISSUE TITLE
Enhancement `--controllers` flag of `karmada-controller-manager`

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1085]
**Background**
#1083(by @snowplayfire) introduced `--controllers` flag to `karmada-controller-manager` for customize controllers:
```
--controllers string                            A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'. All controllers: cluster, clusterStatus, hpa, binding, execution, workStatus, namespace, serviceExport, endpointSlice, serviceImport. (default "*")
```

**What would you like to be added**:
The default enabled controller list now is `hard-coded`:
https://github.com/karmada-io/karmada/blob/43d75741e84ef31e1ce7b06f90f0ef8a31220a4c/cmd/controller-manager/app/options/options.go#L81

It'd be great if we can generate the controller list automatically, otherwise, if we introduce a new controller in the future, we might forget to update.

**Why is this needed**:

**Comment by jameszhangyukun** [comment]
I think If we can generate the controller list automatically. But the func `IsControllerEnabled` for different controller has different code logic. For example  `endpointSliceController` and `serviceImportController` we can not generate the code automatically
```go
if IsControllerEnabled("endpointSlice", controllers) {
		endpointSliceController := &mcs.EndpointSliceController{
			Client:        mgr.GetClient(),
			EventRecorder: mgr.GetEventRecorderFor(mcs.EndpointSliceControllerName),
		}
		if err := endpointSliceController.SetupWithManager(mgr); err != nil {
			klog.Fatalf("Failed to setup EndpointSlice controller: %v", err)
		}
	}

	if IsControllerEnabled("serviceImport", controllers) {
		serviceImportController := &mcs.ServiceImportController{
			Client:        mgr.GetClient(),
			EventRecorder: mgr.GetEventRecorderFor(mcs.ServiceImportControllerName),
		}
		if err := serviceImportController.SetupWithManager(mgr); err != nil {
			klog.Fatalf("Failed to setup ServiceImport controller: %v", err)
		}
	}

```

**Comment by iawia002** [comment]
@RainbowMango You can take a look at #1084 first, I made a little optimization to the `--controllers` flag

**Comment by RainbowMango** [comment]
@jameszhangyukun I think we can define a `controllerContext` just like Kubernetes does:
https://github.com/kubernetes/kubernetes/blob/cc6f12583f2b611e9469a6b2e0247f028aae246b/cmd/kube-controller-manager/app/controllermanager.go#L311

Then we can add a `setup` function for each controller, like https://github.com/kubernetes/kubernetes/blob/cc6f12583f2b611e9469a6b2e0247f028aae246b/cmd/kube-controller-manager/app/controllermanager.go#L401

**Comment by jameszhangyukun** [comment]
> @jameszhangyukun I think we can define a `controllerContext` just like Kubernetes does: https://github.com/kubernetes/kubernetes/blob/cc6f12583f2b611e9469a6b2e0247f028aae246b/cmd/kube-controller-manager/app/controllermanager.go#L311
> 
> Then we can add a `setup` function for each controller, like https://github.com/kubernetes/kubernetes/blob/cc6f12583f2b611e9469a6b2e0247f028aae246b/cmd/kube-controller-manager/app/controllermanager.go#L401

I got it! I will implement this function as soon as possible

**Comment by Garrybest** [comment]
I think the `karmada-agent` also needs this enhancement.

**Comment by RainbowMango** [comment]
Agree, we might introduce more controllers to `karmada-agent`.
I'll file another issue to track it.

**Comment by RainbowMango** [comment]
> Agree, we might introduce more controllers to `karmada-agent`. I'll file another issue to track it.

Filed #1127 for tracking the tasks.
