### ISSUE TITLE
Why should we separate the sync mode into pull mode and push mode?

### ISSUE THREAD

**Issue by paulzhn** [karmada-io/karmada#1088]
**Please provide an in-depth description of the question you have**:

Running the `kubectl get cluster`, and it can be known that the clusters have two modes: pull and push. And in `pkg/apis/cluster/v1alpha1/types.go`, it can be known that the main difference between two modes. However, I am wondering that what's the criterion I should consider when I choose the sync mode, and what's the main difference between two modes in practice?

**What do you think about this question?**:

**Environment**:
- Karmada version: master
- Kubernetes version: 1.21
- Others:

**Comment by RainbowMango** [comment]
Good question. We do need a document to explain it by the way.

For quick answer, for the `push` mode cluster, Karmada directly operates it's `kube-apiserver` to manage workloads, but for `pull` mode cluster, the workloads are deployed by `karmada-agent`.

**Comment by lonelyCZ** [comment]
I think the `pull` mode have following functions:
1. Reducing the karmada control plane pressure.
2. It can be used to the environment that single side network communication from member cluster to karmada control plane.

**Comment by RainbowMango** [comment]
I'm adding a document about this by #1173, this issue will be closed after that.
Thanks for reaching us @paulzhn though.
