### ISSUE TITLE
Bump CI base Kubernetes from v1.20 to v1.21

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1089]
**Task description**:
For now, we are using Kubernetes@v1.20 in our CI process. 
We are going to update the base Kubernetes from v1.20.7 to v1.21.1.

**Solution**:
This involves very few changes, like:
```diff
diff --git a/hack/local-up-karmada.sh b/hack/local-up-karmada.sh
index 1ecfe5bc..0f64753d 100755
--- a/hack/local-up-karmada.sh
+++ b/hack/local-up-karmada.sh
@@ -23,7 +23,7 @@ MEMBER_CLUSTER_2_NAME=${MEMBER_CLUSTER_2_NAME:-"member2"}
 PULL_MODE_CLUSTER_NAME=${PULL_MODE_CLUSTER_NAME:-"member3"}
 HOST_IPADDRESS=${1:-}

-CLUSTER_VERSION=${CLUSTER_VERSION:-"kindest/node:v1.20.7"}
+CLUSTER_VERSION=${CLUSTER_VERSION:-"kindest/node:v1.21.1"}
 KIND_LOG_FILE=${KIND_LOG_FILE:-"/tmp/karmada"}

 #step0: prepare
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by XiShanYongYe-Chang** [comment]
The associated solution PR #1095 has been merged, so close this issue.

/close
