### ISSUE TITLE
Enable `karmadactl get` to support pull mode.

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1091]
**What would you like to be added**:
If we don't consider that there is only single side network communication from member cluster to karmada control plane. We can enable  `karmadactl get` to support `pull mode`. There are two way to do this.

1. Using `--cluster-kubeconfig` and `--cluster-context`.
2. Add access secret of member cluster of `pull mode` to karmada control plane.

**Why is this needed**:
This command can be used with the `migrate` command, we also add a field that can check if the workload are managed by karmada through `karmadactl get`.

**Comment by RainbowMango** [comment]
I think after https://github.com/karmada-io/karmada/discussions/1077, we can get a better solution to achieve this.

**Comment by lonelyCZ** [comment]
> I think after #1077, we can get a better solution to achieve this.

Ok, expecting for it.
