### ISSUE TITLE
How to realize `Association` when propagating resources

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1100]
**Please provide an in-depth description of the question you have**:
There have been discussed in https://github.com/karmada-io/karmada/issues/627#issuecomment-902560272, but haven't realized.

It is benefited for propagating resources to multi clusters.

**What do you think about this question?**:
Perhaps, Built-in resources and CRD can be implemented separately.

**Comment by GitHubxsy** [comment]
@mrlihanbo  Working on `Association `features

**Comment by lonelyCZ** [comment]
> @mrlihanbo Working on `Association `features

Ok, thanks! :)
