### ISSUE TITLE
Add interpreter.ReviseReplica hook when create work

### ISSUE THREAD

**Issue by GodLoveMinch** [karmada-io/karmada#1111]
**What would you like to be added**:
Recently, I tried to work with ResourceInterpreterWebhook framework which is the new feature in karmada v0.10.0 .
I tried `InterpretReplica` hook, and it work fine for me , But I  found a problem with `ReviseReplica`. 
I cannt find any hook point to call `ReviseReplica`, both in karmada v0.10.0. & v0.10.1 , which like `InterpretReplica ` hook point 
 `ResourceInterpreter.GetReplicas(object) ... ` 

**Why is this needed**:
Now , I interperter my CR's replica and scheduled well, but Karmada Work.workload.manifests replicas cannt be revised so that replica cannot be divided in member cluster. 

Should add  `ReviseReplica` hook point in function `ensureWork` ?

**Comment by RainbowMango** [comment]
@GodLoveMinch Thanks for reaching us and giving us feedback.

Yes, the `ResourceInterpreterWebhook` framework only implemented `InterpretReplica` and `Retain` hooks.  We are looking forward to feedback and then deciding which one is the next.

> Should add ReviseReplica hook point in function ensureWork ?

It's reasonable to me. Are you willing to help to implement it? 
Maybe we can discuss the details before starting.

**Comment by iawia002** [comment]
/assign

I will implement the `ReviseReplica` hook
