### ISSUE TITLE
Use github package to host container images

### ISSUE THREAD

**Issue by kevin-wangzefeng** [karmada-io/karmada#112]
**What would you like to be added**:
Github package now offers container images hosting, we can upload container images of karmada components to github package

**Why is this needed**:

**Comment by RainbowMango** [comment]
Refer to https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by RainbowMango** [comment]
/close
As we now use DockerHub to host both the `latest` and `released` images.
