### ISSUE TITLE
Run karmada-interpreter-webhook-example in CI

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1136]
**What would you like to be added**:
The [karmada-interpreter-webhook-example](https://github.com/karmada-io/karmada/tree/master/examples) was used to give an example about how to implement webhooks, and on the other hand, we also want it running in CI testing.

But no ideas about how to deploy it in our E2E testing yet.

**Why is this needed**:
We have implemented `InterpretReplica` and `Retain` [operations ](https://github.com/karmada-io/karmada/blob/98390f5615e0263da00a84b16588319752b893dc/pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go#L71-L108)at v0.10 release, but the testing still missing for now, without the E2E it will slow down the iterate frequency.

**Comment by lonelyCZ** [comment]
I am just interested in `interpreter` workflow, I would like to do it.

/assign

**Comment by lonelyCZ** [comment]
I consider the test processes is below:

1. In `hack/run-e2e.sh`, creating `work` crd in `karmada-apiserver` and all member clusters, deploying `karmada-interpreter-webhook-example` in host cluster.
2. In `test/e2e/resourceinterpreter_test.go`, testing `InterpretReplica`, `Retain` and `ReviseReplica` by distributing `workload` CR. And adding tests case if there will be new interpret functions.

How do you think? @RainbowMango

**Comment by RainbowMango** [comment]
I haven't really thought about it.

Things what we have to do for the environment might include:
- Deploy the [Workload CRD](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml) to karmada-apiserver and propagate it to all member clusters(by a ClusterPropagationPolicy).
- Deploy the [karmada-interpreter-webhook-example](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml) to host cluster
- Deploy the [webhook-configuration](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/webhook-configuration.yaml) to karmada-apiserver

Things what we have to do for the test might include:
- Create the `Workload CR` and propagate it to member clusters
- For the `retain`, we might have to update the `.spec.paused` fields and expect the fielded can be `retained`.
- For the `InterpretReplica`, we might have to check if the replicas resource requirement be `interpreted` correctly? (Not sure).
- For the `ReviseReplica `, we might have to split its replicas among member clusters, just like what we did on deployment.

**Comment by RainbowMango** [comment]
Yes, for the environment preparation, we can do that in `hack/run-e2e.sh`, but can we introduce another script for not coupling so much?

Yes, we might have to add some documentation for how to [the example](https://github.com/karmada-io/karmada/tree/master/examples), for people to deploy it and try it on their clusters.

**Comment by lonelyCZ** [comment]
> Things what we have to do for the environment might include:
> 
> * Deploy the [Workload CRD](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml) to karmada-apiserver and propagate it to all member clusters(by a ClusterPropagationPolicy).
> * Deploy the [karmada-interpreter-webhook-example](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml) to host cluster
> * Deploy the [webhook-configuration](https://github.com/karmada-io/karmada/blob/master/examples/customresourceinterpreter/webhook-configuration.yaml) to karmada-apiserver
> 
> Things what we have to do for the test might include:
> 
> * Create the `Workload CR` and propagate it to member clusters
> * For the `retain`, we might have to update the `.spec.paused` fields and expect the fielded can be `retained`.
> * For the `InterpretReplica`, we might have to check if the replicas resource requirement be `interpreted` correctly? (Not sure).
> * For the `ReviseReplica `, we might have to split its replicas among member clusters, just like what we did on deployment.

Ok, I will firstly implement a version according to these processes.

> Yes, for the environment preparation, we can do that in hack/run-e2e.sh, but can we introduce another script for not coupling so much?

Got it.

> Yes, we might have to add some documentation for how to the example, for people to deploy it and try it on their clusters.

Ok, I will add it.
