### ISSUE TITLE
Two questions about binding process

### ISSUE THREAD

**Issue by BDXGD** [karmada-io/karmada#1140]
**Please provide an in-depth description of the question you have**:

1. When resource looks for an appropriate `propagationPolicy`, the existing priority comparison plan is lexicographical order. Is this reasonable?

2. According to the existing logic, for the same resource, except for the `propagationPolicy` with the smallest lexicographic order, no other propagationPolicy will have any effect. Furthermore, if the `propagationPolicy` with the smallest lexicographic order can't find the corresponding `overridePolicy`, then it will always be pending, even if the `propagationPolicy` with larger lexicographic order can find the `overridePolicy`.

**Comment by RainbowMango** [comment]
> When resource looks for an appropriate propagationPolicy, the existing priority comparison plan is lexicographical order. Is this reasonable?

The alphabetical order guarantees the dedicated Propogation would be selected no matter how many times doing the match.
This is the protection of people misconfigured PropagationPolicy.

**Comment by RainbowMango** [comment]
For the question `2`, can you give an example to show the problem?

**Comment by BDXGD** [comment]
Is there such a possibility? The user created a `propagation` named `aaa` a long time ago, and now creates a `propagation` named `bbb`, and fills in a newly created `override` in its `dependentOverrides` field, and then keeps pending.

This means that, for the same resource, only the propagation with the **smallest lexicographic order** can be matched, and other propagations will never have any effect.

**Comment by GitHubxsy** [comment]
> Is there such a possibility? The user created a `propagation` named `aaa` a long time ago, and now creates a `propagation` named `bbb`, and fills in a newly created `override` in its `dependentOverrides` field, and then keeps pending.
> 
> This means that, for the same resource, only the propagation with the **smallest lexicographic order** can be matched, and other propagations will never have any effect.
 
The minimum lexicographic order is not the best solution. The priority configuration solution can't solve the problem you're talking about.  Do you have a good idea?

**Comment by GitHubxsy** [comment]
> The priority configuration solution

 The priority configuration solution indicates that a priority is configured for an override policy. The override policy with a higher priority is preferentially used.

**Comment by BDXGD** [comment]
> > Is there such a possibility? The user created a `propagation` named `aaa` a long time ago, and now creates a `propagation` named `bbb`, and fills in a newly created `override` in its `dependentOverrides` field, and then keeps pending.
> > This means that, for the same resource, only the propagation with the **smallest lexicographic order** can be matched, and other propagations will never have any effect.
> 
> The minimum lexicographic order is not the best solution. The priority configuration solution can't solve the problem you're talking about. Do you have a good idea?

The current solution by Karmada is to remind users to create corresponding `overrides` through `klog`.

When the `Propogation` with the lowest lexicographic order is selected but there is no corresponding override, the log will be used to remind the user that the user needs to pay attention.

If Karmada wants to configure a dedicated `Propogation` for each resource, I haven't thought of a better solution, and I think there should be no users who create multiple `Propogation` for a resource template.

**Comment by BDXGD** [comment]
> > When resource looks for an appropriate propagationPolicy, the existing priority comparison plan is lexicographical order. Is this reasonable?
> 
> The alphabetical order guarantees the dedicated Propogation would be selected no matter how many times doing the match. This is the protection of people misconfigured PropagationPolicy.

I think `alphabetical order` does not mean `dedicated Propogation`, what if the user mistakenly creates a `Propogation` smaller than the one with smallest alphabetical order?

**Comment by RainbowMango** [comment]
How about giving an example to reproduce the issue we are talking about?

**Comment by BDXGD** [comment]
> > When resource looks for an appropriate propagationPolicy, the existing priority comparison plan is lexicographical order. Is this reasonable?
> 
> The alphabetical order guarantees the dedicated Propogation would be selected no matter how many times doing the match. This is the protection of people misconfigured PropagationPolicy.

I can’t understand this sentence. If the user currently matches the `PropagationPolicy` named `bbb` with a certain resource template, if a `PropagationPolicy` named `aaa` is now initialized (misconfigured), then the resource will be bound to `aaa`.

IMO, if we want to achieve **the protection of people misconfigured PropagationPolicy**, we can limit a resource to only match one `PropagationPolicy`.

![image](https://user-images.githubusercontent.com/47907508/147212460-17f16f53-e9f4-4000-b37a-f78a4b73f949.png)

**Comment by GitHubxsy** [comment]
> > > Is there such a possibility? The user created a `propagation` named `aaa` a long time ago, and now creates a `propagation` named `bbb`, and fills in a newly created `override` in its `dependentOverrides` field, and then keeps pending.
> > > This means that, for the same resource, only the propagation with the **smallest lexicographic order** can be matched, and other propagations will never have any effect.
> > 
> > 
> > The minimum lexicographic order is not the best solution. The priority configuration solution can't solve the problem you're talking about. Do you have a good idea?
> 
> The current solution by Karmada is to remind users to create corresponding `overrides` through `klog`.
> 
> When the `Propogation` with the lowest lexicographic order is selected but there is no corresponding override, the log will be used to remind the user that the user needs to pay attention.
> 
> If Karmada wants to configure a dedicated `Propogation` for each resource, I haven't thought of a better solution, and I think there should be no users who create multiple `Propogation` for a resource template.

In the initial design, policy was shared, not exclusive designated deployment. For example, policy resourceselector is set to a label, and any resource object such as the Deployment will be matched and distributed to the same cluster if there has same label. 

If users can provision policy in advance, using karmada the same as single cluster k8s.

**Comment by XiShanYongYe-Chang** [comment]
Close this issue first, feel free to reopen it if you have more related question.

/close
