### ISSUE TITLE
install with local-up-karmada.sh, cannot be deleted with delete-cluster.sh

### ISSUE THREAD

**Issue by leonharetd** [karmada-io/karmada#1141]
**What happened**:
I use local-up-karma.sh to test, then I want to recycle resources, I found delete-cluste.sh.
When I use it to delete a cluster. such as member1, I use it to delete a cluster, an error is returned.
```shell
hack/delete-cluster.sh member1 /root/.kube/karmada.config
>>> error: cannot rename the context "member1", it's not in /root/.kube/karmada.config
```
when i used "kubectl config use-context member1" first
hack/delete-cluster.sh member1 /root/.kube/karmada.config is work.
also
https://github.com/karmada-io/karmada/blob/b57b7235044fea6ecec4b5ed7907ae0dcef582ab/hack/util.sh#L137
the next time I come in, I find that kind can't find it.

**What you expected to happen**:
First I can delete the cluster correctly
Second I can use kind correctly, or guide me for adding a directory to my PATH
**How to reproduce it (as minimally and precisely as possible)**:
```shell
git clone https://github.com/karmada-io/karmada
cd karmada
hack/local-up-karmada.sh
```
Execute the kind command
Execute hack/delete-cluster.sh
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by leonharetd** [comment]
I can try to fix it

**Comment by RainbowMango** [comment]
Thanks, please cc me and @lfbear after you file the PR.

**Comment by RainbowMango** [comment]
Let's back to this original issue. You want use `hack/delete-cluster.sh` to remove the cluster created by `hack/local-up-karmada.sh`? right?

**Comment by RainbowMango** [comment]
> the next time I come in, I find that kind can't find it.

Sorry I can't get it. what do you mean `next time I come in`? and kind can't find `what`?

**Comment by leonharetd** [comment]
Maybe I complicated the problem, I use hack/delete-cluster.sh one by one to delete clusters by name. Then I want to add a batch deletion. to remove the cluster created by hack/local-up-karmada.sh. Later, I want to delete all the created by kind and added to Karada

**Comment by leonharetd** [comment]
> > the next time I come in, I find that kind can't find it.
> 
> Sorry I can't get it. what do you mean `next time I come in`? and kind can't find `what`?

Re entering the terminal，Kind command not found. ps: I didn't install `kind` before

**Comment by RainbowMango** [comment]
The `hack/delete-cluster.sh` is paired with `hack/create-cluster.sh`, it definitely can remove the cluster created by `hack/local-up-karmada.sh`, but each time it only removes one cluster. 

And the `hack/delete-cluster.sh` not designed for deleting multi-clusters.

**Comment by RainbowMango** [comment]
> Re entering the terminal，Kind command not found. ps: I didn't install kind before

Confused. The `hack/local-up-karmada.sh` will help you install kind by default.

**Comment by leonharetd** [comment]
> > Re entering the terminal，Kind command not found. ps: I didn't install kind before
> 
> Confused. The `hack/local-up-karmada.sh` will help you install kind by default.

Installation is OK, but `$Path` without `kind` bin

**Comment by leonharetd** [comment]
> The `hack/delete-cluster.sh` is paired with `hack/create-cluster.sh`, it definitely can remove the cluster created by `hack/local-up-karmada.sh`, but each time it only removes one cluster.
> 
> And the `hack/delete-cluster.sh` not designed for deleting multi-clusters.

I see. I'll restore this
