### ISSUE TITLE
Enable `karmada-aggregated-apiserver` installation by helm

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1147]
**What would you like to be added**:
The #1122 introduced the `karmada-aggregated-apiserver` component which is the mandatory component to the Karmada control plane, so it should be included in charts.

**Why is this needed**:

/assign @algebra2k @jrkeen 
Can you guys help with it? We are going to cut the new release by the end of this month, sorry for the short notice.
Please let me know if you have any questions.

**Comment by jrkeen** [comment]
I will do it.

**Comment by RainbowMango** [comment]
Appreciate!!!

**Comment by RainbowMango** [comment]
@jrkeen What's the progress now? Can we finish it by this Wednesday?

**Comment by jrkeen** [comment]
> @jrkeen What's the progress now? Can we finish it by this Wednesday?

Yes, I will finish it tonight.
