### ISSUE TITLE
Can't directly tell whether the deployment has been dropped from the workqueue.

### ISSUE THREAD

**Issue by BDXGD** [karmada-io/karmada#1151]
**Please provide an in-depth description of the question you have**:

A deploy will requeue if no `propagation` is found, and will be dropped after trying `maxRetries` times. But it will behave the same before and after the drop by using `kubectl get deploy`:

![bf641b8811d1e050e15c783dfa5091e](https://user-images.githubusercontent.com/47907508/147108431-a2aeb124-2d18-43bb-bc4f-5f7a3d1d70dc.png)

The user can only judge whether deploy has been dropped by checking the log, which is a bit troublesome.

For example, when the deployment is successfully created, it is found that there is no suitable `propagation` to match it (it may also be because the matched `propagation` has not created an `override`). After the problem is solved, the user finds that `rb` is still not generated, which will cause confusion.. Finally found that because of too many attempts, deploy has been dropped from the workqueue.

**Comment by GitHubxsy** [comment]
The label of deployment is not labeled with policy, indicating that the deployment does not match. If the rb is not generated , there is an event generated. There is an application creation state and running state of each cluster on rb.

**Comment by BDXGD** [comment]
There is no `rb` may not be because of the label, it may be because the `override` of `Propagation` dependency has not been created, my idea is to let the `detector` watch `override`. #1162

**Comment by XiShanYongYe-Chang** [comment]
As you analyzed, the reason for the failure here is that the dependent ovierrdes were not created for a long time, resulting in a synchronization failure. This failure occurred repeatedly and eventually led to its abandonment. However, if there is no PropagationPolicy created, it will not cause a failure. Therefore, we recommend preparing an OverridePolicy in advance.

I plan to close it first. Please feel free to reopen it if you think it is necessary.
/close
