### ISSUE TITLE
如何在api-server 中运行crd呢？

### ISSUE THREAD

**Issue by isloveh** [karmada-io/karmada#1159]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Please provide an in-depth description of the question you have.

**Comment by isloveh** [comment]
我的应用场景是通过crd的交互方式创建PropagationPolicy, 通过kubebuilder 创建的crd 本地make run 测试通过，但是通过deployment 形式部署在api-server上，查看是没有创建对应的pod, 具体了解你们的架构，是在api-server中屏蔽了pod的创建，请问这个如何解决呢？

**Comment by RainbowMango** [comment]
> 但是通过deployment 形式部署在api-server上，

通过dep部署CRD？没理解你的场景。

**Comment by isloveh** [comment]
简单来说就是我定义了一个crd ，功能就是通过用户描述能够创建不同的PropagationPolicy 资源分发策略， 我想把这个crd以容器的行书部署在karmada-api-server中，目前的现象是不会拉起对应的pod，导致自定义资源逻辑不生效， 我不知道我的处理方式是不是正确的

**Comment by RainbowMango** [comment]
我理解你的CRD用于控制PropagationPolicy的创建，同时你有一个controller来reconcile CR源，你的controller用Deployment来运行。现在的问题是你把Deployment提交到karmada-apiserver，但这个deployment因不会创建pod而无法运行。对吧？

我个人认为，你的controller不应该部署在karmada-apiserver中，只是你的controller行为会操作`karmada-apiserver`。

**Comment by isloveh** [comment]
好的，明白了，谢谢您

**Comment by RainbowMango** [comment]
如果你们已经或准备在生产环境中使用Karmada，请联系我，karmada社区希望更更好的倾听用户声音。
/close

**Comment by isloveh** [comment]
好的，目前在技术演进阶段，准备上生产会联系您这边，获取的宝贵意见或者建议
