### ISSUE TITLE
Using Karmadactl to get cluster information fails, but using Kubectl to get cluster information succeeds

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#1171]
**What happened**:
Using `karmadactl` to get cluster information fails, but using `kubectl `to get cluster information succeeds
![image](https://user-images.githubusercontent.com/31329928/147429722-69b13f9e-89bc-4b27-bc25-a5eea4e7d56a.png)
I don't know what the reason is.

**Environment**:
- Karmada version: v0.10.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):v0.10.0
- Others:

**Comment by RainbowMango** [comment]
`karmadactl get` designed for `get` workloads from member clusters, and the `Cluster` is not supported.

I think this command might be ambiguous.

**Comment by 2hangchen** [comment]
> `karmadactl get` designed for `get` workloads from member clusters, and the `Cluster` is not supported.
> 
> I think this command might be ambiguous.

I see, so the only way to get `cluster` resource information is through `kubectl `or kube-apiserver?

**Comment by RainbowMango** [comment]
For now, yes. Get `Cluster` by `kubectl get` which gets it from `karmada-apiserver`.

**Comment by 2hangchen** [comment]
> For now, yes. Get `Cluster` by `kubectl get` which gets it from `karmada-apiserver`.

ok,thx
