### ISSUE TITLE
Default PropagationPolicy

### ISSUE THREAD

**Issue by iawia002** [karmada-io/karmada#1185]
**What would you like to be added**:

Introduce a default `PropagationPolicy` that matches all resources, and use it directly if the resource does not have a `PropagationPolicy` configured.

Or maybe we can also introduce `PropagationPolicy` priority.

**Why is this needed**:

The scenario is as follows: in many cases I need to distribute my resources to all clusters, but to configure `PropagationPolicy` every time is very tedious, if there is a default `PropagationPolicy` will be very convenient, this may also be able to achieve direct distribution of a helm application.

**Comment by RainbowMango** [comment]
>  in many cases I need to distribute my resources to all clusters, 

What's the exact use case we are talking about? Why users need that?

**Comment by RainbowMango** [comment]
We have considered this issue before, we named it `fully propagation` mode.
Haven't do it because:
- Not so clear the user cases are.
- Need a way to identify the resources between users and karmada-apiserver auto-generated?

**Comment by iawia002** [comment]
> > in many cases I need to distribute my resources to all clusters,
> 
> What's the exact use case we are talking about? Why users need that?

Not necessarily all clusters, but just need a default `PropagationPolicy` to describe which clusters to distribute to, many of our users will use the same policy to distribute resources to several clusters (just as today I create an application and distribute it to cluster A B with the same number of replicas, tomorrow I create a new application and need to use the same strategy), this time the default `PropagationPolicy` is very convenient, if when there is a separate need, you can create a separate `PropagationPolicy`.

> karmada-apiserver auto-generated?

Do we have such resources, like what? We can label such resources and make the default `PropagationPolicy` ignores such resources.

**Comment by GitHubxsy** [comment]
You want a propagation policy that can match any resource?

**Comment by iawia002** [comment]
> You want a propagation policy that can match any resource? For example：
> 
> ```
> apiVersion: policy.karmada.io/v1alpha1
> kind: PropagationPolicy
> metadata:
>   name: example-policy
>   namespace: default
> spec:
>   resourceSelectors:
>     - apiVersion: *
>       kind: *
>       name: *
>   placement:
>     clusterAffinity:
>       clusterNames:
>         - cluster1
>         - cluster2
> ```

It's not just global matching, it's about the priority, If I configure a single policy for a resource, which policy will be used? Can I know and control this clearly?

**Comment by GitHubxsy** [comment]
> 

If there are multiple policies that can match, we use lexicographic sorting. Priority is a good idea.

**Comment by iawia002** [comment]
@RainbowMango What do you think about `Priority`, is this a reasonable feature?

**Comment by RainbowMango** [comment]
What a pity we didn't talk about it at the meeting. 

Does the `priority` thing only act on `PP`/`CPP`?

**Comment by iawia002** [comment]
> What a pity we didn't talk about it at the meeting.

Yeah, totally forgot this issue.

> Does the `priority` thing only act on `PP`/`CPP`?

Yes, and it won't introduce breaking changes, if you don't set the `priority` value, everything will behave as it is now.

**Comment by Garrybest** [comment]
Agree, I hope this could be integrated into karmada.

**Comment by iawia002** [comment]
Community Meeting Summary: We now have two issues to be decided:

* Explicit or implicit priority
  * Explicit: The value of the priority field represents the final priority result
  * Implicit: The value of the priority field does not represent the final priority result, and needs to be combined with the degree of matching to determine, for example, the name matches exactly mean the highest priority
* What to do when a resource is rematched to a high priority policy

**Comment by jwcesign** [comment]
Explicit priority has been implemented, and this scenario is now covered with this configuration: https://github.com/karmada-io/karmada/issues/1185#issuecomment-1002599517
