### ISSUE TITLE
Use 'karmadactl init', "v1alpha1.cluster.karmada.io" not found

### ISSUE THREAD

**Issue by prodanlabs** [karmada-io/karmada#1204]
**What happened**:

```
I0102 04:26:49.722221 4144235 deploy.go:217] Update APIService 'v1alpha1.cluster.karmada.io'
F0102 04:26:49.724130 4144235 deploy.go:95] apiservices.apiregistration.k8s.io "v1alpha1.cluster.karmada.io" not found
```

Due to the change of CRD resources, the method of creating `v1alpha.clusterKarmada.io` should be `create` instead of `update`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by prodanlabs** [comment]
hi @RainbowMango
Can you update CRDs tarball and add an empty `v1alpha1.cluster.karmada.io`. I'll fix this later.

**Comment by RainbowMango** [comment]
> Can you update CRDs tarball and add an empty v1alpha1.cluster.karmada.io

Do you mean to add the following `APIService` yaml to crds.tar.gz of v1.0.0 release?
https://github.com/karmada-io/karmada/blob/1d166b6f354ac73fb6995f9518f7e7f065b43c12/artifacts/deploy/apiservice.yaml#L1-L16
