### ISSUE TITLE
Introduce cherry-pick tools 

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1210]
**What would you like to be added**:
- [x] : cherry-pick tooks, like [Kubernetes hack/cherry_pick_pull.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh)
- [x] : cherry-pick document at `docs/contributors/devel/cherry-picks.md`, like [this one](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md)

**Why is this needed**:

**Comment by jameszhangyukun** [comment]
I want to try two tasks /assign

**Comment by carlory** [comment]
@jameszhangyukun 

Sorry, I did not notice this issue, I have already submitted a related PR #1216 

/assign

**Comment by RainbowMango** [comment]
@jameszhangyukun Have you started this task?

**Comment by jameszhangyukun** [comment]
> @jameszhangyukun Have you started this task?

I just read https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh do not begin this task

**Comment by RainbowMango** [comment]
So, how do you want to move this issue forward? You can help review #1216 or submit a new PR, it's up to you.

@carlory Thanks for your contribution, but since this issue has been claimed by @jameszhangyukun , I need confirmation before moving your PR. Hope you can understand.

**Comment by jameszhangyukun** [comment]
> So, how do you want to move this issue forward? You can help review #1216 or submit a new PR, it's up to you.
> 
> @carlory Thanks for your contribution, but since this issue has been claimed by @jameszhangyukun , I need confirmation before moving your PR. Hope you can understand.

If he finish this issue.I think you can receive his PR.

**Comment by carlory** [comment]
@RainbowMango  @jameszhangyukun 

sorry, it's my mistake. I will be more careful next time.

**Comment by jameszhangyukun** [comment]
> @RainbowMango @jameszhangyukun
> 
> sorry, it's my mistake. I will be more careful next time.

It doesn't matter.

**Comment by RainbowMango** [comment]
@carlory Don't get me wrong, It's not your fault.

We are following the first-come-first-serve rule, all contributor's efforts are fully respected.

**Comment by RainbowMango** [comment]
Thanks @jameszhangyukun for your cooperation.
