### ISSUE TITLE
Deepcopy didn't generate 

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1220]
**What happened**:
The #704 introduced API change but without `deepcopy` update. This kind of mistake should be intercepted by [hack/verify-codegen.sh](https://github.com/karmada-io/karmada/blob/7323eadb18bf928e5bb5a44a190837bad44349dc/.github/workflows/ci.yml#L39), but seems it does not work as expected.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
$ hack/verify-codegen.sh
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.0.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others:

**Comment by RainbowMango** [comment]
@iawia002 Any idea?

**Comment by iawia002** [comment]
Strange, my local test results are normal, it fails as expected:

```diff
diff -Naupr hack/../pkg/apis/work/v1alpha2/zz_generated.deepcopy.go hack/../_tmp/pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
--- hack/../pkg/apis/work/v1alpha2/zz_generated.deepcopy.go	2022-01-07 10:07:05.000000000 +0800
+++ hack/../_tmp/pkg/apis/work/v1alpha2/zz_generated.deepcopy.go	2021-12-29 16:19:14.000000000 +0800
@@ -32,27 +32,6 @@ func (in *AggregatedStatusItem) DeepCopy
 }

 // DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
-func (in *BindingSnapshot) DeepCopyInto(out *BindingSnapshot) {
-	*out = *in
-	if in.Clusters != nil {
-		in, out := &in.Clusters, &out.Clusters
-		*out = make([]TargetCluster, len(*in))
-		copy(*out, *in)
-	}
-	return
-}
```

Let me do some research.

**Comment by iawia002** [comment]
I know what the problem is. In the GitHub Action environment, our code is not in the `GOPATH/src/github.com` directory, but the `deepcopy-gen` generates the code into the GOPATH directory, so the deep copy files in the current directory don't actually been updated.

I have fixed this, see https://github.com/karmada-io/karmada/runs/4734865346?check_suite_focus=true for the results.

/assign
