### ISSUE TITLE
failed to sync resource to member cluster

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#1222]
**What happened**:

E0107 05:21:56.594451       1 execution_controller.go:213] Failed to get resource xxx from member cluster, err is the informer of cluster(xxx) h
as not been initialized

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v0.10.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Does this error persist?

See the comment.
https://github.com/karmada-io/karmada/blob/b1a2914ed420a347f4bc33889a8ee1054d94eaf2/pkg/util/helper/cache.go#L34-L40
