### ISSUE TITLE
如何在k8s内部部署karmada

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#1232]
**看了karmada的启动脚本 都是对给定的一个k8s集群从外部进行部署karmada，有没什么方式可以在k8s集群内部部署karmada的？？**:

**What do you think about this question?**: 有官方开发者支持解答一下疑问吗

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Have you checked [Installing Karmada](https://github.com/karmada-io/karmada/blob/master/docs/installation/installation.md) document?

**Comment by SZT0728** [comment]
when  i use kubectl-karmada install karmada，the output failed message is follow:

I0111 13:59:09.146318  477525 deploy.go:217] Update APIService 'v1alpha1.cluster.karmada.io'
F0111 13:59:09.149806  477525 deploy.go:95] **apiservices.apiregistration.k8s.io "v1alpha1.cluster.karmada.io" not found**

how can fix this？？

**Comment by SZT0728** [comment]
Environment：kubectl-karmada is build from source code which tag is v1.0.0
k8s server version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**Comment by RainbowMango** [comment]
Oh, this is a bug that has been fixed by #1228.

I think you can re-build the `kubectl-karmada` with the latest code. Or, create the `APIService` below manually before run `kubectl-karmada init`:
https://github.com/karmada-io/karmada/blob/eb4b3e27bc9d080377b899ce251f49ce3f67fbd5/artifacts/deploy/apiservice.yaml#L1-L16

**Comment by RainbowMango** [comment]
cc @prodanlabs

**Comment by prodanlabs** [comment]
Yes, unfortunately, a karmadactl needs to be compiled manually.

**Comment by prodanlabs** [comment]
hi @RainbowMango 
Is it possible to add a karmadactl to the release page, what do you think?

**Comment by orangedeng** [comment]
I went into the same issue and I can't continue to install karmada after init failed.

**Comment by RainbowMango** [comment]
> hi @RainbowMango Is it possible to add a karmadactl to the release page, what do you think?

We can't do that even it will work. But we can cut a new release `v1.0.1` for this.

**Comment by prodanlabs** [comment]
> ll karmada after init failed.

you can compile the latest  karmadactl from source，you need a golang environment.
```
git clone https://github.com/karmada-io/karmada.git
cd karmada
make kubectl-karmada  
```

**Comment by SZT0728** [comment]
Yet i build kubectl-karmada from master:latest(eb4b3e27bc9d0) and use **kubectl karmada init**, it already install successful.
but  when i join a cluster into karmada，the output shows join successful,but when i get clusters the member READY status is false
the member cluster i use kind to create by this:**kind create cluster --name=k8s-cluster1 --image=kindest/node:v1.19.1 --kubeconfig=/root/.kube/k8s-cluster1.config**
and i join to karmada by this : 
`[root .kube]# kubectl karmada --kubeconfig /etc/karmada/karmada-apiserver.config  join ${MEMBER_CLUSTER_NAME} --cluster-kubeconfig=/root/.kube/k8s-cluster1.config
cluster(kind-k8s-cluster1) is joined successfully
[root .kube]# kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get clusters
NAME                VERSION   MODE   READY   AGE
kind-k8s-cluster1             Push   False   3m3s
`
how could resolve this?

**Comment by prodanlabs** [comment]
> 

What is the current-context of kubeconfig?
`cat /root/.kube/k8s-cluster1.config | grep current-context | sed 's/: /\n/g' | sed '1d'`

**Comment by RainbowMango** [comment]
That is probably because `karmada-controller-manager` can't access member cluster, I don't know where you installed Karmada, but please check the endpoint of the member cluster, by following command:
```
kubectl get clusters k8s-cluster1 -o jsonpath='{.spec.apiEndpoint}'
```
Or, you can describe the clusters to see the conditions/events:
```
kubectl describe clusters member1
```

We usually use `hack/create-cluster.sh` to create a kind cluster for testing, we'll [update the endpoint](https://github.com/karmada-io/karmada/blob/eb4b3e27bc9d080377b899ce251f49ce3f67fbd5/hack/create-cluster.sh#L95-L98) to deal with the network issues.

**Comment by SZT0728** [comment]
> > 
> 
> What is the current-context of kubeconfig? `cat /root/.kube/k8s-cluster1.config | grep current-context | sed 's/: /\n/g' | sed '1d'`

the karmada-scheduler's log show that 
**[core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-kind-k8s-cluster1:10352 karmada-scheduler-estimator-kind-k8s-cluster1:10352 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-kind-k8s-cluster1 on 10.1.0.10:53: no such host". Reconnecting...**
and i guess that the k8s-cluster1 is create by kind and run in docker，and the karmada running in k8s,maybe  because  they are not the same net spaces, so the karmada failed to connect k8s-cluster1，is  it？

**Comment by prodanlabs** [comment]
> 



> > > 
> > 
> > 
> > What is the current-context of kubeconfig? `cat /root/.kube/k8s-cluster1.config | grep current-context | sed 's/: /\n/g' | sed '1d'`
> 
> the karmada-scheduler's log show that **[core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-kind-k8s-cluster1:10352 karmada-scheduler-estimator-kind-k8s-cluster1:10352 0 }. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-kind-k8s-cluster1 on 10.1.0.10:53: no such host". Reconnecting...** and i guess that the k8s-cluster1 is create by kind and run in docker，and the karmada running in k8s,maybe because they are not the same net spaces, so the karmada failed to connect k8s-cluster1，is it？

`karmada-scheduler-estimator` is a non-essential component.You can look at the `karmada-controller-manager`  log
```
 kubectl -n karmada-system logs -f karmada-controller-manager-b954bdf4c-q77zp
```

**Comment by orangedeng** [comment]
I noticed that a new `host cluster` is **created** inside my current k8s cluster. I think we are looking to let the specific cluster to **become** the `host cluster`. Is there any way to do so?

**Comment by pigletfly** [comment]
You can try installing with helm

**Comment by RainbowMango** [comment]
/close
Hi @SZT0728 Thanks for reporting, If this issue still exist, please feel free to let us know.
