### ISSUE TITLE
Did karmada have a docker image and i can use docker run to start it?

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#1236]
**Did karmada has a docker image and i can use docker run to start it in a container? If not，any advices to build this image**:

**I think about Could I  use the base image dind(docker int docker)，and the ENTRYPOINT first install k8s，after that ，use **kubectl-karmada** to install karmada**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Sorry, I can't get what you mean. Is it the same thing that #1228 trying to do?

**Comment by SZT0728** [comment]
> Sorry, I can't get what you mean. Is it the same thing that #1228 trying to do?

it looks like the same thing. i want to karmada run in docker . even thouth i want to kubectl apply -f karmada-rs.yaml  to run multi pod, inside each pod run the karmada. May I have some information about it？

**Comment by GitHubxsy** [comment]
> > Sorry, I can't get what you mean. Is it the same thing that #1228 trying to do?
> 
> yeah ，it looks like the same thing. i want to karmada run in docker . even thouth i want to kubectl apply -f karmada-rs.yaml to run multi pod, inside each pod run the karmada. May I have some information about it？

Can you describe in detail the scenario you're facing? Your request seems a little strange.

**Comment by SZT0728** [comment]
> Can you describe in detail the scenario you're facing? Your request seems a little strange.

like the kind (k8s in docker), i want the image karmada in docker.
for example, the docker image names karmada:v1.0. and i type: docker run -itd --name karmada-instance  -p 5443:5443   karmada:v1.0。   so i  can use  karmada-instance  to manager multi k8s.

**Comment by SZT0728** [comment]
> > Can you describe in detail the scenario you're facing? Your request seems a little strange.
> 
> i'm sorry for what describe,maybe it's pool.
like the kind (k8s in docker), i want the image karmada in docker. for example, the docker image names karmada:v1.0. and i type: docker run -itd --name karmada-instance -p 5443:5443 karmada:v1.0。 so i can use karmada-instance to manager multi k8s.

**Comment by GitHubxsy** [comment]
> > > Can you describe in detail the scenario you're facing? Your request seems a little strange.
> > 
> > 
> > i'm sorry for what describe,maybe it's pool.
> > like the kind (k8s in docker), i want the image karmada in docker. for example, the docker image names karmada:v1.0. and i type: docker run -itd --name karmada-instance -p 5443:5443 karmada:v1.0。 so i can use karmada-instance to manager multi k8s.

Karmada contains many components such as Karmada-apiserver, karmada-controller, and karmada-schduler. You are not advised to package them in one image.

Kind schematic diagram：
![kind](https://user-images.githubusercontent.com/11901080/149074924-811e816d-218f-46bf-a817-3c0158f83924.png)

**Comment by SZT0728** [comment]
> Kind schematic diagram

thank you for your reply.
karmada support multi-user mode which users are isolated from each other?
(是否支持多用户，然后用户之间彼此是互相隔离)

**Comment by lonelyCZ** [comment]
> karmada support multi-user mode which users are isolated from each other? (是否支持多用户，然后用户之间彼此是互相隔离)

I think so, you can use native RBAC of k8s to implement `multi-user` mode.

**Comment by RainbowMango** [comment]
/close
Feel free to re-open if you have further questions.
