### ISSUE TITLE
[docs]specify the cluster name restriction in join command

### ISSUE THREAD

**Issue by orangedeng** [karmada-io/karmada#1243]
When I was joining new cluster with the karmada [docs](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md);

> Join cluster with name `member1` to Karmada by using the following command.

I got following error in response

```
Error: failed to get joining cluster config. error: context "member1" does not exist
```

After I change the cluster name with `default`, which is the same as the cluster in my cluster kubeconfig, the cluster can be joined. I think this restriction should be in the docs.

**Comment by RainbowMango** [comment]
> Maybe you have to specify the context if there are more than one contexts in kubeconfig file:
> kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --karmada-context=karmada \
--cluster-kubeconfig=<member1 kubeconfig> --cluster-context=member1

Have you noticed the words at [register cluster by CLI](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md#register-cluster-by-cli)?

**Comment by RainbowMango** [comment]
It's not clear enough, I'll make an update on that.

/remove-kind good-first
/assign

**Comment by orangedeng** [comment]
If the `--karmada-context=karmada` parameters is required when I have multiple context in my cluster kubeconfig, I should not be able to join the cluster with cluster name `default` and the error logs should tell me that my cluster kubeconfig has multiple context.

In the other hand, I have my `current-context` settings in my cluster config. This should imply that I am adding the cluster from the `current-context` setting specifies.

**Comment by RainbowMango** [comment]
> In the other hand, I have my current-context settings in my cluster config. This should imply that I am adding the cluster from the current-context setting.

Yes, exactly.

**Comment by orangedeng** [comment]
> > In the other hand, I have my current-context settings in my cluster config. This should imply that I am adding the cluster from the current-context setting.
> 
> Yes, exactly.

So the cluster name `member1` **should not** be restricted to the context name in my cluster config without `cluster-context` parameter, do you agree?

**Comment by RainbowMango** [comment]
Do you mean the `--cluster-context` should not default to `cluster-name`(registering), and should take the `current-context`?

https://github.com/karmada-io/karmada/blob/2060616c4a9084e55feeee154738cbbc69a32e2f/pkg/karmadactl/join.go#L114-L117

**Comment by orangedeng** [comment]
> Do you mean the `--cluster-context` should not default to `cluster-name`(registering), and should take the `current-context`?
> 
> https://github.com/karmada-io/karmada/blob/2060616c4a9084e55feeee154738cbbc69a32e2f/pkg/karmadactl/join.go#L114-L117

Yes. I think both `cluster-name as context name` and `current-context` way are acceptable but the rule must be written in docs.

**Comment by RainbowMango** [comment]
That makes sense.
