### ISSUE TITLE
[Proposal] caching member cluster resources 

### ISSUE THREAD

**Issue by huntsman-li** [karmada-io/karmada#1245]
**What would you like to be added**:

Caching member cluster resources

Scenarios:
- Global resource access/search (multi-cluster/cross-regional cluster)
- Global application view (multi-cluster application)
- Unified multi-cluster resource entry (for dashboard/cli)

**Why is this needed**:

- Accelerate (cross-regional) resource access
- High-frequency kubernetes resource access
- Aggregate multi-cluster resources

**Comment by RainbowMango** [comment]
What an awesome proposal I would say! It fits perfectly with Karmada's roadmap.

Thanks, @huntsman-li, and would like to share your idea in more detail at the community meeting?  Feel free to add an agenda to  [meeting agenda](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).

**Comment by huntsman-li** [comment]
Yes, I‘d like to. I added an agenda.
