### ISSUE TITLE
[Good First] Modify log type to Error when err ocurs

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1247]
**Task description**:

In file `pkg/scheduler/scheduler.go`:

https://github.com/karmada-io/karmada/blob/2060616c4a9084e55feeee154738cbbc69a32e2f/pkg/scheduler/scheduler.go#L533

Modify log type to Error when err occurs.

**Solution**:

```diff
--- a/pkg/scheduler/scheduler.go
+++ b/pkg/scheduler/scheduler.go
@@ -530,7 +530,7 @@ func (s *Scheduler) scheduleResourceBinding(resourceBinding *workv1alpha2.Resour
        }
        scheduleResult, err := s.Algorithm.Schedule(context.TODO(), &placement, &resourceBinding.Spec)
        if err != nil {
-               klog.V(2).Infof("Failed scheduling ResourceBinding %s/%s: %v", resourceBinding.Namespace, resourceBinding.Name, err)
+               klog.Errorf("Failed scheduling ResourceBinding %s/%s: %v", resourceBinding.Namespace, resourceBinding.Name, err)
                return err
        }
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
`ErrorS` or `Errorf`? We haven't supported structured logs.

**Comment by XiShanYongYe-Chang** [comment]
> `ErrorS` or `Errorf`? We haven't supported structured logs.

Use `Errorf` first, and then change it to `ErrorS` globally.
