### ISSUE TITLE
FailoverSchedule support spread constraints

### ISSUE THREAD

**Issue by Chenhb123** [karmada-io/karmada#1258]
**Please provide an in-depth description of the question you have**:
I have recently been testing karmada's ability to distribute randomly in a multi-cluster environment, which I had achieved by setting spread Constraints, like this:
```bash
# export KUBECONFIG=/root/.kube/karmada.config
# kubectl get clusters
NAME                             VERSION   MODE   READY   AGE
kubernetes-admin-10-10-176-223   v1.19.4   Push   True    2d
member1                          v1.21.1   Push   True    2d
member2                          v1.21.1   Push   True    2d
member3                          v1.21.1   Pull   True    2d
# cat failover.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    spreadConstraints:
      - maxGroups: 1
        minGroups: 1
    replicaScheduling:
      replicaSchedulingType: Duplicated
# kubectl apply -f failover.yaml
# karmadactl get deploy | grep nginx
nginx   kubernetes-admin-10-10-176-223   2/2     2            2           47h   Y
```
It works very well for me,Out of curiosity, I went to see the implementation of the source code:
```go
// pkg/scheduler/core/generic_scheduler.go 128
func (g *genericScheduler) selectClusters(clustersScore framework.ClusterScoreList, spreadConstraints []policyv1alpha1.SpreadConstraint, clusters []*clusterv1alpha1.Cluster) []*clusterv1alpha1.Cluster {
	defer metrics.ScheduleStep(metrics.ScheduleStepSelect, time.Now())

	if len(spreadConstraints) != 0 {
		return g.matchSpreadConstraints(clusters, spreadConstraints)
	}

	return clusters
}
```
There's nothing wrong with that, but when I look at the details of the FailoverSchedule method, I notice this comment：
```go
// pkg/scheduler/core/generic_scheduler.go 289
// TODO: check if the final result meets the spread constraints.
	targetClusters := reservedClusters
	clusterList := candidateClusters.List()
	for i := 0; i < deltaLen && i < len(candidateClusters); i++ {
		targetClusters.Insert(clusterList[i])
	}
```
This seems to say that failover across clusters has not yet added spread Constraints related support.
**What do you think about this question?**:
I would like to know if failover across the cluster is already supported for Spread Constraints and if not, is it already in the development plan of the project? I look forward to hearing from you.😬
**Environment**:
- Karmada version:
```bash
# karmadactl version
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version:
```bash
# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:45Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

**Comment by huone1** [comment]
the failover scheduler Miss some shceduling process, such as Spread Constraints, ReplicaScheduling for now;
the **rescheduleResourceBinding** should be integrated into the normal scheduling process **scheduleResourceBinding** .
the **Failover** just is a  condition for triggering the scheduling process, and shouldn't create another process shceduling process.

**Comment by Chenhb123** [comment]
> 

Thank you very much for your reply.I would also like to know if support for scheduling based on cluster resource margin has been included in the  recent plan,like this:
![image](https://user-images.githubusercontent.com/31341363/149446754-6a35d580-436a-4a5f-85cd-f71f3eae91a3.png)

**Comment by dddddai** [comment]
> is it already in the development plan of the project?

Yes this would be fixed by [the commit](https://github.com/karmada-io/karmada/pull/1049/commits/a08dd3d7675b008e5e4137f44843d76880d454b3) in #1049

BTW the spread constraints would only work with `replicaSchedulingType: Duplicated` currently
