### ISSUE TITLE
docker pull dashboard image failed

### ISSUE THREAD

**Issue by merryzhou** [karmada-io/karmada#1259]
**What happened**:
docker pull karmada-scheduler image works well, but "docker pull swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-dashboard:latest" failed with response:

Error response from daemon: Get https://swr.ap-southeast-1.myhuaweicloud.com/v2/karmada/karmada-dashboard/manifests/latest: denied: You may not login yet

**Comment by RainbowMango** [comment]
Thanks for giving us feedback.  I forgot to public the image, and it's ok now. Please try again.

**Comment by merryzhou** [comment]
it's ok now, Thanks
