### ISSUE TITLE
resource status aggregating slow down due to informer resync

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#1260]
**What happened**:
When the clusters are large-scale, there are many workloads in karmada-control-plane. The controller may have a perf issue. 

Here is what I found:

The status aggregation is too slow every 10 hours, because the controller-runtime will resync all bindings by default. See [here](https://github.com/kubernetes-sigs/controller-runtime/blob/45b13b951f7761f4cb5035e86e706545eb71c60a/pkg/cache/cache.go#L133).

**What you expected to happen**:
I have 2 methods to fix this problem.

1. Make resync period as an option, default 0, i.e., we will not resync any more by default.
2. Make concurrent reconciles as an option, default 1, i.e., we will process serially by default. If not adaptable, set it larger by args.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
/retitle resource status aggregating slow down due to informer resync

**Comment by RainbowMango** [comment]
> Make resync period as an option, default 0, i.e., we will not resync any more by default.

+1

> Make concurrent reconciles as an option, default 1, i.e., we will process serially by default. If not adaptable, set it larger by args.

+1

We can fix this bug first(not introduce the options) then port to release-1.0.

**Comment by RainbowMango** [comment]
/assign @Garrybest 
As you sent the @1265
