### ISSUE TITLE
[GoodFirst] Fix documentation mistake of cluster registration

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1279]
**Task description**:
Update [Cluster Registration](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md#register-cluster-by-cli) that is when joining cluster, the `--cluster-kubeconfig` is mandatory, not the `--cluster-context`.

**Solution**:
```diff
-kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --karmada-context=karmada --cluster-context=member1
+kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --karmada-context=karmada --cluster-kubeconfig=<member1 kubeconfig>
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
@viniciuspietscher Thanks for taking this, appreciated!

**Comment by viniciuspietscher** [comment]
Hi @RainbowMango !

Thank you for the opportunity! Very excited to do my first pull request!
Please let me know on what I could improve!

**Comment by RainbowMango** [comment]
I don't know if you're familiar with the project yet, if not, maybe you can try the [QuickStart](https://github.com/karmada-io/karmada#quick-start) and after that, there are some documentations at [docs directory](https://github.com/karmada-io/karmada/tree/master/docs).

When you go through the documents, you might find some mistakes(most of the authors do not speak English), feel free to file a PR for it.

And, we are still missing a lot of documentation, but we're making slow progress. You can also help with it.

**Comment by viniciuspietscher** [comment]
I'm not very familiar with K8s but I am very interested to help and learn more!

**Comment by RainbowMango** [comment]
That's great! Please feel free to cc me if you have any questions.
Or, you can find me on [the slack channel #karmada](https://slack.cncf.io/) .
