### ISSUE TITLE
feature: add `karmada reset` commond to uninstall

### ISSUE THREAD

**Issue by zgfh** [karmada-io/karmada#1296]
**What would you like to be added**:
add `karmada reset` commond to uninstall 

my idea to uninstall :

1. check pod exist ,then backup and delete: 
 `kubectl -n karmada-system get all -o yaml  > xxx-backup.yaml && kubectl delete ns karmada-system
2. backup and delete dir `/etc/karmada`:
  `mv /etc/karmada /etc/karmada.back-xxx `

**Why is this needed**:
He will help the newcomer to clean up the installation when there is a problem, and install it again

**Comment by RainbowMango** [comment]
That makes sense. I discussed this issue with @prodanlabs before, but we gonna take `deinit` as the command name.

@prodanlabs Could you please share your ideas about how to achieve this feature?

**Comment by prodanlabs** [comment]
@RainbowMango Nice idea. No problem, I'll make a demo later.

**Comment by zgfh** [comment]
I find there is a pr will remove data when instanll https://github.com/karmada-io/karmada/pull/1455

I think it is dangerous, we should let user choice what should do 

Guide customers to uninstall with `karmadactl reset -f `？
