### ISSUE TITLE
Enable organization-wide two-factor authentication

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1300]
We are going to enable [two-factor authentication][1] in the karmada-io organization at the end of Jan 2022.

All members are required to [config two-factor authentication][2]. After the administrator requires the use of two-factor authentication for `karmada-io` organization, **members who do not use two-factor authentication will be removed from the organization`**.

Members who havn't enable TFA: 
- [ ] @574179870
- [x] @adamzhoul
- [ ] @AllenXL
- [ ] @cg-gaochao
- [x] @ChanceLi
- [x] @chenxianpao
- [ ] @cheyuexian
- [ ] @davkeor
- [x] @devadapter
- [x] @jhnine
- [ ] @jiangshantao-dbg
- [ ] @liuhewei
- [x] @lonelyCZ
- [x] @lynnsong
- [x] @oif
- [x] @prodanlabs
- [x] @snowplayfire
- [ ] @wangrenjie-jack
- [ ] @weibaohui
- [ ] @xuming68
- [ ] @zcc35357949
- [ ] @zoroyouxi

[1]: https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication
[2]: https://docs.github.com/en/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa/configuring-two-factor-authentication

**Comment by chenxianpao** [comment]
I have finished configuring two-factor authentication. @RainbowMango

**Comment by RainbowMango** [comment]
Thanks @chenxianpao, @kevin-wangzefeng will confirm that and check off the items above.

**Comment by prodanlabs** [comment]
I have finished configuring two-factor authentication.

**Comment by devadapter** [comment]
I have finished configuring two-factor authentication.

**Comment by lonelyCZ** [comment]
I also have finished configuring two-factor authentication.

**Comment by adamzhoul** [comment]
I also have finished configuring two-factor authentication.

**Comment by oif** [comment]
2FA enabled @RainbowMango

**Comment by snowplayfire** [comment]
I have finished configuring two-factor authentication. @RainbowMango

**Comment by jhnine** [comment]
I have finished configuring two-factor authentication.

**Comment by lynnsong** [comment]
I have finished configuring two-factor authentication.

**Comment by RainbowMango** [comment]
Kindly ping @574179870 @AllenXL @cg-gaochao @ChanceLi @cheyuexian @davkeor @jiangshantao-dbg @liuhewei @wangrenjie-jack @weibaohui @xuming68 @zcc35357949 @zoroyouxi

**Comment by ChanceLi** [comment]
2FA enabled. Sorry for late response. @RainbowMango

**Comment by RainbowMango** [comment]
Thanks @ChanceLi .

**Comment by kevin-wangzefeng** [comment]
Enabled 2FA organization wide, and sent invitation to add back following people removed by github.

@liuhewei
@AllenXL
@jiangshantao-dbg
@cheyuexian
@wangrenjie-jack
@xuming68
@zcc35357949
@weibaohui
@zoroyouxi
@574179870
@davkeor
@cg-gaochao
@duguhaotian
@jingxiaolu
@liufen90
@ylf881011
@jshachm
@yangcheng-icbc
@tinyma123
@zhaohaidan
@jing-rui
@RyanZhao10

Please feel free to reachout the maintainers if you missed the invitation.

**Comment by liuhewei** [comment]
2FA enabled, and rejoin the organization... [Twilio Authy desktop ](https://authy.com/guides/github/) is recommended if mobile app is not easy for you (just like me...)
