### ISSUE TITLE
ResourceBinding get reconciled multiple times

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#1309]
**What happened**:

When a ResourceBinding comes, detector  does reconcile https://github.com/karmada-io/karmada/blob/master/pkg/detector/detector.go#L942 to collect resource status, such as Deployment,Job, and binding_controller will also do the reconcile to sync work object and collect bindingStatus from work.So ResourceBinding objects get reconciled twice.I propose to reconcile ResourceBinding all in binding_controller, that is syncBinding > updateBindingStatus > updateResourceStatus > done.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by pigletfly** [comment]
we should move reconcile rb into resourcebinding_controller from detector

**Comment by RainbowMango** [comment]
Is it a bug?

**Comment by Garrybest** [comment]
I don't think so, it is just an optimization. @RainbowMango
