### ISSUE TITLE
Cannot delete cr in karmada

### ISSUE THREAD

**Issue by Chenhb123** [karmada-io/karmada#1325]
I used operator to deploy mongodb before, and recently I was testing whether karmada is compatible with mongodb operator.I first deployed crd, rbac and secret, and then deployed cr, everything went well, I successfully deployed mongodb to the corresponding cluster,After the test is done, I start to execute the delete command in karmada to clear the scene, unfortunately, the delete command was not executed successfully, but stuck there:
```bash
root@node5[percona-mgo]#
root@node5[percona-mgo]# kubectl delete -f cr.yaml
perconaservermongodb.psmdb.percona.com "my-cluster-name" deleted









```

**What happened**:
I waited for a long time and got no response,Hope to get a reply to this question.
**What you expected to happen**:
After the delete command is executed, the cr is successfully deleted instead of stopping there
**How to reproduce it (as minimally and precisely as possible)**:
You should only need to submit crd.yaml and crd-clusterpropagationpolicy.yaml and cr.yaml and cr-propagationpolicy.yaml respectively, and after the deployment is successful, execute `kubectl delete -f cr.yaml` to reproduce
**Anything else we need to know?**:
The contents of the cr file and crd file are shown in the following attachments:
[cr.txt](https://github.com/karmada-io/karmada/files/7948613/cr.txt)
[crd.txt](https://github.com/karmada-io/karmada/files/7948617/crd.txt)

The cr-propagationpolicy.yaml content and the crd-clusterpropagationpolicy.yaml content are given as follows:
```bash
root@node5[percona-mgo]# ll
total 36
-rw-r--r-- 1 root root   422 Jan 27 10:38 cr-propagationpolicy.yaml
-rw-r--r-- 1 root root 11214 Jan 27 10:04 cr.yaml
-rw-r--r-- 1 root root  1443 Jan 27 10:04 crd-clusterpropagationpolicy.yaml
-rw-r--r-- 1 root root 15642 Jan 27 10:28 crd.yaml
root@node5[percona-mgo]# cat cr-propagationpolicy.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mgo-cr-pp
  namespace: percona
spec:
  resourceSelectors:
    - apiVersion: psmdb.percona.com/v1
      kind: PerconaServerMongoDB
      name: my-cluster-name
      namespace: percona
  placement:
    clusterAffinity:
      clusterNames:
        - kubernetes-admin-10-10-176-223
    replicaScheduling:
      replicaSchedulingType: Duplicated
root@node5[percona-mgo]# cat crd-clusterpropagationpolicy.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: mgo-crd-cpp
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Namespace
      name: percona
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: perconaservermongodbs.psmdb.percona.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: perconaservermongodbbackups.psmdb.percona.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: perconaservermongodbrestores.psmdb.percona.com
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      name: percona-server-mongodb-operator
      namespace: percona
    - apiVersion: v1
      kind: ServiceAccount
      name: percona-server-mongodb-operator
      namespace: percona
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      name: service-account-percona-server-mongodb-operator
      namespace: percona
    - apiVersion: apps/v1
      kind: Deployment
      name: percona-server-mongodb-operator
      namespace: percona
    - apiVersion: v1
      kind: Secret
      name: my-cluster-name-secrets
      namespace: percona
  placement:
    clusterAffinity:
      clusterNames:
        - kubernetes-admin-10-10-176-223
    replicaScheduling:
      replicaSchedulingType: Duplicated
```
**Environment**:
- Karmada version:
```bash
root@node5[percona-mgo]# karmadactl version
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Chenhb123** [comment]
Sorry,This is my mistake,It's because I set finalizers in the cr file and the cr can't be deleted:
```bash
apiVersion: psmdb.percona.com/v1-9-0
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
  namespace: percona
  finalizers:
    - delete-psmdb-pvc
```
After executing the following command, the issue was resolved:
```bash
kubectl patch PerconaServerMongoDB/my-cluster-name -p '{"metadata":{"finalizers":[]}}' --type=merge -n percona
```

**Comment by RainbowMango** [comment]
Thanks @Chenhb123. 
I saw you are talking about the operator thing at the WeChat group, you are welcome to have a talk at the community meeting.
