### ISSUE TITLE
[lfx-mentorship]Refactor `get` command to leverage aggregated API

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1329]
**What would you like to be added**:
Now `karmadactl get` command retrieves resources by Cluster token stores at `Cluster` object.
We should refactor it to leverage the [Aggregated API](https://github.com/karmada-io/karmada/blob/master/docs/userguide/aggregated-api-endpoint.md), the benefits would be:
1. Both `Push` and `Pull` clusters are supported
2. Stop using the administrator's credential to access member clusters.

**Why is this needed**:

**Comment by ccchenjiahuan** [comment]
@RainbowMango hi, l am interested in this project and want to take this as my lfx project. Are there any pre-requirements before applying, e.g detailed design?

**Comment by lonelyCZ** [comment]
Hi @ccchenjiahuan, sorry, I am working on this function, please look at #1091 #1219 #1343.

**Comment by ccchenjiahuan** [comment]
> Hi @ccchenjiahuan, sorry, I am working on this function, please look at #1091 #1219 #1343.

@lonelyCZ Thanks for your reminding!
@RainbowMango So are there any available karmada lfx projects to apply for now? Please let me know ahead, thanks!

**Comment by RainbowMango** [comment]
I've posted [4 projects](https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2022/01-Spring#karmada) to LFX. And I will post some ideas to the [Google Summer of Code](https://github.com/cncf/mentoring/discussions/469).

If you have any ideas/proposals, please feel free to let me know.

**Comment by XiShanYongYe-Chang** [comment]
Maybe the refactor not be over?

**Comment by lonelyCZ** [comment]
> Maybe the refactor not be over?

Yes, there are other tasks, for example, performance optimization.

/reopen

**Comment by lonelyCZ** [comment]
I seemingly don't have right. Could you please reopen this issue? @RainbowMango
