### ISSUE TITLE
[lfx-mentorship] refactor the scheduler framework

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1330]
**What would you like to be added**:
Refactor the framework of `karmada-scheduler` to make it easier to extend and adopt more scheduling policies.

**Why is this needed**:

Refer to:
- https://github.com/karmada-io/karmada/issues/1195

**Comment by kerthcet** [comment]
I'm glad to follow this feature, should I have to apply for the mentorship? @RainbowMango

**Comment by halfrost** [comment]
I applied for the mentorship program of this project in LFX, clicked the apply button and it was successful. I thought I needed to fill in some information. So I suspected that the application was not successful, I withdrew the application, but when I reapplied, the LFX system told me "You already applied to this program.". I'm just curious whether my application is successful or not? @kevin-wangzefeng

**Comment by huone1** [comment]
it is the schedule refactor proposal : https://docs.google.com/document/d/1yZfw50F7uu9WG_dZ0M7-jbsmlidPIlMmDSI3AA4eWRg/edit?usp=sharing
it is just a draft version, so  you can give any suggestions and ideas.

**Comment by kerthcet** [comment]
It's a great start. I read the document overall and left several  comments there. Maybe not mature but make sense to me. Thanks @huone1

**Comment by RainbowMango** [comment]
/close
as finished.
