### ISSUE TITLE
[lfx-mentorship] Enhancement for controllers scalebility

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1331]
**What would you like to be added**:
Ensures the controllers are suitable for large-scale deployment in production cases.

**Why is this needed**:
There are some actions on-going already, but not for all controllers.
Refer to:
- https://github.com/karmada-io/karmada/pull/1321
- https://github.com/karmada-io/karmada/pull/1199
- https://github.com/karmada-io/karmada/issues/1260

**Comment by zuston** [comment]
Hi. I want to take over this, and so do i just only apply it on LFX [website](https://mentorship.lfx.linuxfoundation.org/participate/mentee?projectId=74840708-0989-4983-88f6-9f43034ae351) ? @RainbowMango

**Comment by RainbowMango** [comment]
Yes, you can apply it and there will be a [Mentee selection process](https://github.com/cncf/mentoring/blob/main/lfx-mentorship/README.md#mentee-selection-process) later.

**Comment by RainbowMango** [comment]
I can see several guys are applying for this project.

**Comment by zuston** [comment]
Got it. Can i apply for several tickets to ensure selected ？ @RainbowMango

**Comment by RainbowMango** [comment]
You can refer to [Eligibility Rules](https://docs.linuxfoundation.org/lfx/mentorship/mentees), no guarantees from me.

**Comment by RainbowMango** [comment]
/assign @dddddai 
Congrats!!!

**Comment by RainbowMango** [comment]
/close
As completed.
