### ISSUE TITLE
chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.21.5-eks-bc4871b

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1339]
**What happened**:
When installing Karmada with Kubernetes `v1.21.5-eks-bc4871b`:
```bash
helm install karmada -n karmada-system --create-namespace ./charts
```

Getting below error:
```
Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.16.0 which is incompatible with Kubernetes v1.21.5-eks-bc4871b
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
No.
This issue is echoed from [Karmada Community's webpage](https://community.cncf.io/karmada-community/) and user report this by email.

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.0.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

cc @algebra2k @jrkeen

**Comment by pigletfly** [comment]
are you using helm v2 or v3 ?

**Comment by RainbowMango** [comment]
I don't know, this issue is synced from email. 
I don't think it has anything to do with the Helm version.
