### ISSUE TITLE
Support autoscaling/v2 api-resource

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1344]
**What would you like to be added**:
Support autoscaling/v2 api-resource

**Why is this needed**:
The HorizontalPodAutscaler autoscaling/v2 stable API moved to GA in 1.23. The HorizontalPodAutoscaler autoscaling/v2beta2 API has been deprecated. Karmada use autoscaling/v1 version now.

**Comment by RainbowMango** [comment]
> Karmada use autoscaling/v1 version now

Why do you think that? I guess we can use `kube-apiserver@v1.23` as `karmada-apiserver`. isn't it?

**Comment by RainbowMango** [comment]
Oh, right. But we might have to hold for a while. The reasons are:

- For the federated HPA feature, we are going to refactor it, I guess the draft proposal will be discussed at next week's community meeting. 
- We can't just upgrade to autoscaling/v2 as it does not work for clusters less than v1.23.

**Comment by jwcesign** [comment]
FederatedHPA is using the same `spec` as autoscaling/v2.

If you want to use the original HPA(v1 or v2), please use PP/CPP to propagate it.
