### ISSUE TITLE
karmada control plane will be destroyed when unjoined if its host cluster is joined to itself

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#1350]
**What happened**:
If the host cluster is joined to karmada and using the same namespace. When we try to unjoin the host cluster, the karmada control plane will be destroyed due to the unjoin process will delete the namespace.

**What you expected to happen**:
The karmada control plane can't be destroyed.

**How to reproduce it (as minimally and precisely as possible)**:
step1: deploy karmada
hack/local-up-karmada.sh

step2: join host cluster 
./karmadactl join karmada-host --cluster-kubeconfig=/root/.kube/karmada.config --cluster-namespace=karmada-system

step3: unjoin host cluster
./karmadactl unjoin karmada-host --cluster-kubeconfig=/root/.kube/karmada.config --cluster-namespace=karmada-system

result: karmada control plane components will be deleted.
```
[root@karmada-lhb follow-yaml]# kubectl --context=karmada-host get po -n karmada-system 
NAME                                            READY   STATUS        RESTARTS   AGE
karmada-aggregated-apiserver-7b88b8df99-w4kjc   1/1     Terminating   0          23h
karmada-apiserver-5746cf97bb-g7lpm              1/1     Terminating   0          23h
karmada-webhook-85db7d4c94-mhvwb                0/1     Terminating   0          23h
```

**Anything else we need to know?**:
I have 2 methods to fix this problem.
1. Users can't use the `karmada-system` namespace when joined. `karmada-system` is reservered for karmada control plane and we need to add a validation in karmadactl join command.
2. We will add an annotation to the namespace created by karmada in member cluster when joining. When unjoining, if we found that the namespace is not created by karmada, we won't delete it. 

**Environment**:
- Karmada version: lastest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Poor12** [comment]
I think the solution 2 is better. There are some user case that users will not install karmada in `karmada-system`.

**Comment by RainbowMango** [comment]
> Users can't use the karmada-system namespace when joined. karmada-system is reservered for karmada control plane and we need to add a validation in karmadactl join command.

That's an interesting proposal, the `--cluster-namespace` used to specify the namespace where to put the secrets stuff, it is not recommended to put them into `karmada-system` which is usually used for components. I'm not so sure if we should force users don't do that.

I'll get back after I look at the following proposal and the implementation addressed by #1653.

**Comment by RainbowMango** [comment]
After going through the second approach, now I tend to the first proposal. But given this issue only happened when people changed the default `--cluster-namespace`, we can assume that people know what he is doing and we can give a warning on that.

**Comment by RainbowMango** [comment]
/assign @Poor12 
As the #1653
