### ISSUE TITLE
a cluster can be joined to mulit karmada instance or be joined to the same karmada with different names

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#1351]
**What happened**:
A cluster can be joined to mulit karmada instances or be joined to the same karmada with different names. 

**What you expected to happen**:
A cluster should be allowd to be joined to only one karmada instance.

**How to reproduce it (as minimally and precisely as possible)**:
Just join a cluster to different karmada instance.

**Anything else we need to know?**:
Maybe we can implement the cluster ID propasal. See [ClusterID](https://docs.google.com/document/d/1S0u6xzP2gcJKPipA6tBNDNuid76nVKeGhTk7PrCIuQY/edit#heading=h.4aw518aveb4f)

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by GitHubxsy** [comment]
Related sig-multicluster [clusterid enhancements](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/2149-clusterid).

**Comment by lonelyCZ** [comment]
Also mentioned at #880
