### ISSUE TITLE
 When the status field of the resource changes, it will trigger the karmada controller reconcile to start working, it should be better to trigger when the spec changes

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1353]
#### What happened:
When the kube-controller-manager of the host cluster cluster is all enabled, a deployment is created, but there is no suitable node node will always be updated with the status field. At this time, you can see that the controller of karmada is also constantly reconcile
####  What you expected to happen:
Only when the  spec field changed, karmada controller should be triggered

**Comment by RainbowMango** [comment]
Is this the same issue we have talked about at the WeChat group?

> When the kube-controller-manager of the host cluster cluster is all enabled

If no node, why enable all these controllers?

**Comment by CharlesQQ** [comment]
> Is this the same issue we have talked about at the WeChat group?
> 
> > When the kube-controller-manager of the host cluster cluster is all enabled
> 
> If no node, why enable all these controllers?

**Comment by CharlesQQ** [comment]
> Is this the same issue we have talked about at the WeChat group?
> 
> > When the kube-controller-manager of the host cluster cluster is all enabled
> 
> If no node, why enable all these controllers?

**Comment by RainbowMango** [comment]
Hi @CharlesQQ 

> it should be better to trigger when the spec changes 

It is a reasonable request I think. I'm asking because I want to know your cases.

**Comment by CharlesQQ** [comment]
@RainbowMango 
it' s  first time I install karmada in standard k8s cluster, all controllers is enabled and found this case

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
