### ISSUE TITLE
Is there any doc to describe how to install ANP for non-kind case?

### ISSUE THREAD

**Issue by MingZhang-YBPS** [karmada-io/karmada#1361]
**Please provide an in-depth description of the question you have**:
From Doc, https://github.com/karmada-io/karmada/blob/master/docs/working-with-anp.md, it describes how to install ANP for test environment which is built on top of **Kind**. However, what can be done for **standard K8S clusters**?  
In my case, I have 2 standard clusters. And I have already made the Karmada control plane installation and member cluster registration (Pull mode) worked. Then how can I install proxy-server and proxy agent for my Karmada host cluster and Karmada member cluster?
**What do you think about this question?**:
Some statement in the doc `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' karmada-host-control-plane` are not applicable for the standard K8S cluster installation case. Meanwhile, shall I create 2 proxy server instances on Karmada host if I have 2 PULL mode member clusters?

**Environment**:
- Karmada version:
1.0.1
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Good question.
cc @mrlihanbo @XiShanYongYe-Chang

**Comment by GitHubxsy** [comment]
![image](https://user-images.githubusercontent.com/11901080/154030576-9c96ce1f-6380-41b1-8809-6cabc26bf80f.png)
Why do we use apiserver-network-proxy?
Clusters are classified into two types:
type-1 clusters：The Kube-apiserver can be directly connected.
type-2 clusters：The Kube-apiserver cannot be directly connected. For example, the cluster is deployed behind the firewall.

For type-2 clusters, we introduce the apiserver-network-proxy (ANP). You can also use other proxy components. The ANP-server is deployed on the Karmada control plane and the ANP-agent is deployed on the registration cluster. The ANP-agent initiates registration with the ANP-server. In this way, we can access Kube-apiserver indirectly through ANP-Server without opening firewalls.

**Comment by XiShanYongYe-Chang** [comment]
The statement in the doc `docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' karmada-host-control-plane` is used to obtain the IP address of the host cluster.

> Meanwhile, shall I create 2 proxy server instances on Karmada host if I have 2 PULL mode member clusters?

We only need to deploy one proxy-server instance on the host cluster. And we need to deploy proxy-agent for every pull mode cluster.

**Comment by MingZhang-YBPS** [comment]
@GitHubxsy @XiShanYongYe-Chang 
Thanks! It is more clear for me now. One remaining question from my side:
For ANP proxy server, maybe one single instance is unreliable. Is there any HA solutions?

**Comment by GitHubxsy** [comment]
> @GitHubxsy @XiShanYongYe-Chang Thanks! It is more clear for me now. One remaining question from my side: For ANP proxy server, maybe one single instance is unreliable. Is there any HA solutions?

Both the ANP-server and ANP-agent support multiple instances. For details, see [ANP PR](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/46) .
