### ISSUE TITLE
Why use both executioncontroller and workstatuscontroller to create or update k8s object in member cluster

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1362]
**Please provide an in-depth description of the question you have**:
I'm confused that the `executioncontroller` and the `wotkstatuscontroller` both can create or update k8s object in member cluster for each work. 

**What do you think about this question?**:
I think all the operation about work can be implemented in one controller. k8s object in member cluster is just subresource of the work as pod to deploy. 

**Environment**:
- Karmada version: v1.0.1
- Kubernetes version: 
- Others:

**Comment by RainbowMango** [comment]
The main responsibility of `workstatus controller` is syncing resource status from member cluster to Karmada control plane, it usually does not create resources, but it'll update resources if the desired state changed unexpectedly, e.g. manually updated.

**Comment by likakuli** [comment]
Just like `deployment controller` not only create pod, but also update deployment status. All the operations implemented in one controller. 
For now, the `execution controller` just create or update k8s resource in member cluster. The `workstatus controller` sync resource status from member cluster to karmada control plane, but it also has the logic to create or update k8s object in member cluster.

**Comment by RainbowMango** [comment]
Yeah, I get your question now.
The reason why we separate the controllers is we want each controller to be simple and focused.

**Comment by likakuli** [comment]
The `execution controller` is simple enough, but the `workstatus controller` do all the operations related to resource deployed in member cluster.  This bring about a lot of code like `RetryOnConflict`

**Comment by RainbowMango** [comment]
> This bring about a lot of code like RetryOnConflict

Do you mean that brings a lot of `conflicts`?

**Comment by XiShanYongYe-Chang** [comment]
It will be tracked by #3807.
/close
