### ISSUE TITLE
Enhance security of `karmadactl join` to register member cluster

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1363]
**What would you like to be added**:
Enhance `karmadactl join` command, making it support to register member cluster with `--token`, Such as
```
karmadactl join --token <tokenSecret> --karmada-apiserver <karmada-apiserver-url> --name <cluster_name>
```

like `kubeadm` and `keadm` to register node to master.
```
kubeadm join [api-server-endpoint] --token [token]
```

and like OCM
```
# Join a cluster to the hub
clusteradm join --hub-token <tokenID.tokenSecret> --hub-apiserver <hub_apiserveR_url> --name <cluster_name>
```

**Why is this needed**:

Now, registering a member cluster, we need to copy the kubeconfig file of member cluster to karmada control plane host, which is some risk involved. For example, forgetting to delete the Kubeconfig file causes permissions to leak.

**Comment by lonelyCZ** [comment]
In this mode, we also deploy `agent` for `pull mode` register by CLI without `karmada.config` that is more reasonable.

**Comment by lonelyCZ** [comment]
Perhaps, implement `bootstrap token` to register member clusters.

Refer 
1. [bootstrap tokens](https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/)
2. [certificate-signing-requests](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/)

**Comment by duanmengkk** [comment]
I have also noticed that the current pull mode cluster registration mode is a bit complex (must copy config from host to member, create secrets and so on) and insecure (member cluster has the highest rights on the  karmada control plane ).
My opinion is to use karmadactl to join pull mode cluster in karmada control plane,like `kubectl karmada join cluster member3 --mode pull`.This command will generate a cert user such as `karmada-member3` and the outputs is a URL or yamL file(secrets，clusterRole，clusterRoleBinding, agent in this file),It's like an invitation.In member cluster,we just use the command to register a cluster without install any tools `curl {url} | kubectl apply -f `.
What do you think about it? @lonelyCZ

**Comment by lonelyCZ** [comment]
> curl {url} | kubectl apply -f 

Right, it is convenient for member clusters to register. But it seems to leave too much manual work to the karmada control plane. 

If the way can bring users a more secure registration step, in fact, there is a certain value.

Agent is currently using `karmada-kubeconfig` directly, which is not acceptable, so we need to consider implementing a mechanism based on the CA. We need to modify the `karmada-agent` slightly to support multiple security modes and certificate rotation like `kubelet`.

**Comment by duanmengkk** [comment]
I fully agree with you,but i think it is little different from kubeadm used in k8s,pull mode cluster should not have the privileges to operate other member cluster.`kubeadm init ` will generate a token and others node use this token to join k8s,but this token is unique,it cannot determine the permissions of each different cluster.Anyway, I don't think the member cluster should have control plane permissions except for itself,network traffic from the pull mode cluster to the control plane should be one-way and cannot be propagated to other member clusters.Can we implement these logic in aggregated-apiserver?

> > curl {url} | kubectl apply -f
> 
> Right, it is convenient for member clusters to register. But it seems to leave too much manual work to the karmada control plane.
> 
> If the way can bring users a more secure registration step, in fact, there is a certain value.
> 
> Agent is currently using `karmada-kubeconfig` directly, which is not acceptable, so we need to consider implementing a mechanism based on the CA. We need to modify the `karmada-agent` slightly to support multiple security modes and certificate rotation like `kubelet`.

**Comment by lonelyCZ** [comment]
> kubeadm init will generate a token and others node use this token to join k8s,but this token is unique,it cannot determine the permissions of each different cluster

`token` is only a authentication flags, specific permissions need to be refined in the cloud. For example, only allow the member cluster to access their own `Exection namespace`.

> I don't think the member cluster should have control plane permissions except for itself,network traffic from the pull mode cluster to the control plane should be one-way and cannot be propagated to other member clusters.

Yes, this is our goals.

> Can we implement these logic in aggregated-apiserver?

We can talk about how to do that in detail, possibly needing to add some controllers. 

I plan to carry out this work in detail during the summer, welcome to talk about it.

**Comment by duanmengkk** [comment]
OK,Can i work with you for it together? If you are going to discuss this at the meeting, please just @ me
