### ISSUE TITLE
It is possible upload meeting recordings?

### ISSUE THREAD

**Issue by haiker2011** [karmada-io/karmada#1364]
**Please provide an in-depth description of the question you have**: 
Want to know more detail about the meeting, but can not find meeting recordings to learn karmada.

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Yeah, it's reasonable. I'll try to upload it ASAP.

**Comment by RainbowMango** [comment]
I saw you at yesterday's meeting but didn't hear from you. Is there anything you want to know/talk about?

**Comment by haiker2011** [comment]
I am really interested in karmada and learning about karmada, If possible I want to get involved in developing the Karmada code.

**Comment by haiker2011** [comment]
I want to get some resources to learn， e.g meeting recordings.

**Comment by RainbowMango** [comment]
Please look at the records on BiliBili: https://b23.tv/gKSmkKz.
The link is now listed at [community meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).

/close
