### ISSUE TITLE
Generates API documents

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1367]
**What would you like to be added**:
Generates API documents (like [swagger.json](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json)).

- [ ] Auto-generates the API documents when API changes.
- [ ] Check If API documents are up to date by CI.

**Why is this needed**:
Simplify API development for users.

**Comment by 2hangchen** [comment]
I've exported swagger.json,where can I upload it?

**Comment by RainbowMango** [comment]
Updated descriptions just now, not just upload it, we need to generate it (like, by scripts).

By the way, how do you generate the docs?

**Comment by 2hangchen** [comment]
> Updated descriptions just now, not just upload it, we need to generate it (like, by scripts).
> 
> By the way, how do you generate the docs?
I'm sorry,I didn't see the description, I'm not through script generated,I was through curl `/openapi/v2` generated `swagger.json`.

**Comment by RainbowMango** [comment]
Oh, I guess the Karmada related APIs are included in the file. I didn't know that before.

Can you upload the swagger.json file to this issue or send it to me by slack or by email?

**Comment by 2hangchen** [comment]
> Oh, I guess the Karmada related APIs are included in the file. I didn't know that before.
> 
> Can you upload the swagger.json file to this issue or send it to me by slack or by email?
I have  sent it to this email address :qdurenhongcai@gmail.com.

**Comment by RainbowMango** [comment]
Thanks. I've generated it locally.

I see both Kubernetes and Karmada API are in it, do you know how to just keep Karmada's API?

**Comment by 2hangchen** [comment]
> Thanks. I've generated it locally.
> 
> I see both Kubernetes and Karmada API are in it, do you know how to just keep Karmada's API?

I don't know. I export it in full every time.

**Comment by lonelyCZ** [comment]
The [project](https://github.com/argoproj/argo-workflows/blob/master/api/openapi-spec/swagger.json) seem to achieve these functions, I have tested it that is working correctly and there are only it own APIs. And I'm working on how to do it.

**Comment by RainbowMango** [comment]
Great! Looking forward to your progress.
