### ISSUE TITLE
Extension for out-of-tree plugins

### ISSUE THREAD

**Issue by kerthcet** [karmada-io/karmada#1371]
**What would you like to be added**:
We have some filter plugins customized, and we want to add them to scheduler easily, e.g.
1. initialization
```golang
	command := app.NewSchedulerCommand(stopChan, customizedPlugins...)
```
2. Locate our plugins' source code to the plugins folder. 

**Why is this needed**:
Extension for out-of-tree plugins.

TODOs:

- [x] introduce registry to store plugins in framework initialization: https://github.com/karmada-io/karmada/pull/1382
- [ ] add out-of-tree options to initialize scheduler

**Comment by RainbowMango** [comment]
I'd like to have a chat with you at the next community meeting.
If it is accepted, it can be included in the next release(release 1.2).

**Comment by RainbowMango** [comment]
I think we are ready to start the discussion now, right? @huone1

**Comment by huone1** [comment]
the first part  has been merged， I am looking forward that you can start the development of the second port

**Comment by kerthcet** [comment]
I have completed the second part but will follow after https://github.com/karmada-io/karmada/pull/1627 merged for some extra works.
