### ISSUE TITLE
no matching resources found

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#1379]
### When executing the local-up-karmada.sh script, the following error is reported

![294c9c2be01ca5081be0c573199bdfa](https://user-images.githubusercontent.com/31637804/154796689-cecfdf93-5a69-4042-b687-6509cd77baa2.png)

**Environment**:
- Karmada version: master
- kubectl version: v1.23.3
- Others: go 1.17.2

**Comment by RainbowMango** [comment]
Are you running the `hack/local-up-karmada.sh` under the root directory of karmada repo?

**Comment by RainbowMango** [comment]
Could you please post the whole output here?

**Comment by luoMonkeyKing** [comment]
> 您是否正在运行`hack/local-up-karmada.sh`karmada repo 的根目录下？
Yes, the directory I am running is /home/karmada and the running command is hack/local-up-karmada.sh

**Comment by luoMonkeyKing** [comment]
> 你能把整个输出贴在这里吗？
### My previous virtual machine was deleted, I rebuilt a HUAWEI CLOUD virtual machine today, and this error was reported after installation
```2022/02/21 10:39:31 [INFO] encoded CSR
2022/02/21 10:39:31 [INFO] signed certificate with serial number 44646887950809210002655652010120055702994310444
namespace/karmada-system created
serviceaccount/karmada-controller-manager created
serviceaccount/karmada-scheduler created
serviceaccount/karmada-webhook created
clusterrole.rbac.authorization.k8s.io/karmada-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/karmada-controller-manager created
secret/karmada-cert-secret created
secret/kubeconfig created
secret/webhook-cert created
statefulset.apps/etcd created
service/etcd-client created
service/etcd created
wait the etcd ready...
pod/etcd-0 condition met

Apply dynamic rendered apiserver service in /tmp/tmp.tWMBxJgplV/karmada-apiserver.yaml.
deployment.apps/karmada-apiserver created
service/karmada-apiserver created
wait the karmada-apiserver ready...
pod/karmada-apiserver-5746cf97bb-m9vs9 condition met

Karmada API Server's IP is: 172.x.x.x, host cluster type is: local
Cluster "karmada-apiserver" set.
User "karmada-apiserver" set.
Context "karmada-apiserver" created.
deployment.apps/karmada-kube-controller-manager created
deployment.apps/karmada-aggregated-apiserver created
service/karmada-aggregated-apiserver created
wait the karmada-aggregated-apiserver ready...
pod/karmada-aggregated-apiserver-7b88b8df99-cwp96 condition met
pod/karmada-aggregated-apiserver-7b88b8df99-fbkw4 condition met
error: error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "karmada-system", Namespace: ""
from server for: "hack/../hack/../artifacts/deploy/namespace.yaml": Get "https://172.x.x.x:5443/api/v1/namespaces/karmada-system": http2: client connection lost```

**Comment by luoMonkeyKing** [comment]
It should be that the virtual machine configuration is not enough. The original virtual machine is 2u4G, and it can be upgraded to 4u8G.

**Comment by RainbowMango** [comment]
Thanks @luoMonkeyKing for your feedback. It means a lot.

I think we should document this case somewhere.

/reopen
/assign

**Comment by RainbowMango** [comment]
We are running `hack/local-up-karmada.sh` in GitHub-Hosted runners which with the following hardware specification:
- 2-core CPU
- 7 GB of RAM memory
- 14 GB of SSD disk space

If it is the case, I guess this problem is due to a lack of memory.

**Comment by luoMonkeyKing** [comment]
> 我们`hack/local-up-karmada.sh`在 GitHub 托管的运行器中运行，其硬件规格如下：
> 
> * 2核CPU
> * 7 GB RAM 内存
> * 14 GB SSD 磁盘空间
> 
> 如果是这样的话，我猜这个问题是由于内存不足造成的。

I think it should be like this

**Comment by XiShanYongYe-Chang** [comment]
This issue has not been active for a long time. Close it first. If have any problems, you can open it at any time.
/close
