### ISSUE TITLE
karmada-aggregated-apiserver error

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#1391]
base git tag v1.0.1

**What happened**:
```
Flag --karmada-config has been deprecated, This flag is currently no-op and will be deleted.
Error: unable to load configmap based request-header-client-ca-file: Get "https://karmada-apiserver.karmada-system.svc.cluster.local:5443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 172.30.64.253:5443: connect: connection refused
Usage:
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.0.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
> base git tag v1.0.1

> Flag --karmada-config has been deprecated, This flag is currently no-op and will be deleted.

I don't what happened to your case, but the flag hasn't been deprecated in v1.0.1. 
https://github.com/karmada-io/karmada/blob/v1.0.1/cmd/aggregated-apiserver/app/options/options.go#L57

**Comment by RainbowMango** [comment]
@chestarss could you please check the version and tell us what you did (operation steps)?

**Comment by chestarss** [comment]
> @chestarss could you please check the version and tell us what you did (operation steps)?

base git v1.0.1 karmada code
execute
```
hack/remote-up-karmada.sh ~/.kube/config k8s-test
```

then error in this step
```
wait the karmada-aggregated-apiserver ready...
error: timed out waiting for the condition on pods/karmada-aggregated-apiserver-7b88b8df99-spl7n
kubectl wait --for=condition=Ready --timeout=30s pods -l app=karmada-aggregated-apiserver -n karmada-system failed, retrying(1 times)
```

**Comment by RainbowMango** [comment]
Can you check why the pods(`pods/karmada-aggregated-apiserver-7b88b8df99-spl7n`) failed to start?

**Comment by chestarss** [comment]
找到原因了，安装脚本里的镜像用的是latest, 改成v1.0.1后正常了
