### ISSUE TITLE
自定义CRD中的repicas使用customresourceinterpreter托管replicas后没有resourcebinding生成

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#1397]
**Please provide an in-depth description of the question you have**:
我是参考这个链接部署了karmada-interpreter-webhook-example
https://github.com/karmada-io/karmada/tree/master/examples

然后修改webhook-configuration.sh脚本生成的yaml中资源为我自己的crd定义

之后重新提交crd 实例到集群看到webhook里有日志，但是没有resourcebinding生成。
karmada-interpreter-webhook-example中的日志

  ```
1 workloadwebhook.go:33] Explore workload(alter-645202407390711808/dev-alter-645202407390711808-spring-mvc-demo) for request: InterpretReplica
I0224 07:43:16.317055       1 http.go:85] wrote response UID: "c13e3bac-4ae3-40e5-a4e6-428f1dfd5444", successful: true
```

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.0.1
- Kubernetes version: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

- Others:

**Comment by chestarss** [comment]
kubectl get resourceinterpreterwebhookconfigurations -o yaml
```
apiVersion: v1
items:
- apiVersion: config.karmada.io/v1alpha1
  kind: ResourceInterpreterWebhookConfiguration
  metadata:
    creationTimestamp: "2022-02-24T07:36:28Z"
    generation: 1
    name: dnaapp-res-int-webhook-config
    resourceVersion: "119309"
    uid: fa431f54-b6a1-439d-b2ab-3254efe017a4
  webhooks:
  - clientConfig:
      caBundle: XXXX
      url: https://karmada-interpreter-webhook-example.karmada-system.svc:443/interpreter-workload
    interpreterContextVersions:
    - v1alpha1
    name: dnaapp.dian.so
    rules:
    - apiGroups:
      - dna.dian.so
      apiVersions:
      - v1
      kinds:
      - DnaApp
      operations:
      - InterpretReplica
      - ReviseReplica
      - Retain
    timeoutSeconds: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

```

**Comment by chestarss** [comment]
kubectl get pp -n alter-645202407390711808 dev-alter-645202407390711808-spring-mvc-demo-pp -o yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  creationTimestamp: "2022-02-23T13:15:53Z"
  generation: 3
  name: dev-alter-645202407390711808-spring-mvc-demo-pp
  namespace: alter-645202407390711808
  resourceVersion: "115768"
  uid: b416969c-c4bd-4684-b9c3-feae846bd3eb
spec:
  placement:
    clusterAffinity:
      clusterNames:
      - openshit-test
      - openshift-staging
      labelSelector: {}
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - openshift-staging
          weight: 1
        - targetCluster:
            clusterNames:
            - openshit-test
          weight: 1
  resourceSelectors:
  - apiVersion: dna.dian.so/v1
    kind: DnaApp
    name: dev-alter-645202407390711808-spring-mvc-demo
    namespace: alter-645202407390711808

```

CRD资源实例 dev-alter-645202407390711808-spring-mvc-demo 中replicas设置是2

**Comment by XiShanYongYe-Chang** [comment]
When you use you own CRD, you need to implement the appropriate logic in `examples/customresourceinterpreter/webhook/app/webhook.go`.

In addition, you can check the logs of the `karmada-controller-manager`.

**Comment by chestarss** [comment]
> When you use your own CRD, you need to implement the appropriate logic in `examples/customresourceinterpreter/webhook/app/webhook.go`.
> 
> In addition, you can check the logs of the `karmada-controller-manager`.

好的多谢，以后是否可以考虑和hpa一样去读crd中的replicas定义，只要遵循k8s replicas接口规范就能自动被托管呢。
我们在单集群下，crd资源是可以直接被hpa管理副本数的

**Comment by chestarss** [comment]
我的crd定义里指定了这个，官方的hpa就能根据这个找到replicas路径自动改值。希望你们也可以参考这个做成自动的，这样无需再自己实现webhook

```go
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:subresource:scale:specpath=.spec.deployment.replicas,statuspath=.status.deploymentStatus.replicas,selectorpath=.status.selector
// +kubebuilder:pruning:PreserveUnknownFields
```

  ```
  subresources:
      scale:
        labelSelectorPath: .status.selector
        specReplicasPath: .spec.deployment.replicas
        statusReplicasPath: .status.deploymentStatus.replicas
      status: {}
```

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/155490791-9d711ba9-671c-4351-9cbf-3b79ee990286.png)

**Comment by chestarss** [comment]
可以参考hpa的实现https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/horizontal-pod-autoscaler.md#scale-subresource

**Comment by XiShanYongYe-Chang** [comment]
Good advice 👍 

Welcome to join karmada and participate in the evolution development of this feature.

**Comment by RainbowMango** [comment]
@chestarss 
非常好的建议，对于已实现了`scale` subresource的CRD，可以减少一次webhook的访问。有没有兴趣试者改一下？

cc another owner here. 
cc @iawia002

**Comment by RainbowMango** [comment]
Why closed? @chestarss

**Comment by chestarss** [comment]
> Why closed? @chestarss

不好意思，我以为这个issue的提问已经完成，新的需求会在另一个issue记录。

**Comment by iawia002** [comment]
The direction of this method is quite good, for the GetReplicas hook point, we can query the scale subresource API to get the number of replicas directly, for the ReviseReplica hook point, we need to query the CRD of the corresponding resource

**Comment by XiShanYongYe-Chang** [comment]
Hi @chestarss We plan to close this issue, the relate reason can refer to https://github.com/karmada-io/karmada/pull/1728#issuecomment-1331625519

If you have a request for the current issue in the future, you can reopen it at any time or submit a new issue. Thanks anyway ~!
/close
