### ISSUE TITLE
A better way to choose the matched policy when more than one policies fits

### ISSUE THREAD

**Issue by qianjun1993** [karmada-io/karmada#1410]
**What would you like to be added**:

when more than one policies fit workload, we must check whether the resource has applied any policy. If the old policy  exists and still fits, we choose it so the workload will not be scheduled again. Otherwise, we sort policy by creating time and choose the newest one.

**Why is this needed**:
When we look for matched policy for workload and find more than one  policies, we just sort them by name and choose the first one now . But it may not be suitable for some condition that pods may be recreated when new policy is added.. 
We have such a user case:
     We create a common policy for one namespace, so that users can use Karmada like Kubernetes without any extra operator. But sometimes we may found that the old common policy may not be accurate for new workloads, so we need to add a new common policy. All the old workload should use the old policy ,so their pods will not be recreated . All the new workload should use the new policy.

**Comment by iawia002** [comment]
we have the same needs, see #1185 for our previous discussion.

**Comment by RainbowMango** [comment]
Hi @qianjun1993 Long time no see.

The use case is similar to #1185 (@iawia002 ). I guess it is worth filing a proposal for this. Things I want to know:
- What's the real use case?
- How common the use case is?
- How painful without a solution for this?( Is there a workaround?)
- What's the idea/design?

**Comment by qianjun1993** [comment]
@RainbowMango .
The priority of policy is also useful for our case . But we have a special use case :
We have one default policy in each namespace so that  user no need to create  extra policy . After use this policy a long time , the users  may have new needs that the old default policy is not suitable any more. In that time we need create a new default policy for  new workloads but all the workloads with old policy  will not change.

**Comment by qianjun1993** [comment]
My idea
we  need a new way  to sort the matched policy (even if we set priority for policy). The most important order is the priority. And then when we have two matched policy with the same priority, if our workload have applied one of them and create a rb , we just choose this policy so the rb will  not change. After that we can sort the policy with name (Current scheme )or create time

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
