### ISSUE TITLE
How to use overall property in FederatedResourceQuota

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1420]
**Please provide an in-depth description of the question you have**:

Karmada v1.1.0 release note introduces Federated ResourceQuota, which provides constraints that limit total resource consumption per namespace `across all clusters`.

But under my observation on the actual behavior and karmada code, the overall property doesn't constraint the total resource limit, it only set the overall property in quota status property.

Does federeated resource quota only constraint resource limit for each cluster individually that is set on staticAssignments, and can not constraint the overall resource limit?

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.1.0
- Kubernetes version: v1.23.1
- Others:

**Comment by XiShanYongYe-Chang** [comment]
> But under my observation on the actual behavior and karmada code, the overall property doesn't constraint the total resource limit, it only set the overall property in quota status property.
>
> Does federeated resource quota only constraint resource limit for each cluster individually that is set on staticAssignments, and can not constraint the overall resource limit?

We will add the validation in `karmada-webhook`, so as to limit the total amount not to be exceeded.

**Comment by stingshen** [comment]
Thanks for the explanation.
