### ISSUE TITLE
Is it acceptable for one object to have more than one propagationpolicy?

### ISSUE THREAD

**Issue by snowplayfire** [karmada-io/karmada#1423]
**What would you like to be added**:

One object can have more than one propagationpolicy.

**Why is this needed**:

Suppose we have many clusters named cluster1, cluster2...cluster10.  Every workload object may need one of the combinations of the ten clusters to propogate and  we hope  combinations can be reused rather than one workload has one propagationpolicy. If we create all combinations as propogationpolicies having `labelselector` in fed cluster beforehand, every workload has a certain label to  use `labelselector` to select propogationpolicy, we can reach the target of reusing propogationpolicies.

But ten clusters have lots of combinations, we hope to create less propogationpolicies .

If one workload object is allowed to have more than one propagationpolicy, every propagationpolicy stands for one cluster and has one labelselector, the workload object can be setted several labels to select several propogationpolicies. Then only ten propogationpolicies need to be created in fed cluster.

**Comment by RainbowMango** [comment]
Maybe I didn't get it yet, why don't you specify the clusters in a `PropagationPolicy`?

**Comment by huone1** [comment]
> > Maybe I didn't get it yet, why don't you specify the clusters in a `PropagationPolicy`?
> 
> I hope propagationpolicy can be reused rather than one object has one propagationpolicy.

you can fill more than one resource object in propagationpolicy spec.resourceSelectors

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
