### ISSUE TITLE
Why creating two service account during cluster join?

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1428]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

In the following code, two service accounts are created: service account and service account for impersonation. But it seems that the impersonation SA is not used to manipulate resources on member clusters.

https://github.com/karmada-io/karmada/blob/e02b5d3211f490ddc8171fc1d61ac5fa10ac76ed/pkg/karmadactl/join.go#L203-L217

So what is the impersonation SA used for?

**Environment**:
- Karmada version: v1.1.0
- Kubernetes version: v1.12.0
- Others:

**Comment by XiShanYongYe-Chang** [comment]
The impersonate secret are use to access member cluster when user use cluster proxy:

https://github.com/karmada-io/karmada/blob/e02b5d3211f490ddc8171fc1d61ac5fa10ac76ed/pkg/registry/cluster/storage/proxy.go#L65

You can try the new feature [Aggregated Kubernetes API Endpoint](https://github.com/karmada-io/karmada/blob/master/docs/userguide/aggregated-api-endpoint.md) which is released in v1.0.0 version.

**Comment by stingshen** [comment]
Thank you!
