### ISSUE TITLE
[GoodFirst] prevent networking api from propagating

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1432]
**Task description**:
We have introduced a new API group at the last release(v1.1) and it should be ignored from propagating.

**Solution**:
Just add the API group to `skipped resource config`, i.e.:

```diff
diff --git a/pkg/util/apigroup.go b/pkg/util/apigroup.go
index 4a9a42d7..6d22c2f8 100644
--- a/pkg/util/apigroup.go
+++ b/pkg/util/apigroup.go
@@ -9,6 +9,7 @@ import (

        clusterv1alpha1 "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1"
        configv1alpha1 "github.com/karmada-io/karmada/pkg/apis/config/v1alpha1"
+       networkingv1alpha1 "github.com/karmada-io/karmada/pkg/apis/networking/v1alpha1"
        policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
        workv1alpha1 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha1"
 )
@@ -41,6 +42,7 @@ func NewSkippedResourceConfig() *SkippedResourceConfig {
        r.DisableGroup(policyv1alpha1.GroupVersion.Group)
        r.DisableGroup(workv1alpha1.GroupVersion.Group)
        r.DisableGroup(configv1alpha1.GroupVersion.Group)
+       r.DisableGroup(networkingv1alpha1.GroupVersion.Group)

        // disable event by default
        r.DisableGroup(eventsv1.GroupName)
```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Amartya-Mahato** [comment]
@RainbowMango Hi, i would like to give it a try. Can i work on it?

**Comment by RainbowMango** [comment]
Hi @Amartya-Mahato  You can get who can join and how to join the task from the PR description.
