### ISSUE TITLE
Failed to install karmada via helm

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#1441]
**What happened**:

when installing karmada 1.1.0 via helm, it failed.
```
+ kubectl apply -f /opt/configs/
secret/karmada-cert configured
configmap/karmada-crds-patches configured
secret/karmada-kubeconfig configured
configmap/karmada-static-resources configured
secret/karmada-webhook-cert configured
Error from server (Invalid): error when creating "/opt/configs/crds-bases-configmaps.yaml": ConfigMap "karmada-crds-bases" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Error from server (Invalid): error when creating "/opt/configs/crds-configmaps.yaml": ConfigMap "karmada-crds" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by jrkeen** [comment]
Thank your feedback, the kubectl trying to record the previous state of affairs in an {"metadata":{"annotation":{"kubectl.kubernetes.io/last-applied-configuration": "GINORMOUS string"}}}. The configMap is too huge so exceeding the limit, I will try to fix it.
