### ISSUE TITLE
Clean `/etc/karmada` directory with `karmadactl init` cmd at the beginning

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1454]
**What would you like to be added**:

Clean `/etc/karmada` directory with `karmadactl init` cmd at the beginning.

**Why is this needed**:

When I run `karmadactl init`  multiple times to install karmada, an error reported:
```
Error: prepare karmada failed.mkdir /etc/karmada/crds/: file exists
```
When I delete `/etc/karmada/crds/` directory, and install conitue, an error is reported like this:
```
F0308 17:14:33.682027 4151946 deploy.go:49] Post "https://172.19.0.2:32443/api/v1/namespaces": x509: certificate is valid for 127.0.0.1, 10.254.0.1, 172.19.0.3, 94.74.101.46, not 172.19.0.2
```

**Comment by prodanlabs** [comment]
I did have this problem with multiple installs, I'll fix it later :)

**Comment by XiShanYongYe-Chang** [comment]
@prodanlabs thanks~

/assign @prodanlabs
