### ISSUE TITLE
Sync namespace to specific clusters

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1461]
**What would you like to be added**:

Sync namespace to specific clusters. For example, sync namespace A to cluster a, b, c. Maybe we could use namespace label or configmap in namespace to specify which clusters should be synced to?

**Why is this needed**:

Currently, namespace would be synced to all clusters except for those specified statically in `--skipped-propagating-namespaces`. But  there maybe some more dynamic usecases. For example, users only need to create the namespace on the specific region.

**Comment by RainbowMango** [comment]
> But there maybe some more dynamic usecases. For example, users only need to create the namespace on the specific region.

In that case, you can [disable the `namespace` controller](https://github.com/karmada-io/karmada/blob/master/docs/userguide/configure-controllers.md#configure-controllers-1) and use `ClusterPropagationPolicy` to specify which clusters you want to sync to.

**Comment by stingshen** [comment]
Thank you!
