### ISSUE TITLE
使用 kubectl karmada init 安装karmada报x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")

### ISSUE THREAD

**Issue by hanweisen** [karmada-io/karmada#1467]
**Please provide an in-depth description of the question you have:  
参考https://github.com/karmada-io/karmada/blob/release-1.0/docs/installation/installation.md   
使用kubectl karmada init 安装karmada，由于国内被墙了，使用如下命令安装  
`kubectl karmada init --crds crds.tar.gz --karmada-apiserver-image registry.aliyuncs.com/google_containers/kube-apiserver:v1.21.7 --etcd-image registry.aliyuncs.com/google_containers/etcd:3.4.13-0 --karmada-kube-controller-manager-image registry.aliyuncs.com/google_containers/kube-controller-manager:v1.21.7`  
使用的crd文件：https://github.com/karmada-io/karmada/releases/download/v1.0.1-2/crds.tar.gz  
在apiserver成功启动后报错，日志如下  
`F0310 17:21:16.348710  264106 deploy.go:49] Post "https://100.73.10.30:32443/api/v1/namespaces": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")`

**What do you think about this question?**:
看了一下安装的代码 应该是在创建client去连karmada-apiserver创建namespace的时候报错。

**Environment**:
- Karmada version: v1.0.0
- Kubernetes version: v1.18.5
- Others:

**Comment by hanweisen** [comment]
出现上面错误的时候 在前面的步骤也失败了好几次，/etc/karmada/下面的一些正式文件没有清理干净
`rm -rf /etc/karmada/*`
`kubectl delete ns karmada-system`
重新安装就可以了

**Comment by RainbowMango** [comment]
Thanks for reporting, this will be fixed by #1455.
