### ISSUE TITLE
failed to install via helm

### ISSUE THREAD

**Issue by guyingyan** [karmada-io/karmada#1471]
used the command line 
helm install karmada -n karmada-system --create-namespace ./charts
to install helm, it's failed when install pod karmada-pre-install , log as below
==============
root@92b06d68-7364-4c24-9cc6-091e90dade4d-master-1:~# kubectl logs karmada-pre-install-c2pbh -n karmada-system
+ kubectl apply --server-side -f /opt/configs/
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)
Server-side apply not available on the server: (415: Unsupported Media Type)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
@pigletfly @jrkeen Could you please take a look?

**Comment by pigletfly** [comment]
@guyingyan can you provide your kubernetes version?

**Comment by guyingyan** [comment]
> @guyingyan can you provide your kubernetes version?
v1.20.13-20

**Comment by guyingyan** [comment]
the configuration --feature-gates ServerSideApply=false should be unset in /etc/kubernetes/manifests/kube-apiserver.yaml

**Comment by RainbowMango** [comment]
@guyingyan Do you mean this issue is solved? Any improvement needed to be done at the Karmada side?

**Comment by guyingyan** [comment]
@RainbowMango maybe this is not an issue, it's a conflict. when use the parameter --server-side in the command line "kubectl apply --server-side -f " , ks8 configuration should be not set  "--feature-gates ServerSideApply=false" in file manifests/kube-apiserver.yaml

**Comment by pigletfly** [comment]
do you add the `--feature-gates ServerSideApply=false` in charts template? there is no `--feature-gates` flags in https://github.com/karmada-io/karmada/blob/master/charts/templates/karmada_apiserver.yaml#L37.

**Comment by guyingyan** [comment]
> manifests/kube-apiserver.yaml

this parameter in k8s directory is :/etc/kubernetes/manifests/kube-apiserver.yaml not in karmada apiserver configuration

**Comment by pigletfly** [comment]
server-side apply is supported since kubernetes 1.14, and we should turn this on.

**Comment by RainbowMango** [comment]
/close
As lack of activities. Feel free to reopen it if the problem has not been solved.
