### ISSUE TITLE
No Desceduler function

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#1503]
**What happened**:
I installed karmada offline and wanted to test the Descheduler function, but the pod of karmada-descheduler was not started
![image](https://user-images.githubusercontent.com/31637804/158965998-f1d8ed79-afb4-4adf-b587-0f6115c3a854.png)

- Karmada version:
   v1.1.0
- Others:
I installed karmada this way:
```
kubectl karmada init --crds /$HOME/crds.tar.gz
```

**Comment by RainbowMango** [comment]
Hi @luoMonkeyKing The v1.1.0 release didn't include `karmada-descheduler`, it will be included in v1.2.

For now, you can try it on the master branch.

**Comment by RainbowMango** [comment]
/remove-kind bug
/kind question
/close
Feel free to re-open if you want further discussion.
