### ISSUE TITLE
The `Latest` label is best set to `v1.1.1 release`

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1509]
**What happened**:
Now the `Latest` label is set to `v1.0.2 release` that is a bug fixed last version. Its display on the home page may mislead the users.

**What you expected to happen**:
The `v1.1.1 release` should be a latest version.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by lonelyCZ** [comment]
cc @RainbowMango

**Comment by RainbowMango** [comment]
Do you mean [latest release](https://github.com/karmada-io/karmada/releases/latest) is wrong?

It is how GitHub identifies the `latest` release, not set by maintainers. GitHub will find the latest tag from `master` branch and take that tag as the `latest`.

**Comment by lonelyCZ** [comment]
Got it, I thought maintainers could set it.

**Comment by RainbowMango** [comment]
We cut the `v1.0.0` from the master branch, but for the `v1.1.0` we cut the release from the `release-1.1` branch. The GitHub always takes the tag from the master branch, so that's the reason. 

Anyway, I guess the next `v1.2.0` will be cut from the master, just like the way we did for `v1.0.0`.

**Comment by lonelyCZ** [comment]
Right, I see, thanks. :)
