### ISSUE TITLE
本地调试运行控制面scheduler报错

### ISSUE THREAD

**Issue by wangfeng1983** [karmada-io/karmada#1529]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
![image](https://user-images.githubusercontent.com/98692607/159831729-b60c026e-e6c0-4639-b243-91886de74cbc.png)
在本地的mac上通过kind创建了k8s集群，然后将自定义的crd apply上去，在golang工具种调试scheduler模块指定本地k8s的kubeconfig链接，出现这个错误，自定义扩展的crd也出现这种服务端找不到资源定义的情况，不知道有哪里需要注意的
**Environment**:
- Karmada version:
1.1
- Kubernetes version:
1.23
- Others:

**Comment by RainbowMango** [comment]
How to reproduce it (as minimally and precisely as possible)?

**Comment by wangfeng1983** [comment]
> How to reproduce it (as minimally and precisely as possible)?

我就是直接在goland 里面，启动配置了指定的kubeconfig
![企业微信截图_31fb120c-dea6-489b-8a4f-0baad868d63d](https://user-images.githubusercontent.com/98692607/159836286-9c560ebd-db8a-40c4-9281-05e2170be17f.png)

然后直接运行的
![企业微信截图_66302feb-fb94-46c7-bd91-987af10374ad](https://user-images.githubusercontent.com/98692607/159836393-7a7445cd-8d3e-46da-ae94-f7a3d9d3e8f3.png)

**Comment by wangfeng1983** [comment]
> > How to reproduce it (as minimally and precisely as possible)?
> 
> 我就是直接在goland 里面，启动配置了指定的kubeconfig ![企业微信截图_31fb120c-dea6-489b-8a4f-0baad868d63d](https://user-images.githubusercontent.com/98692607/159836286-9c560ebd-db8a-40c4-9281-05e2170be17f.png)
> 
> 然后直接运行的 ![企业微信截图_66302feb-fb94-46c7-bd91-987af10374ad](https://user-images.githubusercontent.com/98692607/159836393-7a7445cd-8d3e-46da-ae94-f7a3d9d3e8f3.png)

**Comment by wangfeng1983** [comment]
> How to reproduce it (as minimally and precisely as possible)?

也临时注释了选主的代码，所以应该可以直接运行scheduler进程，连到本地的k8s集群上去，本地k8s集群已经创建了相应的crd
![image](https://user-images.githubusercontent.com/98692607/159837263-555e2e30-31e5-490a-a42c-a094d26089b0.png)

**Comment by wangfeng1983** [comment]
> How to reproduce it (as minimally and precisely as possible)?

不小心被我关了，我重新关联一个新的issue打开了，谢谢！
