### ISSUE TITLE
> How to reproduce it (as minimally and precisely as possible)?

### ISSUE THREAD

**Issue by wangfeng1983** [karmada-io/karmada#1531]
> How to reproduce it (as minimally and precisely as possible)?

也临时注释了选主的代码，所以应该可以直接运行scheduler进程，连到本地的k8s集群上去，本地k8s集群已经创建了相应的crd
![image](https://user-images.githubusercontent.com/98692607/159837263-555e2e30-31e5-490a-a42c-a094d26089b0.png)

_Originally posted by @wangfeng1983 in https://github.com/karmada-io/karmada/issues/1529#issuecomment-1077034925_

**Comment by wangfeng1983** [comment]
[](https://user-images.githubusercontent.com/98692607/159836286-9c560ebd-db8a-40c4-9281-05e2170be17f.png)[](https://user-images.githubusercontent.com/98692607/159836393-7a7445cd-8d3e-46da-ae94-f7a3d9d3e8f3.png)我就是直接在goland 里面，启动配置了指定的kubeconfig
企业微信截图_31fb120c-dea6-489b-8a4f-0baad868d63d

然后直接运行的
企业微信截图_66302feb-fb94-46c7-bd91-987af10374ad

**Comment by pigletfly** [comment]
是否在对应的集群中安装了 karmada 的 crd ?

**Comment by wangfeng1983** [comment]
> 是否在对应的集群中安装了 karmada 的 crd ?

安装了
![image](https://user-images.githubusercontent.com/98692607/159848163-524f9bfc-bd13-4ca0-9ee1-aac897198274.png)

**Comment by wangfeng1983** [comment]
> 是否在对应的集群中安装了 karmada 的 crd ?

抱歉，我已经找到原因，我可以关闭这个issue了，非常感谢支持！

**Comment by XiShanYongYe-Chang** [comment]
可以把找到的原因贴到当前issue中。
