### ISSUE TITLE
咨询下*v1alpha1.Cluster这个CR资源是在哪个yaml创建的

### ISSUE THREAD

**Issue by wangfeng1983** [karmada-io/karmada#1534]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
`Cluster`是目前唯一一种不用CRD扩展的资源，而是用的aggregate-apiserver扩展的。

**Comment by RainbowMango** [comment]
For more details, please refer to #1122.

**Comment by wangfeng1983** [comment]
> For more details, please refer to #1122.

了解了，就是我要是本地调试，必须要连aggregate-apiserver
