### ISSUE TITLE
API Go Pkg that can be referenced by other go tools

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1541]
**What would you like to be added**:

API Go package. Similar to:

https://pkg.go.dev/volcano.sh/apis@v1.5.0-beta.0

The package can be installed by `go get`

**Why is this needed**:

Third party go tools may need the api defined in Karmada.

**Comment by RainbowMango** [comment]
Do you mean https://pkg.go.dev/github.com/karmada-io/api and https://pkg.go.dev/github.com/karmada-io/karmada ?

**Comment by stingshen** [comment]
Yes. That is exactly what I need. Thank you!
