### ISSUE TITLE
why statefulset and daemonset were not ready？

### ISSUE THREAD

**Issue by maidol** [karmada-io/karmada#1544]
### **why statefulset and daemonset were not ready status？The deployment was all right.**

deployment
![微信图片_20220325193423](https://user-images.githubusercontent.com/4978561/160113690-8500e701-22ea-48df-a339-43363f01a130.png)

statefulset
![微信图片_20220325193552](https://user-images.githubusercontent.com/4978561/160113876-5a951963-1010-4909-a9e8-57f4d627e7b6.png)

daemonset
![微信图片_20220325193604](https://user-images.githubusercontent.com/4978561/160113945-974f3e13-4bbb-413d-bd7d-063ad1139f50.png)

**Environment**:
- Karmada version: v1.1.1
- Kubernetes version: v1.21.5+k3s2

**Comment by lonelyCZ** [comment]
It seem not to implement default `aggregateStatefulsetStatus` and `aggregateDaemonsetStatus` in resourceinterpreter.

https://github.com/karmada-io/karmada/blob/a084c8d7b09e7c3b361eea7137b86d4ed1fe3d20/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go#L22-L29

**Comment by RainbowMango** [comment]
Yes, exactly as @lonelyCZ mentioned above.

It will be pretty easy to support `Statefulset` and `Daemonset` I guess. 

@maidol Would you like to share your use case with us?

**Comment by RainbowMango** [comment]
/assign @Poor12 
As I see a PR for this issue.
