### ISSUE TITLE
Add cluster-proxy-rbac for admin in multiple installation modes

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1546]
**What would you like to be added**:
We have introduced `cluster-proxy-admin-rbac.yaml` when use script to deploy Karmada at #1527 , we need to introduce it in other installation modes.

- [x] karmadactl init (#1550 by @AllenZMC )
- [x] helm (#1547  by @AllenZMC )

**Comment by chinmaym07** [comment]
Hey Can I try work on the first one ? Please do guide me a little on this . I want to try it out.

**Comment by RainbowMango** [comment]
Hi @chinmaym07 , this issue has been picked by @AllenZMC, thank you all the same.

This issue might be a little bit involved for you.  I can cc you when there are some appropriate tasks.

**Comment by RainbowMango** [comment]
Good job @lonelyCZ , I totally forgot this.

**Comment by RainbowMango** [comment]
/assign @AllenZMC 
(correct the wrong command/typo)
