### ISSUE TITLE
Request to be a member of Karmada

### ISSUE THREAD

**Issue by Arhell** [karmada-io/karmada#1554]
Hello 
My contributions
https://github.com/karmada-io/website/issues/created_by/Arhell
https://github.com/karmada-io/website/issues?q=is%3Aissue+author%3AArhell+is%3Aclosed

PRs
https://github.com/karmada-io/website/pulls/Arhell
https://github.com/karmada-io/website/pulls?q=is%3Apr+author%3AArhell+is%3Aclosed

I want to improve the site, fix bugs, ui , accessibility and more.

Thanks for attention!

@RainbowMango

**Comment by RainbowMango** [comment]
+1 
Thanks @Arhell for your contributions.
/assign @kevin-wangzefeng

**Comment by RainbowMango** [comment]
Kindly ping @Arhell, have you received the invitation?

**Comment by RainbowMango** [comment]
/close
Welcome, @Arhell !
