### ISSUE TITLE
it's failed  that installed with helm for used other namespaces 

### ISSUE THREAD

**Issue by guyingyan** [karmada-io/karmada#1557]
installed release 1.1.0 with helm , did not use  karmada-system, but used other namespace 

helm install karmada -n test --create-namespace ./charts

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Poor12** [comment]
I tried to install karmada without karmada-system. And It works.
![image](https://user-images.githubusercontent.com/26862112/162958437-54d12530-87d6-43e4-b180-f5b1a77e99ae.png)

**Comment by RainbowMango** [comment]
Hi @guyingyan sorry for letting this sit so long. I missed this issue.

Please tell us more details about what happened, any logs?

**Comment by XiShanYongYe-Chang** [comment]
Close this first, please feel free to reopen it if you occur the same errors.

/close
