### ISSUE TITLE
Proposal for English meeting time

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1560]
For now, the community running [a regular bi-weekly](https://github.com/karmada-io/karmada#meeting) meeting with Chinese.

We are glad to set up another meeting with folks who speak English.
If you are interested in joining the meeting, please feel free to propose a meeting time by reply to this issue.

**Comment by chinmaym07** [comment]
India Standard Time
1:00 pm to 2:00 pm IST
(13:00 to 14:00 IST)

GMT+8
3:30 pm to 4:30 pm GMT+8
(15:30 to 16:30 GMT+8)

**Comment by mikeshng** [comment]
I want to propose 16:00 UTC which is noon time for NA EST but that will be kind of late for participants from China.

Is there a particular time range to choose from? Is it 9AM to 5PM Shanghai time?

It will be nice if the English meeting is recorded and uploaded to somewhere as well. Thanks.

**Comment by anu491** [comment]
I have been to community meetings of some orgs before and I am looking forward to having one with the community here at Karmada :smiley: 

```
Day : Anyday (week days preferred)
Time : 30 mins - 1 hour slot anytime after 4 pm GMT+8
```

**Comment by lewismacdonald** [comment]
Any time 9am-8pm US EST would be great.

**Comment by ryanzhang-oss** [comment]
Any time 10am-6pm US PST would be great.

**Comment by jpedro1992** [comment]
I am interested in joining the meetings. 

Since I am in EU-CET, between 2:00 pm - 6:00 pm CET would be best, but it is hard to find a friendly time for all people (EU, US, Asia). My suggestion results in: 

EST: 8:00am - 1:00pm 
PST: 5:00am - 10:00am
CST: 9:00pm - 2:00 am

**Comment by RainbowMango** [comment]
Thanks @jpedro1992 .
I hope we can start the meeting at the beginning of February.

**Comment by bhavyastar** [comment]
Hey @RainbowMango 
It is good if we can start English meetings as well.

**Comment by rakshitgondwal** [comment]
I am interested in joining the English meetings as well! @RainbowMango

**Comment by taniaduggal** [comment]
I am also interested to join the English meetings :)

**Comment by RainbowMango** [comment]
Hey folks, thanks for proposing the meeting time. 
It's very difficult to pick a time that is good for everyone. But we can try to have our first call on `Tuesday, May 16th`([Convert to your time](https://dateful.com/convert/pt-pacific-time?t=08&d=2023-05-16)).  We can talk about the meeting time there if you want to adjust it.

Please feel free to add your agenda on the [meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.xom4jxumka6a).  (By [joining the google groups](https://groups.google.com/forum/#!forum/karmada) you will be able to edit the meeting notes.)

Looking forward to meeting you there~

**Comment by RainbowMango** [comment]
Hello folks,
Reminder, the first English Karmada Community Metting is scheduled for this Tuesday (16/04/2023 @ 8am PT) (Convert to your timezone)[https://dateful.com/convert/pt-pacific-time?t=08&d=2023-05-16]
Zoom: https://zoom.com/my/karmada
Meeting Notes: https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit
