### ISSUE TITLE
In pull mode, can karmada be able to get pod logs and exec pod like kubeedge

### ISSUE THREAD

**Issue by prodanlabs** [karmada-io/karmada#1568]
I personally think there are many similarities between pull mode and `kubeedge` edge, can karmada learn from kubeedge to enhance pull mode, e.g.  `get pod logs`, `exec  pod`. What do you think :)

**Comment by lonelyCZ** [comment]
Cool, directly access to pod from control plane, it can collaborate with `karmadactl get`. 

Like,
```
karmadactl logs <pod-name> -n <namespace> -c <cluster-name>
karmadactl exec pod <pod-name> -n <namespace> -c <cluster-name>
```

**Comment by lonelyCZ** [comment]
I am still interested in this feature, but I don't know actual needs of customers. Look forward to more discussions in this issue.

**Comment by prodanlabs** [comment]
> I am still interested in this feature, but I don't know actual needs of customers. Look forward to more discussions in this issue.

I also think it's a nice feature, as it was discussed on kubeedge and a lot of people love it.

**Comment by prodanlabs** [comment]
> @prodanlabs I'm not sure I understand you correctly, can you give an example or more details about the use case?


Now the karmada control plane is unable to get the pod logs of the member cluster (pull mode) 
like
```
karmadactl logs <pod-name> -n <namespace> -c <cluster-name>
```
 or pods that cannot be entered into a member cluster (pull mode) via on the karmada control plane
```
karmadactl exec pod <pod-name> -n <namespace> -c <cluster-name>

**Comment by lonelyCZ** [comment]
My understand that for pull mode cluster, it is like `Node` that is One-sided communicate with control plane. For kubeedge, it seemingly erect a tunnel to access nodes.

**Comment by prodanlabs** [comment]
Like in the cloud kubedge can use `kubectl exec -it <pod_name>` to enter the pod of the edge node

**Comment by lonelyCZ** [comment]
But now, we also need to access apiserver of member cluster by third-party networking tools like [ANP](https://github.com/karmada-io/karmada/blob/master/docs/working-with-anp.md). Similarly, we also need to erect a extra tunnel to access pod.

**Comment by RainbowMango** [comment]
Yes, I like the feature.

**Comment by prodanlabs** [comment]
kubeedge does a lot of work on the cloud-edge network link, so this functionality is relatively easy for kubeedge. How does karmada implement this function elegantly, I currently have no good solution.

**Comment by lonelyCZ** [comment]
I think we need a network plugin that can support to access directly to nodes from control plane. This plugin can be installed according to the user's choice.

**Comment by GitHubxsy** [comment]
![image](https://user-images.githubusercontent.com/11901080/161077196-e600093f-871b-4a8f-ab82-0c492201e750.png)

If the network problem is caused by the internal cluster, the problem should be solved in cluster instead of karmada.

**Comment by lonelyCZ** [comment]
> After the APIServer is connected, the pod can be accessed. Am I misunderstood?

There seems other port to access containers of pod for `logs` and `exec` commands rather than through `apiserver`.

refer https://kubernetes.io/docs/concepts/cluster-administration/logging/

**Comment by XiShanYongYe-Chang** [comment]
We can `logs` and `exec` throuth `clusters/proxy`, why `other port to access containers of pod`?

**Comment by lonelyCZ** [comment]
> We can `logs` and `exec` throuth `clusters/proxy`, why `other port to access containers of pod`?

I don't know the exact mechanism yet. I am going to research it in this time, perhaps we can discuss it in next community meeting.

**Comment by RainbowMango** [comment]
Thanks @lonelyCZ .
/assign @lonelyCZ

**Comment by lonelyCZ** [comment]
> ![image](https://user-images.githubusercontent.com/11901080/161077196-e600093f-871b-4a8f-ab82-0c492201e750.png)
> 
> If the network problem is caused by the internal cluster, the problem should be solved in cluster instead of karmada.

I agree with it!

I found that get logs of container in kubernetes only accessing api (like `api/v1/namespaces/default/pods/nginx-6799fc88d8-9mpxn/log?container=nginx`) that internally implements a set of methods to get logs.

In Kubeedge, because it cuts some of the functionality of K8S, it needs to implement log collection by itself. It redirects the interface for getting logs to its own implementation by [modifying `iptables`](https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature) .

So if logs are normally accessible in a member cluster, they can be accessed at a multi-cloud level using 'cluster-proxy'.

I implement a demo at #1597

**Comment by lonelyCZ** [comment]
I think we only introduce `get`、`logs`、`exec`、`describe` command to `karmadactl`, which can easily view the status of member clusters. We don't need to change the status of member clusters from `karmada control plane`, so there is no need to introduce other commands.

And the commands are optional for user, if you don't use `karmadactl`, you only need to configurate `kubectl` to support `cluster-proxy`.

What do you think? @GitHubxsy

**Comment by GitHubxsy** [comment]
@lonelyCZ  Can we directly reuse kubectl?
1、kubectl binary（Tell kubectl binary path）
2、Reference the kubectl code.（Can we?）
![image](https://user-images.githubusercontent.com/11901080/165296172-11194f60-b869-46a5-a6cf-8caa1720d198.png)


In multi-cluster scenarios, you can run the kubectl command multiple times.
![image](https://user-images.githubusercontent.com/11901080/165297364-92e52d23-ff90-4049-aef6-d691a0ef7105.png)


Karmada enable kubectl. It supports all the original commands of kubectl. Karmactl supports kubectl as a multi-cluster command tool.

Maybe we can reference [gorunner](https://github.com/kubernetes/kubernetes/blob/1c93be24ee8a/build/go-runner/go-runner.go)'s idea.

**Comment by lonelyCZ** [comment]
Hi, @GitHubxsy , the scheme is cool, but I think we don't need to support all commands from `kubectl` in `karmadactl`.

We only introduce most frequently-used command to `karmadactl` to view the status of member clusters, we don't need to change the status of member clusters.

It is not recommended to use the `karmadactl` command to modify resources in member clusters, that is more used for controlling resources in karmada control plane, like `taint cluster`

> Karmada enable kubectl. It supports all the original commands of kubectl. Karmactl supports kubectl as a multi-cluster command tool.

When we add a new cluster, we still need to modify the Kubeconfig file, so I think this is better left to the user to configure and  use `kubectl` to operate each cluster.

**Comment by GitHubxsy** [comment]
> Hi, @GitHubxsy , the scheme is cool, but I think we don't need to support all commands from `kubectl` in `karmadactl`.
> 
> We only introduce most frequently-used command to `karmadactl` to view the status of member clusters, we don't need to change the status of member clusters.
> 
> It is not recommended to use the `karmadactl` command to modify resources in member clusters, that is more used for controlling resources in karmada control plane, like `taint cluster`
> 
> > Karmada enable kubectl. It supports all the original commands of kubectl. Karmactl supports kubectl as a multi-cluster command tool.
> 
> When we add a new cluster, we still need to modify the Kubeconfig file, so I think this is better left to the user to configure and use `kubectl` to operate each cluster.

The kubeconfig file is generated by karmadactl and is stored in the temporary directory.
