### ISSUE TITLE
Error reported when executing `kubectl edit cluster`

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1571]
**What happened**:
When I executing `kubectl edit cluster member1`, there is a error whatever I do and even do nothing.

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# clusters.cluster.karmada.io "member1" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Cluster.metadata.managedFields[2]): unknown field "subresource" in io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
#
apiVersion: cluster.karmada.io/v1alpha1
kind: Cluster
metadata:
......
```

I found that it is to delete `subresource: status` that will not to report error.

```
 - apiVersion: cluster.karmada.io/v1alpha1
    fieldsType: FieldsV1
   ......
    manager: karmada-agent
    operation: Update
    subresource: status
    time: "2022-03-31T21:45:19Z"
```

**What you expected to happen**:
There is no this error when edit cluster.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl edit cluster <cluster-name>
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Yeah, I reproduced this issue on my side.
I tried to add `.spec.provider` filed to a cluster, then I found
```
# clusters.cluster.karmada.io "member1" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Cluster.metadata.managedFields[2]): unknown field "subresource" in io.k8s.apimachinery.pkg.apis.meta.v1.ManagedFieldsEntry
```
cc @XiShanYongYe-Chang 
/priority important-soon

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ @RainbowMango , I edit cluster object successfully:
```
# kubectl edit cluster member1
cluster.cluster.karmada.io/member1 edited
```
Is it related to the kubectl version in use?

**Comment by RainbowMango** [comment]
My kubectl :
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
I'll try one a newer version.

**Comment by XiShanYongYe-Chang** [comment]
I use kubectl version `v1.22.3` and `v1.23.1` test ok.

**Comment by lonelyCZ** [comment]
I also this version.

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by RainbowMango** [comment]
After I update `kubectl` from `1.18.0` to `v1.23.5`, It works fine.

I guess we need to find the root cause and add an item to [Troubleshooting](https://github.com/karmada-io/karmada/blob/master/docs/troubleshooting.md).

**Comment by lonelyCZ** [comment]
I test `kubectl` of `v1.19.16` that is ok.

**Comment by XiShanYongYe-Chang** [comment]
> I guess we need to find the root cause and add an item to [Troubleshooting](https://github.com/karmada-io/karmada/blob/master/docs/troubleshooting.md).

I will try to find it.

**Comment by XiShanYongYe-Chang** [comment]
> I test `kubectl` of `v1.19.16` that is ok.

Looks like we can start with kubectl version 1.18.

**Comment by RainbowMango** [comment]
https://github.com/kubernetes/kubernetes/pull/91946

That's might be the reason why it works for 1.19+.

**Comment by XiShanYongYe-Chang** [comment]
Can this issue be closed?
