### ISSUE TITLE
When karmada call interperter webhook server failed, karmada controller will panic

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1578]
**What happened**:
karmada controller panic when call interpreter webhook failed, the following is the stack information:
```
I0402 15:12:53.420134      23 interpreter.go:104] Begin to revise replicas for object: apps/v1, Kind=Deployment default/nginx.
E0402 15:12:53.427640      23 common.go:101] failed to revise replica for Deployment/default/nginx in cluster test-c-rz, err is: Internal error occurred: get nil response from webhook call
E0402 15:12:53.427674      23 binding_controller.go:125] Failed to transform resourceBinding(default/nginx-deployment) to works. Error: Internal error occurred: get nil response from webhook call.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19ecea9]

goroutine 2953 [running]:
github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter/webhook.verifyResourceInterpreterContext({0x1f3d2ed, 0x1}, 0xc000d14f00)
	/Users/momo/go/src/git.wemomo.com/sa/octopus/karmada/pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go:112 +0x189
github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter/webhook.VerifyResourceInterpreterContext({0xc001241380, 0x1f430c1}, {0x1f3d2ed, 0xd}, {0x21ef590, 0xc00138ac00})
	/Users/momo/go/src/git.wemomo.com/sa/octopus/karmada/pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go:72 +0x2ad
github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter.(*CustomizedInterpreter).callHook(0xc000a1f0e0, {0x220d4e8, 0xc000054098}, {0x22439f8, 0xc000a14820}, 0xc000d7ef40)
	/Users/momo/go/src/git.wemomo.com/sa/octopus/karmada/pkg/resourceinterpreter/customizedinterpreter/customized.go:233 +0xb9e
github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter.(*CustomizedInterpreter).interpret.func1({0x22439f8, 0xc000a14820})
	/Users/momo/go/src/git.wemomo.com/sa/octopus/karmada/pkg/resourceinterpreter/customizedinterpreter/customized.go:145 +0xb9
created by github.com/karmada-io/karmada/pkg/resourceinterpreter/customizedinterpreter.(*CustomizedInterpreter).interpret
	/Users/momo/go/src/git.wemomo.com/sa/octopus/karmada/pkg/resourceinterpreter/customizedinterpreter/customized.go:143 +0x409
```

**What you expected to happen**:
Should print out the call failure message, not panic

**How to reproduce it (as minimally and precisely as possible)**:
I create interpreter webhook for deployment, like follow message
```
webhooks:
- clientConfig:
    caBundle:  ===
    url: https://xxxxx/interpreter-workload
  interpreterContextVersions:
  - v1alpha1
  name: deployment.interpreter.webhook
  rules:
  - apiGroups:
    - apps
    apiVersions:
    - v1
    kinds:
    - Deployment
    operations:
    - InterpretReplica
    - ReviseReplica
    - Retain
    - AggregateStatus
  timeoutSeconds: 3
```
**Anything else we need to know?**:

**Environment**:
k8s v1.18.2
- Karmada version:
v 1.1.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
k8s  mutatingwebhook failurePolicy support failurePolicy, karmada interterper  webhook whether to support failurePolicy field

**Comment by RainbowMango** [comment]
> Should print out the call failure message, not panic

Agree. The panic happened after invoking the webhook, right? From the stack backtrace, I can't see the line where panics. Can you remind me?

**Comment by CharlesQQ** [comment]
The interpreter webhook is similar example in karamda, when no patch data, response's Patch and PatchType field is nil
<img width="673" alt="image" src="https://user-images.githubusercontent.com/18431718/161376938-3ecc2182-69bb-4ae8-90cf-9e7d6750aba2.png">

the panic happend in here
<img width="866" alt="image" src="https://user-images.githubusercontent.com/18431718/161377018-6fadfaf7-22e6-424c-8c1c-5a733f378b2e.png">

**Comment by XiShanYongYe-Chang** [comment]
Hi, @CharlesQQ , we have check response with func `verifyResourceInterpreterContextWithPatch`:

https://github.com/karmada-io/karmada/blob/7a1e96ea45817918c8df88b0b6e2a2b089a34901/pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go#L127-L129

There should be no panic.

**Comment by CharlesQQ** [comment]
The interpreter webhook server is similar example in karamda, when no patch data, response's Patch and PatchType field is nil, here is webhook server response code
<img width="673" alt="image" src="https://user-images.githubusercontent.com/18431718/161376938-3ecc2182-69bb-4ae8-90cf-9e7d6750aba2.png">

the controller panic happend in here, it's a bug
<img width="866" alt="image" src="https://user-images.githubusercontent.com/18431718/161377018-6fadfaf7-22e6-424c-8c1c-5a733f378b2e.png">

**Comment by XiShanYongYe-Chang** [comment]
@CharlesQQ , of course you can fix bugs, but I think here will occur no panic. It's somewhere else that's wrong.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @RainbowMango, It is indeed the mistake you pointed out. Can you help to fix it?

**Comment by CharlesQQ** [comment]
@XiShanYongYe-Chang Ok

**Comment by RainbowMango** [comment]
/assign @CharlesQQ 
Thanks~~.
