### ISSUE TITLE
error: You must be logged in to the server (the server has asked for the client to provide credentials)

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#1585]
**Please provide an in-depth description of the question you have**:
```
Karmada API Server's IP is: 192.168.229.135, host cluster type is: remote
Cluster "karmada-apiserver" set.
User "karmada-apiserver" set.
Context "karmada-apiserver" modified.
deployment.apps/karmada-kube-controller-manager created
deployment.apps/karmada-aggregated-apiserver created
service/karmada-aggregated-apiserver created
wait the karmada-aggregated-apiserver ready...
pod/karmada-aggregated-apiserver-7b88b8df99-d9d52 condition met
pod/karmada-aggregated-apiserver-7b88b8df99-q4nrp condition met
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
**What do you think about this question?**:

**Environment**:
- Karmada version:
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version:
[root@node01 karmada]# kubectl version --short
Client Version: v1.21.0
Server Version: v1.21.7
- Others:

**Comment by lonelyCZ** [comment]
Could you give us more information? What command do you use to deploy Karmada? And you can check the pod status in other terminal when you is executing this command.

**Comment by 13567436138** [comment]
./hack/remote-up-karmada.sh /root/.kube/config context-cluster1  false

**Comment by lonelyCZ** [comment]
I guess the error happened in phase of installing CRD in `karmada-apiserver`.

https://github.com/karmada-io/karmada/blob/b4be8be08d2b8bb5291b2d7707b5a7bd4a8e8ce6/hack/deploy-karmada.sh#L203-L220

Can you access normally the `karmada-apiserver` by using kubectl, `kubeconfig` and `karmada-apiserver context`?

**Comment by 13567436138** [comment]
```
[root@node01 ~]# kubectl config use-context karmada-apiserver
Switched to context "karmada-apiserver".
[root@node01 ~]# kubectl get pod -n kube-system
No resources found in kube-system namespace.
[root@node01 ~]# kubectl get pod --all-namespaces 
No resources found
[root@node01 ~]# kubectl get ns
NAME              STATUS   AGE
default           Active   2d16h
kube-node-lease   Active   2d16h
kube-public       Active   2d16h
kube-system       Active   2d16h
```

yes I can

**Comment by 13567436138** [comment]
[root@node01 karmada]# kubectl get pod --all-namespaces 
error: You must be logged in to the server (Unauthorized)

**Comment by lonelyCZ** [comment]
> [root@node01 karmada]# kubectl get pod --all-namespaces
> error: You must be logged in to the server (Unauthorized)

It is probably certificate problem, why there is different from above? Did you perform any operations？

**Comment by lonelyCZ** [comment]
You could check `/root/.kube/config` and the status of `karmada-apiserver` pod.
