### ISSUE TITLE
Uninstall karmada using helm is not clean

### ISSUE THREAD

**Issue by hzxuzhonghu** [karmada-io/karmada#1587]
**What happened**:

I tried install karmada controlplane by helm, and a little while later I tried to uninstall it following https://github.com/karmada-io/karmada/tree/master/charts#uninstalling-the-chart

But I found after uninstall finished, there are still many resources left. Like secret, configmap. 

**What you expected to happen**:

All resources created by install including karmada-system should be cleaned.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
/assign @Poor12 
as #1602
