### ISSUE TITLE
helm: cluster proxy rbac should be installed in karmada-apiserver

### ISSUE THREAD

**Issue by fanzhihai0215** [karmada-io/karmada#1594]
**What happened**:
`proxy-rbac` is in host cluster rather than karmada-apiserver. 

**How to reproduce it (as minimally and precisely as possible)**:
Install karmada with helm.
```
# kubectl --kubeconfig karmada-host.config -n karmada-system get clusterrole
NAME                                                                   CREATED AT
admin                                                                  2022-04-08T08:36:12Z
cluster-admin                                                          2022-04-08T08:36:12Z
edit                                                                   2022-04-08T08:36:12Z
karmada-cluster-proxy-admin                                            2022-04-08T09:23:12Z
......
```
`kubectl --kubeconfig karmada-apiserver.config get clusterrole | grep proxy` return nothing.

**Environment**:
- Karmada version: master

**Comment by AllenZMC** [comment]
Is your k8s cluster deployed with kubeadm or kind? @fanzhihai0215

**Comment by fanzhihai0215** [comment]
> Is your k8s cluster deployed with kubeadm or kind? @fanzhihai0215 I can't install karmada in kind.

kind.  

BTW. I suggest load all images in advance using `kind load docker-image`. I feel your network is not good. Too much time to pull images...

@AllenZMC

**Comment by AllenZMC** [comment]
OK. What command did you use: helm or `hack/remote-up-karmada.sh`? Is your kind a single node?

**Comment by fanzhihai0215** [comment]
> OK. What command did you use: helm or `hack/remote-up-karmada.sh`? 

helm.

> Is your kind a single node?

Yes. 
```
# kubectl --kubeconfig karmada-host.config get node
NAME                        STATUS   ROLES                  AGE     VERSION
karmada-1.1-control-plane   Ready    control-plane,master   2d16h   v1.22.0
```

@AllenZMC

**Comment by AllenZMC** [comment]
How do you get and use the karmada apiserver kubeconfig? @fanzhihai0215

**Comment by fanzhihai0215** [comment]
> How do you get and use the karmada apiserver kubeconfig? @fanzhihai0215

get: `$ kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d`

Set karmada apiserver kubeconfig `insecure-skip-tls-verify: true` and remove `certificate-authority-data`. You should use kubeconfig in the kind container. Because you are out of the karmada apiserver cluster.

@AllenZMC

**Comment by AllenZMC** [comment]
Thanks, what container image are you using? @fanzhihai0215

**Comment by fanzhihai0215** [comment]
> Thanks, what container image are you using? @fanzhihai0215

kindest/node:v1.22.0

**Comment by AllenZMC** [comment]
How are you running this container? @fanzhihai0215
