### ISSUE TITLE
How to ReScheduler workloads like ConfigMap when add new clusters 

### ISSUE THREAD

**Issue by qianjun1993** [karmada-io/karmada#1601]
**What would you like to be added**:
A new scheduler condition for workloads like ConfigMap when new clusters add 

**Why is this needed**:
For example we have a  ConfigMap and at least one deployment for one work, so they have the same PP. In first schedule, they are scheduled to cluster A and B with label X . And then we add Cluster C with label X to Karmada.  After that , we scale up these deployment , and they may be schedule to the new clusters while the ConfigMap will not . In that case , deployments in cluster C  can not work.

**Comment by hanweisen** [comment]
I found a proposal `docs/proposals/dependencies-automatically-propagation/README.md` may resolve your problem. But I don't know whether it has been done in current release.

**Comment by RainbowMango** [comment]
Sorry @qianjun1993 , I missed this :(

Yes, we can do that as @hanweisen mentioned feature. This feature has been released at v1.1.0. (but the document is missing...).

**Comment by hanweisen** [comment]
> Sorry @qianjun1993 , I missed this :(
> 
> Yes, we can do that as @hanweisen mentioned feature. This feature has been released at v1.1.0. (but the document is missing...).

Do you have any plan add this document? or Let me add this document. @RainbowMango

**Comment by RainbowMango** [comment]
Many thanks in advance. @mrlihanbo Could you please find the PR that enables the dependencies future?

**Comment by hanweisen** [comment]
OK，I find a switch a feturegate. I'll try this
```

**Comment by qianjun1993** [comment]
Thanks

**Comment by XiShanYongYe-Chang** [comment]
It seems that the problem has been resolved.
/close
