### ISSUE TITLE
[Docs] tutorial of working with Open Policy Agent

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1614]
**What would you like to be added**:
We need a demo to run OPA on the Karmada control plane to see if there is any change needed. And after that, we can provide a tutorial to describe how to run OPA on Karmada. So the tasks would be:
- [ ] Run a demo with OPA( by precisely [Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/howto) )
- [ ] Make changes to Karmada if there are any
- [ ] Make a tutorial document

Reference:
- [How to use Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/howto)
- [Installing Gatekeeper](https://open-policy-agent.github.io/gatekeeper/website/docs/install)
- [Gatekeeper Examples](https://open-policy-agent.github.io/gatekeeper/website/docs/examples)

**Why is this needed**:
The [Open Policy Agent](https://www.openpolicyagent.org/)  is a well-known policy engine and adopted by a large number of users.
Karmada has been asked to support OPA. 

In addition, Karmada still needs to enforce policies for security and compliance purposes.

**Comment by prodanlabs** [comment]
Oh, I've been researching this direction recently too.I look forward to it.

**Comment by RainbowMango** [comment]
That's great @prodanlabs , I got one for source to hear user cases.

> In addition, Karmada still needs to enforce policies for security and compliance purposes.

I'm thinking about what kind of policies users want to enforce security and compliance when using Karmada.

**Comment by prodanlabs** [comment]
> That's great @prodanlabs , I got one for source to hear user cases.
> 
> > In addition, Karmada still needs to enforce policies for security and compliance purposes.
> 
> I'm thinking about what kind of policies users want to enforce security and compliance when using Karmada.

Enforce security, such as removing namespaces and CRDs.

Compliance policies, such as when there are multiple versions of CRDs, create operation users can only use the latest version.

I think these questions are relatively common. Currently we implement it through webhook, OPA should be more elegant.
