### ISSUE TITLE
Request to be a Member of Karmada

### ISSUE THREAD

**Issue by AllenZMC** [karmada-io/karmada#1615]
I'm requesting to be a Member of Karmada.
Recently，I started to to participate in the development of the community and submit PRs 14+
PRs：
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3AAllenZMC+is%3Aclosed+

<img width="491" alt="企业微信截图_a88e6575-421b-4aab-9a2a-ddfab5fbeddd" src="https://user-images.githubusercontent.com/49428979/163397902-1b5e213e-8030-4537-9b71-ae9c0760a44d.png">

Hope bring more improvements for Karmada in the future.

**Comment by AllenZMC** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by XiShanYongYe-Chang** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invited, please visit https://github.com/karmada-io to accept invitation.
