### ISSUE TITLE
cluster/proxy 下长链接问题

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#1618]
**What happened**:
使用cluster/proxy来测试watch、logs -f、exec操作，均有失败结果。

0. 准备
```
$ cat ~/.kube/karmada-cluster-2.config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://192.168.50.183:32443/apis/cluster.karmada.io/v1alpha1/clusters/cluster2/proxy
```

2. Watch
```
$ kubectl --kubeconfig ~/.kube/karmada-cluster-2.config get po -w
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6d8dbbb794-lrp9f   1/1     Running   0          9m15s
nginx-6d8dbbb794-r4sq6   1/1     Running   0          9m15s
STATUS                   REASON          MESSAGE
Failure                  InternalError   an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 69; INTERNAL_ERROR; received from peer") has prevented the request from succeeding
```

3. logs
```
$ kubectl --kubeconfig ~/.kube/karmada-cluster-2.config logs -f nginx-6d8dbbb794-lrp9f
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/04/15 10:19:52 [notice] 1#1: using the "epoll" event method
2022/04/15 10:19:52 [notice] 1#1: nginx/1.21.6
2022/04/15 10:19:52 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027)
2022/04/15 10:19:52 [notice] 1#1: OS: Linux 4.19.202
2022/04/15 10:19:52 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/04/15 10:19:52 [notice] 1#1: start worker processes
2022/04/15 10:19:52 [notice] 1#1: start worker process 33
2022/04/15 10:19:52 [notice] 1#1: start worker process 34
error: stream error: stream ID 3; INTERNAL_ERROR; received from peer
```

4. exec
```
$ kubectl --kubeconfig ~/.kube/karmada-cluster-2.config exec -ti nginx-6d8dbbb794-lrp9f sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr
```

**Environment**:
- Karmada version: v1.1.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): karmadactl version: version.Info{GitVersion:"v1.1.0-138-gddd4cc29", GitCommit:"ddd4cc29929d8f4ce79fbe40a71f1765e2484649", GitTreeState:"clean", BuildDate:"2022-03-22T07:50:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
- Others:

**Comment by RainbowMango** [comment]
cc @XiShanYongYe-Chang @lonelyCZ @prodanlabs

**Comment by prodanlabs** [comment]
`logs` : seems to be caused by http timeout

`exec` : I also encountered, the connection forwarded by the proxy cannot be upgraded to `SPDY` or `websocket`, I am also looking for a solution

**Comment by prodanlabs** [comment]
I went back and tried setting the value of the Connection header to `Upgrade` to indicate that this was an upgrade request. I don't know if it would work :(

**Comment by lonelyCZ** [comment]
This problem will occur in about 30 seconds, I guess the proxy does not support long links now, we need to find out if it can be set.

**Comment by XiShanYongYe-Chang** [comment]
On my local site test, the process lasted about a minute:

```
time kubectl --kubeconfig karmada.config -n kube-system get po -A -w
...
NAMESPACE            STATUS                                          REASON          MESSAGE
                     Failure                                         InternalError   an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 3; INTERNAL_ERROR") has prevented the request from succeeding

real	1m0.067s
user	0m0.049s
sys	0m0.019s

time kubectl --kubeconfig karmada.config -n kube-system logs -f kube-controller-manager-member1-control-plane
...
error: stream error: stream ID 69; INTERNAL_ERROR

real	1m0.386s
user	0m0.138s
sys	0m0.173s
```

**Comment by lonelyCZ** [comment]
Right，one minute on my side.


```
time kubectl get pod --cluster=member2 -w
......
real	1m0.680s
user	0m0.202s
sys	0m0.156s
```

**Comment by XiShanYongYe-Chang** [comment]
the error info with watch `-w` and `logs` cmd:
```log
E0416 07:11:36.823069       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/pods?resourceVersion=293717&watch=true" audit-ID="b914c908-8bfe-4ea0-8d5a-3b21dbed7736"
2022/04/16 07:11:36 httputil: ReverseProxy read error during body copy: context deadline exceeded
E0416 07:11:36.824828       1 timeout.go:137] post-timeout activity - time-elapsed: 1.676031ms, GET "/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/pods" result: net/http: abort Handler

E0416 07:12:57.370995       1 wrap.go:54] timeout or abort while handling: method=GET URI="/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/namespaces/kube-system/pods/kube-controller-manager-member1-control-plane/log?container=kube-controller-manager&follow=true" audit-ID="9c283f45-7f69-4c8e-8efb-e5840c8480d5"
2022/04/16 07:12:57 httputil: ReverseProxy read error during body copy: context deadline exceeded
E0416 07:12:57.373356       1 timeout.go:137] post-timeout activity - time-elapsed: 2.222352ms, GET "/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/namespaces/kube-system/pods/kube-controller-manager-member1-control-plane/log" result: net/http: abort Handler
```

**Comment by XiShanYongYe-Chang** [comment]
> exec : I also encountered, the connection forwarded by the proxy cannot be upgraded to SPDY or websocket, I am also looking for a solution

Hi @ikaven1024 , as @prodanlabs said, the error of `exec` command is not the problem of `http keep-alive` or `request timeout`.  I have no idea how to fix it just now.

**Comment by prodanlabs** [comment]
> > exec : I also encountered, the connection forwarded by the proxy cannot be upgraded to SPDY or websocket, I am also looking for a solution
> 
> Hi @ikaven1024 , as @prodanlabs said, the error of `exec` command is not the problem of `http keep-alive` or `request timeout`. I have no idea how to fix it just now.


I used `websocket` to implement `exec` and also encountered the problem of `keepalive`. When requesting the gRPC endpoint, the keepalive time of the gRPC client is not within the allowable range of the server and an error is reported. The call chain of exec is very long, and I am still looking for the problem.
```
closing transport due to: connection error: desc = “error reading from server: EOF”, received prior goaway: code: ENHANCE_YOUR_CALM, debug data: “too_many_pings”
```

**Comment by lonelyCZ** [comment]
> I went back and tried setting the value of the Connection header to Upgrade to indicate that this was an upgrade request. 

I found we seemingly always disable `upgradeRequired`.

https://github.com/karmada-io/karmada/blob/5b3ef7d93f63daac0b396ef50fdacb4ab0f5ca48/pkg/registry/cluster/storage/proxy.go#L112

https://github.com/karmada-io/karmada/blob/5b3ef7d93f63daac0b396ef50fdacb4ab0f5ca48/pkg/registry/cluster/storage/proxy.go#L126-L129

**Comment by pangsq** [comment]
[tryUpgrade](https://github.com/kubernetes/apimachinery/blob/v0.23.4/pkg/util/proxy/upgradeaware.go#L321) lost the RawQuery because `h.Location` only have `Path`  set.

https://github.com/karmada-io/karmada/blob/8ea4c4d8819dc4c4b5fa885e3b24bb2fef910dbb/pkg/registry/cluster/storage/proxy.go#L63

I think that is the reason why `exec` fails.

Add `location.RawQuery = req.URL.RawQuery` before `newThrottledUpgradeAwareProxyHandler` solved the problem in my cluster. https://github.com/karmada-io/karmada/blob/15e614ba569adeddfe6a8238179937acb7674c0e/pkg/registry/cluster/storage/proxy.go#L112

**Comment by XiShanYongYe-Chang** [comment]
Hi @pangsq , thanks for your solution, I test it works successfully. Can you help pull a request to fix it?

By the way, do you think other fields in the URL need to be handled? just as: `req.URL.Fragment`.

**Comment by ikaven1024** [comment]
is it bug of k8s apimachinery?

**Comment by XiShanYongYe-Chang** [comment]
> is it bug of k8s apimachinery?

It should be a matter of our karmada use.

**Comment by pangsq** [comment]
> Hi @pangsq , thanks for your solution, I test it works successfully. Can you help pull a request to fix it?
> 
> By the way, do you think other fields in the URL need to be handled? just as: `req.URL.Fragment`.

I am glad to create a PR to fix it. As far as I know, `Fragment` is not used in apiserver.

**Comment by XiShanYongYe-Chang** [comment]
> I am glad to create a PR to fix it. As far as I know, `Fragment` is not used in apiserver.

Thanks!
