### ISSUE TITLE
controller manager crashes when cluster secretRef is empty

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1621]
**What happened**:

When cluster secretRef is nil, controller manager crashes. 

**What you expected to happen**:

Controller manager should not crash at any time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster object with secretRef is nil
2. Controller manager crashes

**Anything else we need to know?**:

**Environment**:
- Karmada version:
1.1.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
kubectl karmada version: version.Info{GitVersion:"v1.1.1", GitCommit:"8ea4c4d8819dc4c4b5fa885e3b24bb2fef910dbb", GitTreeState:"clean", BuildDate:"2022-03-18T01:34:59Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
- Others:

**Comment by RainbowMango** [comment]
> Create a cluster object with secretRef is nil

Do you mean you create the `Cluster` by yourself (not by `karmadactl join` or `karmada-agent`)?

**Comment by stingshen** [comment]
> > Create a cluster object with secretRef is nil
> 
> Do you mean you create the `Cluster` by yourself (not by `karmadactl join` or `karmada-agent`)? Can you explain why?

Yes. We are integrating Karmada into our system. The system has an api server and a controller manager. Users call the api server to register cluster. The api server creates a cluster object `without secretRef`, sa, impersonate sa, and doesn't wait for the sa secret to be generated. The controller manager watches for the cluster object and fill in the sa secret if available.

Anyway, I think the controller manager should not crash with the cluster object that comforms to the schema.

**Comment by RainbowMango** [comment]
> Anyway, I think the controller manager should not crash with the cluster object that comforms to the schema.

Agree. (I'm asking because I want to know more details about your use case.)
