### ISSUE TITLE
karmada有推荐的把原有k8s迁移到karmada的迁移方案吗？

### ISSUE THREAD

**Issue by mrningyang** [karmada-io/karmada#1624]
如果想使用karmada，迁移这块官方有推荐的解决方案吗？只能通过逐步把资源迁移上来，然后下线老k8s的方式吗？谢谢

**Comment by prodanlabs** [comment]
可以使用 `kubectl-karmada promote`  把k8s的资源提升到karmada
https://github.com/karmada-io/karmada/blob/master/docs/userguide/promote-legacy-workload.md

**Comment by mrningyang** [comment]
> 可以使用 `kubectl-karmada promote` 把k8s的资源提升到karmada https://github.com/karmada-io/karmada/blob/master/docs/userguide/promote-legacy-workload.md

ok，这种方式对子k8s的版本有要求吗

**Comment by RainbowMango** [comment]
基本上没有要求。只要你要同步的资源在k8s和karmada控制面同时可用就可以。

**Comment by mrningyang** [comment]
> 基本上没有要求。只要你要同步的资源在k8s和karmada控制面同时可用就可以。

ok，karmada要求的k8s版本有限制吗，比较老的1.12版本也可以吗

**Comment by RainbowMango** [comment]
部署karmada-apiserver时选择`kube-apiserver`版本(v1.16及以上)就可以，老版本集群也可以管理，不过需要注意资源API是否匹配，比如1.12版本上的部分资源可能在1.16版本上已经弃用了。

**Comment by lonelyCZ** [comment]
你可以参考这个[文档](https://github.com/karmada-io/karmada/blob/master/docs/userguide/promote-legacy-workload.md)来使用promote命令

**Comment by mrningyang** [comment]
> 你可以参考这个[文档](https://github.com/karmada-io/karmada/blob/master/docs/userguide/promote-legacy-workload.md)来使用promote命令，有什么问题可以随时提出，一起提升该工具的可用性。:)

好的，感谢
