### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by carlory** [karmada-io/karmada#1626]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs 12+

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Acarlory+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by carlory** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1
Thanks @carlory for all your contributions!

/assign @kevin-wangzefeng

**Comment by RainbowMango** [comment]
Hi @carlory  The invitation has been sent, please check your GitHub notifications.

**Comment by carlory** [comment]
@RainbowMango thanks!
