### ISSUE TITLE
请问如何打通两个集群的网络，submariner？

### ISSUE THREAD

**Issue by yanlingsishao** [karmada-io/karmada#1643]
请问如何打通两个集群的容器网络，使用submariner？

**Environment**:
- Karmada version: 0.9.0
- Kubernetes version: 1.21

**Comment by RainbowMango** [comment]
submariner是个选项，这里有篇文档可以参考：https://github.com/karmada-io/karmada/blob/master/docs/working-with-submariner.md

**Comment by RainbowMango** [comment]
/close

Please feel free to re-open it if you want to further discussion.
