### ISSUE TITLE
Karmada should rescheduled when  a new cluster is joined

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1644]
**What would you like to be added**:
when I apply a `propagationPolicy ` and has a cluster haven't joined,karmada will generate  a `resourcebinding `not include the cluster. When this cluster has joined,the  `resourcebinding ` will not regenerated, and will not rescheduled. This makes users must delete  `propagationPolicy `and `resourcebinding ` manually and recreate them so the new joined cluster will participate in scheduling.

**Why is this needed**:
I think it will enhance the userexperience,more than one of us has had the same problem.  Whether the step of joining a cluster must before creating a propagaPolicy.

**Comment by dddddai** [comment]
Related to [#829](https://github.com/karmada-io/karmada/issues/829#issuecomment-982234201)

**Comment by huone1** [comment]
in some scenarios，user don't hope to reschedule when adding a new cluster， So is it necessary to add a field in propagation policy to specify whether to trigger the rescheduling

**Comment by huone1** [comment]
it is considerrd with the issue #1644

**Comment by RainbowMango** [comment]
/close 
in favor of #2301
