### ISSUE TITLE
Support using karmadactl join to join cluster with pull mode

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#1648]
**What would you like to be added**:

- [ ] Offer an option for user to choose whether use pull mode or push mode
- [ ] Support using karmadactl join to join cluster with pull mode

**Why is this needed**:
command line enhancements

**Comment by lonelyCZ** [comment]
For `Pull` mode cluster, I consider a safer way to register. At #1363 , what do you think?

**Comment by Poor12** [comment]
That's cool. Actually, the difference between pull mode and push mode is the deploy of the agent and the creation of what agent need, such as sa and clusterrole.

**Comment by lonelyCZ** [comment]
> Actually, the difference between pull mode and push mode is the deploy of the agent and the creation of what agent need, such as sa and clusterrole.

Yes, but now the agent directly use `karmada-kubeconfig` to access `karmada-apiserver`, so I plane to optimize it and improve the security. Perhaps implement a certificate verification system for the registration mechanism, like `kubeedge` register nodes.
