### ISSUE TITLE
what is the problem karmada-controller-manager crashOff

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#1651]
the karmada-controller-manager usually crashoff by the follow reason: 
controller manager exits unexpectedly: failed to wait for federatedresourcequota caches to sync: timed out waiting for cache to be synced
Error: failed to wait for federatedresourcequota caches to sync: timed out waiting for cache to be synced

**Comment by XiShanYongYe-Chang** [comment]
Hi @SZT0728 , can you explain the detailed steps to reproduce the problem, and which version do you use in your site. So I can to reproduce the problem on my site.

**Comment by SZT0728** [comment]
> Hi @SZT0728 , can you explain the detailed steps to reproduce the problem, and which version do you use in your site. So I can to reproduce the problem on my site.

well, i use the kubectl-karmada 1.1.1 with the crds which version is 1.1.0, now the problem is dealed

**Comment by XiShanYongYe-Chang** [comment]
> now the problem is dealed

How did you solve it?

**Comment by SZT0728** [comment]
> > now the problem is dealed
> 
> How did you solve it?

 i download the kubectl-karmada and crds package at the tag v1.1.0 .  but when the karmada installed , the karmada-controller-manager crash off often ,and i use the kubectl-karmada:v1.1.1 to install

**Comment by XiShanYongYe-Chang** [comment]
@SZT0728 thanks!

Can this issue be closed?

**Comment by RainbowMango** [comment]
> well, i use the kubectl-karmada 1.1.1 with the crds which version is 1.1.0, now the problem is dealed

How do you mean `dealed`? Do you mean no crash now?

**Comment by CharlesQQ** [comment]
is crd federatedresourcequota created successfully?

**Comment by XiShanYongYe-Chang** [comment]
As the lack of activity, the problem may no longer exist, close it now. Feel free to reopen if you occur the same problem.
/close
