### ISSUE TITLE
Automatic update lifted/doc.go

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#1652]
**What would you like to be added**:
`lifted/doc.go` seems to be updated manually. It is better to do it automatically.

We can add lifted info in comments, like:
```
//+source: https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/apis/core/helper/helpers.go#L57-L61
//+changed: no

// IsQuotaHugePageResourceName returns true if the resource name has the quota
// related huge page resource prefix.
func IsQuotaHugePageResourceName(name core.ResourceName) bool {
	return strings.HasPrefix(string(name), core.ResourceHugePagesPrefix) || strings.HasPrefix(string(name), core.ResourceRequestsHugePagesPrefix)
}
```

Then we can parse it with `AST` and generate `doc.go`. 
`update-lifted.sh` and `verify-lifted.sh` can be added in hack.

**Why is this needed**:
Avoid `lifted/doc.go` out of date.

**Comment by XiShanYongYe-Chang** [comment]
@ikaven1024 Sounds great! Would you like to do this task?

**Comment by ikaven1024** [comment]
I will do it when i am available.

**Comment by ikaven1024** [comment]
glad to do it.

**Comment by lonelyCZ** [comment]
Great, you remind me that I added a lifted file but forgot to update `lifted/doc.go`. 

Looking forward to this feature,Thanks @ikaven1024

**Comment by CharlesQQ** [comment]
@lonelyCZ  i guess use `lifted/doc.go`  can download function from github instead of cp that, right? if i have a lifted/doc.go file, how can i download the function to my project?

**Comment by lonelyCZ** [comment]
> i guess use lifted/doc.go can download function from github instead of cp that, right?

I think you could download codes that don't change. But sometimes, we need to change the codes for our project. Generally, we develop the right features first, and then explain which parts of the code we use from other projects.

> if i have a lifted/doc.go file, how can i download the function to my project?

If you need this functionality, I think you could develop a tool to implement it, which shouldn't be too complicated. If more people need this feature, welcome to contribute it to the community.
