### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by huntsman-li** [karmada-io/karmada#1666]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit a proposal.

The proposal is about caching member cluster, see:

- https://github.com/karmada-io/karmada/pull/1386

- https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Ahuntsman-li+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by huntsman-li** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1 from me

We benefit a lot from the meetings with @huntsman-li and @liys87x. And I'm appreciated that you are willing to bring your practice to Karmada.

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Looking forward to more of your contributions :-)

**Comment by kevin-wangzefeng** [comment]
Invitation sent, pleaes visit https://github.com/karmada-io to confirm and join.

**Comment by huntsman-li** [comment]
@kevin-wangzefeng @RainbowMango thanks
