### ISSUE TITLE
Add FederatedResourceQuota to karmada api

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#1669]
**What happened**:

FederatedResourceQuota doesn't exist in [policyv1alpha1](https://pkg.go.dev/github.com/karmada-io/api@v1.0.0/policy/v1alpha1)

**What you expected to happen**:

FederatedResourceQuota should be in Karmada API package.

**How to reproduce it (as minimally and precisely as possible)**:

No FederatedResourceQuota in [policyv1alpha1](https://pkg.go.dev/github.com/karmada-io/api@v1.0.0/policy/v1alpha1)

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.1.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 

```
kubectl karmada version: version.Info{GitVersion:"v1.0.1", GitCommit:"ce2267c5d04a5e97368285fd64fdbe5fa285856e", GitTreeState:"clean", BuildDate:"2022-01-21T09:37:08Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
```

- Others:

**Comment by stingshen** [comment]
I found the pr in Karmada API repo...

https://github.com/karmada-io/api/pull/9

@RainbowMango What is the plan to sync APIs from Karmada to API repo?

**Comment by RainbowMango** [comment]
Are you using `karmada-io/api`?

The API of v1.1.0 hasn't been synced to `karmada-io/api`. 
We are going to build the ability that automatically syncs APIs from `karmada-io/karmada` to `karmada-io/api`, but hasn't started yet.

**Comment by stingshen** [comment]
> Are you using `karmada-io/api`?

Yes, I'm using `karmada-io/api`. Do you have any suggestion if my project needs to create FederatedResourceQuota object now? What package should be imported?

**Comment by RainbowMango** [comment]
/assign

I'll send another PR to `karmada-io/api`.

**Comment by stingshen** [comment]
> I'll send another PR to `karmada-io/api`.

Thank you!
