### ISSUE TITLE
arch matrix shall be remove in docker hub image building

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#1680]
**What happened**:
In pr #927, we have realized build multi platform in `docker buildx`. 
https://github.com/karmada-io/karmada/runs/6203840283?check_suite_focus=true#step:7:18

So the the arch matrix in `dockerhub-latest-image.yml` and `dockerhub-release-image.yml` is unnecessary.
https://github.com/karmada-io/karmada/blob/f411443e0bc9eacf3288fa9b66c49b3d51199cb8/.github/workflows/dockerhub-latest-image.yml#L15-L17

**What you expected to happen**:
`matrix.arch` shall  be remove and, ci will only run once.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

/cc @RainbowMango @gy95 
/assign @ikaven1024

**Comment by RainbowMango** [comment]
@ikaven1024 Can you help confirm if it is all good after [the publish job](https://github.com/karmada-io/karmada/runs/6211059713?check_suite_focus=true) is finished?

And we should cherry-pick both #1681 #927 to release branches.

**Comment by ikaven1024** [comment]
All images work well on my side.

**Comment by RainbowMango** [comment]
Thanks @ikaven1024. I wonder to know if you are working on the cherry-pick thing for #927. (I'm asking because don't want to repeat efforts. :) ) If not, both I and @gy95 can help with it.
We are going to cut a new release after that.
