### ISSUE TITLE
对于pull模式的成员集群，部署了ANP后，有没有可能支持karmadactl中的get，promeote等命令？

### ISSUE THREAD

**Issue by wongearl** [karmada-io/karmada#1695]
**Please provide an in-depth description of the question you have**:
对于pull模式的成员集群，部署ANP后已经可以通过AA获取该成员集群内的资源，但是依然无法使用kamadactl get获取资源信息，也无法使用karmadactl promete命令接管该集群内资源。
**What do you think about this question?**:
是否有支持的可能，这样感觉无论是pull模式还是push模式karmadactl使用起来更丝滑。
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
> 但是依然无法使用kamadactl get获取资源信息

理论上是可以的，可否提供详细的信息（版本、操作步骤、错误日志）？
@lonelyCZ 是这个特性的owner。可以根据你的信息进行初步诊断。

> 也无法使用karmadactl promete命令接管该集群内资源

同上。

**Comment by lonelyCZ** [comment]
Hi, @wongearl , 你可以分享一下你部署了ANP使用`karmadactl get`命令的日志信息吗？可以通过`karmadactl get pod -v=6`来获取。

**Comment by wongearl** [comment]
使用的4月1日时候的release1.1分支，使用/hack/local-up-karmada部署的karmada及成员集群。
部署ANP后尝试 kubectl get --raw /apis/cluster.karmada.io/v1alpha1/clusters/member3/proxy/api/v1/nodes能正常获取到信息。
`kubectl karmada get all` 提示：`The karmadactl get command now only supports Push mode, [ member3 ] are not push mode`

`kubectl karmada promote deployment nginx-deployment -n default -c member3` 提示： `Error: failed to get Secret info in karmada control plane. err: secrets "member3" not found`

是4月1日之后添加了支持是吗？

**Comment by lonelyCZ** [comment]
是的，在master分支上已经支持了

**Comment by wongearl** [comment]
@lonelyCZ 好的，谢谢

**Comment by lonelyCZ** [comment]
不过`kubectl promote`暂时还未支持，正在逐步迁移，下一个release版本，就都会支持的。

**Comment by wongearl** [comment]
好的，对于接管集群中遗留工作负载，目前方案只有通过kubectl promote是吧？而对于pull模式promote的支持下个版本会支持是吧？

**Comment by lonelyCZ** [comment]
> 对于接管集群中遗留工作负载，目前方案只有通过kubectl promote是吧？

是的，为了避免发生冲突，目前只能通过`karmadactl promote`逐个接管

> 而对于pull模式promote的支持下个版本会支持是吧？

现在已经支持PULL模式的了，不过需要提供子集群的`kubeconfig`，我们正在讨论`promote`命令的演进方向，如果你也有兴趣，欢迎参与讨论。

https://github.com/karmada-io/karmada/pull/1721#discussion_r866475220
