### ISSUE TITLE
should we change default UserName of kubeconfig to karmada-admin?

### ISSUE THREAD

**Issue by zgfh** [karmada-io/karmada#1700]
**What happened**:
when i import karmada kubeconfig to .kube/config with
```
KUBECONFIG=~/.kube/config:/etc/karmada/karmada-apiserver.config kubectl config view --flatten > /tmp/config && mv -f /tmp/config ~/.kube/config
```
it will error because of username conflict
```
[root@10-29-22-116 ~]# KUBECONFIG=~/.kube/config:/etc/karmada/karmada-apiserver.config kubectl config view --flatten > /tmp/config && mv -f /tmp/config ~/.kube/config
[root@10-29-22-116 ~]# kubectl config use-context karmada;kubectl get node
error: You must be logged in to the server (Unauthorized)
```
should we change default UserName of kubeconfig to 'karmada-admin'?
or let UserName = ClusterName+"-"+UserName?

**What you expected to happen**:
make karmada easy to export kubeconfig 

**How to reproduce it (as minimally and precisely as possible)**:
```
KUBECONFIG=~/.kube/config:/etc/karmada/karmada-apiserver.config kubectl config view --flatten > /tmp/config && mv -f /tmp/config ~/.kube/config
kubectl config use-context karmada;kubectl get node
```
**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.1.2
- Others:

**Comment by lonelyCZ** [comment]
Yes, I also think it is better to add `karmada` prefix. Or, use `karmada-apiserver` consistently.

https://github.com/karmada-io/karmada/blob/46dacea8972e061c1b5de108c776b214c7504848/pkg/karmadactl/cmdinit/options/global.go#L16-L21

cc @prodanlabs

**Comment by prodanlabs** [comment]
I think it can.
