### ISSUE TITLE
interpreter webhook response's patch is nil, workload sync to member  cluster unsuccessfully

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1703]
**What happened**:
deployment not synced to member cluster, log print following message:
```
E0501 09:24:02.017878      20 common.go:102] failed to revise replica for Deployment/default/nginx in cluster xxx, err is: Internal error occurred: failed calling webhook "interpreter-webhook/deployment.interpreter.webhook": reveived invalid webhook response: webhook returned empty response.patch

Failed to transform resourceBinding(nginx-deployment), Error: Internal error occurred: failed calling webhook "interpreter-webhook/deployment.interpreter.webhook": reveived invalid webhook response: webhook returned empty response.patch
```

**What you expected to happen**:
response'patch is nil, that is expected, workload should be synced successfully

**How to reproduce it (as minimally and precisely as possible)**:
interpreter webhook  type `ReviseReplica`  response object's patch is nil

**Anything else we need to know?**:
response with func verifyResourceInterpreterContextWithPatch, the following code is unnecessary and cause problems
https://github.com/karmada-io/karmada/blob/46dacea8972e061c1b5de108c776b214c7504848/pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go#L138-L140

**Environment**:
- Karmada version:
v1.1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @CharlesQQ , when response object's patch is nil, the response object's patchType also needs to be nil. 

In your case, is patchType also nil?

**Comment by RainbowMango** [comment]
> response'patch is nil, that is expected,

Why do you think the `nil patch` is expected? Any more detailed infos?

**Comment by CharlesQQ** [comment]
`In your case, is patchType also nil?`
patchType is JSONPatch, it's similar example, logic enter following code
https://github.com/karmada-io/karmada/blob/772e6fa6f33dc6aa5e803b23e2b1e684dc35c2ca/pkg/webhook/interpreter/response.go#L26-L45

**Comment by CharlesQQ** [comment]
`Why do you think the nil patch is expected?`
original and  current is same, so response'patch is nil is expected
https://github.com/karmada-io/karmada/blob/772e6fa6f33dc6aa5e803b23e2b1e684dc35c2ca/pkg/webhook/interpreter/response.go#L48-L56

**Comment by RainbowMango** [comment]
> original and current is same, so response'patch is nil is expected

If the `patch` is empty, then the `PatchType` makes no sense, right? Can you set the `PatchType` to nil? Is there any trouble to do that?

**Comment by CharlesQQ** [comment]
@RainbowMango yes, i can set `PatchType ` to nil when `patch ` is empty

**Comment by XiShanYongYe-Chang** [comment]
> it means PatchType judgement should be remove too, right?

I think there is no need to remove this judgment. There is a similar judgment in kubernetes: 

https://github.com/kubernetes/kubernetes/blob/af4dceeac2d9f5cd22afcb68fcf7af0ee4af7c67/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/request/admissionreview.go#L67-L79

**Comment by CharlesQQ** [comment]
ok, it means if patchType should be set to nil when patch is nil; and if patchType should be set to JSONPatch when patch is not  nil  in interperter webhook server, is that right? @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
> ok, it means if patchType should be set to nil when patch is nil; and if patchType should be set to JSONPatch when patch is not nil in interperter webhook server, is that right?

Yes~

**Comment by CharlesQQ** [comment]
thanks~
