### ISSUE TITLE
whether  `InterpretDependency` can only propagate resource in member cluster that created in host cluster?

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1710]
**Please provide an in-depth description of the question you have**:
I might create or update a configmap in member cluster if find a mesh sidecar container, configmap's data is not same all the time and sidecar doesn't have  the configmap volume; It seems `InterpretDependency`  does not meet user needs
**What do you think about this question?**:
`DependentObjectReference` should not only Include gvk of resource, but also object; user can create/update dependencies or let  karmada controller create/update that
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
I guess this is a special use case that `InterpretDependency` hasn't covered.  

Do you mean you will create `ConfigMap` for `Workload` in the member cluster? The `ConfigMap` doesn't present in `Karmada control plane`, right?

**Comment by CharlesQQ** [comment]
`Do you mean you will create ConfigMap for Workload in the member cluster? The ConfigMap doesn't present in Karmada control plane, right?`
yes
