### ISSUE TITLE
If some member cluster not ready, the topology of the workload may change, which is very dangerous

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1717]
**What would you like to be added**:
The scheduler adds command line parameters to decide whether to tolerate the situation that some member clusters are not ready

**Why is this needed**:
When a part of the cluster is not ready, it happens that the part of the cluster deploys the workload. When the related resources change, the workload may be removed from the cluster, which cannot be tolerated in some scenarios.

**Comment by duanmengkk** [comment]
Related to https://github.com/karmada-io/karmada/issues/829#issuecomment-982234201

**Comment by RainbowMango** [comment]
Please @CharlesQQ confirm if tit is the same issue that was addressed by #1640?

**Comment by CharlesQQ** [comment]
@RainbowMango yes, it's the same issue, Thinks~

**Comment by RainbowMango** [comment]
/close

Let's track this issue by #1640.
