### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by wlp1153468871** [karmada-io/karmada#1723]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs 

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Apr+is%3Aclosed+author%3Awlp1153468871

issues:
https://github.com/karmada-io/karmada/issues?q=is%3Aissue+assignee%3Awlp1153468871+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by wlp1153468871** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to accept the invitation.

**Comment by wlp1153468871** [comment]
> Invitation sent, please visit https://github.com/karmada-io to accept the invitation.
