### ISSUE TITLE
Deploy the `karmada-agent` into the `karmada-cluster` namespace

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#1736]
**What would you like to be added**:
Deploy the `karmada-agent` into the `karmada-cluster` namespace to operate PUSH and PULL cluster uniformly.

**Why is this needed**:
Now, we deploy `karmada-agent` in `karmada-system` namespace by default, and because we uniformly deploy the `karmda-impersonator` in `karmada-cluster` namespace so that we have two namespaces in PULL mode cluster.

Although we support custom namespace for `karmada-agent` deployment, we can define the default deployment mode.

**Comment by RainbowMango** [comment]
>  so that we have two namespaces in PULL mode cluster.

Do you mean two namespaces in PULL mode cluster is a bad idea?  What are the specific bad effects?

**Comment by lonelyCZ** [comment]
1. Like #1350, if users deploy `agent` in `karmada-host` for testing, they can't use this script #1735 to remove `agent`, which will destroy the whole karmada control plane.
2. Unify the namespace of PUSH and PULL mode, which is better.
3. `karmada-system` is used by karmada control plane, `karmada-cluster` is used by member cluster, which makes it easier to understand.

**Comment by RainbowMango** [comment]
Sorry @lonelyCZ , I didn't get the necessity of this. 

For 1: I think it's a case that we can fix it.
For 2: I think for Push mode cluster, we stores the secrets to `karmada-cluster` namespaces and install components in `karmada-system`, seems no difference with Pull mode. What am I missing here?

For 3: 
I would say that the `karmada-system` is intended for system components and `karmada-cluster` is for cluster-related configurations.

**Comment by lonelyCZ** [comment]
Ok, that makes sense. Thanks. :)
