### ISSUE TITLE
Support specifying context when `init`

### ISSUE THREAD

**Issue by hzxuzhonghu** [karmada-io/karmada#1744]
**What would you like to be added**:

When I install karmada into a cluster I can specify the kubeconfig. 

However, if there are multi contexts in the kubeconfig, I have no way to specify which host cluster to install karmada control plane. 
This is not friendly to local env, especially when using kind.

**Comment by lonelyCZ** [comment]
It did leave out, I will fix it.

**Comment by RainbowMango** [comment]
I guess @hzxuzhonghu is using the `karmadactl int`, @lonelyCZ Hope we are on the same page.

**Comment by lonelyCZ** [comment]
Yes, I have fixed it, prepare to submit.

**Comment by RainbowMango** [comment]
Great!
/assign @lonelyCZ
