### ISSUE TITLE
Add destroy karmada-controller-plane in kubectl-karmada

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1747]
**What would you like to be added**:
Kubectl karmada destroy|uninstall|undeploy **** 
**Why is this needed**:
When I try to use karmadactl to init a karmada system , I can not found any destroy command to uninstall karmada system.
It is not friendly.
How about add a command in karmadactl for destroy the karmada system.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16109961/167352651-14026e0d-0b1f-4aee-91f4-17b7ba04c2b8.png">

**Comment by wuyingjun-lucky** [comment]
@RainbowMango @lonelyCZ  what's your opinion

**Comment by lonelyCZ** [comment]
Thank you, #1337 is implementing it. Welcome to talk about it there.

**Comment by wuyingjun-lucky** [comment]
> Thank you, #1337 is implementing it. Welcome to talk about it there.

OK
