### ISSUE TITLE
Support --image-mirror-country  or --image-repositor  like minikube

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1753]
Hi,i can't download these images `k8s.gcr.io/etcd:3.5.1-0`,`k8s.gcr.io/kube-controller-manager:v1.21.7`,`k8s.gcr.io/kube-apiserver:v1.21.7`

For many mainland users, specifying the `--image-mirror-country` parameter may be more convenient than specifying [their image repository](https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/cmdinit.go#L59) separately.

Such as minikube ,for Chinese mainland users, set it to cn.

[minikube --image-mirror-country](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go#L263)

**Comment by RainbowMango** [comment]
I guess what you are talking about is the `karmadactl init` flags, right?

I'll look at how minikube use this flag. Does this just affect the images in `k8s.gcr.io`?

**Comment by wuyingjun-lucky** [comment]
@RainbowMango @chaunceyjiang  Can I take some work on the issue ？

**Comment by RainbowMango** [comment]
For this issue, we haven't made final decisions yet.

Anyone can take any issue so long as the `Assignees` list is still empty.

**Comment by RainbowMango** [comment]
I checked some minikube code, and found that [it maintains the available image repositories for different countries](https://github.com/kubernetes/minikube/blob/f51fc4ccaccb333c57795dbdb9b138fa09bb3a91/pkg/minikube/constants/constants.go#L178-L182):
```
	// ImageRepositories contains all known image repositoriesAnders F Björklund, 2 years ago: • Add comments to avoid warnings from go lint
	ImageRepositories = map[string][]string{Medya Ghazizadeh, 2 years ago: • Add podman driver (#6515)
		"global": {""},Zhongcheng Lao, 3 years ago: • Triggers repository detection only when --ima…
		"cn":     {"registry.cn-hangzhou.aliyuncs.com/google_containers"},Zhongcheng Lao, 3 years ago: • Select an accessible image repository for som…
	}
```
And It also checked if the repository is accessible.
https://github.com/kubernetes/minikube/blob/f51fc4ccaccb333c57795dbdb9b138fa09bb3a91/cmd/minikube/cmd/start.go#L868-L906

**Comment by wuyingjun-lucky** [comment]
> it maintains the available image repositories for different countries
Do you think we should set karmada registry besides the kube image？
I use the commands below
kubectl-karmada init \
--karmada-scheduler-image=nexus.cmss.com/karmada/karmada-scheduler:1.1.1 \
--karmada-apiserver-image=nexus.cmss.com/karmada/kube-apiserver:v1.21.7 \
--karmada-kube-controller-manager-image=nexus.cmss.com/karmada/kube-controller-manager:v1.21.7 \
--karmada-controller-manager-image=nexus.cmss.com/karmada/karmada-controller-manager:1.1.1 \
--karmada-webhook-image=nexus.cmss.com/karmada/karmada-webhook:1.1.1 \
--karmada-aggregated-apiserver-image=nexus.cmss.com/karmada/karmada-aggregated-apiserver:1.1.1 \
--etcd-image=nexus.cmss.com/karmada/etcd:3.4.13-0 \
--etcd-init-image=nexus.cmss.com:8086/karmada/alpine:3.15.1 \
--kubeconfig=/root/wyj/config \
--crds=/root/wyj/crds.tar.gz

**Comment by wuyingjun-lucky** [comment]
/close
As https://github.com/karmada-io/karmada/pull/1764 closed

**Comment by RainbowMango** [comment]
/close

@wuyingjun-lucky Maybe you can use this command after you become a member of Karmada. You can file an issue for the membership.
