### ISSUE TITLE
kubectl-karmada init failed but return success

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1754]
**What happened**:
Use kubectl  init  to deploy karmada-system. The control-plane deployed failed, But the console output successful messages
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/16109961/167410214-e660c201-00ba-4b5f-b320-f787f4208b1f.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/16109961/167410230-d1989351-98ca-4577-85c6-85bc93878435.png">

I found the source just use warn to log the result.
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/16109961/167410614-9e655d02-485c-41c1-8a91-ff9de313bb8a.png">

@RainbowMango @lonelyCZ can you help me check the bug ? 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
> But I found that if we failed to deploy midway and had to manually clean up the environment and deploy again, it was a bit too much hassle. Should we think about the atomicity of the operation？

Maybe we can refer to [kubeadm --reset](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/reset.go#L171)

**Comment by wuyingjun-lucky** [comment]
> Right, expect for #1337

you means we can resovle the question by https://github.com/karmada-io/karmada/pull/1337 done

**Comment by RainbowMango** [comment]
/close
I guess this issue has been solved.
