### ISSUE TITLE
Kubectl Karmada Promete can not take over some GVRs

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1758]
**What happened**:
Some panics or problems will happens if we promete any GVRs in k8s.Such as promete a service will generate a panic,promete a ns will generate a error too.
![图片](https://user-images.githubusercontent.com/17697155/167532754-95074d5a-6621-424c-8c5c-d20f18b35cf3.png)

**What you expected to happen**:
limit GVR (deployments,job,crd and  so on ) when excute kubectl karmada promete. Provide a flag to propagate dependencies(secrets and configmap).Or resovle the problems one by one to support any resources?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
> Such as promete a service will generate a panic,promete a ns will generate a error too.

I want to know the root cause before make changes for it.
Can you help provide steps for reproducing it?

**Comment by duanmengkk** [comment]
1. promete will add  a annotation to resource. if a resource‘ annotation is nil ,will generate a nil-pointed exception.
2. promete excute a command `kubectl get {resource} -n {namespace}` in code,but if a resource is not namespaced,such as `namespace`,`clusterRole`,the command` kubectl karmada promete namespace test -c cluster1` will act as` kubectl get namespace test  -n default `,this will generate a problem.
3. excution_controller will create a resource other than update a resource,so if a err is `IsAlreadyExists` and have a annotation talked above，karmada will update the resource. However,if some resources are existed in member cluster,create a same resource  will not return `IsAlreadyExists`,such as service,it will return a `IsInvalid` err,because the port confilt.

**Comment by lonelyCZ** [comment]
> promete will add a annotation to resource. if a resource's annotation is nil ,will generate a nil-pointed exception.

Yes, it could be happened.

> promete excute a command kubectl get {resource} -n {namespace} in code,but if a resource is not namespaced,such as namespace,clusterRole,the command kubectl karmada promete namespace test -c cluster1 will act askubectl get namespace test -n default,this will generate a problem.

Could you recreate this specific problem？CRD resource seemingly can be promoted.

> excution_controller will create a resource other than update a resource,so if a err is IsAlreadyExists and have a annotation talked above，karmada will update the resource. However,if some resources are existed in member cluster,create a same resource will not return IsAlreadyExists,such as service,it will return a IsInvalid err,because the port confilt.

Sure, there might be a case where we didn't think about managing services before, and is there a need for managing services？

**Comment by duanmengkk** [comment]
> Could you recreate this specific problem？CRD resource seemingly can be promoted.

not crd,I mean if a gvr is a global resources(not namespaced resource),there some logic problem in code, promete will excete a `kubectl get clusterRole -n default ` in code if i excete `kubectl karmada promete clusterRole test -c cluster1` in command line.



> Sure, there might be a case where we didn't think about managing services before, and is there a need for managing services？

When user need to deploy diffrent backend-service to diffrent cluster,I doubt this is one of karmada's scene?
May be we should have a limit to the GVR for `promete`,Only support crd and others workloads in k8s (deployment,statefulset,job and so on)?

**Comment by lonelyCZ** [comment]
> not crd,I mean if a gvr is a global resources(not namespaced resource),there some logic problem in code, promete will excete a kubectl get clusterRole -n default in code if i excete kubectl karmada promete clusterRole test -c cluster1 in command line.

There should be no impacts, it firstly scan namescaped resources, if not to find, then scan not-namespaced resources.

> May be we should have a limit to the GVR for promete,Only support crd and others workloads in k8s (deployment,statefulset,job and so on)?

Perhaps, we should not limit it too much, if there are crd and cr defined by users, we also support to promote them.

**Comment by duanmengkk** [comment]
> There should be no impacts, it firstly scan namescaped resources, if not to find, then scan not-namespaced resources.

when i fix the null-pointer exception,and excute 'kubectl karmada promote clusterroles openebs -c cluster37'
![图片](https://user-images.githubusercontent.com/17697155/167546575-e8146ab7-f253-4b9f-806e-88bba4656f4c.png)



> Perhaps, we should not limit it too much, if there are crd and cr defined by users, we also support to promote them.

Agree ,But how to limit, what  resources to be limited? I think some  system resource in member cluster (such as serviceaccount,clusterRole in kube-system)

**Comment by lonelyCZ** [comment]
> when i fix the null-pointer exception,and excute 'kubectl karmada promote clusterroles openebs -c cluster37'.The error occurs

Right, it also happen in my env, I think it should be checked whether is namespaced or not namespaced resources when creating it.
