### ISSUE TITLE
Open karmada-scheduler-estimator error

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#1765]
**What happened**:
When I deploy karmada on k8s, I want to enable karmada-scheduler-estimator, but the following error is reported：
```I0511 01:44:37.161357       1 cache.go:87] Start dialing estimator server(karmada-scheduler-estimator-member1:10352) of cluster(member1).
W0511 01:44:37.184544       1 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-member1:10352 karmada-scheduler-estimator-member1:10352 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-member1 on 169.254.25.10:53: no such host". Reconnecting...
W0511 01:44:38.188679       1 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-member1:10352 karmada-scheduler-estimator-member1:10352 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-member1 on 169.254.25.10:53: no such host". Reconnecting...
W0511 01:44:40.068675       1 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-member1:10352 karmada-scheduler-estimator-member1:10352 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-member1 on 169.254.25.10:53: no such host". Reconnecting...
E0511 01:44:42.162138       1 cache.go:90] Failed to dial cluster(member1): dial karmada-scheduler-estimator-member1:10352 error: context deadline exceeded.
```
**What you expected to happen**:
How to solve this problem and make it work properly ?

**Anything else we need to know?**
I deployed karmada offline on the existing k8s and used the kubeovn network plugin

**Environment**:
- Karmada version: v1.1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):  v1.1.2
- Others:

**Comment by hanweisen** [comment]
I think karmada could add a subcmd to enable feature like schedule-estimator 
For example
```
$ kubectl karmada feature enable  schedule-estimator
deploy schedule-estimator on cluster member1
deploy schedule-estimator on cluster member2
restart schedule
feature schedule-estimator has been successfully enabled
```
Then add some code in cluster_controller. when new cluster join deploy corresponding schedule-estimator.

**Comment by luoMonkeyKing** [comment]
> 我认为 karmada 可以添加一个 subcmd 来启用诸如 schedule-estimator 之类的功能 例如
> 
> ```
> $ kubectl karmada feature enable  schedule-estimator
> deploy schedule-estimator-member1
> deploy schedule-estimator-member2
> restart schedule
> feature schedule-estimator has been successfully enabled
> ```
> 
> 然后在 cluster_controller 中添加一些代码。当新集群加入时，部署相应的调度估计器。
The problem is solved because hack/deploy-scheduler-estimator.sh is not executed, but I think your proposal is very good

**Comment by luoMonkeyKing** [comment]
> 我认为 karmada 可以添加一个 subcmd 来启用诸如 schedule-estimator 之类的功能 例如
> 
> ```
> $ kubectl karmada feature enable  schedule-estimator
> deploy schedule-estimator-member1
> deploy schedule-estimator-member2
> restart schedule
> feature schedule-estimator has been successfully enabled
> ```
> 
> 然后在 cluster_controller 中添加一些代码。当新集群加入时，部署相应的调度估计器。

The problem is solved because hack/deploy-scheduler-estimator.sh is not executed, but I think your proposal is very good

**Comment by hanweisen** [comment]
When new cluster add/delete we should execute hack/deploy-scheduler-estimator.sh/delete schedule-es manually. this is inconvenient

**Comment by chaunceyjiang** [comment]
I have the same problem.


> I think karmada could add a subcmd to enable feature like schedule-estimator For example
> 
> ```
> $ kubectl karmada feature enable  schedule-estimator
> deploy schedule-estimator-member1
> deploy schedule-estimator-member2
> restart schedule
> feature schedule-estimator has been successfully enabled
> ```
> 
> Then add some code in cluster_controller. when new cluster join deploy corresponding schedule-estimator.

Agree with you.

**Comment by RainbowMango** [comment]
I'm not sure if `karmadactl init` can install a specific component, such as `karmada-estimator`? 
cc @prodanlabs @lonelyCZ for comments.

**Comment by lonelyCZ** [comment]
> I'm not sure if karmadactl init can install a specific component, such as karmada-estimator?

`karmada-estimator` can not installed by `karmadactl init` currently.

> I think karmada could add a subcmd to enable feature like schedule-estimator.

Cool, `karmada-estimator` is same as `plugin`, we can enable it by cmd.

**Comment by lonelyCZ** [comment]
I mentioned this earlier at #790, `karmada-estimator` does not necessarily need to be deployed when the member cluster is added, deploy it as needed.

**Comment by hanweisen** [comment]
When new cluster add, we should deploy a new schedule-estimator. This function can add in cluster_controller, or introduce a new controller.

**Comment by hanweisen** [comment]
I don't understand why karmada-estimator deploy as needed in #790. when enable karmada-scheduler-estimator we have to deploy all corresponding schedule-estimator, otherwise we will find a connection error in scheduler as mentioned in this issue

**Comment by hanweisen** [comment]
This is the reason why deploy `karmada-estimator` as needed ?

>>Good idea. But note that karmadactl join and unjoin does not need to know the kubeconfig of host cluster, while the scheduler estimator must be deployed in host cluster. So this enhancement may lead to some complexity.

>Yes, this requires consideration of whether to add host cluster config to karmadactl join and unjoin. I think this could be an option for user, otherwise user need to delete scheduler estimator manually after excuting karmadactl unjoin.

**Comment by anu491** [comment]
I guess we could forward with a subcmd to enable the feature ?! Is there any other better/appropriate method which you'll know off ..... to address the issue ?

**Comment by lonelyCZ** [comment]
I just checked it, there are some `yaml` created after executing `karmadactl init`

```
-rw-r--r--. 1 root root 1705 May 23 14:27 karmada-agent.yaml
-rw-r--r--. 1 root root 1524 May 23 14:27 karmada-scheduler-estimator.yaml
```

https://github.com/karmada-io/karmada/blob/d9b043bedd4507b9f81196f55ff1bd3fd5df6ab0/pkg/karmadactl/cmdinit/utils/examples.go#L141-L151

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
