### ISSUE TITLE
Improve `hack/local-up-karmada.sh` execution time -2

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1769]
**What would you like to be added**:
This is subsequent to #1729. Continue to optimize the performance of `hack/local-up-karmada.sh`.

**Why is this needed**:
The image of `karmada-agent` will be built twice when we load Karmada by `hack/local-up-karmada.sh`.
That's redundant and will slow down the progress.

1st: https://github.com/karmada-io/karmada/runs/6383586223?check_suite_focus=true#step:4:222
2th: https://github.com/karmada-io/karmada/runs/6383586223?check_suite_focus=true#step:4:520

Note: I haven't thought about how to fix it yet. Feel free to leave your comments below if you want to help.
/help

**Comment by hanweisen** [comment]
There is a little problem with docker.sh. In my env I execute `local-up-karmada.sh` gets a error `hack/docker.sh:行34: target: 只读变量`.  I change `local -ra target=$1` to `local -a target=$1` in docker.sh line 34. problem solved

**Comment by duanmengkk** [comment]
> There is a little problem with docker.sh. In my env I execute `local-up-karmada.sh` gets a error `hack/docker.sh:行34: target: 只读变量`. I change `local -ra target=$1` to `local -a target=$1` in docker.sh line 34. problem solved

Can you take a look about this @ikaven1024? I have the same problem

**Comment by RainbowMango** [comment]
I guess you mean #1774. Please rebase your code and try again.

**Comment by RainbowMango** [comment]
Yes, exactly. We should consider if `hack/deploy-karmada-agent.sh` should take the responsibility to build the images. I guess no.

**Comment by hanweisen** [comment]
When developing karmada-agent, deployer may way execute `hack/deploy-karmada-agent.sh` directly and want to the build images. I think we can add a variable in `local-up-karmada.sh`, then `hack/deploy-karmada-agent.sh` check this variable, If exists skip build images.

`hack/deploy-karmada-agent.sh` line 64
```
if kubectl config get-clusters | grep "kind-${MEMBER_CLUSTER_NAME}"
then
  if [ -n ${} ]; then
  # make agent image
  export VERSION="latest"
  export REGISTRY="swr.ap-southeast-1.myhuaweicloud.com/karmada"
  make image-karmada-agent --directory="${REPO_ROOT}"
  kind load docker-image "${REGISTRY}/karmada-agent:${VERSION}" --name="${MEMBER_CLUSTER_NAME}"
fi
AGENT_IMAGE_PULL_POLICY="IfNotPresent" # It must not reload the image when member cluster created by kind
```

**Comment by ikaven1024** [comment]
Giving an ideal. Exact the build function into `build-image.sh`, e.g.
```sh
function build_image_karama_agent() {
    if [[ $KAMADA_IMAGE_AGENT_READY == "true" ]]; then
        return
    fi
    make image-karamada-agent
    KAMADA_IMAGE_AGENT_READY=true
}
```

Then we can call `build_image_karama_agent` repeatedly.

**Comment by RainbowMango** [comment]
> Giving an ideal. Exact the build function into build-image.sh, e.g.

Looks like a little bit hack...

**Comment by hanweisen** [comment]
> Giving an ideal. Exact the build function into `build-image.sh`, e.g.

Nice idea!

**Comment by hanweisen** [comment]
I plan to modify `docker.sh` add `image_ready_tag`
```
function build_images() {
  local -r target=$1
  local -r output_type=${OUTPUT_TYPE:-docker}
  local platforms="${BUILD_PLATFORMS:-"$(util:host_platform)"}"

  # Preferentially use `docker build`. If we are building multi platform,
  # or cross building, change to `docker buildx build`
  cross=$(isCross "${platforms}")
  if [[ "${cross}" == "true" ]]; then
    build_cross_image "${output_type}" "${target}" "${platforms}"
  else
    build_local_image "${output_type}" "${target}" "${platforms}"
  fi
  local -r image_ready_tag=KAMADA_IMAGE_${target//-/_}_READY
  export "${image_ready_tag}"=ture

}
```
Then in `deploy-karmada-agent.sh` we can call ensure_image_karama_agent() function
```
if kubectl config get-clusters | grep "kind-${MEMBER_CLUSTER_NAME}"
then
   export VERSION="latest"
   export REGISTRY="swr.ap-southeast-1.myhuaweicloud.com/karmada"
   ensure_image_karama_agent
   AGENT_IMAGE_PULL_POLICY="IfNotPresent" # It must not reload the image when member cluster created by kind
fi
```

**Comment by ikaven1024** [comment]
I didn't get it, why must add image_ready_tag in docker.sh, KAMADA_IMAGE_AGENT_READY in build-image.sh is not enough?

Another question, `make image-xxx` will run both `go build` and `docker build`. You only prevent `docker build` twice, but not `go build`

**Comment by hanweisen** [comment]
>I didn't get it, why must add image_ready_tag in docker.sh, KAMADA_IMAGE_AGENT_READY in build-image.sh is not enough?
`hack/local-up-karmada.sh` line 108 make images GOOS="linux" --directory="${REPO_ROOT}" will build all images include karmada-agent.  

> Another question, make image-xxx will run both go build and docker build. You only prevent docker build twice, but not go build
Yes you are right

**Comment by ikaven1024** [comment]
> make images GOOS="linux" --directory="${REPO_ROOT}" will build all images include karmada-agent

You can build several images with it:
https://github.com/karmada-io/karmada/blob/3e057819f5605a1437a9b2b95f2cda78e182a8be/Makefile#L63

```diff
diff --git a/hack/local-up-karmada.sh b/hack/local-up-karmada.sh
index c9adf2a6..19498c12 100755
--- a/hack/local-up-karmada.sh
+++ b/hack/local-up-karmada.sh
@@ -105,7 +105,8 @@ util::create_cluster "${PULL_MODE_CLUSTER_NAME}" "${MEMBER_CLUSTER_KUBECONFIG}"
 #step2. make images and get karmadactl
 export VERSION="latest"
 export REGISTRY="swr.ap-southeast-1.myhuaweicloud.com/karmada"
-make images GOOS="linux" --directory="${REPO_ROOT}"
+make images karmada-aggregated-apiserver karmada-controller-manager ... GOOS="linux" --directory="${REPO_ROOT}"
+ensure_image_karama_agent
 
 GO111MODULE=on go install "github.com/karmada-io/karmada/cmd/karmadactl"
 GOPATH=$(go env GOPATH | awk -F ':' '{print $1}')

```

**Comment by hanweisen** [comment]
> You can build several images with it:

If make change like this. I think `ensure_image_karama_agent` is not need any more. Just let `hack/deploy-karmada-agent.sh` response to build images for karmada-agent.

**Comment by ikaven1024** [comment]
> Just let hack/deploy-karmada-agent.sh response to build images for karmada-agent.

Yes, you can do it solving this issue.
While, i am thinking when we add more cluster with agent, `hack/deploy-karmada-agent.sh` will run some times.

**Comment by hanweisen** [comment]
Yes we really should consider this situation. May be some e2e test need more than one member cluster join with pull mode

**Comment by RainbowMango** [comment]
> When developing karmada-agent, developer may way execute hack/deploy-karmada-agent.sh directly and want to build the karmada-agent image only.

I think `hack/local-up-karmada.sh` would fit most cases for development. Please reminds me if it doesn't.

**Comment by ikaven1024** [comment]
> I think `hack/local-up-karmada.sh` would fit most cases for development.

`hack/local-up-karmada.sh` will desctroy old clusters and create new cluster. Developer may have created some resource in cluster, and donnot want it lost.
