### ISSUE TITLE
 Incorrect used the member cluster context

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1772]
https://github.com/karmada-io/karmada/blob/b2ebfb60361a8ac54fb9e2da9728f08ae5c3a02f/hack/deploy-scheduler-estimator.sh#L52

When I manually deploy `scheduler estimator`, kubectl incorrect used the member cluster context.

It will cause me to connect to the member cluster, but I don't want to.
Maybe I can delete it directly,

**Comment by RainbowMango** [comment]
cc @Garrybest

**Comment by chaunceyjiang** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/17962021/167974441-57a3b829-81ed-416e-8965-cf7d3bc5b9f7.png">

**Comment by wuyingjun-lucky** [comment]
good scheme
