### ISSUE TITLE
kubectl karmada unjoin CLUSTER_NAME can not remove clusters

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1773]
**What happened**:
kubectl karmada unjoin CLUSTER_NAME can not remote clusters
**What you expected to happen**:
kubectl karmada unjoin CLUSTER_NAME can remove clusters
**How to reproduce it (as minimally and precisely as possible)**:
1、
<img width="861" alt="image" src="https://user-images.githubusercontent.com/16109961/167818454-5a8060d4-b5ff-4ca4-b710-95d56ea20d53.png">
2、
<img width="716" alt="image" src="https://user-images.githubusercontent.com/16109961/167818635-d24f1929-1f52-4bf5-9cc9-ce352f5b0111.png">

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by wuyingjun-lucky** [comment]
@lonelyCZ help me to check the bug and can you tell me when we command `kubectl karmada unjoin CLUSTER_NAME`
What we want happen? Just remove the cluster only and keep resource in the member cluster?

**Comment by chaunceyjiang** [comment]
It should be like this
```shell 
kubectl karmada unjoin k8s-node3  --kubeconfig=/Users/chauncey/github/karmada-etc/karmada-apiserver.config  --cluster-kubeconfig=/Users/chauncey/github/karmada-etc/k8s-node3.kubeconfig 
```

[unregister-cluster-by-cli](https://karmada.io/docs/userguide/cluster-registration#unregister-cluster-by-cli)

**Comment by wuyingjun-lucky** [comment]
> It should be like this
> 
> ```shell
> kubectl karmada unjoin k8s-node3  --kubeconfig=/Users/chauncey/github/karmada-etc/karmada-apiserver.config  --cluster-kubeconfig=/Users/chauncey/github/karmada-etc/k8s-node3.kubeconfig 
> ```
> 
> [unregister-cluster-by-cli](https://karmada.io/docs/userguide/cluster-registration#unregister-cluster-by-cli)

Yes , The help message is not correct
