### ISSUE TITLE
When I want to promote a deploy from member to cluster control plane It failed because I have not created a namespace. 

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1776]
**Please provide an in-depth description of the question you have**:
When I want to promote a deploy from member to cluster control plane
It failed when I have not created a namespace. 
Why karmadactl design like this.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/16109961/167973697-d204b8d3-8865-4c72-82c2-f17858d5de34.png">

**What do you think about this question?**:
If we created a namespace in control plane we do not need to create in member cluster again
Or should we add some flags like --createNS=true? to reduce the promote operations

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:
- Karmadactl promote

**Comment by lonelyCZ** [comment]
Right, the command only support to promote one resource once, if there is not namespace, we need to promote namespace firstly, which is tedious. Namespace is alway used, `--createNS=true` is useful.

**Comment by duanmengkk** [comment]
> Right, the command only support to promote one resource once, if there is not namespace, we need to promote namespace firstly, which is tedious. Namespace is alway used, `--createNS=true` is useful.

Shoule the dependencies(configmap secrets) be promoted? @lonelyCZ

**Comment by lonelyCZ** [comment]
> Should the dependencies(configmap secrets) be promoted?

It's a little bit complicated. If you are interested in it, we can talk about it on next meeting.

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
