### ISSUE TITLE
Can't compile on Mac

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1779]
**What happened**:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/17962021/168019354-8f072f3e-52b3-4dd4-92d9-41672febd45f.png">

**What you expected to happen**:

Can compile on Mac 

**How to reproduce it (as minimally and precisely as possible)**:

The bash version of Mac OS is too low.
The `-A` parameter is not supported.

https://github.com/karmada-io/karmada/blob/master/hack/util.sh#L24

<img width="570" alt="image" src="https://user-images.githubusercontent.com/17962021/168019135-65ec8bfb-0bdb-4a52-ae6e-cbfeb35faad1.png">

**Anything else we need to know?**:

**Environment**:
- Karmada version:  master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Seems this has been solved by #1774.

**Comment by chaunceyjiang** [comment]
> Seems this has been solved by #1774.

They are not the same problem , 

only bash 4.0+ supports the  `-A`,
but mac os bash version is 3.2

**Comment by RainbowMango** [comment]
I get it. 
cc @ikaven1024 for comments.

**Comment by ikaven1024** [comment]
ok. i will fix.

**Comment by RainbowMango** [comment]
Sorry hold on @ikaven1024 , I see @chaunceyjiang has assigned this issue to himself. 
I guess you can help review the PR...
