### ISSUE TITLE
Disenable namespace controller affect other controllers

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1780]
**What happened**:

When I disenable `namespace` controller with `karmada-controller-manager` `--controllers` flag:

```diff
--- a/artifacts/deploy/karmada-controller-manager.yaml
+++ b/artifacts/deploy/karmada-controller-manager.yaml
@@ -28,6 +28,7 @@ spec:
             - --kubeconfig=/etc/kubeconfig
             - --bind-address=0.0.0.0
             - --cluster-status-update-frequency=10s
+            - --controllers=-namespace
             - --secure-port=10357
             - --feature-gates=PropagateDeps=true
             - --v=4
```

And then propagate namespace with `ClusterPropagationPolicy`, here will only generate `ClusterResourceBinding` but not `Work` object generate.

At the same time, all other controllers stop working.

The function does not correctly determine whether to enable the controller.

https://github.com/karmada-io/karmada/blob/0f2bd7c02b6231b644266fb30aa2d62faa261784/pkg/controllers/context/context.go#L69-L89

**What you expected to happen**:

When disenable someone controller, other controllers are not affected.

After the modification, it is better to add a ut to cover this scenario.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

It occurs on master branch.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by hanweisen** [comment]
--controllers=-namespace,*

**Comment by XiShanYongYe-Chang** [comment]
> add argument like this
> `--controllers=-namespace,*`

If so, the argument like `--controllers=-namespace` is an incorrect configuration?

**Comment by AllenZMC** [comment]
> Hi @AllenZMC , thanks.
> 
> It doesn't seem like a bug, we just need to add a ut.
> 
> /remove-kind bug

OK, I will do it later.

**Comment by XiShanYongYe-Chang** [comment]
> how does karmada-controller-manager disable and enable the controller that comes with k8s?

They control their own controllers, which were independent of each other.

**Comment by XiShanYongYe-Chang** [comment]
> what is the difference between k8s-controller-manager and karmada-controller-manager

Can refer here: https://github.com/karmada-io/karmada/blob/master/docs/frequently-asked-questions.md#why-karmada-requires-kube-controller-manager
