### ISSUE TITLE
Helm repo for chart retrieval

### ISSUE THREAD

**Issue by BartvdBerkHU** [karmada-io/karmada#1783]
**What would you like to be added**:
A Helm repo to be able to retreive a Helm chart remotely without cloning the GitHub repo.

**Why is this needed**:
I only need the Helm chart and not the other contents from the Git repo.

Is there a reason why the Karmada project has chosen to distribute its Helm chart via cloning the repo and call the chart locally?

**Comment by RainbowMango** [comment]
Thanks for reaching us @BartvdBerkHU.
Yeah, we are planning to do it.  @Poor12 is working on it.
