### ISSUE TITLE
【E2E】Add karmadactl promote test in e2e

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1786]
**What would you like to be added**:
【E2E】Add karmadactl promote test in e2e
**Why is this needed**:
lack of promote test

**Comment by wuyingjun-lucky** [comment]
@XiShanYongYe-Chang @lonelyCZ  Is it necessary to add promote e2e test?

**Comment by XiShanYongYe-Chang** [comment]
@wuyingjun-lucky Thanks for your attention to e2e. Currently, we just have one promotion test case for the workload(deployment): https://github.com/karmada-io/karmada/blob/0f2bd7c02b6231b644266fb30aa2d62faa261784/test/e2e/porting_workloads_test.go#L22

Which scenario do you want to add?

**Comment by wuyingjun-lucky** [comment]
> scenario 
I want to use karmadactl to promote originally. 
And add cluster resource.

**Comment by XiShanYongYe-Chang** [comment]
> I want to use karmadactl to promote originally.
> And add cluster resource.

I see.  Good 👍 .

We have not developed E2E test cases for `karmadactl` CLI yet. We look forward to your contributions in this regard.

**Comment by lonelyCZ** [comment]
Great. Expect for it.

**Comment by wuyingjun-lucky** [comment]
> > I want to use karmadactl to promote originally.
> > And add cluster resource.
> 
> I see. Good 👍 .
> 
> We have not developed E2E test cases for `karmadactl` CLI yet. We look forward to your contributions in this regard.

Should I add karmadactl_test or promote_test @lonelyCZ @XiShanYongYe-Chang 
I found the unjoined_test use karmadactl join and unjoin to do integrated testing
<img width="627" alt="image" src="https://user-images.githubusercontent.com/16109961/168196278-37202013-cd2e-4092-8d94-d30fc3f6851a.png">

**Comment by XiShanYongYe-Chang** [comment]
I this `karmadactl_test` is better, as we continue to add test case for the karmadactl subcommand, we can add new `karmadactl` folders.

`unjoined_test` file directly test `karmadactl.RunJoin` and `karmadactl.RunUnjoin` to build test case. Do you plan to add test case like this? If so, you can put the `unjoin_test` file content into the new karmadactl test file.

**Comment by XiShanYongYe-Chang** [comment]
/close 

As #1801 has added the karmadactl promote e2e test.
