### ISSUE TITLE
Resourcebindings  FULLYAPPLIED field is False

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1797]
**What happened**:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/17962021/168510569-2204ff9d-09d8-46db-a909-eeb1d7606b04.png">

**What you expected to happen**:

`FULLYAPPLIED` field is True

**How to reproduce it (as minimally and precisely as possible)**:
1. create pp 
``` shell 

# k get pp -ojsonpath="{.items[0].spec.resourceSelectors}" |jq

[
  {
    "apiVersion": "apps/v1",
    "kind": "Deployment",
    "name": "nginx",
    "namespace": "default"
  },
  {
    "apiVersion": "v1",
    "kind": "Service",
    "name": "nginx",
    "namespace": "default"
  }
]
```
2. apply nginx service 
``` shell 

# cat nginx-svc.yaml
kind: Service
apiVersion: v1
metadata:
  name: "nginx"
spec:
  selector:
    app: "nginx"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort

# k apply -f nginx-svc.yaml
service/nginx created

```

3. check resourcebindings
``` shell 
# k get resourcebindings
NAME               SCHEDULED   FULLYAPPLIED   AGE
nginx-deployment   True        True           5d
nginx-service      True        False          6m30s
```
**Anything else we need to know?**:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/17962021/168512620-8fc79574-a549-4fe3-ba3c-cf63dec6696e.png">

Why does `FullyAppliedFailed` happen before `AppliedSuccessful`？ 

**Environment**: 
- Karmada version:  v1.1.2 
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your pointing out!

**Comment by XiShanYongYe-Chang** [comment]
For services other than the lb type, it is unnecessary to collect their status, because for `.status.loadBalancer`, only services for the lb type exist.

Maybe we can fix this bug by modifying `assembleWorkStatus` function.

**Comment by chaunceyjiang** [comment]
> Maybe we can fix this bug by modifying assembleWorkStatus function.

Why not delete the follow code? 
https://github.com/karmada-io/karmada/blob/b54760bb00c05141bc968b12532d19ebeba61904/pkg/controllers/status/workstatus_controller.go#L286-L288

**Comment by XiShanYongYe-Chang** [comment]
> Why not delete the follow code?

This patch is added to reduce unnecessary work status updates. For resources with no status or meaningless status, we can only record whether the propagation is successful in work.

**Comment by XiShanYongYe-Chang** [comment]
This solution is feasible. Thanks~
