### ISSUE TITLE
How to scale the cluster horizontally to ensure maximum utilization of resources？

### ISSUE THREAD

**Issue by hyq-make** [karmada-io/karmada#1798]
**What would you like to be added**:
I want to add the function that ensure maximum utilization of resources.
**Why is this needed**:
For example, I have two clusters such as A and B. According to the resource utilization, I want to dispatch  microservices to these cluster. If A's cpu has been used by 95% and B's cpu has been used by 45%，we can believe that the B should be used with more. After resource allocation, I also need to consider load balancing between services. I'm trying to figure out a way to fix it. Do you feel the issues has practical value and significance? If you agree with me, I hope you can give me some suggestions. Thanks!

**Comment by GitHubxsy** [comment]
This feature appears to be a central HPA and can be elastically scaled across clusters.

**Comment by huangyiqi111** [comment]
Yes, this is my idea, and I think the function is significance for resource utilization. But I don't known without this function is implemented in other tools. If not, I want to try to add this function to Karmada.

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
