### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#1800]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Aclose+is%3Apr+author%3Aikaven1024

Hope bring more improvements for Karmada in the future.

**Comment by ikaven1024** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
Welcome !!!
+1 from me

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by RainbowMango** [comment]
Welcome @ikaven1024 
/close
