### ISSUE TITLE
Remove karmada-config flag in karmada-aggregated-apiserver

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1807]
**Task description**:

As `karmada-config` flag has been marked deprecated in `karmada-aggregated-apiserver` component, we need to remove this flag in `karmada-aggregated-apiserver` deployment.

**Solution**:

Remove `karmada-config` flag in `karmada-aggregated-apiserver` deployment, such as `artifacts/deploy/karmada-aggregated-apiserver.yaml:39`.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by huangyiqi111** [comment]
I want to try it.

**Comment by huangyiqi111** [comment]
I want to try it.
/assign

**Comment by XiShanYongYe-Chang** [comment]
@huangyiqi111 thanks.

**Comment by XiShanYongYe-Chang** [comment]
Hi @huangyiqi111, Have you encountered any difficulties?

**Comment by huangyiqi111** [comment]
> Hi @huangyiqi111, Have you encountered any difficulties?

Yes, I have been installed Karmada on Virtual Machine and don't known how to use it to do something. At the same time, I need a few days to deal with something for my department, so I will fix it later.  Is this mission urgent?

**Comment by huangyiqi111** [comment]
> Hi @huangyiqi111, Have you encountered any difficulties?

Yes, I have been installed Karmada on Virtual Machine and don't known how to use it to do something. At the same time, I need a few days to deal with something for my department, so I will fix it later. Is this issue urgent?

**Comment by RainbowMango** [comment]
No worries. Take your time. Feel free to let us know if you need help. @huangyiqi111

**Comment by anutosh491** [comment]
Hello @huangyiqi111 , if you're okay could I possibly try fixing this . Being a new contributor I would like to start with a good first issue and this issue looks approachable to me . I am getting some help setting up Karmada locally on Slack ([thread link](https://cloud-native.slack.com/archives/C02MUF8QXUN/p1652970743304369)) after which I would like to work on this !

**Comment by huangyiqi111** [comment]
> Hello @huangyiqi111 , if you're okay could I possibly try fixing this . Being a new contributor I would like to start with a good first issue and this issue looks approachable to me . I am getting some help setting up Karmada locally on Slack ([thread link](https://cloud-native.slack.com/archives/C02MUF8QXUN/p1652970743304369)) after which I would like to work on this !

Ok，you can do it! If you will fix it, Could you help me to understand it about this issue?

**Comment by huangyiqi111** [comment]
> Hello @huangyiqi111 , if you're okay could I possibly try fixing this . Being a new contributor I would like to start with a good first issue and this issue looks approachable to me . I am getting some help setting up Karmada locally on Slack ([thread link](https://cloud-native.slack.com/archives/C02MUF8QXUN/p1652970743304369)) after which I would like to work on this !

Ok，you can do it! If you will fixed it, Could you help me to understand it about this issue?

**Comment by anutosh491** [comment]
Simple grep command for "--karmada-config" shows me these files and references.

> 1) tl/cmdinit/kubernetes/deployments.go:	 "--karmada-config=/etc/kubeconfig",
> 2) artifacts/deploy/karmada-aggregated-apiserver.yaml:            - --karmada-config=/etc/kubeconfig
> 3) docs/upgrading/v0.10-v1.0.md:            - --karmada-config=/etc/kubeconfig
> 4) docs/CHANGELOG/CHANGELOG-1.1.md:- `karmada-aggregate-apiserver`: Deprecated `--master` and `--karmada-config` > flags. Please use `--kubeconfig` instead. 
> 5) charts/templates/karmada-aggregated-apiserver.yaml:            - --karmada-config=/etc/kubeconfig
> 6) cmd/aggregated-apiserver/app/options/options.go:	flags.StringVar(&o.karmadaConfig, "karmada-config", > o.karmadaConfig, "Path to a karmada-apiserver KubeConfig.")
> 7) cmd/aggregated-apiserver/app/options/options.go:	_ = flags.MarkDeprecated("karmada-config", "This flag is currently no-> op and will be deleted.")

If I am correct we just need to get rid of **2nd** and **5th** reference . Do we need to do anything else to address this issue ? I would be glad to hear from @XiShanYongYe-Chang and @RainbowMango Sir, if there is something else I would need to take into account !

**Comment by huangyiqi111** [comment]
> Simple grep command for "--karmada-config" shows me these files and references.
> 
> > 1. tl/cmdinit/kubernetes/deployments.go:	 "--karmada-config=/etc/kubeconfig",
> > 2. artifacts/deploy/karmada-aggregated-apiserver.yaml:            - --karmada-config=/etc/kubeconfig
> > 3. docs/upgrading/v0.10-v1.0.md:            - --karmada-config=/etc/kubeconfig
> > 4. docs/CHANGELOG/CHANGELOG-1.1.md:- `karmada-aggregate-apiserver`: Deprecated `--master` and `--karmada-config` >flags. Please use `--kubeconfig` instead.
> > 5. charts/templates/karmada-aggregated-apiserver.yaml:            - --karmada-config=/etc/kubeconfig
> > 6. cmd/aggregated-apiserver/app/options/options.go:	flags.StringVar(&o.karmadaConfig, "karmada-config", > o.karmadaConfig, "Path to a karmada-apiserver KubeConfig.")
> > 7. cmd/aggregated-apiserver/app/options/options.go:	_ = flags.MarkDeprecated("karmada-config", "This flag is currently no-> op and will be deleted.")
> 
> If I am correct we just need to get rid of **2nd** and **5th** reference . Do we need to do anything else to address this issue ? I would be glad to hear from @XiShanYongYe-Chang and @RainbowMango Sir, if there is something else I would need to take into account !

Thank you!

**Comment by XiShanYongYe-Chang** [comment]
> If I am correct we just need to get rid of **2nd, 3rd** and **5th** reference . Do we need to do anything else to address this issue ?

Thanks! 1st, 2nd and 5th is needed to be removed.

**Comment by anutosh491** [comment]
> Thanks! 1st, 2nd and 5th is needed to be removed.

Thanks for the quick response , I'll do the needful !!

**Comment by anutosh491** [comment]
Hello @XiShanYongYe-Chang , I made the change through another account which had already karmada setup on it ! Let me know what you feel about the change , thanks for the guidance !

**Comment by XiShanYongYe-Chang** [comment]
Hi @anutosh491, thanks! I have reviewed it.
