### ISSUE TITLE
Request to be a Member of Karmada community 

### ISSUE THREAD

**Issue by my-git9** [karmada-io/karmada#1809]
I'm requesting to be a Member of Karmada community.
Recently，I started to  trying to put some PRs for karmada

See:
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Amy-git9+is%3Aclosed+

Hope bring more improvements for Karmada in the future.

**Comment by my-git9** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1
Thanks @my-git9 for the contributions.
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Invitation sent, please visit https://github.com/karmada-io to accept and join.

**Comment by RainbowMango** [comment]
Welcome @my-git9 
/close

**Comment by my-git9** [comment]
Thanks
