### ISSUE TITLE
lease of karmada component create failed when use custom namespace

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1813]
**What happened**:
Lease of karmada component will create failed when use custom namespace, this problem is introduced by https://github.com/karmada-io/karmada/pull/1683

**What you expected to happen**:
karmada component create successfully whether use custom namespace or not.

**How to reproduce it (as minimally and precisely as possible)**:

1. kubectl create ns customns
2. karmada init --namespace=customns
3. wait for `karmada-controller-manager` running
4. kubectl -n customns logs $(karmada-controller-manager-pod-name)
you will see that there are some logs like create lease failed, because of namespace customns not found.

**Anything else we need to know?**:

there are three reasons:  

1.  karmada component is deployed in the host cluster, while the lease of karmada component is create in the karmada cluster.
2. the pr https://github.com/karmada-io/karmada/pull/1683 only deal with `karmada-controller-manager`,  other component like `karmada-scheduler` need also to be processed.
3. bad smells in `init` cmd, there should be systemNamespace, not namespace define in global const variable. https://github.com/karmada-io/karmada/blob/780d75c9164918d9eec927683c7bf1cdbf2236ec/pkg/karmadactl/cmdinit/karmada/deploy.go#L45

The third problem has already been fixed in master.

**Environment**:
- Karmada version: v1.1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by likakuli** [comment]
It seems that this bug have been fixed in master branch, so i closed it

**Comment by RainbowMango** [comment]
> It seems that this bug have been fixed in master branch, so i closed it

By which PR?

**Comment by likakuli** [comment]
there are two pr to support custom namespace

1. https://github.com/karmada-io/karmada/pull/1449
2. https://github.com/karmada-io/karmada/pull/1683

Both need to be cherrypick to v1.1.2 tag. For now, only the second pr was picked to v1.1.2 tag. This bug could be triggered when use v1.1.2 and use kubectl init --namespace.

**Comment by likakuli** [comment]
release-1.0 and release-1.1 have this bug also.

**Comment by RainbowMango** [comment]
OK. Thanks for pointing this out.
Can you help cherry-pick the missed one ?
You can use `hack/cherry_pick_pull.sh` to do it. 
https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md

**Comment by likakuli** [comment]
opened two pr to check pick https://github.com/karmada-io/karmada/pull/1449 to release-1.0 and release-1.1

https://github.com/karmada-io/karmada/pull/1827
https://github.com/karmada-io/karmada/pull/1826

**Comment by likakuli** [comment]
Do we need to cherrypick the lost pr into v1.1.tag also? release-1.0 and release-1.1 branch is ok now.

**Comment by RainbowMango** [comment]
No, we can't modify tags. After we cherry-pick patches to the release branch, we'll cut a new release(a new tag).
