### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1815]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs 10+ 
PRs：
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Awuyingjun-lucky+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by wuyingjun-lucky** [comment]
@RainbowMango

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Invitation sent, please visit https://github.com/karmada-io to confirm and join.

**Comment by wuyingjun-lucky** [comment]
Thank you @kevin-wangzefeng @RainbowMango
