### ISSUE TITLE
Promote failed if you promote a resource (other kind) with same name before

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1821]
**What happened**:
Promote failed if you promote a resource (other kind) with same name before
**What you expected to happen**:
promote sucess
**How to reproduce it (as minimally and precisely as possible)**:
`Step 1 in member`:
kubectl create clusterrole  test-0517 --verb=get,list,watch --resource=pods
kubectl create namespace test-0517
`Step 2 in karmada`
kubectl-karmada --kubeconfig /etc/karmada/karmada-apiserver.config promote clusterrole test-0517 -c cluster37
kubectl-karmada --kubeconfig /etc/karmada/karmada-apiserver.config promote namespace test-0517 -c cluster37
`Result`

<img width="982" alt="image" src="https://user-images.githubusercontent.com/16109961/168950130-a728b631-49d5-438e-b3aa-1812c298f8b9.png">

**Anything else we need to know?**:
@lonelyCZ Should we fix the error in this scenario ?
**Environment**:
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/16109961/168950311-9f94be8f-a432-48ec-9696-f3f298f5b380.png">

- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by lonelyCZ** [comment]
Thanks for finding it, yes, this is a bug, for cluster scope resource, we could add kind to the name of `cpp`.

**Comment by wuyingjun-lucky** [comment]
> add

kind + "-" + "name" + "-propagation" ?

**Comment by lonelyCZ** [comment]
> kind + "-" + "name" + "-propagation" ?

Good.
