### ISSUE TITLE
karmadactl taint  failed

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1823]
**What happened**:
karmadactl taint  failed
**What you expected to happen**:
karmadactl taint  sucess

**How to reproduce it (as minimally and precisely as possible)**:
`Step one`
Use karmadactl command to taint a cluster like
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/16109961/168967075-d69e506c-93d1-4ae4-b31b-75c6609da45f.png">
 
**Anything else we need to know?**:
`Debug log`
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/16109961/168967135-f884b6f9-218a-4b40-a719-32200b76ae2e.png">
It connect to host cluster api server but not karmada api server
@lonelyCZ please help me to check it is an error or not
**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by lonelyCZ** [comment]
Right, it is a problem, it always use default path. Thanks.
