### ISSUE TITLE
Huge CPU usage when apply workload.example.io_workloads.yaml

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1828]
cpu usage is too large when apply `workload.example.io_workloads.yaml` and my cluster is deployed by kind .It locked when i apply the work.
![image](https://user-images.githubusercontent.com/17697155/169036780-625a5d59-3108-40f4-b7b4-73c96e4a4356.png)

![image](https://user-images.githubusercontent.com/17697155/169036118-07d8f9f2-a5b1-4fad-965b-10a8a0cdc7ba.png)
Take other resource as a comparison.
![image](https://user-images.githubusercontent.com/17697155/169036547-bd5ab5c7-39df-40a3-951c-ae3ffd2e742c.png)

**What would you like to be added**:
improve the code or use other methods to optimize performance
**Why is this needed**:

**Comment by duanmengkk** [comment]
I have no idea about it, need your help @XiShanYongYe-Chang 
Is the problem location in it? 
![image](https://user-images.githubusercontent.com/17697155/169037690-ada44bbf-6dcd-47e0-bac5-87c38da1dfa0.png)

**Comment by duanmengkk** [comment]
It is not a bug, This is because `Template corev1.PodTemplateSpec json:"template" protobuf:"bytes,3,opt,name=template" `definited in `WorkloadSpec` is a little complex,so the apiserver take a long time to computing it. I delete `Template corev1.PodTemplateSpec json:"template"` and regenerate the crd, `kubectl apply -f workload.example.io_workloads.yaml `
will immediate response.

It takes a long time(15-30min) to apply it second time (first time is ok ). `Workload` is used for test, does `PodTemplateSpec`  really needed in workload.example.io_workloads? @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your analysis.

> `Workload` is used for test, does `PodTemplateSpec` really needed in workload.example.io_workloads?

We use it primarily to simulate a workload, similar to `Deployment`, as we use in e2e:

https://github.com/karmada-io/karmada/blob/4d5428e79824946cc7aeeceeca1b0e8c446233ed/test/helper/resource.go#L499
