### ISSUE TITLE
resource not rescheduled when uncordon cluster

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1844]
**What happened**:
resource not rescheduled when uncordon cluster

**What you expected to happen**:
reschedule triggered

**How to reproduce it (as minimally and precisely as possible)**:

1. cordon member cluster A.
2. create a deploy and a pp, set cluster affinity of pp to cluster A and B with `Duplicated` type.
3. deploy will scheduled to cluster B because of cluster A has taint which deploy not tolerate.
4. uncordon member cluster A
5. deploy will not deploy to cluster A.  rb.spec.cluster only has cluster B.

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by likakuli** [comment]
the reason is that karmada-scheduler only care cluster conditions, the other property's change will not trigger reschedule logic

**Comment by hanweisen** [comment]
I meet the same problem.

**Comment by duanmengkk** [comment]
We can use k8s as a comparison, `cordon `means `SchedulingDisabled`,pod in node will not be evicted,`drain ` will evicted pod instead.Maybe that's not a problem?

**Comment by likakuli** [comment]
If i set a nodeselector to pod that i want to schedule pod to node A. If node A is unschedulable, the pod will schedule failed. but when the node becomes schedulable, the pod will move to active queue to be scheduled again. 

karmada-scheduler not reschedule when cluster bacomes ready.

**Comment by duanmengkk** [comment]
> If node A is unschedulable, the pod will schedule failed

we have discussed about it ,k8s's nodeAffinity support two mode ,`requiredDuringSchedulingIgnoredDuringExecution` and `preferredDuringSchedulingIgnoredDuringExecution`, karmada's clusterAffinity seems is `preferredDuringSchedulingIgnoredDuringExecution`,that means if a cluster is not ready,replicas will scheduled to other ready cluster.
Maybe we should add a similar field in `PropagationPolicy.spec.placement.clusterAffinity ` as `preferredDuringSchedulingIgnoredDuringExecution`.otherwise, users will be misunderstood @RainbowMango

**Comment by likakuli** [comment]
I don't know if this comment is related to this?  https://github.com/karmada-io/karmada/blob/92a134b00fb77936921a595d14dd9a68be91e18a/pkg/scheduler/scheduler.go#L338

**Comment by duanmengkk** [comment]
> I don't know if this comment is related to this?
> 
> https://github.com/karmada-io/karmada/blob/92a134b00fb77936921a595d14dd9a68be91e18a/pkg/scheduler/scheduler.go#L338

Not really,it means if cluster'status from ready to unready, and if `failover ` is open,karmada will trigger a reschedule

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
