### ISSUE TITLE
how to use karmada to propagate keda.sh cr and istio cr and customer cr to member cluster?

### ISSUE THREAD

**Issue by wanghonglei5181** [karmada-io/karmada#1849]
**how to use karmada to propagate keda.sh cr and istio cr and customer cr to member cluster?**:
* for example ,i have 4 kubernetes cluster,they are run in diffrent data center.
* i need deploy kubernetes deployment\service\ingress\configmap\... etc.
* i need deploy keda.sh ,keda cr.
* i need deploy istio ,gateway\virtual service\destination rule\... etc.
* i need deploy some customer cr.
* all above , make up a http service
* i should propagate all of these to member cluster
* how use karmada to do this

**What do you think about this question?**:

**Environment**:
- Karmada version: latest
- Kubernetes version: 1.17 1.22
- Others:
i found the doc,https://github.com/karmada-io/karmada/blob/master/docs/istio-on-karmada.md
that is not my wanted

**Comment by RainbowMango** [comment]
From the title seem you are asking about the way to propagate `CRs`.
CRs are no different from Kubernetes native resources except that you should install the `CRDs` to the member cluster first, sure Karmada can help to propagate CRDs too, in that case, `CRD` itself is no different from other resources.

Let me know if it's not the case you are asking.

**Comment by wanghonglei5181** [comment]
## i have installed istio crds on karmada-apiserver\karmada-host\member1\member2\member3
## i create gateway and PropagationPolicy use the follow yamls 
## switch to member1\member2\member3,i can not found gateway cr in the three clusters
## am i do some wrong operation?
## thanks!!
```
0> cat gateway.yaml 
kind: "Gateway"
apiVersion: "networking.istio.io/v1alpha3"
metadata: 
  name: "wap-test-online-gateway"
spec: 
  servers: 
    - 
      port: 
        number: 80
        protocol: "HTTP"
        name: "wap-test-online-gateway"
      hosts: 
        - "i.test.example.com"
        - "test.example.com"
  selector: 
    istio: "ingressgateway"

0> cat propagationpolicy.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: istio-gateway-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      name: sinawap-test-online-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
```

**Comment by wanghonglei5181** [comment]
## here is some logs from kamada-controller-manager
```
0> kubectl logs karmada-controller-manager-54c54cd745-m7b4l    -n karmada-system --tail 10 -f 
I0520 07:20:22.192111       1 reflector.go:536] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Watch close - *unstructured.Unstructured total 7 items received
I0520 07:20:23.401773       1 cluster_status_controller.go:94] Syncing cluster status: member1
I0520 07:20:23.413524       1 cluster_status_controller.go:94] Syncing cluster status: member2
I0520 07:20:25.162649       1 reflector.go:536] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Watch close - *unstructured.Unstructured total 4 items received
I0520 07:20:25.171945       1 reflector.go:536] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Watch close - *unstructured.Unstructured total 8 items received
I0520 07:20:31.183142       1 reflector.go:536] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Watch close - *unstructured.Unstructured total 5 items received
I0520 07:20:33.433384       1 cluster_status_controller.go:94] Syncing cluster status: member1
I0520 07:20:33.439527       1 cluster_status_controller.go:94] Syncing cluster status: member2
I0520 07:20:43.471834       1 cluster_status_controller.go:94] Syncing cluster status: member1
I0520 07:20:43.474971       1 cluster_status_controller.go:94] Syncing cluster status: member2
I0520 07:20:51.616761       1 reflector.go:536] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:250: Watch close - *v1alpha1.ServiceImport total 3 items received
```

**Comment by RainbowMango** [comment]
`name: "wap-test-online-gateway"` vs `name: sinawap-test-online-gateway`
The name `wap-test-xxx` is different with `sinawap-test-xxx`.

**Comment by wanghonglei5181** [comment]
## the new yamls.
I delete the old .
use the new yamls to create,
i can not found gateway in member1/member2/member3

** thanks **
## the new yamls
0> cat gateway.yaml
kind: "Gateway"
apiVersion: "networking.istio.io/v1alpha3"
metadata: 
  name: "wap-test-online-gateway"
spec: 
  servers: 
    - 
      port: 
        number: 80
        protocol: "HTTP"
        name: "wap-test-online-gateway"
      hosts: 
        - "i.test.example.com"
        - "test.example.com"
  selector: 
    istio: "ingressgateway"

0> cat propagationpolicy.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: istio-gateway-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      name: wap-test-online-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3

**Comment by RainbowMango** [comment]
Please check the `ResourceBinding` object to see if the scheduler works as expected.

**Comment by wanghonglei5181** [comment]
## it looks like this,this is no gateway  resourceBinding
0> kubectl get resourcebindings.work.karmada.io -A
NAMESPACE   NAME               SCHEDULED   FULLYAPPLIED   AGE
default     nginx-deployment   True        True           2d1h

**Comment by RainbowMango** [comment]
It's weird. Then, please share the reproduction steps, then I can help reproduce on my side.

**Comment by wanghonglei5181** [comment]
i will redo all the comands,
later, i will show you

**Comment by wanghonglei5181** [comment]
#### i have recreated my all the kubernetes clusters,include karmada-host\member1\member2\member3.

##### the below yamls is a cr of keda.sh,it works ok.
0> cat propagationpolicy.yaml so.yaml 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mysql-scaledobject-propagation
spec:
  resourceSelectors:
    - apiVersion: keda.sh/v1alpha1
      kind: ScaledObject
      name: mysql-scaledobject
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-scaledobject
spec:
  scaleTargetRef:
    name: worker
  triggers:
  - type: mysql
    metadata:
      queryValue: "4"
      query: "SELECT CEIL(COUNT(*) / 6) FROM task_instance WHERE state='running' OR state='queued'"
    authenticationRef:
      name: keda-trigger-auth-mysql-secret

##### the below yamls is istio gateway and virtualservice, it works failed
0> cat *
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: vs-test-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1alpha3
      kind: VirtualService
      name: bookinfo
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: bookinfo-gateway-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1alpha3
      kind: Gateway
      name: bookinfo-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
        - member3
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080

##### karmada apiserver
0> kubectl get pp
NAME                             AGE
bookinfo-gateway-propagation     14m
mysql-scaledobject-propagation   148m
nginx-propagation                3h41m
vs-test-propagation              9m31s
0> kubectl get gateway
NAME               AGE
bookinfo-gateway   14m
0> kubectl get vs
NAME       GATEWAYS               HOSTS   AGE
bookinfo   ["bookinfo-gateway"]   ["*"]   12m

0> kubectl get so
NAME                 SCALETARGETKIND   SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION                   READY   ACTIVE   FALLBACK   AGE
mysql-scaledobject                     worker                        mysql      keda-trigger-auth-mysql-secret   
#####  member cluster
0> kubectl get gateway
No resources found in default namespace.

**hava been propagated  scaledobject  to member1**
0> kubectl get so
NAME                 SCALETARGETKIND   SCALETARGETNAME   MIN   MAX   TRIGGERS   AUTHENTICATION                   READY   ACTIVE    FALLBACK   AGE
mysql-scaledobject                     worker                        mysql      keda-trigger-auth-mysql-secret   False   Unknown   

0> kubectl get vs
No resources found in default namespace.

**Comment by RainbowMango** [comment]
> the below yamls is istio gateway and virtualservice, it works failed

Any error message do you get when applying the following yamls?

**Comment by wanghonglei5181** [comment]
no errors found

**Comment by wanghonglei5181** [comment]
i have another test，
run 2 kuberbetes cluster in diffrent machine。
that have the same issue

**Comment by wanghonglei5181** [comment]
if debug level is 8,the follow is the output

0> kubectl create -f gateway.yaml -v 8
I0607 09:32:30.327019 3753616 loader.go:372] Config loaded from file:  /root/.kube/config
I0607 09:32:30.329642 3753616 round_trippers.go:432] GET https://10.41.42.83:5443/openapi/v2?timeout=32s
I0607 09:32:30.329671 3753616 round_trippers.go:438] Request Headers:
I0607 09:32:30.329689 3753616 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:32:30.329702 3753616 round_trippers.go:442]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0607 09:32:30.356619 3753616 round_trippers.go:457] Response Status: 200 OK in 26 milliseconds
I0607 09:32:30.356652 3753616 round_trippers.go:460] Response Headers:
I0607 09:32:30.356666 3753616 round_trippers.go:463]     Last-Modified: Mon, 06 Jun 2022 08:17:24 GMT
I0607 09:32:30.356680 3753616 round_trippers.go:463]     X-From-Cache: 1
I0607 09:32:30.356688 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:32:30.356696 3753616 round_trippers.go:463]     Vary: Accept-Encoding
I0607 09:32:30.356704 3753616 round_trippers.go:463]     Vary: Accept
I0607 09:32:30.356712 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:32:30.356719 3753616 round_trippers.go:463]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0607 09:32:30.356734 3753616 round_trippers.go:463]     Accept-Ranges: bytes
I0607 09:32:30.356742 3753616 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:32:30.356749 3753616 round_trippers.go:463]     Content-Type: application/octet-stream
I0607 09:32:30.356756 3753616 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:32:30 GMT
I0607 09:32:30.356764 3753616 round_trippers.go:463]     Etag: "24C2F5D1B4AFFE0C1A32E2041CD7B42027956B18D04F140F7E29E47ABA98968DC60FB979FCC038E6236CD40388A829241C88258EE86B13BEDD703A3FC89297F9"
I0607 09:32:30.531018 3753616 request.go:1179] Response Body:
00000000  0a 03 32 2e 30 12 15 0a  0a 4b 75 62 65 72 6e 65  |..2.0....Kuberne|
00000010  74 65 73 12 07 76 31 2e  32 31 2e 37 42 9d f3 de  |tes..v1.21.7B...|
00000020  01 12 f3 29 0a 45 2f 61  70 69 73 2f 61 70 70 73  |...).E/apis/apps|
00000030  2f 76 31 2f 77 61 74 63  68 2f 6e 61 6d 65 73 70  |/v1/watch/namesp|
00000040  61 63 65 73 2f 7b 6e 61  6d 65 73 70 61 63 65 7d  |aces/{namespace}|
00000050  2f 63 6f 6e 74 72 6f 6c  6c 65 72 72 65 76 69 73  |/controllerrevis|
00000060  69 6f 6e 73 2f 7b 6e 61  6d 65 7d 12 a9 29 12 fa  |ions/{name}..)..|
00000070  04 0a 07 61 70 70 73 5f  76 31 1a b9 01 77 61 74  |...apps_v1...wat|
00000080  63 68 20 63 68 61 6e 67  65 73 20 74 6f 20 61 6e  |ch changes to an|
00000090  20 6f 62 6a 65 63 74 20  6f 66 20 6b 69 6e 64 20  | object of kind |
000000a0  43 6f 6e 74 72 6f 6c 6c  65 72 52 65 76 69 73 69  |ControllerRevisi|
000000b0  6f 6e 2e 20 64 65 70 72  65 63 61 74 65 64 3a 20  |on. deprecated: |
000000c0  75 73 65 20 74 68 65 20  27 77 61 74 63 68 27 20  |use the 'watch' [truncated 24460132 chars]
I0607 09:32:30.604746 3753616 round_trippers.go:432] GET https://10.41.42.83:5443/apis/external.metrics.k8s.io/v1beta1?timeout=32s
I0607 09:32:30.604784 3753616 round_trippers.go:438] Request Headers:
I0607 09:32:30.604796 3753616 round_trippers.go:442]     Accept: application/json, */*
I0607 09:32:30.604806 3753616 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:32:30.610413 3753616 round_trippers.go:457] Response Status: 503 Service Unavailable in 5 milliseconds
I0607 09:32:30.610444 3753616 round_trippers.go:460] Response Headers:
I0607 09:32:30.610450 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:32:30.610462 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:32:30.610471 3753616 round_trippers.go:463]     Content-Length: 20
I0607 09:32:30.610479 3753616 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:32:30 GMT
I0607 09:32:30.610486 3753616 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:32:30.610494 3753616 round_trippers.go:463]     Content-Type: text/plain; charset=utf-8
I0607 09:32:30.610502 3753616 round_trippers.go:463]     X-Content-Type-Options: nosniff
I0607 09:32:30.611719 3753616 request.go:1181] Response Body: service unavailable
I0607 09:32:30.612563 3753616 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0607 09:32:30.612589 3753616 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0607 09:32:30.620577 3753616 request.go:1181] Request Body: {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"name":"bookinfo-gateway","namespace":"default"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
I0607 09:32:30.620677 3753616 round_trippers.go:432] POST https://10.41.42.83:5443/apis/networking.istio.io/v1alpha3/namespaces/default/gateways?fieldManager=kubectl-create
I0607 09:32:30.620693 3753616 round_trippers.go:438] Request Headers:
I0607 09:32:30.620700 3753616 round_trippers.go:442]     Accept: application/json
I0607 09:32:30.620707 3753616 round_trippers.go:442]     Content-Type: application/json
I0607 09:32:30.620713 3753616 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:32:30.626026 3753616 round_trippers.go:457] Response Status: 201 Created in 5 milliseconds
I0607 09:32:30.626050 3753616 round_trippers.go:460] Response Headers:
I0607 09:32:30.626056 3753616 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:32:30.626061 3753616 round_trippers.go:463]     Content-Type: application/json
I0607 09:32:30.626065 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:32:30.626077 3753616 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:32:30.626082 3753616 round_trippers.go:463]     Content-Length: 629
I0607 09:32:30.626088 3753616 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:32:30 GMT
I0607 09:32:30.626121 3753616 request.go:1181] Response Body: {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"creationTimestamp":"2022-06-07T01:32:30Z","generation":1,"managedFields":[{"apiVersion":"networking.istio.io/v1alpha3","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{".":{},"f:selector":{".":{},"f:istio":{}},"f:servers":{}}},"manager":"kubectl-create","operation":"Update","time":"2022-06-07T01:32:30Z"}],"name":"bookinfo-gateway","namespace":"default","resourceVersion":"142664","uid":"07e04538-ea9a-485a-9196-08b981d3dea8"},"spec":{"selector":{"istio":"ingressgateway"},"servers":[{"hosts":["*"],"port":{"name":"http","number":80,"protocol":"HTTP"}}]}}
gateway.networking.istio.io/bookinfo-gateway created

**Comment by wanghonglei5181** [comment]
for compare ,the follow is scaledObject of keda.sh

0> kubectl create -f so.yaml  -v 8
I0607 09:41:04.024477 3763932 loader.go:372] Config loaded from file:  /root/.kube/config
I0607 09:41:04.026893 3763932 round_trippers.go:432] GET https://10.41.42.83:5443/openapi/v2?timeout=32s
I0607 09:41:04.026915 3763932 round_trippers.go:438] Request Headers:
I0607 09:41:04.026930 3763932 round_trippers.go:442]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0607 09:41:04.026941 3763932 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:41:04.062444 3763932 round_trippers.go:457] Response Status: 200 OK in 35 milliseconds
I0607 09:41:04.062475 3763932 round_trippers.go:460] Response Headers:
I0607 09:41:04.062489 3763932 round_trippers.go:463]     Vary: Accept-Encoding
I0607 09:41:04.062497 3763932 round_trippers.go:463]     Vary: Accept
I0607 09:41:04.062505 3763932 round_trippers.go:463]     X-From-Cache: 1
I0607 09:41:04.062512 3763932 round_trippers.go:463]     Accept-Ranges: bytes
I0607 09:41:04.062520 3763932 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:41:04.062527 3763932 round_trippers.go:463]     Content-Type: application/octet-stream
I0607 09:41:04.062534 3763932 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:41:04 GMT
I0607 09:41:04.062542 3763932 round_trippers.go:463]     Etag: "24C2F5D1B4AFFE0C1A32E2041CD7B42027956B18D04F140F7E29E47ABA98968DC60FB979FCC038E6236CD40388A829241C88258EE86B13BEDD703A3FC89297F9"
I0607 09:41:04.062557 3763932 round_trippers.go:463]     Last-Modified: Mon, 06 Jun 2022 08:17:24 GMT
I0607 09:41:04.062566 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:41:04.062573 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:41:04.062580 3763932 round_trippers.go:463]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0607 09:41:04.291924 3763932 request.go:1179] Response Body:
00000000  0a 03 32 2e 30 12 15 0a  0a 4b 75 62 65 72 6e 65  |..2.0....Kuberne|
00000010  74 65 73 12 07 76 31 2e  32 31 2e 37 42 9d f3 de  |tes..v1.21.7B...|
00000020  01 12 f3 29 0a 45 2f 61  70 69 73 2f 61 70 70 73  |...).E/apis/apps|
00000030  2f 76 31 2f 77 61 74 63  68 2f 6e 61 6d 65 73 70  |/v1/watch/namesp|
00000040  61 63 65 73 2f 7b 6e 61  6d 65 73 70 61 63 65 7d  |aces/{namespace}|
00000050  2f 63 6f 6e 74 72 6f 6c  6c 65 72 72 65 76 69 73  |/controllerrevis|
00000060  69 6f 6e 73 2f 7b 6e 61  6d 65 7d 12 a9 29 12 fa  |ions/{name}..)..|
00000070  04 0a 07 61 70 70 73 5f  76 31 1a b9 01 77 61 74  |...apps_v1...wat|
00000080  63 68 20 63 68 61 6e 67  65 73 20 74 6f 20 61 6e  |ch changes to an|
00000090  20 6f 62 6a 65 63 74 20  6f 66 20 6b 69 6e 64 20  | object of kind |
000000a0  43 6f 6e 74 72 6f 6c 6c  65 72 52 65 76 69 73 69  |ControllerRevisi|
000000b0  6f 6e 2e 20 64 65 70 72  65 63 61 74 65 64 3a 20  |on. deprecated: |
000000c0  75 73 65 20 74 68 65 20  27 77 61 74 63 68 27 20  |use the 'watch' [truncated 24460132 chars]
I0607 09:41:04.396151 3763932 round_trippers.go:432] GET https://10.41.42.83:5443/apis/external.metrics.k8s.io/v1beta1?timeout=32s
I0607 09:41:04.396187 3763932 round_trippers.go:438] Request Headers:
I0607 09:41:04.396198 3763932 round_trippers.go:442]     Accept: application/json, */*
I0607 09:41:04.396208 3763932 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:41:04.398145 3763932 round_trippers.go:457] Response Status: 503 Service Unavailable in 1 milliseconds
I0607 09:41:04.398167 3763932 round_trippers.go:460] Response Headers:
I0607 09:41:04.398180 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:41:04.398204 3763932 round_trippers.go:463]     Content-Length: 20
I0607 09:41:04.398213 3763932 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:41:04 GMT
I0607 09:41:04.398225 3763932 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:41:04.398237 3763932 round_trippers.go:463]     Content-Type: text/plain; charset=utf-8
I0607 09:41:04.398248 3763932 round_trippers.go:463]     X-Content-Type-Options: nosniff
I0607 09:41:04.398259 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:41:04.399660 3763932 request.go:1181] Response Body: service unavailable
I0607 09:41:04.400668 3763932 request.go:1372] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0607 09:41:04.400706 3763932 cached_discovery.go:78] skipped caching discovery info due to the server is currently unable to handle the request
I0607 09:41:04.402258 3763932 request.go:1181] Request Body: {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"name":"mysql-scaledobject","namespace":"default"},"spec":{"scaleTargetRef":{"name":"worker"},"triggers":[{"authenticationRef":{"name":"keda-trigger-auth-mysql-secret"},"metadata":{"query":"SELECT CEIL(COUNT(*) / 6) FROM task_instance WHERE state='running' OR state='queued'","queryValue":"4"},"type":"mysql"}]}}
I0607 09:41:04.402333 3763932 round_trippers.go:432] POST https://10.41.42.83:5443/apis/keda.sh/v1alpha1/namespaces/default/scaledobjects?fieldManager=kubectl-create
I0607 09:41:04.402356 3763932 round_trippers.go:438] Request Headers:
I0607 09:41:04.402372 3763932 round_trippers.go:442]     Accept: application/json
I0607 09:41:04.402385 3763932 round_trippers.go:442]     Content-Type: application/json
I0607 09:41:04.402400 3763932 round_trippers.go:442]     User-Agent: kubectl/v1.22.2 (linux/amd64) kubernetes/8b5a191
I0607 09:41:04.409258 3763932 round_trippers.go:457] Response Status: 201 Created in 6 milliseconds
I0607 09:41:04.409290 3763932 round_trippers.go:460] Response Headers:
I0607 09:41:04.409303 3763932 round_trippers.go:463]     Cache-Control: no-cache, private
I0607 09:41:04.409316 3763932 round_trippers.go:463]     Content-Type: application/json
I0607 09:41:04.409329 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 301c0feb-aa86-44c7-9441-c6565ff6b37e
I0607 09:41:04.409345 3763932 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 9d4da6be-9050-407b-a9f7-15195795943e
I0607 09:41:04.409357 3763932 round_trippers.go:463]     Content-Length: 751
I0607 09:41:04.409369 3763932 round_trippers.go:463]     Date: Tue, 07 Jun 2022 01:41:04 GMT
I0607 09:41:04.409428 3763932 request.go:1181] Response Body: {"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"creationTimestamp":"2022-06-07T01:41:04Z","generation":1,"managedFields":[{"apiVersion":"keda.sh/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{".":{},"f:scaleTargetRef":{".":{},"f:name":{}},"f:triggers":{}}},"manager":"kubectl-create","operation":"Update","time":"2022-06-07T01:41:04Z"}],"name":"mysql-scaledobject","namespace":"default","resourceVersion":"143806","uid":"e2e2dfaf-1521-4058-b630-afca2b19bcc8"},"spec":{"scaleTargetRef":{"name":"worker"},"triggers":[{"authenticationRef":{"name":"keda-trigger-auth-mysql-secret"},"metadata":{"query":"SELECT CEIL(COUNT(*) / 6) FROM task_instance WHERE state='running' OR state='queued'","queryValue":"4"},"type":"mysql"}]}}
scaledobject.keda.sh/mysql-scaledobject created

**Comment by wanghonglei5181** [comment]
thanks @RainbowMango 

<img width="1417" alt="图片" src="https://user-images.githubusercontent.com/8133524/172297028-5449e545-4ed3-4cc8-926e-dca14bd2b5a6.png">

##  get more logs 
kubectl edit deployment karmada-controller-manager -n karmada-system
modify the arg  --v to 6
##  use this yaml it works fine
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: bookinfo-gateway-propagation
spec:
  resourceSelectors:
    - apiVersion: networking.istio.io/v1beta1  ## karmada actually use this apiverison
      kind: Gateway
      name: bookinfo-gateway
  placement:
    clusterAffinity:
      clusterNames:
        - member1
```

##

**Comment by XiShanYongYe-Chang** [comment]
Use `ClusterPropagationPolicy` to propagate the CRD resource.

**Comment by RainbowMango** [comment]
@wanghonglei5181 talked to me on WeChat, and this issue has been solved as mentioned at https://github.com/karmada-io/karmada/issues/1849#issuecomment-1148191300.

/close
