### ISSUE TITLE
Support --context in karmadactl 

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1852]
**What would you like to be added**:
add `--kubeconfig` and `--context` in karmadactl 
**Why is this needed**:
I have a problem when excuting promote command
![image](https://user-images.githubusercontent.com/17697155/169492382-edf4f1ec-9f3e-4618-9f81-4393b48c1aca.png)

**Comment by duanmengkk** [comment]
Do you think we need it ? @lonelyCZ

**Comment by lonelyCZ** [comment]
Please have a try `--karmada-context`

**Comment by duanmengkk** [comment]
> Please have a try `--karmada-context`

thanks,why not `--context` @lonelyCZ

**Comment by lonelyCZ** [comment]
> why not --context

Perhaps, it can distinguish your operations between karmada-host-cluster and karmada-control-plane.

For example, the `karmadactl init` use `--context` to operate karmada-host-cluster.

**Comment by duanmengkk** [comment]
sorry,i can not understand, `kubectl karmada --context {context-name}`,Didn't we distinguish operations by `context-name`?

**Comment by lonelyCZ** [comment]
Yes, there are two `context` in `karmadactl` that can prompt the user not to use it incorrectly. 

Of course, I don't think it will do much. That's probably the only reason to use `--karmada-context` now.

This is Karmada's early definition, maybe ask @RainbowMango  what he thinks.
