### ISSUE TITLE
Use taint instead of condition in karmada scheduler

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1853]
**What would you like to be added**:

use taint to filter cluster instead of using cluster ready condition.

**Why is this needed**:

User story:

Support set not ready clusters to rb.  For now, not ready cluster will be filtered.

for example:

pp's cluster affinity has tow cluster: A and B, and B is not ready for some reason now.

if i add another ready cluster C to pp's cluster affinity, the rb.spec.cluster will be A and C，which will result to resources already dispatched to cluster B be deleted. This is what we not expected to happen. Just let rb.spec.clusters be A and B and C even if cluster B is not ready, karmada-controller-manager will retry to make resource dispatched to cluster B when it becomes ready.

Use taint instead of condition could make it easy to be controlled by user who has the requirement. The only thing need to do is to set pp's clustertolerations as actual requirement.

**Comment by duanmengkk** [comment]
refer to https://github.com/karmada-io/karmada/issues/1762,  They are working for it now.

**Comment by likakuli** [comment]
> refer to #1762, They are working for it now.

thx，I found the taint has already been added. so i just make a pr to update karmada scheduler to make it not filter cluster by condition.

**Comment by likakuli** [comment]
https://github.com/karmada-io/karmada/issues/1762 is for evict, use `TaintEffectNoExecute`, taint is added when failover eviction timeout, but what i need is to add `TaintEffectNoSchedule` immediately when cluster not ready.

**Comment by Garrybest** [comment]
Hi @likakuli, we'are going to stop evicting already-scheduled result in scheduler. So I think this problem may be fixed after https://github.com/karmada-io/karmada/issues/1762.

**Comment by likakuli** [comment]
I don't have any requirement for eviction. In my case, i wish the resource  can be scheduled to clusters specified in pp's placement whether the cluster is ready or not and whether the api  is installed in the cluster or not.

Maybe i can directly operate the resoucebinding to skip the karmada scheduler?

**Comment by Garrybest** [comment]
It seems like you want to disable some plugins, right?

Now all plugins are enabled by default and cannot be configurable via config file. There is a plan to optimize config files. https://github.com/karmada-io/karmada/issues/1605#issuecomment-1098848260 may be useful.

**Comment by likakuli** [comment]
https://github.com/karmada-io/karmada/blob/9a72c70085db4b15eef05c881c7f1cead1896941/pkg/scheduler/core/generic_scheduler.go#L96

for now, the unready cluster will be filtered before the first plugin execute. I wish that unready cluster be filtered by taint which means that in cluster controller we can add taint to cluster when cluster not ready and update the code above like this
```go
clusters := clusterInfo.GetClusters() 
```

When all these work done, user can determine whether to schedule resource to unready cluster by themself. What they need   to do is to set `ClusterTolerations` of pp's `Placement`.

**Comment by Garrybest** [comment]
Oh, I get you. We are supposed to abstract unhealthy as taints instead of handle conditions itself.

So would you like to make a contribution for this issue? @likakuli 
[Here](https://github.com/kubernetes/kubernetes/blob/1868a3a2eb9945f26239f700fc491fb37232db5a/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L611-L665) are some references for you. And I think we should add this logic [in this place](https://github.com/karmada-io/karmada/blob/7e6c38a6e79e9e0c2b18eaaf5f55a230e385757a/pkg/controllers/cluster/cluster_controller.go#L175-L186).

**Comment by RainbowMango** [comment]
I agree with what @Garrybest said above.

I have some questions about the user story you mentioned in the issue description.

> if i add another ready cluster C to pp's cluster affinity, the rb.spec.cluster will be A and C，which will result to resources already dispatched to cluster B be deleted. This is what we not expected to happen.

Does the `PP` looks like:
```
    clusterAffinity:
      clusterNames:
        - A
        - B
        - C
```
And you want the workload to be propagated to the three clusters even when some of them are in a `not-ready` state?

I can't get it, why do you insist on propagating workloads to the `not-ready` cluster? 
If the `PP` tries [Divide](https://github.com/karmada-io/karmada/blob/3f1d0cf81c0f83766c3002688a47f8e2d745ff38/pkg/apis/policy/v1alpha1/propagation_types.go#L211) replicas, I'm afraid the `not-ready` cluster also takes some, is that acceptable? Or you just uses the [Duplicated](https://github.com/karmada-io/karmada/blob/master/pkg/apis/policy/v1alpha1/propagation_types.go#L211)?

**Comment by likakuli** [comment]
> And you want the workload to be propagated to the three clusters even when some of them are in a `not-ready` state?

yes



> why do you insist on propagating workloads to the `not-ready` cluster?

We need to provision cluster before it can serve. The cluster joined to karmada in our scene is default cordoned and we will propagate some resources to it and check whether all resources specified has been propagated successfully before uncordon.

The karmada scheduler will not schedule resource to cluster even it changes from `not-ready` to `ready` if rb has been scheduled once.

**Comment by likakuli** [comment]
> It seems like you want to disable some plugins, right?

https://github.com/karmada-io/karmada/pull/1663 can't disable default plugins but https://github.com/karmada-io/karmada/pull/2135 can do that.

**Comment by RainbowMango** [comment]
/assign @likakuli 
as #1854
