### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by liys87x** [karmada-io/karmada#1860]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Aclose+is%3Apr+author%3Aliys87x

Hope bring more improvements for Karmada in the future.

**Comment by liys87x** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng
