### ISSUE TITLE
support to promote dependency resources automatically

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1862]
**What would you like to be added**:
Currently,`kubectl kamada promote` only support promote resources one by one ,wish to support promote dependency resources automatically

**Why is this needed**:

**Comment by duanmengkk** [comment]
It is a bit more complicated for promoting CRDs,Anyone with ideas will be welcome!

**Comment by yanfeng1992** [comment]
Consider adding a Workload Promotion crd and promote controller to realize the function of promote? I tried to realize the promote resource and its dependencies. @duanmengkk @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Thanks to all of you~
Use issue #3842 to track the task in subsequent steps.
/close

**Comment by liangyuanpeng** [comment]
@XiShanYongYe-Chang Could you help to remote the label of `help wanted`? Thanks.

**Comment by liangyuanpeng** [comment]
> Could you help to remote the label of `help wanted`? Thanks.

It's closed, so it's fine, do not need to remove label.

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang Could you help to remote the label of `help wanted`? Thanks.

ok~ let me try
/remove-kind help
