### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1864]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs 10+
PRs：
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Aduanmengkk
Issues:
https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3Aduanmengkk
Hope bring more improvements for Karmada in the future.

**Comment by duanmengkk** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
Seems I missed this. Sorry for that :(
+1

**Comment by duanmengkk** [comment]
3q~

**Comment by kevin-wangzefeng** [comment]
+1

**Comment by RainbowMango** [comment]
Welcome @duanmengkk 
/close
