### ISSUE TITLE
Transform objects in informer

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#1866]
**What would you like to be added**:
Adopt `SetTransform` feature of `client-go`.

**Why is this needed**:
Save memory usage for the informers.

### References
background: https://github.com/karmada-io/karmada/pull/1858#issuecomment-1134114741
SetTransform feature: https://github.com/kubernetes/kubernetes/pull/107507

### Dependencies 
- [ ] Bump Kubernetes dependencies to v1.24 (do it after release-1.2)

**Comment by dddddai** [comment]
Transforming pods would prevent users from propagating pods directly, personally I don't think users would do it though... but anyway it's a breaking change, do you think it's ok to ignore it?

**Comment by RainbowMango** [comment]
> Transforming pods would prevent users from propagating pods directly, 

Why do you think that?  I haven't looked at this feature carefully but seems we can `null out` unused fields to save ram cost.
