### ISSUE TITLE
Use Istio on Karmada

### ISSUE THREAD

**Issue by suwliang3** [karmada-io/karmada#1868]
**What would you like to be added**:
All clusters reside on the different network,when using Istio on Karmada.

**Why is this needed**:

In most cases,the clusters reside on different network,meaning there is not direct connectivity between the pods in every clusters.I want to know your next plan.

**Comment by duanmengkk** [comment]
How about submariner?https://github.com/karmada-io/karmada/blob/master/docs/working-with-submariner.md

**Comment by lonelyCZ** [comment]
The other day, there was a topic in Kubecon, https://static.sched.com/hosted_files/kccnceu2022/1d/Sailing_Multi_Cloud_Traffic_Management_With_Karmada_ZhonghuXu.pdf

**Comment by suwliang3** [comment]
@duanmengkk @lonelyCZ Thank you for your answer and sharing.Flattening the network through a submariner is one solution.I would like to know how to build a multi-network model with karmada without using a submariner.Is there such a solution now like 
https://github.com/karmada-io/karmada/blob/master/docs/istio-on-karmada.md?

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
