### ISSUE TITLE
helm ：Certificate generation of karmada-config

### ISSUE THREAD

**Issue by lts0609** [karmada-io/karmada#1880]
**Please provide an in-depth description of the question you have**:
从master上获取chart包，修改values中clusterip改为nodeport
用helm部署karmada后，
kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d > admin.conf 导出config
生成的config文件的内容为
server: https://karmada-apiserver.karmada-system.svc.cluster.local:5443
服务暴露方式已经改变后，config生成时端口仍然是5443
又查看了二进制部署后生成的config内容
server: https://111.111.203.51:32443
按照微信群里的解答，手动修改server部分为127.0.0.1后，还是不可用
```
kubectl get cluster --kubeconfig admin.conf
The connection to the server 127.0.0.1:5443 was refused - did you specify the right host or port?
```
改成 127.0.0.1:32443
```
Unable to connect to the server: dial tcp 127.0.0.1:32443: i/o timeout
```
改成 111.111.203.51:5443
```
The connection to the server 111.111.203.51:5443 was refused - did you specify the right host or port?
```
改成 111.111.203.51:32443
```
Unable to connect to the server: x509: certificate is valid for 127.0.0.1, not 111.111.203.51
```
我最后修改了values里生成证书的host添加了本机ip，重新部署
```
hosts: [
"kubernetes.default.svc",
"*.etcd.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}",
"*.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}",
"*.{{ .Release.Namespace }}.svc",
"localhost",
"127.0.0.1",
"111.111.203.51"        # 手动添加了本机IP
]
```
然后导出config，把server改成 111.111.203.51:32443 才能正常使用

**What do you think about this question?**:
1. 证书的生成是不是还存在一些问题，只有127
2. config文件生成后的server是不是应该像二进制部署一样，不再要手动修改
3. 如果证书只对于127.0.0.1，那如何用pull方法添加成员集群

**Comment by prodanlabs** [comment]
karmada apiserver 默认端口是5443，karmada 组件是通过  `karmada-kubeconfig` secret 连接 karmada apiserver , karmada 是部署在k8s中的，server 地址应该是 dns (karmada-apiserver.karmada-system.svc.cluster.local) 而不是 IP，这与 karmada apiserver 的 Service 类型没有关系，不管是 `NodePort` 还是 `ClusterIP`  ，`karmada-kubeconfig`  都是不变的。

问题2：
我不清楚你说的二进制部署说的是不是 `karmadactl init`。如果是通过 `karmadactl init` 是安装的karmada， 那karmada apiserver 的 Service 类型是`NodePort` ，端口是32443。它会额外生产一个config文件，地址是k8s master节点的地址，端口是32443
https://github.com/karmada-io/karmada/blob/56d5aec0dff9693604996e129eb27ae84809e4ab/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L414-L419

问题3：
 如果是 `karmadactl init` 安装，默认会取执行 `karmadactl init` 命令的服务器的公网IP，加到证书里面
https://github.com/karmada-io/karmada/blob/56d5aec0dff9693604996e129eb27ae84809e4ab/pkg/karmadactl/cmdinit/utils/format.go#L54-L69

另外，还可以通过 `--cert-external-ip` 和 `cert-external-dns` 参数，把IP和DNS地址加入到证书里面.

**Comment by lts0609** [comment]
> karmada apiserver 默认端口是5443，karmada 组件是通过 `karmada-kubeconfig` secret 连接 karmada apiserver , karmada 是部署在k8s中的，server 地址应该是 dns (karmada-apiserver.karmada-system.svc.cluster.local) 而不是 IP，这与 karmada apiserver 的 Service 类型没有关系，不管是 `NodePort` 还是 `ClusterIP` ，`karmada-kubeconfig` 都是不变的。
> 
> 问题2： 我不清楚你说的二进制部署说的是不是 `karmadactl init`。如果是通过 `karmadactl init` 安装的karmada， 那karmada apiserver 的 Service 类型是`NodePort` ，端口是32443。它会额外生成一个config文件，地址是k8s master节点的地址，端口是32443
> 
> https://github.com/karmada-io/karmada/blob/56d5aec0dff9693604996e129eb27ae84809e4ab/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L414-L419
> 
> 问题3： 如果是 `karmadactl init` 安装，默认会取执行 `karmadactl init` 命令的服务器的公网IP，加到证书里面
> 
> https://github.com/karmada-io/karmada/blob/56d5aec0dff9693604996e129eb27ae84809e4ab/pkg/karmadactl/cmdinit/utils/format.go#L54-L69
> 
> 另外，还可以通过 `--cert-external-ip` 和 `cert-external-dns` 参数，把IP和DNS地址加入到证书里面.

karmada init 部署后的 secret `kubeconfig` 和helm部署后的secret `karmada-kubeconfig` 内容是一致的，都在控制面集群中的

但是init额外生成的 `/etc/karmada-apiserver.config`  中的 server 是 IP 而不是 `secret` 中的 DNS

如果helm部署karmada后我要进行操作，在没有创建context `karmada-apiservcer`的情况下需要手动指定 `kubeconfig` 文件，这个 config 我是要由 `karmada-kubeconfig` 导出后，修改 server 来来实现，还是有其他的办法可以得到如 init 后生成的 `karmada-apiserver.config` 呢，不然是如何操作控制面资源的

helm部署时要如何添加 Internet ip 到证书里，如果证书中没有公网IP，那在pull添加成员集群时怎么创建secret来连接apiserver

 在添加成员集群时，我了解的push方法是指定 karmada-kubeconfig 和待添加集群的 kubeconfig，pull方法拿karmada-kubeconfig创建secret和agent，helm部署后也是一样吗？我看到https://github.com/karmada-io/karmada/tree/master/charts#1-install-agent 这部分不是很清楚具体是如何修改和操作的，这个agent和pull创建的agent是一个吗，可不可以解答下，谢谢

**Comment by jrkeen** [comment]
`kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d > admin.conf` 这个命令是拿到集群内部的 kubeconfig ，要使用这个 kubeconfig ，前提你在集群内网中，比如你在这个集群的 pod 中。如果你要在生成的证书中添加 IP，需要在 values 文件中，添加你的 IP，pre-job 会自动处理。如果你需要在集群外部访问该集群，需要重新编辑拿到的内部 kubeconfig, 修改 server 地址为你的 karmada apiserver 外部 IP，同时这个 IP 需要添加到证书中。目前不支持一键生成所需的 kubeconfig，欢迎贡献👏。

**Comment by 631068264** [comment]
@jrkeen 使用helm chart安装遇到同样问题，建议更新helm chart部分的文档。不然安装流程都不完善，干嘛要开放helm chart安装方式？
