### ISSUE TITLE
Propagate dependencies add support propagate pvc and service

### ISSUE THREAD

**Issue by hanweisen** [karmada-io/karmada#1887]
**What would you like to be added**:
Propagate dependencies add support propagate `pvc` and `service,` and give a option to user configure which resources need to dependend propagate
**Why is this needed**:
Propagate dependencies support propagate `configmap` and `secret` #1684

**Comment by RainbowMango** [comment]
I added this issue to release-1.3 backlog.

**Comment by xyz2277** [comment]
I can work it with you @hanweisen

**Comment by chaunceyjiang** [comment]
Any progress? If you are not free now, can I take the issue? @hanweisen
