### ISSUE TITLE
feature or bug

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#1888]
**Please provide an in-depth description of the question you have**:

1. Why resource detector not set up rb's informer? for now if we delete the rb, it will not auto generated by resource detector.
2. if we delete pp first and then delete the rb, after we recreate the pp, the rb will be recreated as expected. If we delete the rb first and then delete the pp, after we recreate the pp, rb will not recreated because the resource detector not put resource into `waitingObjects` queue in this case. Is this a feature or a bug?

**What do you think about this question?**:
1. the key about above question is that can rb be accessed and operated directly by user? 

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by likakuli** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
`feature or bug` depends on if this is a real use case. 

> the key about above question is that can rb be accessed and operated directly by user?

Technically speaking, the user can access the RB objects, e.g  get status from it. But the users should know the RB object is managed by the Karmada system, they shouldn't delete/create/update it unless they really know what they are doing.

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
