### ISSUE TITLE
SyncEvent from execution_controller is not be bind with workload

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#1898]
**What would you like to be added**:
Now SyncEvent from execution_controller is not be bind with workload. For example, when you apply a nginx deployment to member clusters. You can see the sync event like below:
![image](https://user-images.githubusercontent.com/26862112/170808585-01486741-00f5-47d7-be2f-c09620a496cc.png)
But it is not bind with actual workload:
![image](https://user-images.githubusercontent.com/26862112/170625069-8e360b9c-0cb8-4f10-bebc-dba8acb3536a.png)

Mainly because the workload in the work object is just a template, some values like resourceVersion and UID is missing. I wonder if there is a way to improve it.

**Why is this needed**:
Improve user experience.

**Comment by hanweisen** [comment]
This feature is useful. I think I need this feature.

**Comment by RainbowMango** [comment]
> Mainly because the workload in the work object is just a template, some values like resourceVersion and UID is missing.

What exactly needs to bind an even to an object? `resourceVersion` or `UID`, or both of them are mandatory?

**Comment by RainbowMango** [comment]
```
# kubectl describe deployments.apps nginx --v=6
...
I0608 15:20:22.350148 3806953 round_trippers.go:553] GET https://172.18.0.2:5443/api/v1/namespaces/default/events?fieldSelector=involvedObject.name%3Dnginx%2CinvolvedObject.namespace%3Ddefault%2CinvolvedObject.kind%3DDeployment%2CinvolvedObject.uid%3D81c62bf4-ebd0-440f-abe6-f0e82bf0654c&limit=500 200 OK in 1 milliseconds
...
Name:                   nginx
Namespace:              default
...
Events:
  Type    Reason                  Age                 From                Message
  ----    ------                  ----                ----                -------
  Normal  SyncWorkSucceed         11m (x10 over 11m)  binding-controller  Sync work of resourceBinding(default/nginx-deployment) successful.
  Normal  ApplyPolicySucceed      11m (x4 over 11m)   resource-detector   Apply policy(default/nginx-propagation) succeed
  Normal  AggregateStatusSucceed  11m (x10 over 11m)  binding-controller  Update resourceBinding(default/nginx-deployment) with AggregatedStatus successfully.
  Normal  ScheduleBindingSucceed  11m (x10 over 11m)  karmada-scheduler   Binding has been scheduled
```

kubectl gets the object's relevant events by API:
```
api/v1/namespaces/default/events?fieldSelector=involvedObject.name%3Dnginx%2CinvolvedObject.namespace%3Ddefault%2CinvolvedObject.kind%3DDeployment%2CinvolvedObject.uid%3D81c62bf4-ebd0-440f-abe6-f0e82bf0654c
```
So, the `name`/`namespace`/`kind`/`uid` are necessary items when firing an event.

**Comment by RainbowMango** [comment]
The root cause is that when [firing the event for the workload in `Work` object](https://github.com/karmada-io/karmada/blob/3791cd581573651a1caf3e0220d52a17367d32b2/pkg/controllers/execution/execution_controller.go#L212), the `uid` information is missing.

The reason for `uid` missing is due to `karmada-webhook` removed the irrelevant fields:
https://github.com/karmada-io/karmada/blob/3791cd581573651a1caf3e0220d52a17367d32b2/pkg/webhook/work/mutating.go#L46
