### ISSUE TITLE
Install error :unable to prepare context:

### ISSUE THREAD

**Issue by maoyangLiu** [karmada-io/karmada#1910]
when I install karamda whit the command : hack/local-up-karmada.sh
when  Building image for linux/amd64: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:latest
+ docker build --build-arg BINARY=karmada-aggregated-apiserver --tag swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:latest --file hack/../cluster/images/Dockerfile hack/../_output/bin/linux/amd64
return an error  unable to prepare context: The Dockerfile (/root/karmada/cluster/images/Dockerfile) must be within the build context (hack/../_output/bin/linux/amd64)

What is wrong with my configuration or operation

**Environment**:  centos7
- Karmada version:  the master branch
- Kubernetes version: 1.20.4
- Others:

**Comment by RainbowMango** [comment]
Is it the first time you use the `hack/local-up-karmada.sh`? 

Are you running the script under the root of the repo?

**Comment by maoyangLiu** [comment]
@RainbowMango   It is my first time to use it ,I do run the script in the root directory, but I have the same problem in the home directory，I can't find the cause of the problem

**Comment by AnteBox** [comment]
> @RainbowMango 第一次用，在根目录下运行脚本，但是在home目录下也出现同样的问题，找不到问题的原因

I have the same problem, I upgraded my docker version(form 1.13.1 to 20.10.17). There is no such problem now.

**Comment by RainbowMango** [comment]
Thanks @AnteBox.  @maoyangLiu what's the docker version you are using? Can you upgrade it and try again?

**Comment by ikaven1024** [comment]
Dockerfile is allowed from outside build-context after docker 18.03. https://github.com/docker/cli/pull/886
@AnteBox @maoyangLiu, plz update your docker above this version.
 

By the way, @RainbowMango  shall we support the docker under v18? we can link the Dockerfile to the build dir.

**Comment by RainbowMango** [comment]
> By the way, @RainbowMango shall we support the docker under v18? we can link the Dockerfile to the build dir.

I didn't hear anyone ask for it.
