### ISSUE TITLE
[UT] add unite test for pkg/registry/search/storage/requestinfo.go

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#1918]
**Task description**:

Add unite test for pkg/registry/search/storage/requestinfo.go

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by CharlesQQ** [comment]
I can try it
/assign

**Comment by XiShanYongYe-Chang** [comment]
@CharlesQQ Thanks！
