### ISSUE TITLE
Request to be a member of Karmada

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#1922]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs 10+
PRs：
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3APoor12
Issues:
https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3APoor12+
Hope bring more improvements for Karmada in the future.

**Comment by RainbowMango** [comment]
+1

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Invited, please visit https://github.com/karmada-io to accept the invitation.
