### ISSUE TITLE
How to propagate a long-size yaml resource 

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#1934]
**Please provide an in-depth description of the question you have**:
Some opensource products is deployed by a long-size yaml,such as calico https://docs.projectcalico.org/manifests/calico.yaml
Is there a way to provide an easy way to deploy it to member cluster.This way I don't have to write resources one by one into a propagationpolicy.

**What do you think about this question?**:

This work is a bit like Ansible. Can we provide a command like this `karmadactl  apply -f calico.yaml -c member1,member2,member3`

**Comment by duanmengkk** [comment]
@lonelyCZ @XiShanYongYe-Chang

**Comment by calvin0327** [comment]
In the case:
There are 3 resource in the yaml file, I want create resource 1, 2 to `member1` and `member2`, create resource3 to `member3`.
How do we design the command？

**Comment by duanmengkk** [comment]
> In the case: There are 3 resource in the yaml file, I want create resource 1, 2 to `member1` and `member2`, create resource3 to `member3`. How do we design the command？

I guess in this scenario, you must write resources  in the yaml into propagationPolicy one by one.

**Comment by lonelyCZ** [comment]
This is a interesting feature! But should we need to select the `schedule policy` in this command?

**Comment by duanmengkk** [comment]
> This is a interesting feature! Should we need to select the `schedule policy` in this command?

I thought about it before.In my opinion ,long size yaml is not need to schedule, it just need to propagated to member cluster,right ?

**Comment by RainbowMango** [comment]
/assign @carlory 
as #2192
