### ISSUE TITLE
karmada search return empty list  sometimes

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#1946]
**What happened**:
use the command `kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/apis/apps/v1/deployments | python -m json.tool` to fetch all deployments from cache, but return empty list sometimes
<img width="274" alt="image" src="https://user-images.githubusercontent.com/18431718/171539050-41f5e82b-ca32-43f9-8795-1521d0e79a2c.png">

log print following message:
`W0602 10:32:24.626462      28 cache.go:96] SingleClusterInformerManager for cluster(xxx) is nil.`

**What you expected to happen**:
return  resource list of all member cluster 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
# kubectl get resourceregistries.search.karmada.io test -o yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  annotations:
  creationTimestamp: "2022-06-01T13:42:13Z"
  managedFields:
  - apiVersion: search.karmada.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:resourceSelectors: {}
        f:targetCluster:
          f:clusterNames: {}
    manager: kubectl
    operation: Update
    time: "2022-06-01T13:42:13Z"
  name: test
  resourceVersion: "246709202"
  uid: c82278f3-b2e2-40bc-a058-135484cb17bd
spec:
  resourceSelectors:
  - apiVersion: apps/v1
    kind: Deployment
  targetCluster:
    clusterNames:
    - xxx
status: {}
```

**Environment**:
- Karmada version:  v1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
![image](https://user-images.githubusercontent.com/17962021/171541788-71336b0b-6a48-4e99-acef-697c102277ce.png)

**Comment by XiShanYongYe-Chang** [comment]
Will it happen or will it happen occasionally? 

Is there are some logs like this:

```log
I0602 03:00:16.369366       1 controller.go:200] try to build informer manager for cluster member1
I0602 03:00:16.404053       1 controller.go:222] add informer for member1, apps/v1, Resource=deployments
I0602 03:00:16.404137       1 controller.go:225] start informer for member1
I0602 03:00:16.505041       1 controller.go:228] start informer for member1 done
```

We need to start an informer for member clusters.

**Comment by GitHubxsy** [comment]
![image](https://user-images.githubusercontent.com/11901080/171546916-cf15a694-d1dc-43eb-a798-124227ddfdca.png)

The karmada-search component is a multi-instance component and works in load balancing mode. Some instances work abnormally？

**Comment by CharlesQQ** [comment]
`Some instances work abnormally？`
3 instances, I find that cluster in pull mode, log print following message:
```E0603 10:23:42.547929      26 controller.go:160] Error cache memeber cluster member1, cluster member1 does not have a secret
W0603 10:44:39.627526      26 cache.go:96] SingleClusterInformerManager for cluster(member1) is nil.```

**Comment by CharlesQQ** [comment]
https://github.com/karmada-io/karmada/blob/36368ce50e29678d683f2f3c5562503fc9a96483/pkg/search/controller.go#L203-L205

create clusterDynamicClient need secret, but in pull mode, karmada control plane can not find secret objects

**Comment by RainbowMango** [comment]
> create clusterDynamicClient need secret, but in pull mode, karmada control plane can not find secret objects

Right. For now, karmada-agent won't report `secret` for `Pull` mode cluster. 
I think it's time to do it now.

**Comment by CharlesQQ** [comment]
> I think it's time to do it now.
May be I can try it~
/assign

**Comment by RainbowMango** [comment]
Just share some ideas here:

1. We need to introduce a flag to `karmada-agent` to specify whether report secret when registering cluster.
2. Then implements the logic at [registerWithControlPlaneAPIServer](https://github.com/karmada-io/karmada/blob/1bc32ea8fc003a0755254ac35a4f1af1a3830f1b/cmd/agent/app/agent.go#L294)

**Comment by GitHubxsy** [comment]
The **karmada search** and **aggregation API** feature requires that the kube-apiserver of the member cluster be accessed from the karmada control plane. If you cannot directly access the network due to network restrictions, you are advised to use the reverse proxy mode and set the cluster.proxyURL field. 

The aggregation API uses the **ImpersonatorSecret** (empty permission). The karmada search uses the **cluster.secretRef** (higher permission is required). Currently, the **cluster.secretRef** is missing.
If you do not use the karmada search feature, you can choose not to report the secret.

**Comment by XiShanYongYe-Chang** [comment]
Hi @CharlesQQ, dose this issue been fixed?

**Comment by RainbowMango** [comment]
ping @CharlesQQ
