### ISSUE TITLE
We want to get resource（pod）details from  karmada-control-plane by using apiserver

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1949]
**Please provide an in-depth description of the question you have**:

Requirement:
`1` We have one k8s cluster for running  our deployments|sts|.... and the number of deployments|sts|.... is increasing. The k8s cluster is under pressure.
`2` We plan to use karmada to  dispatch the deployments to member clusters. 
But our application （web client） need to get pods or other resource details from apiserver and do not want to get this from member that will bring costs of coding.

**What do you think about this question?**:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/16109961/171584707-13539211-7c29-43b6-a0c8-f4fe739961bb.png">
Is there some way or plane to resolve this ?

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by wuyingjun-lucky** [comment]
> 
Some confused , our application want to ignore resource location.  It seems we can not ignore member clusters by using aa

**Comment by XiShanYongYe-Chang** [comment]
> Some confused , our application want to ignore resource location. It seems we can not ignore member clusters by using aa

Aye, we need to assign a cluster when using aa. `Karmada-search` will get resources from all config clusters through cache, it migths fit your need.

**Comment by XiShanYongYe-Chang** [comment]
> By the way，does the result data structure of karmada-search keep pace with origin result from api-server ?

Yes. Refer to #1891

**Comment by wuyingjun-lucky** [comment]
> #1891

Thanks a lot. We may be the first real users of karmada-search

**Comment by XiShanYongYe-Chang** [comment]
We also store the resource into OpenSearch, refer to #1897

**Comment by wuyingjun-lucky** [comment]
> We also store the resource into OpenSearch, refer to #1897

OK，GOT it

**Comment by wuyingjun-lucky** [comment]
some questions， optional components  can not be installed by karmadactl init

**Comment by wuyingjun-lucky** [comment]
> We also store the resource into OpenSearch, refer to #1897

It seems we can only get the rest by rest api. But our app code is written by client-go , do you have some ideas for the capable of adapting

**Comment by RainbowMango** [comment]
@wuyingjun-lucky At the community meeting yesterday, @ikaven1024 proposed an idea that might properly fit your needs. 
Hold on for a while, @ikaven1024 will send a feature proposal.

**Comment by wuyingjun-lucky** [comment]
> 

Yeah , I have participated in the meeting

**Comment by ikaven1024** [comment]
@wuyingjun-lucky  #2058

**Comment by wuyingjun-lucky** [comment]
> @wuyingjun-lucky #2058

OK, Thanks

**Comment by ikaven1024** [comment]
Hi @wuyingjun-lucky proxy feature has released in v1.3.0. You can try it. Looking forward your feedback.

**Comment by wuyingjun-lucky** [comment]
> Hi @wuyingjun-lucky proxy feature has released in v1.3.0. You can try it. Looking forward your feedback.

OK  We will try it as soon as possible.

**Comment by XiShanYongYe-Chang** [comment]
It seems that the issue has been fixed, close it first, and you can always reopen it if there is a problem.
/close
