### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by zgfh** [karmada-io/karmada#1954]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Azgfh

Hope bring more improvements for Karmada in the future.

**Comment by RainbowMango** [comment]
+1
Thanks @zgfh for your contributions.
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Invitation sent as well, please visit [@karmada-io](https://github.com/karmada-io) to accept the invitation.

**Comment by zgfh** [comment]
thanks @kevin-wangzefeng @RainbowMango
