### ISSUE TITLE
feature: `karmadactl init` support param of  "--karmada-version"

### ISSUE THREAD

**Issue by zgfh** [karmada-io/karmada#1956]
**What would you like to be added**:
for now, if I want install  karmada of specific versions ,I need set many params,like :
```
karmada_version="v1.2.1"
image_repository="swr.ap-southeast-1.myhuaweicloud.com"
kubectl karmada init -n ${ns} --crds https://github.com/karmada-io/karmada/releases/download/${karmada_version}/crds.tar.gz \
  --karmada-aggregated-apiserver-image ${image_repository}karmada/karmada-aggregated-apiserver:${karmada_version} \
  --karmada-controller-manager-image ${image_repository}karmada/karmada-controller-manager:${karmada_version} \
  --karmada-scheduler-image ${image_repository}karmada/karmada-scheduler:${karmada_version} \
  --karmada-webhook-image ${image_repository}karmada/karmada-webhook:${karmada_version}
```

I have a idea(like kubeadm):
```
--image-repository: Choose a container registry to pull control plane images from (default "swr.ap-southeast-1.myhuaweicloud.com")
--karmada-version string            Choose a specific karmada version for the control plane. (default "latest")
```

**Why is this needed**:
simplified installation of specific versions

**Comment by wuyingjun-lucky** [comment]
We have introduced --kube-image-mirror-country and --kube-image-registry 
It looks pretty and good  
What do you think about it @RainbowMango @lonelyCZ

**Comment by prodanlabs** [comment]
I feel great.

**Comment by prodanlabs** [comment]
But there is a problem, if a lower version of `karmadactl` is installed with a higher version of karmada, some parameters of the higher version of karmada may have changed, then how to deal with the lower version of `karmadactl`

**Comment by RainbowMango** [comment]
> But there is a problem, if a lower version of `karmadactl` is installed with a higher version of karmada, some parameters of the higher version of karmada may have changed, then how to deal with the lower version of `karmadactl`

I don't know how `kubeadm` handle this kind of thing, I think it's not guaranteed for a lower version `karmadactl` to install a higher Karmada.

**Comment by prodanlabs** [comment]
> > But there is a problem, if a lower version of `karmadactl` is installed with a higher version of karmada, some parameters of the higher version of karmada may have changed, then how to deal with the lower version of `karmadactl`
> 
> I don't know how `kubeadm` handle this kind of thing, I think it's not guaranteed for a lower version `karmadactl` to install a higher Karmada.

AFAIK, `kubeadm` does not have the problem of installing a higher version of `kubernetes` with a lower version of `kubeadm` or installing a lower version of `kubernetes` with a higher version of `kubeadm`.

If you install a specific version, usually update the `kubeadm` and `kubelet` versions first, and then execute `kubeadm upgrade`.

**Comment by zgfh** [comment]
there is waht i find:  

minVersion: [there is waht i find:  ](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/common.go#L124)

maxVersion: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/preflight/checks.go#L592

should I refer to this implementation？

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
