### ISSUE TITLE
What is the plan of optional component to be installed by karmadactl

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#1957]
**Please provide an in-depth description of the question you have**:
1. We have installed karmada control plane by using `karmadactl init` at first
2. We want to study search component for https://github.com/karmada-io/karmada/issues/1949  but it seems can not be installed by `karmadactl` like other optional components.
**What do you think about this question?**:
What is the plan of optional component to be installed by `karmadactl`
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by wuyingjun-lucky** [comment]
@RainbowMango @XiShanYongYe-Chang @lonelyCZ

**Comment by RainbowMango** [comment]
@lonelyCZ and @prodanlabs are the authors, I think we can make a plan for it.

**Comment by lonelyCZ** [comment]
Associate #1879 

Yes, we can make a plan for it. Could you share your ideas about it? @duanmengkk @wuyingjun-lucky 

After talking, we can make a `umbrella` issue to trace it.

**Comment by wuyingjun-lucky** [comment]
> Associate #1879
> 
> Yes, we can make a plan for it. Could you share your ideas about it? @duanmengkk @wuyingjun-lucky
> 
> After talking, we can make a `umbrella` issue to trace it.

OK， We will work for it  and make a plan in spare time as soon as possible

**Comment by lonelyCZ** [comment]
Thanks!

/assign @duanmengkk

**Comment by chaunceyjiang** [comment]
Have you made any progress recently for this issue   @wuyingjun-lucky 

> What is the plan of optional component to be installed by karmadactl

karmada-search addon ?
karmada-scheduler-estimator addon ?

**Comment by wuyingjun-lucky** [comment]
> 

Sorry, we got a little busy earlier and will start these days 

I think the addons can be supported one by one
