### ISSUE TITLE
 REQUEST: New karmada project karmada-installer

### ISSUE THREAD

**Issue by riverzhang** [karmada-io/karmada#1970]
**What would you like to be added**:
Add new project `karmada-installer` in karmada-io.

**Why is this needed**:
1. related issues：#1276
2. [karmada installation survey for 2022](https://docs.google.com/document/d/1lOXHfpLiA0sg5dJr7ye9E0Qemd_YvOS-TACfsA3xQig/edit) #1889 
3. Our plan:
    -  integrate all current deployment approaches. Including Ansible + [Karmada Charts](https://github.com/karmada-io/karmada/tree/master/charts) and [Kubectl Karmada](https://github.com/karmada-io/karmada/tree/master/cmd/kubectl-karmada)，based on ansible. 
    -  Build CI infrastructure for testing our karmada-installer
    -  karmada-installer operator API,  It is a kubernetes operator deploy in meta/host kubernetes and manage karmada(create、scale、delete、upgrade、 fault self-healing, etc...)

intro:
===

API driven Karmada provisioning and management.

Karmada-installer is an operator which runs as a service on top of Kubernetes.The Karmada-installer service
can be used to provision and perform initial configuration of karmada.

For provisioning Karmada, Karmada-installer uses the all current deployment tools approaches.
- [Kubectl Karmada](https://github.com/karmada-io/karmada/tree/master/cmd/kubectl-karmada)
- [Karmada Charts](https://github.com/karmada-io/karmada/tree/master/charts)
- [binary install karmada]
- [karmada yaml](https://github.com/karmada-io/karmada/tree/master/artifacts/deploy)

To better use these tools, we used Ansible to orchestrate tasks,This playbook will install Karmada control plane 
and register a set of clusters to the karmada control plane.

Karmada-installer's roadmap
===========================

### Ansible Playbook
- deploy karmada
-  add and delete member cluster
- upgrade karmada
- reset karmada

## Continuous integration tests
- kubectl-karmada tests for all supported configurations(like kubectl-karmada init、join、unjoin)
- helm charts tests for all supported configurations
- install karmada from binaries tests
- upgrade tests(non-HA and HA upgrade tests)
- add/delete member cluster and reset karmada tests
- external etcd cluster supported tests
- addons tests(test special configurations like istio,argocd,etc...)
- e2e test(check karmada api and run e2e test)]

## Karmada Operator API
- operator api define
- controller logic implementation

**Comment by riverzhang** [comment]
@@RainbowMango

**Comment by riverzhang** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
For the repo name, I suppose you can give some options, such as :
- installer
- operator
- installation-operator
- karmadadm
- etc...

I'm not sure the repo name should start with `karmada-` prefix, since it's in `karmada-io` orgs.

**Comment by riverzhang** [comment]
ka-installer(k-->k8s, a-->armada)

**Comment by riverzhang** [comment]
List names for similar open source projects：
1.kubesphere -[ ks-installer](https://github.com/kubesphere/ks-installer):   k-->k8s,s-->sphere,and based on ansible +controller,
2.openshfit - [hive](https://github.com/openshift/hive): special meaning, and based on k8s operator

**Comment by RainbowMango** [comment]
Thanks @riverzhang for listing examples from other project.

I prefer to take `karmada-operator` as the repo name.

@kevin-wangzefeng @riverzhang how do you think?

**Comment by duanmengkk** [comment]
Is it simalar as ks-installler which use shell-operator(https://github.com/flant/shell-operator)  to deploy kubesphere? Or use operator-sdk(ansible operator sdk https://github.com/operator-framework/operator-sdk ) to deploy?  @riverzhang

**Comment by riverzhang** [comment]
> Is it simalar as ks-installler which use shell-operator(https://github.com/flant/shell-operator) to deploy kubesphere? Or use operator-sdk(ansible operator sdk https://github.com/operator-framework/operator-sdk ) to deploy? @riverzhang

Yes, similar usage.

**Comment by riverzhang** [comment]
> Thanks @riverzhang for listing examples from other project.
> 
> I prefer to take `karmada-operator` as the repo name.
> 
> @kevin-wangzefeng @riverzhang how do you think?

+1

**Comment by prodanlabs** [comment]
I personally think that organizations can be set up for karmada SIG related work, including but not limited to `karmada-installer`.

Maybe my idea may be unrealistic.

**Comment by RainbowMango** [comment]
Agree with @prodanlabs. We need SIGs.

**Comment by wuyingjun-lucky** [comment]
karmada-installer or karmada-operator

**Comment by RainbowMango** [comment]
repo created.
/close
