### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1973]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs and Issues 
See:

https://github.com/karmada-io/karmada/issues?q=+author%3Achaunceyjiang

Hope bring more improvements for Karmada in the future.

**Comment by RainbowMango** [comment]
+1
Thanks @chaunceyjiang for all your contributions.

/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
But please not add irrelevant lables.

**Comment by chaunceyjiang** [comment]
thx,joined
