### ISSUE TITLE
The namespace controller is turned off, but the namespace is still propagated to the member cluster

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1981]
**What happened**:

The namespace controller is turned off, but the namespace is still propagated to the member cluster.

**What you expected to happen**:

Do not propagate to member clusters

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/17962021/172783264-e1460020-9130-4235-9a9d-936af73ecc6c.png)

![image](https://user-images.githubusercontent.com/17962021/172783402-c27dfdff-af88-4324-b3ce-ea029bf76670.png)

![image](https://user-images.githubusercontent.com/17962021/172784184-487ce0cf-52b2-4e98-9fe3-cfe0f288590b.png)

**Anything else we need to know?**:

**Environment**:
- Karmada version:  v1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.2.0
- Others:

**Comment by RainbowMango** [comment]
The `namespace` controllers will propagate `namespace` to all joined clusters without a `PropagationPolicy`/`ClusterPropagationPolicy`.

But in your case, you are using a `ClusterPropagationPolicy`, so, I think the behavior is expected.
correct me if I misunderstand your case.

**Comment by chaunceyjiang** [comment]
> The namespace controllers will propagate namespace to all joined clusters without a PropagationPolicy/ClusterPropagationPolicy

I see...  ,thank you for your answer.
