### ISSUE TITLE
Why does Built-in Interpreter AggregateStatus not contain Pod

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#1988]
**Please provide an in-depth description of the question you have**:

Why does Built-in Interpreter [AggregateStatus](https://github.com/karmada-io/karmada/blob/master/docs/userguide/customizing-resource-interpreter.md#aggregatestatus) not contain Pod(v1)

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Working on it. See #1913.
