### ISSUE TITLE
Derived service doesn't change with origin service

### ISSUE THREAD

**Issue by Alphonse-iwnl** [karmada-io/karmada#1993]
**Please provide an in-depth description of the question you have**:
once service had propagated into member cluster, service in member cluster would change when origin service in control-plane has changed, but derived service doesn't; 

recording to source code of serviceImport controller, derived service  is only reconcile in serviceImport event, which means i have to update serviceImport when i actually want to update origin service, meanwhile there is many service information does not exist in serviceImport like selector, labels or annotations
**What do you think about this question?**:
i dont know if this as expected, if not, we might start a worker listening to the service event in serviceImport contorller for syncing the difference of origin svc and derived service
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by Alphonse-iwnl** [comment]
> Could you share your usage example? I am also interested in multi-cluster service/ingress recently.

condition we were facing:

- endpointSlice collected from member cluster is only related to derived service instead of origin service(logic in serviceExportContorller), so we build multi-cluster service dependent on derived service because we can easily find endpoint with it
-  some of our custom service function is opening to user by labels/annotations, but any changes made to origin service is not synchronized to derived service(spec/labels/annotations),  which cause user changes does not take effect. The situation require them to change both origin servcie, serviceImport and derived service if they want to make any update to the service.

i suppose user is more likely to modifying origin service than derived service, just because derived service is auto generated?  so im thinking about the necessary of the synchronizition between origin service and derived service

**Comment by XiShanYongYe-Chang** [comment]
Hi @Alphonse-iwnl, I think I may have understood what you mean: when the service changed, the derived service generated by the `ServiceImport controller` need to be synced at the meanwhile.

In fact, the derived service is defined by ServiceImport, and the original service simply determines the EndpointSlices of the derived service. The change of the original service will reflect in the EndpointSlices, then we will sync the change of EndpointSlices to the derived servcie.

**Comment by 1285yvonne** [comment]
> Hi @Alphonse-iwnl, I think I may have understood what you mean: when the service changed, the derived service generated by the `ServiceImport controller` need to be synced at the meanwhile.
> 
> In fact, the derived service is defined by ServiceImport, and the original service simply determines the EndpointSlices of the derived service. The change of the original service will reflect in the EndpointSlices, then we will sync the change of EndpointSlices to the derived servcie.

But if users change ports of the original service and the derived service couldn't be synced at the sametime, then the derived service will lose its meaning(I think).  Or in your design, the derived service is only used as a tool to sync EndpointSlices? But does this conform to the original semantics of MCS?

**Comment by lonelyCZ** [comment]
> But if users change ports of the original service and the derived service couldn't be synced at the sametime, then the derived service will lose its meaning(I think). 

Yes, I encountered this problem.

As [web example](https://github.com/karmada-io/karmada/blob/master/docs/multi-cluster-ingress.md#deploy-web-on-member1-cluster), if I change `web` service port to 82, the port of `derived-web` service is not changed,  and modify the `MCI` alone is not enough, I need to manually change the `derived-web` service.

**Comment by XiShanYongYe-Chang** [comment]
> As [web example](https://github.com/karmada-io/karmada/blob/master/docs/multi-cluster-ingress.md#deploy-web-on-member1-cluster), if I change `web` service port to 82, the port of `derived-web` service is not changed,

Why not change the `ServiceImport.ports`?

**Comment by lonelyCZ** [comment]
> Why not change the ServiceImport.ports?

It makes sense. We need to keep `serviceimport` apply to `service` manually.

**Comment by XiShanYongYe-Chang** [comment]
> It makes sense. We need to keep `serviceimport` apply to `service` manually.

Yes, it's like this.

**Comment by XiShanYongYe-Chang** [comment]
> But if users change ports of the original service and the derived service couldn't be synced at the sametime, then the derived service will lose its meaning(I think). 

Just as I mentioned above, we can update related `serviceimport` to sync derived service.

> Or in your design, the derived service is only used as a tool to sync EndpointSlices? 

We can get the EndpointSlices through the derived service. EndpointSlices will be synced by `service-export-controller` and `endpointslice-controller` if we updated the original service.

> But does this conform to the original semantics of MCS?

Can you help specify which point it is? We can have a discussion together.

**Comment by 1285yvonne** [comment]
refer: https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#importing-services

> Because of the potential wide impact a ServiceImport may have within a cluster, non-cluster-admin users should not be allowed to create or modify ServiceImport resources. The mcs-controller should be solely responsible for the lifecycle of a ServiceImport.

> For each exported service, one ServiceExport will exist in each cluster that exports the service. The mcs-controller will create and maintain a derived ServiceImport in each cluster within the clusterset so long as the service's namespace exists (see: [constraints and conflict resolution](https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#constraints-and-conflict-resolution)). If all ServiceExport instances are deleted, each ServiceImport will also be deleted from all clusters.

It seems that the mcs-controller is responsible for the lifecycle of a ServiceImport.  So I think maybe the mcs-controller should sync ServiceImport resources rather than normal users?

**Comment by XiShanYongYe-Chang** [comment]
The application of ServiceExport and ServiceImport has added meaning. ServiceExports are used to specify the clusters from which services are to be exported and ServiceImports are used to specify the clusters to which services are to be imported.

In addition, the service's port information exported from different clusters may be different. As a result, we cannot determine which service is the basis for synchronization.

**Comment by 1285yvonne** [comment]
refer: https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster/1645-multi-cluster-services-api#constraints-and-conflict-resolution

![image](https://user-images.githubusercontent.com/15215212/175231322-a1d1075f-3da3-41d2-9242-67f201d5a8f9.png)

It looks like there is a consensus in the community on conflicts and constraints, but I understand the complexity you think about implementing it. So is it possiable for you to handle this situation, synchronizing the ServiceImport resource via karmada mcs-controller

**Comment by XiShanYongYe-Chang** [comment]
Implementation complexity is a secondary factor, mainly because the benefits brought by doing so are not high. 

The connection point of the derived service and the original service is the same as their backend. When the port information of the original service is changed, the existing derived service can still work normally.

**Comment by Alphonse-iwnl** [comment]
closing the issue if u thought it keep low priority
