### ISSUE TITLE
how to use argoCD and karmada to deploy `chart` project on multis-cloud env

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#1999]
**Please provide an in-depth description of the question you have**:

If we use `argoCD` and `karmada` to deploy chart project on multis-cloud env, how do we create the policy resources?  e.g: `OP` and `PP`.

* Do we define the resources （OP & PP） in the Chart package？
* Or create them separately in the cluster?

Is there a best practice in our community？thanks for helping me to solve the issue 🙏

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
I don't know if argoCD has a similar feature like [flux](https://github.com/karmada-io/karmada/blob/master/docs/working-with-flux.md).

If not, 
> Do we define the resources （OP & PP） in the Chart package？

Might help, but I'm not sure. In this approach, you have to unzip the chart and deploy the yamls to karmda-apiserver.

**Comment by calvin0327** [comment]
There are some diffrent on them:
* Flux need deploy server on every cluster and deploy itself crd on karmada controller cluster. karmada only propogate flux cr `HelmRepository` and `HelmRelease `
* Argocd use karmada cluster as the only entrance, all of resource in the chart be propogated by karmada. (I'm not sure it's right to do in the approach)

If in this way, I need define all of resource of chart in PropogatePolicy and OveridePolicy. if there are 100 resource in chart, it's difficult to do it.

**Comment by RainbowMango** [comment]
> If in this way, I need define all of resource of chart in PropogatePolicy and OveridePolicy. if there are 100 resource in chart, it's difficult to do it.

yes, but usually not so many resources in a chart I guess.  I don't know much about charts, is there possible to generate the PP and OP automatically, not by manual? such as a job?

**Comment by calvin0327** [comment]
Today, I try to use ArgoCD in combination with Flux to deploy helm, It's seem to work. deploy helm-operator on every member cluster and use karmada to propagate `HelmRelease` cr to every member cluster trigger by ArgoCD.

**Comment by calvin0327** [comment]
> > If in this way, I need define all of resource of chart in PropogatePolicy and OveridePolicy. if there are 100 resource in chart, it's difficult to do it.
> 
> yes, but usually not so many resources in a chart I guess. I don't know much about charts, is there possible to generate the PP and OP automatically, not by manual? such as a job?

The approach like a good idea, we have already have the tool to generate the PP and OP or need implemente myself? 😄

**Comment by calvin0327** [comment]
@RainbowMango I have tested using flux, karmada and argocd to distribute chart. Close this issue for the time being.
