### ISSUE TITLE
Enlarge timeout setting of golangci-lint

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2009]
**Task description**:
The golangci-lint timeout several times, the latest one at:
https://github.com/karmada-io/karmada/runs/6860875119?check_suite_focus=true#step:5:125

**Solution**:

Just enlarge the timeout option, as the capacity of GitHub Action runner is pretty small, that's the reason it runs longer than normal machines. Such as:
```
diff --git a/.golangci.yml b/.golangci.yml
index 1429db2c..d6dd01fe 100644
--- a/.golangci.yml            
+++ b/.golangci.yml            
@@ -3,7 +3,7 @@                

 run:
   # timeout for analysis, e.g. 30s, 5m, default is 1m
-  timeout: 5m
+  timeout: 10m
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by wuyingjun-lucky** [comment]
some questions : 
karmada linters do not contains gci
I try to use `golangci-lint run` with gci and found some imports can be improved like https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/karmadactl.go#:~:text=%22flag%22,pkg/version/sharedcommand%22

**Comment by RainbowMango** [comment]
@wuyingjun-lucky Does gci is a linter?

**Comment by wuyingjun-lucky** [comment]
> golangci-lint

Yes 

https://golangci-lint.run/usage/linters/#:~:text=v1.18.0-,gci%C2%A0%E2%9A%99%EF%B8%8F,-Gci%20controls%20golang

https://github.com/daixiang0/gci#examples

**Comment by XiShanYongYe-Chang** [comment]
We have `golangci-lint` in `hack/verify-staticcheck.sh`.

**Comment by RainbowMango** [comment]
I get it. I'll look at it.

**Comment by hanweisen** [comment]
Is it possible to make a base image that already contains the packages that `golangci-lint` depends on.
In our environment lint often times out. I solved it by this method. we can reduce lint time from 4 minutes to 1 minutes

**Comment by RainbowMango** [comment]
> Is it possible to make a base image that already contains the packages that golangci-lint depends on.

Maybe we can consider this approach if the image maintains by golangci-lint community, but I don't want to maintain that.

By the way, for now, we install the golangci-lint by `go install` that will load the packages, another idea is just to download the binary(If not exist), which will help I guess.

**Comment by hanweisen** [comment]
They already maintains image golangci/golangci-lint:v1.46.2
They don't suggest using go install.
![image](https://user-images.githubusercontent.com/14215449/174209588-0c4569d0-e231-4d6e-a538-8ccae32b2da3.png)

**Comment by RainbowMango** [comment]
The image size is about `500M`, larger than the binary (about ~40M), I tend to the binary. 
```
golangci/golangci-lint                                                                           v1.42.1-alpine         02077ed43ef9   9 months ago   539MB
```

**Comment by RainbowMango** [comment]
@cutezhangq 
Are you ready to send the PR now?
We met another failure at #2029 
https://github.com/karmada-io/karmada/runs/6959540342?check_suite_focus=true

Just a reminder, this issue just tracks the `timeout` setting, I hope to fix it as soon as possible.

**Comment by AllenZMC** [comment]
Can I help do it quickly, @cutezhangq  doesn't seem to have time for it right now.

**Comment by RainbowMango** [comment]
sounds good to me if @cutezhangq ok with it.

**Comment by cutezhangq** [comment]
OK, I'm still familiar with the project and can't fix it soon. @AllenZMC @RainbowMango

**Comment by cutezhangq** [comment]
I will learn from @AllenZMC , get familiar with the project as soon as possible and complete the repair of other problems.
