### ISSUE TITLE
The package imports can be improved in pkg/karmadactl/karmadactl.go

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2025]
**Task description**:
The package imports can be improved in [pkg/karmadactl/karmadactl.go ](https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/karmadactl.go#:~:text=import%20(,))

We organize the import package in three parts:
`go package

third-party package

current project package`

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by wuyingjun-lucky** [comment]
@RainbowMango @lonelyCZ can this issue set up by good first issue label

**Comment by RainbowMango** [comment]
@wuyingjun-lucky Sure! Many thanks.

**Comment by wuyingjun-lucky** [comment]
/close
As [https://github.com/karmada-io/karmada/pull/2038](2038) is merged
