### ISSUE TITLE
E2E run faild for member cluster not ready

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#2057]
#### Which jobs are flaking:

E2E test

#### Which test(s) are flaking:

https://github.com/karmada-io/karmada/runs/7035097848?check_suite_focus=true

Error log info:

```log
/home/runner/work/karmada/karmada/test/e2e/suite_test.go:95
Unexpected error:
      <*errors.errorString | 0xc0002ebf70>: {
          s: "cluster member1 not ready",
      }
      cluster member1 not ready
  occurred
In [SynchronizedBeforeSuite] at: /home/runner/work/karmada/karmada/test/e2e/framework/cluster.go:[60](https://github.com/karmada-io/karmada/runs/7035097848?check_suite_focus=true#step:5:61)
Full Stack Trace
    github.com/karmada-io/karmada/test/e2e/framework.InitClusterInformation({0x3d31968, 0xc0001d5340}, {0x3d34258, 0xc00045f490})
    	/home/runner/work/karmada/karmada/test/e2e/framework/cluster.go:60 +0x26c
    github.com/karmada-io/karmada/test/e2e.glob..func25({0xc00012b[68](https://github.com/karmada-io/karmada/runs/7035097848?check_suite_focus=true#step:5:69)0?, 0xc000435438?, 0xc000435498?})
    	/home/runner/work/karmada/karmada/test/e2e/suite_test.go:119 +0x5cf
```

#### Reason for failure:

As comment in https://github.com/karmada-io/karmada/pull/2056#issuecomment-1165159263

**Comment by XiShanYongYe-Chang** [comment]
We can consider to check the Cluster status in `hack/local-up-karmada.sh` or `hack/run-e2e.sh`.

/kind help

**Comment by calvin0327** [comment]
/assign

@XiShanYongYe-Chang I'm going to call `wait_pod_ready` in `post-run-e2e.sh` to check the status of k`ube-apiserver `pod. what do you think?

**Comment by RainbowMango** [comment]
I guess the `post-run-e2e.sh` doing the cleanup stuff `after` E2E, I think what @XiShanYongYe-Chang wants to do is ensure the testing cluster is ready for run E2E.

**Comment by calvin0327** [comment]
I'm wrong, I mean `pre-run-e2e`, there are three position on files `pre-run-e2e`，`run-e2e` and `local-up-karmada.sh`, which is better position to do it?

**Comment by XiShanYongYe-Chang** [comment]
@calvin0327 thanks! I agree to add checkout in the `pre-run-e2e.sh` to ensure the testing cluster is ready.

**Comment by RainbowMango** [comment]
wait, seems cluster still can't get available when the `hack/local-up-karmada.sh` exits, do you know why? How long it will take?

Since the `hack/local-up-karmada.sh` has been heavily used probably  by new users, they might meet this issue as well, how can we avoid it?

**Comment by XiShanYongYe-Chang** [comment]
> wait, seems cluster still can't get available when the `hack/local-up-karmada.sh` exits, do you know why?

We did not wait for the cluster to be ready after we joined the cluster, so theoretically this could happen.

> How long it will take?

There is no specific data at this time, depending on how quickly the `cluster-controller` collects the cluster status, which is low in terms of the current CI operation.

Maybe we could consider adding this wait to the `hack/local-up-karmada.sh` script.

**Comment by RainbowMango** [comment]
> Maybe we could consider adding this wait to the hack/local-up-karmada.sh script.

+1

**Comment by calvin0327** [comment]
> Since the `hack/local-up-karmada.sh` has been heavily used probably by new users

In this respect. I agree with you. 

+1

**Comment by calvin0327** [comment]
@RainbowMango I seem to have not found the issue of adding cluster ID mentioned last time? 😅

**Comment by XiShanYongYe-Chang** [comment]
> I seem to have not found the issue of adding cluster ID mentioned last time?

@calvin0327, This proposal @2017 related work.

**Comment by RainbowMango** [comment]
Yes, cluster ID is now in progress of proposal. 
Please help review it.
