### ISSUE TITLE
shoudn't switch context when deploy or update karmada

### ISSUE THREAD

**Issue by wangyanzhao** [karmada-io/karmada#2059]
**What would you like to be added**:
should replace `kubectl config use-context "${CONTEXT}"` with `kubectl --context="${CONTEXT}"` .

**Why is this needed**:
1. if deploy failed, it can't ensure context switch to "HOST_CLUSTER".
2. when deploy karmada, if other operations engineer switch context, karmada will failed too.

**Comment by RainbowMango** [comment]
Which piece of code we are talking about here? Can you give a link?

**Comment by wangyanzhao** [comment]
such as:

https://github.com/karmada-io/karmada/blob/master/hack/deploy-karmada.sh#L216

https://github.com/karmada-io/karmada/blob/master/hack/remote-up-karmada.sh#L34

**Comment by RainbowMango** [comment]
Yeah, thanks. Basically, I agree with your opinion. 
Would you like to send a PR?

**Comment by XiShanYongYe-Chang** [comment]
Hi @wangyanzhao, would you like to fix it? Or mark it as a help label so that someone else can help do it?

**Comment by wangyanzhao** [comment]
OK, I will fix it.

**Comment by XiShanYongYe-Chang** [comment]
Thanks~

/assign @wangyanzhao
