### ISSUE TITLE
Why does Built-in Interpreter AggregateStatus not contain PVC

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2065]
**Please provide an in-depth description of the question you have**:

Why does Built-in Interpreter AggregateStatus not contain PVC

**What do you think about this question?**:
When I config  a pod to use a PersistentVolumeClaim for storage , I found that the PersistentVolumeClaim status in karmada was always "Pending".

![image](https://user-images.githubusercontent.com/17962021/175930442-69a4cf94-10f1-4af3-8828-fb7d386a869a.png)

PVC used frequently. I think that build-in interpreter aggregatestatus should contain PVC

**Environment**:
- Karmada version: master 
- Kubernetes version: 1.23
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaunceyjiang, we haven't added PVC yet, if you have a plan, you can bring it up and we can discuss it together.

**Comment by chaunceyjiang** [comment]
I want to install [clusterpedia](https://github.com/clusterpedia-io/clusterpedia) in Karmada. It can be seen from the [clusterpedia](https://github.com/clusterpedia-io/clusterpedia) to [the documentation](https://clusterpedia.io/docs/installation/kubectl-apply/#install) that installing [clusterpedia](https://github.com/clusterpedia-io/clusterpedia) requires installing `PV` and `PVC`. When I deploy [clusterpedia](https://github.com/clusterpedia-io/clusterpedia) to Karmada. I find that PVC is always pending in karmada .
