### ISSUE TITLE
Plans for GitOps support

### ISSUE THREAD

**Issue by eedorenko** [karmada-io/karmada#2068]
Plans for [2021 Q4](https://karmada.io/docs/roadmap#2021-q4) include GitOps support. What exactly is planned for this support? 

There are samples of [propagation of Flux resources with Karmada](https://github.com/karmada-io/karmada/blob/master/docs/working-with-flux.md) and [delivering resources to Karmada API server with ArgoCD](https://github.com/karmada-io/karmada/blob/master/docs/working-with-argocd.md), but is there anything else to be implemented in Karmada itself?

**Comment by liangyuanpeng** [comment]
> but is there anything else to be implemented in Karmada itself?

As far as i know,karmada have not implement anything for gitops.

/cc @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
