### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#2079]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:
pr: https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Acalvin0327+is%3Aclosed
issue: https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3A%40me+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by XiShanYongYe-Chang** [comment]
+1

**Comment by kevin-wangzefeng** [comment]
Welcome onboard! Please visit https://github.com/karmada-io to accept the invitation.

**Comment by calvin0327** [comment]
@kevin-wangzefeng Done, thanks.

**Comment by RainbowMango** [comment]
Welcome!
/close
