### ISSUE TITLE
How to propagate a resource with webhook?

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2104]
**Please provide an in-depth description of the question you have**:

I want to propagate [cert-manager](https://github.com/cert-manager/cert-manager) to the member cluster through karmada.

I have successfully installed `cert-manager`

 When I create a `Certificate` CR, I get the following error.

``` shell
# cat cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: guestbook-serving-cert
  namespace: default
spec:
  dnsNames:
  - guestbook-webhook-service.guestbook-system.svc
  - guestbook-webhook-service.guestbook-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: guestbook-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: guestbook-selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}

# export KUBECONFIG=~/.kube/karmada.config
# k apply -f cert.yaml 

Error from server (InternalError): error when creating "cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
Error from server (InternalError): error when creating "cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded

```

**What do you think about this question?**:

Karmada apiserver will not deploy a real  pod, so how to propagate a resource with webhook?

**Environment**:
- Karmada version: matser 
- Kubernetes version: 1.23
- Others:

**Comment by lonelyCZ** [comment]
You can deploy `cert-manager` in `karmada-host` cluster, `karmada-apiserver` is used to propagate resource. You can collect `cert-manager` crd to `karmada-apiserver` and then create `PropagationPolicy` to propagate resource to member clusters that has installed `cert-manager`.

> Karmada apiserver will not deploy a real pod, so how to propagate a resource with webhook?

What is a resource with webhook? I guess the usage step is that create a certificate and then propagate it by `PropagationPolicy`, it doesn't call webhook in karmada-control-plane.
