### ISSUE TITLE
Request to be a Member of Karmada

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#2107]
I'm requesting to be a Member of Karmada.

Recently，I started to participate in the development of the community and submit some issues and prs.  
I will use karmada in production environment. We have found some bugs and performance problems and i will keep up with the community.

PRs：
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Alikakuli+

issues:
https://github.com/karmada-io/karmada/issues?q=+is%3Aissue+author%3Alikakuli+

Hope bring more improvements for Karmada in the future.

**Comment by likakuli** [comment]
@RainbowMango thx

**Comment by RainbowMango** [comment]
Thanks @likakuli 
+1

/assign @kevin-wangzefeng 

@likakuli and his team give us a lot of valuable performance and functionality feedback based on their adoption testing.

**Comment by kevin-wangzefeng** [comment]
+1, looking foward to more of your contributions ;-)
The invitation should arrive via email shortly, you can also visit https://github.com/karmada-io to accept the invitation.
