### ISSUE TITLE
the kube controller manager of karmada keep restarting after installed the master helm chart due to liveness probe

### ISSUE THREAD

**Issue by brucexyz1234** [karmada-io/karmada#2110]
**What happened**:
the kube controller manager of karmada keep restarting after installed the master chart due to liveness probe
**What you expected to happen**:
should not keep restating
**How to reproduce it (as minimally and precisely as possible)**:
install the master helm chart 
**Anything else we need to know?**:
try it
**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by calvin0327** [comment]
Is there some message with the kube-controller livenessProbe?

**Comment by calvin0327** [comment]
@brucexyz1234 can you support more message about the issue?

**Comment by brucexyz1234** [comment]
![image](https://user-images.githubusercontent.com/26198722/177071046-aaa09435-8318-4baa-bce0-049a46c2e21a.png)

**Comment by brucexyz1234** [comment]
![image](https://user-images.githubusercontent.com/26198722/177071207-54306d63-3bf6-4b50-bbd3-32faa15a48bb.png)

**Comment by brucexyz1234** [comment]
@calvin0327 
fyi

**Comment by brucexyz1234** [comment]
----     ------        ----                    ----                  -------
  Warning  Unhealthy     24m (x4251 over 35h)    kubelet, xxx  Liveness probe failed: Get "https://127.0.0.1:10257/healthz": dial tcp 127.0.0.1:10257: connect: connection refused
  Normal   Pulled        9m29s (x538 over 35h)   kubelet, xxx Container image "xxxxxxx/kube-controller-manager:v1.22.10" already present on machine
  Warning  BackOffStart  4m20s (x6552 over 34h)  kubelet, xxx  the failed container exited with ExitCode: 2

**Comment by brucexyz1234** [comment]
@calvin0327

**Comment by calvin0327** [comment]
I think we should add `Startup probe` work before liveness probe.

**Comment by calvin0327** [comment]
It maybe kube controller manager server is not running really and the liveness probe start worl already.

**Comment by calvin0327** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/45745657/177084621-2367a211-0585-4bb0-a1f4-845689e4a38c.png">

Restart 2 time and running normal.

**Comment by Poor12** [comment]
Hello,  I wonder if kube-controller-manager just restarts serveral times finally start or it will never start successfully.

**Comment by calvin0327** [comment]
@brucexyz1234 Did the kubelet report any error message?

**Comment by mrequena** [comment]
Sorry I commented the #2277 and I guess my comment should be here...

Hi, what is the status of this issue?

I have the same issue "kube controller manager restart all the time" with karmada version v1.3.0 and v1.3.1.
My deployments (simple nginx webserver deployments) take a lot of time to be deployed/undeployed (around 5-6 min).

To try to debug/fix the issue, I add manually "--secure-port=10257" to files "artifacts/deploy/kube-controller-manager.yaml" and "charts/karmada/templates/kube-controller-manager.yaml" before the installation of karmada with hack/remote-up-karmada.sh but the issue persists.

But if I remove the loopback address 127.0.0.1 from livenessProbe: httpGet: host: (in file "artifacts/deploy/kube-controller-manager.yaml") , then the issue (Restarts + CrashLoopBackOff status) seems to dissapear (no more restarts nor CrashLoopBackOff of karmada-kube-controller-manager)

**Comment by XiShanYongYe-Chang** [comment]
The related pr has been merged.
/close
