### ISSUE TITLE
Failed to use local-up-karmada.sh to setup Karmada on Mac when set ChinaMainland

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#2114]
**Task description**:
When use local-up-karmada.sh to setup Karmada on Mac, if use ChinaMainland, it will run some scripts to override default images. 
```
  for dockerfile in "${dockerfile_list[@]}"; do
    grep 'mirrors.ustc.edu.cn' ${repo_root}/${dockerfile} > /dev/null || sed -i'' -e "s#FROM alpine:3.15.1#FROM alpine:3.15.1\nRUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.15/main/ > /etc/apk/repositories#" ${repo_root}/${dockerfile}
  done
```
However, macos do not use \n to line feed. So it will like below:
<img width="1231" alt="截屏2022-07-03 下午9 52 37" src="https://user-images.githubusercontent.com/26862112/177042903-75b97e64-39c2-435c-a7b4-cad5332ecb0f.png">
 So build image failed.

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by ikaven1024** [comment]
What's your mac version? It works well on my side: MacOS 11 & 12

**Comment by Poor12** [comment]
> @Poor12 What's your mac version? It works well on my side: MacOS 11 & 12

10.15.7. Catalina.
