### ISSUE TITLE
Why karmada-search use genericoptions.NewRecommendedOptions 

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2116]
**Please provide an in-depth description of the question you have**:
Why karmada-search use genericoptions.NewRecommendedOptions  (ETCD options)
It seems karmada-search will work fine while the etcd-servers use wrong address and the karmada-search seems not directly use ectd. The backend store is not ectd yet .

**What do you think about this question?**:
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/16109961/177046498-3c59c1fd-5efc-4916-b688-55bf478667c2.png">

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by calvin0327** [comment]
As `genericoptions.NewRecommendedOptions` is very useful option help us to build karmada-search cmd. 
Indeed, etcd is not in use now, I don't know if it will be used in the future？

**Comment by wuyingjun-lucky** [comment]
> As `genericoptions.NewRecommendedOptions` is very useful option help us to build karmada-search cmd. Indeed, etcd is not in use now, I don't know if it will be used in the future？

It seems karmada-search will not use etcd and opensearch is the backend store

**Comment by calvin0327** [comment]
```golang
func NewOptions() *Options {
	o := &Options{
		RecommendedOptions: genericoptions.NewRecommendedOptions(
			defaultEtcdPathPrefix,
			searchscheme.Codecs.LegacyCodec(searchv1alpha1.SchemeGroupVersion)),
	}
	...
}
```

This place can be modified, Look at other member's opinions?

**Comment by wuyingjun-lucky** [comment]
> ```go
> func NewOptions() *Options {
> 	o := &Options{
> 		RecommendedOptions: genericoptions.NewRecommendedOptions(
> 			defaultEtcdPathPrefix,
> 			searchscheme.Codecs.LegacyCodec(searchv1alpha1.SchemeGroupVersion)),
> 	}
> 	...
> }
> ```
> 
> This place can be modified, Look at other member's opinions?

Yes I  hope we can remove  the  etcd options

**Comment by XiShanYongYe-Chang** [comment]
@wuyingjun-lucky @calvin0327 Thanks~ If there are any problems or bad coding, you can send a pr to optimize them, 👍

**Comment by wuyingjun-lucky** [comment]
/close 
for introducing cache
