### ISSUE TITLE
why e2e test (v1.24.0) test failure

### ISSUE THREAD

**Issue by hanweisen** [karmada-io/karmada#2119]
**Please provide an in-depth description of the question you have**:
my e2e test in  e2e test (v1.24.0) failure, the reason is
```
      <*errors.StatusError | 0xc0000ca460>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "the server could not find the requested resource (get clusters.cluster.karmada.io)",
              Reason: "NotFound",
              Details: {
                  Name: "",
                  Group: "cluster.karmada.io",
                  Kind: "clusters",
                  UID: "",
                  Causes: [
                      {
                          Type: "UnexpectedServerResponse",
                          Message: "404 page not found",
                          Field: "",
                      },
                  ],
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
      the server could not find the requested resource (get clusters.cluster.karmada.io)
```
referring: https://github.com/karmada-io/karmada/runs/7172926157?check_suite_focus=true

**What do you think about this question?**:
I think this failure is not caused by my PR #2118. Can anyone help with it?
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/runs/7169278909?check_suite_focus=true#step:5:81
I had a similar problem.

**Comment by chaunceyjiang** [comment]
Have you rebase the master branch?
refer to https://github.com/karmada-io/karmada/pull/2095

**Comment by hanweisen** [comment]
I remember I rebase before submitting. Let me try it again

**Comment by hanweisen** [comment]
I forget to fetch  before rebase

**Comment by wuyingjun-lucky** [comment]
Could karmada-bot add a command like `/retest` by the pull request authors ? @RainbowMango

**Comment by RainbowMango** [comment]
> Could karmada-bot add a command like /retest by the pull request authors ?

I don't know how to do it. The test is triggered by GitHub Action but not karmada-bot.

**Comment by hanweisen** [comment]
> Have you rebase the master branch? refer to #2095

That works, thanks @chaunceyjiang
