### ISSUE TITLE
Why is the short usage of cluster parameters lowercase in karmadactl promote different from other modules

### ISSUE THREAD

**Issue by Fish-pro** [karmada-io/karmada#2131]
**Please provide an in-depth description of the question you have**:
When using the karmadactl promote command, the cluster parameter is shortened to -c, but other modules are -C. Why is there such a difference?
`karmadactl promote -h`
```
Examples:

# Support to use '--cluster-kubeconfig' and '--cluster-context' to specify the configuration of member cluster
karmadactl promote deployment nginx -n default -c cluster1 --cluster-kubeconfig=<CLUSTER_KUBECONFIG_PATH> --cluster-context=<CLUSTER_CONTEXT>

Flags:
  -c, --cluster string              the name of legacy cluster (eg -c=member1)
      --cluster-context string      Context name of legacy cluster in kubeconfig. Only works when there are multiple contexts in the kubeconfig.
```
`karmadactl get -h`
```
Examples:

# List all pods of member1 cluster in ps output format
karmadactl get pods -C member1

Flags:
  -C, --clusters strings              -C=member1,member2
```

**What do you think about this question?**:
Because of the container operation -c?
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by lonelyCZ** [comment]
It was designed separately, but I think we can unify it now. Would you like to file a pr to improve it? @Fish-pro

**Comment by Fish-pro** [comment]
> It was designed separately, but I think we can unify it now. Would you like to file a pr to improve it? @Fish-pro

@lonelyCZ Thanks for the answer, I will submit a PR to unify it later
