### ISSUE TITLE
describe pod status error

### ISSUE THREAD

**Issue by weichenhao** [karmada-io/karmada#2137]
kubectl get pods
![image](https://user-images.githubusercontent.com/34300622/177448523-4387894c-a209-4d2c-baff-5bb46c6e6053.png)
kubectl describe pod breeding-10001
![image](https://user-images.githubusercontent.com/34300622/177448633-6e7bf2b0-b2fb-4834-a768-f8ea0c0e98b2.png)
karmadactl describe pod breeding-10001 -C=cluster2
![image](https://user-images.githubusercontent.com/34300622/177448805-e18055d2-32b6-4da9-9594-ad43fc58ea60.png)
command：kubectl describe pod breeding-10001 shows status error when pod exec Succeeded.

**Comment by chaunceyjiang** [comment]
Can you paste your pod yaml file?

**Comment by weichenhao** [comment]
pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: breeding-10001
  namespace: default
spec:
  containers:
  - command:
    - bash
    - /workspace/CSRNet/breeding.sh
    - /workspace/CSRNet
    - /workspace/datas
    - /workspace/datas/breeding-10001
    - '2'
    image: hjj-image:v2
    imagePullPolicy: IfNotPresent
    name: breeding-100018582
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /workspace/datas
      name: vol-data
    - mountPath: /workspace/CSRNet
      name: vol-alg
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /mnt/nas/breeding/datas
      type: DirectoryOrCreate
    name: vol-data
  - hostPath:
      path: /mnt/nas/breeding/CSRNet
      type: DirectoryOrCreate
    name: vol-alg

policy.yaml

apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: propagation-breeding-10001
spec:
  placement:
    clusterAffinity: &id004
      clusterNames:
      - cluster2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
        - targetCluster: *id004
          weight: 1
  resourceSelectors:
  - apiVersion: v1
    kind: Pod
    name: breeding-10001

**Comment by lonelyCZ** [comment]
We don't seem to have an aggreagte pod status. It is recommended to use workload(like `Deployment`) to distribute applications. 
Do you have any requirements that require you to distribute pods directly?

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/db4fdc14740b8729d7759d030657e003b778e443/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go#L310-L313
Because we have no aggregated `Succeeded`  status
I think we should also aggregate the pod `Succeeded`and `Failed` status.

|  The Pod Status of ClusterN | The Pod Status of ClusterM  | Aggregate Priority | AggregatePodStatus |
|  ----  | ----  | ----  | ----  |
|  Failed | Pending or  Running or Succeeded  or Failed | 1 | Failed |
| Pending  | Pending or  Running or Succeeded  |2 |Pending |
| Running  |  Running or Succeeded  |3 |Running |
| Succeeded  | Succeeded |4 |Succeeded |

**Comment by weichenhao** [comment]
Yes，you should aggregate status whatever pod has，otherwise it will be inconsistent.

**Comment by weichenhao** [comment]
thx, please tell me when you fixed it.

**Comment by XiShanYongYe-Chang** [comment]
Hi @weichenhao, the fixed pr has been merged, you can have a retry.
