### ISSUE TITLE
karmada-search cannot list resource "resourceregistries" in API group

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#2138]
**What happened**:

**What you expected to happen**:
karmada-searche logs:
```
W0706 02:19:54.745435       1 reflector.go:324] pkg/generated/informers/externalversions/factory.go:106: failed to list *v1alpha1.ResourceRegistry: resourceregistries.search.karmada.io is forbidden: User "system:anonymous" cannot list resource "resourceregistries" in API group "search.karmada.io" at the cluster scope
E0706 02:19:54.745500       1 reflector.go:138] pkg/generated/informers/externalversions/factory.go:106: Failed to watch *v1alpha1.ResourceRegistry: failed to list *v1alpha1.ResourceRegistry: resourceregistries.search.karmada.io is forbidden: User "system:anonymous" cannot list resource "resourceregistries" in API group "search.karmada.io" at the cluster scope
I0706 02:19:54.814904       1 shared_informer.go:262] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0706 02:19:54.814938       1 shared_informer.go:262] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0706 02:19:54.814964       1 shared_informer.go:262] Caches are synced for RequestHeaderAuthRequestController
I0706 02:19:56.016560       1 controller.go:170] Cluster member3 is not registered
I0706 02:19:56.016610       1 controller.go:170] Cluster member4 is not registered
```
Also did not find the ResourceRegistry resource
![image](https://user-images.githubusercontent.com/31637804/177461749-d2b25de3-55c3-405f-9d5c-280e53d23623.png)

**Anything else we need to know?**:
karmada-search startup parameters：
![8905560cfa6edbadad720c7c3e5daba](https://user-images.githubusercontent.com/31637804/177462096-84704404-580b-49ad-9dc1-92ffbb60acbd.png)

**Environment**:
- Karmada version: v1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):v1.2.0
- Others:

**Comment by XiShanYongYe-Chang** [comment]
`karmada-search` is an optional component.

The secret name `karmada-cert` in cmd init is different from the secret name `karmada-cert-secret` in `artifacts/deploy/karmada-cert-secret.yaml`, when deploying `karmada-search`, we need to change the corresponding value name.

**Comment by luoMonkeyKing** [comment]
> secret name

Ok, but I don't think it's the secret name, because the search component and karmada-apiserver use the same secret, and the current error is that there is no permission to collect the data of the member cluster

**Comment by luoMonkeyKing** [comment]
The reason for the problem was found, because I didn't create the cr ResourceRegistry, sorry！
I feel that the above error is sometimes misleading.

**Comment by XiShanYongYe-Chang** [comment]
Thanks!

/close
