### ISSUE TITLE
When are ResourceBindings created？

### ISSUE THREAD

**Issue by AllenZMC** [karmada-io/karmada#2149]
**Please provide an in-depth description of the question you have**:
When are ResourceBindings created ?  Where is the created process in the code? And where is the code for Policy Controller?

**What do you think about this question?**:

**Comment by XiShanYongYe-Chang** [comment]
I'm sorry, I didn't quite understand your meaning. During scheduling, ResourceBindings will not be created.

**Comment by AllenZMC** [comment]
@XiShanYongYe-Chang  Sorry, maybe my description is not clear, what I want to express is where the `ResourceBindings` will be created?

**Comment by XiShanYongYe-Chang** [comment]
ok, we will create rb in detector: pkg/detector/detector.go:432

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/18515424c2491fbd9982f8460d15a36585987e10/pkg/detector/detector.go#L640-L643

**Comment by AllenZMC** [comment]
@XiShanYongYe-Chang  `Policy Controller: the controller watches PropagationPolicy objects. When the PropagationPolicy object is added, it selects a group of resources matching the resourceSelector and creates ResourceBinding with each single resource object.`  Is the `policy controller` in this description just a general reference? I don't see the corresponding processing code in the controller manager, can you tell me where the controller is?

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/18515424c2491fbd9982f8460d15a36585987e10/pkg/detector/detector.go#L90-L107

https://github.com/karmada-io/karmada/blob/18515424c2491fbd9982f8460d15a36585987e10/pkg/detector/detector.go#L131-L137

**Comment by XiShanYongYe-Chang** [comment]
Currently, there is no dedicated `policy controller`. Its processing logic is also in the detector. We add an independent event handler to the policy for processing:

https://github.com/karmada-io/karmada/blob/6adce059d6b198eb099a81a8fc43bdfc1084b567/pkg/detector/detector.go#L95-L109

**Comment by AllenZMC** [comment]
> Currently, there is no dedicated `policy controller`. Its processing logic is also in the detector. We add an independent event handler to the policy for processing:


Is it necessary to update the description of this controller in the homepage documentation?

**Comment by RainbowMango** [comment]
I don't think so. The detector is essentially a controller because it works in a controller style.

**Comment by AllenZMC** [comment]
> I don't think so. The detector is essentially a controller because it works in a controller style.

OK.
