### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by Fish-pro** [karmada-io/karmada#2151]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit PRs 7+

See:
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3AFish-pro+is%3Aclosed

Hope bring more improvements for Karmada in the future.

/cc @kevin-wangzefeng @RainbowMango

**Comment by RainbowMango** [comment]
+1
/assign @kevin-wangzefeng

**Comment by kevin-wangzefeng** [comment]
+1
Please visit https://github.com/karmada-io to accept the invitation
