### ISSUE TITLE
Propagate dependencies support adding by annotation 

### ISSUE THREAD

**Issue by mathlsj** [karmada-io/karmada#2154]
**What would you like to be added**:

Propagate dependencies support adding by annotation 

**Why is this needed**:

service dependent deployment.  both of them are linked by pod lable, but themselves are not directly linked. so it  is dependent by annotaion, controlled by the user

**Comment by mathlsj** [comment]
``` yaml
 resourceTemplateDependenciesAnnotationKey represents the key of dependencies data (json serialized)
// in the annotations of an independent resource.
resourceTemplateDependenciesAnnotationKey = "resourcetemplate.karmada.io/dependencies"

func getDependFromAnnotation(annotations map[string]string, namespace string) ([]configv1alpha1.DependentObjectReference, error) {
    dependencies, exist := annotations[resourceTemplateDependenciesAnnotationKey]
    if !exist {
        return nil, nil
    }

    var dependenciesSlice []configv1alpha1.DependentObjectReference
    err := json.Unmarshal([]byte(dependencies), &dependenciesSlice)
    if err != nil {
        return nil, fmt.Errorf("json unmarshal annotation(%v) failed", dependencies)
    }

    // check annotation
    for _, v := range dependenciesSlice {
        if v.APIVersion == "" || v.Name == "" || v.Namespace == "" || v.Kind == "" {
            return nil, fmt.Errorf("annotation dependcies(%+v) is invalid", v)
        }
        if v.Namespace != namespace {
            return nil, fmt.Errorf("annotation dependcies(%+v) namespace is not equal obj namespace:%s", v, namespace)
        }
    }

    return dependenciesSlice, nil
}
```

**Comment by chaunceyjiang** [comment]
So ,which resource should I set the annotation to it?

**Comment by mathlsj** [comment]
> for example: add service to annotation
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1234
  namespace: test
  annotations:
    resourcetemplate.karmada.io/dependencies: '[{"apiVersion": "v1", "kind":"Service", "namespace":"test", "name":"depended-service"}]'
  labels:
    app: nginx1234
```

then the result looks like this（ignore the lable details . in my environment i splite depended labels to three lables):

```shell
[root@]# kubectl --kubeconfig=/root/.kube/karmada.config get rb -n test --show-labels
NAME                       SCHEDULED   FULLYAPPLIED   AGE   LABELS
depended-service-service               True           64m   resourcebinding.karmada.io/depended-by-6996b44b44.kind=deployment,resourcebinding.karmada.io/depended-by-6996b44b44.name=nginx1234,resourcebinding.karmada.io/depended-by-6996b44b44.namespace=test
nginx1234-deployment       True        True           64m   propagationpolicy.karmada.io/name=nginx1234-propagation,propagationpolicy.karmada.io/namespace=test

```

**Comment by renhuaihuai** [comment]
In which version can this capability be used？

**Comment by RainbowMango** [comment]
@mathlsj Thanks for the awesome idea. I like it. 
This probably could be a supplement way for Karmada to find the potential dependencies.

Is it available for you to have a chat at next community meeting?

**Comment by mathlsj** [comment]
@RainbowMango sorry, I've just seen it.

**Comment by mathlsj** [comment]
> @mathlsj Thanks for the awesome idea. I like it. This probably could be a supplement way for Karmada to find the potential dependencies.
> 
> Is it available for you to have a chat at next community meeting?

@RainbowMango sorry, i've just seen it.

**Comment by RainbowMango** [comment]
After going through this discussion again, I think you can use [Resource Interpreter](https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/#resource-interpreter-framework) to get the dependencies by customizing the `InterpretDependency`.

**Comment by mathlsj** [comment]
I am implemented in this way

**Comment by RainbowMango** [comment]
@mathlsj I don't think we are going to do something at Karmada project, I mean if people want to declare dependencies by labels or annotations, they can leverage resource interpreter to do that. 
Are we on the same page?

**Comment by mathlsj** [comment]
你的意思是: 不想加在 karmada 代码里.由用户自己通过 customized(karmada-webhook) 的方式实现?
我的意思是: 通过 built-in interpreter 的通用方式实现.

**Comment by RainbowMango** [comment]
我觉得在built-in里实现时机还不成熟，不确定这是一个通用的诉求，还有比较多的问题没讨论清楚，比如只针对Deployment实现，还是所有资源类型上都要支持？

除此之外，安全方面也是一个不容忽视的考虑因素，如果出现依赖另一个namespace中的资源可能会存在安全风险，比如会把不属于当前ns中的资源做为依赖下发。这也是为什么built-in中关于依赖仅做到ConfigMap，Secret等基础依赖的原因。

**Comment by mathlsj** [comment]
OK， i  get it.
