### ISSUE TITLE
gitTreeState

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#2155]
**Task description**:
When there are files uncommit(i.e. git status is dirty), e.g.
```diff
diff --git a/README.md b/README.md
index c4b12c21..81cc751b 100644
--- a/README.md
+++ b/README.md
@@ -1,3 +1,4 @@
+
 # Karmada
 
 ![Karmada-logo](docs/images/Karmada-logo-horizontal-color.png)
```
While building binary, the `gitTreeState` is  `clean`. It shall be `dirty`.

```shell
$ make karmada-aggregated-apiserver
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-263-gdb4fdc14-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=db4fdc14740b8729d7759d030657e003b778e443 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-08T06:30:09Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmada-aggregated-apiserver
!!! Building karmada-aggregated-apiserver for darwin/arm64:
```

The reason is wrong here.
https://github.com/karmada-io/karmada/blob/821a18542e57ae5ecf5fdc44bd3fa14c586f4a66/hack/util.sh#L616

`$$`  the PID of shell. `$?` shall be used here, indicating the exit code of last command.

**Solution**:
```diff
diff --git a/hack/util.sh b/hack/util.sh
index 86591481..e571d810 100755
--- a/hack/util.sh
+++ b/hack/util.sh
@@ -613,7 +613,7 @@ function util::get_GO_LDFLAGS() {
   GIT_VERSION=$(git describe --tags --dirty)
   GIT_COMMIT_HASH=$(git rev-parse HEAD)
   GIT_TREESTATE="clean"
-  GIT_DIFF=$(git diff --quiet >/dev/null 2>&1; if [[ $$ = 1 ]]; then echo "1"; fi)
+  GIT_DIFF=$(git diff --quiet >/dev/null 2>&1; if [[ $? = 1 ]]; then echo "1"; fi)
   if [[ "${GIT_DIFF}" == "1" ]];then
       GIT_TREESTATE="dirty"
   fi
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
I just tried it on my side, that I modified `README.md` by adding two empty lines:
```diff
diff --git a/README.md b/README.md
index c4b12c21..ef09aaaa 100644
--- a/README.md
+++ b/README.md
@@ -3,6 +3,8 @@
 ![Karmada-logo](docs/images/Karmada-logo-horizontal-color.png)
 
 
+
+

``` 

Then run `make karmada-aggregated-apiserver`, I can see the `gitVersion=v1.2.0-279-g821a1854-dirty`.
```bash
# make karmada-aggregated-apiserver
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-279-g821a1854-dirty -X github.com/karmada-io/karmada/pkg/version.gitCommit=821a18542e57ae5ecf5fdc44bd3fa14c586f4a66 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-08T08:47:42Z' BUILD_PLATFORMS=linux/amd64 hack/build.sh karmada-aggregated-apiserver
```

By the way, I run the test on Linux CentOS.

**Comment by RainbowMango** [comment]
Yeah, got it. 
I guess it was introduced when we move this from `Makefile` to shell. cc @gy95

**Comment by RainbowMango** [comment]
Hi @ihuibin What's the progress now? 
@carlory send a PR and provides another way to solve this issue, are you OK with it?
