### ISSUE TITLE
Not able to deploy outside of default namespace

### ISSUE THREAD

**Issue by steveww** [karmada-io/karmada#2195]
GKE

I run the examples and deploy nginx in the default namespace in my clusters.
I change the namespace for the deployment and service.
The namespace gets created on the cluster bit nothing else.
Lots of these messages in the scheduler logs

W0714 16:12:09.963725       1 clientconn.go:1322] [core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-harry:10352 karmada-scheduler-estimator-harry:10352 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-harry on 10.20.0.10:53: no such host"

What when wrong?

**Comment by prodanlabs** [comment]
```
W0714 16:12:09.963725 1 clientconn.go:1322] [core] grpc: addrConn.createTransport failed to connect to {karmada-scheduler-estimator-harry:10352 karmada-scheduler-estimator-harry:10352 0 }. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup karmada-scheduler-estimator-harry on 10.20.0.10:53: no such host"
```
This error is that `karmada-scheduler-estimator` is not deployed, but it is not a core component of karmada and will not affect the scheduler work, so your error may be caused by other reasons.

**Comment by prodanlabs** [comment]
I remember that karmada has some namespaces reserved, if your namespace is a reserved namespace, that won't work.

Wait for @RainbowMango  to confirm.

**Comment by RainbowMango** [comment]
@steveww Could you please help confirm if you enabled `estimator`? You can check the flag `--enable-scheduler-estimator` in `karmada-scheduler`.

By the way, please tell up which version are you using.

**Comment by RainbowMango** [comment]
> I change the namespace for the deployment and service.

Can you show your PropagationPolicy here? Or, please confirm if you updated it as well.

**Comment by steveww** [comment]
The command line for the scheduler.

/bin/karmada-scheduler --kubeconfig=/etc/kubeconfig --bind-address=0.0.0.0 --secure-port=10351 --feature-gates=Failover=true --enable-scheduler-estimator=true --leader-elect=true --leader-elect-resource-namespace=karmada-system --v=4

karmadactl version: version.Info{GitVersion:"v1.2.1", GitCommit:"de4972b74f848f78a58f9a0f4a4e85f243ba48f8", GitTreeState:"clean", BuildDate:"2022-07-14T09:33:33Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

**Comment by steveww** [comment]
Deployment

---
apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: web
  labels:
    service: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: nginx
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    service: nginx

**Comment by steveww** [comment]
Just tried it all again.
Still no propagation of my deployment to my namespace. However, no errors, nothing.
How do I figure out what it's doing or not doing?
The docs should be updated with some trouble shooting guides.

**Comment by RainbowMango** [comment]
> Looks like as soon as a Namespace is created inside Karmada it get automatically propagated to all members.

Yes, there is a controller named `namespace` which will propagate namespaces to all members. If you don't need it you can disable it, see [this guide](https://github.com/karmada-io/karmada/blob/master/docs/userguide/configure-controllers.md#configure-karmada-controllers)

**Comment by RainbowMango** [comment]
> Still no propagation of my deployment to my namespace. However, no errors, nothing.

I see the Deployment and the Service are in namespace `web`, but the PropagationPolicy declares that it only matches resources from `default` namespace:
```
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default   // this shows it only focus on resources in `default` namespace.
    - apiVersion: v1
      kind: Service
      name: nginx
      namespace: default
```
So, I'm not sure if you can directly update the PropagationPolicy, but you can update by `delete` --> `create`.

**Comment by RainbowMango** [comment]
Thanks @steveww .
/close
