### ISSUE TITLE
To continue doing nothing when propagationPolicy is updated?

### ISSUE THREAD

**Issue by snowplayfire** [karmada-io/karmada#2204]
```
// OnClusterPropagationPolicyUpdate handles object update event and push the object to queue.
func (d *ResourceDetector) OnClusterPropagationPolicyUpdate(oldObj, newObj interface{}) {
	// currently do nothing, since a policy's resource selector can not be updated.
}
```
If policy's weight is updated,  the  `ResourceSelectors` object should be added into reconcile queue rather than do nothing.

**Comment by RainbowMango** [comment]
Here `do nothing` means it won't start to look for matched `resource template`s. Not really `do nothing`.

Am I missed some scenarios? Do you have an example to show the problem?

**Comment by snowplayfire** [comment]
Sorry for my misleading.
