### ISSUE TITLE
working with istio on non flat network when your cluster don't have LB

### ISSUE THREAD

**Issue by suwliang3** [karmada-io/karmada#2212]
**What would you like to be added**:
working with istio on non flat network when your cluster don't have LB
**Why is this needed**:
Most of clusters don't have LB.

**Comment by suwliang3** [comment]
@suwliang3

**Comment by XiShanYongYe-Chang** [comment]
As lack of activity, close it now. Please feel free to reopen it if you think we still need it.
/close
