### ISSUE TITLE
karmada-search cannot query single namespace information

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#2221]
**What happened**:
When I query a single namespace information through karmada-search, I can't find it, but when I query all namespaces, I can query the namespace information.
```
kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/api/v1/namespaces/nihao123
```

**Anything else we need to know?**:
karmada-searche logs:
```
E0720 02:28:00.980820       1 cache.go:110] Failed to get /v1, Resource=namespaces resource(nihao123/nihao123) from cluster(member1)'s informer cache: namespaces "nihao123" not found
E0720 02:28:00.980891       1 cache.go:110] Failed to get /v1, Resource=namespaces resource(nihao123/nihao123) from cluster(member2)'s informer cache: namespaces "nihao123" not found
```

**Environment**: 
- Karmada version: 1.2.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 1.2.0

**Comment by XiShanYongYe-Chang** [comment]
Thanks for you pointing out this bug.

This bug seems we don't correctly resolve the `namespace resource`, the namespace of the `namespace resource` should be empty.

/assign @luoMonkeyKing
