### ISSUE TITLE
Make it easier to use `Retain`

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#2223]
**What would you like to be added**:

A more easyly way to use `Retain` in crd.

**Why is this needed**:

Currently, I need to write a whole project( **customresourceinterpreter**) to  use the `Retain ` when my resource is a crd ,and I must to deploy this project . Can we provide a simple way or API to implement it , like `Overridepolicy `using  `PlaintextOverrider ` to patch the resource .

**Comment by RainbowMango** [comment]
Do you mean you want an easy way(don't need to implement the webhook) to customize your CRD?
Something like https://github.com/karmada-io/karmada/tree/master/docs/proposals/configurable-local-value-retention ?

**Comment by duanmengkk** [comment]
That's what I was thinking,What is the progress of it ?

> Do you mean you want an easy way(don't need to implement the webhook) to customize your CRD? Something like https://github.com/karmada-io/karmada/tree/master/docs/proposals/configurable-local-value-retention ?

**Comment by RainbowMango** [comment]
> That's what I was thinking,What is the progress of it ?

We need a demo for the [proposal](https://github.com/karmada-io/karmada/tree/master/docs/proposals/configurable-local-value-retention) to make sure it really works as expected.
Even though the proposal is only for `retain`, it can be easily extended to support other interpreters, like `aggregate status`. So, there is a lot of work to do.

cc @wuyingjun-lucky .
