### ISSUE TITLE
add nodeSelector for etcd in charts

### ISSUE THREAD

**Issue by Fish-pro** [karmada-io/karmada#2231]
**What would you like to be added**:
add nodeSelector for etcd in charts

**Why is this needed**:

When I used charts to deploy Karmada, the storage type of etcd was `hostPath`. After the deployment, if there was delete some pods,  pod was only configured with anti-affinity, so it might be re-scheduled to a new node. At this time, an error would occur, resulting in the normal operation of Karmada
etcd pod logs:
```shell
$ kubectl -n karmada-system logs -f etcd-0
2022-07-21 01:56:46.209379 E | rafthttp: failed to dial 6458921221e19302 on steam MsaApp v2 (peer 6458921221e19302 failed to find local node 92ead5a9687d4550
```
karmada-apiserver logs:
```shell
$ kubectl -n karmada-system logs -f  karmada-apiserver-665695645c-rcw5c
w072 02:00:38.445173          1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://etcd-client.karmada-system.svc.cluster.local:2379 <nil> 0 <nil>}. Err : connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
```
Therefore, it is necessary that we schedule fixed nodes for etcd

**Comment by Poor12** [comment]
I'm not sure about the root cause of the issue. Is that because the pod of etcd is scheduled to another node?

**Comment by Fish-pro** [comment]
> I'm not sure about the root cause of the issue. Is that because the pod of etcd is scheduled to another node?

@Poor12 Thanks for your reply. Yes, pod has been scheduled to a new node
