### ISSUE TITLE
namespace sync controller support ClusterOverridePolicy

### ISSUE THREAD

**Issue by zirain** [karmada-io/karmada#2236]
**What would you like to be added**:

namespace sync controller support `ClusterOverridePolicy`

**Why is this needed**:

In this [working-with-istio-on-non-flat-network](https://github.com/karmada-io/karmada/blob/master/docs/working-with-istio-on-non-flat-network.md), we need change `karmada-controller-manager`'s args,  with that we can set different labels on `istio-system` in different member clusters.

If we allow `ClusterOverridePolicy` can be applied during namespace syncing loop, it will make something like that more easier.

cc @RainbowMango @XiShanYongYe-Chang

**Comment by RainbowMango** [comment]
Let me try to understand this.
Since installing `Istio` needs to set different labels on namespaces(istio-system), and because `namespace` controller does not support `ClusterOverridePolicy`, so we have to disable it by changing `karmada-controller-manager`'s args:
```
--controllers=-namespace,*
```
then, manage the namespace propagation by `ClusterPropagationPolicy` and `ClusterOverridePolicy`.

Am I right? 

It makes sense to me, but don't know if and how we can reuse the [ApplyOverride code](https://github.com/karmada-io/karmada/blob/0ab14028f12dbd63f0ed0fccdedd820a683e2076/pkg/controllers/binding/common.go#L120).
Can you help to investigate it?

**Comment by RainbowMango** [comment]
By the way, you don't need to disable `namespace` controller if you only need to customize `istio-system` namespace.
You can use `--skipped-propagating-namespaces` to specify namespaces that you don't want to propagate by `namespace controller`.
```
--skipped-propagating-namespaces strings                                                                                                                                                                                   
                Comma-separated namespaces that should be skipped from propagating in addition to the default skipped namespaces(karmada-system, karmada-cluster, namespaces prefixed by kube- and karmada-es-).
```

**Comment by zirain** [comment]
> By the way, you don't need to disable `namespace` controller if you only need to customize `istio-system` namespace. You can use `--skipped-propagating-namespaces` to specify namespaces that you don't want to propagate by `namespace controller`.
> 
> ```
> --skipped-propagating-namespaces strings                                                                                                                                                                                   
>                 Comma-separated namespaces that should be skipped from propagating in addition to the default skipped namespaces(karmada-system, karmada-cluster, namespaces prefixed by kube- and karmada-es-).
> ```

if add `istio-system` into `skipped-propagating-namespaces `, I need create `ClusterPropagationPolicy` to sync namespace, and `ClusterOverridePolicy` to override annotations?

**Comment by RainbowMango** [comment]
> if I add istio-system into skipped-propagating-namespaces , I need create ClusterPropagationPolicy to sync namespace, and ClusterOverridePolicy to override annotations?

Ignore me. The `--skipped-propagating-namespaces` would disable the namespaces from propagating, which means both `namespace` controller and `ClusterOverridePolicy` can't propagate it. 
https://github.com/karmada-io/karmada/blob/ed9b838056ee45720abf51b2d603548e6ce922bf/pkg/detector/detector.go#L291-L294
