### ISSUE TITLE
Refactor code to make re-use and extend scheduler functionality more easily

### ISSUE THREAD

**Issue by elinx** [karmada-io/karmada#2247]
**What would you like to be added**:
1. make `selectClusters` method public accessible: https://github.com/karmada-io/karmada/blob/6969a5d643fbb0024f44dfc6ae2340828370ca88/pkg/scheduler/core/generic_scheduler.go#L76
2. make `assignReplicas` public accessible: https://github.com/karmada-io/karmada/blob/6969a5d643fbb0024f44dfc6ae2340828370ca88/pkg/scheduler/core/generic_scheduler.go#L82
3. make the whole `pkg/scheduler/core/util.go` functions public accessible
4. `getPlacement` and `getClusterPlacement` are coupled with cluster and policy listers, if I want to use the selection placement logic I have to copy the code, maybe putting the lister logic into a callback function is a good choice:https://github.com/karmada-io/karmada/blob/6969a5d643fbb0024f44dfc6ae2340828370ca88/pkg/scheduler/scheduler.go#L256
5. is it possible to make `selectBestClustersBySpreadConstraints` customizable? like if I want to add more constraint methods like by region order and don't need to change the framework code: https://github.com/karmada-io/karmada/blob/cb2836db297925c96c79074c12531b498f794760/pkg/scheduler/core/spreadconstraint/select_clusters.go#L37-L43

**Why is this needed**:
I'm developing an enhanced scheduler to support our business needs which needs to re-use karmada scheduler code where some are not publicly accessible and some are not customizable, so I've to copy and paste the code from the scheduler, maybe it's good to make them public and some improvements, please take a look.

**Comment by RainbowMango** [comment]
> make selectClusters method public accessible:

Something like this? 
```diff
diff --git a/pkg/scheduler/core/generic_scheduler.go b/pkg/scheduler/core/generic_scheduler.go
index 453df094..ec424489 100644                                                               
--- a/pkg/scheduler/core/generic_scheduler.go                                                 
+++ b/pkg/scheduler/core/generic_scheduler.go                                                 
@@ -145,7 +145,7 @@ func (g *genericScheduler) prioritizeClusters(                            
        return result, nil                                                                    
 }

-func (g *genericScheduler) selectClusters(clustersScore framework.ClusterScoreList,
+func (g *genericScheduler) SelectClusters(clustersScore framework.ClusterScoreList,
        placement *policyv1alpha1.Placement, spec *workv1alpha2.ResourceBindingSpec) ([]*clusterv1alpha1.Cluster, error) {
        defer metrics.ScheduleStep(metrics.ScheduleStepSelect, time.Now())

```

**Comment by elinx** [comment]
These two methods don't use  `genericScheduler`'s member variable, how about removing the receiver like this:

```diff
diff --git a/pkg/scheduler/core/generic_scheduler.go b/pkg/scheduler/core/generic_scheduler.go
index 453df094..ec424489 100644                                                               
--- a/pkg/scheduler/core/generic_scheduler.go                                                 
+++ b/pkg/scheduler/core/generic_scheduler.go                                                 
@@ -145,7 +145,7 @@ func (g *genericScheduler) prioritizeClusters(                            
        return result, nil                                                                    
 }

-func (g *genericScheduler) selectClusters(clustersScore framework.ClusterScoreList,
+func SelectClusters(clustersScore framework.ClusterScoreList,
        placement *policyv1alpha1.Placement, spec *workv1alpha2.ResourceBindingSpec) ([]*clusterv1alpha1.Cluster, error) {
        defer metrics.ScheduleStep(metrics.ScheduleStepSelect, time.Now())
```

**Comment by RainbowMango** [comment]
> These two methods don't use genericScheduler's member variable, how about removing the receiver like this:

I think `selectCluster` is part of `genericScheduler`. Please confirm if https://github.com/karmada-io/karmada/issues/2247#issuecomment-1193642334 is acceptable in your case.

**Comment by elinx** [comment]
> > These two methods don't use genericScheduler's member variable, how about removing the receiver like this:
> 
> I think `selectCluster` is part of `genericScheduler`. Please confirm if [#2247 (comment)](https://github.com/karmada-io/karmada/issues/2247#issuecomment-1193642334) is acceptable in your case.

In this way, I need to create a `genericScheduler` object which requires a scheduler cache and a plugins registry, and to create the later two I need to import a lot more packages like `Snapshot`, `Cache`, `Plugins` etc. and need to do more adaptions. Then I use the whole function of `genericScheduler` and can't customize it anymore, right?

From the architectural view, there maybe exist a `specificScheduler` in the future in karmada scheduler and it perhaps shares some same process as the `genericScheduler`. From this point, it might be good to put these functions somewhere in public for combinations. Just a wild guess, what do you think.

**Comment by RainbowMango** [comment]
I get it. You just need `selectClusters`, the single method, not the `genericScheduler`. right?

**Comment by elinx** [comment]
> I get it. You just need `selectClusters`, the single method, not the `genericScheduler`. right?

yes

**Comment by XiShanYongYe-Chang** [comment]
Hi @elinx, at present, the relevant code logic may be changed, can you help to see it again?

**Comment by RainbowMango** [comment]
Seems @elinx not need this right now.
/close
