### ISSUE TITLE
Karmada can not support `.spec.ttlSecondsAfterFinished` by job

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2248]
**What happened**:
The job will not be deleted in karmada control plane

**What you expected to happen**:
The job will be deleted in karmada control plane and member clusters

**How to reproduce it (as minimally and precisely as possible)**:
1· Use `karmada init` a karmada cluster
2. Create a job with setting .spec.ttlSecondsAfterFinished and pp in karmada control plane 

**Anything else we need to know?**:

**The karmada is deployed by `karmada init`**

**Comment by wuyingjun-lucky** [comment]
Can we add `ttl-after-finished` controller into  [karmada-init](ttl-after-finished)  ?
@RainbowMango @lonelyCZ @prodanlabs

**Comment by wuyingjun-lucky** [comment]
HI，@ligapeng Maybe we can wait for @RainbowMango @lonelyCZ @prodanlabs  suggestions

**Comment by XiShanYongYe-Chang** [comment]
/cc @RainbowMango @lonelyCZ @prodanlabs 
Ask related guys to help take a look~
