### ISSUE TITLE
somethings different between charts and artifacts

### ISSUE THREAD

**Issue by zhixian82** [karmada-io/karmada#2254]
1. a validate webhook config defined in:  

https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/_karmada_webhook_configuration.tpl#L62

while no such configuration in https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/webhook-configuration.yaml

which one is correct？

**Comment by RainbowMango** [comment]
Seems we don't have `MutatingWebhookConfiguration` for ClusterOverridePolicy, I guess it's a mistake from #1129.

@lonelyCZ can you help to confirm it?

**Comment by lonelyCZ** [comment]
> a validate webhook config defined in:
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/_karmada_webhook_configuration.tpl#L62
> 
>while no such configuration in https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/webhook-configuration.yaml

It seems same. What is different?

https://github.com/karmada-io/karmada/blob/ec84d649a9975435f58f690493e943204f9fbff6/charts/karmada/templates/_karmada_webhook_configuration.tpl#L62

https://github.com/karmada-io/karmada/blob/ec84d649a9975435f58f690493e943204f9fbff6/artifacts/deploy/webhook-configuration.yaml#L122

**Comment by lonelyCZ** [comment]
> Seems we don't have MutatingWebhookConfiguration for ClusterOverridePolicy, I guess it's a mistake from https://github.com/karmada-io/karmada/pull/1129.

I remember that it didn't have mutating operating, so not to add it.
