### ISSUE TITLE
cluster apiservice not created when certs.mode not 'auto'

### ISSUE THREAD

**Issue by zhixian82** [karmada-io/karmada#2255]
https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/pre-install-job.yaml#L1
https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/pre-install-job.yaml#L84

cluster apiservice is required in any case，so maybe apiservice should be added to post-install-job also：https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/post-install-job.yaml

**Comment by Poor12** [comment]
It does make sense. Would you like to send a pr to fix it?

**Comment by zhixian82** [comment]
> It does make sense. Would you like to send a pr to fix it?

https://github.com/karmada-io/karmada/pull/2258
