### ISSUE TITLE
kindly ask about the release of hpa

### ISSUE THREAD

**Issue by zhixian82** [karmada-io/karmada#2259]
The multi cluster HPA feature was included in 2022 H1 [roadmap](https://github.com/karmada-io/karmada/blob/master/ROADMAP.md)

```
2022 H1
...
Multi-cluster HPA (Horizontal Pod Autoscaling)
...
```

May I ask which release will contains this feature?

**Comment by watermeion** [comment]
I'm curious to know when Karmada plans to release the next version. The features outlined in the 2022 roadmap are essential for our needs, so I would greatly appreciate it if you could let me know as soon as possible. Thank you.
@RainbowMango

**Comment by RainbowMango** [comment]
Hi @watermeion @zhixian82 We are working on the [proposal](https://github.com/karmada-io/karmada/pull/3161) right now. We hope to release this feature(or part of) in release-1.5(2023-06-30).  It'd be great if you can help to review the proposal. cc @jwcesign
