### ISSUE TITLE
 failed to update apis:   API rule violation: list_type_missing

### ISSUE THREAD

**Issue by bretagne-peiqi** [karmada-io/karmada#2265]
executed; hack/update_codegen.sh 

Generating with deepcopy-gen
Generating with register-gen
Generating with conversion-gen
Generating with client-gen
Generating with lister-gen
Generating with informer-gen
Generating with openapi-gen
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1,APIEnablement,Resources
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1,ClusterSpec,Taints
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1,ClusterStatus,APIEnablements
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1,ClusterStatus,Conditions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterRequest,AggregatedStatus
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterResponse,Dependencies
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterResponse,Patch
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterWebhook,InterpreterContextVersions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterWebhook,Rules
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterWebhookConfiguration,Webhooks
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,Rule,APIGroups
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,Rule,APIVersions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,Rule,Kinds
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,RuleWithOperations,Operations
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,ClusterAffinity,ClusterNames
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,ClusterAffinity,ExcludeClusters
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,ClusterPreferences,StaticWeightList
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,CommandArgsOverrider,Value
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,FederatedResourceQuotaSpec,StaticAssignments
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,FederatedResourceQuotaStatus,AggregatedStatus
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,FieldSelector,MatchExpressions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,OverrideSpec,OverrideRules
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,OverrideSpec,ResourceSelectors
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,ArgsOverrider
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,CommandOverrider
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,ImageOverrider
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,NameOverrider
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,Plaintext
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Placement,ClusterTolerations
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Placement,SpreadConstraints
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,PropagationSpec,DependentOverrides
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,PropagationSpec,ResourceSelectors
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/search/v1alpha1,OpenSearchConfig,Addresses
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/search/v1alpha1,ResourceRegistrySpec,ResourceSelectors
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/search/v1alpha1,ResourceRegistryStatus,Conditions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,ResourceBindingSpec,Clusters
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,ResourceBindingStatus,AggregatedStatus
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,ResourceBindingStatus,Conditions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,WorkStatus,Conditions
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,WorkStatus,ManifestStatuses
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,WorkloadTemplate,Manifests
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,BindingSnapshot,Clusters
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,NodeClaim,Tolerations
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,ResourceBindingSpec,Clusters
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,ResourceBindingSpec,RequiredBy
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,ResourceBindingStatus,AggregatedStatus
API rule violation: list_type_missing,github.com/karmada-io/karmada/pkg/apis/work/v1alpha2,ResourceBindingStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,MutatingWebhook,AdmissionReviewVersions
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,MutatingWebhook,Rules
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,MutatingWebhookConfiguration,Webhooks
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,Rule,APIGroups
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,Rule,APIVersions
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,Rule,Resources
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,RuleWithOperations,Operations
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,ValidatingWebhook,AdmissionReviewVersions
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,ValidatingWebhook,Rules
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,ValidatingWebhookConfiguration,Webhooks
API rule violation: list_type_missing,k8s.io/api/admissionregistration/v1,WebhookClientConfig,CABundle
API rule violation: list_type_missing,k8s.io/api/core/v1,AvoidPods,PreferAvoidPods
API rule violation: list_type_missing,k8s.io/api/core/v1,Capabilities,Add
API rule violation: list_type_missing,k8s.io/api/core/v1,Capabilities,Drop
API rule violation: list_type_missing,k8s.io/api/core/v1,CephFSPersistentVolumeSource,Monitors
API rule violation: list_type_missing,k8s.io/api/core/v1,CephFSVolumeSource,Monitors
API rule violation: list_type_missing,k8s.io/api/core/v1,ComponentStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,ConfigMapProjection,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,ConfigMapVolumeSource,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,Args
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,Command
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,Env
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,EnvFrom
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,VolumeDevices
API rule violation: list_type_missing,k8s.io/api/core/v1,Container,VolumeMounts
API rule violation: list_type_missing,k8s.io/api/core/v1,ContainerImage,Names
API rule violation: list_type_missing,k8s.io/api/core/v1,DownwardAPIProjection,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,DownwardAPIVolumeSource,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,EndpointSubset,Addresses
API rule violation: list_type_missing,k8s.io/api/core/v1,EndpointSubset,NotReadyAddresses
API rule violation: list_type_missing,k8s.io/api/core/v1,EndpointSubset,Ports
API rule violation: list_type_missing,k8s.io/api/core/v1,Endpoints,Subsets
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,Args
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,Command
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,Env
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,EnvFrom
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,VolumeDevices
API rule violation: list_type_missing,k8s.io/api/core/v1,EphemeralContainerCommon,VolumeMounts
API rule violation: list_type_missing,k8s.io/api/core/v1,ExecAction,Command
API rule violation: list_type_missing,k8s.io/api/core/v1,FCVolumeSource,TargetWWNs
API rule violation: list_type_missing,k8s.io/api/core/v1,FCVolumeSource,WWIDs
API rule violation: list_type_missing,k8s.io/api/core/v1,HTTPGetAction,HTTPHeaders
API rule violation: list_type_missing,k8s.io/api/core/v1,HostAlias,Hostnames
API rule violation: list_type_missing,k8s.io/api/core/v1,ISCSIPersistentVolumeSource,Portals
API rule violation: list_type_missing,k8s.io/api/core/v1,ISCSIVolumeSource,Portals
API rule violation: list_type_missing,k8s.io/api/core/v1,LimitRangeSpec,Limits
API rule violation: list_type_missing,k8s.io/api/core/v1,LoadBalancerStatus,Ingress
API rule violation: list_type_missing,k8s.io/api/core/v1,NamespaceSpec,Finalizers
API rule violation: list_type_missing,k8s.io/api/core/v1,NamespaceStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeAffinity,PreferredDuringSchedulingIgnoredDuringExecution
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSelector,NodeSelectorTerms
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSelectorRequirement,Values
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSelectorTerm,MatchExpressions
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSelectorTerm,MatchFields
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSpec,PodCIDRs
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeSpec,Taints
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeStatus,Addresses
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeStatus,Images
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeStatus,VolumesAttached
API rule violation: list_type_missing,k8s.io/api/core/v1,NodeStatus,VolumesInUse
API rule violation: list_type_missing,k8s.io/api/core/v1,PersistentVolumeClaimSpec,AccessModes
API rule violation: list_type_missing,k8s.io/api/core/v1,PersistentVolumeClaimStatus,AccessModes
API rule violation: list_type_missing,k8s.io/api/core/v1,PersistentVolumeClaimStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,PersistentVolumeSpec,AccessModes
API rule violation: list_type_missing,k8s.io/api/core/v1,PersistentVolumeSpec,MountOptions
API rule violation: list_type_missing,k8s.io/api/core/v1,PodAffinity,PreferredDuringSchedulingIgnoredDuringExecution
API rule violation: list_type_missing,k8s.io/api/core/v1,PodAffinity,RequiredDuringSchedulingIgnoredDuringExecution
API rule violation: list_type_missing,k8s.io/api/core/v1,PodAffinityTerm,Namespaces
API rule violation: list_type_missing,k8s.io/api/core/v1,PodAntiAffinity,PreferredDuringSchedulingIgnoredDuringExecution
API rule violation: list_type_missing,k8s.io/api/core/v1,PodAntiAffinity,RequiredDuringSchedulingIgnoredDuringExecution
API rule violation: list_type_missing,k8s.io/api/core/v1,PodDNSConfig,Nameservers
API rule violation: list_type_missing,k8s.io/api/core/v1,PodDNSConfig,Options
API rule violation: list_type_missing,k8s.io/api/core/v1,PodDNSConfig,Searches
API rule violation: list_type_missing,k8s.io/api/core/v1,PodExecOptions,Command
API rule violation: list_type_missing,k8s.io/api/core/v1,PodPortForwardOptions,Ports
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSecurityContext,SupplementalGroups
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSecurityContext,Sysctls
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,Containers
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,EphemeralContainers
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,HostAliases
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,ImagePullSecrets
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,InitContainers
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,ReadinessGates
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,Tolerations
API rule violation: list_type_missing,k8s.io/api/core/v1,PodSpec,Volumes
API rule violation: list_type_missing,k8s.io/api/core/v1,PodStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,PodStatus,ContainerStatuses
API rule violation: list_type_missing,k8s.io/api/core/v1,PodStatus,EphemeralContainerStatuses
API rule violation: list_type_missing,k8s.io/api/core/v1,PodStatus,InitContainerStatuses
API rule violation: list_type_missing,k8s.io/api/core/v1,PodStatus,PodIPs
API rule violation: list_type_missing,k8s.io/api/core/v1,ProjectedVolumeSource,Sources
API rule violation: list_type_missing,k8s.io/api/core/v1,RBDPersistentVolumeSource,CephMonitors
API rule violation: list_type_missing,k8s.io/api/core/v1,RBDVolumeSource,CephMonitors
API rule violation: list_type_missing,k8s.io/api/core/v1,RangeAllocation,Data
API rule violation: list_type_missing,k8s.io/api/core/v1,ReplicationControllerStatus,Conditions
API rule violation: list_type_missing,k8s.io/api/core/v1,ResourceQuotaSpec,Scopes
API rule violation: list_type_missing,k8s.io/api/core/v1,ScopeSelector,MatchExpressions
API rule violation: list_type_missing,k8s.io/api/core/v1,ScopedResourceSelectorRequirement,Values
API rule violation: list_type_missing,k8s.io/api/core/v1,SecretProjection,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,SecretVolumeSource,Items
API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceAccount,ImagePullSecrets
API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceAccount,Secrets
API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceSpec,ExternalIPs
API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceSpec,LoadBalancerSourceRanges
API rule violation: list_type_missing,k8s.io/api/core/v1,TopologySelectorLabelRequirement,Values
API rule violation: list_type_missing,k8s.io/api/core/v1,TopologySelectorTerm,MatchLabelExpressions
API rule violation: list_type_missing,k8s.io/api/networking/v1,IPBlock,Except
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicyEgressRule,Ports
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicyEgressRule,To
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicyIngressRule,From
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicyIngressRule,Ports
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicySpec,Egress
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicySpec,Ingress
API rule violation: list_type_missing,k8s.io/api/networking/v1,NetworkPolicySpec,PolicyTypes
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,ConversionRequest,Objects
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,ConversionResponse,ConvertedObjects
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,CustomResourceDefinitionNames,Categories
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,CustomResourceDefinitionNames,ShortNames
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,CustomResourceDefinitionSpec,Versions
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,CustomResourceDefinitionStatus,StoredVersions
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,CustomResourceDefinitionVersion,AdditionalPrinterColumns
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSON,Raw
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,AllOf
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,AnyOf
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,Enum
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,OneOf
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,Required
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XListMapKeys
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrArray,JSONSchemas
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrStringArray,Property
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,WebhookClientConfig,CABundle
API rule violation: list_type_missing,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,WebhookConversion,ConversionReviewVersions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroup,ServerAddressByClientCIDRs
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroup,Versions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIGroupList,Groups
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResource,Categories
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResource,ShortNames
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIResourceList,APIResources
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIVersions,ServerAddressByClientCIDRs
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,APIVersions,Versions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,ApplyOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,CreateOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,DeleteOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,FieldsV1,Raw
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,LabelSelector,MatchExpressions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,LabelSelectorRequirement,Values
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,ObjectMeta,Finalizers
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,ObjectMeta,ManagedFields
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,ObjectMeta,OwnerReferences
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,PatchOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,RootPaths,Paths
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,StatusDetails,Causes
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,Table,ColumnDefinitions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,Table,Rows
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,TableRow,Cells
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,TableRow,Conditions
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/apis/meta/v1,UpdateOptions,DryRun
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/runtime,RawExtension,Raw
API rule violation: list_type_missing,k8s.io/apimachinery/pkg/runtime,Unknown,Raw
API rule violation: names_match,github.com/karmada-io/karmada/pkg/apis/config/v1alpha1,ResourceInterpreterRequest,DesiredReplicas
API rule violation: names_match,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,ClusterAffinity,ExcludeClusters
API rule violation: names_match,github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1,Overriders,NameOverrider
API rule violation: names_match,github.com/karmada-io/karmada/pkg/apis/work/v1alpha1,ObjectReference,ReplicaResourceRequirements
API rule violation: names_match,k8s.io/api/core/v1,AzureDiskVolumeSource,DataDiskURI
API rule violation: names_match,k8s.io/api/core/v1,ContainerStatus,LastTerminationState
API rule violation: names_match,k8s.io/api/core/v1,DaemonEndpoint,Port
API rule violation: names_match,k8s.io/api/core/v1,Event,ReportingController
API rule violation: names_match,k8s.io/api/core/v1,FCVolumeSource,WWIDs
API rule violation: names_match,k8s.io/api/core/v1,GlusterfsPersistentVolumeSource,EndpointsName
API rule violation: names_match,k8s.io/api/core/v1,GlusterfsVolumeSource,EndpointsName
API rule violation: names_match,k8s.io/api/core/v1,ISCSIPersistentVolumeSource,DiscoveryCHAPAuth
API rule violation: names_match,k8s.io/api/core/v1,ISCSIPersistentVolumeSource,SessionCHAPAuth
API rule violation: names_match,k8s.io/api/core/v1,ISCSIVolumeSource,DiscoveryCHAPAuth
API rule violation: names_match,k8s.io/api/core/v1,ISCSIVolumeSource,SessionCHAPAuth
API rule violation: names_match,k8s.io/api/core/v1,NodeResources,Capacity
API rule violation: names_match,k8s.io/api/core/v1,NodeSpec,DoNotUseExternalID
API rule violation: names_match,k8s.io/api/core/v1,PersistentVolumeSource,CephFS
API rule violation: names_match,k8s.io/api/core/v1,PersistentVolumeSource,StorageOS
API rule violation: names_match,k8s.io/api/core/v1,PodSpec,DeprecatedServiceAccount
API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,CephMonitors
API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RBDImage
API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RBDPool
API rule violation: names_match,k8s.io/api/core/v1,RBDPersistentVolumeSource,RadosUser
API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,CephMonitors
API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RBDImage
API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RBDPool
API rule violation: names_match,k8s.io/api/core/v1,RBDVolumeSource,RadosUser
API rule violation: names_match,k8s.io/api/core/v1,VolumeSource,CephFS
API rule violation: names_match,k8s.io/api/core/v1,VolumeSource,StorageOS
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSON,Raw
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,Ref
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,Schema
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XEmbeddedResource
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XIntOrString
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XListMapKeys
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XListType
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XMapType
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XPreserveUnknownFields
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaProps,XValidations
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrArray,JSONSchemas
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrArray,Schema
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrBool,Allows
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrBool,Schema
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrStringArray,Property
API rule violation: names_match,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1,JSONSchemaPropsOrStringArray,Schema
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,Quantity,Format
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,Quantity,d
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,Quantity,i
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,Quantity,s
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,int64Amount,scale
API rule violation: names_match,k8s.io/apimachinery/pkg/api/resource,int64Amount,value
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,APIResourceList,APIResources
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,Duration,Duration
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,InternalEvent,Object
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,InternalEvent,Type
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,MicroTime,Time
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,ObjectMeta,ZZZ_DeprecatedClusterName
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,StatusCause,Type
API rule violation: names_match,k8s.io/apimachinery/pkg/apis/meta/v1,Time,Time
API rule violation: names_match,k8s.io/apimachinery/pkg/runtime,Unknown,ContentEncoding
API rule violation: names_match,k8s.io/apimachinery/pkg/runtime,Unknown,ContentType
API rule violation: names_match,k8s.io/apimachinery/pkg/runtime,Unknown,Raw

**Comment by bretagne-peiqi** [comment]
I am not sure if it's a bug, but it failed to generate new apis

**Comment by RainbowMango** [comment]
I noticed it too, but I'm not sure if this is a bug either. But thanks for pointing it out.

> but it failed to generate new apis

What do you mean `failed to generate new APIs`?

**Comment by bretagne-peiqi** [comment]
I means the generated files

**Comment by RainbowMango** [comment]
I suppose these are `warning`s, not errors. All the generated files are generated as expected, right?

**Comment by bretagne-peiqi** [comment]
I run the script， but my deepcopy.files are not renewed. so I suppose there exists some errors?

**Comment by RainbowMango** [comment]
I guess they are generated to `$GOPATH/src/github.com/karmada-io/karmada` which is the working directory.

**Comment by cmicat** [comment]
I run into this error when run `make verify`. Comment `bash "$REPO_ROOT/hack/verify-codegen.sh"` will remove this error.

**Comment by RainbowMango** [comment]
@cmicat Do you mean run `make verify` would raise the error but `bash "$REPO_ROOT/hack/verify-codegen.sh"` won't?

**Comment by cmicat** [comment]
> @cmicat Do you mean run `make verify` would raise the error but `bash "$REPO_ROOT/hack/verify-codegen.sh"` won't?

I mean run `make verify` will run `bash "$REPO_ROOT/hack/verify-codegen.sh"`. This will fail `make verify`. 

Currently, we need to comment `bash "$REPO_ROOT/hack/verify-codegen.sh"` to be able to run verification.

I found this issue because I cannot run `make verify` in my development machine.

**Comment by RainbowMango** [comment]
I just confirmed on my side, `make verify` works for me, it won't fail, but also dumps a lot of `API rule violation` warnings.
```
-bash-4.2# uname -a 
Linux ecs-d8b6 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cmicat** [comment]
I reran `make verify`, found it worked. There might be some environment issue in my development machine.

**Comment by XiShanYongYe-Chang** [comment]
Since the current issue has been inactive for too long, close it first, and you can always reopen it if there is a problem.
/close
