### ISSUE TITLE
REQUEST: add carlory to karmadactl reviewers 

### ISSUE THREAD

**Issue by carlory** [karmada-io/karmada#2270]
Hello team. I'd like to nominate myself to karmadactl reviewers.

I have learned a lot from the projects since Jan 2, 2022. And I would like to step up and continue it to learn more.

**Reviewer requirements:**

ref: https://github.com/karmada-io/community/blob/main/community-membership.md#requirements-1

- member for at least 1 months: https://github.com/karmada-io/karmada/issues/1626
- Primary reviewer for at least 5 PRs to the codebase: [Reviewed 14 PRs](https://github.com/karmada-io/karmada/pulls?q=is%3Apr++reviewed-by%3Acarlory+)
- Reviewed or merged at least 20 substantial PRs to the codebase: [32 merged PRs + 5 reviewed PRs](https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Acarlory+)

Finally, hope bring more improvements for Karmada in the future.

/cc @RainbowMango @lonelyCZ

**Comment by lonelyCZ** [comment]
+1

Thanks for your contributions!!!

**Comment by RainbowMango** [comment]
Thanks. 
Please @lonelyCZ or @carlory send a PR for this.
