### ISSUE TITLE
how can we run the latest  Kyverno in karmada-host

### ISSUE THREAD

**Issue by hackerboy01** [karmada-io/karmada#2279]
**Please provide an in-depth description of the question you have**:
The latest version of Kyverno has removed kubeconfig flags support, how can we run Kyverno in karmada-host? 

https://github.com/karmada-io/karmada/blob/master/docs/working-with-kyverno.md

**Comment by hackerboy01** [comment]
@Poor12 @AllenZMC Could you please take a look at this issues?

**Comment by Poor12** [comment]
If kubeconfig flag is removed, you can try to set `KUBECONFIG`  environment env in the Pod.

**Comment by hackerboy01** [comment]
> If kubeconfig flag is removed, you can try to set `KUBECONFIG` environment env in the Pod.
the latest Kyverno is only supported to run  InClusterConfig.
https://github.com/kyverno/kyverno/blob/main/cmd/kyverno/main.go#L121

**Comment by Poor12** [comment]
Seems that it's removed in https://github.com/kyverno/kyverno/issues/3570. For my opinion, whether it's used by flag or environment env, Kyverno should support configurable `KUBECONFIG`. Could you start an issue in Kyverno community? Maybe we can push this thing together.

**Comment by hackerboy01** [comment]
There is an issue here(https://github.com/kyverno/kyverno/discussions/4282) , we can push this thing together.

**Comment by Poor12** [comment]
Completed.
/close
