### ISSUE TITLE
improve istio on karmada doc

### ISSUE THREAD

**Issue by zirain** [karmada-io/karmada#2288]
**What would you like to be added**:

improve istio on karmada doc

**Why is this needed**:

we can simply this [doc](https://github.com/karmada-io/karmada/blob/master/docs/working-with-istio-on-non-flat-network.md) after this [PR](https://github.com/karmada-io/karmada/pull/2263) released.

**Comment by RainbowMango** [comment]
Thank you !!! 
/assign @zirain
