### ISSUE TITLE
chart: install together karmada and its component together use `host` installMode

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#2290]
**What would you like to be added**:
case: I want install karmada necessary components and search component, I will exec following two commands:
* Firstly, install karmada with `host` installMode:
```shell
helm install karmada -n karmada-system --create-namespace --dependency-update ./charts/karmada --debug
```

* And then install search component with `component` installMode:
```shell
helm install karmada -n karmada-system --create-namespace --dependency-update ./charts/karmada  \
--set installMode=component \ 
--set components={search} --debug
```

I think it’s not friendly to users, if we combine `host` and `component` installMode, and only use a single cmd to completed above operation:

```shell
helm install karmada -n karmada-system --create-namespace --dependency-update ./charts/karmada  \
--set components={search}  --debug
```

**Why is this needed**:
I think It is more convenient to users. please correct me if not.

**Comment by calvin0327** [comment]
@Poor12 @RainbowMango What do you think? We can talk about it together. I dont konw Is there a historical reason with component installMode?

**Comment by Poor12** [comment]
Karmada-search is mainly a optional components. Users can judge whether to install Karmada-search according to their own needs.

**Comment by calvin0327** [comment]
> Karmada-search is mainly a optional components. Users can judge whether to install Karmada-search according to their own needs.

Yes, you are right. the `schedulerEstimator`, `descheduler` and `search` are all optional components.
we can use flag `--set components` to select components to install. If we are not set the flag that means we don't install them.  I mean we don't need to install `karmada` and component separately.

**Comment by lonelyCZ** [comment]
We will use `karmadactl addons` to deploy optional conponents, referring #2134 . Surely we also should be able to select to deploy them by Helm.

**Comment by Poor12** [comment]
> > Karmada-search is mainly a optional components. Users can judge whether to install Karmada-search according to their own needs.
> 
> Yes, you are right. the `schedulerEstimator`, `descheduler` and `search` are all optional components. we can use flag `--set components` to select components to install. If we are not set the flag that means we don't install them. I mean we don't need to install `karmada` and component separately.

Sorry for misunderstanding. I think it's quite useful to provide a way to install together while maintaining the original optional strategy. Are you willing to work on it？

**Comment by calvin0327** [comment]
@Poor12 ok. 
/assign
