### ISSUE TITLE
karmadactl promote 接管成员集群应用之后，是否可以取消接管

### ISSUE THREAD

**Issue by sunt89** [karmada-io/karmada#2307]
**Please provide an in-depth description of the question you have**:
karmadactl promote 接管成员集群应用之后，是否可以取消接管，而不影响成员集群上的应用

**Environment**:
- Karmada version: v1.2.1
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
使用场景是什么呢？为什么要取消接管？

**Comment by sunt89** [comment]
> 使用场景是什么呢？为什么要取消接管？

目前没有实际的使用场景，只是测试到这块的时候，在文档里面看到没有取消接管的流程，出于完整性的考虑，这边产生了一些疑问，既然有接管的流程，为啥就没有取消接管的流程。

**Comment by RainbowMango** [comment]
取消接管，其实是`join`的反向操作`unjoin`，当前的行为是清理目标集群中通过Karmada分发的资源，当然，也有[一个提案](https://github.com/karmada-io/karmada/blob/master/docs/keps/cleanup-propagated-resources.md)是希望有机制能够保留资源，但暂时缺乏更多的使用场景，所以还未开发。

**Comment by sunt89** [comment]
> 取消接管，其实是`join`的反向操作`unjoin`，当前的行为是清理目标集群中通过Karmada分发的资源，当然，也有[一个提案](https://github.com/karmada-io/karmada/blob/master/docs/keps/cleanup-propagated-resources.md)是希望有机制能够保留资源，但暂时缺乏更多的使用场景，所以还未开发。

好的  谢谢

**Comment by XiShanYongYe-Chang** [comment]
更新下提案链接：https://github.com/karmada-io/karmada/tree/master/docs/proposals/cleanup-propagated-resources
