### ISSUE TITLE
Add some samples with `client-go` to use karmada

### ISSUE THREAD

**Issue by victory460** [karmada-io/karmada#2320]
**What would you like to be added**:
Some samples with `client-go` to use karmada.

**Why is this needed**:
Easy make more app base karmada with `client-go`.

**Comment by RainbowMango** [comment]
I don't know if there is an example for Kubernetes. Don't know what kind of example would help.

By the way, Karmada generates the client set at [here](https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/generated/clientset/versioned/clientset.go#L93) it's very similar to client-go.

**Comment by victory460** [comment]
> I don't know if there is an example for Kubernetes. Don't know what kind of example would help.
> 
> By the way, Karmada generates the client set at [here](https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/generated/clientset/versioned/clientset.go#L93) it's very similar to client-go.

Thanks for your reply.
I want to known that how to create `PropagationPolicy`  by  `client-go` and [deploy a simplest multi-cluster Deployment](https://karmada.io/docs/userguide/resource-propagating) with `client-go` ,  but not use kubectl and karmadactl.

**Comment by RainbowMango** [comment]
We don't have a such example yet. But maybe you can refer to the E2E test for CRUD examples.
https://github.com/karmada-io/karmada/blob/0694d0cdd4dc309bb5609c8d9c4d730722a0a306/test/e2e/framework/propagationpolicy.go#L20

**Comment by victory460** [comment]
> We don't have a such example yet. But maybe you can refer to the E2E test for CRUD examples.
> 
> https://github.com/karmada-io/karmada/blob/0694d0cdd4dc309bb5609c8d9c4d730722a0a306/test/e2e/framework/propagationpolicy.go#L20

Thanks a lot.
