### ISSUE TITLE
Put Lease to default SkippedResourceConfig 

### ISSUE THREAD

**Issue by duanmengkk** [karmada-io/karmada#2321]
**Please provide an in-depth description of the question you have**:
The following logs are continuously output in console, This makes log unreadble. Should we put `Lease ` to `SkippedResourceConfig` ? 
```
I0804 13:11:28.990003   20744 recorder.go:103] "events: Warning" object={Kind:Lease Namespace:karmada-dm Name:karmada-scheduler UID:12d61ad2-e93e-46e1-ab72-4815217c74e8 APIVersion:coordination.k8s.io/v1 ResourceVersion:108632 FieldPath:} reason="ApplyPolicyFailed" message="No policy match for resource"
I0804 13:11:28.990003   20744 recorder.go:103] "events: Warning" object={Kind:Lease Namespace:karmada-dm Name:kube-controller-manager UID:0b0eac39-a7bf-4f55-88d5-04a3e4167981 APIVersion:coordination.k8s.io/v1 ResourceVersion:108633 FieldPath:} reason="ApplyPolicyFailed" message="No policy match for resource"
```

```
// disable Lease by default
r.DisableGroupVersion(coordinationv1.SchemeGroupVersion)
```

@RainbowMango @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
I think `Lease` should be ignored by the detector, but are these logs related to whether we disable it or not?

**Comment by duanmengkk** [comment]
> I think `Lease` should be ignored by the detector, but are these logs related to whether we disable it or not?

Yes,Lease will update every 10 seconds,so the log will continuously output. I will try to fix it.
/assign @duanmengkk

**Comment by XiShanYongYe-Chang** [comment]
Hi @duanmengkk, where is the log printing you mentioned about handled in the code?

**Comment by duanmengkk** [comment]
> 
Dector will watch all resources in karmada, so these logs will continuously output since Lease is updated every few seconds.

https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/detector/detector.go#L399
https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/detector/detector.go#L392
https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/detector/detector.go#L361
https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/detector/detector.go#L354
https://github.com/karmada-io/karmada/blob/393bf843ded76f1e3d318123734343a3e7917af0/pkg/detector/detector.go#L255

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your explain, I got it.

**Comment by RainbowMango** [comment]
Yeah, I think it's fair enough to disable `lease`. 

Just a question, can we get the log from CI?

**Comment by duanmengkk** [comment]
![image](https://user-images.githubusercontent.com/17697155/182797075-91a5534f-4ce2-4fb4-90d1-0625c4ea4013.png)


> Yeah, I think it's fair enough to disable `lease`.
> 
> Just a question, can we get the log from CI?

CI doesn't mean github CI ?  Do you mean this?

**Comment by RainbowMango** [comment]
Yes, thanks.
