### ISSUE TITLE
Karmada search sync data error By using opensearch

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2335]
**What happened**:
Karmada search sync data error By using opensearch
**What you expected to happen**:
Karmada search sync data successfully By using opensearch
**How to reproduce it (as minimally and precisely as possible)**:
1、using opensearch to registry
<img width="666" alt="image" src="https://user-images.githubusercontent.com/16109961/183007001-a5ec8956-0306-46b0-ac8e-85b0f9d1fca5.png">
2、member clusters has developments with label `app.kubernetes.io/managed-by` and so on
3、search log
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/16109961/183007135-453fd719-f521-4335-8e39-4684c68fa98e.png">

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by wuyingjun-lucky** [comment]
ping @XiShanYongYe-Chang

**Comment by wuyingjun-lucky** [comment]
Besides I start two replicas for karmada-search deployment. There will be two controllers working at one time.  Is that ok ?

**Comment by XiShanYongYe-Chang** [comment]
> Besides I start two replicas for karmada-search deployment. There will be two controllers working at one time. Is that ok ?

Yes, it is.

Ask @huntsman-li @liys87x for help.
