### ISSUE TITLE
install-kubectl-karmada docs do not contain new releases tgz package change description

### ISSUE THREAD

**Issue by ArenaSu** [karmada-io/karmada#2336]
**What happened**:

failed to wget latest karmada-linux from https://karmada.io/docs/installation/install-kubectl-karmada/ website
```
wget https://github.com/karmada-io/karmada/releases/download/v1.2.1/kubectl-karmada-linux-amd64.tar.gz
```

**What you expected to happen**:
we should add comment that latest package's suffix is tgz.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
/assign @ArenaSu 
In favor of https://github.com/karmada-io/website/pull/124.
