### ISSUE TITLE
Karmada can not support customized clusterDomain with k8s

### ISSUE THREAD

**Issue by mengqinghao** [karmada-io/karmada#2341]
Because  the suffix of domain name fixed and ends with "cluster.local" from karmada component config,
what's more, the certificate has been bound with a fixed domain name (e.g.  etcd-0.etcd.karmada-system.svc.cluster.local),
 
if clusterDomain with k8s  is not default (cluster.local) ,  failed to resolve URL Host with karmada component pods

I think clusterDomain is customized , In particular, with the production environment,  it is not cluster.local 

Support dynamic configuration is necessary to karmada   

**What happened**:

 Installation from Karmadactl will be failed.

**What you expected to happen**:
Installation from Karmadactl will be successful

**How to reproduce it (as minimally and precisely as possible)**:
clusterDomain  is not default(cluster.local),  use karmadactl init to install ...

**Anything else we need to know?**:

**Environment**:
- Karmada version:  v1.2.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.23.1
- Others:

**Comment by RainbowMango** [comment]
> clusterDomain is not default(cluster.local), use karmadactl init to install ...

I wonder if there is a way to reproduce it. Or show us the link to the relevant code.

**Comment by liangyuanpeng** [comment]
I did create a  preview pr https://github.com/liangyuanpeng/karmada/pull/2  to do this, but then I left. Recently this issue was resolved by PR https://github.com/karmada-io/karmada/pull/3292.

Maybe this issue can be closed.

/close

/cc @RainbowMango

**Comment by RainbowMango** [comment]
Yes. This feature will be released in v1.6(by the end of May) by the way.
/remove-kind bug
/kind feature
/close
