### ISSUE TITLE
Default Replica Interpreter should support scale subresource

### ISSUE THREAD

**Issue by yusank** [karmada-io/karmada#2362]
**background**

in current default replica interpreter, it only supports `Deployment` and `job` like this:

```go
func getAllDefaultReplicaInterpreter() map[schema.GroupVersionKind]replicaInterpreter {
	s := make(map[schema.GroupVersionKind]replicaInterpreter)
	s[appsv1.SchemeGroupVersion.WithKind(util.DeploymentKind)] = deployReplica
	s[batchv1.SchemeGroupVersion.WithKind(util.JobKind)] = jobReplica
	return s
}
```

If there are other custom resources like `cloneset`, the `rb` didn't contains replica in spec and got an error log in controller manager:

```log
I0811 02:40:54.531669       1 customized.go:64] Hook interpreter is not enabled for kind "apps.kruise.io/v1alpha1, Kind=CloneSet" with operation "InterpretReplica".
I0811 02:40:54.531683       1 default.go:67] Default interpreter is not enabled for kind "apps.kruise.io/v1alpha1, Kind=CloneSet" with operation "InterpretReplica".
```

**What would you like to be added**:

The Default Replica Interpreter should support k8s [scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) instead of writing hard code. **If this request is sound fair then I  can push a PR.**

**Why is this needed**:

There are not only deployments and jobs in worker clusters , also has own CRD or third party CRD like openkruis. Karmada should try to use k8s defined API or subresource as much as possible to support more situations in  cluster instead of only support k8s defined workload only.

**Comment by yusank** [comment]
https://github.com/karmada-io/karmada/blob/431e06a684c08a027376e66da656bf4f3ef357c9/pkg/resourceinterpreter/defaultinterpreter/replica.go#L18-L23

**Comment by RainbowMango** [comment]
> The Default Replica Interpreter should support k8s [scale subresource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource) instead of writing hard code. If this request is sound fair then I can push a PR.

Thanks @yusank , can you help review #1728? Does it help your case?

**Comment by yusank** [comment]
> Thanks @yusank , can you help review #1728? Does it help your case?

Of course. I'm on it.

**Comment by XiShanYongYe-Chang** [comment]
Please refer to https://github.com/karmada-io/karmada/pull/1728#issuecomment-1331625519
