### ISSUE TITLE
resources may be lost when recovering the network after a disconnection

### ISSUE THREAD

**Issue by JackZxj** [karmada-io/karmada#2364]
**What happened**:
I deploy a deployment into 2 clusters, and mark cluster1 as main, cluster2 as the backup; then I block down the network between clsuter1 and control plane to simulate a sudden failure of the main cluster; and then I mark cluster2 as main, cluster1 as backup by updating OverridePolicy; after that, I recover the network of cluster1 and wait for cluster1 to be the backup. But finally I found that cluster1 would not be the backup, but would be deleted by karmada.

**What you expected to happen**:

Do not delete the resources, and should apply the latest overridepolicy for clusters after reconnection

**How to reproduce it (as minimally and precisely as possible)**:
here are my operations:
```BASH
$ kubectl create ns test1
namespace/test1 created

$ echo '# Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx
---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      port: 80
      nodePort: 30088
---
# PropagationPolicy 
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
spec:
  resourceSelectors: 
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
    - apiVersion: v1
      kind: Service
      name: nginx
  placement:
    clusterAffinity:
      clusterNames: 
        - member1  
        - member2   
---
# OverridePolicy 
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx-override
spec:
  resourceSelectors: 
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  overrideRules:
  - targetCluster:
      clusterNames:
        - member2   
    overriders:
      plaintext:
        - operator: add
          path: /spec/template/spec/containers/0/env
          value: [{"name": "TYPE", "value": "backup"}]
' | kubectl apply -n test1 -f -
deployment.apps/nginx created
service/nginx created
propagationpolicy.policy.karmada.io/nginx-propagation created
overridepolicy.policy.karmada.io/nginx-override created

# it's normal
$ kubectl get deploy,svc,pp,op -owide -n test1
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
deployment.apps/nginx   4/2     4            4           16s   nginx        nginx:alpine   app=nginx

NAME            TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE   SELECTOR
service/nginx   NodePort   10.109.225.9   <none>        80:30088/TCP   16s   app=nginx

NAME                                                    AGE
propagationpolicy.policy.karmada.io/nginx-propagation   16s

# WITHOUT env
$ kubectl get deploy -n test1 nginx  -ojsonpath="{.spec.template.spec.containers[0].env}" --kubeconfig .kube/members.config --context member1

# WITH env
$ kubectl get deploy -n test1 nginx  -ojsonpath="{.spec.template.spec.containers[0].env}" --kubeconfig .kube/members.config --context member2
[{"name":"TYPE","value":"backup"}]
```

turn off the network of cluster1
```BASH
$ iptables -t raw -I PREROUTING -s 127.0.0.1 -j ACCEPT
$ iptables -t raw -A PREROUTING -j DROP
```

in control plane
```bash
# cluster1 become not ready
$ kubectl  get cluster
NAME      VERSION   MODE   READY   AGE
member1   v1.23.6   Push   False   47d
member2   v1.23.6   Push   True    47d
member3   v1.23.6   Pull   True    47d

# update overridepolicy
$ echo 'apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: nginx-override
spec:
  resourceSelectors: 
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  overrideRules:
  - targetCluster:
      clusterNames:
        - member1    
    overriders:
      plaintext:
        - operator: add
          path: /spec/template/spec/containers/0/env
          value: [{"name": "TYPE", "value": "backup"}]
' | kubectl replace -n test1 -f -
overridepolicy.policy.karmada.io/nginx-override replaced

# member2 removes the envs
$ kubectl get deploy -n test1 nginx  -ojsonpath="{.spec.template.spec.containers[0].env}" --kubeconfig .kube/members.config --context member2
```

recover the network of cluster1
```bash
$ iptables -t raw -F
```

wait for cluster1 ready
```bash
$ kubectl  get cluster -w
NAME      VERSION   MODE   READY   AGE
member1   v1.23.6   Push   False   47d
member2   v1.23.6   Push   True    47d
member3   v1.23.6   Pull   True    47d
member1   v1.23.6   Push   True    47d

# after about 5 minutes
$ kubectl get deploy -n test1 nginx  -ojsonpath="{.spec.template.spec.containers[0].env}" --kubeconfig .kube/members.config --context member1
Error from server (NotFound): deployments.apps "nginx" not found
$ kubectl get deploy,svc -n test1 -owide --kubeconfig .kube/members.config --context member1
No resources found in test1 namespace.
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: 
  karmada-controller-manager version: version.Info{GitVersion:"v1.2.0-dirty", GitCommit:"cc74a423222ccf1b6896d7fa8c314544a24cade7", GitTreeState:"clean", BuildDate:"2022-06-24T08:00:11Z", GoVersion:"go1.17", Compiler:"gc", Platform:"linux/amd64"}
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Hi @JackZxj thanks for reaching us.

> But finally I found that cluster1 would not be the backup, but would be deleted by karmada.

Karmada would evict resources from failure clusters by default.
We introduced `eviction by taints` feature to release 1.3(still in the master branch, and will be released by the end of this month). For your case, I guess you can set the [tolerations at PropagationPolicy](https://github.com/karmada-io/karmada/blob/f0379682a201af9b6763b8b7e8af8946c3bfcb6b/pkg/apis/policy/v1alpha1/propagation_types.go#L129), by default we set the tolerations with a default toleration seconds(300s), maybe you can tolerate the taint forever so that the resource would not be removed in case of cluster failure.

I'm not sure if this could solve your problem. You can fetch the latest code and try again, looking forward to your feedback.

**Comment by JackZxj** [comment]
@RainbowMango  Sorry that I can not try it right now, maybe next week I will try it out.

But in my opinion, this solution has a little bit counter-intuitive. I think when clusters recovered after disconnection, it should re-trigger the policies. Because that the PropagationPolicy has declared the clusters to propagate, and it should be firmly executed when the cluster is connected by default. If it is not work as it declared, then I cannot fully trust the results of the PropagationPolicy.  So would you please explain why it is designed like this?

**Comment by RainbowMango** [comment]
> I think when clusters recovered after disconnection, it should re-trigger the policies.

Yes, you are right. Actually, we are working on it.(see #2301). 

> Sorry that I can not try it right now, maybe next week I will try it out.

Thanks in advance. 
Just a reminder, if you are using the master branch, you might have to set [feature gates to `karmada-controller-manager`](https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/artifacts/deploy/karmada-controller-manager.yaml#L32):
```
--feature-gates=PropagateDeps=true,Failover=true,GracefulEviction=true
```
