### ISSUE TITLE
resource with specific name not sync to member cluster

### ISSUE THREAD

**Issue by zirain** [karmada-io/karmada#2392]
**What happened**:

I'm trying to install [OLM](https://olm.operatorframework.io/) with karmada, but got following error message:
```
time="2022-08-19T00:11:31Z" level=fatal msg="couldn't clean previous release" error="catalogsources.operators.coreos.com \"olm-operators\" is forbidden: User \"system:serviceaccount:olm:olm-operator-serviceaccount\" cannot delete resource \"catalogsources\" in API group \"operators.coreos.com\" in the namespace \"olm\": RBAC: clusterrole.rbac.authorization.k8s.io \"system:controller:operator-lifecycle-manager\" not found"
```

seems `system:controller:operator-lifecycle-manager` not sync to member cluster?

cc @XiShanYongYe-Chang 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by zirain** [comment]
seems `karmada` not working with `OLM`, cc @XiShanYongYe-Chang, is this an known issue?

**Comment by XiShanYongYe-Chang** [comment]
This is a known issue. We will try to fix it in the next version.

**Comment by zirain** [comment]
ping @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
For `ClusterRole` and `ClusterRoleBinding` resources, how about replacing the `:` with `-` when generating the name of ClusterResourceBinding?
