### ISSUE TITLE
Cluster Resource Binding controller should sync status for resources

### ISSUE THREAD

**Issue by yusank** [karmada-io/karmada#2394]
**background**
In current code logic, crb controller didn't sync resource status to crd in kramada cluster:
https://github.com/karmada-io/karmada/blob/822abc540b622bad61f1319cc9bbe7d1363fe102/pkg/controllers/binding/cluster_resource_binding_controller.go#L121-L135

If I want to check Resource status like PV, I only go to the member cluster to check.

**What would you like to be added**:
I have added sync status logic in my branch and it's quite same as resource binding controller sync logic:
https://github.com/karmada-io/karmada/blob/303d4652efe70777c1de6b33360f24e7348208e5/pkg/controllers/binding/binding_controller.go#L146-L151

And also need logic to `aggregateStatusInterpreter`. If this fix is acceptable for this repo  I can submit a PR, please let me know if this bugfix/feature is acceptable.

**Why is this needed**:
User need check some cluster level crd status from karmada cluster.

**Comment by RainbowMango** [comment]
> And also need logic to aggregateStatusInterpreter. If this fix is acceptable for this repo I can submit a PR, please let me know if this bugfix/feature is acceptable.

I'm so surprised that we missed status collection for cluster scoped resources. 
@XiShanYongYe-Chang don't we have related E2E tests?

@yusank Sure, I'm glad that you can help with it. 

By the way, @yusank can you help give reproduce steps that let folks better understand this issue?

**Comment by yusank** [comment]
> I'm so surprised that we missed status collection for cluster scoped resources. @XiShanYongYe-Chang don't we have related E2E tests?
> 
> @yusank Sure, I'm glad that you can help with it.
> 
> By the way, @yusank can you help give reproduce steps that let folks better understand this issue?

1. Create a simple PV by `PropagationPolicy` from karmada cluster
2. After PV created in member cluster, PV status is `Available`
<img width="905" alt="image" src="https://user-images.githubusercontent.com/21994267/185555166-eb1f2b92-06bb-445a-af02-f02a99167319.png">
3. But get PV from karmada cluster, PV status shows `Pending`
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/21994267/185555232-85419bfc-aa8d-4892-9559-7bfe4e1369aa.png">

**Comment by XiShanYongYe-Chang** [comment]
> I'm so surprised that we missed status collection for cluster scoped resources.
> @XiShanYongYe-Chang don't we have related E2E tests?

We really didn't handle cluster scoped resources, related E2E tests only namespace scoped `workload` resources.

**Comment by RainbowMango** [comment]
/assign @yusank 
as #2395
