### ISSUE TITLE
It will occur error when `karmada-agent` restart

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#2403]
**What happened**:
After restarting `karmada-agent`, the `karmada-agent` doesn't work fine. It possibly will be not running when `karmada-agent` restart accidently.

```
[root@master68 lonelyCZ]# kubectl logs -n karmada-system   karmada-agent-85cd9b84f5-8nbtz
I0822 09:43:28.276201       1 agent.go:107] karmada-agent version: version.Info{GitVersion:"v1.2.0-537-ge2376149", GitCommit:"e237614954a64b2595b9ec18128834a538975518", GitTreeState:"clean", BuildDate:"2022-08-19T08:38:52Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
E0822 09:43:28.363671       1 run.go:74] "command failed" err="the same cluster has been registered with name member68"
```

**What you expected to happen**:
`karmda-agent` support disaster recovery, just as restarting.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy `karmada-agent` in a member cluster.
2. `kubectl rollout restart -n karmada-system karmada-agent`

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master
- Others:

**Comment by yy158775** [comment]
In https://github.com/karmada-io/karmada/pull/2369 , in order to avoid joining the same cluster repeatedly, I add the logic in the agent.
But it can't distinguish the agent restart or cluster rejoining.

**Comment by yy158775** [comment]
> I think if the name and cluster_id are same as cluster in karmada control plane, we can see it as agent restart, is it?

But if the user deploy two agents in the cluster using the same cluster name and id.

**Comment by lonelyCZ** [comment]
> But if the user deploy two agents in the cluster using the same cluster name and id.

In this way, there will be only one Cluster on the control plane, which does not affect the state of the control plane. In fact, the Agent itself can be deployed with multiple copies to implement disaster recovery. At the same time, we use `cluster_id` only to prevent repeated cluster-joining. If a user insists on using the wrong registration method, we can hardly completely restrict it.
