### ISSUE TITLE
request cherry-pick PR(2258,2401)

### ISSUE THREAD

**Issue by zhixian82** [karmada-io/karmada#2417]
**Please provide an in-depth description of the question you have**:

The release v1.2.0 has the issues: https://github.com/karmada-io/karmada/issues/2255 and https://github.com/karmada-io/karmada/issues/2254. Maybe the fix pr(https://github.com/karmada-io/karmada/pull/2258, https://github.com/karmada-io/karmada/pull/2401) should rebase to release v1.2.0?

**Environment**:
- Karmada version: v1.2.0
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
I guess you mean cherry-pick #2258 and #2401 to release-1.2 branch, and cut a new release(the next release would be v1.2.2). right?

**Comment by zhixian82** [comment]
> I guess you mean cherry-pick #2258 and #2401 to release-1.2 branch, and cut a new release(the next release would be v1.2.2). right?

right

**Comment by RainbowMango** [comment]
/close
We'll cut the patch release this week, it's already on the plan.
