### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by zhuwint** [karmada-io/karmada#2419]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:

https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Azhuwint+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by RainbowMango** [comment]
Hi @zhuwint Please open an issue against on `karmada-io/community` repo. 
https://github.com/karmada-io/community/blob/main/community-membership.md#member

Thanks for your contribution.
/close
