### ISSUE TITLE
Install Karmada for development environment compile error

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2433]
Execute the following command locally ：

hack/local-up-karmada.sh

[go version go1.18.5 darwin/amd64]

output the following：

Preparing: 'kind' existence check - passed
Preparing: 'kubectl' existence check - passed

 Detected that you are installing Karmada on macOS 

It needs a Macintosh IP address to bind Karmada API Server(port 5443),
so that member clusters can access it from docker containers, please
input an available IP, default IP will be en0 inet addr if exists
[Enter for default -------]:
Using IP address: -------
Preparing kindClusterConfig in path: /var/folders/q_/hngcmwfs5258hpdd_8bwb1yw0000gn/T/tmp.TIS8OXRV
Creating cluster karmada-host and the log file is in /tmp/karmada/karmada-host.log
Creating cluster member1 and the log file is in /tmp/karmada/member1.log
Creating cluster member2 and the log file is in /tmp/karmada/member2.log
Creating cluster member3 and the log file is in /tmp/karmada/member3.log
set -e;\
	target=$(echo karmada-aggregated-apiserver);\
	make $target GOOS=linux;\
	VERSION=latest REGISTRY=swr.ap-southeast-1.myhuaweicloud.com/karmada BUILD_PLATFORMS=linux/amd64 hack/docker.sh $target
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-588-g78395393 -X github.com/karmada-io/karmada/pkg/version.gitCommit=7839539383836dab40e556a29a84c87ec2bc8847 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-08-27T04:49:14Z' BUILD_PLATFORMS=linux/amd64 hack/build.sh karmada-aggregated-apiserver
!!! Building karmada-aggregated-apiserver for linux/amd64:
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-588-g78395393 -X github.com/karmada-io/karmada/pkg/version.gitCommit=7839539383836dab40e556a29a84c87ec2bc8847 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-08-27T04:49:14Z' -o _output/bin/linux/amd64/karmada-aggregated-apiserver github.com/karmada-io/karmada/cmd/aggregated-apiserver
# unicode/utf8
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# runtime/internal/sys
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# internal/race
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# internal/unsafeheader
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# math/bits
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# encoding
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# unicode/utf16
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/apimachinery/pkg/selection
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# unicode
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# internal/nettrace
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/utils/strings/slices
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# container/list
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# crypto/internal/subtle
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# crypto/subtle
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/apiserver/pkg/authentication/user
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/apimachinery/pkg/types
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# google.golang.org/protobuf/internal/flags
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/utils/integer
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# internal/cpu
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# runtime/internal/atomic
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# google.golang.org/grpc/attributes
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# google.golang.org/grpc/serviceconfig
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# github.com/google/go-cmp/cmp/internal/flags
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/utils/buffer
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# go.opentelemetry.io/otel/sdk/instrumentation
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# sync/atomic
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# go.opentelemetry.io/contrib
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# go.opentelemetry.io/otel/unit
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# golang.org/x/net/html/atom
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# golang.org/x/crypto/internal/subtle
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/client-go/util/exec
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# k8s.io/apiserver/pkg/util/dryrun
compile: version "go1.16.3" does not match go tool version "go1.18.5"
# golang.org/x/crypto/salsa20/salsa
compile: version "go1.16.3" does not match go tool version "go1.18.5"
make[1]: *** [karmada-aggregated-apiserver] Error 2
make: *** [image-karmada-aggregated-apiserver] Error 2

**Comment by RainbowMango** [comment]
I guess you are using `go 1.18.5`, but the `GOROOT` points to the go source of 1.16.3.
I think you might have to remove 1.16.3 and re-install Go 1.18.5 or, reset your GOROOT.

**Comment by wxuedong** [comment]
> I guess you are using `go 1.18.5`, but the `GOROOT` points to the go source of 1.16.3. I think you might have to remove 1.16.3 and re-install Go 1.18.5 or, reset your GOROOT.

Thanks done
