### ISSUE TITLE
Local execution command  ‘ make kubectl-karmada ’   error

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2438]
go version ：
<img width="626" alt="image" src="https://user-images.githubusercontent.com/15843627/187102355-9b42a87f-1be3-4807-871a-bd2d07dd53db.png">

Update local code to latest：

<img width="824" alt="image" src="https://user-images.githubusercontent.com/15843627/187102495-90d86a2a-ee71-42b2-818d-4f9201916f66.png">

Then execute the command and the following appears：

```
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-594-gb73ea25e -X github.com/karmada-io/karmada/pkg/version.gitCommit=b73ea25e8c8e03b34df537a9b9c4e2c431b2c131 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-08-29T00:35:39Z' BUILD_PLATFORMS=darwin/amd64 hack/build.sh kubectl-karmada
!!! Building kubectl-karmada for darwin/amd64:
+ CGO_ENABLED=0
+ GOOS=darwin
+ GOARCH=amd64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-594-gb73ea25e -X github.com/karmada-io/karmada/pkg/version.gitCommit=b73ea25e8c8e03b34df537a9b9c4e2c431b2c131 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-08-29T00:35:39Z' -o _output/bin/darwin/amd64/kubectl-karmada github.com/karmada-io/karmada/cmd/kubectl-karmada
go: no such tool "compile"
go: no such tool "compile"
make: *** [kubectl-karmada] Error 2

```

**Comment by RainbowMango** [comment]
Hi @wxuedong you might need to check your `Go` configuration, I guess you can't compile any Go code, not only Karmada code.
And here is a reference I just found from StackOverflow:
https://stackoverflow.com/questions/51182422/all-of-a-sudden-go-tool-no-such-tool-compile
