### ISSUE TITLE
How to check the distribution of application resources in each subcluster on Karmada ApI Server?

### ISSUE THREAD

**Issue by wxuedong** [karmada-io/karmada#2440]
For example, I submitted a Deployment resource image as nginx on Karmada ApI Server, and set the number of replicas to 6. Then submit the cluster deployment strategy to deploy 3 pods for each of the two management clusters. After the overall process is over, without accessing the management cluster, how to view the deployment distribution of the Deployment's Pods in Karmada ApI Server, such as how many clusters are deployed to nstance?

**Comment by XiShanYongYe-Chang** [comment]
You can use `karmadactl` to get the resources in the member cluster:

```shell
# _output/bin/linux/amd64/karmadactl get deploy
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE     ADOPTION
nginx   member3   2/2     2            2           3h      Y
nginx   member1   2/2     2            2           3h      N
nginx   member2   2/2     2            2           3h31m   Y
# _output/bin/linux/amd64/karmadactl get pod
NAME                     CLUSTER   READY   STATUS    RESTARTS   AGE
nginx-85b98978db-d69vp   member2   1/1     Running   0          3h32m
nginx-85b98978db-mrj4f   member2   1/1     Running   0          3h32m
nginx-85b98978db-bx9sp   member1   1/1     Running   0          3h2m
nginx-85b98978db-s2fjx   member1   1/1     Running   0          3h2m
nginx-85b98978db-mccnl   member3   1/1     Running   0          3h1m
nginx-85b98978db-wthv5   member3   1/1     Running   0          3h1m
```

**Comment by wxuedong** [comment]
This cmd  only support cluster mode is Push

**Comment by wxuedong** [comment]
> You can use `karmadactl` to get the resources in the member cluster:
> 
> ```shell
> # _output/bin/linux/amd64/karmadactl get deploy
> NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE     ADOPTION
> nginx   member3   2/2     2            2           3h      Y
> nginx   member1   2/2     2            2           3h      N
> nginx   member2   2/2     2            2           3h31m   Y
> # _output/bin/linux/amd64/karmadactl get pod
> NAME                     CLUSTER   READY   STATUS    RESTARTS   AGE
> nginx-85b98978db-d69vp   member2   1/1     Running   0          3h32m
> nginx-85b98978db-mrj4f   member2   1/1     Running   0          3h32m
> nginx-85b98978db-bx9sp   member1   1/1     Running   0          3h2m
> nginx-85b98978db-s2fjx   member1   1/1     Running   0          3h2m
> nginx-85b98978db-mccnl   member3   1/1     Running   0          3h1m
> nginx-85b98978db-wthv5   member3   1/1     Running   0          3h1m
> ```


kubectl karmada --kubeconfig=xxx  get deploy

Error: [cluster() is inaccessible, please check authorization or network, cluster() is inaccessible, please check authorization or network]
(base)


The two cluster mode are Pull ,  another cluster mode is Push it's ok

**Comment by XiShanYongYe-Chang** [comment]
For `Pull` mode cluster, you can work with reverse proxy, for example [ANP](https://karmada.io/docs/userguide/clustermanager/working-with-anp).

**Comment by wxuedong** [comment]
Thanks
