### ISSUE TITLE
Use argocd to create an application and propagate it through karmada, the application status has been in processing status

### ISSUE THREAD

**Issue by nuclearwu** [karmada-io/karmada#2457]
**Please provide an in-depth description of the question you have**:
After using argocd to create an application and distribute it through karmada, the deployment status is normal, and the member cluster pod is also started normally, but the application status always shows processing.
![image](https://user-images.githubusercontent.com/37976659/187812245-d5374c97-96e0-4218-bb60-3b387b5fe82a.png)
![image](https://user-images.githubusercontent.com/37976659/187812341-19fbfab5-f9a8-4057-a598-0e42865902e8.png)
![image](https://user-images.githubusercontent.com/37976659/187813545-d6c0e9c1-8609-4607-b64e-5dcd294e1840.png)
![image](https://user-images.githubusercontent.com/37976659/187812878-90049b24-3d24-4149-aec9-95e2a86ced9a.png)
![image](https://user-images.githubusercontent.com/37976659/187812289-fa661426-95f3-4d2a-b8c4-918781306779.png)

**What do you think about this question?**:

**Environment**:
- Karmada version: 1.2.1
- Kubernetes version: 1.21.5
- Others:

**Comment by RainbowMango** [comment]
> the application status always shows processing.

I guess this is the bug that we've fixed by #2256. The path is included in [release v1.2.2](https://github.com/karmada-io/karmada/releases/tag/v1.2.2), as well as in [release v1.3.0](https://github.com/karmada-io/karmada/releases/tag/v1.3.0).

Since you are using v1.2.1, I suggest you upgrade to v1.2.2.

**Comment by nuclearwu** [comment]
> > the application status always shows processing.
> 
> I guess this is the bug that we've fixed by #2256. The path is included in [release v1.2.2](https://github.com/karmada-io/karmada/releases/tag/v1.2.2), as well as in [release v1.3.0](https://github.com/karmada-io/karmada/releases/tag/v1.3.0).
> 
> Since you are using v1.2.1, I suggest you upgrade to v1.2.2.

Thanks, I'll try the updated version
