### ISSUE TITLE
Verify kyverno revert kubeconfig flag

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2459]
**What would you like to be added**:
> Note: the following task requires Kyverno [release-1.8 comes out](https://github.com/kyverno/kyverno/releases/tag/v1.8.0).

- [ ] verify if Kyverno works as expected as per [Working with Kyverno](https://karmada.io/docs/userguide/security-governance/working-with-kyverno).
- [ ] Reform the docs and note that release-1.7 does not work for Karmada.

**Why is this needed**:
The --kubeconfig flag was deleted by Kyverno at release-1.7(by https://github.com/kyverno/kyverno/pull/3744 and https://github.com/kyverno/kyverno/pull/3802), that lead to Karmada can't use it, the issue is addressed by https://github.com/karmada-io/karmada/issues/2279.

Now Kyverno has reverted the change(see, https://github.com/kyverno/kyverno/pull/4308), and removed `--kubeconfig` flag will come back to the coming release-1.8. 

Thanks @hackerboy01 report and push this issue to both Karmada and Kyverno communities.

**Comment by RainbowMango** [comment]
Just a reminder, the Kyverno just released [v1.18.0](https://github.com/kyverno/kyverno/releases/tag/v1.8.0).

**Comment by Poor12** [comment]
I have tested Kyverno 1.8.0. It works well. I'll update the doc soon.

**Comment by hackerboy01** [comment]
> I have tested Kyverno 1.8.0. It works well. I'll update the doc soon.
Yes,  Kyverno 1.8.1 has been running in our production environment for a month.
