### ISSUE TITLE
Add cluster annotation to proxying objects

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#2463]
**What would you like to be added**:
When users read objects via proxy, add annotation `resource.karmada.io/cached-from-cluster` to objects.
Stay the same with search:
https://github.com/karmada-io/karmada/blob/d4da468dc301147977b4c44651482761795cf05d/pkg/registry/search/storage/cache.go#L114

**Why is this needed**:
Stay the same with search.

**question**
When user update objects, this annotation will be added in member clusters.

**Comment by ikaven1024** [comment]
cc @XiShanYongYe-Chang what do you think about it.

**Comment by ikaven1024** [comment]
> When user update objects, this annotation will be added in member clusters.

cc @XiShanYongYe-Chang what do you think about it.

**Comment by RainbowMango** [comment]
Do you mean there is no such annotation for resources returned by proxy?
Sounds good to me if it is the case.

**Comment by ikaven1024** [comment]
> Do you mean there is no such annotation for resources returned by proxy?

Yes, this annotation is not added in proxy now.

But when add it. Users will get objects with this annotation. while updating, this annotation will be updated to member clusters. It maybe a hack to member clusters.

**Comment by XiShanYongYe-Chang** [comment]
> But when add it. Users will get objects with this annotation. while updating, this annotation will be updated to member clusters. It maybe a hack to member clusters.

Can we filter it out when updating? It would be best if there was no additional impact on the resources in the cluster.

**Comment by ikaven1024** [comment]
> Can we filter it out when updating?

But what if this really exist in member cluster?

**Comment by XiShanYongYe-Chang** [comment]
Are you referring to the annotation whose key is `resource.karmada.io/cached-from-cluster`? 

This key is used only on the Karmada control plane. I think it is unnecessary for member clusters to use this key annotation. If there is a misuse, it can be troublesome.

**Comment by ikaven1024** [comment]
Get it. I will try it.

/assign

**Comment by XiShanYongYe-Chang** [comment]
@ikaven1024 Thanks!
