### ISSUE TITLE
Contribute custom health check for RB/CRB 

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2464]
**What would you like to be added**:
Contribute health checks for [ResourceBinding](https://github.com/karmada-io/karmada/blob/74dab4429603eacae715569a9cf2786cff4d9364/pkg/apis/work/v1alpha2/binding_types.go#L40) and [ClusterResourceBinding](https://github.com/karmada-io/karmada/blob/74dab4429603eacae715569a9cf2786cff4d9364/pkg/apis/work/v1alpha2/binding_types.go#L309) API to the [ArgoCD project](https://github.com/argoproj/argo-cd).

Please refer to [Contribute a Custom Health Check](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#way-2-contribute-a-custom-health-check).

For how to check if RB is in healthy status, I draft a function in Go which would help when translating to Lua:
```golang
func Healthy(binding *workv1alpha2.ResourceBinding) bool {
	// The ResourceBinding hasn't been resolved by scheduler or
	// failed to find appropriate target cluster.
	if len(binding.Spec.Clusters) == 0 {
		return false
	}

	// current resource status is insufficient
	if len(binding.Spec.Clusters) < len(binding.Status.AggregatedStatus) {
		return false
	}

	for _, status := range binding.Status.AggregatedStatus {
		switch status.Health {
		case workv1alpha2.ResourceUnhealthy:
			return false
		// If Karmada can't assess the healthy, we think it's healthy
		// as long as it has been applied to member cluster.
		case workv1alpha2.ResourceUnknown:
			if !status.Applied {
				return false
			}
		}
	}

	return true
}
```

The iterated tasks:
- [x] contribute the health checks to ArgoCD project (@chaunceyjiang, https://github.com/argoproj/argo-cd/pull/11192)
- [ ] revise the [documents for Karmada](https://karmada.io/docs/userguide/cicd/working-with-argocd)

**Why is this needed**:
For now, when distributing application by ArgoCD, there is no health label for RB/CRB resources, (see the picture at [here](https://karmada.io/docs/userguide/cicd/working-with-argocd#checking-apps-status)). That is because ArgoCD can't assess health for CRD resources.

We introduced a [Health](https://github.com/karmada-io/karmada/blob/74dab4429603eacae715569a9cf2786cff4d9364/pkg/apis/work/v1alpha2/binding_types.go#L259) field to RB/CRB API, this makes possible for us to assess health status.

**Comment by chaunceyjiang** [comment]
Friendly ping @carlory  Any progress？ If you don't have time, I can help 😊

**Comment by carlory** [comment]
you can pick up it.

/assign @chaunceyjiang 

/unassign

**Comment by RainbowMango** [comment]
Thanks @chaunceyjiang.

**Comment by RainbowMango** [comment]
Thanks @chaunceyjiang
