### ISSUE TITLE
Derived service can not found endpointSilces

### ISSUE THREAD

**Issue by zanghao2** [karmada-io/karmada#2473]
**Please provide an in-depth description of the question you have**:
I follow https://karmada.io/docs/userguide/service/multi-cluster-service/ this doc to deploy service between multi cluster.
When i finish i can not found endpointSlices from member1. The error from karmada controller is error: informer for discovery.k8s.io/v1, Resource=endpointsilces hasn't synced.
**What do you think about this question?**:
I found in my cluster, the endpointslice api version is v1alpha1, I want to know is karmada has endpointslices v1alhpa1?
**Environment**:
- Karmada version:  0.10.0
- Kubernetes version:  1.20.0
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @zanghao2, currently, the endpointslices version used in karmada version is v1.
