### ISSUE TITLE
access subCluster resources by the aggragate-apiserver failed

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#2480]
here is my subClusters joined under karmada:
controller-0:~/shen/karmada-aggregate$ kubectl get cluster
**NAME    VERSION   MODE   READY   AGE
k8s01   v1.20.5   Push   True    4h49m
k8s02   v1.20.5   Push   True    4h49m**

and here is the **rbac.yaml** which grant admin permission:

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-proxy-clusterrole
rules:
- apiGroups:
  - 'cluster.karmada.io'
  resources:
  - clusters/proxy
  resourceNames:
  - k8s01
  - k8s02
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-proxy-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-proxy-clusterrole
subjects:
  - kind: User
    name: "system:admin"

but finally i access resources in subcluster failed:
kubectl get --raw /apis/cluster.karmada.io/v1alpha1/clusters/k8s02/proxy/api/v1/nodes --kubeconfig=karmada-apiserver.config

**Error from server: failed to get impresonateToken for cluster k8s02: the impersonatorSecretRef of cluster k8s02 is nil**

how can solve this problem?

**Comment by XiShanYongYe-Chang** [comment]
Hi @SZT0728, which Karmada and karmadactl versions do you use? Maybe you need to use the same version for them.

We will collect `impersonatorSecret` for every joined cluster, such as:

```shell
# kubectl --context karmada-apiserver -n karmada-cluster get secret
NAME                   TYPE     DATA   AGE
member1                Opaque   2      118s
member1-impersonator   Opaque   1      118s
member2                Opaque   2      114s
member2-impersonator   Opaque   1      114s
member3                Opaque   2      103s
member3-impersonator   Opaque   1      103s
```

**Comment by SZT0728** [comment]
> Hi @SZT0728, which Karmada and karmadactl versions do you use? Maybe you need to use the same version for them.
> 
> We will collect `impersonatorSecret` for every joined cluster, such as:
> 
> ```shell
> # kubectl --context karmada-apiserver -n karmada-cluster get secret
> NAME                   TYPE     DATA   AGE
> member1                Opaque   2      118s
> member1-impersonator   Opaque   1      118s
> member2                Opaque   2      114s
> member2-impersonator   Opaque   1      114s
> member3                Opaque   2      103s
> member3-impersonator   Opaque   1      103s
> ```

both Karmada and karmadactl version are v1.2.0

when i join cluster i indicate the cluster-namespace  like `karmada-es-k8s01`. 
``` shell
# kubectl get secret -n  karmada-es-k8s01
NAME                 TYPE     DATA   AGE
k8s01                Opaque   2      5m39s
k8s01-impersonator   Opaque   1      5m39s
```
and i access subcluster resources and get the error as belong:

``` shell
# kubectl get --raw /apis/cluster.karmada.io/v1alpha1/clusters/k8s01/proxy/api/v1/nodes --kubeconfig=karmada-apiserver.config

Error from server (Forbidden): users "system:admin" is forbidden: User "system:serviceaccount:karmada-es-k8s01:karmada-impersonator" cannot impersonate resource "users" in API group "" at the cluster scope
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @SZT0728, do you specify the namespace by the flag `--cluster-namespace`? 

Currently, if other namespaces are specified(besides `karmada-cluster`), the unified authentication function may be unavailable. Currently, `karmada-cluster/karmada-impersonator` is used to grant permissions to users in the member cluster:

https://github.com/karmada-io/karmada/blob/665af6916a733da4cae2ce1dfb9321c264f114ff/pkg/controllers/unifiedauth/unified_auth_controller.go#L159-L163

We need to modify it to be configurable. I am sorry for that, we will implement this configurable function as soon as possible.

Also, I'd like to say that the prefixed with `karmada-es-` are namespaces reserved for each cluster and are not appropriate to set up as ns for the cluster key store.

**Comment by SZT0728** [comment]
> 
 now the subCluster joined by call the golang api function as below:
```golang
joinOpt := karmadactl.CommandJoinOption{
		ClusterNamespace: options.DefaultKarmadaClusterNamespace,
		ClusterName:      req.UserClusterName,
	}
	err = karmadactl.JoinCluster(internal_karmada.Client.GetKarmadaConfig(), restConfig, joinOpt)
```
and it's work well ~ thanks

**Comment by XiShanYongYe-Chang** [comment]
Hi @SZT0728, Let us use #2495 to track the problem we found in the issue.

I will close this issue first, when you encounter a new problem related to this, you can reopen it at any time, thanks.

/assign
