### ISSUE TITLE
use karmadactl init failed and reports `nodePort of karmada apiserver 32443 already exist`

### ISSUE THREAD

**Issue by cleverhu** [karmada-io/karmada#2492]
**What happened**:
When I use karmadactl to init control-plane, but the image 'docker.io/alpine:3.15.1' can't be pulled, when I try to use `karmadactl init` init again, it failed and reports `error: nodePort of karmada apiserver 32443 already exist`

**What you expected to happen**:
I can use karmadactl init repeated and can be successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:`karmadactl version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:22Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}`
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by lonelyCZ** [comment]
Right, that's always been a problem, If the process is failed, we only can firstly execute `karmadactl deinit`, and init again.


 Welcome! Thanks for your contribution, I will look it ASAP.

**Comment by cleverhu** [comment]
The e2e of the pr is failed for 1.24.2, can you help me to retrigger it?

**Comment by RainbowMango** [comment]
> The e2e of the pr is failed for 1.24.2, can you help me to retrigger it?

Done.

**Comment by cleverhu** [comment]
This might result a new error: 
```
F0916 00:58:36.620899   52602 deploy.go:55] Post "https://10.130.59.18:32443/api/v1/namespaces": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "karmada")
```
There I closed the issue.
