### ISSUE TITLE
E2E failed for 1.24.2

### ISSUE THREAD

**Issue by cleverhu** [karmada-io/karmada#2499]
**What happened**:
E2E failed for 1.24.2 for the last case.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/51436614/189317078-104e4e10-d6f5-4678-af4d-7c3932bd1a90.png">

**What you expected to happen**:
It should be successful.

**How to reproduce it (as minimally and precisely as possible)**:
Pull a request

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by cleverhu** [comment]
It should be enhancement, I select the wrong label, could anyone help me to relabel or close the issue.

**Comment by XiShanYongYe-Chang** [comment]
Hi @cleverhu , I noticed this CI failing, and pull a request #2498 to fix it
/kind flake
/remove kind-bug
/assign
