### ISSUE TITLE
init failed and report `namespaces "karmada-system" already exists`

### ISSUE THREAD

**Issue by cleverhu** [karmada-io/karmada#2504]
**What happened**:
I install karmada controller-plane by `karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers` , before execute this, I have tried `karmadactl deinit`.
The log of install is:
```
 karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers  [13:36:11 09/11]
I0911 13:36:41.544986 3505120 deploy.go:145] kubeconfig file: /root/.kube/config, kubernetes: https://139.198.167.220:6443
W0911 13:36:41.986808 3505120 node.go:30] the kubernetes cluster does not have a Master role.
I0911 13:36:41.986827 3505120 node.go:38] randomly select 3 Node IPs in the kubernetes cluster.
I0911 13:36:42.080548 3505120 deploy.go:165] karmada apiserver ip: [10.130.59.18 10.130.58.25]
I0911 13:36:42.770834 3505120 cert.go:229] Generate ca certificate success.
I0911 13:36:42.951945 3505120 cert.go:229] Generate karmada certificate success.
I0911 13:36:43.031271 3505120 cert.go:229] Generate apiserver certificate success.
I0911 13:36:43.118985 3505120 cert.go:229] Generate front-proxy-ca certificate success.
I0911 13:36:43.393367 3505120 cert.go:229] Generate front-proxy-client certificate success.
I0911 13:36:43.571701 3505120 cert.go:229] Generate etcd-ca certificate success.
I0911 13:36:43.798231 3505120 cert.go:229] Generate etcd-server certificate success.
I0911 13:36:43.966271 3505120 cert.go:229] Generate etcd-client certificate success.
I0911 13:36:43.966398 3505120 deploy.go:251] download crds file name: /etc/karmada/crds.tar.gz
Downloading...[ 100.00% ]
Downloading...[ 100.00% ]
Download complete.I0911 13:36:45.129184 3505120 deploy.go:441] Create karmada kubeconfig success.
I0911 13:36:45.201297 3505120 namespace.go:36] Create Namespace 'karmada-system' successfully.
I0911 13:36:45.267352 3505120 rbac.go:60] CreateClusterRole karmada-controller-manager success.
I0911 13:36:45.304952 3505120 rbac.go:81] CreateClusterRoleBinding karmada-controller-manager success.
I0911 13:36:45.446397 3505120 secret.go:78] secret kubeconfig Create successfully.
I0911 13:36:45.645377 3505120 secret.go:78] secret etcd-cert Create successfully.
I0911 13:36:46.334288 3505120 secret.go:78] secret karmada-cert Create successfully.
I0911 13:36:46.585324 3505120 secret.go:78] secret karmada-webhook-cert Create successfully.
I0911 13:36:46.735304 3505120 services.go:66] service etcd create successfully.
I0911 13:36:46.735325 3505120 deploy.go:316] create etcd StatefulSets
I0911 13:36:47.033344 3505120 check.go:98] etcd desired replicaset is 1, currently: 1
I0911 13:36:50.088561 3505120 check.go:49] pod: etcd-0 is ready. status: Running
I0911 13:36:50.088591 3505120 deploy.go:327] create karmada ApiServer Deployment
I0911 13:36:50.109394 3505120 services.go:66] service karmada-apiserver create successfully.
W0911 13:36:53.258975 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:54.279705 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:55.282321 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:56.279460 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:57.279178 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:58.280250 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:36:59.279784 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:00.279771 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:01.279843 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:02.279994 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:03.279330 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:04.279959 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:05.281172 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:06.281214 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:07.279962 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:08.282896 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:09.280201 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:10.279884 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:11.296561 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:12.280035 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:13.279739 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:14.327825 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:15.279376 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:16.280166 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:17.282564 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:18.280128 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:19.280047 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
W0911 13:37:20.279926 3505120 check.go:52] pod: karmada-apiserver-7c575bf6d5-sl54z not ready. status: Running
I0911 13:37:21.279513 3505120 check.go:49] pod: karmada-apiserver-7c575bf6d5-sl54z is ready. status: Running
I0911 13:37:21.279544 3505120 deploy.go:340] create karmada aggregated apiserver Deployment
I0911 13:37:21.297513 3505120 services.go:66] service karmada-aggregated-apiserver create successfully.
I0911 13:37:24.405758 3505120 check.go:49] pod: karmada-aggregated-apiserver-7c8db9d89b-8f7lq is ready. status: Running
F0911 13:37:24.415798 3505120 deploy.go:55] namespaces "karmada-system" already exists
```
and the created resource is :
```
kubectl get pod -nkarmada-system
NAME                                            READY   STATUS    RESTARTS   AGE
etcd-0                                          1/1     Running   0          65s
karmada-aggregated-apiserver-7c8db9d89b-8f7lq   1/1     Running   0          30s
karmada-apiserver-7c575bf6d5-sl54z              1/1     Running   0          61s
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
`karmadactl version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:22Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}`
- Others:

**Comment by cleverhu** [comment]
I found the namespace has been created before `InitKarmadaResources` in `i.CreateNamespace()`. And I tried `init` twice, It reported the same error. So the bug might be `inevitable`.

**Comment by RainbowMango** [comment]
Hi @cleverhu 
Could you please tell us how to reproduce this issue in detail?
I remember `karmada init` works after `karmada deinit`. Yeah, I didn't try on v1.3.0.

**Comment by cleverhu** [comment]
> Hi @cleverhu Could you please tell us how to reproduce this issue in detail? I remember `karmada init` works after `karmada deinit`. Yeah, I didn't try on v1.3.0.

My karmadactl version is `karmadactl version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:22Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}`, you can execute ` karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers` to start control-plane. Then execute `karmadactl deinit`. Then execute ` karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers`, you will find it reproduced again and it might inevitable. The way to solve it is to delete the etcd data which seems not so friendly.

**Comment by cleverhu** [comment]
If you execute `karmadactl init` twice and will find the error of `error: nodePort of karmada apiserver 32443 already exist` reported and I also pull a request to fix it.

**Comment by RainbowMango** [comment]
> The way to solve it is to delete the etcd data which seems not so friendly.

which way we are talking about?

**Comment by cleverhu** [comment]
> > The way to solve it is to delete the etcd data which seems not so friendly.
> 
> which way we are talking about?

The content of this pr fix is that the `deinit` execute uninstall cleanly which results in only excute rm `etcd data` , we can install successfully again.

**Comment by RainbowMango** [comment]
Thanks @cleverhu. I reproduced it on my side.


```
-bash-4.2# karmadactl version
karmadactl version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:22Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

First-time installation, it works fine.
```
-bash-4.2# karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers
```

```
-bash-4.2# kubectl get pods -n karmada-system 
NAME                                            READY   STATUS    RESTARTS   AGE
etcd-0                                          1/1     Running   0          109s
karmada-aggregated-apiserver-7c8db9d89b-s54fj   1/1     Running   0          60s
karmada-apiserver-7c575bf6d5-6twrn              1/1     Running   0          91s
karmada-controller-manager-8478c5458d-cfvk4     1/1     Running   0          44s
karmada-scheduler-56f47db5cf-xp65r              1/1     Running   0          47s
karmada-webhook-5bf5549fdf-lpz8k                1/1     Running   0          41s
kube-controller-manager-797675c9cc-tfkcg        1/1     Running   0          53s
```

```
-bash-4.2# karmadactl deinit
...
remove Karmada from Kubernetes successfully.

deinit will not delete etcd data, if the etcd data is persistent, please delete it yourself.
```

And after de-init, the namespace `karmada-system` has been cleaned up too.
```
-bash-4.2# kubectl get ns 
NAME                 STATUS   AGE
default              Active   5m5s
kube-node-lease      Active   5m6s
kube-public          Active   5m6s
kube-system          Active   5m6s
local-path-storage   Active   5m1s
```

Then, the error raised when re-initing:
```
-bash-4.2# karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers
I0915 14:48:20.233237 2376707 services.go:66] service karmada-aggregated-apiserver create successfully.
I0915 14:48:23.245748 2376707 check.go:49] pod: karmada-aggregated-apiserver-7c8db9d89b-zmjwk is ready. status: Running
F0915 14:48:23.268025 2376707 deploy.go:55] namespaces "karmada-system" already exists
```

@cleverhu Do you mean the root cause is `deinit` not cleaning the etcd data?
> deinit will not delete etcd data, if the etcd data is persistent, please delete it yourself.

**Comment by RainbowMango** [comment]
@yy158775 Could you please take a look and try to figure out the root cause?

**Comment by cleverhu** [comment]
> Thanks @cleverhu. I reproduced it on my side.
> 
> 
> 
> 
> 
> ```
> 
> -bash-4.2# karmadactl version
> 
> karmadactl version: version.Info{GitVersion:"v1.3.0", GitCommit:"12e8f01d01571932e6fe45cb7f0d1bffd2e40fd9", GitTreeState:"clean", BuildDate:"2022-08-31T13:09:22Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
> 
> ```
> 
> 
> 
> First-time installation, it works fine.
> 
> ```
> 
> -bash-4.2# karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers
> 
> ```
> 
> 
> 
> ```
> 
> -bash-4.2# kubectl get pods -n karmada-system 
> 
> NAME                                            READY   STATUS    RESTARTS   AGE
> 
> etcd-0                                          1/1     Running   0          109s
> 
> karmada-aggregated-apiserver-7c8db9d89b-s54fj   1/1     Running   0          60s
> 
> karmada-apiserver-7c575bf6d5-6twrn              1/1     Running   0          91s
> 
> karmada-controller-manager-8478c5458d-cfvk4     1/1     Running   0          44s
> 
> karmada-scheduler-56f47db5cf-xp65r              1/1     Running   0          47s
> 
> karmada-webhook-5bf5549fdf-lpz8k                1/1     Running   0          41s
> 
> kube-controller-manager-797675c9cc-tfkcg        1/1     Running   0          53s
> 
> ```
> 
> 
> 
> ```
> 
> -bash-4.2# karmadactl deinit
> 
> ...
> 
> remove Karmada from Kubernetes successfully.
> 
> 
> 
> deinit will not delete etcd data, if the etcd data is persistent, please delete it yourself.
> 
> ```
> 
> 
> 
> And after de-init, the namespace `karmada-system` has been cleaned up too.
> 
> ```
> 
> -bash-4.2# kubectl get ns 
> 
> NAME                 STATUS   AGE
> 
> default              Active   5m5s
> 
> kube-node-lease      Active   5m6s
> 
> kube-public          Active   5m6s
> 
> kube-system          Active   5m6s
> 
> local-path-storage   Active   5m1s
> 
> ```
> 
> 
> 
> Then, the error raised when re-initing:
> 
> ```
> 
> -bash-4.2# karmadactl init --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers
> 
> I0915 14:48:20.233237 2376707 services.go:66] service karmada-aggregated-apiserver create successfully.
> 
> I0915 14:48:23.245748 2376707 check.go:49] pod: karmada-aggregated-apiserver-7c8db9d89b-zmjwk is ready. status: Running
> 
> F0915 14:48:23.268025 2376707 deploy.go:55] namespaces "karmada-system" already exists
> 
> ```
> 
> 
> 
> @cleverhu Do you mean the root cause is `deinit` not cleaning the etcd data?
> 
> > deinit will not delete etcd data, if the etcd data is persistent, please delete it yourself.
> 
> 
> 
> 

Yes

**Comment by cleverhu** [comment]
The other pr that service port exists is for local cluster.The issue likes more a virtual cluster bug.

**Comment by yy158775** [comment]
I agree with @cleverhu, the default cause is that etcd data is persistent on the host.
```
  - hostPath:
      path: /var/lib/karmada-etcd
      type: DirectoryOrCreate
    name: etcd-data
```
So once deinit and init again,namespace karmada-system has existed in context karmada-apisever.

But when I use v1.2.1 karmadactl,it doestn't has such problem.I find this issue https://github.com/karmada-io/karmada/pull/2191 change the parameter "etcd-storage-mode" to hostPath. So this problem occur in the later version.

**Comment by yy158775** [comment]
I think we don't need to create namespace karmada-system in karmada-apiserver when using the existed etcd data. But we need to think how to classify these two scenarios,using existed etcd data or create new ectd data storage.

**Comment by RainbowMango** [comment]
> But when I use v1.2.1 karmadactl,it doestn't has such problem.I find this PR https://github.com/karmada-io/karmada/pull/2191 changes the parameter "etcd-storage-mode" to hostPath. So this problem occur in the later version.

Yeah, I remember it works in previous version. Thanks for pointing it out, maybe we need to pick this patch for release-1.3.

**Comment by cleverhu** [comment]
> I found the namespace has been created before `InitKarmadaResources` in `i.CreateNamespace()`. And I tried `init` twice, It reported the same error. So the bug might be `inevitable`.

I'm wrong at first, the cause for it is `InitKarmadaResources` which connects to the `controler-plane` and the resources exists in the `etcd`. Not caused by `i.CreateNamespace()`. The funcs of them operates differents resources in 
```
// CreateNamespace namespace IfNotExist
func (i *CommandInitOption) CreateNamespace() error {
	namespaceClient := i.KubeClientSet.CoreV1().Namespaces()
	_, err := namespaceClient.Get(context.TODO(), i.Namespace, metav1.GetOptions{})
```
```
func InitKarmadaResources(dir, caBase64, systemNamespace string) error {
	restConfig, err := utils.RestConfig("", filepath.Join(dir, options.KarmadaKubeConfigName))
	if err != nil {
		return err
	}
...
}
```
I'm so sorry that It has caused some misunderstanding. In fact, I have found that it is caused by the etcd data for a long time, but this comment has not been updated. The initial wrong comment is wrong.

**Comment by XiShanYongYe-Chang** [comment]
Hi @cleverhu, looks like you've solved the problem. Congratulations.
Let's close this first, if you have a related problem again, you can reopen it at any time.
/close
/kind question
