### ISSUE TITLE
run hack/local-up-karmada.sh with environment CHINA_MAINLAND=true fail: sed: can't read : No such file or directory

### ISSUE THREAD

**Issue by ikaven1024** [karmada-io/karmada#2521]
**Task description**:
```bash
$ export CHINA_MAINLAND=true
$ hack/local-up-karmada.sh
sed: can't read : No such file or directory
```

**Solution**:

`sed -i ''` is invalid on GNU sed, change it to `sed -i''` (delete space after -i)

```diff
diff --git a/hack/util.sh b/hack/util.sh
index 14c6ba01..238be503 100755
--- a/hack/util.sh
+++ b/hack/util.sh
@@ -681,7 +681,7 @@ function util::set_mirror_registry_for_china_mainland() {
     "cluster/images/buildx.Dockerfile"
   )
   for dockerfile in "${dockerfile_list[@]}"; do
-    grep 'mirrors.ustc.edu.cn' ${repo_root}/${dockerfile} > /dev/null || sed -i '' -e "1a\\
+    grep 'mirrors.ustc.edu.cn' ${repo_root}/${dockerfile} > /dev/null || sed -i'' -e "1a\\
 RUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.15/main/ > /etc/apk/repositories" ${repo_root}/${dockerfile}
   done
 }
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
> sed -i '' is invalid on GNU sed, change it to sed -i'' (delete space after -i)

Does this change also work on Mac OS?  I remember something different between Linux and Mac.

**Comment by ikaven1024** [comment]
> Does this change also work on Mac OS?

Yes, for Mac OS, both `sed -i ''` and `sed -i''` are OK.

**Comment by rahul3002** [comment]
hey I'm new here i would like to contribute to this issue

**Comment by mrningyang** [comment]
> hey I'm new here i would like to contribute to this issue

sorry，this task has been assigned to me，you can look at other tasks，thanks
