### ISSUE TITLE
Karmada init failed when k8s master (node) IP can not be connected by karmadactl

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2537]
**What happened**:
Karmadactl init failed when k8s master (node) IP can not be connected by karmadactl but karmadactl can connected to the host cluster with kubeconfig
**What you expected to happen**:
Karmadactl init succeed when k8s master (node) IP can not be connected by karmadactl but karmadactl can  connected the host cluster with kubeconfig

**How to reproduce it (as minimally and precisely as possible)**:
1、karmadactl init 
**Anything else we need to know?**:
1、Karmadactl can connected the host cluster with kubeconfig. The kubeconfig host IP may be slb、proxy ip or Management IP 
2、The host cluster master （node）IP got from api server are internal IP or Service IP that can not directly connected from karmadactl  

 @RainbowMango  @lonelyCZ @prodanlabs
**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by wuyingjun-lucky** [comment]
Can we generate the karmada apiserver ip by the host cluster api server host and karmada apiserver port ? 
It now use the host cluster master | node ip.

**Comment by wuyingjun-lucky** [comment]
sudo ./kubectl-karmada init --kube-image-mirror-country=cn
I0919 16:32:45.966506     400 deploy.go:145] kubeconfig file: /Users/wuyingjun/.kube/config, kubernetes: https://kubernetes.docker.internal:6443
I0919 16:32:45.996183     400 deploy.go:165] karmada apiserver ip: [192.168.65.4]
I0919 16:32:47.873043     400 cert.go:229] Generate ca certificate success.
I0919 16:32:47.947931     400 cert.go:229] Generate karmada certificate success.
I0919 16:32:48.115205     400 cert.go:229] Generate apiserver certificate success.
I0919 16:32:48.360968     400 cert.go:229] Generate front-proxy-ca certificate success.
I0919 16:32:48.599864     400 cert.go:229] Generate front-proxy-client certificate success.
I0919 16:32:48.676908     400 cert.go:229] Generate etcd-ca certificate success.
I0919 16:32:48.775063     400 cert.go:229] Generate etcd-server certificate success.
I0919 16:32:48.931648     400 cert.go:229] Generate etcd-client certificate success.
I0919 16:32:48.931964     400 deploy.go:251] download crds file name: /etc/karmada/crds.tar.gz
Downloading...[ 100.00% ]
Downloading...[ 100.00% ]
Download complete.I0919 16:32:51.349507     400 deploy.go:497] Create karmada kubeconfig success.
I0919 16:32:51.362657     400 namespace.go:36] Create Namespace 'karmada-system' successfully.
I0919 16:32:51.394290     400 rbac.go:60] CreateClusterRole karmada-controller-manager success.
I0919 16:32:51.403838     400 rbac.go:81] CreateClusterRoleBinding karmada-controller-manager success.
I0919 16:32:51.413334     400 secret.go:78] secret kubeconfig Create successfully.
I0919 16:32:51.754855     400 secret.go:78] secret etcd-cert Create successfully.
I0919 16:32:52.155429     400 secret.go:78] secret karmada-cert Create successfully.
I0919 16:32:52.555356     400 secret.go:78] secret karmada-webhook-cert Create successfully.
I0919 16:32:52.955821     400 services.go:66] service etcd create successfully.
I0919 16:32:52.955849     400 deploy.go:316] create etcd StatefulSets
I0919 16:32:53.153970     400 check.go:98] etcd desired replicaset is 1, currently: 1
I0919 16:32:56.161570     400 check.go:49] pod: etcd-0 is ready. status: Running
I0919 16:32:56.161589     400 deploy.go:327] create karmada ApiServer Deployment
I0919 16:32:56.171504     400 services.go:66] service karmada-apiserver create successfully.
W0919 16:32:59.188714     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:00.192295     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:01.193401     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:02.193162     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:03.192810     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:04.194039     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:05.194100     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:06.193905     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:07.194434     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:08.195602     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:09.193413     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:10.192946     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:11.193887     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:12.193042     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:13.193748     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:14.194548     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:15.193291     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:16.195476     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:17.192778     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:18.193483     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:19.195440     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:20.194486     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:21.193755     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:22.194004     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:23.192943     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:24.193559     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:25.196545     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
W0919 16:33:26.194572     400 check.go:52] pod: karmada-apiserver-7cb58cf678-5kqjb not ready. status: Running
I0919 16:33:27.193831     400 check.go:49] pod: karmada-apiserver-7cb58cf678-5kqjb is ready. status: Running
I0919 16:33:27.193855     400 deploy.go:340] create karmada aggregated apiserver Deployment
I0919 16:33:27.205146     400 services.go:66] service karmada-aggregated-apiserver create successfully.
I0919 16:33:30.219331     400 check.go:49] pod: karmada-aggregated-apiserver-6b7f866dd6-q6292 is ready. status: Running
F0919 16:34:00.221464     400 deploy.go:55] Post "https://192.168.65.4:32443/api/v1/namespaces": dial tcp 192.168.65.4:32443: i/o timeout

**Comment by wuyingjun-lucky** [comment]
host cluster config host
```
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
```

**Comment by wuyingjun-lucky** [comment]
```
kubectl get nodes -o wide
NAME             STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION     CONTAINER-RUNTIME
docker-desktop   Ready    control-plane,master   21d   v1.22.5   192.168.65.4   <none>        Docker Desktop   5.10.76-linuxkit   docker://20.10.12
```

**Comment by lonelyCZ** [comment]
Yes, currently karmadactl directly use the `NodePort` service mode to export `karmada-apiserver`, we may need to provide a custom way.

**Comment by RainbowMango** [comment]
I guess you mean, now we get the node addresses as the `karmada-apiserver` address:
https://github.com/karmada-io/karmada/blob/d81f0ff97c5fa98f3e976268d63ef5cd7e53dc2c/pkg/karmadactl/cmdinit/kubernetes/node.go#L44-L49

> Can we generate the karmada apiserver ip by the host cluster api server host and karmada apiserver port or given a flag to set karmada apiserver IP?

I'm not sure. Just a reminder, we need to access the karmada-apiserver during the installation process, the provided `host` IP should be accessible by karmadactl.

**Comment by wuyingjun-lucky** [comment]
> I guess you mean, now we get the node addresses as the `karmada-apiserver` address:
> 
> https://github.com/karmada-io/karmada/blob/d81f0ff97c5fa98f3e976268d63ef5cd7e53dc2c/pkg/karmadactl/cmdinit/kubernetes/node.go#L44-L49
> 
> > Can we generate the karmada apiserver ip by the host cluster api server host and karmada apiserver port or given a flag to set karmada apiserver IP?
> 
> I'm not sure. Just a reminder, we need to access the karmada-apiserver during the installation process, the provided `host` IP should be accessible by karmadactl.

Yes
The `karmadactl` can access the one of the host ip in our environment we call it `管理IP` in chinese. But the karmadactl finally use the node ip that named `业务IP` and was not accessible by karmadactl to generate karmada config.
And other secene was  that we use proxy ip or lb ip to access host cluster.

**Comment by RainbowMango** [comment]
I get it.
I see there is a `--apiserver-advertise-address` in `kubeadm init`, can we introduce a similar flag?
```
# kubeadm init --help
      --apiserver-advertise-address string   The IP address the API Server will advertise it's listening on. If not set the default network interface will be used.

```

**Comment by wuyingjun-lucky** [comment]
> I get it. I see there is a `--apiserver-advertise-address` in `kubeadm init`, can we introduce a similar flag?
> 
> ```
> # kubeadm init --help
>       --apiserver-advertise-address string   The IP address the API Server will advertise it's listening on. If not set the default network interface will be used.
> ```

Actually I resolve it by this similar way

**Comment by RainbowMango** [comment]
@wuyingjun-lucky You can get the command usage from [here](https://prow.k8s.io/command-help?repo=kubernetes%2Fkubernetes).

/remove-kind bug
