### ISSUE TITLE
run hack/local-up-karmada.sh behind an HTTP proxy

### ISSUE THREAD

**Issue by loicalbertin** [karmada-io/karmada#2553]
:wave: Hi all!

I'm evaluating Karmada in an environment that access to the internet through an HTTP proxy.

When running `hack/local-up-karmada.sh` I'm facing an error when building docker images. Basically `apk add` fails when trying to download packages.

To workaround this I added a `DOCKER_BUILD_ARGS` variable to [`hack/docker.sh`](https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/hack/docker.sh#L57)

```bash
  docker build --build-arg BINARY="${target}" \
          ${DOCKER_BUILD_ARGS} \                # <<<< ADDED THIS LINE
          --tag "${image_name}" \
          --file "${REPO_ROOT}/cluster/images/Dockerfile" \
          "${REPO_ROOT}/_output/bin/${platform}"
```

And I now run the `hack/local-up-karmada.sh` this way:

```bash
DOCKER_BUILD_ARGS="--build-arg https_proxy=${https_proxy}" hack/local-up-karmada.sh
```

Is there a better way to work with proxies?

Thanks & have a nice day!
Loïc

**Comment by RainbowMango** [comment]
Maybe we can pass the variable from Makefile to `hack/docker.sh`.
https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/Makefile#L72
and 
https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/Makefile#L91

**Comment by RainbowMango** [comment]
@ikaven1024 How do you say?
It is the first I've heard that build images behind a proxy. I'm not sure if it is a common case.

**Comment by loicalbertin** [comment]
> Maybe we can pass the variable from Makefile to `hack/docker.sh`.
> 
> https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/Makefile#L72
> 
> 
> and
> https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/Makefile#L91

Well, actually env vars are already automatically passed through the Makefile, no changes needed here.

**Comment by loicalbertin** [comment]
> @ikaven1024 How do you say? It is the first I've heard that build images behind a proxy. I'm not sure if it is a common case.

Well it's a quite common (and painful) case when working on premises in companies that forbid direct access to internet.

**Comment by RainbowMango** [comment]
> Well, actually env vars are already automatically passed through the Makefile, no changes needed here.

You are right. But all environment variables now are passed from Makefile, I guess it(define a variable in Makefile) would be better to customize the values when they run `make` commands.

Similarly, since we are using `hack/local-up-karmada.sh`, should we introduce variables to the script as well?
The variable passed path would be `hack/local-up-karmada.sh` --> `Makefile` --> `hack/docker.sh`.

After that, you can find all variables at [the head of `local-up-karmada.sh`](https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/hack/local-up-karmada.sh#L16-L24), and don't need to care what scripts it depends on.

**Comment by loicalbertin** [comment]
Ok thanks for the clarification.
So the question is: does it worth to expose this new variable for this usecase?

**Comment by RainbowMango** [comment]
I don't know much about the `--build-arg` before, but after I went through the [documents](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg),
I think it's reasonable. Would you like to send a PR for this? I think the new variable should be empty.

**Comment by ikaven1024** [comment]
Yes, we should add the build args to these two places:

https://github.com/karmada-io/karmada/blob/48d9ed11a1f7b36a473a1979fe9b9dfc9cb80aca/hack/docker.sh#L57-L60

https://github.com/karmada-io/karmada/blob/48d9ed11a1f7b36a473a1979fe9b9dfc9cb80aca/hack/docker.sh#L77-L82

**Comment by RainbowMango** [comment]
@ikaven1024 
As I [mentioned above](https://github.com/karmada-io/karmada/issues/2553#issuecomment-1253668305), I think we should add the variable to both `Makefile` and `hack/local-up-karmada.sh` as well, are you ok with that?

**Comment by ikaven1024** [comment]
I prefer NOT add the variable to `Makefile` and `hack/local-up-karmada.sh`, just like we don't expose `GOPROXY` and other variables in underlying scripts.

**Comment by RainbowMango** [comment]
Sounds good to me. We can postpone this(introduce variable to Makefile and hack/local-up-karmada.sh) until we have more evidence. 

So, @loicalbertin, how do you say? Are you willing to send a patch for this?

**Comment by RainbowMango** [comment]
```
  docker build --build-arg BINARY="${target}" \
          ${DOCKER_BUILD_ARGS} \                # <<<< ADDED THIS LINE
          --tag "${image_name}" \
          --file "${REPO_ROOT}/cluster/images/Dockerfile" \
          "${REPO_ROOT}/_output/bin/${platform}"
```
This patch looks good to me, by the way.

**Comment by loicalbertin** [comment]
I would be more than happy to contribute a PR for this.

There is an alternative to consider.
By adding `DOCKER_BUILD_ARGS` variable you will allow arbitrary customization to your build which may be a good or bad thing, I don't known.

An alternative would be to restrict to `--build-arg` and relying on standard `HTTPS_PROXY` env var.
We could do something like this:

```bash
export HTTP_PROXY="${HTTP_PROXY:-${http_proxy:-}"

**Comment by RainbowMango** [comment]
The alternative is great too. 
I'm not sure if the `no_proxy` would disable the `http_proxy`/`https_proxy` or not. 

> By adding DOCKER_BUILD_ARGS variable you will allow arbitrary customization to your build which may be a good or bad thing, I don't known.

No worries, we won't set this variable when releasing, this is just for development.

**Comment by loicalbertin** [comment]
> I'm not sure if the `no_proxy` would disable the `http_proxy`/`https_proxy` or not.

`no_proxy` is used to define exceptions to the proxy settings.

[This blog post](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/) has a great state of the proxy env vars usage today.

In fact it will be up to the underlying program within the container (typically `apk` in this case)  to take them into account. Reading this blog post make me realize that using the lower case version may make more sense (I was Golang-oriented as Go preference goes to the uppercase version).

Anyway, I propose to open 2 PRs with those both alternatives to continue the discussion and let you choose the one you prefer.

**Comment by RainbowMango** [comment]
Thanks @loicalbertin. Both approaches are fantastic! I prefer #2565 a little bit, as it looks clean and straightforward.
