### ISSUE TITLE
[umbrella] UT Supplemental Plan

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#2579]
To improve the reliability of the Karmada project, verify the implementation and usability of functions, and improve user experience, we plan to supplement the UT case. 

We'll list all the tasks in the google execel: https://docs.google.com/spreadsheets/d/1691AczZtovlF8t_UzGjEHCfSde5GHLPsjREGvOpmGDA/edit?hl=zh-cn#gid=0.

You can pick up any tasks you're interested in, thanks all!

> The task list is based on files. We need to improve the code coverage of the current file as much as possible.

> You can also let me know if you think there are some files that need to be added to UT but aren't listed in the task list, thanks~

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang I unpinned this issue, Is there a gate to mark this issue complete?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang I unpinned this issue, Is there a gate to mark this issue complete?

My initial idea was to supplement the UT of the previously identified files https://docs.google.com/spreadsheets/d/1691AczZtovlF8t_UzGjEHCfSde5GHLPsjREGvOpmGDA/edit?hl=zh-cn#gid=0. Considering that we will recently start an [lfx project](https://github.com/karmada-io/karmada/issues/3086) to enhance testing coverage, I think we can close the current issue first.

Since this issue was raised, our coverage rate has increased by [26%](https://app.codecov.io/gh/karmada-io/karmada?search=&trend=6%20months), and now the coverage rate has reached 49%. Thank you for all your contributions.

**Comment by RainbowMango** [comment]
That makes sense to me.

Closing his doesn't means we are not accepting UT contributions anymore.
/close
