### ISSUE TITLE
karmda  controls plane endpoint

### ISSUE THREAD

**Issue by wolgod** [karmada-io/karmada#2588]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
 
Whether karmda controls the endpoints in the ns under the cluster to obtain the endpoint sets of the services managed under the multiple work clusters under managemen？

**Environment**:
- Karmada version:v1.0.2
- Kubernetes version:v1.23.6
- Others:

**Comment by RainbowMango** [comment]
I'm not sure I understand your question correctly.
Do you mean if Karmada collects `endpoints` from member clusters in multi-cluster service scenario?

**Comment by wolgod** [comment]
> I'm not sure I understand your question correctly. Do you mean if Karmada collects `endpoints` from member clusters in multi-cluster service scenario?

yes，This way I can Karmada all the ip's of a service

**Comment by RainbowMango** [comment]
Yes, Karmada collects the `EndpointSlice` (not EndPoints) from the member cluster. [See this controller](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/mcs/endpointslice_controller.go#L35).

**Comment by wolgod** [comment]
i use 1.02 release，when i deploy in the Karmada ns， i can't then EndpointSlice is empty in Karmada，in the member cluster  i can get  EndpointSlice。 Is this feature a new release version? which version i can try？

**Comment by XiShanYongYe-Chang** [comment]
Hi @wolgod, this is made by the MCS(multi-cluster-service) feature, which requires the k8s version 1.21 or later.

**Comment by XiShanYongYe-Chang** [comment]
As lack of activity, close it now, Please feel free to reopen it if you still have the same problem.
/close
