### ISSUE TITLE
istio-ingressgateway 15012 port timeout

### ISSUE THREAD

**Issue by luoMonkeyKing** [karmada-io/karmada#2592]
**What happened**:
When installing istio according to this document [istio](https://github.com/karmada-io/website/blob/main/docs/userguide/service/working-with-istio-on-flat-network.md) , the istio-ingressgateway of the member cluster reports that port 15012 has timed out, and the container network is now connected.
![image](https://user-images.githubusercontent.com/31637804/192727806-c3a61b65-0125-4ff5-871d-f6cd67e2a70c.png)

karmada host istiod-elb
![image](https://user-images.githubusercontent.com/31637804/192728053-e84c422d-3c9b-4039-8f49-eb77c96acb8a.png)

When I telnet port 30359 in the member cluster, it is connected, but the telnet port 15012 in the member cluster is not connected

**Environment**:
- Karmada version: 1.3
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 1.3

**Comment by RainbowMango** [comment]
@zirain Can you help with it?

**Comment by luoMonkeyKing** [comment]
The final solution is to restart the istiod in the karmada host, but the specific reason is not found. This is the second time I have encountered such a problem.

**Comment by luoMonkeyKing** [comment]
There is one more question I want to ask, how do I open the application to the outside world, is the istio-ingressgateway to be deployed in the karmada host?

**Comment by zirain** [comment]
> There is one more question I want to ask, how do I open the application to the outside world, is the istio-ingressgateway to be deployed in the karmada host?

nop

**Comment by luoMonkeyKing** [comment]
> > There is one more question I want to ask, how do I open the application to the outside world, is the istio-ingressgateway to be deployed in the karmada host?
> 
> nop

hi ,Does the gateway configuration need to be propagated to member cluster through pp? I only created the gateway configuration in the host cluster, which does not seem to take effect

**Comment by zirain** [comment]
you should create it in `karmada-apiserver`

**Comment by luoMonkeyKing** [comment]
> you should create it in `karmada-apiserver`



> you should create it in `karmada-apiserver`

yes, I created the gateway configuration in karmada-apiserver, and I also see the relevant configuration in the member cluster, but the error below the ingressgateway of the member cluster when accessing
```
"GET /productpage HTTP/1.1" 503 NC cluster_not_found - "-" 0 0 0 - "192.168.77.1" "curl/7.29.0" "c8e2a0fd-0a41-4c1c-8564-ce11939fcc2d" "192.168.77.1:32693" "-" - - 10.19.0.33:8080 192.168.77.1:47120 - -

```

**Comment by zirain** [comment]
can you check the logs from ingressgateway and istiod? is everything ok?

**Comment by luoMonkeyKing** [comment]
> 您可以检查来自ingressgateway 和istiod 的日志吗？一切都顺利吗？

member cluster istiod logs:
![image](https://user-images.githubusercontent.com/31637804/195000611-6eb1ad6d-da95-4c35-9b6d-41ccb9290759.png)

member cluster ingressgateway logs:
![image](https://user-images.githubusercontent.com/31637804/195000700-88633c86-053d-4b2c-b367-0fea5a967949.png)

**Comment by luoMonkeyKing** [comment]
> 您可以检查来自ingressgateway 和istiod 的日志吗？一切都顺利吗？

hi, the previous question should be the reason why the request is not added host, but I think the official case of istio does not need to be added. I plan to sort out the documents combining karmada and istiogateway later, and contribute to the community later

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
