### ISSUE TITLE
There is a problem with the API interface for creating a propagationpolicy when neither the namespace of the propagationpolicy nor the resourceselectors is set

### ISSUE THREAD

**Issue by ranzhouol** [karmada-io/karmada#2597]
**What happened**:
When I use the API interface to create a **PropagationPolicy**, the namespace of the PropagationPolicy is not set, nor the namespace in the resourceSeletors. The template of the PropagationPolicy is as follows:
```
{
    "apiVersion": "policy.karmada.io/v1alpha1",
    "kind": "PropagationPolicy",
    "metadata": {
        "name": "example-policy"
    },
    "spec": {
        "resourceSelectors": [
            {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "name": "nginx"
            }
        ],
        "placement": {
            "clusterAffinity": {
                "clusterNames": ["test72-k8s"]
            }
        }
    }
}
```
Although the deployment is successfully distributed and the namespace of the PropagationPolicy is set to "default" by default, the namespace in the resourceSeletors does not exist, see below:

![image](https://user-images.githubusercontent.com/67987211/192986920-d640f86e-9a7d-40df-9ddf-14165d339d02.png)

Next, when I edit and modify this PropagationPolicy:

![image](https://user-images.githubusercontent.com/67987211/192987219-a1240a89-4207-40fa-9f8f-aa604a32e912.png)

The following error occurs:

![image](https://user-images.githubusercontent.com/67987211/192987364-88dc4bee-823d-44ed-a5f2-856f2a15cf58.png)

**What you expected to happen**:
I hope the deployment can be distributed normally after modifying the PropagationPolicy

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 1.2
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @ranzhouol, thanks for your feedback!
The problem you mentioned is known to us because we are currently not allowed to modify the policy's `resourceSelector` field, but we are already planning to release this restriction, see #2562

**Comment by RainbowMango** [comment]
For a workaround before #2562, you can remove the PropagationPolicy and apply it again.

**Comment by ranzhouol** [comment]
Hello, we have not modified the policy's resourceSelector field. When we use the API interface to create a propagationpolicy, and the namespace of the policy and resourceselectors is not set, when we edit other modifiable fields again, this bug will appear




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "karmada-io/karmada"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 下午5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [karmada-io/karmada] There is a problem with the API interface for creating a propagationpolicy when neither the namespace of the propagationpolicy nor the resourceselectors is set (Issue #2597)





 
Hi @ranzhouol, thanks for your feedback!
 The problem you mentioned is known to us because we are currently not allowed to modify the policy's resourceSelector field, but we are already planning to release this restriction, see #2562
