### ISSUE TITLE
Custom Resource Interpreter example README should be updated with LoadBalancer/MetalLB support

### ISSUE THREAD

**Issue by loicalbertin** [karmada-io/karmada#2614]
:wave: Hi :wave: 

**What happened**:

Currently if you follow the README on the Custom Resource Interpreter example you will get an error [at that point](https://github.com/karmada-io/karmada/blob/master/examples/README.md#step2-deploy-webhook-configuration-in-karmada-apiserver).

This is because the webhook url should be replaced but this is not done in `webhook-configuration.sh`:

https://github.com/karmada-io/karmada/blob/75a0305a8c2bbbb91823bd0d000331ca7db91b6d/examples/customresourceinterpreter/webhook-configuration.yaml#L14 

**What you expected to happen**:

Based on `hack/pre-run-e2e.sh` I think that:

* MetalLB should be deployed (could be described in tutorial or through `hack/local-up-karmada.sh`).
* `webhook-configuration.sh` should replace the webhook IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the tutorial

**Comment by RainbowMango** [comment]
Hi @loicalbertin, nice to see you again. I'm just getting back from a long holiday.
Yes, you are right. Seems we forgot to update the docs(or, webhook-configuration.sh) at #1676.

The author is on paternity leave and will get back at the end of this month. I don't have enough time for this right now, let's tag this issue for help.
/help

**Comment by RainbowMango** [comment]
Thank you @loicalbertin, I appreciate that you can help.

> Do you think that describing how to deploy MetalLB in the README and update webhook-configuration.sh to replace the webhook IP address would be enough?

Sounds good to me.

**Comment by XiShanYongYe-Chang** [comment]
@loicalbertin thanks a lot for your patch!
