### ISSUE TITLE
ANP deploy success,but aggregate api access failed with 503

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#2635]
The karmada deploy in the host kubernetes not in kind docker container.And the member cluster which join karmada in pull mode, and finally deploy ANP in the member cluster and karmada host cluster, it seem be deploy well with the log.

In karmada host cluster with the command `kubectl logs --tail 100 -f proxy-server-774dc95c8d-j2k9l -n karmada-system`

<img width="1212" alt="截屏2022-10-13 下午3 39 09" src="https://user-images.githubusercontent.com/15276000/195532952-53f024e9-82dc-410f-8d01-97de08ee205d.png">

And in the Member cluster with the command `kubectl logs --tail 100 -f  proxy-agent-854994b6b6-zsnkn -n karmada-system`
<img width="1148" alt="截屏2022-10-13 下午3 40 53" src="https://user-images.githubusercontent.com/15276000/195533331-1ee64e5a-00ee-46f7-937b-14f861c56363.png">

And i already grant permission to user system:admin.

But when i access the member's info through the aggregate api it failed with the log:

<img width="1227" alt="截屏2022-10-13 下午3 45 25" src="https://user-images.githubusercontent.com/15276000/195534297-9a69f5f2-4637-44cf-b4e7-90d7ad8077f1.png">

the ip `10.0.2.28` is the pod proxy-server's pod IP. Is the port `32443` in the request url  right？

**Comment by lonelyCZ** [comment]
How do you deploy karmada? `script`, `helm` or `karmadactl`?

**Comment by SZT0728** [comment]
> How do you deploy karmada? `script`, `helm` or `karmadactl`?

karmada deployed by `karmadactl`. I removed the command flag `--proxy-server-address` which list in the **Step 6** [https://karmada.io/docs/userguide/clustermanager/working-with-anp/](url) and it well now. 

why?

**Comment by lonelyCZ** [comment]
> karmada deployed by karmadactl. I removed the command flag --proxy-server-address which list in the Step 6 [https://karmada.io/docs/userguide/clustermanager/working-with-anp/](https://karmada.io/docs/userguide/clustermanager/working-with-anp/) and it well now.

Because your karmada control plane can directly access ip address of member cluster apiserver?

**Comment by SZT0728** [comment]
> > karmada deployed by karmadactl. I removed the command flag --proxy-server-address which list in the Step 6 https://karmada.io/docs/userguide/clustermanager/working-with-anp/ and it well now.
> 
> Because your karmada control plane can directly access ip address of member cluster apiserver?

yes, they are in the same network area. Is it different in the other case( karmada control plane can't directly access ip address of member cluster apiserver)

**Comment by lonelyCZ** [comment]
> Is it different in the other case( karmada control plane can't directly access ip address of member cluster apiserver)

Yes, it is.

**Comment by SZT0728** [comment]
> > Is it different in the other case( karmada control plane can't directly access ip address of member cluster apiserver)
> 
> Yes, it is.

thanks~
