### ISSUE TITLE
Karmada can not get the pvc information include status and spec

### ISSUE THREAD

**Issue by wuyingjun-lucky** [karmada-io/karmada#2642]
**What would you like to be added**:
Karmada can get the pvc information include status and spec
**Why is this needed**:
`1` pvc is dispatched by karmada control plane 
`2` member cluster  by kubectl : 
<img width="861" alt="image" src="https://user-images.githubusercontent.com/16109961/195752984-b10e3c58-853e-4876-85f2-08fb559b3dc2.png">
`3` host cluster by kubectl: 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/16109961/195753097-a732af01-6523-4274-b91f-e17387638d89.png">

**Comment by wuyingjun-lucky** [comment]
Maybe we can set the status in default interpreter karmada but how to set the spec field ?

**Comment by wuyingjun-lucky** [comment]
cc @RainbowMango

**Comment by RainbowMango** [comment]
> Maybe we can set the status in default interpreter but how to set the spec field ?

What about propagating the PVC to more than one cluster? We would get one `volume name` or more?

**Comment by wuyingjun-lucky** [comment]
> > Maybe we can set the status in default interpreter but how to set the spec field ?
> 
> What about propagating the PVC to more than one cluster? We would get one `volume name` or more?

Both situations will exist

**Comment by RainbowMango** [comment]
That's the point, we can't set two names to a single filed. That's the limitation. 
Even for status, we still got similar situations.

**Comment by wuyingjun-lucky** [comment]
> That's the point, we can't set two names to a single filed. That's the limitation. Even for status, we still got similar situations.
If we do not use override policy, the capacity or accessModes will keep the same. Do you think we can just keep the fields unchanged.

**Comment by RainbowMango** [comment]
> If we do not use override policy, the capacity or accessModes will keep the same. Do you think we can just keep the fields unchanged.

I guess the `.spec.volumeName` and `.status.accessModes` are both generated by member clusters, right? Then, I don't think we can sync the status back to the `resource template` without bringing ambiguity.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
