### ISSUE TITLE
Use Kwok instead of Kind without actually running a container

### ISSUE THREAD

**Issue by wzshiming** [karmada-io/karmada#2661]
**What would you like to be added**:

https://github.com/kubernetes-sigs/kwok

1. Use Kwok instead of Kind with the non-pull mode clusters in the example
2. ~~Update the document to use Kwok instead of [fake-kubelet] (https://github.com/wzshiming/fake-kubelet)
    https://karmada.io/docs/next/developers/performance-test-setup-for-karmada~~

**Why is this needed**:

Reduce CI resource requirements

**Comment by wzshiming** [comment]
> I'm not sure if Kwok can be used by CI, glad to see a demo.

Well, I will work on this.


> For the [performance test](https://karmada.io/docs/next/developers/performance-test-setup-for-karmada/), that's the document to record how the last round performance test run. And we don't have a plan to run the second round for now.

Ok, then I'll leave the document alone.

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok#basic-usage
Kwok can be used to simulate nodes and clusters

Simulate Node: https://github.com/kubernetes-sigs/kwok/blob/main/docs/examples/kwok-in-cluster.md
Simulate Cluster: https://github.com/kubernetes-sigs/kwok/blob/main/docs/examples/kwokctl-manage-cluster.md
Manage nodes and pods: https://github.com/kubernetes-sigs/kwok/blob/main/docs/examples/kwok-manage-nodes-and-pods.md

Kwok is actually a [fake-kubelet](https://github.com/wzshiming/fake-kubelet) migration
Kwokctl is actually a [fake-k8s](https://github.com/wzshiming/fake-k8s) migration

**Comment by Poor12** [comment]
/close
This issue is discussed on the community meeting. Feel free to reopen it if you have any questions.
