### ISSUE TITLE
Improve karmadactl command description

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#2665]
At present, the description format of karmadactl subcommands is not uniform, some do not have Long descriptions, some descriptions are sentences and some are not. From the next version, we will generate readable documents for commands, so I think we need to complete and unify the description information format.

See the page：https://karmada.io/docs/next/reference/karmadactl/karmadactl-commands/karmadactl_index

**Comment by lonelyCZ** [comment]
Ok, I will improve them.

/assign

**Comment by Fish-pro** [comment]
@lonelyCZ Can I be part of the process?
