### ISSUE TITLE
controller manager crashes when cluster ImpersonatorSecretRef is nil

### ISSUE THREAD

**Issue by stingshen** [karmada-io/karmada#2674]
**What happened**:

When cluster ImpersonatorSecretRef is nil, controller manager crashes. 

**What you expected to happen**:

Controller manager should not crash at any time.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster object with ImpersonatorSecretRef is nil
2. Controller manager crashes

**Anything else we need to know?**:

**Environment**:
- Karmada version:
1.3.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
karmadactl version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
- Others:

**Comment by RainbowMango** [comment]
Thanks @stingshen for reporting this to us and sending the patch.
/assign @stingshen 
as per #2675
