### ISSUE TITLE
karmada-system namespace deletion sucks.

### ISSUE THREAD

**Issue by bretagne-peiqi** [karmada-io/karmada#2685]
when try to delete karmada system, the karmada-system yaml shows as belows:
  
- lastTransitionTime: "2022-10-26T01:38:28Z"
    message: 'Failed to delete all resource types, 2 remaining: servicebindings.servicecatalog.k8s.io
      "Unknown" is forbidden: not yet ready to handle request, serviceinstances.servicecatalog.k8s.io
      "Unknown" is forbidden: not yet ready to handle request'
    reason: ContentDeletionFailed
    status: "True"
    type: NamespaceDeletionContentFailure

karmada version: 1.0

**Comment by bretagne-peiqi** [comment]
I try to get  servicebindings.servicecatalog.k8s.io  and serviceinstances.servicecatalog.k8s.io in my cluster. but these two crd(resource) doesn't exist. 

so I don't understand the cause.

**Comment by XiShanYongYe-Chang** [comment]
You can try to forcibly delete the namespace by deleting the finalizers field:
```yaml
spec:
  finalizers:
  - kubernetes
```

**Comment by XiShanYongYe-Chang** [comment]
You can use `kubectl describe` command to describe the cluster object and see the condition status:
```
kubectl describe cluster member1
```

**Comment by bretagne-peiqi** [comment]
there are no errors  ni events

Metadata:
  Creation Timestamp:  2022-10-26T06:46:33Z
  Managed Fields:
    API Version:  cluster.karmada.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:apiEndpoint:
        f:impersonatorSecretRef:
          .:
          f:name:
          f:namespace:
        f:secretRef:
          .:
          f:name:
          f:namespace:
        f:syncMode:
    Manager:         Go-http-client
    Operation:       Update
    Time:            2022-10-26T06:46:33Z
  Resource Version:  2171705
  UID:               8391690f-4b30-4e29-9783-d5855d5f7aa7
Spec:
  API Endpoint:  https://192.168.16.18:6443
  Impersonator Secret Ref:
    Name:       jichucluster-impersonator
    Namespace:  karmada-cluster
  Secret Ref:
    Name:       jichucluster
    Namespace:  karmada-cluster
  Sync Mode:    Push
Status:
Events:  <none>

**Comment by bretagne-peiqi** [comment]
thanks for your reply.  I tried the new version release 1.3

#my installation from your guide: 
./remote-up-karmada.sh ~/.kube/config karmada-host

##when I try to register cluster, it shows:

[root@cn-shanghai .kube]# kubectl karmada join jichucluster --kubeconfig=config --cluster-kubeconfig=configjichu
W1027 10:19:25.352438    5535 cluster.go:96] failed to retrieve cluster(). error: the server is currently unable to handle the request (get clusters.cluster.karmada.io jichucluster)
Error: failed to create cluster(jichucluster) object. error: the server is currently unable to handle the request (get clusters.cluster.karmada.io jichucluster)

should I install crd cluster.karmda.io ? I have not found it in pkg

**Comment by bretagne-peiqi** [comment]
<img width="825" alt="1666838199243" src="https://user-images.githubusercontent.com/5621794/198177584-e7a9ff96-a8a7-4e6b-aaa1-41c9601ade64.png">

this logs is from karmada-controller

**Comment by bretagne-peiqi** [comment]
![1666839045390](https://user-images.githubusercontent.com/5621794/198179423-04d8aecc-aa2b-4421-963f-5ecc4426ddf2.jpg)

logs from karmada-aggregated-apiserver

**Comment by XiShanYongYe-Chang** [comment]
> should I install crd cluster.karmda.io ? I have not found it in pkg

`Cluster` is registered by AA, not CRD.

You can have a check with command:
```
# kubectl get apiservices.apiregistration.k8s.io | grep cluster
v1alpha1.cluster.karmada.io            karmada-system/karmada-aggregated-apiserver   True        2d
```
To ensure the `Cluster` resource is ok.

**Comment by bretagne-peiqi** [comment]
@XiShanYongYe-Chang thanks, it is sovled.

**Comment by XiShanYongYe-Chang** [comment]
You are welcome :)
/assign
/close
