### ISSUE TITLE
CreateOrUpdateSecret function not works as expected

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2687]
**What would you like to be added**:
The `CreateOrUpdateSecret` doesn't work as expected as the `Update` operation would fail due to not refresh the latest `ResourceVersion`:
https://github.com/karmada-io/karmada/blob/5d42e82b7b92812a04aaade4b77e66556aa20d66/pkg/util/secret.go#L49-L61

For more details please refer to: https://github.com/karmada-io/karmada/pull/2596#discussion_r1006333298

Since this function is used by `karmadactl init` and `karmadactl register`, so we need to verify the two functionalities after we make changes.

**Why is this needed**:

**Comment by lonelyCZ** [comment]
It also contain other several functions like rbac, I will fix them.

/assign
