### ISSUE TITLE
Error when accessing member cluster by client-go using karmada-apiserver endpoint

### ISSUE THREAD

**Issue by b2k4j** [karmada-io/karmada#2697]
I can access resource of member cluster using my serviceaccount in CLI:
![b](https://user-images.githubusercontent.com/89241565/198559328-5e736fdc-d29d-4d68-9b4b-79918fbde34f.png)

But got such an error using client-go:
![a](https://user-images.githubusercontent.com/89241565/198558497-72d0b230-41eb-4c1d-aa5d-87d7c1026783.png)

**What do you think about this question?**:
I'm sure all the configuration is fine because I can access the host cluster resources via client-go.

**Environment**:
- Karmada version: v1.3.0
- Kubernetes version: v1.24.0
- Others:

**Comment by RainbowMango** [comment]
cc @XiShanYongYe-Chang @lonelyCZ

**Comment by b2k4j** [comment]
@XiShanYongYe-Chang
Sure, my configuration of the karmada-apiserver is as following:
```
func CreateClientKarmadaConfig(host, cluster string, clientSecret *corev1.Secret) (*rest.Config, error) {
	ca := clientSecret.Data["ca.crt"]
	token := clientSecret.Data["token"]

	if err := os.MkdirAll(clientDir, fs.ModeDir); err != nil {
		klog.Errorf("failed to mkdir client dir `%s`: %v", clientDir, err)
		// keep going on
	}
	if err := os.WriteFile(caFile, ca, fs.ModePerm); err != nil {
		klog.Errorf("error writing CA file `%s`: %v", caFile, err)
		return nil, err
	}
	if err := os.WriteFile(tokenFile, token, fs.ModePerm); err != nil {
		klog.Errorf("error writing token file `%s`: %v", tokenFile, err)
		return nil, err
	}

	tlsClientConfig := rest.TLSClientConfig{}

	if _, err := certutil.NewPoolFromBytes(ca); err != nil {
		klog.Errorf("expected to load client CA config from %s, but got err: %v", caFile, err)
	} else {
		tlsClientConfig.CAFile = caFile
	}

	return &rest.Config{
		Host:            host,
		TLSClientConfig: tlsClientConfig,
		BearerToken:     string(token),
		BearerTokenFile: tokenFile,
                Proxy: func(req *http.Request) (*url.URL, error) {
		req.URL.Path = path.Join("/apis/cluster.karmada.io/v1alpha1/clusters", cluster, "proxy", req.URL.Path)
		return req.URL, nil
	        }
	}, nil
}
```
And the sample code is as follows:
```
clientset, err := sdkClient.NewKubeClientset()
if err != nil {
	setupLog.Error(err, "unable to start clientset")
	os.Exit(1)
}

podList, err := clientset.CoreV1().Pods("ccos-kube-apiserver").List(context.Background(), metav1.ListOptions{})
if err != nil {
	klog.Errorf("unable to list pods: %+v", err)
	os.Exit(1)
}

for _, n := range podList.Items {
	setupLog.Info("list nodes: %q", n.Name)
}
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @b2k4j , I'm sorry, I don't know how to solve this problem. I think some parameters are not set correctly when constructing `*rest.Config`.

**Comment by lonelyCZ** [comment]
I also guess that it could be the parameter problem of `*rest.Config`, because we can use the `Factory` to access the resources of member clusters normally.

https://github.com/karmada-io/karmada/blob/f68da6d64e76f52dcf45ac32844342d70cb9b66a/pkg/karmadactl/util/factory.go#L58-L59

**Comment by b2k4j** [comment]
@XiShanYongYe-Chang
Fine, thanks for your reply.

**Comment by b2k4j** [comment]
@lonelyCZ 
Thanks, it's a nice tip!

**Comment by XiShanYongYe-Chang** [comment]
Our E2E also constructs requests to access:

https://github.com/karmada-io/karmada/blob/5811aea95303236ff1c98eb110cea065b4020143/test/e2e/aggregatedapi_test.go#L199

If there are new developments, we can talk more about it.

**Comment by b2k4j** [comment]
@lonelyCZ @XiShanYongYe-Chang 
Thanks for your help! I've fixed this issue.

**Comment by XiShanYongYe-Chang** [comment]
> pkg/controllers/cluster/cluster_controller.go

Gold to here that. By the way, can you share your fix?

**Comment by b2k4j** [comment]
I'm sorry I do not know the cause of this problem, and it's still a mystery.  I resolve this problem by using `*rest.Config.Host` instead of `*rest.Config.Proxy` behaving like `*rest.Config.Host = "https://karmada-apiserver.karmada-system.svc.cluster.local:5443/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy"`.

**Comment by b2k4j** [comment]
I'm sorry I do not know the cause of this problem, and it's still a mystery.  I resolve this problem by using `rest.Config.Host` instead of `rest.Config.Proxy` behaving like `rest.Config.Host = "https://karmada-apiserver.karmada-system.svc.cluster.local:5443/apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy"`.

**Comment by XiShanYongYe-Chang** [comment]
Ok. thanks~
