### ISSUE TITLE
controller: pass `ctx` parameter from top level to sub functions, instead of creating one new or using default context

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#2701]
**What would you like to be added**:
 pass `ctx` parameter from top level to sub functions, instead of creating one new or using default context

**Why is this needed**:
1. When create controllerManager, `Options.BaseContext` is empty:
https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/cmd/controller-manager/app/controllermanager.go#L117

https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go#L245

2. When create `Runnables`, `Options.BaseContext` empty, so `runnableGroup.ctx` will be `defaultBaseContext`:
https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go#L616

https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go#L103

3. When run resource `reconcile` function, they use the `defaultBaseContext` :
https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go#L219

4. this `ctx` will be passed to resource `Reconcile` function:
https://github.com/karmada-io/karmada/blob/026781f207005c07b5f4cb0e76cf79b055bf53c0/pkg/controllers/namespace/namespace_sync_controller.go#L49

This will cause: `cancel signal` can't control some sub functions

**Comment by jwcesign** [comment]
cc @RainbowMango

**Comment by yanggangtony** [comment]
@jwcesign 
Hi , I just take a pr for that , PTAL
