### ISSUE TITLE
cfssl image does not support arm64

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2712]
**What happened**:

https://github.com/karmada-io/karmada/blob/bd8d734054f55f44786ffebd2acff015abea2963/charts/karmada/values.yaml#L35-L39

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/17962021/198962446-508cbc11-9ec4-4330-94e7-6d8035f8d7c5.png">

cfssl image does not support arm64

**What you expected to happen**:

Karmada can be installed using `helm` in the arm64 environment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by calvin0327** [comment]
`bitnami/kubectl` is not supported either, if we install karmada with helm, the pods of `pre job` and `post job` cannot running.

**Comment by cmicat** [comment]
It seems more like an upstream problem? What Karmada project can do with it?

**Comment by calvin0327** [comment]
Indeed, karmada should not to maintain these dependent third-party images.

Don't know if there is a better support for multi-platform image source.
