### ISSUE TITLE
Please sync APIs to karmada-api repo from karmada repo based on v1.3.x

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#2720]
**Please provide an in-depth description of the question you have**:

Please sync APIs to karmada-api repo from karmada repo based on v1.3.x

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
/assign
Are you using this repo?

**Comment by chaunceyjiang** [comment]
> Are you using this repo?


![image](https://user-images.githubusercontent.com/17962021/199204614-e4e584ad-b385-4546-aa18-343c1f303e50.png)

**Comment by calvin0327** [comment]
Should we add a CI workflow to automatically synchronize the API repo?

**Comment by RainbowMango** [comment]
Yes, but not yet.
