### ISSUE TITLE
ResourceVersion returned by watch API in karmada-search is not comparable

### ISSUE THREAD

**Issue by hanzai** [karmada-io/karmada#2721]
**What would you like to be added**:
  resouceversion should include some information to indicate which cluster the watch event comes from.   

**Why is this needed**:
  The resourceversion returned by watch API in karmada-search  is a base64-encoded string. The original content is a jsonobject including member cluster names and their respective resourceversion. This design works well in the List and Watch API. But it is not comparable for the lack of  the exact resourceversion of resource in the watch event. 
  In some scenarios, resourceversion should be comparable. https://github.com/kubernetes/client-go/blob/master/tools/cache/mutation_cache.go#L228

**Comment by ikaven1024** [comment]
> You must not assume resource versions are numeric or collatable. API clients may only compare two resource versions for equality (this means that you must not compare resource versions for greater-than or less-than relationships).

FROM: https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions

**Comment by hanzai** [comment]
OK, I see. tks

**Comment by ikaven1024** [comment]
Hoping more feedbacks from you about it. @hanzai
