### ISSUE TITLE
cfssl checksum mismatch

### ISSUE THREAD

**Issue by wzshiming** [karmada-io/karmada#2722]
**What happened**:

``` console
GOPROXY=https://goproxy.io go install github.com/cloudflare/cfssl/cmd/...@v1.6.2
go: github.com/cloudflare/cfssl/cmd/...@v1.6.2: github.com/cloudflare/cfssl@v1.6.2: verifying module: checksum mismatch
        downloaded: h1:V7EcbVzttAkK3J7PmAxjf7wD7UpMtWSCI+Wl+mu87mw=
        sum.golang.org: h1:3T2oQHypP81rykPfkTxOCyJkRU3xQz5SySVahMpN5LE=
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Can you tell us how to reproduce it?
By the way, can you show the output of `go env GOPROXY`?

**Comment by wzshiming** [comment]
GOPROXY=https://goproxy.io go install github.com/cloudflare/cfssl/cmd/...@v1.6.2

**Comment by wzshiming** [comment]
This means that the tag has been force-pushed, and goproxy.io has cached the tag without updating it.

**Comment by ikaven1024** [comment]
> GOPROXY=https://goproxy.io go install github.com/cloudflare/cfssl/cmd/...@v1.6.2

I works well on my side. What's your `GOSUMDB`?
```
go env GOSUMDB
```

**Comment by wzshiming** [comment]
``` console
go env GOSUMDB
sum.golang.org
```

**Comment by wzshiming** [comment]
``` console
docker run --rm -it docker.io/library/golang:alpine sh -c 'GOPROXY=https://goproxy.io go install github.com/cloudflare/cfssl/cmd/...@v1.6.2'

go: downloading github.com/cloudflare/cfssl v1.6.2
go: github.com/cloudflare/cfssl/cmd/...@v1.6.2: github.com/cloudflare/cfssl@v1.6.2: verifying module: checksum mismatch
        downloaded: h1:V7EcbVzttAkK3J7PmAxjf7wD7UpMtWSCI+Wl+mu87mw=
        sum.golang.org: h1:3T2oQHypP81rykPfkTxOCyJkRU3xQz5SySVahMpN5LE=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by wzshiming** [comment]
> > GOPROXY=https://goproxy.io go install github.com/cloudflare/cfssl/cmd/...@v1.6.2
> 
> It works well on my side. What's your `GOSUMDB`?
> 
> ```
> go env GOSUMDB
> ```

Maybe had cached in machine

**Comment by RainbowMango** [comment]
I guess it's the `goproxy.io`'s problem, it might cached the wrong code.

**Comment by cmicat** [comment]
I tested `GOPROXY=https://goproxy.io/ go install github.com/cloudflare/cfssl/cmd/...@v1.6.2`, it will return the same `SECURITY ERROR` as you said.

But when I changed to `https://goproxy.cn/`, everything is fine.

**Comment by RainbowMango** [comment]
@wzshiming I suggest reporting this issue to goproxy.io.

**Comment by wzshiming** [comment]
well, we'd better bump to avoid this issue
Please have a look at #2723

**Comment by wzshiming** [comment]
> @wzshiming I suggest reporting this issue to goproxy.io.

It may not be a issue of `goproxy.io`, but rather that `github.com/cloudflare/cfssl`'s tag `v1.6.2` has been force-pushed

**Comment by RainbowMango** [comment]
> github.com/cloudflare/cfssl's tag v1.6.2 has been force-pushed

Each version will be cached by `proxy.golang.org` and `sum.golang.org` will record the checksum.
If the maintainer re-tagged the version, then we can't install it with `sum.golang.org`.

**Comment by RainbowMango** [comment]
@wzshiming have you figured out the root cause?
