### ISSUE TITLE
Stop update krew for release 1.1.x

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2743]
**Task description**:
Since [krew ](https://github.com/kubernetes-sigs/krew) only caches the `latest` release, so we don't need to update it for v1.1.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2541.

**Solution**:

This task is for branch `release-1.1`, and here is an example for `release-1.2`:
https://github.com/karmada-io/karmada/pull/2742

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by ndkhangvl** [comment]
I want to assign, I am a newbie. My job is to delete some lines of code used to update the version in branch 1.1.x?

**Comment by RainbowMango** [comment]
@ndkhangvl Yes. but @yanggangtony has sent a PR for this. Hope you don't mind.
