### ISSUE TITLE
Unification karmadactl dry-run usage

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/karmada#2762]
**Task description**:
Unification karmadactl dry-run usage
**Solution**:
`pkg/karmadactl/register.go`
```go
flags.BoolVar(&opts.DryRun, "dry-run", false, "Run the command in dry-run mode, without making any server requests.")
```
replace
```go
flags.BoolVar(&opts.DryRun, "dry-run", false, "Don't apply any changes; just output what would be done.")
```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
Just replace the usage from `Run the command in dry-run mode, without making any server requests.` to `Don't apply any changes; just output what would be done.`? Why?

**Comment by RainbowMango** [comment]
Yeah, I get it. You want to replace `Don't apply any changes; just output what would be done.` with `Run the command in dry-run mode, without making any server requests.`. 
Right, I agree.
