### ISSUE TITLE
Default scheduler should be declared

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#279]
**What would you like to be added**:
Set default scheduler name `default-scheduler` to PropagationPolicy and ClusterPropagationPolicy objects:
- PropagationPolicy: https://github.com/karmada-io/karmada/blob/62cacffd597f1190dd780923472a67322de1789a/pkg/apis/policy/v1alpha1/propagation_types.go#L51
- `karmada-scheduler` should filter policies with this

**Why is this needed**:
Mandatory if we want to support a third-party scheduler.

PS:
// +kubebuilder:default="default-scheduler"

**Comment by algebra2k** [comment]
> **What would you like to be added**:
> Set default scheduler name `default-scheduler` to PropagationPolicy and ClusterPropagationPolicy objects:
> 
> * PropagationPolicy: https://github.com/karmada-io/karmada/blob/62cacffd597f1190dd780923472a67322de1789a/pkg/apis/policy/v1alpha1/propagation_types.go#L51
> * `karmada-scheduler` should filter policies with this
> 
> **Why is this needed**:
> Mandatory if we want to support a third-party scheduler.
> 
> PS:
> // +kubebuilder:default="default-scheduler"

I think there is also a need to filter some bindings inside the scheduler based on the schedulerName.

**Comment by RainbowMango** [comment]
> I think there is also a need to filter some bindings inside the scheduler based on the schedulerName.

Yes.  It is the second item in the list above, `karmada-scheduler should filter policies with this`

**Comment by RainbowMango** [comment]
Hi @phantooom How's it going? Do you need help?
We are going to cut a new release next week, I wonder if this feature would be included.

**Comment by RainbowMango** [comment]
I can't reach @phantooom. 
@qianjun1993 Can you take this task? You can split it into small PRs if necessary.
