### ISSUE TITLE
isPodReady add check job pod status

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/karmada#2792]
**Task description**:
Add check of job pod to `isPodReady`
see https://github.com/kubernetes-sigs/application/blob/8ce143e2c9b5480034ec3c60f8ba1c89b6afebe5/controllers/status.go#L205
**Solution**:
`pkg/karmadactl/cmdinit/kubernetes/check.go`
add `|| v.Reason == "PodCompleted"`
```go
func isPodReady(c *kubernetes.Clientset, n, p string) wait.ConditionFunc {
	return func() (done bool, err error) {
		pod, err := c.CoreV1().Pods(n).Get(context.TODO(), p, metav1.GetOptions{})
		if err != nil {
			return false, err
		}

		if pod.Status.Phase == corev1.PodPending && len(pod.Status.ContainerStatuses) == 0 {
			klog.Warningf("pod: %s not ready. status: %v", pod.Name, corev1.PodPending)
			return false, nil
		}

		for _, v := range pod.Status.Conditions {
			switch v.Type {
			case corev1.PodReady:
				if v.Status == corev1.ConditionTrue || v.Reason == "PodCompleted" {
					klog.Infof("pod: %s is ready. status: %v", pod.Name, podStatus(pod))
					return true, nil
				}
				klog.Warningf("pod: %s not ready. status: %v", pod.Name, podStatus(pod))
				return false, nil
			default:
				continue
			}
		}
		return false, err
	}
}
```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by helen-frank** [comment]
@RainbowMango Do you approve of this ?

**Comment by RainbowMango** [comment]
I removed `good first issue` because the description is not clear enough for the first-time controller to get started.

**Comment by RainbowMango** [comment]
Why do you think we need to add `v.Reason == "PodCompleted"`? I guess this reason more like to represent the status of a `Job`, 
but we don't have `Job`, right?

**Comment by helen-frank** [comment]
Yes, maybe this will be needed in the future, temporarily closed?

**Comment by RainbowMango** [comment]
+1
