### ISSUE TITLE
[E2E] `StatefulSetStatus collection testing` run failed randomly

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#2804]
#### Which jobs are flaking:

https://github.com/karmada-io/karmada/actions/runs/3459716584/jobs/5775815989
https://github.com/karmada-io/karmada/actions/runs/3459287784/jobs/5774639785
https://github.com/karmada-io/karmada/actions/runs/3461076772/jobs/5778451508

#### Which test(s) are flaking:

```log
• [FAILED] [310.064 seconds]
[resource-status collection] resource status collection testing
/home/runner/work/karmada/karmada/test/e2e/resource_test.go:27
  StatefulSetStatus collection testing
  /home/runner/work/karmada/karmada/test/e2e/resource_test.go:464
    [It] statefulSet status collection testing
    /home/runner/work/karmada/karmada/test/e2e/resource_test.go:495

  Begin Captured StdOut/StdErr Output >>
    I1114 07:36:27.774176   39833 resource_test.go:498] Waiting for statefulSet(karmadatest-nxzv9/statefulset-mt8v6) collecting correctly status
    I1114 07:36:27.781282   39833 resource_test.go:503] statefulSet(karmadatest-nxzv9/statefulset-mt8v6) replicas: 0, wanted replicas: 9
    I1114 07:36:32.784572   39833 resource_test.go:503] statefulSet(karmadatest-nxzv9/statefulset-mt8v6) replicas: 9, wanted replicas: 9
    I1114 07:36:37.791092   39833 resource_test.go:503] statefulSet(karmadatest-nxzv9/statefulset-mt8v6) replicas: 9, wanted replicas: 9
    I1114 07:36:37.803486   39833 resource_test.go:520] Waiting for statefulSet(karmadatest-nxzv9/statefulset-mt8v6) collecting correctly status
  << End Captured StdOut/StdErr Output

  Begin Captured GinkgoWriter Output >>
    STEP: Creating StatefulSet(karmadatest-nxzv9/statefulset-mt8v6) 11/14/22 07:36:27.752
    STEP: Creating PropagationPolicy(karmadatest-nxzv9/statefulset-mt8v6) 11/14/22 07:36:27.762
    STEP: check whether the statefulSet status can be correctly collected 11/14/22 07:36:27.773
    STEP: Updating StatefulSet(karmadatest-nxzv9/statefulset-mt8v6)'s replicas to 6 11/14/22 07:36:37.791
    STEP: check if statefulSet status has been update with new collection 11/14/22 07:36:37.803
    STEP: Removing PropagationPolicy(karmadatest-nxzv9/statefulset-mt8v6) 11/14/22 07:41:37.804
    STEP: Removing StatefulSet(karmadatest-nxzv9/statefulset-mt8v6) 11/14/22 07:41:37.81
  << End Captured GinkgoWriter Output

  Timed out after 300.000s.
  Expected
      <bool>: false
  to equal
      <bool>: true
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/resource_test.go:533

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.glob..func26.8.3.2()
    	/home/runner/work/karmada/karmada/test/e2e/resource_test.go:533 +0x44c
    github.com/karmada-io/karmada/test/e2e.glob..func26.8.3()
    	/home/runner/work/karmada/karmada/test/e2e/resource_test.go:517 +0x168
```

#### Reason for failure:

Failed to wait for target status during `statefulset` collection. Find the `kubelet` logs of the member cluster and find that the pod cannot be started:

![image](https://user-images.githubusercontent.com/78244870/201665005-bcb3a612-2faa-498d-91a8-ff3ff58c0760.png)

#### Anything else we need to know:

Solution: Decrease the number of replicas when updating the number of statefulset replicas:

https://github.com/karmada-io/karmada/blob/eee362c6f636568ecd5a05c36cd5d15d4a7b67f9/test/e2e/suite_test.go#L60

**Comment by XiShanYongYe-Chang** [comment]
The previous analysis of the cause of the problem was wrong, the reason for failure is:

Test cases `Test clusterOverridePolicy with nil resourceSelectors`, `OverrideRules with nil resourceSelectors` and `OverridePolicy with nil resourceSelectors` run concurrently with other test cases, affecting the workload image in other test cases. As a result, the image cannot be pulled correctly. So we need to execute these use cases serially.

**Comment by RainbowMango** [comment]
cc @wuyingjun-lucky for the lesson learn :)

**Comment by wuyingjun-lucky** [comment]
> The previous analysis of the cause of the problem was wrong, the reason for failure is:
> 
> Test cases `Test clusterOverridePolicy with nil resourceSelectors`, `OverrideRules with nil resourceSelectors` and `OverridePolicy with nil resourceSelectors` run concurrently with other test cases, affecting the workload image in other test cases. As a result, the image cannot be pulled correctly. So we need to execute these use cases serially.

The overridepolicy works.
Maybe we can change it to annotation rules in another way ?

**Comment by XiShanYongYe-Chang** [comment]
> The overridepolicy works.
> Maybe we can change it to annotation rules in another way ?

Which way?

**Comment by wuyingjun-lucky** [comment]
> 

I have seen your pr . I mean can we avoid this failed case if the overrider is not  image-overrider but just label-overrider.
And I am be curious about why it does not happen before ? Overridepolicy with nil selector test case have existed before.  
  
```
ginkgo.Context("Deployment override testing", func() {
		ginkgo.BeforeEach(func() {
			framework.CreatePropagationPolicy(karmadaClient, propagationPolicy)
			framework.CreateOverridePolicy(karmadaClient, overridePolicy)
			framework.CreateDeployment(kubeClient, deployment)
			ginkgo.DeferCleanup(func() {
				framework.RemovePropagationPolicy(karmadaClient, propagationPolicy.Namespace, propagationPolicy.Name)
				framework.RemoveOverridePolicy(karmadaClient, overridePolicy.Namespace, overridePolicy.Name)
				framework.RemoveDeployment(kubeClient, deployment.Namespace, deployment.Name)
			})
		})

		ginkgo.It("deployment imageOverride testing", func() {
			klog.Infof("check if deployment present on member clusters have correct image value")
			framework.WaitDeploymentPresentOnClustersFitWith(framework.ClusterNames(), deployment.Namespace, deployment.Name,
				func(deployment *appsv1.Deployment) bool {
					return deployment.Spec.Template.Spec.Containers[0].Image == "fictional.registry.us/nginx:1.19.0"
				})
		})
	})
```

**Comment by XiShanYongYe-Chang** [comment]
> I have seen your pr . I mean can we avoid this failed case if the overrider is not image-overrider but just label-overrider.

Thanks, I get your meaning, this can work. However, in test cases, for parallel running, the best case is that test cases do not affect each other because it is difficult to locate a problem. If the condition is not met, we can set it to serial execution.

> And I am be curious about why it does not happen before ? Overridepolicy with nil selector test case have existed before.

The previous writing method is also problematic, but the probability of error is very small, occasional occurrence is also ignored by me :)

**Comment by wuyingjun-lucky** [comment]
And should we cherry-pick [2811](https://github.com/karmada-io/karmada/pull/2811) to release1.1-1.3?

**Comment by XiShanYongYe-Chang** [comment]
> And should we cherry-pick [2811](https://github.com/karmada-io/karmada/pull/2811) to release1.1-1.3?

Yes, we should do it.
