### ISSUE TITLE
资源在传播到被纳管的集群后，丢失status

### ISSUE THREAD

**Issue by quaminigin** [karmada-io/karmada#2818]
**What happened:**
在管理集群上创建 Kubeedge 的 Device 和 DeviceModel 资源，并创建对应的传播策略，将资源传播到某个被纳管集群。在被纳管集群查看资源的信息，发现没有status；而在管理集群查看资源的信息，是有status的。

**What you expected to happen:**
我希望资源在从管理集群传播到被纳管集群时，保持完整的信息，不丢失status

**How to reproduce it:**
**1. 根据以下yaml创建Device**
```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: temperature
  namespace: xapp
  labels:
    description: 'temperature'
    manufacturer: 'test'
spec:
  deviceModelRef:
    name: temperature-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - raspberry-pi-node01
status:
  twins:
    - propertyName: temperature-status
      desired:
        metadata:
          type: string
        value: ''
```
**2. 根据以下yaml创建DeviceModel**
```
apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: temperature-model
  namespace: xapp
spec:
  properties:
    - name: temperature-status
      description: Temperature collected from the edge device
      type:
        string:
          accessMode: ReadOnly
          defaultValue: ''
```
**3. 根据以下yaml创建Device的传播策略**
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: temperature-propagation-qn01
  namespace: xapp
spec:
  resourceSelectors:
    - apiVersion: devices.kubeedge.io/v1alpha2
      kind: Device
      name: temperature
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-50
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cluster-50
            weight: 1
```
**4. 根据以下yaml创建DeviceModel的传播策略**
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: temperaturemodel-propagation-qn01
  namespace: xapp
spec:
  resourceSelectors:
    - apiVersion: devices.kubeedge.io/v1alpha2
      kind: DeviceModel
      name: temperature-model
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-50
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cluster-50
            weight: 1
```
**5. 最后在管理集群查询资源信息的结果（去掉敏感信息）**
```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  creationTimestamp: "2022-11-16T13:00:05Z"
  generation: 1
  labels:
    description: temperature
    manufacturer: test
    propagationpolicy.karmada.io/name: temperature-propagation-qn01
    propagationpolicy.karmada.io/namespace: xapp
  name: temperature
  namespace: xapp
  resourceVersion: "16571643"
  uid: xxxxxx
spec:
  deviceModelRef:
    name: temperature-model
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ""
        operator: In
        values:
        - raspberry-pi-node01
status:
  twins:
  - desired:
      metadata:
        type: string
      value: ""
    propertyName: temperature-status

```
**6. 作为对比最后在被纳管集群查询资源信息的结果（去掉敏感信息）**
```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  annotations:
    resourcebinding.karmada.io/name: temperature-device
    resourcebinding.karmada.io/namespace: xl-app-1562772936380780546
    resourcetemplate.karmada.io/uid: e20c5ec8-2490-4a58-9ddd-aaf5eb81df68
  creationTimestamp: "2022-11-16T13:01:39Z"
  generation: 1
  labels:
    description: temperature
    manufacturer: test
    propagationpolicy.karmada.io/name: temperature-propagation-qn01
    propagationpolicy.karmada.io/namespace: xapp
    resourcebinding.karmada.io/key: xxxxxx
    work.karmada.io/name: temperature-xxxxxx
    work.karmada.io/namespace: karmada-xxxxxxx
  name: temperature
  namespace: xapp
  resourceVersion: "35255917"
  selfLink: /apis/devices.kubeedge.io/v1alpha2/namespaces/xapp/devices/temperature
  uid: xxxxxx
spec:
  deviceModelRef:
    name: temperature-model
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ""
        operator: In
        values:
        - raspberry-pi-node01
```
**What do you think about this question?**:
可以发现确实在被纳管集群上，资源的status不见了，希望知道原因，谢谢

**Environment**:
- Karmada version: v1.3.0
- Kubernetes version: v1.22.10
- Others:

**Comment by lonelyCZ** [comment]
在下发work前，裁剪了workload中的一些字段

https://github.com/karmada-io/karmada/blob/06ca219b2b4c75a2f555407561b68db45288f77f/pkg/webhook/work/mutating.go#L38-L46

https://github.com/karmada-io/karmada/blob/06ca219b2b4c75a2f555407561b68db45288f77f/pkg/resourceinterpreter/defaultinterpreter/prune/prune.go#L49

`Device`这个对象为什么要在status中指定内容呢？一般情况下，这个status都是CR运行之后上报的状态，所以在下发的时候将这部分裁剪了。

**Comment by RainbowMango** [comment]
@quaminigin 你提交的`Device`原始yaml中包含 `status`吗？

默认status是不会向成员集群传播的，之所以成员集群中没有状态信息，是因为成员集群没有相应的控制器（controller）来生成状态信息。

**Comment by quaminigin** [comment]
> @quaminigin 你提交的`Device`原始yaml中包含 `status`吗？
> 
> 默认status是不会向成员集群传播的，之所以成员集群中没有状态信息，是因为成员集群没有相应的控制器（controller）来生成状态信息。

对。原始yaml有status。这个是kubeedge的Device的yaml的官方例子，有status的定义

**Comment by quaminigin** [comment]
> 在下发work前，裁剪了workload中的一些字段
> 
> https://github.com/karmada-io/karmada/blob/06ca219b2b4c75a2f555407561b68db45288f77f/pkg/webhook/work/mutating.go#L38-L46
> 
> https://github.com/karmada-io/karmada/blob/06ca219b2b4c75a2f555407561b68db45288f77f/pkg/resourceinterpreter/defaultinterpreter/prune/prune.go#L49
> 
> `Device`这个对象为什么要在status中指定内容呢？一般情况下，这个status都是CR运行之后上报的状态，所以在下发的时候将这部分裁剪了。

Kubeedge好像就是在status中定义了一些东西，这个是Device的yaml的官方例子，有status的定义

**Comment by RainbowMango** [comment]
[Device Model Sample](https://kubeedge.io/en/docs/developer/device_crd/#device-model-sample)里是没有status(一般也不会有status). 这个才是原始yaml.

[Device `Instance` Sample](https://kubeedge.io/en/docs/developer/device_crd/#device-instance-sample) 才有status, 这个展示的是完整的资源对象，不是原始的yaml.

**Comment by sunt89** [comment]
@RainbowMango 
https://github.com/kubeedge/kubeedge/blob/release-1.9/build/crds/devices/devices_v1alpha2_device.yaml

**Comment by sunt89** [comment]
@RainbowMango https://github.com/kubeedge/kubeedge/blob/release-1.9/build/crds/devices/devices_v1alpha2_device.yaml
这个是device的crd文件。   
里面有一段这个是需要自己定义的设备的孪生属性。  

status:
  twins:
    - propertyName: temperature-status
      desired:
        metadata:
          type: string
        value: ''

**Comment by RainbowMango** [comment]
Thanks @sunt89 .

Seems there is an open issue tracked this at KubeEdge: https://github.com/kubeedge/kubeedge/issues/679.

**Comment by quaminigin** [comment]
> [Device Model Sample](https://kubeedge.io/en/docs/developer/device_crd/#device-model-sample)里是没有status(一般也不会有status). 这个才是原始yaml.
> 
> [Device `Instance` Sample](https://kubeedge.io/en/docs/developer/device_crd/#device-instance-sample) 才有status, 这个展示的是完整的资源对象，不是原始的yaml.

seems they are two different kinds

**Comment by RainbowMango** [comment]
@quaminigin Yes, you are right. But nothing we can do until KubeEdge fixes this.
