### ISSUE TITLE
How to create namespace in part of cluster members

### ISSUE THREAD

**Issue by sunt89** [karmada-io/karmada#2860]
**Please provide an in-depth description of the question you have**:
I created the namespace on the Karmada control plane and it will be propagated to all the member clusters. But I would like to use a propagation policy to implement only partial propagation to the member cluster how can it be implemented

**Comment by RainbowMango** [comment]
/assign @Poor12 
We need to document this scenario.

**Comment by sunt89** [comment]
> Hi @sunt89, you can do this in two ways:
> 
> * Disable the `namespace` controller through `--controllers` flag, refer to [Configure Karmada Controllers](https://karmada.io/docs/administrator/configuration/configure-controllers/#configure-karmada-controllers).
> * We just introduced a label([Add label "namespace.karmada.io/skip-auto-propagation" to control whether to propagate ns to member clusters #2696](https://github.com/karmada-io/karmada/pull/2696)) that can be used to label the namespace resources that should be skipped from auto-propagation. refer to the [comment](https://github.com/karmada-io/karmada/issues/2512#issuecomment-1295756298).

Thank you
- I disable the namespace controller, and It solved my problem now.
