### ISSUE TITLE
 Workload not synced to control plane version

### ISSUE THREAD

**Issue by Rains6** [karmada-io/karmada#2863]
**What happened**:
When I send the deployment to multiple clusters, everything is ok. After one of the clusters fails and then recovers, I modify the delivered deployment on the cluster, and it is not synchronized back to the version of the karmada control plane.

**What you expected to happen**:
I hope to directly modify the distributed deployment on the cluster, which can be automatically synchronized back to the version of the karmada control plane

**How to reproduce it (as minimally and precisely as possible)**:
Send the deployment to multiple clusters, After one of the clusters fails and then recovers, modify the delivered deployment on the cluster, and it is not synchronized back to the version of the karmada control plane.

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.3.0

**Comment by calvin0327** [comment]
@Rains6 what version your say, `resourceVersion`？ or else?

**Comment by Rains6** [comment]
> @Rains6 what version your say, `resourceVersion`？ or else?

Resource template of the karmada control plane

**Comment by Poor12** [comment]
Reproduction：
1. `Failover` is close.
2. Deploy a deployment to m1 and m2.
3. m1 apiserver failed. The cluster status of m1 became false. Soon it recovered. The cluster status of m1 became true again.
4. Update the deployment in m1. But the control plane cannot perceive the change of deployment in m1.

Reason:
Informer of m1 didn't work and could not collect update events.

Solutions:
1. work-status-controller can perceive the change of cluster status and re-start the informers.
2. cluster-status-controller can re-start the informers when the cluster state is restored.

**Comment by RainbowMango** [comment]
Seems it's a serious problem.
/priority important-soon

Please try to find the root cause and then talk about the solutions.

/assign @Poor12
