### ISSUE TITLE
install use local-up-karmada.sh fail

### ISSUE THREAD

**Issue by flystarts** [karmada-io/karmada#287]
**What happened**:
[root@c2 /opt/gopath/src]$git clone https://github.com/karmada-io/karmada
[root@c2 /opt/gopath/src]$cd karmada
[root@c2 /opt/gopath/src/karmada]$hack/local-up-karmada.sh
Error: unknown flag: --kubeconfig

**What you expected to happen**:
install success

**How to reproduce it (as minimally and precisely as possible)**:
just exec  “hack/local-up-karmada.sh”
**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- Others:

**Comment by RainbowMango** [comment]
Hi @flystarts, I just the script against [master](https://github.com/karmada-io/karmada/commit/419a7076eb434a69ecfc4dcc6e9e002c64ce053b), and this works.

Which version of kind you are using?
I guess your `kind` version is too old that not support `--kubeconfig` flag.

**Comment by flystarts** [comment]
A very nice, easy and working solution. Good work and thanks

**Comment by RainbowMango** [comment]
You are welcome! I'm glad to help you.
