### ISSUE TITLE
Unidirectional network question

### ISSUE THREAD

**Issue by SZT0728** [karmada-io/karmada#2890]
If the member cluster's network can access the karmada-control plane,but the karmada-control plane's network can't access the member cluster, and i register the member cluster using Pull mode. Can i access the member cluster using ANP(apiserver-network-proxy)?

**Comment by XiShanYongYe-Chang** [comment]
Yes, it can be done

**Comment by SZT0728** [comment]
> Yes, it can be done

which member'IP should register the karmada-control plane ? 
my member cluster is the k8s in docker-desktop, and it's default apiserver is `https://kubernetes.docker.internal:6443`
so after i registerd and get cluster in karmada-control plane like below:
<img width="1036" alt="截屏2022-11-30 下午3 59 18" src="https://user-images.githubusercontent.com/15276000/204739892-9e4ea3c9-f8b3-4d36-96a5-c081df402620.png">
after i deploy ANP in karmada-control plane and member cluster,i access the member cluster using aggregated Api ,it through the error:

**Comment by XiShanYongYe-Chang** [comment]
Take a look with https://karmada.io/docs/next/userguide/clustermanager/working-with-anp/

**Comment by SZT0728** [comment]
> https://karmada.io/docs/next/userguide/clustermanager/working-with-anp/

yes,i already look it,and deploy ANP proxy server and agent success

**Comment by XiShanYongYe-Chang** [comment]
The value of `--cluster-api-endpoint` may not be filled in correctly. Does your k8s API endpoint not have an IP address?

**Comment by SZT0728** [comment]
> The value of `--cluster-api-endpoint` may not be filled in correctly. Does your k8s API endpoint not have an IP address?

yes, it doesn't have the Public IP address. the member cluster and the karmada-control plane in the different Network plane. The karmada-control plane can't access the member cluster directly. Just like my computer can access the baidu server, but the baidu server can't access my computer directly

**Comment by XiShanYongYe-Chang** [comment]
The anp server may not be able to resolve the domain name.

**Comment by SZT0728** [comment]
> The anp server may not be able to resolve the domain name.
yes,that's right.
so for the case member cluster and karmada-control plane in different Network plane, is really the karmada-control plane can access the member cluster directly?

**Comment by XiShanYongYe-Chang** [comment]
> so for the case member cluster and karmada-control plane in different Network plane, is really the karmada-control plane can access the member cluster directly?

As I can see, the network is connected through the ANP. If the ANP is connected successfully, the member cluster can be accessed from the control plane.

**Comment by Poor12** [comment]
/close
Feel free to reopen this issue if you have any questions.
