### ISSUE TITLE
the server could not find the requested resource (get clusters.cluster.karmada.io)

### ISSUE THREAD

**Issue by Kostavro** [karmada-io/karmada#2892]
**What happened**:
Failure to join cluster.
Error:
```
Error from server (NotFound): the server could not find the requested resource (get clusters.cluster.karmada.io)
```

**What you expected to happen**:
The cluster to join as a member.

**How to reproduce it (as minimally and precisely as possible)**:
Have two clusters on AWS EKS, on separate VPCs, with private API endpoints.
Install Karmada on cluster1 via the Helm chart (also tried via `remote-up-karmada.sh`).
Export kube context of both clusters.
Try to run `kubectl karmada join ...`.

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest

- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): kubectl karmada version: version.Info{GitVersion:"v1.3.2", GitCommit:"a79d18cff04c77bd5ee4b6e747d24417f4cac478", GitTreeState:"clean", BuildDate:"2022-11-24T03:00:49Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}

- Others:

**Comment by RainbowMango** [comment]
Hi @Kostavro,

> Export kube context of both clusters.

Do you mean you combined two cluster configs into one `kubeconfig` file? 
If it is the case, you might need to specify `--karmada-context=` in addition to `--kubeconfig`. As well as the `--cluster-context=''`.

> Try to run kubectl karmada join ...

Can you share the whole command here?
As well as more outputs, thanks.

**Comment by Kostavro** [comment]
Hey @RainbowMango , thanks for the quick response. Here's some more info on what I run:

```
$ aws eks update-kubeconfig --name cluster1 --alias cluster1 --region eu-central-1 --kubeconfig /tmp/kube.cluster_one.config
Added new context cluster1 to /tmp/kube.cluster_one.config

$ aws eks update-kubeconfig --name cluster2 --alias cluster2 --region eu-central-1 --kubeconfig /tmp/kube.cluster_one.config
Added new context cluster2 to /tmp/kube.cluster_one.config

$ kubectl karmada join cluster2 --kubeconfig=/tmp/kube.cluster_one.config --karmada-context=cluster1 --cluster-kubeconfig=/tmp/kube.cluster_one.config --cluster-context=cluster2
Error from server (NotFound): the server could not find the requested resource (get clusters.cluster.karmada.io)
```
All pods look healthy.

**Comment by RainbowMango** [comment]
> I realized I was querying the apiserver of the cluster and not the apiserver of karmada

Yes, this is probably the root cause.  Seems the query is against a cluster's apiserver that not installed the `clusters.cluster.karmada.io` API.

> $ kubectl karmada join cluster2 --kubeconfig=/tmp/kube.cluster_one.config --karmada-context=cluster1

Seems the `--karmada-context` points to cluster1's apiserver. 
After you installed Karmada on cluster1, then you should use the configuration of karmada's apiserver to join another cluster.
