### ISSUE TITLE
Why Karmada will replace member-cluster namespace label ?  question about Istio sidecar.

### ISSUE THREAD

**Issue by SAMZONG** [karmada-io/karmada#2896]
a real scene!

about this: https://karmada.io/docs/userguide/service/working-with-istio-on-non-flat-network

we desgin karmada working with Istio, BUT GET SOME BAD THING.

When I enable auto sidercar in a Namespace, will need add label at namespace, like `kubectl label namespace <namespace> istio-injection=enabled`

when I in karmadaadd add this label, it's can be work. but in istio CAN NOT!

How can do it in istio, and will not be reset by karmada?

https://istio.io/latest/blog/2019/data-plane-setup/#automatic-injection

**Comment by XiShanYongYe-Chang** [comment]
Generally, karmada overwrites resources on member clusters. You can customize conflicting behaviors by configuring resource interpreters, focusing on `Retain` operations: https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/

Given the commonness of labels, we can also consider embedding their logic into karmada logic, such as [annotation](https://github.com/karmada-io/karmada/blob/97e859525af30a1a67639f33ffad83996888328a/pkg/util/objectwatcher/objectwatcher.go#L139), but we need to fully discuss the specific plan.

**Comment by RainbowMango** [comment]
> when I in karmadaadd add this label, it's can be work. but in istio CAN NOT!

sorry, I didn't get it. What do you mean `in istio can not`?

**Comment by SAMZONG** [comment]
> > when I in karmadaadd add this label, it's can be work. but in istio CAN NOT!
> 
> 
> 
> sorry, I didn't get it. What do you mean `in istio can not`?

use istio add namespace label， it will be reset by karmada. Because karmada control it at now.

**Comment by chaunceyjiang** [comment]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/17962021/205536456-4aa9a182-c1c4-43bf-88ed-d8cc42231d75.png">

Department B cannot modify namespace1.

**Comment by chaunceyjiang** [comment]
According to the minutes of the meeting, the `labels` needs to be consistent with the behavior of `annotation`, right?
Like https://github.com/karmada-io/karmada/blob/master/pkg/util/objectwatcher/objectwatcher.go#L139

**Comment by XiShanYongYe-Chang** [comment]
> According to the minutes of the meeting, the `labels` needs to be consistent with the behavior of `annotation`, right?
> Like https://github.com/karmada-io/karmada/blob/master/pkg/util/objectwatcher/objectwatcher.go#L139

Yes

**Comment by XiShanYongYe-Chang** [comment]
> According to the minutes of the meeting, the `labels` needs to be consistent with the behavior of `annotation`, right?
> Like https://github.com/karmada-io/karmada/blob/master/pkg/util/objectwatcher/objectwatcher.go#L139

In addition, as discussed at the meeting, we need to add an annotation to record the annotations/labels that Karmad's control plane is responsible for.

**Comment by chaunceyjiang** [comment]
> In addition, as discussed at the meeting, we need to add an annotation to record the annotations/labels that Karmad's control plane is responsible for.

Yes, such as `label-managed-by-karmada: [key1,key2,key3]` and `annotation-managed-by-karmada: [key1,key2,key3]` ?

**Comment by RainbowMango** [comment]
> In addition, as discussed at the meeting, we need to add an annotation to record the annotations/labels that Karmad's control plane is responsible for.

That's out of the scope of this issue. 

The idea could be used to solve label/annotation removing scenarios.

**Comment by SAMZONG** [comment]
> > In addition, as discussed at the meeting, we need to add an annotation to record the annotations/labels that Karmad's control plane is responsible for.
> 
> Yes, such as `label-managed-by-karmada: [key1,key2,key3]` and `annotation-managed-by-karmada: [key1,key2,key3]` ?

this's another topic
