### ISSUE TITLE
Support karmadactl create to propagate long-size yaml resource

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#2920]
**What would you like to be added**:
#1934 , we support `karmadactl apply` to propagate long-size yaml resources. However, `kubectl apply` is a bit function-limited, specially when creating crds.  I think we should import `karmdactl create` in the same time.

**Why is this needed**:

**Comment by lonelyCZ** [comment]
It is useful. We can refer to the `karmadactl apply` command to realize it.

/help

**Comment by RainbowMango** [comment]
> However, kubectl apply is a bit function-limited, specially when creating crds.

What kind of limited functions? An example?

**Comment by lonelyCZ** [comment]
The process of recuring problem:
```
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.63.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml

[root@master67 prometheus]# kubectl apply -f monitoring.coreos.com_prometheuses.yaml
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

But refering to https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/, It can be salved by option `--server-side` of `kubectl apply`

```
[root@master67 prometheus]# kubectl apply -f monitoring.coreos.com_prometheuses.yaml --server-side
customresourcedefinition.apiextensions.k8s.io/prometheuses.monitoring.coreos.com serverside-applied
```

But it is convinent to create resources quickly like `karmadactl create ns xxx --all-clusters`

So do we also need `create` command?

cc @RainbowMango @Poor12

**Comment by RainbowMango** [comment]
> But it is convinent to create resources quickly like karmadactl create ns xxx --all-clusters

Currently, the user can only do that by adding an extra `--server-side=true` flag to `karmadactl apply`, right?
like `karmadactl apply -f xxx.xml --all-clusters --server-side=true`.

**Comment by lonelyCZ** [comment]
> Currently, the user can only do that by adding an extra --server-side=true flag to karmadactl apply, right?

Yes, it need `--server-side=true` for applying too large yaml files. Because `apply` command can push the resource template to annotation filed, but the maximum length of `annotation` is 256K.

**Comment by RainbowMango** [comment]
OK. I get it. I'm fine with that. It's your call. @lonelyCZ
