### ISSUE TITLE
cherry-pick of #2915(fix karmadactl default validating config)

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#2921]
We need to cherry-pick #2915 for the following release branches:
- [x] release-1.2 (https://github.com/karmada-io/karmada/pull/2922)
- [ ] release-1.3 (https://github.com/karmada-io/karmada/pull/2923)
- [ ] release-1.4 (https://github.com/karmada-io/karmada/pull/2924)

**Comment by qingwave** [comment]
Hi @RainbowMango, could I assign this task?

**Comment by RainbowMango** [comment]
Yes, sure. Thanks in advance.
/assign @qingwave 

Just a suggestion, you can try with the scripts mentioned in [How to cherry-pick PRs](https://karmada.io/docs/contributor/cherry-picks), it really helps when you are going to cherry-pick a PR to more than one branch.

**Comment by XiShanYongYe-Chang** [comment]
Thanks for @qingwave 's work, this job has been finished.
/close
