### ISSUE TITLE
Clean up kind clusters in quickstart demo.

### ISSUE THREAD

**Issue by qingwave** [karmada-io/karmada#2926]
**What would you like to be added**:
Now, in the [quickstart](https://github.com/karmada-io/karmada#3-deploy-and-run-karmada-control-plane), we only create the karmada clusters via `hack/local-up-karmada.sh`, another step(just use `kind delete`) or a script should be added in the ReadMe/quickstart to cleanup all demo cluters.

**Why is this needed**:
Clean up step is a necessary step for the demo.

**Comment by calvin0327** [comment]
now, it's seem not a script to delete those kind cluster created by exec `hack/local-up-karmada.sh`.

**Comment by qingwave** [comment]
> /assign Can I apply for this assignment?

@Fish-pro Sure, feel free to solve this issue.
