### ISSUE TITLE
UpdateRevision in aggregateStatefulSetStatus is needed

### ISSUE THREAD

**Issue by hanzai** [karmada-io/karmada#2948]
**What would you like to be added**:
Accessibility of updateRevision in the status of statefulset from karmada-control-plane is needed.

**Why is this needed**:
We attempt to control the upgrade process of pods in the member clusters. Our operator get the pods through karmada-search and get statefulset from karmada-control-plane, then find pods to be upgraded by comparing UpdateRevision in the status of statefulset and controller-revision-hash in the labels of pod. Without UpdateRevision the operator is unable to find which pods have bean upgraded.

**Comment by XiShanYongYe-Chang** [comment]
The `UpdateRevision` field is a string type and cannot be simply added during aggregation like the `UpdatedReplicas` field. What kind of aggregation do you want?

**Comment by RainbowMango** [comment]
Glad to hear that you are using `karmada-search`. Maybe you can get the status from `ResourceBinding`.

**Comment by XiShanYongYe-Chang** [comment]
> aggregateStatefulSetStatus. UpdateRevision could be a base64-encoded json string like multiClusterResourceVersion, I suppose.

Hi @hanzai, this may destroy the meaning of the original field, so this action may be destructive. Perhaps you can use [Customizing Resource Interpreter](https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/) to define your own interpretation of `StatefulSetStatus` resource.

Or, as @RainbowMango says, the information can be obtained from the `ResourceBinding`.

**Comment by hanzai** [comment]
The default interpreter of `StatefulSetStatus` doesn't handle `UpdateRevision` field. Consequently,  `Work` and `ResourceBinding`  do not have this field. 

![image](https://user-images.githubusercontent.com/1121360/207221336-720e9d05-9450-4613-b575-1f451e15c8b5.png)

It will be an optimization to provide UpdateRevision in aggregateStatefulSetStatus. Stateful applications can benefit a lot from this feature.

At this stage, Customizing Resource Interpreter maybe is a better choice. I will try it.

**Comment by XiShanYongYe-Chang** [comment]
> The default interpreter of `StatefulSetStatus` doesn't handle `UpdateRevision` field. Consequently, `Work` and `ResourceBinding` do not have this field.

We can add the `UpdateRevision` field in the process of status collection `ReflectStatus`.

> It will be an optimization to provide UpdateRevision in aggregateStatefulSetStatus. Stateful applications can benefit a lot from this feature.

cc @RainbowMango tale a look.

**Comment by RainbowMango** [comment]
Sounds like a reasonable feature.
But I'd like to know more details about your scenario.

@hanzai Are you using Karmada now? or in the progress of evaluation?

**Comment by hanzai** [comment]
> Sounds like a reasonable feature. But I'd like to know more details about your scenario.
> 
> @hanzai Are you using Karmada now? or in the progress of evaluation?

We are planning to deploy stateful distributed system across clusters through karmada.

![image](https://user-images.githubusercontent.com/1121360/207491610-60e65663-461a-42a1-ba84-a01e59f96cfd.png)

**Comment by RainbowMango** [comment]
Great! That must be an exciting use case.
Feel free to contact me if you need any support, you can find my email [here](https://github.com/RainbowMango).

> At this stage, Customizing Resource Interpreter maybe is a better choice. I will try it.

Yes, you can use the Customizing Resource Interpreter, it won't block you.
And looking forward to hearing more feedback about your practice, we can consider collecting the `UpdateRevision` by default.

**Comment by Poor12** [comment]
/close
Feel free to reopen this issue if you have any questions.
