### ISSUE TITLE
sample object does not work

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#2965]
**What happened**:
Samples in `samples/nginx/` does not work.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl create -f samples/nginx/

kubectl describe deployments.apps nginx

```

You will see a warning `  Warning  SyncWorkFailed             2s (x10 over 4s)  binding-controller  add operation does not apply: doc is missing path: "/metadata/annotations/env": missing value`, and this deployment could not be propagated to member clusters.

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Thanks to both of you @chaunceyjiang @Garrybest

**Comment by chaunceyjiang** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/17962021/208068485-5bc7e0f2-5e09-486b-9e70-d76b9ea3af0a.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/17962021/208068379-fed0c875-264d-4a89-8804-b2d22324d6b0.png">


hi, @Garrybest 

It is normal for me to use the master branch code to build karmada. Are you sure you use the master branch?

**Comment by RainbowMango** [comment]
@chaunceyjiang Can you explain the root cause a little bit here?

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/8bcfd7810b56fe075c0051899892965f8897fdf0/samples/nginx/overridepolicy.yaml#L32-L35

https://github.com/karmada-io/karmada/blob/8bcfd7810b56fe075c0051899892965f8897fdf0/pkg/util/overridemanager/labelannotationoverrider.go#L43-L47



https://go.dev/play/p/-Maxaghj-yU


The `annotations/labels` field does not exist has not been handled.

**Comment by RainbowMango** [comment]
I get it the root cause is we missed the case that `.metadata.annotation` might be `nil`, so we can't just patch a new annotation item to it.

> When testing locally, I used kubectl create - f samples/nginx/. This command will automatically add a annotation of kubectl.kubernetes.io/last-applied-configuration so this cease was not tested.

Seems the command(`kubectl create - f samples/nginx/`) is same as the one in PR description.( `- f` should be `-f` by the way).
Do you mean, in your environment, the `kubectl.kubernetes.io/last-applied-configuration` will be added automatically, but not in @Garrybest's?
What version of the `kube-apiserver` are you using?

**Comment by chaunceyjiang** [comment]
> When testing locally, I used  ~~kubectl create - f samples/nginx/~~ . This command will automatically add a annotation of kubectl.kubernetes.io/last-applied-configuration so this cease was not tested.

When testing locally, I used  `kubectl apply - f samples/nginx/` . This command will automatically add a annotation of kubectl.kubernetes.io/last-applied-configuration so this cease was not tested.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/17962021/208220066-45e7035c-1514-4f4a-b7b2-de7381023f5c.png">

**Comment by RainbowMango** [comment]
I get it. `apply` vs `create`. :)
