### ISSUE TITLE
Add E2E cases for Replica Scheduling Policy feature

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#297]
**What would you like to be added**:
We implemented ReplicaSchedulingPolicy feature by #269, but there are no E2E cases that cover this feature.

Maybe we need two cases:
- Basic functionality: A deployment's replicas could split by static weight list referencing by ReplicaSchedulingPolicy.
- Once the weight list changes, the replicas should be re-scheduled.

PS: There is some discussion at #192 that can help to understand this feature.

**Need your help**:
If you interest in this task or have any questions, please feel free to reply on this issue.

**Comment by jrkeen** [comment]
I will do this.

**Comment by RainbowMango** [comment]
Hi @jrkeen 
I appreciate you can help, but we are discussing a new API for this feature at #452.
That means the `ReplicaSchedulingPolicy` feature may be deprecated.

I don't want to waste your time, let's just hold for a while.

**Comment by RainbowMango** [comment]
To reduce the noise, I'm going to close this issue.
/close
