### ISSUE TITLE
karmada-agent keep logging error about resourceinterpretercustomizations resource

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#2982]
**What happened**:
Init the host plane with karmadactl init, and then register the member cluster with karmadactl.
karmada-agent keep logging error about resourceinterpretercustomizations resource like follows:
```log
I1221 03:41:17.731728       1 reflector.go:257] Listing and watching *unstructured.Unstructured from k8s.io/client-go/dynamic/dynamicinformer/informer.go:91
W1221 03:41:17.732840       1 reflector.go:424] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: failed to list *unstructured.Unstructured: resourceinterpretercustomizations.config.karmada.io is forbidden: User "system:node:kind-karmada-member" cannot list resource "resourceinterpretercustomizations" in API group "config.karmada.io" at the cluster scope
E1221 03:41:17.732866       1 reflector.go:140] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: resourceinterpretercustomizations.config.karmada.io is forbidden: User "system:node:kind-karmada-member" cannot list resource "resourceinterpretercustomizations" in API group "config.karmada.io" at the cluster scope
I1221 03:41:26.540278       1 cluster_status_controller.go:109] Syncing cluster status: kind-karmada-member
I1221 03:41:36.551038       1 cluster_status_controller.go:109] Syncing cluster status: kind-karmada-member
```
But with hack/local-up-karmada.sh, there is no error log.

**What you expected to happen**:
No error log

**How to reproduce it (as minimally and precisely as possible)**:
1. clone Karmada repo
2. checkout to release-1.4 branch and build karmadactl
3. Creat a host plane and member cluster plane with KinD
4. Init host plane with karmadactl.
5. Register member cluster in pull mode with karmadactl.
6. Check the logs of karmada-agent

**Anything else we need to know?**:
none

**Environment**:
- Karmada version: v1.4.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):release-1.4 branch
- Others:

**Comment by jwcesign** [comment]
cc @lonelyCZ @XiShanYongYe-Chang

**Comment by lonelyCZ** [comment]
It seems to need the `resourceinterpretercustomizations` permission. 

https://github.com/karmada-io/karmada/blob/9068240ab09a475a25b3574e97987e2b6758506c/pkg/karmadactl/cmdinit/karmada/rbac.go#L47-L48

**Comment by jwcesign** [comment]
@lonelyCZ Thanks, let me try

**Comment by jwcesign** [comment]
It works, and will give a PR.
