### ISSUE TITLE
The expiration time of the cert

### ISSUE THREAD

**Issue by hexiaofeng** [karmada-io/karmada#2985]
The expiration time of the cert by  kubectl-karmada is 1 year

``` golang
func (i *CommandInitOption) genCerts() error {
	notAfter := time.Now().Add(cert.Duration365d).UTC()
        ......
}
```

The expiration time of the cert by  deploy-karmada.sh is 10 years

```  shell
function util::create_signing_certkey {
    ......
    ${OPENSSL_BIN} req -x509 -sha256 -new -nodes -days 3650 -newkey rsa:2048 -keyout "${dest_dir}/${id}.key" -out "${dest_dir}/${id}.crt" -subj "/CN=${cn}/"
    ......
}
``` 

Expectations are 10 years

**Comment by lonelyCZ** [comment]
We could make it configurable.

Hi, @hexiaofeng ， would you like to take this work?

**Comment by hexiaofeng** [comment]
> We could make it configurable.
> 
> Hi, @hexiaofeng ， would you like to take this work?

I'm willing to do this

**Comment by RainbowMango** [comment]
> I'm willing to do this

Thanks.
/assign @hexiaofeng
