### ISSUE TITLE
[HelpWanted] ClusterResourceBinding should only reference cluster-scoped resources

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#300]
**What would you like to be added**:
When [applying cluster policy](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/util/detector/detector.go#L338) for a resource template, we should build [ResourceBinding](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/apis/work/v1alpha1/binding_types.go#L13) for namespace-scoped resources, and build [ClusterResourceBinding](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/apis/work/v1alpha1/binding_types.go#L102) for cluster-scoped resources.

But currently, we always build [ClusterResourceBinding](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/apis/work/v1alpha1/binding_types.go#L102) and regardless of the resource scope.  The relevant code at :
https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/util/detector/detector.go#L346-L354

**Why is this needed**:
[ResourceBinding](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/apis/work/v1alpha1/binding_types.go#L13) is designed for binding namespace scoped resources and [ClusterResourceBinding](https://github.com/karmada-io/karmada/blob/46de97140ea05de5809f00e337277c209f3b1c2c/pkg/apis/work/v1alpha1/binding_types.go#L102) is designed for binding cluster scoped resources.

**Comment by vincent-pli** [comment]
@RainbowMango 
So when you `apply policy`, do you need consider to build `ClusterResourceBinding`?

**Comment by RainbowMango** [comment]
No, the `PropagationPolicy` can only match namespace-scoped resources, such as deployment, so when applying PropagationPolicy, we only need to build `ResourceBinding`.
@vincent-pli thanks for asking, would like to try this?

**Comment by vincent-pli** [comment]
Sure, I'd like to take a look @RainbowMango

**Comment by vincent-pli** [comment]
Checked the code, so we will decide to create `resourcebinding` or `clusterresourcebinding` based on if the `object` has `namespace` field (correct me)?
That's make sense but one problem:  when user defined in `ClusterPropagationPolicy.ResourceSelectors`,  a namespace scope resource in namespace `default` maybe has no `namespace`.

In `PropagationPolicy` scenario, the `namespace` of resource will be set as `PropagationPolicy.namespace` if nil in webhook.

So, do we refer to let user know the requirement or introduce `client-go.discovery` to make sure it's a namespace scoped or cluster scope before create `binding`s. @RainbowMango

**Comment by RainbowMango** [comment]
I can tell that you have gone through quite a lot of relevant codes.
We are going to create `binding` objects via `object`s which are retrieved from karmada-apiserver, they do have a namespace even they are in `default` namespace. (kube-apiserver set the default ns).

The `ResourceSelectors` defines the rule for `objects` to match, the `namespace` in it may be empty.

**Comment by vincent-pli** [comment]
@RainbowMango 
>The ResourceSelectors defines the rule for objects to match, the namespace in it may be empty.

That's exactly what I talk about, do you think we need to handle it?
