### ISSUE TITLE
How to prevent deletion of resources for member clusters?

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#3004]
**Please provide an in-depth description of the question you have**:

I used the following command by mistake. Now I want to delete coredns on the control plane, but I don’t want to delete the coredns of the member cluster. How should I do it?

```
karmadactl promote deployment coredns -n kube-system -C cluster1
```

**What do you think about this question?**:

**Environment**:
- Karmada version: v.1.4.0
- Kubernetes version: 
- Others:

**Comment by RainbowMango** [comment]
We have a draft proposal for this:https://github.com/karmada-io/karmada/tree/master/docs/proposals/cleanup-propagated-resources

The proposal is not to solve the `mistake` but to provide a mechanism to control if the resource should be removed from member clusters.

**Comment by chaunceyjiang** [comment]
> provide a mechanism to control if the resource should be removed from member clusters.

> This document proposes a mechanism to specify that a member cluster resource should be removed from a managed cluster when **leaving**.

I don't want to remove the member cluster, I just want to delete the `coredns` of the control plane.

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/d1617303a41c9fb472e29550acd16dc4cbd1320d/pkg/util/constants.go#L12-L18

I think we can extend this instruction.

**Comment by sunbinnnnn** [comment]
I got the same case, my workaround is stopping the controller, and force delete RB, workload and WORK, then start the controller...

**Comment by chaunceyjiang** [comment]
>  and almost cause terrible disaster. 

Yes

> my workaround is stopping the controller, and force delete RB, workload and WORK, then start the controller...

This operation has caused me a lot of trouble.

**Comment by RainbowMango** [comment]
I'm trying to figure out which PR/Issue should be included in the coming v1.7 release which is planned at the end of this month.
I guess we don't have enough time for this feature, so I'm moving this to v1.8.

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaunceyjiang Do you need to keep work at the same time in your use case?

Ref https://github.com/karmada-io/karmada/pull/4788#discussion_r1575971218

**Comment by RainbowMango** [comment]
This issue could be resolved by https://github.com/karmada-io/karmada/issues/5577#issuecomment-2372856091.

/close
