### ISSUE TITLE
The connection to the server was refused

### ISSUE THREAD

**Issue by Fatimastm** [karmada-io/karmada#3022]
**What happened**:
Karmada suddenly stopped working:
couldn't get current server API group list: Get "https://172.20.0.2:5433/api?timeout=32s": dial tcp 172.20.0.2:5433: connect: connection refused
The connection to the server 172.20.0.2:5433 was refused - did you specify the right host or port?

**Anything else we need to know?**:
I installed karmada with `hack/local-up-karmada.sh` script. I expected to see three member clusters by default however only one kind cluster 'kind-member2' was created. Control plane was running fine. 

**Environment**:
- Karmada version: v1.4.1

**Comment by RainbowMango** [comment]
> I installed karmada with hack/local-up-karmada.sh script. I expected to see three member clusters by default however only one kind cluster 'kind-member2' was created.

Any error logs raised by `hack/local-up-karmada.sh`? During the startup, the script will `join` the cluster, at least `member1` and `member2` clusters should be ready, otherwise the error log will be dumped out.

**Comment by Fatimastm** [comment]
> > I installed karmada with hack/local-up-karmada.sh script. I expected to see three member clusters by default however only one kind cluster 'kind-member2' was created.
> 
> Any error logs raised by `hack/local-up-karmada.sh`? During the startup, the script will `join` the cluster, at least `member1` and `member2` clusters should be ready, otherwise the error log will be dumped out.

**Comment by Fatimastm** [comment]
Actually I tried to install karmada twice (followed the same instructions as before to install successfully prior versions(1.2 and 1.3)). First time, karmada did not deploy successfully and second time deployed with one member cluster. 
> Any error logs raised by `hack/local-up-karmada.sh`? During the startup, the script will `join` the cluster, at least `member1` and `member2` clusters should be ready, otherwise the error log will be dumped out.
Yes. I have gotten _time out_ error. I checked the status of control plane and once I was sure that it is working fine, I did some test like joining kind cluster to karmada without error, or testing a nginx deployment without error. From today karmada has stopped working.

**Comment by RainbowMango** [comment]
> Yes. I have gotten time out error.

Can you show the raw logs here?

Just a guess, there might be you don't have enough resources to launch multiple kind clusters.
Since `hack/local-up-karmada.sh` would launch clusters in parallel, and you can get the logs from `/tmp/karmada/<cluster_name>.log`. Please check the logs there.

**Comment by Fatimastm** [comment]
> Can you show the raw logs here?


> service/karmada-webhook created
> wait the karmada-controller-manager ready...
> pod/karmada-controller-manager-758b45d96-6zm5p condition met
> pod/karmada-controller-manager-758b45d96-cndtr condition met
> wait the karmada-scheduler ready...
> pod/karmada-scheduler-5754f84499-4ck5p condition met
> pod/karmada-scheduler-5754f84499-fjx6n condition met
> wait the kube-controller-manager ready...
> pod/karmada-kube-controller-manager-7668954bbc-z6hnx condition met
> wait the karmada-webhook ready...
> pod/karmada-webhook-7674f5cfdd-v95h5 condition met
> pod/karmada-webhook-7674f5cfdd-w49lc condition met
> Waiting for kubeconfig file /home/mehr/.kube/members.config and clusters member1 to be ready...
> Waiting for running............................................................................................................................................................................................................................................................................................................
> [ERROR] Timeout waiting for condition running

**Comment by jwcesign** [comment]
> Yes. I have gotten time out error. 
Try:
```sh
sysctl fs.inotify.max_user_watches=16384
sysctl -w fs.inotify.max_user_watches=100000
sysctl -w fs.inotify.max_user_instances=100000
```

**Comment by RainbowMango** [comment]
Hi @Fatimastm, have you checked the logs(/tmp/karmada/<cluster_name>.log)?

If you met the kind issue below, you can try the workaround as mentioned by @jwcesign above.

https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

**Comment by Fatimastm** [comment]
> Hi @Fatimastm, have you checked the logs(/tmp/karmada/<cluster_name>.log)?
>
Yes. It's log file of member3:

> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
> k8s.io/kubernetes/cmd/kubeadm/app.Run
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
> main.main
>         _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
> runtime.main
>         /usr/local/go/src/runtime/proc.go:255
> runtime.goexit
>         /usr/local/go/src/runtime/asm_amd64.s:1581
> error execution phase addon/kube-proxy
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
> k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
> k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
> k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
> k8s.io/kubernetes/cmd/kubeadm/app.Run
>         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
> main.main
>         _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
> runtime.main
>         /usr/local/go/src/runtime/proc.go:255
> runtime.goexit
>         /usr/local/go/src/runtime/asm_amd64.s:1581
> If you met the kind issue below, you can try the workaround as mentioned by @jwcesign above.
That's work.

**Comment by Fatimastm** [comment]
> > Yes. I have gotten time out error.
> 
> Try:
> 
> ```shell
> sysctl fs.inotify.max_user_watches=16384
> sysctl -w fs.inotify.max_user_watches=100000
> sysctl -w fs.inotify.max_user_instances=100000
> ```

That works. Thanks

**Comment by RainbowMango** [comment]
Congrats!
I'm going to close it now.
/remove-kind bug
/kind question
/close
