### ISSUE TITLE
do not use Kind to install karmada

### ISSUE THREAD

**Issue by zqzzq** [karmada-io/karmada#303]
**What would you like to be added**:
Can I install karmada without Kind? I already have a running cluster, can I directly install karmada in this cluster？I found no documentation on this.
**Why is this needed**:
When I installed karmada with Kind, I had a lot of network problems and it was very unfriendly.

**Comment by RainbowMango** [comment]
> Can I install karmada without Kind?

The answer is definitely yes. We are using `kind` just for development. You can run the karmada control plane components anywhere, include your running cluster. 

Currently, we install karmada by yamls, you can find them at [here](https://github.com/karmada-io/karmada/tree/master/artifacts/deploy), and we have a plan to provide a helm chart to simplify the installation.

By the way, anyone who interests in this could join and help.

**Comment by zqzzq** [comment]
Very thanks, closed this.
