### ISSUE TITLE
the flag description for karmada-scheduler-estimator is wrong

### ISSUE THREAD

**Issue by Wang-Kai** [karmada-io/karmada#3038]
**What happened**:

the flag description `--kubeconfig` for `karmada-scheduler-estimator` is wrong .

**What you expected to happen**:

Path to member cluster kubeconfig file

**How to reproduce it (as minimally and precisely as possible)**:

```console
karmada-scheduler-estimator --help
```
**Anything else we need to know?**:

The karmada-scheduler-estimator component use member cluster's kubeconfig, not the karmada control plane's kubeconfig

**Environment**:
- Karmada version: v1..4.1

**Comment by RainbowMango** [comment]
/assign @Wang-Kai 
Thanks for spotting.
