### ISSUE TITLE
one questions

### ISSUE THREAD

**Issue by cfw11** [karmada-io/karmada#304]
### Hi, I have one questions.
+ 1、In the roadmap 2021 Q4, Multi-cluster monitoring & Logging, Is to support query log or exec pod which in work cluster from karmada cluster ?

**Comment by RainbowMango** [comment]
> In the roadmap 2021 Q4, Multi-cluster monitoring & Logging, Is to support query log or exec work cluster pod from master cluster or whether karmada-etcd will save the the member clusters pod infomation。

Yeah, we hope people can query logs from karmada control plane. Not sure if this will stores in ETCD yet. 
Can you explain your use case about `exec work cluster pod`? 

> Is have a plan to support updating a deployment resource in work cluster, than the updated deployment resource will sync to master cluster?

Yes, we will provide a mechanism for people to specify the fields(or resources) that people want to manage. If I understand correctly, that usually happens in scenarios where controllers running in the member clusters and the controllers might be updating the objects.

We'll be appreciated if you want to share your case here.

**Comment by cfw11** [comment]
#### Thinks for answer!  

> Can you explain your use case about exec work cluster pod?

I think it is easy to support `exec` if  query workcluster pod log by  calling apiserver of work cluster in the future, the case is can debug in karmada cluster, but is not important.  

> We'll be appreciated if you want to share your case here.

In edge compute if cloud-cluster and edge-cluster with broken line, updated the federation resources(like updte pod CPU limit) in work cluster. hoping to sync to karmada-cluster when network recover, but i think is not necessary for karmada. If need I think it can be implemented by modifying `karmada-agent` or `webhook` to update `template resource` or create a override policy in karmada cluster for current work-cluster.

**Comment by RainbowMango** [comment]
> If need I think it can be implemented by modifying karmada-agent or webhook to update template resource or create a override policy in karmada cluster for current work-cluster.

That's a good idea. I've never thought about that. I'm not sure if this is the real use case.

**Comment by RainbowMango** [comment]
> Is have a plan to support StatefulSet status aggregation?

Sure but no clear design yet. And we are seeking more user's feedback and expectation.
