### ISSUE TITLE
karmadactl join supports kubeconfig direct access

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/karmada#3050]
**What would you like to be added**:
karmadactl join add boolean flag `--use-kubeconfig`
**Why is this needed**:
Provides the ability to directly use kubeconfig to control clusters without creating serviceaccount.

**Comment by helen-frank** [comment]
@RainbowMango Is this a feasible idea? If so, I will realize this function as soon as possible.

**Comment by RainbowMango** [comment]
Cloud you explain why we need it? What's the benefit?

**Comment by helen-frank** [comment]
1. There is no need to create serviceaccount in the member cluster and reduce non-business modifications to the member cluster (this is mentioned in some requirements and does not want to issue more certificates.)
2. Using kubeconfig access can reduce operation and maintenance costs
3. Maybe we can add another ability to export member cluster kubeconfig in the future.
@RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
