### ISSUE TITLE
[umbrella] Add the version information  in which the feature was first supported in the documentation

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3059]
Now on the official website, the time when the feature was first supported is unclear, we should add it.

**What would you like to be added**:
- [ ] OverridePolicy document updates, [link](https://karmada.io/docs/next/userguide/scheduling/override-policy)
- [ ] resource interpreter document updates, [link](https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#built-in-interpreter)

**Comment by RainbowMango** [comment]
/close
The documentation enhancement is probably not only feature versions.
