### ISSUE TITLE
How agent in pull mode speaks to the kubernetes management?

### ISSUE THREAD

**Issue by Fatimastm** [karmada-io/karmada#3064]
**Please provide an in-depth description of the question you have**:
How does agent in pull mode communicate with the kubernetes cluster in order to receive the health status or deploy applications? Does the agent communicate to by consuming K8s Server API endpoints?

**Comment by RainbowMango** [comment]
Sorry for replying late. I'm just getting back from vacation.

> Does the agent communicate to by consuming K8s Server API endpoints?

Yes. The `karmada-agent` talks to member clusters by consuming the K8s Server API endpoints.
The `--kubeconfig` flag of `karmada-agent` needs to be specified if it runs out-of-cluster.
```
--kubeconfig string                                                                                                                                                                                                   
   Paths to a kubeconfig. Only required if out-of-cluster.
```

**Comment by Poor12** [comment]
/close
Feel free to reopen this issue if you have any questions.
