### ISSUE TITLE
[GoodFirst] fix hack/tools/tools.go gofmt issue

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#308]
**What would you like to be added**:
`hack/tools/tools.go` not gofmted, (don't know why golangci-lint can't catch it).

We usually group import paths in the order of `std packages --> `third-party packages` --> `karmada packages`.
So the fix would be:
```diff
 import (
-       _ "k8s.io/code-generator"
        _ "github.com/onsi/ginkgo/ginkgo"
+       _ "k8s.io/code-generator"
 )
```

Please reply to this issue directly if you want to take this task. :)

**Comment by anirudhramnath** [comment]
Hello @RainbowMango I am looking for my first contribution and would love to help on this.

**Comment by RainbowMango** [comment]
It's yours now, @anirudhramnath .

**Comment by RainbowMango** [comment]
@daixiang0 do you know why golangci-lint can't catch this issue?

**Comment by daixiang0** [comment]
Since the header `// +build tools`, I would look into it to find a solution.
