### ISSUE TITLE
Err: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.3:2379: connect: connection refused"

### ISSUE THREAD

**Issue by dmulizhihui** [karmada-io/karmada#3082]
when i install karmada by " kubectl karmada init"
find this error :
![image](https://user-images.githubusercontent.com/22570915/215420269-310c63a9-1cb0-4eb8-9d52-35e6915f75b2.png)
but when i exec to pod to nslookup svc-name is ok
![image](https://user-images.githubusercontent.com/22570915/215420661-e482da5c-277c-4536-af49-ee30d102d820.png)

how i can solve this problem ?

**Comment by dmulizhihui** [comment]
W0130 08:26:46.050259       1 logging.go:59] [core] [Channel #3 SubChannel #6] grpc: addrConn.createTransport failed to connect to {
  "Addr": "etcd-0.etcd.karmada-system.svc.cluster.local:2379",
  "ServerName": "etcd-0.etcd.karmada-system.svc.cluster.local",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.3:2379: connect: connection refused"

**Comment by jwcesign** [comment]
Hi @dmulizhihui, Can you copy the full log of `kubectl karmada init`?

**Comment by dmulizhihui** [comment]
> Hi @dmulizhihui, Can you copy the full log of `kubectl karmada init`? It looks like the etcd is not ready.

etcd is Running.

**Comment by dmulizhihui** [comment]
> Hi @dmulizhihui, Can you copy the full log of `kubectl karmada init`? It looks like the etcd is not ready.

W0130 08:26:46.050259 1 logging.go:59] [core] [Channel #3 SubChannel #6] grpc: addrConn.createTransport failed to connect to {
"Addr": "etcd-0.etcd.karmada-system.svc.cluster.local:2379",
"ServerName": "etcd-0.etcd.karmada-system.svc.cluster.local",
"Attributes": null,
"BalancerAttributes": null,
"Type": 0,
"Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp 172.17.0.3:2379: connect: connection refused"

**Comment by dmulizhihui** [comment]
> Hi @dmulizhihui, Can you copy the full log of `kubectl karmada init`? It looks like the etcd is not ready.

this is full logs;


[root@dev-nmg-huhehaote4-devtest-261 kubessl]# kubectl karmada init --etcd-image='harbor.ctyuncdn.cn/devops/etcd@sha256:f831c0318e05ccaaa23d043690509700028653695d66abbb28306cb05c4770e3' \
> --karmada-apiserver-image='harbor.ctyuncdn.cn/devops/kube-apiserver@sha256:e23d880f1c63bf8d0225c112c684afc46d9fc5b7c06ce3cd0a417e95d61679e3'
I0130 15:29:45.276702   22929 deploy.go:175] kubeconfig file: , kubernetes: https://cdnkube.io:6443
W0130 15:29:45.318662   22929 node.go:42] the kubernetes cluster does not have a Master role.
I0130 15:29:45.318685   22929 node.go:50] randomly select 3 Node IPs in the kubernetes cluster.
I0130 15:29:45.323155   22929 deploy.go:195] karmada apiserver ip: [172.21.66.16 172.21.66.17 172.21.66.18]
I0130 15:29:46.011413   22929 cert.go:229] Generate ca certificate success.
I0130 15:29:46.128230   22929 cert.go:229] Generate karmada certificate success.
I0130 15:29:46.434997   22929 cert.go:229] Generate apiserver certificate success.
I0130 15:29:46.681906   22929 cert.go:229] Generate front-proxy-ca certificate success.
I0130 15:29:46.748143   22929 cert.go:229] Generate front-proxy-client certificate success.
I0130 15:29:46.858572   22929 cert.go:229] Generate etcd-ca certificate success.
I0130 15:29:47.028801   22929 cert.go:229] Generate etcd-server certificate success.
I0130 15:29:47.245777   22929 cert.go:229] Generate etcd-client certificate success.
I0130 15:29:47.245988   22929 deploy.go:288] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.4.0/crds.tar.gz
Downloading...[ 100.00% ]
Download complete.
I0130 15:29:49.072411   22929 deploy.go:524] Create karmada kubeconfig success.
I0130 15:29:49.085832   22929 idempotency.go:252] Namespace karmada-system has been created or updated.
I0130 15:29:49.152854   22929 idempotency.go:276] Service karmada-system/etcd has been created or updated.
I0130 15:29:49.152880   22929 deploy.go:353] create etcd StatefulSets
W0130 15:29:49.183154   22929 check.go:101] etcd desired replicaset is 1, currently: 0
I0130 15:29:50.189428   22929 check.go:98] etcd desired replicaset is 1, currently: 1
I0130 15:29:53.209101   22929 check.go:49] pod: etcd-0 is ready. status: Running
I0130 15:29:53.209146   22929 deploy.go:364] create karmada ApiServer Deployment
I0130 15:29:53.242006   22929 idempotency.go:276] Service karmada-system/karmada-apiserver has been created or updated.
W0130 15:29:56.272721   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:29:57.278618   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:29:58.276850   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:29:59.277583   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:00.278299   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:01.279736   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:02.279441   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:03.279827   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:04.281679   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:05.565098   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:06.279424   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:07.283954   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:08.278917   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:09.278061   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:10.277206   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:11.278507   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:12.278587   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:13.280760   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:14.279052   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:15.302460   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:16.278266   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:17.279227   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:18.278421   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:19.279135   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:20.278208   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:21.279098   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:22.278252   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:23.287220   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:24.278903   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:25.282341   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:26.279503   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:27.279171   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:28.277673   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:29.280638   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:30.277560   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:31.326038   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:32.278609   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:33.277603   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:34.277409   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:35.277981   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:36.278443   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:37.277966   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:38.277321   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:39.278409   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:40.281793   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:41.278972   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:42.282753   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:43.277767   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:44.336291   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:45.278694   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:46.277990   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:47.332654   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:48.278042   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:49.277998   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:50.277209   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:51.278135   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:52.278423   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:53.278708   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:54.278456   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:55.277720   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:30:56.278562   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:57.277949   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:58.278654   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:30:59.279100   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:00.278416   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:01.278533   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:02.315601   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:03.277862   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:04.288507   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:05.280090   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:06.278040   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:07.307325   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:08.277736   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:09.280600   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:10.278236   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:11.279501   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:12.279897   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:13.278563   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:14.278542   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:15.278802   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:16.278723   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:17.277912   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:18.278371   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:19.545636   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:26.976336   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:27.277878   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:28.430245   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:29.278717   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:30.278668   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:31.279125   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:32.277034   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:33.278783   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:34.278147   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:35.278905   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:36.284720   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:37.279014   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:38.277893   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:39.328713   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:40.277193   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: CrashLoopBackOff
W0130 15:31:41.278140   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:42.279788   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:43.278151   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:44.278315   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:45.277830   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:46.277773   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:47.277948   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:48.278275   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:49.278849   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:50.278341   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:51.278518   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:52.281947   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:53.278780   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:54.318012   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:55.278486   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:56.293558   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
W0130 15:31:56.297527   22929 check.go:52] pod: karmada-apiserver-584d794f88-nc7k8 not ready. status: Running
error: timed out waiting for the condition

**Comment by jwcesign** [comment]
can you show me:
```sh
kubectl get pods -owide -A
```
And try to nslook up  `etcd-0.etcd.karmada-system.svc.cluster.local`.

**Comment by dmulizhihui** [comment]
貌似，域名解析有点问题

**Comment by jwcesign** [comment]
有slack吗？我们slack上聊： https://app.slack.com/client/T08PSQ7BQ/D02NTB3TK5M/thread/C02MUF8QXUN-1659854255.124239

我的slack id： jiang wei

**Comment by dmulizhihui** [comment]
> 有slack吗？我们slack上聊： https://app.slack.com/client/T08PSQ7BQ/D02NTB3TK5M/thread/C02MUF8QXUN-1659854255.124239
> 
> 我的slack id： jiang wei
nslookup  也可以域名解析

**Comment by dmulizhihui** [comment]
> > 有slack吗？我们slack上聊： https://app.slack.com/client/T08PSQ7BQ/D02NTB3TK5M/thread/C02MUF8QXUN-1659854255.124239
> > 我的slack id： jiang wei
> > nslookup  也可以域名解析

刚才解析不成功是nslookup没安装

**Comment by RainbowMango** [comment]
> After we tested it, curl the https://<etcd_pod_ip>:2379 is not ok(but http://<etcd_pod_ip>:2379 is ok), looks like it doesn't have a connection with Karmada.

What's the root cause? and does this issue been solved?

**Comment by jwcesign** [comment]
@dmulizhihui deploys k8s with binary. We tested and the HTTPS connection couldn't be established.
After adding hostnetwork configuration to etcd yaml, Karmada is launched.

So the root cause is the problem of cluster network(flannel is used).

**Comment by dmulizhihui** [comment]
> Got it. Thanks.

flannel run  coreectly.  this problem solved
