### ISSUE TITLE
Pod subresource (attach, exec, port-forward) support through global proxy

### ISSUE THREAD

**Issue by vkukul** [karmada-io/karmada#3089]
**What happened**:
Kube exec, attach and port-foward commands are being rejected.

**What you expected to happen**:
Be able to successfully port-forward, attach, exec to a pod in one of the member clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to use any of the above kubectl commands on any pod from a member cluster and you will see the following error.

**Anything else we need to know?**:
kubectl commands require secondary CREATE requests that get rejected by the proxy plugin for clusters and not forwarded to the underlying member cluster’s api-server. This logic is defined in [cluster.go](https://github.com/karmada-io/karmada/blob/master/pkg/search/proxy/framework/plugins/cluster/cluster.go#L66-L68).This prevents the global proxy implementation of kubectl from supporting these sub commands without using either karmadactl or the karmada kubectl plugin.

Based on the discussion in [this GH Issue](https://github.com/karmada-io/karmada/issues/1618) and what is stated in the global proxy design doc, it seems there is a desire to support these sub commands through the global proxy and not just through the karmada cli implementations.

For our implementation we were hoping to support these commands through the global proxy and were looking to see if the above code can be patched to support these features.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):

```karmadactl version: version.Info{GitVersion:"v1.4.0-196-gfed2f269-dirty", GitCommit:"fed2f269f5a47e4d37db8bffb29aabe4641112d4", GitTreeState:"dirty", BuildDate:"2023-01-31T16:44:56Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}```
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @vkukul, For details about why the Create request is rejected, see [Is creating supported?](https://karmada.io/docs/userguide/globalview/proxy-global-resource/#is-creating-supported).

We can ask @ikaven1024 to help reconfirm it.

In addition, we can use the ` Cluster proxy` API to achieve the purpose: `/apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy`.

**Comment by vkukul** [comment]
Hi @ikaven1024, yup that seems to resolved our problem. Thank you!
