### ISSUE TITLE
karmada-controller-manager has been outputting the log information.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#3097]
**What happened**:

![image](https://user-images.githubusercontent.com/17962021/216000500-4efa1cd3-33b2-46b1-bf40-9671cffc7486.png)

`karmada-controller-manager` has been outputting the above log information.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. kubectl apply -f samples/nginx/deployment.yaml
2. kubectl apply -f samples/nginx/propagationpolicy.yaml
3. kubectl label deploy nginx a=b
4. kubectl label deploy nginx a-

**Anything else we need to know?**:

https://github.com/karmada-io/karmada/blob/master/pkg/util/lifted/objectwatcher.go#L84

When the label  `a` in Karmada is deleted, the label of the member cluster will not be deleted, causing the `objectMetaObjEquivalent` function to always be false.

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Does this issue arise after #3088?

**Comment by chaunceyjiang** [comment]
Sorry, it's my environment's problem
