### ISSUE TITLE
Optimize installation flow

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#310]
**What would you like to be added**:

1. Split installation script for different purposes, in a stand-alone cluster(for production) or a [kind](https://kind.sigs.k8s.io/) cluster(for development)
2. No logger using export diff KUBECONFIG to switch multi-clusters in the install script

**Why is this needed**:
1. Likes #303, the newcomers may not have a sense for [kind](https://kind.sigs.k8s.io/) when they wanna make a production installation, so we should make it clear in the installation stage
2. Using a native way to switch multi-clusters for `kubectl`

**Comment by lfbear** [comment]
If it's ok, assign to me

**Comment by RainbowMango** [comment]
> Split installation script for different purposes, in a stand-alone cluster(for production)

**Comment by pigletfly** [comment]
Can we support install via Helm?

**Comment by lfbear** [comment]
> Can we support install via Helm? @lfbear Are you planning to do this ?

That's a good idea, but I have no plan for this version. I need to make the installation stage clear fisrtly.

**Comment by pigletfly** [comment]
Can we use https://github.com/jetstack/cert-manager for caBundle injection ?
