### ISSUE TITLE
When submiting 1000+ resource objects to Karmada concurrently, the propagating speed is slow

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3108]
When I submit 1000+ Argo Workflows to Karmada concurrently, the whole duration from submitting resources to `karmada-apiserver` to all resources appearing in the member cluster is nearly 15min. The workqueue in execution controller and work-status-controller is crowded from metrics.

For performance optimization, we need to:
* Perform parameter tuning for this scenario.
* Check the processing logic of the controller and optimize the redundant logic.

BTW, we need performance-related parameter lists in our documentation.

**Comment by RainbowMango** [comment]
Please give a root cause analysis in detail before proposing solutions.

**Comment by Poor12** [comment]
Submiting 600 Argo workflow concurrently, recording cpu running time.
Origin: 5min
![image](https://user-images.githubusercontent.com/26862112/220224377-a4b0587f-75e3-4429-8160-722cef15070d.png)
Test #3142: 3min
![image](https://user-images.githubusercontent.com/26862112/220224491-4ffd20cb-806a-472e-8579-774fe1657587.png)

**Comment by Poor12** [comment]
After we split up binding-controllers, I guess the performance has improved a lot. If the performance is still not up to the mark, we may consider to config the concurrentSyncNumbers more for binding-controller and execution-controller. Now the config is global for all controllers.
