### ISSUE TITLE
Why delete the work by deleting the execution space when unjoining the cluster

### ISSUE THREAD

**Issue by yanfeng1992** [karmada-io/karmada#3113]
**Please provide an in-depth description of the question you have**:
now unjoin member cluster:  remove cluster->remove es-namespace-> remove work
I found a problem through my test：
When I unjoin the cluster to delete the execution space of the member for about 5 seconds, the kube controller-manager namespace-controller starts to process the work object under the namespace to be deleted

karmada-controller-manager logs:
06:13:49.738185：cluster_controller deal with deleted cluster

kube-controller-manager logs:
06:13:54.753868：namespaced_resources_deleter.go:508] namespace controller - deleteAllContent - namespace: karmada-es-member2

![image](https://user-images.githubusercontent.com/89568107/216925505-81b266ac-ed8f-41ca-a3d6-e4b804cd2ea4.png)

![image](https://user-images.githubusercontent.com/89568107/216923858-90b0f0c1-afa1-4554-a9d7-67b71e64f7ff.png)

Although it seems very short in 5s, the karmada cluster-controller checks that the namespace cannot be deleted, which leads to 11-12 re-queue of the cluster object. Because the re-queue time increases exponentially, I think this will lead to a longer unjoin time to a certain extent, resulting in the failure of the unjoin cluster within five minutes in the e2e use case

**What do you think about this question?**:

Whether to delete all work objects in es-namespace before deleting the namespace instead of deleting the work objects by deleting the namespace

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by yanfeng1992** [comment]
Please take a look at this question @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Hi @yanfeng1992, thanks for your question~

> Although it seems very short in 5s, the karmada cluster-controller checks that the namespace cannot be deleted, which leads to 11-12 re-queue of the cluster object.

Do you know why this is? Why Cannot a Name Name Be Deleted?

> Whether to delete all work objects in es-namespace before deleting the namespace instead of deleting the work objects by deleting the namespace

I feel like this will speed up deletions, but how do you delete all work first? Do you have any idea?

**Comment by yanfeng1992** [comment]
1.Why does the kube-controller-manager process the delete event of the namespace 5 seconds after the namespace is deleted:

https://github.com/kubernetes/kubernetes/blob/429f71d9583af6f2add7496fd8e41ae0f180a832/pkg/controller/namespace/namespace_controller.go#L49

![image](https://user-images.githubusercontent.com/89568107/217458201-ed383bee-8f79-418d-a500-addc8fdac357.png)

![image](https://user-images.githubusercontent.com/89568107/217458246-412617c1-a978-413a-b95b-c711f85d2191.png)

2.What happened in karmada-controller-manager in these five seconds：

https://github.com/karmada-io/karmada/blob/5e81ea6240c5db01d7eabd0eeddc1dd2d3977ebd/pkg/controllers/cluster/cluster_controller.go#L254

re-queue 10-11times

![image](https://user-images.githubusercontent.com/89568107/217459326-2653bcb3-f0e7-4cb5-808f-bdb12f113454.png)

how do you delete all work first?:

I think this implementation is not difficult. Before deleting es-ns, list all work in es-ns, and delete them one by one.

https://github.com/karmada-io/karmada/blob/5e81ea6240c5db01d7eabd0eeddc1dd2d3977ebd/pkg/controllers/cluster/cluster_controller.go#L242

@XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Hi @yanfeng1992, Let me try to understand: the previous method is that the `namespace-controller` begins to delete the work after 5 seconds. The optimized logic is that the we deletes the work directly, which saves 5 seconds. The `cluster-controller` undergoes multiple reconcile within 5 seconds. As a result, the subsequent check interval is prolonged. If I understand wrong, please help correct it.

Based on the above understanding, I still have some ideas:
- The 5 seconds we saved are not really the first 5 seconds, but the last 5 seconds of the entire time it takes to wait for the namespace to be deleted successfully, which may not have much effect. 
- In addition, we cannot guarantee that there are only work resources in the namespace. In the future, there may be other resources. This means that we may need to adapt to the namespace continuously, which may be a burden.

I think we can focus our optimization on how to better check the logic of namespaces existing.

The above content may be troublesome to communicate. If it is convenient, we can use slack or wechat to communicate.

**Comment by yanfeng1992** [comment]
hi, @XiShanYongYe-Chang I agree with you. I think the focus of optimization should be on the logic of checking whether the namespace exists to avoid meaningless re-entry. I made changes according to this idea on PR. Details can be communicated through slack
