### ISSUE TITLE
scale and quota guide

### ISSUE THREAD

**Issue by henrywangx** [karmada-io/karmada#312]
**What would you like to be added**:
As a user, I wan't to know the how many cluster, node, pod can we support. And what's the recommended quota for karmada with different scale.
**Why is this needed**:
User guide for performance.

**Comment by RainbowMango** [comment]
As far as I know, we don't have a detailed performance report yet.

**Comment by RainbowMango** [comment]
Feel free to re-open this issue if you have further questions.
/close
