### ISSUE TITLE
Lock in clusterInformerManager

### ISSUE THREAD

**Issue by WulixuanS** [karmada-io/karmada#3122]
**What would you like to be added**:
Determine whether manager or handler exists within the scope of the write lock
**Why is this needed**:
Avoid multiple executions after rlock in concurrent scenarios

**Comment by rakeshkumarnahak** [comment]
I would like to work in this issue. Can you please provide some more resources to know more about this?

**Comment by RainbowMango** [comment]
Hi @rakeshkumarnahak Thanks, but @WulixuanS has sent a PR(#3123) for this.
/assign @WulixuanS 

@WulixuanS Can you explain this issue in more detail? I'm not sure if this is a bug.

**Comment by WulixuanS** [comment]
> Hi @rakeshkumarnahak Thanks, but @WulixuanS has sent a PR(#3123) for this. /assign @WulixuanS
> 
> @WulixuanS Can you explain this issue in more detail? I'm not sure if this is a bug.

For example, in the scene created for the first time, we use a read lock to determine whether the manager exists. There may be multiple coroutines judging that the manager does not exist at the same time. At this time, the subsequent creation logic will be executed multiple times.
Even if the subsequent creation logic is idempotent, I think it is better to return earlier.
@RainbowMango

**Comment by WulixuanS** [comment]
https://github.com/karmada-io/karmada/blob/59227f0d4a3b9cd3d79485984202e99c3aa302df/pkg/util/fedinformer/genericmanager/single-cluster-manager.go#L89-L102

line 95 ~ 101  may be executed multiple times

**Comment by RainbowMango** [comment]
I guess for most cases, the handler exists and that's the reason we use a `read lock`.

**Comment by WulixuanS** [comment]
> I guess for most cases, the handler exists and that's the reason we use a `read lock`.

Thanks, i got it.
But function addListener in sharedProcessor  is not idempotent.
I test for this:
```
			for i := 0; i < 10; i++ {
				go func() {
					fedClusterInformer.ForResource(gvr, NewHandlerOnAllEvent(func(object runtime.Object) {
						key, _ := cache.MetaNamespaceKeyFunc(object)
						klog.Info(key)
					}))
					fedClusterInformer.Start()
				}()

			}

			time.Sleep(1 * time.Hour)
```
the result:
![image](https://user-images.githubusercontent.com/20473367/217714799-5b5710cb-f48d-486b-b391-765572a36bb0.png)

**Comment by RainbowMango** [comment]
> But function addListener in sharedProcessor is not idempotent.

Sorry, I don't get it. 

> For most cases, may be use IsHandlerExist first then ForResource?

What's the problem here? Check a handler existence which is protected by a read lock, and append a handler by `ForResource` which is protected by a mutex lock. 

I wonder if this `bug` be reproduced.

**Comment by WulixuanS** [comment]
> What's the problem here? Check a handler existence which is protected by a read lock, and append a handler by `ForResource` which is protected by a mutex lock.
> 
> I wonder if this `bug` be reproduced.

As tested above, the expected behavior is to add the handler once because ForResource function judged IsHandlerExist firstly,  but it added 9 times. So i think a handler existence should be protected by write lock.

> Sorry, I don't get it.
> 
> > For most cases, may be use IsHandlerExist first then ForResource?

To resolve above bug, the ForResource should be protected by write lock.  
In most cases(read more write less), for performance, we may use IsHandlerExist func which is protected by read lock, then to use ForResource func which is protected by write lock, but it's not necessary.

**Comment by WulixuanS** [comment]
This bug can be reproduced @RainbowMango

**Comment by Poor12** [comment]
After I analyzed the issue, I find that now `ForResource` has three steps: `isHandlerExist`, `addHandler`, `appendHandler`(to map). Now we add a read lock to `isHandlerExist`. The following phenomena may occur when multiple goroutines operate concurrently.

For example, there are 10 goroutines, before the latest executed goroutine is executed to appendHandler, since the currently executed resource has not been stored in the map, the remaining 9 goroutines will still enter the step of `addHandler` after judgment, which will cause addHandler to be performed 10 times, which may result in adding multiple duplicate Handlers.

I wonder if it's the above issue. @WulixuanS

**Comment by WulixuanS** [comment]
> After I analyzed the issue, I find that now `ForResource` has three steps: `isHandlerExist`, `addHandler`, `appendHandler`(to map). Now we add a read lock to `isHandlerExist`. The following phenomena may occur when multiple goroutines operate concurrently.
> 
> For example, there are 10 goroutines, before the latest executed goroutine is executed to appendHandler, since the currently executed resource has not been stored in the map, the remaining 9 goroutines will still enter the step of `addHandler` after judgment, which will cause addHandler to be performed 10 times, which may result in adding multiple duplicate Handlers.
> 
> I wonder if it's the above issue. @WulixuanS

It's the above issue  @Poor12
