### ISSUE TITLE
How scale up karmada-apiserver-replicas and etcd-replicas?

### ISSUE THREAD

**Issue by ghostloda** [karmada-io/karmada#3128]
**Please provide an in-depth description of the question you have**:

I have init karmada with 1 replicas etcd and apiserver,now i want to scale to 3,how to to it?
![image](https://user-images.githubusercontent.com/17566963/217458487-f698ad66-1fd6-4718-9cd3-0fb351761215.png)

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by chaunceyjiang** [comment]
What is your installation mode? `helm` , `karmadactl` or `hack/local-up-karmada.sh`

**Comment by ghostloda** [comment]
> What is your installation mode? `helm` , `karmadactl` or `hack/local-up-karmada.sh`

kubectl karmada init --crds /root/crds.tar.gz --karmada-apiserver-replicas 1 --etcd-replicas 1

**Comment by RainbowMango** [comment]
> kubectl karmada init --crds /root/crds.tar.gz --karmada-apiserver-replicas 1 --etcd-replicas 1

The default storage mode is `hostPath` which means the data is in a node, how can we share it with other etcd replicas?
cc @lonelyCZ for comments.
