### ISSUE TITLE
Add E2E cases for PropagationPolicy/ClusterPropagationPolicy matching with nil resourceSelectors

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#314]
**What would you like to be added**:

We implemented PropagationPolicy/ClusterPropagationPolicy matching when more than one ploicy mathed, in #306 we add:
```go
		if policy.Spec.ResourceSelectors == nil {
			matchedPolicies = append(matchedPolicies, policy)
			continue
		}
```
but we haven't an E2E case for this. 

Maybe we need two cases:
- PropagationPolicy with nil resourceSelectors, how it works on resources.
- ClusterPropagationPolicy with nil resourceSelectors, how it works on resources.

**Why is this needed**:

If you interest in this task or have any questions, please feel free to reply on this issue.

**Comment by RainbowMango** [comment]
Hi @XiShanYongYe-Chang Please confirm if we have done this task.

**Comment by XiShanYongYe-Chang** [comment]
It hasn't been done so far.
