### ISSUE TITLE
unexcepted behavior of `names.GenerateBindingReferenceKey`

### ISSUE THREAD

**Issue by zirain** [karmada-io/karmada#3143]
```
left := names.GenerateBindingReferenceKey("a","b-c") 
right := names.GenerateBindingReferenceKey("a-b","c") 
```

left should not equal to right

cc @XiShanYongYe-Chang

**Comment by jwcesign** [comment]
I tested, and for K8s resource, '/' is not allowed, so how about changing `GenerateBindingReferenceKey` to:
![image](https://user-images.githubusercontent.com/19745536/218926755-f65fb798-415d-4ec6-a948-6b6708254832.png)

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang
