### ISSUE TITLE
karmada可以管理第三方k8s控制器吗？

### ISSUE THREAD

**Issue by dmulizhihui** [karmada-io/karmada#3146]
karmada可以管理第三方的k8s控制器吗（eg:阿里的kruise） ？

如果可以，怎么操作呢？

**Comment by RainbowMango** [comment]
Karmada可以编排K8S应用，第三方控制器通常是以Deployment部署，从这个角度看似乎可行。
不确定您想如何“管理”第三方控制器，所以不好回答。

**Comment by xigang** [comment]
@dmulizhihui karmada 使用的 aggeratedAPIserver 接口兼容k8s原生接口，我理解你只需要在联邦集群和member集群创建好openkruise提供的CRD和对应的operator就能用起来。

**Comment by dmulizhihui** [comment]
> @dmulizhihui karmada 使用的 aggeratedAPIserver 接口兼容k8s原生接口，我理解你只需要在联邦集群创建好openkruise提供的CRD （联邦集群不启动kruise的operator) 并且在member集群创建好openkruise提供的CRD和对应的operator就能用起来。

已经在member集群创建好了CRD,在karmada控制面创建了cloneset这种资源，但是cloneset无法下发到meember且无法创建对应的pod。

**Comment by RainbowMango** [comment]
> 已经在member集群创建好了CRD,在karmada控制面创建了cloneset这种资源，但是cloneset无法下发到meember且无法创建对应的pod。

猜想是PropagationPolicy匹配规则与实际CRD不匹配。另外，也请注意对于 `cluster-scoped`的资源需要使用`ClusterPropagationPolicy`，详情请阅： [What is the difference between PropagationPolicy and ClusterPropagationPolicy](https://karmada.io/docs/faq/#what-is-the-difference-between-propagationpolicy-and-clusterpropagationpolicy).

**Comment by jwcesign** [comment]
总结：
1.对于openkruise，建议部署模式为：在member cluster装全套openkruise的套件+crd，在karmada control plane部署只部署openkruise的crd（通过karmada-apiserver）。
2.为了分发副本数，在control plane添加自定义的interpretor，解析replicas.
3.为了提前发现部署问题，建议后续在control plane部署openkruise的webhook，做资源部署校验。


对于：
>  karmada 使用的 aggeratedAPIserver 接口兼容k8s原生接口，我理解你只需要在联邦集群创建好openkruise提供的CRD （联邦集群不启动kruise的operator) 并且在member集群创建好openkruise提供的CRD和对应的operator就能用起来。
karmada控制面有了cloneset资源，desirved也对，但是available pod一直为0，即无法下发cloneset到member集群的创建

原因是：PP里面的resource selector写错了

**Comment by dmulizhihui** [comment]
犯了很低级的错误，pp的名字和clonset的不一致导致的；

现在已经安装成功。
通过karmada控制 Kruise的资源下发到 member cluster 如下图：

从 Windows 版邮件发送

发件人: Hongcai Ren
发送时间: 2023年2月14日 9:59
收件人: karmada-io/karmada
抄送: dmulizhihui; Mention
主题: Re: [karmada-io/karmada] karmada可以管理第三方k8s控制器吗？ (Issue #3146)

已经在member集群创建好了CRD,在karmada控制面创建了cloneset这种资源，但是cloneset无法下发到meember且无法创建对应的pod。
猜想是PropagationPolicy匹配规则与实际CRD不匹配。另外，也请注意对于 cluster-scoped的资源需要使用ClusterPropagationPolicy，详情请阅： What is the difference between PropagationPolicy and ClusterPropagationPolicy.
