### ISSUE TITLE
Add CI for testing `init` command of karmadactl

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#3162]
**What would you like to be added**:

Add CI for testing `init` command of karmadactl

**Why is this needed**:

It is more convenient to test `init` command.

**Comment by jwcesign** [comment]
/assign

Does only test init? Do we need to run e2e?

**Comment by lonelyCZ** [comment]
> Does only test init?

I think so. Perhaps, we can add the other deployment commands in future, like `karmadactl addon`

> Do we need to run e2e?

I think we only check if all components are running when executing `karmadactl init` in a new kind cluster.

**Comment by jwcesign** [comment]
> I think so. Perhaps, we can add the other deployment commands in future, like karmadactl addon

Make sense.
