### ISSUE TITLE
E2E test for cluster proxy

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#317]
**What would you like to be added**:
We need E2E tests to support access member clusters by proxy. 

Please refer to #307 

**Why is this needed**:

**Comment by MesaCrush** [comment]
I will do this job

**Comment by RainbowMango** [comment]
@MesaCrush It's yours now. Feel free to ask or discuss here.

**Comment by RainbowMango** [comment]
I'm afraid this task will miss `v0.6.0`, let's moving this to `v0.7.0`.

By the way, @MesaCrush are you still working for this?

**Comment by RainbowMango** [comment]
@MesaCrush any progress?

**Comment by Charlie17Li** [comment]
My idea is that we need to simulate a cluster in edge that kubeconfig needs to be set up with 'proxy-url'. 

But how do we simulate a cluster in edge?

And I notice that I use Kind to create a cluster, this is what it will look like:

```
- cluster:
    certificate-authority-data: xxxx
    server: https://127.0.0.1:36573
  name: kind-member4
```


 Can I just change the ‘server’ to the ‘proxy-url’, I wonder what is the difference between ‘server’ and 'proxy-url' in handling

@RainbowMango
