### ISSUE TITLE
"Server could not find resource 'clusters.cluster.karmada.io'" during join after helm install of host

### ISSUE THREAD

**Issue by vyta** [karmada-io/karmada#3175]
**What happened**:
Created kind cluster, installed host components via helm (as per instructions). Created another kind member cluster to join with following command:
```
kubectl karmada join kind-child0 --kubeconfig=<path-to-host-kubeconfig> --cluster-kubeconfig=<path-to-member-kubeconfig>
```

Results in: `Error from server (NotFound): the server could not find the requested resource (get clusters.cluster.karmada.io)`

**What you expected to happen**:
Creation of Cluster resource on host and karmada-agent on member.

**How to reproduce it (as minimally and precisely as possible)**:
Create 2 kind clusters. Install karmada w/ helm on one. Attempt to join second cluster

**Anything else we need to know?**:

karmada-system pods on host:
```
karmada-system       etcd-0                                            1/1     Running   0             17h
karmada-system       karmada-aggregated-apiserver-58b74db774-rfkp7     1/1     Running   1 (17h ago)   17h
karmada-system       karmada-apiserver-d658686cd-lzbjk                 1/1     Running   0             17h
karmada-system       karmada-controller-manager-674657bb46-tbjww       1/1     Running   0             17h
karmada-system       karmada-kube-controller-manager-99849998f-tbdjb   1/1     Running   1 (17h ago)   17h
karmada-system       karmada-scheduler-74c95fb757-7dqv6                1/1     Running   0             17h
karmada-system       karmada-webhook-c9f6ccd6b-2kv5p                   1/1     Running   1 (17h ago)   17h
```
`kubectl get cluster` on host cluster indeed returns `error: the server doesn't have a resource type "cluster"`

**Environment**:
- Karmada version: 1.4.2
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 
- Others:

**Comment by RainbowMango** [comment]
When joing a cluster, you should use `karmada kubeconfig` in the `--kubeconfig=<path-to-host-kubeconfig>` flag, not the host cluster(`path-to-host-kubeconfig`).

**Comment by vyta** [comment]
> When joing a cluster, you should use `karmada kubeconfig` in the `--kubeconfig=<path-to-host-kubeconfig>` flag, not the host cluster(`path-to-host-kubeconfig`).

Not sure I follow. Which kubeconfig should it be if not the control plane cluster? I also tried without specifying `--kubeconfig` since the current context was my control plane cluster and had the same error.

**Comment by sudivate** [comment]
> > When joing a cluster, you should use `karmada kubeconfig` in the `--kubeconfig=<path-to-host-kubeconfig>` flag, not the host cluster(`path-to-host-kubeconfig`).
> 
> Not sure I follow. Which kubeconfig should it be if not the control plane cluster? I also tried without specifying `--kubeconfig` since the current context was my control plane cluster and had the same error.

@vyta post running  `karamda init`, CLI creates another config file (karmada-apiserver.config) at /etc/karmda point your `--kubeconfig=/etc/karamda/karmada-apiserver.config`

**Comment by olderTaoist** [comment]
> **What happened**: Created kind cluster, installed host components via helm (as per instructions). Created another kind member cluster to join with following command:
> 
> ```
> kubectl karmada join kind-child0 --kubeconfig=<path-to-host-kubeconfig> --cluster-kubeconfig=<path-to-member-kubeconfig>
> ```
> 
> Results in: `Error from server (NotFound): the server could not find the requested resource (get clusters.cluster.karmada.io)`
> 
> **What you expected to happen**: Creation of Cluster resource on host and karmada-agent on member.
> 
> **How to reproduce it (as minimally and precisely as possible)**: Create 2 kind clusters. Install karmada w/ helm on one. Attempt to join second cluster
> 
> **Anything else we need to know?**:
> 
> karmada-system pods on host:
> 
> ```
> karmada-system       etcd-0                                            1/1     Running   0             17h
> karmada-system       karmada-aggregated-apiserver-58b74db774-rfkp7     1/1     Running   1 (17h ago)   17h
> karmada-system       karmada-apiserver-d658686cd-lzbjk                 1/1     Running   0             17h
> karmada-system       karmada-controller-manager-674657bb46-tbjww       1/1     Running   0             17h
> karmada-system       karmada-kube-controller-manager-99849998f-tbdjb   1/1     Running   1 (17h ago)   17h
> karmada-system       karmada-scheduler-74c95fb757-7dqv6                1/1     Running   0             17h
> karmada-system       karmada-webhook-c9f6ccd6b-2kv5p                   1/1     Running   1 (17h ago)   17h
> ```
> 
> `kubectl get cluster` on host cluster indeed returns `error: the server doesn't have a resource type "cluster"`
> 
> **Environment**:
> 
> * Karmada version: 1.4.2
> * kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
> * Others:

@vyta check karmada-aggregated-apiserver component is healthy and correspond apiservice v1alpha1.cluster.karmada.io is exist？
`kubectl get apiservices.apiregistration.k8s.io --kubeconfig ~/.kube/karmada-config  | grep karmada` 
should be output fellow
`v1alpha1.cluster.karmada.io             karmada-system/karmada-aggregated-apiserver   True        119d
v1alpha1.config.karmada.io              Local                                         True        16d
v1alpha1.networking.karmada.io          Local                                         True        16d
v1alpha1.policy.karmada.io              Local                                         True        16d
v1alpha1.work.karmada.io                Local                                         True        16d
v1alpha2.work.karmada.io                Local                                         True        16d`

**Comment by RainbowMango** [comment]
@vyta Have you solved the issue? I think @sudivate answered your question as well. You might need to join the cluster to `karmada control plane` instead of `host cluster`.

**Comment by vyta** [comment]
@RainbowMango yes, did not know it was the karmada api server kubeconfig that we needed to specify so I will close this issue for now.

Btw, if init creates the kubeconfig in a default location then perhaps the default may be used for join as well? Is the karmada kubeconfig perhaps persisted in-cluster as well? Such that at some point you may only need access to either the cluster's api server OR the karmada api server?

**Comment by RainbowMango** [comment]
> Btw, if init creates the kubeconfig in a default location then perhaps the default may be used for join as well? Is the karmada kubeconfig perhaps persisted in-cluster as well? Such that at some point you may only need access to either the cluster's api server OR the karmada api server?

Do you mean generates the Karmada's config into the default location, like `.kube/config`? So that people don't need to set the --kubeconfig after installation?

**Comment by amacharya** [comment]
Hello,

https://github.com/karmada-io/karmada/issues/4963

Can you help me with this?

**Comment by Nithesh-b** [comment]
Issue persist
