### ISSUE TITLE
Support more object kind to use ReplicaSchedulingPolicy

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#319]
**What would you like to be added**:
Now, `ReplicaSchedulingPolicy` only supports deployment kind.Can we support any object kind that has `spec.replicas`?

**Why is this needed**:

**Comment by RainbowMango** [comment]
> Can we support any object kind that has spec.replicas?

Sure, will do.  We'll support both Kubernetes `Scale` resources(like ReplicaSet) and all customized resources(CRD) in the future.

We are seeking feedback from users, any comments about `ReplicaSchedulingPolicy`?

**Comment by RainbowMango** [comment]
I'll be appreciate if you can share your use case.

**Comment by pigletfly** [comment]
In my case, I defined a `AppDeployment` in control-plane cluster，which is different with k8s deployment,then I want to propagate the `AppDeployment` using `ReplicaSchedulingPolicy ` to member clusters.And AppDeployment does have a `replicas` in spec.

**Comment by RainbowMango** [comment]
Thanks.

`ReplicaSchedulingPolicy` used to `split` a total number of replicas across clusters. Does that meet your requirement? (presume `ReplicaSchedulingPolicy` can support your `AppDeployment`)

**Comment by RainbowMango** [comment]
I guess this is included by [customresourceinterpreter](https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter).
/close
