### ISSUE TITLE
resourceBinding这些字段，怎么在propagatepolicy配置的，没找到

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3190]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
![15cb9aaa725f26377feebf822a2df61](https://user-images.githubusercontent.com/31508490/220575559-f8a6872e-f4c8-4573-be6a-65c27e7fd7bb.png)
resourceBinding这些字段，怎么在propagatepolicy配置的，没找到
**Environment**:
- Karmada version:1.4.0
- Kubernetes version:
- Others:

**Comment by chaunceyjiang** [comment]
你为什么会直接配置 RB ？ 用户一般不直接使用。

**Comment by 13567436138** [comment]
我就是想直接用rb实验下

**Comment by RainbowMango** [comment]
ResourceBinding is a kind of internal API, it is not recommended to create/update the resource, but you can grab some info from it.
