### ISSUE TITLE
FederatedResourceQuota 能管理哪些资源呢，和ResourceQuota一样么

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#3191]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
FederatedResourceQuota 能管理哪些资源呢，和ResourceQuota一样么
**Environment**:
- Karmada version:1.4.0
- Kubernetes version:
- Others:

**Comment by Fish-pro** [comment]
@13567436138 

Perhaps you can find the FederatedResourceQuota instructions in the documentation
https://karmada.io/docs/userguide/bestpractices/federated-resource-quota/

**Comment by 13567436138** [comment]
the doc is too simple

**Comment by RainbowMango** [comment]
FederatedResourceQuota is designed for global quota management for applications that run on multiple clusters.
/close
