### ISSUE TITLE
Installation instructions in detail

### ISSUE THREAD

**Issue by mnkg561** [karmada-io/karmada#323]
**What would you like to be added**:
Please provide detail installation instructions so that users can install what they need instead of just running a script to do the all the installation. I wanted to try to install it in AWS EKS cluster but installation instructions are not clear and assuming i don't have any existing clusters and starting with kind cluster creation to setup host-cluster. I would like to see the step by step installation guide and k8s manifests(or Helm chart) so users know what they are installing in their clusters and manipulate the manifests if they are running into any issues due to their organization policies.

**Why is this needed**:

**Comment by RainbowMango** [comment]
Hi @mnkg561 Thanks for your feedback.

Totally agree with you, and it's already on the plan, see #310.

**Comment by willzhang** [comment]
there have helm charts , please upload it to https://artifacthub.io/

**Comment by RainbowMango** [comment]
@willzhang Nice suggestion. What are the benefits and what shall we do then?

**Comment by willzhang** [comment]
**benefits：**easy install with helm , because github clone is very hard for chinese
**what shall you do:** registry an account in https://artifacthub.io/, then go to contral panel upload helm chats.

**Comment by RainbowMango** [comment]
The installation guide is available now, please refer to [Installing Karmada](https://github.com/karmada-io/karmada/blob/master/docs/installation/installation.md).

I'm going to close this issue now, but feel free to re-open it if you want further discussion.

> registry an account in https://artifacthub.io/, then go to control panel upload helm chats.

Will do it, probably next release. Thanks.
/close
