### ISSUE TITLE
pp/cpp's spreadconstraints are not validated correctly

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3231]
**What happened**:
Error pp/cpp's spreadconstraints can be create and affect the scheduling process.
![0880c4c80710fad0c20c](https://user-images.githubusercontent.com/89241565/222361149-010ddc44-4759-49d1-96ad-5a8ee1091f8d.jpeg)

![0880c4c80710fad0a20c](https://user-images.githubusercontent.com/89241565/222361359-7852a937-18d5-4e3b-b51f-99ae70db4a30.jpeg)

**What you expected to happen**:
`minGroups` and `maxGroup` should not be less that zero, and `maxGroup` should also get default value(I think it should be `minGroups`)
**How to reproduce it (as minimally and precisely as possible)**:
Create pp or cpp with incorrect `minGroups` and `maxGroup`.
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Thanks, It makes sense to me. I'll look at #3232 later.
