### ISSUE TITLE
The karmada api repo needs to sync to v1.5.0

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#3246]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
/assign

OK. I think I can do it by this week.
