### ISSUE TITLE
Failed to use lua's built-in string function in ResourceInterpreterCustomization lua script

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3247]
**What happened**:

For the following ResourceInterpreterCustomization resource:

```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
  name: declarative-configuration-example
spec:
  target:
    apiVersion: v1
    kind: Service
  customizations:
    statusReflection:
      luaScript: >
        function ReflectStatus (observedObj)
          print(string.len("abc"))
          return observedObj.status
        end
```

I want to interpret the `Service Status` resource with the `interpretStatus` operation:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-06T12:24:10Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "190"
  uid: 79febb3b-af42-4e83-aa4f-9095112771fb
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer:
    ingress:
    - ip: 172.1.1.1
    - ip: 192.1.3.2
```

When I run with the following command:

```shell
karmadactl interpret -f reflectstatus.yaml --operation interpretStatus --observed-file service-status.yaml
```

I got the bellow error:

```log
Execute InterpretStatus error: <string>:2: attempt to index a non-table object(nil) with key 'len'
stack traceback:
        <string>:2: in main chunk
        [G]: ?
```

Then I tried other string functions, and it returned similar errors.

**What you expected to happen**:

The `string` function can be used normally.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This issue is related to lua VM initialization: pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go:43

**Environment**:
- Karmada version: karmada v1.4 and later
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): karmada v1.4 and later
- Others:

**Comment by chaunceyjiang** [comment]
Have you tested the `#str` method?

**Comment by XiShanYongYe-Chang** [comment]
> Have you tested the `#str` method?

Can you give me a demo usage?

**Comment by XiShanYongYe-Chang** [comment]
Found the same problem that [argo-cd](https://github.com/argoproj/argo-cd) had before: https://github.com/argoproj/argo-cd/issues/6039

The solution is to introduce the `useOpenLibs` parameter, allow administrator enable lua standard library for health checks:

https://github.com/argoproj/argo-cd/pull/6087

For us, opening a parameter for user settings may not be the best option.

The reason of disable lua standard library is:
https://github.com/karmada-io/karmada/blob/83c7862289ac3884985cee2a10f023ffb8f925b2/pkg/util/lifted/lua_oslib_safe.go#L7-L10

The lua standard libraries we want to use are `string`, `math`, so we can set up these two standard libraries additionally.
