### ISSUE TITLE
release Helm chart to OCI-based registries

### ISSUE THREAD

**Issue by zirain** [karmada-io/karmada#3249]
OCI-based registry is [stable in helm from v3.8.0](https://helm.sh/docs/topics/registries/#oci-support-prior-to-v380).

what about release karmada chart to [OCI-based registries](https://helm.sh/docs/topics/registries/#use-hosted-registries), like docker hub.

cc @XiShanYongYe-Chang @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
Ask for @Poor12 to help take a look.
/cc @Poor12

**Comment by RainbowMango** [comment]
Do you mean we can publish the chart to DockerHub now?  That sounds great, is there a guideline?

**Comment by zirain** [comment]
all command can be found in this page: https://helm.sh/docs/topics/registries/#use-hosted-registries

here is a summary:

```
# push 
helm push karmada-0.1.0.tgz oci://docker.io/karmada-charts

# install
helm install karmada-release oci://docker.io/karmada-charts/karmada--version 0.1.0
```

**Comment by Poor12** [comment]
I'm wondering if we can make this into our pipeline. Steps may be 1. Change image tag. 2. Generate tgz file and upload it to release file. 3. Push it to OCI-based registries.

**Comment by RainbowMango** [comment]
> I'm wondering if we can make this into our pipeline.

Yes, that'd be wonderful.

**Comment by zirain** [comment]
> I'm wondering if we can make this into our pipeline. Steps may be 1. Change image tag. 2. Generate tgz file and upload it to release file. 3. Push it to OCI-based registries.

I think need another docker hub account(named karmada-charts etc) if you want name the chart with the `karmada`.
