### ISSUE TITLE
cannot join clusters

### ISSUE THREAD

**Issue by softputer** [karmada-io/karmada#325]
**What happened**:  
When i run:
```
 karmadactl join kind-member1  --cluster-kubeconfig=
```
i got errors as follows:
```
W0513 14:05:10.803294   32997 join.go:445] failed to create cluster. cluster: /, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="ba783dbc-f059-4729-a439-c85254a5f769", got ""
W0513 14:05:10.803484   32997 join.go:419] failed to create cluster. cluster: /kind-member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="ba783dbc-f059-4729-a439-c85254a5f769", got ""
E0513 14:05:10.803500   32997 join.go:271] failed to create cluster object. cluster name: kind-member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="ba783dbc-f059-4729-a439-c85254a5f769", got ""
E0513 14:05:10.803511   32997 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="ba783dbc-f059-4729-a439-c85254a5f769", got ""
```
what's wrong with the webhook?

**What you expected to happen**: join the cluster succesfully 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- Others:

**Comment by RainbowMango** [comment]
When joining a cluster, the `karmadactl` will create a [Cluster](https://github.com/karmada-io/karmada/blob/39d1a3a63666fe0d40748afec93a657c3da813cf/pkg/apis/cluster/v1alpha1/types.go#L19) object, in this process, the `karmada-apiserver` will request `karmada-webhook` for validation.

From the output logs, I can tell that the `karmada-webhook` failed to give a response.

Can you share your operation steps that I can reproduce on my side?

**Comment by softputer** [comment]
i deployed karmada into an exsiting k8s cluster, each component of karamada just runs well .
but it would fail when i want to join a cluster.

how would the karamada apiserver know the address of the webhook? etcd? bacause i did not find any configuration in the deployment file of karmada apiserver

**Comment by RainbowMango** [comment]
> how would the karamada apiserver know the address of the webhook?

Here is the [WebhookConfiguration](https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/webhook-configuration.yaml), have you deployed this?  Deploy this configuration means `register` webhook to karmada-apiserver.

**Comment by softputer** [comment]
the k8s server  version is v1.16.8, 
when i deploy WebhookConfiguration, there are errors,
i need to change :      admissionReviewVersions: ["v1","v1alpha1","v1beta1"]
i think that is why apiserver cannot access webhook,
so the k8s server version must be ?

**Comment by softputer** [comment]
有空可以远程桌面看一下不，这个问题，卡死我了……

**Comment by softputer** [comment]
apiserver errors: 
```
W0513 14:41:04.302748       1 dispatcher.go:134] Failed calling webhook, failing closed cluster.karmada.io: failed calling webhook "cluster.karmada.io": expected response.uid="7f2010ec-4fb1-4cf4-820f-139e3596e2a5", got ""
```

**Comment by softputer** [comment]
```
E0513 15:30:03.387614       1 customresource_handler.go:668] error building openapi models for clusters.cluster.karmada.io: ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.allocatable.additionalProperties.schema has invalid property: anyOf
ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.used.additionalProperties.schema has invalid property: anyOf
I0513 15:30:03.388618       1 client.go:360] parsed scheme: "endpoint"
```

**Comment by softputer** [comment]
i found the reason ald,
it is because  the crd in file: cluster.karmada.io_clusters.yaml does not successfully get installed,
because of 
```
E0513 15:30:03.387614       1 customresource_handler.go:668] error building openapi models for clusters.cluster.karmada.io: ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.allocatable.additionalProperties.schema has invalid property: anyOf
ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.used.additionalProperties.schema has invalid property: anyOf
```
and according to this page : https://github.com/kinvolk/lokomotive/issues/1197
k8s v1.20.0 is a must

so the only way is to upgrade k8s to v1.20.0?
or is there any tricky way to change the crd to let me deploy it on k8s v1.16 to have a test first?

**Comment by RainbowMango** [comment]
> is there any tricky way to change the crd to let me deploy it on k8s v1.16 to have a test first?

Are you deploying the CRD on the member clusters(v1.16)'s kube-apiserver? If yes, let me reproduce this on my side and see how to do.

But I suggest deploy a separated `kube-apiserver`(named karmada-apiserver) on your clusters, then you can select a higher version, such as v1.19. (You don't have to upgrade the cluster what you have now).

**Comment by RainbowMango** [comment]
You can find me by [slack](https://join.slack.com/t/karmada-io/shared_invite/zt-omhy1wfa-LmAkCLfpDMnBjVXp3_U~0w) if you want to have a talk.

**Comment by softputer** [comment]
i send message to the slack and below is the detail :
the k8s server version is v1.16.8, i deploy karmada components to karmada-system step by step according to the the shell scrips.
i did not deploy the karmada agent to the member cluster for now
all pods seems work well. the karmada apiserver is v1.19.1. but when i tried to run the following command
```
karmadactl --kubeconfig=karmada-apiserver.config join kind-member1 --cluster-kubeconfig=**/.kube/config.test
```
By the way, kind-member1 cluster is the host k8s cluster, because for now , i only have one cluster
i got errors:
````
E0513 14:05:10.803500   32997 join.go:271] failed to create cluster object. cluster name: kind-member1, error: Internal error occurred: failed calling webhook “cluster.karmada.io”: expected response.uid=“ba783dbc-f059-4729-a439-c85254a5f769", got “”
E0513 14:05:10.803511   32997 join.go:91] Error: Internal error occurred: failed calling webhook “cluster.karmada.io”: expected response.uid=“ba783dbc-f059-4729-a439-c85254a5f769”, got “”
```
it seems that when the apiserver cannot get correct response from webhook,
when i check the logs of apiserver , i found this,
```
E0513 15:30:03.387614       1 customresource_handler.go:668] error building openapi models for clusters.cluster.karmada.io: ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.allocatable.additionalProperties.schema has invalid property: anyOf
ERROR $root.definitions.io.karmada.cluster.v1alpha1.Cluster.properties.status.properties.nodeSummary.properties.used.additionalProperties.schema has invalid property: anyOf
```
so ,the version of karmada host k8s cluser should also be up to v1.19.1.
because ther version of the member cluster shoule be different
so what should i do?   so the karmada needs higher version of host cluster k8s apiserver?

**Comment by softputer** [comment]
i have just deployed a new k8s cluster , version v1.21 ,but the same situation 
```
W0514 12:10:07.937251   42767 join.go:445] failed to create cluster. cluster: /, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="b8c391a2-73f5-4030-9438-f496f124f590", got ""
W0514 12:10:07.937711   42767 join.go:419] failed to create cluster. cluster: /kind-member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="b8c391a2-73f5-4030-9438-f496f124f590", got ""
E0514 12:10:07.937720   42767 join.go:271] failed to create cluster object. cluster name: kind-member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="b8c391a2-73f5-4030-9438-f496f124f590", got ""
E0514 12:10:07.937728   42767 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="b8c391a2-73f5-4030-9438-f496f124f590", got ""
```
