### ISSUE TITLE
Remove special character with English word

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3260]
**Task description**:
There is a special character `+∞` is used in API comments in two places:
 1. https://github.com/karmada-io/karmada/blob/83c7862289ac3884985cee2a10f023ffb8f925b2/pkg/apis/cluster/types.go#L202
 2. https://github.com/karmada-io/karmada/blob/83c7862289ac3884985cee2a10f023ffb8f925b2/pkg/apis/cluster/v1alpha1/types.go#L214

We'd better replace them with the normal English word like `infinite`, to avoid the encoding issue like https://github.com/karmada-io/api/pull/17#discussion_r1131194407.

**Solution**:
Just replace `+∞` with the English word `infinite` from the code base, and then run the command `make update` to refresh the generated files.

```diff
diff --git a/pkg/apis/cluster/types.go b/pkg/apis/cluster/types.go                                                
index 82a76632..b48788e1 100644                                                                                   
--- a/pkg/apis/cluster/types.go                                                                                   
+++ b/pkg/apis/cluster/types.go                                                                                   
@@ -199,7 +199,7 @@ type ResourceModel struct {                                                                   
 // ResourceModelRange describes the detail of each modeling quota that ranges from min to max.                   
 // Please pay attention, by default, the value of min can be inclusive, and the value of max cannot be inclusive.
 // E.g. in an interval, min = 2, max =10 is set, which means the interval [2,10).                                
-// This rule ensure that all intervals have the same meaning. If the last interval is +∞,                        
+// This rule ensure that all intervals have the same meaning. If the last interval is infinite,                  
 // it is definitely unreachable. Therefore, we define the right interval as the open interval.                   
 // For a valid interval, the value on the right is greater than the value on the left,                           
 // in other words, max must be greater than min.
diff --git a/pkg/apis/cluster/v1alpha1/types.go b/pkg/apis/cluster/v1alpha1/types.go
index 462bde28..9d7ab048 100644
--- a/pkg/apis/cluster/v1alpha1/types.go
+++ b/pkg/apis/cluster/v1alpha1/types.go
@@ -211,7 +211,7 @@ type ResourceModel struct {
 // ResourceModelRange describes the detail of each modeling quota that ranges from min to max.
 // Please pay attention, by default, the value of min can be inclusive, and the value of max cannot be inclusive.
 // E.g. in an interval, min = 2, max =10 is set, which means the interval [2,10).
-// This rule ensure that all intervals have the same meaning. If the last interval is +∞,
+// This rule ensure that all intervals have the same meaning. If the last interval is infinite,
 // it is definitely unreachable. Therefore, we define the right interval as the open interval.
 // For a valid interval, the value on the right is greater than the value on the left,
 // in other words, max must be greater than min.

```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by rakshitgondwal** [comment]
Hey @bhavyastar! You still working on this?

**Comment by bhavyastar** [comment]
Yes, will make the PR tomorrow! :)

**Comment by bhavyastar** [comment]
<img width="847" alt="Screenshot 2023-03-27 at 10 50 41 AM" src="https://user-images.githubusercontent.com/84725791/227847754-aa192e65-fb63-40c3-9115-ad92c730d9fc.png">

@RainbowMango Can you check why this command shows an error? After making changes, I did make update and it shows this error attached above!

**Comment by RainbowMango** [comment]
Hi @bhavyastar 
From this output, I can see that you might need to install the `protoc` on your machine.
You can download and install it from https://github.com/protocolbuffers/protobuf/releases.

**Comment by RainbowMango** [comment]
Hi @bhavyastar Are you still working on this issue?

**Comment by bhavyastar** [comment]
Some errors are still coming will try to solve those errors and make PR by tomorrow.

**Comment by RainbowMango** [comment]
Can you share the errors? Have you solved the protocol issue?

I'm thinking this task requires a machine with some mandatory dependent components and may be not suitable for first-time contributors. Please feel free to let me know if you want to transfer this task to someone else. I'm glad to get you to start with other tasks later.

**Comment by RainbowMango** [comment]
Given this issue has been open for a while, let's see if anyone else wants to help.

/unassign @bhavyastar

**Comment by bhavyastar** [comment]
Hey @RainbowMango, I was busy with my exams. Sorry for a little delay. It was just completed and solved yesterday. It would be great if you can review this and give some feedback. :)
