### ISSUE TITLE
Error missing method Filter when a new scheduler image is created

### ISSUE THREAD

**Issue by Fatimastm** [karmada-io/karmada#3277]
**What happened**:
I followed step-by-step instructions for adding new plugin to scheduler from [here](https://github.com/karmada-io/website/pull/286/files#diff-36d959f3b250d7ceaf673341064bb14f049c5212557e8c4ca41f39d5ac8495bf). When I tried to create new image of scheduler with: 
`make image-karmada-scheduler`
I got this error:

> pkg/scheduler/framework/plugins/testfilter/test_filter.go:14:32: cannot use &TestFilter{} (value of type *TestFilter) as framework.FilterPlugin value in variable declaration: *TestFilter does not implement framework.FilterPlugin (wrong type for method Filter)
                **have** Filter(context.Context, *"github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1".Placement, *v1alpha2.ResourceBindingSpec, *"github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1".Cluster) *framework.Result
                **want** Filter(context.Context, *v1alpha2.ResourceBindingSpec, *v1alpha2.ResourceBindingStatus, *"github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1".Cluster) *framework.Result

**What you expected to happen**:
I had added my custom plugin before successfully. This time, I re-install karmada and tried to add the plugin again, that I got the above error.

Thank you in advance.

**Comment by Poor12** [comment]
Thanks for discovering the issue. We have updated the interface before so the document needs to be updated, too.

**Comment by Poor12** [comment]
Hi @Fatimastm, would you like to try it again according to https://github.com/karmada-io/website/pull/334?

**Comment by RainbowMango** [comment]
> I had added my custom plugin before successfully. This time, I re-install karmada and tried to add the plugin again, that I got the above error.

We updated the plugin interface(signature) part at v1.15.
```diff
- func (p *TestFilter) Filter(ctx context.Context, placement *policyv1alpha1.Placement,
	bindingSpec *workv1alpha2.ResourceBindingSpec, cluster *clusterv1alpha1.Cluster) 
+ func (p *TestFilter) Filter(ctx context.Context,
	bindingSpec *workv1alpha2.ResourceBindingSpec, bindingStatus *workv1alpha2.ResourceBindingStatus, cluster *clusterv1alpha1.Cluster)
```

Thanks for spotting this and that reminds us should keep the interface consistent. Sorry for the inconvenience.

**Comment by Fatimastm** [comment]
> Hi @Fatimastm, would you like to try it again according to [karmada-io/website#334](https://github.com/karmada-io/website/pull/334)?

Hi @Poor12, Thanks a lot! It's working.

**Comment by RainbowMango** [comment]
Glad to hear that.

**Comment by Poor12** [comment]
As far as I know, this option has not changed in the new version. I wonder why you have this problem. Could you show the details?

**Comment by RainbowMango** [comment]
Yes, just as @Poor12 said, this option is still in v1.5.
```
# _output/bin/linux/amd64/karmada-scheduler version
karmada-scheduler version: version.Info{GitVersion:"v1.5.0", GitCommit:"51fbbb055d47331e83a6ca2e90b8a5312d6a7986", GitTreeState:"clean", BuildDate:"2023-03-25T02:00:27Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
# _output/bin/linux/amd64/karmada-scheduler --help 
...
Generic flags:

      --enable-scheduler-estimator                                                                                                                                                                                              
                Enable calling cluster scheduler estimator for adjusting replicas.
      --plugins strings                                                                                                                                                                                                         
                A list of plugins to enable. '*' enables all build-in and customized plugins, 'foo' enables the plugin named 'foo', '*,-foo' disables the plugin named 'foo'.
                All build-in plugins: APIEnablement,ClusterAffinity,ClusterLocality,SpreadConstraint,TaintToleration. (default [*])
```

**Comment by Fatimastm** [comment]
I wanted to do a pure test, so I also put `--enable-scheduler-estimator=false`.

**Comment by chaunceyjiang** [comment]
Have you enabled `ResourceModeling`?  https://github.com/karmada-io/karmada/blob/master/pkg/features/features.go#L32

**Comment by Poor12** [comment]
Let's confirm the issue.

> I tested sceduler with custom plugin and since the result was not as exepcted, I just check the log file of scheduler and saw this:

You mean you made a `--plugin` option yourself but it didn't take effect. In that case, I suggest to use the latest image and built-in options.

> I am curious to know that does karmada has any resource reservation in member clusters befor actual deployement?

Now Karmada takes the minimum value calculated by the estimator to represent the available replicas of the cluster. If you install accurate-estimator, it will consider it in combination with the values calculated by [resourceModels](https://karmada.io/docs/userguide/scheduling/cluster-resources) and [accurator-estimator](https://karmada.io/docs/userguide/scheduling/scheduler-estimator).

**Comment by RainbowMango** [comment]
> I am curious to know that does karmada has any resource reservation in member clusters befor actual deployement?

No, for the time being, Karmada doesn't have such a mechanism to reserve resources( but maybe we should consider it). 

> I tested sceduler with custom plugin and since the result was not as exepcted,

Sorry, I'm not quite sure what the question is, how is it `not as expected`?

**Comment by Fatimastm** [comment]
> Let's confirm the issue.
> 
> > I tested sceduler with custom plugin and since the result was not as exepcted, I just check the log file of scheduler and saw this:
> 
> You mean you made a `--plugin` option yourself but it didn't take effect. In that case, I suggest to use the latest image and built-in options.

Yes. Sure I will try that.

**Comment by Fatimastm** [comment]
> > I tested sceduler with custom plugin and since the result was not as exepcted,
> 
> Sorry, I'm not quite sure what the question is, how is it `not as expected`?

@RainbowMango @Poor12  the pod didn't deploy in the cluster which I expected. Kamada repeated several time a loop involving: 1) created container in a cluster, 2) terminate it, and 3) created container in other cluster. Finally it didn't deploy. When I trace the logs of scheduler I saw that after final decision by scheduler, which was what I expected, another binding was sent to scheduler based on these: [conditions](https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/scheduler.go#L326). My assumption is Karmada creates a replica if num replica == 0 to handl pod failing, please correct me if I am wrong.

**Comment by RainbowMango** [comment]
> Kamada repeated several time a loop involving: 1) created container in a cluster, 2) terminate it, and 3) created container in other cluster. Finally it didn't deploy. 

That is probably due to karmada-scheduler making different decisions during each scheduling loop.  Do you disabled [ClusterLocality](https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go#L13) plugin?

> My assumption is Karmada creates a replica if num replica == 0 to handl pod failing, please correct me if I am wrong.

For the time being, Karmada won't make re-scheduling for Pod failing. It might not the case.
