### ISSUE TITLE
What‘s the roadmap of fully compatible k8s original api

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3286]
**Please provide an in-depth description of the question you have**:

The 'fully compatible k8s original api' as the sparkle of karmada, appears many times many where, not only on the official docs but also at talks online or offline.

So many end users are mindful of this, they persist in this original api. However the `kube-controller-manager` of karmada control plane is trimed, there were no controller like `Deployment`, `ReplicaSet`, because karmada don't need it.

So the original apiserver won't provide any pod.

Indeed, there is `search`, `proxy`, but it just **not** the **original api**.

**What do you think about this question?**:

The `apiserver` is the original one, it just a wrapper to etcd to store k8s objects. And the aggragated api server, did nothing but extended `cluster` related api using `API Service` to the original apiserver.

The magic happend at karmada controller manager, which match k8s object and policy, then dispatch the object to member clusters.

And `Pod` or `Node`, or other builtin k8s object could not be override using API Service.

So, what about to introduce a proxy in front of the apiserver, intercept urls of pod, or node or some other resource, to another rest controller, then we can integrate resources from member clusters at rest handler, to achieve the `k8s original api`?

I wonder how the community thinks about this.

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
> And Pod or Node, or other builtin k8s object could not be override using API Service.

What do you mean `could not be override`? 
Can you share a use case?

**Comment by tedli** [comment]
Hi @RainbowMango ,
Thanks for reply.
I mean I can't override `v1.`, the builtin api group using `APIService` like:
```yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2023-03-06T02:44:06Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.
  resourceVersion: "6"
  uid: 08226bb1-e5be-48d3-8f0d-72a9bf8b2d88
spec:
  groupPriorityMinimum: 18000
  version: v1
  versionPriority: 1
status:
  conditions:
  - lastTransitionTime: "2023-03-06T02:44:06Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
```
to give my own implemention of builtin resources like pod or node.

**Comment by RainbowMango** [comment]
You probably want to disable the Kubernetes original core APIs(`v1`) and use [Aggregate APIserver](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) to add it back with your own implementation. Is that right?

But I wonder why? Why are you doing this?

**Comment by tedli** [comment]
Yeah, you got me. It dosen't make sence. Ican't agree more.

What I want to point out, is that there are many users who didn't dive deep enough to the code, they thougth karmada already did this, because the doc said 'karmada provides fully compatable api of original k8s api'.

So I thought if this is a common needs, this could be talked about.

发自我的 iPhone

在 2023年3月16日，下午9:03，Hongcai Ren ***@***.***> 写道：

﻿

You probably want to disable the Kubernetes original core APIs(v1) and use Aggregate APIserver<https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/> to add it back with your own implementation. Is that right?

But I wonder why? Why are you doing this?
