### ISSUE TITLE
for installation ./local-up-karmada.sh Error 

### ISSUE THREAD

**Issue by sadonghwan** [karmada-io/karmada#3294]
**What happened**:
[root@k8s-master hack]# sh ./local-up-karmada.sh
./../hack/util.sh: line 64: `util::get_target_source': not a valid identifier

**What you expected to happen**:
install

**How to reproduce it (as minimally and precisely as possible)**:
[root@k8s-master hack]# sh ./local-up-karmada.sh

**Anything else we need to know?**:
Error occurred from installation...

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:
[root@k8s-master hack]# bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by sadonghwan** [comment]
[root@k8s-master hack]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by RainbowMango** [comment]
@sadonghwan Can you help share the output of `local-up-karmada.sh`?

By the way, the script is supposed run at the root of repo, like `hack/local-up-karmada.sh`, can you try again?

**Comment by sadonghwan** [comment]
![image](https://user-images.githubusercontent.com/50479218/226218780-f6e58d0f-b1e0-4f1d-8786-b2cbcb21fcd0.png)

@RainbowMango Thanks!!!!

**Comment by sadonghwan** [comment]
soory... 
I tried it again and it worked.

**Comment by sadonghwan** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
Good to know. 
Then I guess we can close it now.
/close
