### ISSUE TITLE
response actual resource list from search cache api

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3311]
**What would you like to be added**:

Currently, the search api, response `List`, the user need to define their own receiver type, to deserialize the response.

**Why is this needed**:

If the api response response actual resource list type, then client side code like `client-go` can decode into pre defined api type like `PodList` by scheme codec.

```golang
var raw runtime.Object
var err error
if raw, err = client.CoreV1().RESTClient().Get().RequestURI(
	fmt.Sprintf("/apis/search.karmada.io/v1alpha1/search/cache/api/v1/namespaces/%s/pods", "lizhen6")).Do(
	context.Background()).Get(); err != nil {
	panic(err)
}
pods, ok := raw.(*corev1.PodList)
if !ok {
	panic("not pod list")
}
```

**Comment by XiShanYongYe-Chang** [comment]
In favor of #3312

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/assign @tedli
