### ISSUE TITLE
No need to call setTransitionTime before calling the SetStatusCondition method in syncClusterStatus.

### ISSUE THREAD

**Issue by xigang** [karmada-io/karmada#3313]
**What happened**:
There is no need to call setTransitionTime before calling the SetStatusCondition method. From the code logic, call setTransitionTime is not required.

https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/cluster_status_controller.go#L180 and https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/cluster_status_controller.go#L205

**What you expected to happen**:

The setTransitionTime method should be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
NONE
```

**Comment by dddddai** [comment]
Yes I think so

**Comment by XiShanYongYe-Chang** [comment]
Hi @xigang, do you mean that calling `setTransitionTime ` is redundant because it has been handled in `SetStatusCondition`?

If I understand correctly, this is a cleanup, not a bug.

**Comment by xigang** [comment]
> Hi @xigang, do you mean that calling `setTransitionTime ` is redundant because it has been handled in `SetStatusCondition`?
> 
> If I understand correctly, this is a cleanup, not a bug.

@XiShanYongYe-Chang  Yes, calling setTransitionTime is redundant. It's not a bug.

**Comment by XiShanYongYe-Chang** [comment]
Thanks~ Would you like to send a pr to remove it?

/kind cleanup
/remove-kind bug

**Comment by xigang** [comment]
> Thanks~ Would you like to send a pr to remove it?
> 
> /kind cleanup /remove-kind bug

okay, I submit a PR.

**Comment by Garrybest** [comment]
+1

**Comment by RainbowMango** [comment]
+1
/assign @xigang 
Thanks.
