### ISSUE TITLE
how to get pod in which member cluster

### ISSUE THREAD

**Issue by tomonight** [karmada-io/karmada#3322]
I have no way to get pod in which member, is there  any help ?
I want get pod in which cluster to Secondary development. but I can not found in spec or status etc.

**Comment by RainbowMango** [comment]
Do you mean after propagating a workload(like `Deployment`) to member clusters, how can I get the pods?
If yes, It depends on the cluster in which the Deployment is located. 

> I want get pod in which cluster to Secondary development.

What's the `Secondary development` thing?

**Comment by tomonight** [comment]
never mind . 
so how can I get located member cluster name .  There only pod spec, sts or deployment spec I get from karmada apiserver. how to get cluster name for each pod using these info

**Comment by tomonight** [comment]
using for multi cluster mysql base on karmada.
but there some problems . like dns.  using karmada statefulset locate pod in multiple members. but dns can't found each other. so I want get pod(or service) IP and host to spread every members. First I want where pod is(which cluster), but sound like not easy.
