### ISSUE TITLE
Enhance Karmada UT coverage

### ISSUE THREAD

**Issue by realnumber666** [karmada-io/karmada#3327]
**What would you like to be added**:
Improve the UT coverage from 49% to 69% (↑20%)

**Why is this needed**:
To improve the reliability of the Karmada project, verify the implementation and usability of functions, and improve user experience.

**Plan**:
For maximum efficiency, I will start with the files and folders with the most missed lines.
- [ ] Improve UT coverage of `pkg` from 49% to 80%
- [ ] Improve UT coverage of `cmd` from 31% to 69%
- [ ] Improve UT coverage of `examples` from 64% to 69%

*Here is the reference for the UT coverage [link](https://app.codecov.io/gh/karmada-io/karmada)*

**Comment by XiShanYongYe-Chang** [comment]
Although the target has not been achieved, we have already covered the majority of code that does not involve controller components. Moving forward, we will continue to maintain and improve code coverage.
/close
