### ISSUE TITLE
client-go informer cache synchronization delay linked through the karmada search proxy

### ISSUE THREAD

**Issue by hansongChina** [karmada-io/karmada#3334]
**What happened**: Found that the resource status obtained by informer was not up to date when using the karmada search agent.This is especially true when multiple project deployments are started。By checking karmada logs, it is found that there are listAndWatch delay and deltaFIFO accumulation。client-go version is v0.24.2
![image](https://user-images.githubusercontent.com/7590000/227824308-7e6bb2f9-1377-48b7-b913-8b89930e947f.png)
![image](https://user-images.githubusercontent.com/7590000/227828088-2d87c6fc-2ee5-49a4-ba61-9bb77a83ef39.png)

**What you expected to happen**:
client-go informer Cache synchronization is normal

**How to reproduce it (as minimally and precisely as possible)**:
This occurs when Karmada-linked multiple clusters have many resources, and when a large number of resources are modified at the same time.

**Anything else we need to know?**:
Now there are 3 clusters in the environment, pod quantity is 22.77k。

**Environment**: 
client-go v0.24.2
- Karmada version: v1.3.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):v1.3.0
- Others:

**Comment by RainbowMango** [comment]
cc owners @XiShanYongYe-Chang @ikaven1024 @liys87x

**Comment by hansongChina** [comment]
@ikaven1024 
There are 8 instances of karmada-search，the configuration is 12C64G。
The machine on which karmada-search is deployed is 64C256G。
client-go informer cache synchronization is slow. informer operations are mainly list and watch operations。
![image](https://user-images.githubusercontent.com/7590000/228102678-33e0233f-c119-49b2-90e4-0d0fc736fa47.png)
![image](https://user-images.githubusercontent.com/7590000/228102860-6cfae2b8-f5ae-4cbd-82e7-4d009de81b5b.png)

**Comment by hansongChina** [comment]
> @hansongChina Thanks. Could you provide cpu profile of karmada-search with below command when `a large number of resources are modified at the same time`:
> 
> ```shell
> curl http://<KARMADA_SEARCH_IP>:6060/debug/pprof/profile -o cpu.pprof
> ```

Wait, we'll catch it when it reappears

**Comment by hansongChina** [comment]
I ran a pressure test in the test environment, running 100 workflows simultaneously. Each workflow has two nodes, the first node has a pod, and the second node is a vcjob, a master and worker training. The cpu profile was captured for 5 minutes
[search-cpu1102.pprof.gz](https://github.com/karmada-io/karmada/files/11117867/search-cpu1102.pprof.gz)

**Comment by RainbowMango** [comment]
> `slow event handlers blocking the queue` 

The log seems to say that the event handler function is running slowly.
What the handler does depends on the backend storage configuration in [ResourceRegistry](https://github.com/karmada-io/karmada/blob/5194e1761ae4d344d5b14450eec83bf116627601/pkg/apis/search/searchregistry_types.go#L37-L39).

@hansongChina Can you confirm or share the ResourceRegistry configuration here?

**Comment by RainbowMango** [comment]
> And have you turn off search feature with --disable-search?

Well, that reminds me. Maybe the `search` consumes too much CPU/Memory and slowed down the `proxy` functionality.

```
      --disable-proxy                                                                                                                                                                                                            
                Disable proxy feature that would save memory usage significantly.
      --disable-search                                                                                                                                                                                                           
                Disable search feature that would save memory usage significantly.
```

**Comment by hansongChina** [comment]
> 

  resourceSelectors:
  - apiVersion: v1
    kind: Node
  - apiVersion: v1
    kind: Pod
  - apiVersion: v1
    kind: Event
  - apiVersion: v1
    kind: Namespace
  - apiVersion: v1
    kind: PersistentVolumeClaim
  - apiVersion: v1
    kind: PersistentVolume
  - apiVersion: v1
    kind: ResourceQuota
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
  - apiVersion: v1
    kind: ConfigMap
  - apiVersion: v1
    kind: Secret
  - apiVersion: kubeflow.org/v1
    kind: Profile
  - apiVersion: kubeflow.org/v1
    kind: Notebook
  - apiVersion: kubeflow.org/v1beta1
    kind: Notebook
  - apiVersion: scheduling.volcano.sh/v1beta1
    kind: PodGroup
  - apiVersion: scheduling.volcano.sh/v1beta1
    kind: Queue
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
  - apiVersion: argoproj.io/v1alpha1
    kind: WorkflowTemplate
  - apiVersion: argoproj.io/v1alpha1
    kind: ClusterWorkflowTemplate
  - apiVersion: lpai.org/v1
    kind: Streamlit
  - apiVersion: tensorboard.kubeflow.org/v1alpha1
    kind: Tensorboard
  - apiVersion: apps/v1
    kind: ReplicaSet
  - apiVersion: apps/v1
    kind: StatefulSet
  - apiVersion: batch.volcano.sh/v1alpha1
    kind: Job
  - apiVersion: lpai.lixiang.com/v1alpha1
    kind: Iojob
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
  - apiVersion: security.istio.io/v1beta1
    kind: AuthorizationPolicy
  - apiVersion: batch/v1
    kind: Job
  - apiVersion: apps/v1
    kind: Deployment
  - apiVersion: keda.sh/v1alpha1
    kind: TriggerAuthentication
  - apiVersion: keda.sh/v1alpha1
    kind: ScaledObject
  targetCluster:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3
    - cluster4

**Comment by hansongChina** [comment]
> We have test before: 2 millions pods, and 1m18s latency. #2518 How much latency on you side with 22.77k pods. And have you turn off `search` feature with `--disable-search`?

how to turn off ?

**Comment by hansongChina** [comment]
> ```yaml
>    - --disable-search 
> ```

I'll give it a try

**Comment by hansongChina** [comment]
> ```yaml
> - --disable-search
> ```

Whether version v1.3.0 supports this parameter

**Comment by XiShanYongYe-Chang** [comment]
Discussed in the WeChat group, and by disabling the search feature, we solved this problem. as the number of clusters increases, the problem persists, which is a performance issue that needs to be continuously optimized.

The issues tracked by the current issue have been resolved.
/close
/kind question
