### ISSUE TITLE
Failed runing kubectl-karmada within a pod

### ISSUE THREAD

**Issue by hzxuzhonghu** [karmada-io/karmada#3335]
Met below error when run kubectl-karmada init in a pod. The intention is in [kurator](https://github.com/kurator-dev/kurator) we want to install karmada control plane in a pod. 
```
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

```

I guess it is because of lacking incluster client initiation support.

**Comment by XiShanYongYe-Chang** [comment]
/cc @lonelyCZ 
Can you help take a look?

**Comment by lonelyCZ** [comment]
Could we use volumn to mount `Kubeconfig`? The `incluster client` is usually used by `controller`, I am not sure if introduce it to `karmadactl`.

**Comment by hzxuzhonghu** [comment]
In my case, i donot have the a secret that contains kubeconfig

**Comment by hzxuzhonghu** [comment]
To clarify: the intent is to install karmada controlplane into the cluster where the pod is running.

**Comment by lonelyCZ** [comment]
> To clarify: the intent is to install karmada controlplane into the cluster where the pod is running.

Make sense. Perhaps, we can discuss it in tomorrow's community meeting.

**Comment by RainbowMango** [comment]
> Currently, karmadactl init only support to deploy karmada in a host kubernetes cluster. If we need to deploy it within a Pod, should we need to use binary installation?

Can you remind me what's the gap to support this scenario?

**Comment by lonelyCZ** [comment]
> > Currently, karmadactl init only support to deploy karmada in a host kubernetes cluster. If we need to deploy it within a Pod, should we need to use binary installation?
> 
> Can you remind me what's the gap to support this scenario?

Oh, I just misunderstanded the intention of this PR. 

The gap to container and binary installation is that now we only need to deploy the `Deployment` to host kubernetes cluster using Image, but for binary installation, we need to compile the source codes, and start all components by `systemd` as https://karmada.io/docs/installation/install-binary/

**Comment by RainbowMango** [comment]
> The intention is in [kurator](https://github.com/kurator-dev/kurator) we want to install karmada control plane in a pod.

My understanding is that @hzxuzhonghu wants to install Karmada in a container by `karmadactl init`, isn't it? @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
>My understanding is that @hzxuzhonghu wants to install Karmada in a container by karmadactl init, isn't it? @hzxuzhonghu

Right. Not so complex no systems related, it just needs to support in-cluster kube client build.

**Comment by RainbowMango** [comment]
I see @lonelyCZ added an agenda to [today's community meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.rvewyilqgi4m).  Can we have a chat there @hzxuzhonghu ?

**Comment by hzxuzhonghu** [comment]
Would like to attend the meeting

**Comment by RainbowMango** [comment]
Wow, so quick!
/assign #3338 
After quickly going through the PR, I bet it should be a workable solution.
