### ISSUE TITLE
Propose donot delete namespace when karmadactl deinit

### ISSUE THREAD

**Issue by hzxuzhonghu** [karmada-io/karmada#3344]
**What would you like to be added**:

I installed karmada in a private namespace which has many other resource objects that donot belong to karmada.

However when i uinstall with kubectl-karmda deinit -n <my namespace>, my namespace <my namespace> is also deleted, which is not expected.

Looking into istio, it also use `istioctl uninstall`, but after it uninstall, the namespace is still there. Deleting a namespace can be terrible, i think this option should be given back to user.

**Comment by XiShanYongYe-Chang** [comment]
It makes sense, maybe we can consider adding an option to control.
Ask the module owner to help take a look.

/cc @lonelyCZ @carlory

**Comment by lonelyCZ** [comment]
> @lonelyCZ Please take a look at #3326, seems the same issue.

Oh, I missed it. Let't continue to #3326 .

**Comment by RainbowMango** [comment]
In my opinion, if we can recognize that the namespace was created by Karmada, then we have the confidence to remove it during deinit `by default`, (relying #2862). 
But also glad to have the option/flag to reserve the namespace from deleting.

**Comment by lonelyCZ** [comment]
This has be resolved by #3326 

/close
