### ISSUE TITLE
Introduce a helper method(ReplicaSchedulingType) for PropagationPolicy Placement

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3347]
**What would you like to be added**:
Proposing to introduce a helper method for [Placement](https://github.com/karmada-io/karmada/blob/5194e1761ae4d344d5b14450eec83bf116627601/pkg/apis/policy/v1alpha1/propagation_types.go#L71), like:
```golang
// ReplicaSchedulingType returns the replica assignment strategy which is
// "Duplicated" or "Divided".
func (p *Placement) ReplicaSchedulingType() ReplicaSchedulingType {
	if p.ReplicaScheduling == nil {
		return ReplicaSchedulingTypeDuplicated
	}

	return p.ReplicaScheduling.ReplicaSchedulingType
}
```
The function could be put at [propagation_helper.go](https://github.com/karmada-io/karmada/blob/master/pkg/apis/policy/v1alpha1/propagation_helper.go).

**Why is this needed**:
By leveraging this method, the following code could be simplified:

https://github.com/karmada-io/karmada/blob/5194e1761ae4d344d5b14450eec83bf116627601/pkg/scheduler/scheduler.go#L327-L328

https://github.com/karmada-io/karmada/blob/5194e1761ae4d344d5b14450eec83bf116627601/pkg/scheduler/scheduler.go#L375-L376

In addition, it might be used by #3321 (see comment https://github.com/karmada-io/karmada/pull/3321/files#r1153962080)

**Comment by RainbowMango** [comment]
@Garrybest @Poor12 Does that make sense to you?

**Comment by XiShanYongYe-Chang** [comment]
It looks more clear!

**Comment by whitewindmills** [comment]
/assign
I like this suggestion and I want to implement this function.

**Comment by RainbowMango** [comment]
OK, thanks @whitewindmills, just a reminder, we may need a unit test for it.

**Comment by whitewindmills** [comment]
> OK, thanks @whitewindmills, just a reminder, we may need a unit test for it.

Thanks for your reminder.

**Comment by Garrybest** [comment]
+1

**Comment by whitewindmills** [comment]
This [code](https://github.com/karmada-io/karmada/pull/3321/files#diff-a21edee9bcb99a3ea73ba7aa2aba4a680152bed1d6382dd332a08776d98b3b47R59) reminded me. Perhaps it would be more elegant to fill default replica strategy type as `Duplicated` by webook mutating , so all judgments are no longer needed.

**Comment by whitewindmills** [comment]
I don't think it is necessary to modify the API by upgrading to v1alpha2, we just add this part of the logic to the pp mutating webhook after this [line,](https://github.com/karmada-io/karmada/blob/master/pkg/webhook/propagationpolicy/mutating.go#L62) like:
```
// Set default ReplicaStrategy if it's not set.
helper.SetDefaultReplicaStrategy(policy.Spec.Placement.ReplicaScheduling)
```

**Comment by Poor12** [comment]
Sorry, I guess you misunderstand my meaning. We do not upgrade API specifically to fix this issue. Explicitly configuring `duplicated` is a redundant approach. In the long run, we might remove `ReplicaSchedulingType` according to https://github.com/karmada-io/karmada/pull/3290#discussion_r1144321645.

**Comment by Poor12** [comment]
> Okay, I got you. But if there is a new replica strategy, how should we make it compatible? In the future, replica strategy type may become more and more abundant. For example, I want pick any one cluster with best score(_In fact, we do have this demand_).

Yeah, switching API versions is a prudent thing. We must ensure API compatibility before upgrading API versions. You are more than welcome to come and participate in the follow-up discussion. For now, let's focus the helper method which may make codes clearer.
