### ISSUE TITLE
propagationpolicy rule set namespace but can not propagation resource to member cluster

### ISSUE THREAD

**Issue by fusongke100** [karmada-io/karmada#3359]
karmada version:1.5.0
k8s version:1.21.0
![image](https://user-images.githubusercontent.com/3871556/229435962-ade2ce67-5792-4661-b1dc-0ecdfb98c9d5.png)
can query service-minio serviceaccount in karmada 
![image](https://user-images.githubusercontent.com/3871556/229436152-fd7e62d6-d8ca-4a20-a05e-0cad7a0d41f9.png)
but can not query serviceaccount in member cluster
![image](https://user-images.githubusercontent.com/3871556/229436658-4a3e2eae-9a66-4dee-aa89-e5869a8e1dd1.png)

**Comment by fusongke100** [comment]
I use the **ClusterPropagationPolicy**  , it work well. thank you.

what means for  'target the resources in the same namespace' , could you pls give a example?

and I have another question, when I execute karmadactl command, it show some error message:
![image](https://user-images.githubusercontent.com/3871556/229455392-9cc760d8-03ed-4d7f-bd7e-57a2a744f157.png)

**Comment by RainbowMango** [comment]
> what means for 'target the resources in the same namespace' , could you pls give a example?

`target` == `match`.  I mean PropagationPolicy can only `match` resources in the same namespace. 

In other words, when Karmada matching PropagationPolicy for a namespace-scoped resource, it only match against the PropagationPolicy in the same namespace. See this code:
https://github.com/karmada-io/karmada/blob/7502b2507f3c4004d94e272f5e03e1dfde83d0e2/pkg/detector/detector.go#L318-L319

**Comment by RainbowMango** [comment]
> and I have another question, when I execute karmadactl command, it show some error message:

`karmadactl` loading Karmada config(kubeconfig) from:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

Please check whether the configuration file is correctly configured. 
A common mistake is that the specified kubeconfig belongs to a member cluster instead of  `Karmada control plane`.
