### ISSUE TITLE
PropagationPolicy doesn't work when target resource is in kube-system namespace

### ISSUE THREAD

**Issue by LronDC** [karmada-io/karmada#3369]
**Please provide an in-depth description of the question you have**:
I created a `ConfigMap` on Karmada's ControlPlane in `kube-system` namespace.
Then I created a `PP` to propagate the `ConfiMap` to member1 (which also Karmada ControlPlane is on) and member2. 
But `PP` didn't work because no new `ConfigMap` was created on member1 or member2. So I look into Karmada-controller-manager's pod log, and noticed that `Matched 0 resources by policy(kube-system/xxx`
After confirming the `PP` was created right, I assume that maybe it's the `kube-system` namespace's reason. Then I created an experimental namespace and it worked.
**What do you think about this question?**:
Got 3 associated questions:
1. Is my inference about "Karmada has some protection mechanisms on special namespaces" right?
2. why is protection necessary?
3. Does(or will) Karmada support turning off that kind of limit like feature gateway or environment variables?

**Environment**:
- Karmada version: newest
- Kubernetes version: 1.26

**Comment by chaunceyjiang** [comment]
> Is my inference about "Karmada has some protection mechanisms on special namespaces" right?

Yes, 
https://github.com/karmada-io/karmada/blob/31435bf7f21863a48723975eac5fc9307436235e/pkg/detector/detector.go#L229-L238

**Comment by chaunceyjiang** [comment]
Just a question, Why do you need to create a ConfigMap in the kube-system namespace?

**Comment by LronDC** [comment]
> Just a question, Why do you need to create a ConfigMap in the kube-system namespace?

👋 hi, I'm running a cluster inspection tool that will create a pod which mounts a configmap created from shell scripts(inspection commands in it), it's designed to run on `kube-system` namespace for some specific reason on the business side(regardless it's a bad design or not).
I was trying to use it with Karmada -- propagate the configmap to members, then I bumped into these questions.

**Comment by chaunceyjiang** [comment]
Get it.

I think Karmada should provide a mechanism to allow users to propagate resources under  `Kubernetes reserved namespace`.
