### ISSUE TITLE
Centralized HPA architecture

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3379]
**What would you like to be added**:
#### Decentralized HPA:
The concept of [Decentralized HPA](https://github.com/karmada-io/karmada/blob/33a0593c6984e7d35c34ec9576fa5448d81593ca/docs/proposals/hpa/federated-hpa-v2.md) can be complex to comprehend and configure, leading to confusion among users. Additionally, it may result in duplicate jobs with the scheduler.
But it does have one advantage, though: if the control plane goes down, it can still handle burst requests.

#### Centralized HPA
Centralized HPA is quite easy to understand and configure, there are three kinds of architecture:
K8s native metrics server(CPU/Memory):
![image](https://github.com/karmada-io/karmada/assets/19745536/104b972c-2c27-4733-ae01-09364988cad8)

Customer metrics server:
![image](https://github.com/karmada-io/karmada/assets/19745536/fc1c30af-c9f9-4d6c-b4ae-2a4cdb5fb58d)

![image](https://github.com/karmada-io/karmada/assets/19745536/2f79fcfa-2869-4325-a9a1-48ba86c17f89)

By implementing this architecture, the HPA will solely focus on scaling deployments while the scheduler schedules replicas based on priority policies.   
However, a drawback of this approach is that in case of control plane failure, it cannot manage sudden surge requests.

**Why is this needed**:
In the current era of single clusters, Horizontal Pod Autoscaling (HPA) is commonly used to dynamically scale workload replicas to handle incoming requests and enhance resource utilization. Therefore, in the era of multi-clusters, HPA should still work and be capable of scaling the workloads in different member clusters, to resolve resource limitations for a single cluster and improve scaling fail recovery capabilities.

**Comment by jwcesign** [comment]
cc @Garrybest @XiShanYongYe-Chang @chaunceyjiang what do you think?

**Comment by chenwei01** [comment]
By the way，Will the new version adopt a centralized architecture ? When is the next version scheduled to be released？

**Comment by jwcesign** [comment]
There are two types of architecture: centralized and decentralized, each with its own advantages. Users can choose the type they prefer.

The decentralized HPA has a higher priority.

BTW, what's your use case? @chenwei01

**Comment by chenwei01** [comment]
@jwcesign got it, thanks, my scenario basically matches the use cases in the proposal.

**Comment by jwcesign** [comment]
This feature is finished, let's close this issue
