### ISSUE TITLE
join member error occurs

### ISSUE THREAD

**Issue by fusongke100** [karmada-io/karmada#3394]
karmada version: 1.5
kubenetes version: 1.21.0

When I join the member cluster , the following error occurs:
![image](https://user-images.githubusercontent.com/3871556/231153538-1d0ca451-6139-4bce-978f-11dc92b0e29c.png)

**Comment by whitewindmills** [comment]
@fusongke100
It seems you are using _Azure_ AuthProvider but Karmada does not import _Azure_ auth plugins by default. Is it necessary to use _Azure_ AuthProvider? If not, try to remove it from your `kubeconfig`.
