### ISSUE TITLE
Update the documents regarding the `karmadactl interpret --operation ReviseReplica` section

### ISSUE THREAD

**Issue by yike21** [karmada-io/karmada#3401]
**What would you like to be added**:
The introduction about `karmadactl interpret -f customization.yml --operation ReviseReplica--observed-file observed.yml` can be found in [interpret.go](https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/interpret/interpret.go#L49) and [karmadactl-commands/karmadactl_interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret/). 
Then I find that the document [karmadactl-usage-conventions](https://karmada.io/docs/reference/karmadactl/karmadactl-usage-conventions) and [examples/karmadactlinterpret/README.md](https://github.com/karmada-io/karmada/blob/master/examples/karmadactlinterpret/README.md) haven't been updated.  
Perhaps this section of the document should be updated about `karmadactl interpret --operation ReviseReplica`.

**Why is this needed**:
If the documents are updated, users can more easily find the `karmadactl interpret --operation ReviseReplica` section.

**Comment by Poor12** [comment]
You can contribute documents based on https://karmada.io/docs/contributor/contribute-docs.

**Comment by yike21** [comment]
> You can contribute documents based on https://karmada.io/docs/contributor/contribute-docs.

Ok, I am willing to do it!
