### ISSUE TITLE
karmadactl init configuration files and other information are divided according to namespace

### ISSUE THREAD

**Issue by helen-frank** [karmada-io/karmada#3408]
**What would you like to be added**:
`karmadactl init` generates configuration files and other information according to the namespace division
For example
```bash
# tree /etc/karmada
/etc/karmada
|-- karmada-system
|-- test1
`-- test2
```
**Why is this needed**:
when multiple sets of karmada are deployed on one set of k8s, information such as configuration files will be overwritten

**Comment by RainbowMango** [comment]
Hi @helen-frank Can you give an example of how many configuration files `karmadactl init` would generate and what's the tree layout?
I'd like to cc @lonelyCZ for comments.

**Comment by helen-frank** [comment]
```bash
# tree /etc/karmada -L 2
/etc/karmada
|-- karmada-system
|   |-- crds
|   |-- crds.tar.gz
|   |-- karmada-agent.yaml
|   |-- karmada-apiserver.config
|   |-- karmada-scheduler-estimator.yaml
|   `-- pki
|-- test1
|   |-- crds
|   |-- crds.tar.gz
|   |-- karmada-agent.yaml
|   |-- karmada-apiserver.config
|   |-- karmada-scheduler-estimator.yaml
|   `-- pki
`-- test2
    |-- crds
    |-- crds.tar.gz
    |-- karmada-agent.yaml
    |-- karmada-apiserver.config
    |-- karmada-scheduler-estimator.yaml
    `-- pki

9 directories, 12 files
```
@RainbowMango

**Comment by RainbowMango** [comment]
This is the directory structure you'd expect, right? What's the current directory structure look like?

**Comment by helen-frank** [comment]
Yes, I hope he can divide it according to namespace.
This is the current
```bash
$ tree /etc/karmada -L 2
/etc/karmada
|-- crds
|   |-- bases
|   |-- kustomization.yaml
|   `-- patches
|-- crds.tar.gz
|-- karmada-agent.yaml
|-- karmada-apiserver.config
|-- karmada-scheduler-estimator.yaml
`-- pki
    |-- apiserver.crt
    |-- apiserver.key
    |-- ca.crt
    |-- ca.key
    |-- etcd-ca.crt
    |-- etcd-ca.key
    |-- etcd-client.crt
    |-- etcd-client.key
    |-- etcd-server.crt
    |-- etcd-server.key
    |-- front-proxy-ca.crt
    |-- front-proxy-ca.key
    |-- front-proxy-client.crt
    |-- front-proxy-client.key
    |-- karmada.crt
    `-- karmada.key

4 directories, 21 files
```

**Comment by helen-frank** [comment]
The preliminary expected code changes involve `init` and `deinit`. @RainbowMango

**Comment by lonelyCZ** [comment]
Currently, the situation of multi karmada instance seems rare, but it can be relized by `karmada operator`.

I think it is better that `karmadactl` focus on single instance and high available. And the `hostPath` seems not a good choice for production env.

What do you think? @helen-frank

**Comment by lonelyCZ** [comment]
Thanks for sharing your usage case. @helen-frank Have you test the options `--karmada-data='/etc/karmada'`, `--karmada-pki='/etc/karmada/pki'`, it seems configurable.

**Comment by RainbowMango** [comment]
> And the hostPath seems not a good choice for production env.

That's exactly my biggest concern, especially when people ask me if `karmadactl init` can be used in production :)

**Comment by lonelyCZ** [comment]
> That's exactly my biggest concern, especially when people ask me if karmadactl init can be used in production :)

Yes, but now the `/etc/karmada` is more same as a backup file, because we have saved them as `secret` or `configmap` in karmada control plane or host cluster. 

The key point still is high availability of `etcd`, the default is `hostPath` in `/var/lib/karmada-etcd` that seems not applicable for production env, but it can be configurable by `options`, so it should be used in production.
