### ISSUE TITLE
The member cluster webhook modifies the workload, which will be overwritten by the work

### ISSUE THREAD

**Issue by xigang** [karmada-io/karmada#3410]
**What happened**:

The workload spec in the member cluster is modified by the `webhook` of the member cluster (for example: injected into the sidecar container), and the `work-status-controller` will use the `Work` object manifest (workload) defined in the work to overwrite the spec in the member cluster. Is this expected?

Ref: https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/work_status_controller.go#L218

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Poor12** [comment]
When the resource objects on the control plane and member clusters are inconsistent, the resource templates on the control plane are currently used to overwrite the resource objects on the member clusters.

A common solution is to use the [retain](https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter#interpreter-operations) method of the custom resource interpreter to keep the changed fields in the member cluster.

**Comment by xigang** [comment]
@Poor12 Thank you for your reply. See `InterpreterOperationRetain` comment. `Resource Interpreter` can prevent member resource template from being overwritten. Let me see the implementation of the code.
