### ISSUE TITLE
How to manager the applications  which have existed in member cluster  

### ISSUE THREAD

**Issue by fusongke100** [karmada-io/karmada#3417]
When I use karmada to deploy the aplication , It does not operative,How to manager the applications  which have existed in member cluster ?

**Comment by chaunceyjiang** [comment]
> It does not operative,

What are you basing your judgment on?

**Comment by fusongke100** [comment]
I mean , an old cluster which have already run many applications.  now I want to use karmada to manager the old cluster. but when I propagation resource to old cluster, the application do not redeploy.

**Comment by lonelyCZ** [comment]
Hi @fusongke100 , please try `karmadactl promote` https://karmada.io/docs/administrator/migration/promote-legacy-workload/.

**Comment by chaunceyjiang** [comment]
> but when I propagation resource to old cluster, the application do not redeploy.

You can add an annotation in your application like: `work.karmada.io/conflict-resolution : overwrite`


https://github.com/karmada-io/karmada/blob/df43a00e527fdb1dfbed6e89a9aaf3cf123d492d/pkg/apis/work/v1alpha2/well_known_constants.go#L39-L51

**Comment by fusongke100** [comment]
hello ，I have added 'work.karmada.io/conflict-resolution: overwrite' in resource template ,but it does not work ?

**Comment by chaunceyjiang** [comment]
>  but it does not work ?

What are you basing your judgment on?

**Comment by fusongke100** [comment]
I use this command 'kubectl --kubeconfig /etc/karmada/karmada-apiserver.config -n test3 edit deployment nginx' to add 'kubectl --kubeconfig /etc/karmada/karmada-apiserver.config -n test3 edit deployment nginx' , the old cluster do not redeploy.
the old cluster also have two pods. so why?

![image](https://user-images.githubusercontent.com/3871556/232688898-227ee798-4c69-4df0-94e9-2df84da2fa26.png)


![image](https://user-images.githubusercontent.com/3871556/232696635-325bc128-b5f8-4f65-a52c-bf74ba018822.png)

**Comment by chaunceyjiang** [comment]
Can you share your `PropagationPolicy`?

**Comment by fusongke100** [comment]
this is my PropagationPolicy:
![image](https://user-images.githubusercontent.com/3871556/232703766-17f38027-0357-417f-a1b9-aa0657cdd3e4.png)

**Comment by mkloveyy** [comment]
Do you have any matched `OverridePolicy` that covers the annotations?

**Comment by lonelyCZ** [comment]
Hi @fusongke100 , You can use `kubectl logs` `karmada-controller-manager` pod to check the workflow when you edit the deployment `nginx`. If you find some execptions, you can share the logs.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
