### ISSUE TITLE
Make namespace sync configurable

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#342]
**What would you like to be added**:

Which namespaces can be synced into member clusters should be configurable, maybe host cluster has more namespaces than karmada-system,default,kube-,karmada-es-,karmada-cluster. 

**Why is this needed**:

**Comment by pigletfly** [comment]
Also for event filter.

**Comment by pigletfly** [comment]
scenario: there is a third-party operator installed in a namespace , in both host cluster and member cluster.If the third-party operator is maintained, the namespace could be deleted.Then karama namespace controller will delete the operator namespace in the member cluster,which is not expected.

So I think we should provide a option.

**Comment by RainbowMango** [comment]
It makes sense to me. Are you going to propose a flag for this?

**Comment by pigletfly** [comment]
yes, I'd like to add a flag, the flag will used in eventfilter and namespace controller.

**Comment by RainbowMango** [comment]
I think the flag should be similar to `--skipped-propagating-apis`.

// Comma-separated namespaces that should be skipped from propagating in addition to the default skipped namespaces(namespaces prefixed by `kube-` and `karmada-`). 
--skipped-propagating-namespaces string

@kevin-wangzefeng How do you think?

**Comment by pigletfly** [comment]
They are totally different. watchedNamespaces will only watch specific namespaces, skipped-propagating-namespaces will skip these namespaces.In my case, I want to protect those namespaces used by operators, so I prefer `skipped-propagating-namespaces`.
