### ISSUE TITLE
Letting the user decide whether to automatically generate Propagation-policy when Promote

### ISSUE THREAD

**Issue by LronDC** [karmada-io/karmada#3429]
**What would you like to be added**:
Adding a flag like `--auto-generate-propagation-policy=true` or `propagation-policy-name=*` to command
```shell
karmadactl promote <RESOURCE_TYPE> <RESOURCE_NAME> -n <NAME_SPACE> -C <CLUSTER_NAME>
```

**Why is this needed**:
My story is: I want to do a migration of non-federal applications on the legacy cluster to Karmada Control Plane, then propagate the application to other member clusters. I used the `promote` command and noticed it creates `propagation-policy` with a suffix in its succession. So I need to get the `pp` and edit it manually(which requires a little more work in a scription way).

if the `--auto-generate-propagation-policy=true` flag is supported, I can manually create the `pp` with my other specific requests rather than the default one.

if the `propagation-policy-name=*` flag is supported I don't have to distinguish which is the automatically generated `pp` and then edit it. And it will be easier to get all processes scripted.

Any of these flags will meet my needs here.

Since I have to edit the `propagation-policy` anyway, I think why not let me decide whether to create a default one or how -- decide its name, even more.

Ps. Isn't it more reasonable to let the user create the `propagation-policy` on their thoughts instead of `promote`? Or the `"Promote"` **IS** designed to imply the propagation part? What's your opinion?

**Comment by Poor12** [comment]
I think it's reasonable for users to let them decide the name of auto-generated propagationPolicy. 
/cc @lonelyCZ for opinions.

**Comment by LronDC** [comment]
By the way, if it's decided to be optimized, will it be good for beginners of Karmada? If so I'd like to work on it.

**Comment by lonelyCZ** [comment]
Thanks for your feedback！ @LronDC 

The origin design of `karmadactl promote` is easy that only promote resources from one member cluster to karmada control plane and user still edit the auto-generated `pp` to propagate it to other member cluster.

It is reasonalbe for importing `--auto-generate-propagation-policy` and `--propagation-policy-name` that are convinent for users to define their own `pp`.

Expectint for your contributions, thank you! :)

**Comment by LronDC** [comment]
@lonelyCZ @Poor12 Hi, finally get the opportunity to work on this. May I humbly ask for a quick guide on how to add an option to a specific command? I think this will reduce some of the work required for reviewing and editing later on. It's ok if there is none, just asking. :)
/cc @chaunceyjiang  for suggestions.

**Comment by lonelyCZ** [comment]
> May I humbly ask for a quick guide on how to add an option to a specific command?

Hi @LronDC , you could directly refer the fallowing source codes:

https://github.com/karmada-io/karmada/blob/db01a125e2dadfe06d6270562b735e1e30bae774/pkg/karmadactl/promote/promote.go#L128-L139

> Especially on how to build and test on karmadactl when I finish the change. 

You can use the below command to compile `karmadactl` at root directory of karmada code.
```
make karmadactl
```

And then you can test it on you own karmada cluster or using the `hack/local-up-karmada.sh` to deploy and run Karmada control plane.

**Comment by LronDC** [comment]
Got it. Thank you! @lonelyCZ
