### ISSUE TITLE
Introduce deleteOption for GracefulEvictionTask

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3430]
**What would you like to be added**:
For application migration, we provide three ways, one is `Never` which means that Karmada will not delete the application in the failed clusters. But for the current GracefulEvictionTask, we cannot distinguish that GracefulEvictionTask should be kept or deleted when timeout is reached. In that case, we may need an flag to mark it.

**Why is this needed**:
Distinguish that GracefulEvictionTask should be kept or deleted when timeout is reached.

**Comment by zishen** [comment]
Before answering and looking into this case, I might need to ask some questions to understand this.

1.How long does this failed cluster last?
1.Can the value of unschedulable-threshold be set higher, until the failed cluster recovers?

**Comment by Poor12** [comment]
Another way is use `Producer` to judge it. For example, if a GracefulEvictionTask's producer is from `taintManager`, we may judge it from `Failover.Cluster.PurgeMode` and if a GracefulEvictionTask's producer is from `applicationFailoverController`, we may judge it from `Failover.Application.PurgeMode`.
I prefer to the former one.
/cc @RainbowMango  for opinions.

**Comment by Poor12** [comment]
For multi-cluster failover, some users may hope that application can remain on the failed cluster, and after the failure is restored, it is up to the user to decide how to deal with the redundant copy. In this case, we may want to keep the GracefulEvictionTask.

**Comment by zishen** [comment]
> For multi-cluster failover, some users may hope that application can remain on the failed cluster, and after the failure is restored, it is up to the user to decide how to deal with the redundant copy. In this case, we may want to keep the GracefulEvictionTask.

ok，I got it. It looks good.
Thanks for your patience.
