### ISSUE TITLE
affinityName can be set to an empty string.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#3441]
**What happened**:

``` yaml 
kind: PropagationPolicy
apiVersion: policy.karmada.io/v1alpha1
metadata:
  name: ingress-ingress-region-test-jcdue
  namespace: default
  uid: 8b1ed9e2-bbfa-4cd5-9ef3-c418c3e19488
  resourceVersion: '200261'
  generation: 1
  creationTimestamp: '2023-04-20T09:26:53Z'
spec:
  resourceSelectors:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      namespace: default
      name: ingress-region-test
  placement:
    clusterAffinities:
      - affinityName: ''
        fieldSelector:
          matchExpressions:
            - key: region
              operator: In
              values:
                - shanghai
    clusterTolerations:
      - key: cluster.karmada.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: cluster.karmada.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
  priority: 0
  schedulerName: default-scheduler

```

![image](https://user-images.githubusercontent.com/17962021/233528739-12536517-26a1-4c2e-a3b0-fe975081ef74.png)

affinityName can be set to an empty string.
**What you expected to happen**:

According to the definition of api, this field should not allow setting an empty string, right?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaunceyjiang** [comment]
Please help confirm.

/cc @RainbowMango @XiShanYongYe-Chang

**Comment by RainbowMango** [comment]
> According to the definition of api, this field should not allow setting an empty string, right?

Yes. Nice finding. We need to add validation for that. Can kubebuilder do that?

**Comment by chaunceyjiang** [comment]
> Can kubebuilder do that?

https://book.kubebuilder.io/reference/markers/crd-validation.html

`+kubebuilder:validation:MinLength=1`

specifies the minimum length for this string.

**Comment by XiShanYongYe-Chang** [comment]
Nice finding, thanks~

Should we consider adding regex matching so that names can only begin with letters?

**Comment by RainbowMango** [comment]
> Should we consider adding regex matching so that names can only begin with letters?

Why do we need to do that?

**Comment by XiShanYongYe-Chang** [comment]
> Why do we need to do that?

To prevent such a naming?
```
$test
*123
%...
```

**Comment by RainbowMango** [comment]
It makes sense to me. Maybe DNS How do you say? @chaunceyjiang 

In addition, I think we can restrict the max length(like `+kubebuilder:validation:MaxLength=32`), no specific reason :(
