### ISSUE TITLE
Add kinds options for detector filter

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#345]
**What would you like to be added**:
The detector should only care about kinds that are set via options,otherwise the waiting list would be very large, there are unconcerned objects are adding into the waiting list.

PS: I'm not using a karmada-api-server,so there are many other objects along with karmada-controller-manager.

**Why is this needed**:

**Comment by RainbowMango** [comment]
Yes, good idea. We should provide the ability to decide which resources that karmada should care about.

Furthermore, maybe not just the kinds list, maybe the namespaces list also needs to set.

**Comment by pigletfly** [comment]
yeah, https://github.com/karmada-io/karmada/issues/342 describes we should provide a way to make namespaces list configurable.

**Comment by RainbowMango** [comment]
In my opion, by default `detector` should watch all resources with limited ignore list:
1. part of resource types that introduced by `karmada` should be ignored, such as `Work` should be ignored, but `PropagataionPolicy` should be watched.
2. part of resource types that introduced by `kube-apiserver` that users might don't care about, such as `Node`, `ComponentStatus`

By the way, the `2`th on the above also can be done by `--runtime-config` [options of kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options).

**Comment by RainbowMango** [comment]
> The detector should only care about kinds that are set via options,

We should provide a ability to users to disable a group of `kinds` and enable a group of `kinds` that has been ignored by default.

The behaviour similar with admission plugins options in `kube-apiserver`, `--disable-admission-plugins` and `--enable-admission-plugins`.

**Comment by pigletfly** [comment]
> In my opion, by default `detector` should watch all resources with limited ignore list:
> 
> 1. part of resource types that introduced by `karmada` should be ignored, such as `Work` should be ignored, but `PropagataionPolicy` should be watched.
> 2. part of resource types that introduced by `kube-apiserver` that users might don't care about, such as `Node`, `ComponentStatus`
> 
> By the way, the `2`th on the above also can be done by `--runtime-config` [options of kube-apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/#options).
agreed.But the runtime-config cares about apiVerion and Group,I think we only care about Kind.

**Comment by RainbowMango** [comment]
```
`--disable-resource-templates strings`
resource templates that should be disabled in addition to the default disabled resource template list(cluster.karmada.io, policy.karmada.io, work.karmada.io). The item format:
<group> for disable resources with a specific API group(e.g. networking.k8s.io)
<group>/<version> for disable resources with a specific API version(e.g. networking.k8s.io/v1beta1)
<group>/<version>/<kind>,<kind> for disable one or more specific resource(e.g. networking.k8s.io/v1beta1/Ingress,IngressClass)
```
Hi @pigletfly how do you think about this flag?

**Comment by pigletfly** [comment]
> ```
> `--disable-resource-templates strings`
> resource templates that should be disabled in addition to the default disabled resource template list(cluster.karmada.io, policy.karmada.io, work.karmada.io). The item format:
> <group> for disable resources with a specific API group(e.g. networking.k8s.io)
> <group>/<version> for disable resources with a specific API version(e.g. networking.k8s.io/v1beta1)
> <group>/<version>/<kind>,<kind> for disable one or more specific resource(e.g. networking.k8s.io/v1beta1/Ingress,IngressClass) where the kinds are case-insensitive.
> ```
> 
> Hi @pigletfly how do you think about this flag?

SGTM.So there is also a `--enable-resource-templates` ?

**Comment by RainbowMango** [comment]
> So there is also a --enable-resource-templates ?

Not sure yet.  
`--enable-resource-templates` used to enable the resource templates that have disabled by default, I doubt if users really need it, it might depend on what resources in the default disable list.

So, I think we should make clear that which resources should be in the default disable list first.

**Comment by RainbowMango** [comment]
Another option: difference is `semicolon-delimited` vs `comma-delimited`
```
`--disable-resource-templates strings`
Semicolon-delimited resource templates that should be disabled in addition to the default disabled resource template list(cluster.karmada.io;policy.karmada.io;work.karmada.io). The item format:
<group> for disable resources with a specific API group(e.g. networking.k8s.io)
<group>/<version> for disable resources with a specific API version(e.g. networking.k8s.io/v1beta1)
<group>/<version>/<kind>,<kind> for disable one or more specific resource(e.g. networking.k8s.io/v1beta1/Ingress,IngressClass) where the kinds are case-insensitive.
```

**Comment by kevin-wangzefeng** [comment]
nit: `--disable-resource-templates` might be confusing, as the API group/version/kind is not really disabled in the karmada-apiserver.

We'd like to have users able to indicated APIs that they want karmada skip from propagating to member cluster, so things like `--skipped-propagating-apis string` should be easier to understand.
