### ISSUE TITLE
After workload is scheduled, binding.status.schedulerObservedGeneration and generation are inconsistent

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3454]
**What happened**:
When I deploy a workload to multiple clusters with `divided` type and the workload is successfully scheduled, I found that binding.status.schedulerObservedGeneration and generation are inconsistent. Generation is 2 whereas schedulerObservedGeneration is 1. Because binding.Spec has undergone two changes, the binding is generated for the first time, and the scheduling result is written into the binding for the second. However, the second change will not be scheduled because the following three rules are not met.

https://github.com/karmada-io/karmada/blob/48e93dccb6b6ecce984175a37e06bc674424f24a/pkg/scheduler/scheduler.go#L312-L334

Binding.status.schedulerObservedGeneration equal to generation is a access requirement for eviction controller. This may influence failover process.

https://github.com/karmada-io/karmada/blob/48e93dccb6b6ecce984175a37e06bc674424f24a/pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go#L95

**What you expected to happen**:
After workload is scheduled, binding.status.schedulerObservedGeneration and generation should be the same.

**How to reproduce it (as minimally and precisely as possible)**:
Just use the sample in the Karmada repo.

**Anything else we need to know?**:
This may also exist in the latest three version.

**Environment**:
- Karmada version: v1.5
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your finding~

**Comment by RainbowMango** [comment]
Nice finding! Do you have any idea to handle it?

**Comment by Poor12** [comment]
I have a short discussion with @XiShanYongYe-Chang. The main idea is that even if do not need to schedule, we should regard as a successful scheduling and keep these two field the same.
