### ISSUE TITLE
Add kubebuilder shortName tag  

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#348]
**What would you like to be added**:

We should add kubebuilder shortName tag to resources, especially for PropagationPolicy, ReplicaSchedulingPolicy,OverridePolicy,ClusterOverridePolicy.Any ideas about this suggested list ?

| Name      | ShortName |
| ----------- | ----------- |
| PropagationPolicy      | pp       |
| ClusterPropagationPolicy      | cpp       |
| ReplicaSchedulingPolicy   | rsp        |
| OverridePolicy | op |
| ClusterOverridePolicy | cop |
| ResourceBinding | rb |
| ClusterResourceBinding | crb |

**Why is this needed**:

**Comment by RainbowMango** [comment]
Could you please give an example about the `kubebuilder` tag?

**Comment by pigletfly** [comment]
Here is a example in cluster-api https://github.com/kubernetes-sigs/cluster-api/blob/master/api/v1alpha3/cluster_types.go#L200

**Comment by RainbowMango** [comment]
Yeah, It makes sense to me.
We can discuss this at the next community meeting and make a decision there.

By the way, the `ClusterResourceBinding` is missing from the list.
