### ISSUE TITLE
Upgrade clister-api to v1beta1 for v1alpha3/v1alpha4 deprecated 

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3503]
As mentioned in `Update cluster-api version to semantic version` in #3502, the v1alpha3 and v1alpha4 were [deprecated at cluster-api@v1.4.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0), we might need to do some migration work.

Anyone who is interested in this issue can assign the work.

**Comment by jwcesign** [comment]
cc @JadeFlute0127

Can you take a look about this?

**Comment by JadeFlute0127** [comment]
yeah, it looks funny

**Comment by XiShanYongYe-Chang** [comment]
@JadeFlute0127 Thanks a lot~
