### ISSUE TITLE
fix an issue where DeepEqual becomes invalid in federated-resource-quota-status-controller

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3519]
**Task description**:

When the quota status is collected from the work, we check whether the federatedResourceQuota status changes to reduce the number of updated. However, the result is always false when the status pointer is compared with quota.Status, so we need to change the pointer to the struct.

**Solution**:

```diff
diff --git a/pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go b/pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
index 046ab4b0..8d154f41 100644
--- a/pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
+++ b/pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
@@ -139,7 +139,7 @@ func (c *StatusController) collectQuotaStatus(quota *policyv1alpha1.FederatedRes
        quotaStatus.AggregatedStatus = aggregatedStatuses
        quotaStatus.OverallUsed = calculateUsed(aggregatedStatuses)

-       if reflect.DeepEqual(quota.Status, quotaStatus) {
+       if reflect.DeepEqual(quota.Status, *quotaStatus) {
                klog.V(4).Infof("New quotaStatus are equal with old federatedResourceQuota(%s) status, no update required.", klog.KObj(quota).String())
                return nil
        }
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang I remember we have dealt with a similar issue at #3363, can you help to check this issue from a repo perspective?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang I remember we have dealt with a similar issue at #3363, can you help to check this issue from a repo perspective?

Thanks~, I checked the entire repo, and this is the only place left.
