### ISSUE TITLE
Fix a typo in karmada-operator

### ISSUE THREAD

**Issue by Poor12** [karmada-io/karmada#3544]
**Task description**:
There is a typo in the module of `karmada-operator`. 
`operator/pkg/karmadaresource/webhookconfiguration/mainfests.go` => `operator/pkg/karmadaresource/webhookconfiguration/manifests.go`

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Nikko-Adrian-Pacleb** [comment]
Hi I am very new to open source and I would like to try doing this task. 
What I'm about to do:
 - Go to the module file
 - Change the name of the file

thats it. I don't know if there are other things that are needed to be done please do tell me. I would love to learn more. (aside from forking and creating a pull request)

**Comment by RainbowMango** [comment]
/assign @Nikko-Adrian-Pacleb 
In favor of #3545
