### ISSUE TITLE
Endpointslices on the karmada control plane are not cleared after a cluster failover

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3546]
**What happened**:

When a member cluster failover, the Endpointslices on the karmada control plane which is derived from the faulty member cluster are not cleared. As a result, users may still access pod instances in the faulty cluster.

**What you expected to happen**:

Endpointslices on the karmada control plane can be cleared after a cluster failover.

**How to reproduce it (as minimally and precisely as possible)**:

Use karmada [MCS](https://karmada.io/docs/next/userguide/service/multi-cluster-service) feature, then disable one of the source member cluster.

**Anything else we need to know?**:

**Environment**:
- Karmada version: **master branch**
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
I've come up with two solutions so far,

Solution 1:
When reconcile `work` object in `endpointslice-controller`, we can check whether the cluster where the work resides is healthy to determine whether the `endpointslices` needs to be cleared.

Solution 2:
When cluster failover, we can add a tag(annotation or label) on the related namespace and `works`, when `endpointslice-controller` watch this change, then execute the clean process.

Personally, I prefer Solution 1. We only need to get the cluster once to solve the problem. Solution 2 needs to update all related namespaces and work.

/cc @RainbowMango

**Comment by LronDC** [comment]
Hi @XiShanYongYe-Chang , I'm interested in fixing this issue. I'm guessing that the priority of this task will NOT be too low. But in case its priority is lower, is it ok for me to take this after @RainbowMango and other members shared their opinion?

If this task needs a higher priority or others who are more familiar with Karmada(I'm still new to Karmada source code), then ignore my request.

**Comment by XiShanYongYe-Chang** [comment]
Hi @LronDC, thank you for your self-introduction.

> I'm guessing that the priority of this task will NOT be too low. 

I expect this issue to be resolved in v1.6 (by May 30th). When the solution is settled, we can fix it.

If you're willing to fix it, I'll be able to help you quickly complete this task. :)

**Comment by LronDC** [comment]
If it won't trouble you, I am willing to fix it. But I don't want to cause any delay with this 😂

**Comment by XiShanYongYe-Chang** [comment]
> If it won't trouble you, I am willing to fix it. But I don't want to cause any delay with this 😂

It will be ok, I think we can handle it.

**Comment by RainbowMango** [comment]
I'll try to reproduce it on my side and look into this issue.

**Comment by XiShanYongYe-Chang** [comment]
Whether to clear the EndpointSlice after the cluster is faulty needs to be further analyzed. It is inappropriate to directly handle the problem as a bug.
/close
