### ISSUE TITLE
Do we need to change the method from `UpdateStatus` to `Update`？

### ISSUE THREAD

**Issue by yike21** [karmada-io/karmada#3551]
**Please provide an in-depth description of the question you have**:
When I bundle third-party resources into the Resource Interpreter framework and write `ResourceInterpreterCustomization` for `argoproj.io/v1alpha1/Workflow`, I find that the `.status` of `workflow sample` which I propagate from karmada to member cluster can't be updated. 

The logs of `karmada-controller-manager` show that `Failed to update resource(argoproj.io/v1alpha1, Resource=workflows/test-workflow/sample), Error: workflows.argoproj.io "sample" not found`. [ref](https://github.com/karmada-io/karmada/pull/3438#issuecomment-1542447593)

This is because the `.status` of `workflow` is [not a subresource](https://github.com/karmada-io/karmada/pull/3438#issuecomment-1546931880). And [syncBindingStatus](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/rb_status_controller.go#L118) -> [updateResourceStatus](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/common.go#L77) can't update the `.status` of `workflow` by `dynamicClient.Resource(gvr).Namespace(resource.GetNamespace()).UpdateStatus(context.TODO(), newObj, metav1.UpdateOptions{})`.[ref](https://github.com/karmada-io/karmada/pull/3438#issuecomment-1546830439)

If we change method from `dynamicClient.Resource(gvr).Namespace(resource.GetNamespace()).UpdateStatus(context.TODO(), newObj, metav1.UpdateOptions{})` to `dynamicClient.Resource(gvr).Namespace(resource.GetNamespace()).Update(context.TODO(), newObj, metav1.UpdateOptions{})`, the `.status` of `workflow` can be updated successfully.

**What do you think about this question?**:
There may also be other resources whose `status` is not a subresource. 

To update the `status` successfully from `resourceBinding`, we need to change the CRD of resources which doesn't support `status subresource` in `karmada-control-plane` to make it support `status subresource`, or change the method of [updateResourceStatus](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/common.go#L77) to update the status.

**Environment**:
- Karmada version: master
- Kubernetes version: 
- Others:

**Comment by XiShanYongYe-Chang** [comment]
A good summary of the problems.

IMOP, for the resource interpreter, it deals with the status part of the resource, and the status is a subresource. If a CRD resource does not have a subresource, the interpreter cannot process it. Even though the resource has a field name status, it is not technically the other status. 

However, if strict requirements are met, some resource that do not have the status subresource cannot collect the status part, as analyzed in the example.

Therefore, I think we should ask users to define resources correctly, and push the upstream community to modify the resources mentioned in the issue description.
And then, we can consider modifying the resource update method in the karmada code.

**Comment by yike21** [comment]
Thanks for replying!

**Comment by XiShanYongYe-Chang** [comment]
Until we solve this problem, I feel that we can use this issue to track the problem, so keep it open will be ok.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
