### ISSUE TITLE
How to limit karmada  in least privilege in push mode ?

### ISSUE THREAD

**Issue by watermeion** [karmada-io/karmada#3555]
Q:  What's the design purpose of impersonator serviceaccount when a new cluster joins  karmada in Push mode?

**Comment by XiShanYongYe-Chang** [comment]
> Q: What's the design purpose of impersonator serviceaccount when a new cluster joins karmada in Push mode?

We introduce it for unified auth: https://karmada.io/docs/next/userguide/bestpractices/unified-auth/
