### ISSUE TITLE
deploy local karmada sh, base64 usage error in mac M1 chip

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/karmada#3560]
when we'r run "hack/local-up-karmada.sh" in mac M1 chip, base64 usage need use "-i" or use "<" to redirect input file.
<img width="570" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/8c9f1ae8-755e-4933-b4d8-10498a89d11b">

<img width="623" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/c1344fb7-0009-468f-9116-50cb321a9553">

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Thanks @Vacant2333 for spotting.
/assign @Vacant2333 
in favor of #3561
