### ISSUE TITLE
Can not install karmada with helm

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#3571]
**What happened**:

follow the doc and just got the error

```shell
lan@lan:~/repo/git/karmada$ helm install karmada -n karmada-system --create-namespace --dependency-update ./charts/karmada

Error: INSTALLATION FAILED: failed to install CRD crds/_crds/kustomization.yaml: unable to decode "": Object 'Kind' is missing in '{"patchesStrategicMerge":["patches/webhook_in_resourcebindings.yaml","patches/webhook_in_clusterresourcebindings.yaml"],"resources":["bases/multicluster.x-k8s.io_serviceexports.yaml","bases/multicluster.x-k8s.io_serviceimports.yaml","bases/policy.karmada.io_clusteroverridepolicies.yaml","bases/policy.karmada.io_clusterpropagationpolicies.yaml","bases/policy.karmada.io_federatedresourcequotas.yaml","bases/policy.karmada.io_overridepolicies.yaml","bases/policy.karmada.io_propagationpolicies.yaml","bases/work.karmada.io_resourcebindings.yaml","bases/work.karmada.io_clusterresourcebindings.yaml","bases/work.karmada.io_works.yaml","bases/config.karmada.io_resourceinterpretercustomizations.yaml","bases/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml","bases/networking.karmada.io_multiclusteringresses.yaml"]}'
```

**What you expected to happen**:

Install success with helm

**How to reproduce it (as minimally and precisely as possible)**:

1. git clone git@github.com:karmada-io/karmada.git
2. cd karmada
3. helm install karmada -n karmada-system --create-namespace --dependency-update ./charts/karmada

**Anything else we need to know?**:

I believe that this is a doc problem.

/kind doc

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
cc @Poor12

**Comment by chaosi-zju** [comment]
@calvin0327 hello, I have encountered the same error, do you known if there has some problem?

**Comment by chaosi-zju** [comment]
@liangyuanpeng @RainbowMango I got same bug today, but I find the problem lies in my source code is dirty. So I removed the old karmada repo and pull the latest karmada repo again, the bug gone. The document has no problem, one `helm install ...` command does work~

@liangyuanpeng you can try again with the latest code, if no more problem, this issue can be closed~

**Comment by RainbowMango** [comment]
kindly ping @liangyuanpeng
