### ISSUE TITLE
Cluster joined successfully but status ready is False

### ISSUE THREAD

**Issue by mrequena** [karmada-io/karmada#3573]
**Please provide an in-depth description of the question you have**:

I join a cluster with:
karmadactl join cluster-xxx --kubeconfig=$HOME/.kube/config --karmada-context=karmada-apiserver --cluster-kubeconfig=$HOME/members-configs/config-xxx
and the answer is:
cluster(cluster-xxx is joined successfully

Then I do:
kubectl get clusters
and the answer is:
NAME              VERSION    MODE   READY   AGE
cluster-xxx                  Push   False   14m
member-xxx     v1.19.10   Push   True    54d
member-xxx   v1.19.10   Push   True    55d

The version of the cluster-xxx k8s is v1.26.3 and v1.26.5
How can I debug what is happening? Are there any incompatibility with the versions of k8s?

**What do you think about this question?**:

**Environment**:
- Karmada version: 1.5.0
- Kubernetes version: v1.26.3 and v1.26.5
- Others:

**Comment by RainbowMango** [comment]
> How can I debug what is happening?

Please check out the `karmada-controller-manager` log, Perhaps `karmada-controller-manager` can't talk to the cluster for a reason.

> Are there any incompatibility with the versions of k8s?

I don't think so.  I belive Karmada is compatible with those versions.

**Comment by RainbowMango** [comment]
> What is the "cluster health check" error? What is the "Reconciler error"? What is missing in the cluster "cluster-xxx"?

`cluster health check` means `karmada-controller-manager` can't access the cluster at that time.
`Reconciler error` is a technical concept that is often used in controller patterns. 

> PS. I can reach the cluster "cluster-xxx" with kubectl, using the same kubeconfig file I use for the "karmadactl join".

I guess you were running the `kubectl` on a node that is connective with the target cluster(`cluster-xxx`). 

But, remember `karmada-controller-manager` might `running in a container`, the network situation is different from your node.

**Comment by mrequena** [comment]
> > PS. I can reach the cluster "cluster-xxx" with kubectl, using the same kubeconfig file I use for the "karmadactl join".
> 
> I guess you were running the `kubectl` on a node that is connective with the target cluster(`cluster-xxx`).
> 
> But, remember `karmada-controller-manager` might `running in a container`, the network situation is different from your node.

The k8s cluster that runs Karmada is a master node and a worker node. The cluster "cluster-xxx" is behind a VPN and the VPN is only established in the master node. I run the 'kubectl' from the master node. This means that I should establish the VPN also from the worker node also? How can I check the network situation from a container? Or how I tell a container to use a VPN interface?

**Comment by RainbowMango** [comment]
> This means that I should establish the VPN also from the worker node also? 

This approach works, but it's not ideal because you don't know which node `karmada-controller-manager` will be scheduled to.

Following solution that might works too:
1. Deploying the Karmada component(including `karmada-controller-manager`) to master node, you can do that by `PodAffinity`.
2. Export the service of `cluster-xxx` by another IP address that master node can access.

> How can I check the network situation from a container? Or how I tell a container to use a VPN interface?

Run kubectl in the container?  I'm not quite sure.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
