### ISSUE TITLE
Add CI for karmada operator helm chart

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#3579]
> CI what you say is chart lint?

Yeah, samething of karmada helm chart. ref:
- https://github.com/karmada-io/karmada/blob/master/.github/workflows/lint-chart.yaml

_Originally posted by @liangyuanpeng in https://github.com/karmada-io/karmada/pull/3524#discussion_r1197560745_

**Comment by calvin0327** [comment]
@liangyuanpeng Are you interested in it?
