### ISSUE TITLE
[Karmada operator] Code consult

### ISSUE THREAD

**Issue by yanggangtony** [karmada-io/karmada#3582]
**Please provide an in-depth description of the question you have**:
I rough read the operator code.
I found the 
operator/pkg/deinit.go 's remoteClient define.

```
type deInitData struct {
	name         string
	namespace    string
	remoteClient clientset.Interface
}
```
and operator/pkg/init.go  's remoteClient define.

```
type initData struct {
          ...
	remoteClient        clientset.Interface
	karmadaClient       clientset.Interface
       ...  
}
```

Its just initialized in condition 
```
if opt.Karmada.Spec.HostCluster.SecretRef == nil && len(opt.Karmada.Spec.HostCluster.APIEndpoint) == 0 {
```

But in the next logic about the task execute loop.
Its will immediate be called by tasks..
Like the init task 
```
func NewKarmadaApiserverTask() workflow.Task {
	return workflow.Task{
		Name:        "apiserver",
		Run:         runApiserver,
		RunSubTasks: true,
		Tasks: []workflow.Task{
			{
				Name: constants.KarmadaAPIserverComponent,
				Run:  runKarmadaAPIServer,
```

Also the deinit case is the same..

I want to know if is a known problem? Or If it is can be initialize like the 
```
func (data *initData) KarmadaClient() clientset.Interface {
	if data.karmadaClient == nil {
		data.Once.Do(func() {
			client, err := clientset.NewForConfig(data.controlplaneConifig)
			if err != nil {
				klog.Errorf("error when init karmada client, err: %w", err)
			}
			data.karmadaClient = client
		})
	}

	return data.karmadaClient
}
```

If its really a problem . 
I will assign and handle it..
Thanks.

**What do you think about this question?**:
Karmada operator

**Comment by yanggangtony** [comment]
@calvin0327 @lonelyCZ @Poor12 @RainbowMango

**Comment by calvin0327** [comment]
@yanggangtony Thanks for pointing this out.

Indeed, now we not support installing karmada on remote clusters. if user provides the cluster apiendpoint and tls message, we should init a remoteClient with these message.

If you're interested in it, you can assign this.

**Comment by yanggangtony** [comment]
@calvin0327 
Thanks for the quick response.
I will make a pr to the 
```
remoteClient's fuction.
```

/assign

**Comment by yanggangtony** [comment]
Sorry for the late response .
Recentely have lots of other works to to. 
Have no more time pay for the pr.
🥲🥲
