### ISSUE TITLE
Confusing schedule result condition

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3586]
**Please provide an in-depth description of the question you have**:
I'm confused why the _ResourceBinding_'s condition is `BindingScheduled` when all clusters are filterd by filter plugins.
```
status:
  conditions:
  - lastTransitionTime: "2023-05-25T09:41:11Z"
    message: Failed to apply all works, see status.aggregatedStatus for details
    reason: FullyAppliedFailed
    status: "False"
    type: FullyApplied
  - lastTransitionTime: "2023-05-25T09:50:37Z"
    message: Binding has been scheduled
    reason: BindingScheduled
    status: "True"
    type: Scheduled
  schedulerObservedGeneration: 2
```
karmada-scheduler log:
```
I0525 09:50:37.081526       1 scheduler.go:336] Start to schedule ResourceBinding(default/test-pod) as scheduling type is duplicated
I0525 09:50:37.081536       1 scheduler.go:426] "Begin scheduling resource binding with ClusterAffinity" resourceBinding="default/test-pod"
I0525 09:50:37.081572       1 generic_scheduler.go:150] Cluster "member5715" is not fit, reason: cluster(s) didn't match the placement cluster affinity constraint
I0525 09:50:37.081582       1 scheduler.go:444] ResourceBinding(default/test-pod) scheduled to clusters []
I0525 09:50:37.081694       1 scheduler.go:450] "End scheduling resource binding with ClusterAffinity" resourceBinding="default/test-pod"
I0525 09:50:37.081741       1 scheduler.go:739] Begin to patch status condition to ResourceBinding(default/test-pod)
I0525 09:50:37.081839       1 event.go:294] "Event occurred" object="default/test-pod" fieldPath="" kind="ResourceBinding" apiVersion="work.karmada.io/v1alpha2" type="Warning" reason="ScheduleBindingFailed" message="0/1 clusters are available: 1 cluster(s) didn't match the placement cluster affinity constraint."
I0525 09:50:37.081859       1 event.go:294] "Event occurred" object="default/test" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="ScheduleBindingFailed" message="0/1 clusters are available: 1 cluster(s) didn't match the placement cluster affinity constraint."
```
Could someone explain to me the reason for this code design? /cc @RainbowMango @XiShanYongYe-Chang @Poor12 @chaunceyjiang 
![image](https://github.com/karmada-io/karmada/assets/89241565/5e4634d6-1e34-4ae7-8df0-4f928e8fd2e8)

**What do you think about this question?**:
I think the condition should be `BindingFailedScheduling` when all clusters are filterd by filter plugins. [The code](https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/scheduler.go#LL452C19-L452C19) judgment here seems to be redundant.
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Good question. I'll think about it. added this to v1.7 milestone, so that we won't miss it.

**Comment by RainbowMango** [comment]
Sure, that's great, please remember to add an item to the agenda.

**Comment by RainbowMango** [comment]
I see you put the agenda to `Pending topics`, I just moved it to [Meeting 2023-06-05](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.hqmd0pfhxm0c), please let me know if you can't present this meeting so that we can postpone it.

**Comment by whitewindmills** [comment]
I'm free to attend the meeting.

**Comment by whitewindmills** [comment]
After community discussion, we need to introduce new scheduled condition reasons to explain the status in detail. I'll work on it.
/remove-kind question
/kind feature
