### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by learner0810** [karmada-io/karmada#3588]
I'm requesting to be a Member of Karmada community.
Recently，I started to to participate in the development of the community and submit some PRs

See:
pr: https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Alearner0810+is%3Aclosed+
issue: https://github.com/karmada-io/karmada/issues?q=is%3Aissue+learner0810+is%3Aclosed

Hope bring more improvements for Karmada in the future.

**Comment by XiShanYongYe-Chang** [comment]
Hi @learner0810, you can make a request in the community repo: https://github.com/karmada-io/community/issues

**Comment by learner0810** [comment]
> Hi @learner0810, you can make a request in the community repo: https://github.com/karmada-io/community/issues

Ok, thx
