### ISSUE TITLE
hack/local-up-karmada.sh pull  etccd image timeout

### ISSUE THREAD

**Issue by BUPT-wxq** [karmada-io/karmada#3592]
**What happened**:
I use local-up-karmada.sh to create mutil clusters. I get this error.
wait the etcd ready...
error: no matching resources found
kubectl --context=karmada-host wait --for=condition=Ready --timeout=30s pods -l app=etcd -n karmada-system failed, retrying(1 times)
**What you expected to happen**
what should i do to slove this problem
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
mac os m2
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by BUPT-wxq** [comment]
Failed to pull image "registry.k8s.io/etcd:3.5.3-0": rpc error: code = Unknown desc = failed to pull and unpack image "registry.k8s.io/etcd:3.5.3-0": failed to resolve reference "registry.k8s.io/etcd:3.5.3-0": failed to do request: Head "https://asia-east1-docker.pkg.dev/v2/k8s-artifacts-prod/images/etcd/manifests/3.5.3-0": net/http: TLS handshake timeou

**Comment by Vacant2333** [comment]
you may need provide more information about wait the etcd ready, in my mac M1 its ok .about the pull image problem, try more times or use a proxy for that

**Comment by yike21** [comment]
It's because your host can't pull image from registry.k8s.io. This [document](https://karmada.io/zh/docs/troubleshooting/trouble-shooting) is helpful. @BUPT-wxq 
```shell
sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/karmada-etcd.yaml
sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/karmada-apiserver.yaml
sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/kube-controller-manager.yaml
```

**Comment by BUPT-wxq** [comment]
> It's because your host can't pull image from registry.k8s.io. This [document](https://karmada.io/zh/docs/troubleshooting/trouble-shooting) is helpful. @BUPT-wxq
> 
> ```shell
> sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/karmada-etcd.yaml
> sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/karmada-apiserver.yaml
> sed -i'' -e "s#registry.k8s.io#registry.aliyuncs.com/google_containers#g" artifacts/deploy/kube-controller-manager.yaml
> ```

thanks,it works out.
