### ISSUE TITLE
How Member cluster accesses karmada-apiserver of host cluster

### ISSUE THREAD

**Issue by pingstar** [karmada-io/karmada#361]
**What would you like to be added**:

If my memebr cluster is deployed in another public cloud, how should member access the karmada-apiserver deployed in the host cluster?

**Why is this needed**:

 Ingress? Service Loadbalance or Nodeport?

**Comment by pingstar** [comment]
> I think you could access the karmada-apiserver directly using it's _hostIP_, because the karmada-apiserver is ruuning in _hostNetwork_ mode.

OK. Thanks for your reply. But I found that when I use karmada deploy script also deploys an apiserver in the current cluster using Deployment. so I was wondering if there are two apiserver, deployed way within the cluster for the karmada control-plane-component to access. The apiserver on the host is accessed by the agent of other clusrer.

**Comment by Garrybest** [comment]
> > I think you could access the karmada-apiserver directly using it's _hostIP_, because the karmada-apiserver is ruuning in _hostNetwork_ mode.
> 
> OK. Thanks for your reply. But I found that when I use karmada deploy script also deploys an apiserver in the current cluster using Deployment. so I was wondering if there are two apiserver, deployed way within the cluster for the karmada control-plane-component to access. The apiserver on the host is accessed by the agent of other clusrer.

Well, the karmada-apiserver is deployed in host cluster using k8s deployment and it's network mode is host. The next step is running a karmada-agent in your member cluster and specifying a karmada-apiserver-kubeconfig as it's bootstrap config. The agent running in the member cluster will start to connect with karmada-apiserver, using karmada-apiserver-kubeconfig's host IP and port. By the way, you can also use ingress for the karmada-apiserver-kubeconfig, but I think the deployment script of karmada-apiserver may be modified.

**Comment by pingstar** [comment]
I understand, thank you for your reply
