### ISSUE TITLE
karmadactl init timedout

### ISSUE THREAD

**Issue by hzxuzhonghu** [karmada-io/karmada#3611]
`karmadactl init ` has failed many times during [kurator](https://github.com/kurator-dev/kurator) test.

The logs shows like below error, i believe it is because of timeout deploying components.

```
error: wait for Deployment(default/karmada-apiserver) rollout: timedout wairting for......
```

After digging into it, karmada `WaitComponentReadyTimeout` is 30s when running init, this is a constant. 

Would suggest make it configurable, otherwise it is very fragile for bad network env

**Comment by XiShanYongYe-Chang** [comment]
/kind help
Anyone interested in this issue can assign this task.

**Comment by LronDC** [comment]
> Hi, @hzxuzhonghu  Does this pr https://github.com/karmada-io/karmada/pull/3453 is your need? 
> 

I think it is. But it seems stasis.
/unassign

**Comment by XiShanYongYe-Chang** [comment]
Thanks~ @LronDC @chaunceyjiang I did not notice the target pr.

**Comment by hzxuzhonghu** [comment]
Yes, thank you all. Hope it can be merged soon
