### ISSUE TITLE
kubectl-karmada init failing with error

### ISSUE THREAD

**Issue by naqvis** [karmada-io/karmada#3619]
**What happened**:

`kubectl-karmada` when invoking `init` is failing with error **error: failed to create directory: /etc/karmada, error: mkdir /etc/karmada: permission denied**

**What you expected to happen**:
`init` command should successfully install Karmada control plane

**How to reproduce it (as minimally and precisely as possible)**:

1. Install single node k3s cluster
2. Install `kubectl-karmada`
3. Run `kubectl karmada init`

**Anything else we need to know?**:

**Environment**:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):

```sh
kubectl karmada version: version.Info{GitVersion:"v1.6.0", GitCommit:"6eb79b38949e480cf7a2e12cfa56fef47bda81ea", GitTreeState:"clean", BuildDate:"2023-05-31T09:55:31Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by whitewindmills** [comment]
I'm curious if you are logged in as root.

**Comment by RainbowMango** [comment]
> kubectl-karmada when invoking init is failing with error error: failed to create directory: /etc/karmada, error: mkdir /etc/karmada: permission denied

The output shows that you don't have permission to create a directory at `/etc/karmada`.
You might need to talk to your administrator to grant permission to you.

Another approach might be change the default path:
The `init` command default to put the cert and crds file under `/etc/karmada` directory:
```
    -d, --karmada-data='/etc/karmada':
	Karmada data path. kubeconfig cert and crds files
    --karmada-pki='/etc/karmada/pki':
	Karmada pki path. Karmada cert files
```
You can customize a directory that you have permission to access. like :
```
karmadactl init --karmada-data=~/karmada --karmada-pki=~/karmada   <other flags>
```

**Comment by RainbowMango** [comment]
It doesn't seem like a bug.
/remove-kind bug
/kind question

Please let us know if you have further questions.

**Comment by RainbowMango** [comment]
Thanks for your suggestion. I'll invite init author here to comment. @lonelyCZ 

I'm quite sure about does `init` really requires `root` permission?

**Comment by lonelyCZ** [comment]
> I'm quite sure about does init really requires root permission?

I think it should not need the root permission. It only need the permission of kubeconfig, as for `/etc/karmada` directory is only a common dir like `/etc/kubernetes`, so it can be configured.

> There is no clear indication in documentation or somewhere else that init requires root privileges and for non root users what options are available.

It makes sense, perhaps we can note this in the document. We deafult use `/etc/karmada` that seems more friendly for new Karmada user, especially unify the description of documents, how do you think?

**Comment by RainbowMango** [comment]
> We deafult use /etc/karmada that seems more friendly for new Karmada user, especially unify the description of documents, how do you think?

+1

> but suggestion is to store operation artifacts under user home folder (as that' the common place, where linux user has full privileges)

The `kubectl` configuration is normally used by a specific user, so it makes sense to store the configurations to home folder.

But Karmada configurations(or, Kubernetes configurations), might be used by more than one user. So, I don't think such kind of configuration shouldn't put in a user-specific directory. 
Take `kubeadm` as an example, an administrator(probably root) might install Kubernetes, which might be used by more than one user, so the configuration definitely can't be at `/root/xxx`.

**Comment by RainbowMango** [comment]
The difference between `karmadactl init` and `helm install` is that:
- `karmadactl init` needs a path to store public configurations for multiple users.
- `helm install` doesn't need to store public configurations, it essentially deploys workloads(karmada components) to a specific cluster.

I don't know why we need to document the difference. In addition, we just introduced another installation approach, Karmada Operator, do you mean we also need to note the differences? 

> Update the documentation accordingly stating that init command with default settings (requires escalated privileges & why)

Sounds good to me. Would you like to send a PR for this?

**Comment by RainbowMango** [comment]
/assign 
In favor of https://github.com/karmada-io/website/pull/364.
Thanks.
/remove-kind question
/kind cleanup
/kind documentation

**Comment by RainbowMango** [comment]
Sorry, just mistakenly assigned it to me.
/unassign
/assign @naqvis

**Comment by RainbowMango** [comment]
I guess we can close it now.
/close
