### ISSUE TITLE
feat: provide the script to deploy karmada-metrics-adapter

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3625]
**What would you like to be added**:
* Provide a script to deploy `karmada-metrics-adapter`, similar to the one for `karmada-estimator`. You can find an example here: https://github.com/karmada-io/karmada/blob/master/hack/deploy-scheduler-estimator.sh
* Make sure to install `karmada-metrics-adapter` when running `hack/local-up-karmada.sh`.

**Why is this needed**:
Facilitate the deployment of `karmada-metrics-adapter` for users to utilize FederatedHPA and scale workloads across multiple clusters.

**Comment by jwcesign** [comment]
Hi @sbdtu5498 , how about the process of this issue?

**Comment by sbdtu5498** [comment]
Oh, it's done. I forgot to push the PR. Sorry for the delays.

**Comment by jwcesign** [comment]
Hi @sbdtu5498 , thanks for your contribution.

So when you are available, please submit a PR.
