### ISSUE TITLE
feat: deploy karmada-metreics-adapter with helm/karmadactl/karmada-operator

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3626]
**What would you like to be added**:
- [ ] Implement deployment of `karmada-metrics-adapter` using Helm. @sbdtu5498
- [x] Implement deployment of `karmada-metrics-adapter` using karmadactl. @chaunceyjiang 
- [x] Implement deployment of `karmada-metrics-adapter` using karmada-operator. @calvin0327

**Why is this needed**:
Provider different ways to install `karmada-metrics-adapter`, to utilize FederatedHPA and scale workloads across multiple clusters.  

If you are interested in one of the installation methods, you can choose to complete certain tasks.

**Comment by chaunceyjiang** [comment]
> Implement deployment of karmada-metrics-adapter using karmadactl. 

please assign to @chaunceyjiang .

**Comment by jwcesign** [comment]
> please assign to @chaunceyjiang .

Updated in issue content.

**Comment by jwcesign** [comment]
Hi, @sbdtu5498 , which part you will do?

**Comment by sbdtu5498** [comment]
Currently, working on the helm part. But can work on all three.

**Comment by jwcesign** [comment]
Hi， @sbdtu5498 Thanks for your contribution.

@chaunceyjiang will handle the `karmadactl` portion, so I'll assign the other two parts to you.

**Comment by sbdtu5498** [comment]
Thanks @jwcesign!

**Comment by calvin0327** [comment]
/assign

@jwcesign  @sbdtu5498 Can I handle the karmada operator part?

**Comment by jwcesign** [comment]
I am okay with this. Hi @sbdtu5498, can we delegate this part to @calvin0327?

**Comment by sbdtu5498** [comment]
Sure @calvin0327 you can work on the operator part.

**Comment by jwcesign** [comment]
/cc @sbdtu5498 

any updates about Helm?

**Comment by JadeFlute0127** [comment]
I am willing to complete the helm part, please assign this part to me

**Comment by jwcesign** [comment]
Hi, @sbdtu5498 , do you start with the helm part? if not, can we delegate this part to @JadeFlute0127 ?

**Comment by sbdtu5498** [comment]
@JadeFlute0127 I partially did it some time ago and had it on my local system. I was preoccupied with some other tasks. I will make a PR soon. If possible can you please look for another issue? Thanks!

**Comment by sbdtu5498** [comment]
https://github.com/karmada-io/karmada/issues/3672 @JadeFlute0127, I didn't get time to work on this one. If you think you can deal with this one, please take a look.

**Comment by JadeFlute0127** [comment]
> @JadeFlute0127 I partially did it some time ago and had it on my local system. I was preoccupied with some other tasks. I will make a PR soon. If possible can you please look for another issue? Thanks!

that's great，thanks for your contribution. i am working for an other issue.

**Comment by jwcesign** [comment]
/cc @sbdtu5498 

Hi, did you encounter any issues while implementing `the deployment of karmada-metrics-adapter using Helm`? We can solve it together

**Comment by jwcesign** [comment]
Hi @sbdtu5498 

Considering that we are planning to release a new version in the near future, I would like to develop this feature firstly and include it in the release.

/assign

**Comment by sbdtu5498** [comment]
@jwcesign extremely sorry for the delays. I missed the previous email notification and this issue got out of my mind. I had done some preliminary work on the issue and used karmada-search as a reference to do so. If you can provide some review, I will fix it ASAP so that it can be shipped with the next release. Again very sorry for the delays.

**Comment by jwcesign** [comment]
Thanks, @sbdtu5498 , I will take a look soon.
