### ISSUE TITLE
local-up-karmada.sh cannot using other version but "latest "

### ISSUE THREAD

**Issue by zishen** [karmada-io/karmada#3628]
**What happened**:
When I want to setup Karmada by using local-up-karmada.sh, I found it is not work if I change
export VERSION="latest" to export VERSION="v1.5.1".
The kind container also has latest tag images. And karmada is stiil using latest tag image.

**What you expected to happen**:
The kind container using the special tag images which I assign in local-up-karmada.sh. And karmada is using the same one.

**How to reproduce it (as minimally and precisely as possible)**:
Just assign another VERSION in local-up-karmada.sh

**Anything else we need to know?**:
none

**Environment**:
- Karmada version:v1.5.1,v1.6.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by yike21** [comment]
Hi! Using [local-up-karmada.sh](https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh#L6) will build images based on current [code](https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh#L110-L113) with `export VERSION="latest"`, so tag is always "latest".  

I'm not sure how to assign another VERSION in `local-up-karmada.sh`. To get the specified version of the component, maybe you can first clone the target version source code, then use [make image-{component-name}](https://github.com/karmada-io/karmada/blob/master/Makefile#L45-L63).

**Comment by jwcesign** [comment]
If you want to build a specific version, you can clone the repo and checkout to the particular tag, then run `local-up-karmada.sh`

**Comment by zishen** [comment]
> If you want to build a specific version, you can clone the repo and checkout to the particular tag, then run `local-up-karmada.sh`



> Hi! Using [local-up-karmada.sh](https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh#L6) will build images based on current [code](https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh#L110-L113) with `export VERSION="latest"`, so tag is always "latest".
> 
> I'm not sure how to assign another VERSION in `local-up-karmada.sh`. To get the specified version of the component, maybe you can first clone the target version source code, then use [make image-{component-name}](https://github.com/karmada-io/karmada/blob/master/Makefile#L45-L63).

I have tried to assign VERSION in `local-up-karmada.sh`, but only the code change and the image's version out of kind changed.  The images's version in kind not.

I think the point is  [yaml](https://github.com/karmada-io/karmada/blob/v1.6.0/artifacts/deploy/karmada-controller-manager.yaml#L23-L25) using the latest tag.

**Comment by mrequena** [comment]
The same happens when I use remote-up-karmada.sh, i.e. the latest version is used for all the karmada components. Both scripts (local-up-karmada.sh and remote-up-karmada.sh) use the script deploy-karmada.sh and this script uses the yaml files in artifacts/deploy that contains the "latest" tag for all the images.

Could it be a solution to introduce a variable {{karmada_version}} in the yaml files in artifacts/deploy and then add the sed lines to put the karmada version for all the karmada components with something like?

sed -i'' -e "s/{{karmada_version}}/${KARMADA_VERSION}/g" "${TEMP_PATH_APISERVER}"/karmada-apiserver.yaml

Or is there another reason why in these yaml files always the "latest" version is used?

Is there other way to install a specific version of Karmada? Thanks

**Comment by RainbowMango** [comment]
> Or is there another reason why in these yaml files always the "latest" version is used?

These yamls as well as `local-up-karmada.sh` are used for the development and the CI, that usually runs against lastest code.

> Is there other way to install a specific version of Karmada?

The `local-up-karmada.sh` is also often used by people to evaluate the project, I think it makes sense to launch Karmada system with a specific version.

> Could it be a solution to introduce a variable {{karmada_version}} in the yaml files in artifacts/deploy and then add the sed lines to put the karmada version for all the karmada components with something like?

I'm not sure, but it might be challenging as it might be involved too much.

**Comment by mrequena** [comment]
> 
> These yamls as well as `local-up-karmada.sh` are used for the development and the CI, that usually runs against lastest code.
> 

I totally understand but then what is the recommended way to install a specific version?

> 
> I'm not sure, but it might be challenging as it might be involved too much.

What kind of challenges do you foresee? I would like to patch the yaml files and the scripts, so your advice is highly appreciated.

**Comment by zishen** [comment]
> > These yamls as well as `local-up-karmada.sh` are used for the development and the CI, that usually runs against lastest code.
> 
> I totally understand but then what is the recommended way to install a specific version?
> 
> > I'm not sure, but it might be challenging as it might be involved too much.
> 
> What kind of challenges do you foresee? I would like to patch the yaml files and the scripts, so your advice is highly appreciated.

My opinion is copy the yaml files to a temporary directory like `/tmp`. And delete them when deloy karmada ok.

**Comment by XiShanYongYe-Chang** [comment]
As a lack of activity, let's close this first, feel free to reopen it if you still need it.
/close
