### ISSUE TITLE
feat: version selection for karmadactl

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3633]
**What would you like to be added**:

**Why is this needed**:
Currently, we are importing the alpha release but encountering issues with version parsing. Specifically, when attempting to parse the git version `v1.7.0-alpha.1-2-gcd9ca28f`, it is incorrectly identifying the version as v1.7.0 which has not yet been released.

So how karmada should select the version? based on the logic of kubeadm, we can do the same as K8s.
![img](https://user-images.githubusercontent.com/19745536/243335781-d33a0968-7995-459e-96b4-f1ec78b37247.png)

To fetch the version from github, we can use following code:
```go
package main

import (
	"context"
	"fmt"
	"github.com/google/go-github/github"
)

func getLatestTag(owner, repo string) (string, error) {
	ctx := context.Background()
	client := github.NewClient(nil)

	release, _, err := client.Repositories.GetLatestRelease(ctx, owner, repo)
	if err != nil {
		return "", err
	}
	return *release.TagName, nil
}

func main() {
	fmt.Println(getLatestTag("karmada-io", "karmada"))
}
```

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang @RainbowMango @lonelyCZ for checking

**Comment by RainbowMango** [comment]
What's the definition of `latest release` ?

**Comment by jwcesign** [comment]
the latest release is the latest stable release(not contain pre-release), like https://github.com/karmada-io/karmada/releases/latest

**Comment by RainbowMango** [comment]
I'm asking because each time i draft a new release, GitHub always let me to check if it is a `latest release`. 
Thanks, i get it. Will look into it tomorrow.
