### ISSUE TITLE
Create Deployment Error

### ISSUE THREAD

**Issue by jrkeen** [karmada-io/karmada#366]
**What happened**:
when I had created a deploymnt (use example) for member cluster. Agent told me " Failed to create resource in the given member cluster xxxx, err is resourceVersion should not be set on objects to be created". why? and should I do?
![image](https://user-images.githubusercontent.com/39866845/118917793-34e19800-b964-11eb-9744-3b3016832a97.png)

**Comment by RainbowMango** [comment]
Have you deployed `karmada-webhook`, which is a mandatory component, takes responsibility to remove `resourceVersion` before propagating to member clusters?

**Comment by jrkeen** [comment]
Thanks for your reply. I realized it was my problem that deploy webhook.
