### ISSUE TITLE
Confusing different about kubectl and karmadactl

### ISSUE THREAD

**Issue by haiker2011** [karmada-io/karmada#3663]
**Please provide an in-depth description of the question you have**:
run volcano job in karmada, when use `kubectl get vcjob` , I can not get vcjob STATUA, MINAVAILABLE and RUNNING. but when use kamadactl get vcjob, can get all the information.

```bash
root@KARMADADEV:./karmada/samples/vcjob# kubectl get vcjob
NAME       STATUS   MINAVAILABLE   RUNNINGS   AGE
test-job                                      62s
root@KARMADADEV:./karmada/samples/vcjob# karmadactl get vcjob
NAME       CLUSTER   STATUS    MINAVAILABLE   RUNNINGS   AGE   ADOPTION
test-job   member1   Running   1              1          71s   Y
```

**What do you think about this question?**:
I don't know the different about `kubectl` and `kamadactl`, and if want to use `kubectl` get all info, what should do? I found when use `kubectl get deploy`, I can get all info.
**Environment**:
- Karmada version: master
- Kubernetes version: v1.26.0
- Others:

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/blob/master/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml

This is a very good example. @haiker2011

**Comment by haiker2011** [comment]
@chaunceyjiang Thanks, I'm trying write a sample vcjob interpreter follow the example

**Comment by RainbowMango** [comment]
OK. I guess the question has been answered, please feel free to reopen it if you have further questions.
/close
