### ISSUE TITLE
How to rename a  member cluster when it is online？

### ISSUE THREAD

**Issue by watermeion** [karmada-io/karmada#3666]
How to rename a member cluster when it is online？

**Comment by jwcesign** [comment]
Hi @watermeion ,

The cluster name is in `ObjectMeta`, and there is the following limitation:
`Object names are immutable in Kubernetes. If you want to change a name, you can recreate it with a different name`

So, if you really want to rename it:
1. Taint it and evict the workloads(Make sure you have other clusters to take these workloads).
2. Delete and rejoin it with the name you want.
3. Move the workloads to the newly joined cluster.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @watermeion @jwcesign 
I think @jwcesign has answered the question.
/close
