### ISSUE TITLE
global proxy: kubectl access apiserver error due to setting kubeconfig server address

### ISSUE THREAD

**Issue by xigang** [karmada-io/karmada#3695]
**Please provide an in-depth description of the question you have**:

After the server address of `kubeconfig` is set to `/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy`, an error occurs when using `kubectl` to access proxy cache resources.

admin-proxy.conf kubeconfig:

```
# cat /etc/kubernetes/admin-proxy.conf
apiVersion: v1
clusters:
- cluster:
    server: https://https://master-ip:6443/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy
  name: kubernetes
xxxxxx
```

debug log:
```
# kubectl --kubeconfig /etc/kubernetes/admin-proxy.conf get pods --v 8
I0622 17:31:37.798518  863304 round_trippers.go:420] GET https://master-ip:6443/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api?timeout=32s
```

```
# kubectl --kubeconfig /etc/kubernetes/admin-proxy.conf get pods --v 8
I0622 17:31:37.797798  863304 loader.go:375] Config loaded from file:  /etc/kubernetes/admin-proxy.conf
I0622 17:31:37.798518  863304 round_trippers.go:420] GET https://master-ip:6443/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api?timeout=32s
I0622 17:31:37.798544  863304 round_trippers.go:427] Request Headers:
I0622 17:31:37.798559  863304 round_trippers.go:431]     Accept: application/json, */*
I0622 17:31:37.798607  863304 round_trippers.go:431]     User-Agent: kubectl/v1.17.4 (linux/amd64) kubernetes/f769ba9
I0622 17:31:37.806401  863304 round_trippers.go:446] Response Status: 500 Internal Server Error in 7 milliseconds
I0622 17:31:37.806418  863304 round_trippers.go:449] Response Headers:
I0622 17:31:37.806424  863304 round_trippers.go:452]     Audit-Id: 1e87d97c-6515-480b-94b2-97ffb39d9708
I0622 17:31:37.806429  863304 round_trippers.go:452]     Cache-Control: no-cache, private
I0622 17:31:37.806437  863304 round_trippers.go:452]     Cache-Control: no-cache, private
I0622 17:31:37.806441  863304 round_trippers.go:452]     Content-Type: application/json
I0622 17:31:37.806445  863304 round_trippers.go:452]     Date: Thu, 22 Jun 2023 09:31:37 GMT
I0622 17:31:37.806449  863304 round_trippers.go:452]     Content-Length: 127
I0622 17:31:37.807039  863304 request.go:1017] Response Body: {"kind":"Status","apiVersion":"get","metadata":{},"status":"Failure","message":"no plugin found for request: get ","code":500}
I0622 17:31:37.807750  863304 cached_discovery.go:121] skipped caching discovery info due to no plugin found for request: get
```

--------

When the server address is not set in kubeconfig, pods resource data can be queried in `kubectl get --raw url`

admin.conf kubeconfig: 
```
# cat /etc/kubernetes/admin-proxy.conf
apiVersion: v1
clusters:
- cluster:
    server: https://https://master-ip:6443
  name: kubernetes
xxxxxx
```

debug log:
```
# kubectl --kubeconfig /etc/kubernetes/admin.conf get --raw /apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api/v1/namespaces/kube-system/pods/node-problem-detector-n5qjm | jq .
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "creationTimestamp": "2023-04-12T11:52:52Z",
    "generateName": "node-problem-detector-",
    "labels": {
      "app": "node-problem-detector",
      "controller-revision-hash": "65869d48b8",
      "pod-template-generation": "1"
    },
    "name": "node-problem-detector-n5qjm",
    "namespace": "kube-system",
    "ownerReferences": [
      {
        "apiVersion": "apps/v1",
        "blockOwnerDeletion": true,
        "controller": true,
        "kind": "DaemonSet",
        "name": "node-problem-detector",
        "uid": "1862bb6f-5674-4c52-9e47-12aef228a4d1"
      }
    ],
    xxx
}
```

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
It seems that the url address is not handled correctly, we can get the error message:

```log
skipped caching discovery info due to no plugin found for request: get
```

**Comment by xigang** [comment]
> Hi @xigang ,have you modify the source? I am wondering why `karmada` plugin catch it
> 
> https://github.com/karmada-io/karmada/blob/89295f9606dc6a4d08d983f232936320adca327e/pkg/search/proxy/framework/plugins/karmada/karmada.go#L57-L62

@ikaven1024  Yes, I modified the source code, the current only cache plugin, but I execute `kubectl --kubeconfig /etc/kubernetes/admin-proxy.conf get pods --v 8` can not be cache capture.

**Comment by xigang** [comment]
> # kubectl --kubeconfig /etc/kubernetes/admin-proxy.conf get pods

Yes, when I execute the `kubectl get pods` command, the debug log output is:
```
GET https://master-ip:6443/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api?timeout=32s
```
The normal request path would be
```
https://master-ip:6443/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api/v1/namespaces/default/pods
```

**Comment by xigang** [comment]
> It is mechanism of kubectl. Before query objects, it will discovery pod api with:
> 
> ```json
> ➜  kubectl get --raw '/api' | jq
> {
>   "kind": "APIVersions",
>   "versions": [
>     "v1"
>   ],
>   "serverAddressByClientCIDRs": [
>     {
>       "clientCIDR": "0.0.0.0/0",
>       "serverAddress": "192.168.10.29:32764"
>     }
>   ]
> }
> ```
> 
> ```json
> ➜  .karmada kubectl get --raw '/api/v1' | jq
> {
>   "kind": "APIResourceList",
>   "groupVersion": "v1",
>   "resources": [
>     ...
>     {
>       "name": "pods",
>       "singularName": "",
>       "namespaced": true,
>       "kind": "Pod",
>       "verbs": [
>         "create",
>         "delete",
>         "deletecollection",
>         "get",
>         "list",
>         "patch",
>         "update",
>         "watch"
>       ],
>       "shortNames": [
>         "po"
>       ],
>       "categories": [
>         "all"
>       ],
>       "storageVersionHash": "xPOwRZ+Yhw8="
>     }
>     ...
>   ]
> }
> ```
> 
> At last, query pods with:
> 
> ```
> /api/v1/namespaces/default/pods
> ```
> 
> Above non-resource apis are supported by `karmada plugin`. So you cann't remove it if you want use kubectl.

@ikaven1024 @XiShanYongYe-Chang Thank you very much, Thanks a lot, the karmada plugin is required for kubectl to work.
