### ISSUE TITLE
Move karmada api into a separate repo

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#371]
**What would you like to be added**:

**Why is this needed**:

Like https://github.com/kubernetes/api, we should put karmada api into a separate repo,so that if someone wants to use API definition, he needn't install lots of go dependencies used by controller-manager.

**Comment by RainbowMango** [comment]
That totally reasonable.
And the repo `https://github.com/karmada-io/api` has been created.

I'm not sure if the `api` repo should keep `clients`? 
If not, we need another repo like `client-go`.
@kevin-wangzefeng What's your preference?
