### ISSUE TITLE
Refactor karmada-bootstrap.sh after #367 get merged

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#372]
**What would you like to be added**:
Refactor [hack/karmada-bootstrap.sh](https://github.com/karmada-io/karmada/blob/196c394d88962fbbe5d4fc6d8ad682b329e78591/hack/karmada-bootstrap.sh) after #367 get merged.

**Why is this needed**:
`hack/karmada-bootstrap.sh` is used to prepare E2E testing environment, similar with `hack/local-up-karmada.sh` but need some member clusters.

**Comment by lfbear** [comment]
You may also assign to me

**Comment by mrlihanbo** [comment]
@lfbear 
I found that the kubeconfig of karmada-apiserver gernerated by util::append_client_kubeconfig can't be used by karmada-agent.       
The reasons are  as follows：
1. karmada-agent is not support to assign the context.    
2. The default kubeconfig used in deploy-karmada-agent.sh is "/var/run/karmada/karmada-apiserver.config"

I will add a flag in karmada-agent to support assigning name of the cluster context in given KUBECONFIG file. I will submit the pr soon.   
The second one should be refactored with karmada-bootstrap.sh.  Would you like to fix it when you refactor karmada-bootstrap.sh?

**Comment by lfbear** [comment]
> @lfbear
> I found that the kubeconfig of karmada-apiserver gernerated by util::append_client_kubeconfig can't be used by karmada-agent.
> The reasons are as follows：
> 
> 1. karmada-agent is not support to assign the context.
> 2. The default kubeconfig used in deploy-karmada-agent.sh is "/var/run/karmada/karmada-apiserver.config"
> 
> I will add a flag in karmada-agent to support assigning name of the cluster context in given KUBECONFIG file. I will submit the pr soon.
> The second one should be refactored with karmada-bootstrap.sh. Would you like to fix it when you refactor karmada-bootstrap.sh?

I found it too, I have refactored deploy-karmada-agent.sh before  refactoring karmada-bootstrap.sh [like this](https://github.com/lfbear/karmada/blob/refactor-karmada-bootstrap/hack/deploy-karmada-agent.sh), it supported deploy karmada-agent for standalone cluster too, if the needs are met?

**Comment by lfbear** [comment]
> 2\. The default kubeconfig used in deploy-karmada-agent.sh is "/var/run/karmada/karmada-apiserver.config"
I moved the kubeconfig of 'karmada-apiserver' to $HOME/.kube/ and merged host-cluster kubeconfig to a whole one named 'karmada.config' placed in $HOME/.kube/ because:
1. the files in '/var/run/' will be removed after reboot, then the kubeconfig will be lost
2. the kubeconfig of multi-clusters merged a whole file will be easy to use, so I'll synchronize this change to `deploy-karmada-agent.sh` and `karmada-bootstrap.sh` after #367 merged.
Welcome to hear your opinion.

**Comment by mrlihanbo** [comment]
> > 2. The default kubeconfig used in deploy-karmada-agent.sh is "/var/run/karmada/karmada-apiserver.config"
> 
> I moved the kubeconfig of 'karmada-apiserver' to $HOME/.kube/ and merged host-cluster kubeconfig to a whole one named 'karmada.config' placed in $HOME/.kube/ because:
> 
> 1. the files in '/var/run/' will be removed after reboot, then the kubeconfig will be lost
> 2. the kubeconfig of multi-clusters merged a whole file will be easy to use, so I'll synchronize this changes to `deploy-karmada-agent.sh` and `karmada-bootstrap.sh` after #367 merged.
> 
> Welcome to hear your opinion.

hello, lfbear. I have submited the pr to introduce --karmada-context flag to karmada-agent to select context in kubeconfig file. The  --karmada-context flag can work with the "MEMBER_CLUSTER_CONTEXT_NAME" param you introduce in deploy-karmada-agent.sh.      
The code is here #415 .
