### ISSUE TITLE
The Scheduler not prepare for handling resourcebinding generated by clusterpropagationpolicy

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#373]
**What happened**:
`Scheduler` do not schedule `resourcebinding` generated by `clusterpropagationpolicy`, since it expected `PropagationPolicyNameLabel` and `PropagationPolicyNamespaceLabel` do not existed(since by `clusterpropagationpolicy` not `propagationpolicy`)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
Thanks and it's my bad that haven't catch it before~
