### ISSUE TITLE
Add E2E for #3670: when cluster update, karmada need to reconcile search cache

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#3731]
**Task description**:

#3670 make a patch when cluster update, Karmada will reconcile search cache. And then, we can add an E2E case to cover this update. 

We can add the case here:

https://github.com/karmada-io/karmada/blob/c39856bfe9a40bdc20a44cedb22c8fa5c4a5ceec/test/e2e/search_test.go#L343

**Who can join or take the task**:

Anyone who is interested can come and claim this job.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by XiShanYongYe-Chang** [comment]
@zhy76 Thanks~

**Comment by XiShanYongYe-Chang** [comment]
Hi @zhy76, did you encounter any problems during the writing process?

**Comment by zhy76** [comment]
> Hi @zhy76, did you encounter any problems during the writing process?

Sorry for the late reply, I've been a little busy these days, I've already written a PR and I'm still verifying it.
