### ISSUE TITLE
Avoid calculating available replicas for non-workload

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3743]
**What would you like to be added**:
We should avoid calculating available replicas for non-workload, like `ServiceAccount`, `ConfigMap` and `Secret` and etc.

**Why is this needed**:
For now, all resource are be selected to calculate its available replicas in every member cluster, that's unnecessary expensive cost.
https://github.com/karmada-io/karmada/blob/1d030d4f8c01f8370c80bb0ecdd52630d87a5bf0/pkg/scheduler/core/util.go#L37-L76

**Comment by Garrybest** [comment]
Hi @whitewindmills, since non-workload does not have replicas, the field `spec.replicas` of resource binding is zero. According to https://github.com/karmada-io/karmada/blob/b01cf50caee8c895c808c2ba7d7dbb75eff2a5b8/pkg/scheduler/core/generic_scheduler.go#L185, we don't cope with it.

**Comment by whitewindmills** [comment]
> Hi @whitewindmills, since non-workload does not have replicas, the field `spec.replicas` of resource binding is zero. According to
> 
> https://github.com/karmada-io/karmada/blob/b01cf50caee8c895c808c2ba7d7dbb75eff2a5b8/pkg/scheduler/core/generic_scheduler.go#L185
> 
> , we don't cope with it.

Calculating replicas is always invoked by function `selectClusters`.

**Comment by Garrybest** [comment]
You are right. We still caculate replicas when select clusters. I think it is necessary to add a condition check here.

**Comment by whitewindmills** [comment]
> I think it is necessary to add a condition check here.

Yes, I'll work on it.
/assign

**Comment by XiShanYongYe-Chang** [comment]
Reasonable improvement points. 👍
