### ISSUE TITLE
feat: Support CronFederatedHPA to scale workload at a specific time

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#3746]
**What would you like to be added**:
Support CronFederatedHPA to scale workload across clusters at a specific time.

**Why is this needed**:
For some certain predictable load change scenarios, for example, the Black Friday sale and Singles' Day sale, there will be sharp load peaks. With standard K8s HPA, it needs time to scale up the replicas, which may not be fast enough to handle sharp load peaks, resulting in service unavailability.

To solve this problem, there are already some approaches in a single cluster, called `CronHPA`, which can scale up/down the workloads at a specific time. Cluster administrators can scale up the workloads in advance with `CronHPA`, to meet the requirements of the sharp load peaks. So this proposal proposes `CronFederatedHPA` to meet the same requirements in the multi-cluster scenario.

There are following tasks:
- [x] Give a proposal about the design details of CronFederatedHPA. (https://github.com/karmada-io/karmada/pull/3664)
- [x] Defined the API of CronFederatedHPA. (https://github.com/karmada-io/karmada/pull/3692)
- [x] Implement CronFederatedHPA controller to scale the workloads. (https://github.com/karmada-io/karmada/pull/3729)
- [x] Add e2e cases to ensure the feature is always ready. (@jwcesign )
- [x] Support init validation configuration of CronFederatedHPA via karmadactl (@chaunceyjiang).
- [x] Add tutorials for CronFederatedHPA. (@jwcesign)

**Comment by chaunceyjiang** [comment]
> Support init validation configuration of CronFederatedHPA via karmadactl.

Please assign this task to me.

**Comment by jwcesign** [comment]
> Please assign this task to me.

Done

**Comment by RainbowMango** [comment]
/close
as all tasks have been resolved.
