### ISSUE TITLE
Sync the API of the karmada operator to the `karmada-io/api` repository

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#3755]
**What would you like to be added**:
We need sync the API of the karmada operator to the `karmada-io/api` repository.

**Why is this needed**:
Recently, we want to integrate karmada operator to our product and complete dependence on the karmada operator API. but we can not import whole karmada as a module.
So, can we sync API of karmada operator to api repository? @RainbowMango

**Comment by RainbowMango** [comment]
Sure, I'll do it.
/assign

**Comment by RainbowMango** [comment]
Send a PR https://github.com/karmada-io/api/pull/19, please take a look.
I don't know how to test it before merging :)

**Comment by calvin0327** [comment]
Can I import the branch to my project directly? I will try it

**Comment by calvin0327** [comment]
Replace with given branch:

```mod
replace (
	github.com/karmada-io/api => github.com/RainbowMango/api-1 v0.0.0-20230705092214-a0843f7a55d2
)
```
And execute command go vendor:

<img width="1032" alt="image" src="https://github.com/karmada-io/karmada/assets/45745657/4c40c5fc-2d55-43d3-be57-3c390a066d8b">

It seem to work.
