### ISSUE TITLE
support Resource Quotas in karmada

### ISSUE THREAD

**Issue by lynnsong** [karmada-io/karmada#377]
**What would you like to be added**:
support Resource Quotas in karmada

**Why is this needed**:
In our scenario, several users or teams will share the ‘cluster’, many users can use all the resources provided. If there is no restriction, someone will be hungry. In order to make all users use resources fairly, we need to support Resource Quotas

**Comment by RainbowMango** [comment]
Given the `users` and `teams` are working in different namespaces, so the user story might be:
- As an administrator, I want to limit aggregate resource consumption per namespace by `ResourceQuota`, so that different users and teams could sharing the cluster according to the quota assigned to them.

Is that your case?

**Comment by lynnsong** [comment]
> Given the `users` and `teams` are working in different namespaces, so the user story might be:
> 
> * As an administrator, I want to limit aggregate resource consumption per namespace by `ResourceQuota`, so that different users and teams could sharing the cluster according to the quota assigned to them.
> 
> Is that your case?

yes, exactly

**Comment by pigletfly** [comment]
You may have a ResourceQuota in each user's namespace, and karmada will propagate the resourcequota to member cluster.Do you want to split ResourceQuota into each cluster using a policy?

**Comment by aven-ai** [comment]
Hello everyone.
Recently, in the application of Karmada, our scenario requires a quota to manage the resource usage of different businesses, similar to Kubernetes' ResourceQuota. 
I noticed that Karmada does not currently have a ResourceQuota object. 
Do we currently have plans to support it? 
If not, I am willing to start supporting ResourceQuota on Karmada.
