### ISSUE TITLE
The karmada-serach helm chart  code without the volumes of etcd certs causes pod failed

### ISSUE THREAD

**Issue by watermeion** [karmada-io/karmada#3774]
**What happened**:

The deployment of karmada-search generated by helm chart  is without  volumes and volumeMounts of /etc/etcd. This causes pod start error in v1.6.0. 
It is definitely missing In helm chart codes.

**Comment by RainbowMango** [comment]
Hi @watermeion Thanks for spotting.
Can you explain how to reproduce it? 
cc @Poor12 @calvin0327 to take a look.

**Comment by watermeion** [comment]
Easy to reproduce by exec helm install using etcd external mode.
Or You can dig into `charts/karmada/templates/karmada-search.yaml` file,  there are no volumeMounts with path `/etc/etcd/pki ....` , but using in container args . This will cause the container exit with no such cert files in order to connect etcd

**Comment by Poor12** [comment]
I think it's definitely a bug. cc contributor @my-git9 to check.

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-search.yaml#L89

Indeed, this is a bug in external mode, the search not to mount the external certs of etcd, I think this a easy to fix bug reference the karmada apiserver yaml:  
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-apiserver.yaml#L140

**Comment by my-git9** [comment]
Sorry for the omission, I will try fix it in https://github.com/karmada-io/karmada/pull/3777/files

**Comment by RainbowMango** [comment]
/assign @my-git9 
Thanks for help.
