### ISSUE TITLE
Operation cannot be fulfilled on karmadas.operator.karmada.io 

### ISSUE THREAD

**Issue by MolisXYliu** [karmada-io/karmada#3782]
when i use karmada-operator to create karmada,the operator's log is
I0711 06:12:29.411489       1 reflector.go:221] Starting reflector *v1alpha1.Karmada (0s) from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262
I0711 06:12:29.411510       1 reflector.go:257] Listing and watching *v1alpha1.Karmada from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262
I0711 06:12:29.511755       1 shared_informer.go:303] caches populated
I0711 06:12:29.511820       1 shared_informer.go:303] caches populated
I0711 06:12:29.511871       1 controller.go:228] "Starting workers" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" worker count=5
I0711 06:14:14.604511       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:14.604471507 +0000 UTC m=+173.395138770"
I0711 06:14:14.647717       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:14.647806       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:14.666396       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0711 06:14:14.666435       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"
I0711 06:14:20.685454       1 controller.go:47] "Finished syncing karmada" karmada="test/karmada-demo" duration="6.080959982s"
I0711 06:14:20.685551       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:20.685532296 +0000 UTC m=+179.476199566"
I0711 06:14:20.685639       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:20.685684       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:20.694281       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0711 06:14:20.694307       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"
I0711 06:14:24.706166       1 controller.go:47] "Finished syncing karmada" karmada="test/karmada-demo" duration="4.020606169s"
I0711 06:14:24.706247       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:24.706230719 +0000 UTC m=+183.496897987"
I0711 06:14:24.706317       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:24.706348       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:24.733990       1 controller.go:47] "Finished syncing karmada" karmada="test/karmada-demo" duration="27.744017ms"
E0711 06:14:24.734058       1 controller.go:329] "Reconciler error" err="Operation cannot be fulfilled on karmadas.operator.karmada.io \"karmada-demo\": the object has been modified; please apply your changes to the latest version and try again" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" Karmada="test/karmada-demo" namespace="test" name="karmada-demo" reconcileID=0dcda10e-2b37-4071-b08b-f3acb5b85900
I0711 06:14:24.734101       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:24.73408924 +0000 UTC m=+183.524756495"
I0711 06:14:24.734160       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:24.734189       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:24.739744       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0711 06:14:24.739763       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"
I0711 06:14:28.751886       1 controller.go:47] "Finished syncing karmada" karmada="test/karmada-demo" duration="4.017782637s"
I0711 06:14:28.752002       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:28.751990406 +0000 UTC m=+187.542657660"
I0711 06:14:28.752067       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:28.752093       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:28.783570       1 controller.go:47] "Finished syncing karmada" karmada="test/karmada-demo" duration="31.56409ms"
E0711 06:14:28.783622       1 controller.go:329] "Reconciler error" err="Operation cannot be fulfilled on karmadas.operator.karmada.io \"karmada-demo\": the object has been modified; please apply your changes to the latest version and try again" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" Karmada="test/karmada-demo" namespace="test" name="karmada-demo" reconcileID=7451daab-2a5b-4c44-b7f6-959455451b7f
I0711 06:14:28.783667       1 controller.go:45] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-11 06:14:28.783654346 +0000 UTC m=+187.574321605"
I0711 06:14:28.783785       1 controller.go:80] "Reconciling karmada" name="karmada-demo"
I0711 06:14:28.783814       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0711 06:14:28.791281       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0711 06:14:28.791313       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"

**Comment by RainbowMango** [comment]
@MolisXYliu Could you please tell us which version you are using?

> E0711 06:14:28.783622 1 controller.go:329] "Reconciler error" err="Operation cannot be fulfilled on karmadas.operator.karmada.io "karmada-demo": the object has been modified; please apply your changes to the latest version and try again"

From the log, I guess this is a temporary conflict, it probably be solved by automatically retrying. 
Have you successfully installed finnally?

**Comment by MolisXYliu** [comment]
the k8s version is v1.20.7 and karmada-operator is the latest. I try in some different environment ang have the same question.

**Comment by MolisXYliu** [comment]
> @MolisXYliu Could you please tell us which version you are using?
> 
> > E0711 06:14:28.783622 1 controller.go:329] "Reconciler error" err="Operation cannot be fulfilled on karmadas.operator.karmada.io "karmada-demo": the object has been modified; please apply your changes to the latest version and try again"
> 
> From the log, I guess this is a temporary conflict, it probably be solved by automatically retrying. Have you successfully installed finnally?
the k8s version is v1.20.7 and karmada-operator is the latest. I try in some different environment ang have the same question.

**Comment by MolisXYliu** [comment]
K8s v1.23.1 has the same question

**Comment by MolisXYliu** [comment]
the karmada-operator image is 
karmada/karmada-operator       latest    9c746fc7572b   21 hours ago    67.3MB

**Comment by calvin0327** [comment]
@MolisXYliu Thanks for pointing this out. 
This is a known problem and there is similar issue: https://github.com/karmada-io/karmada/issues/3770
Related PR: https://github.com/karmada-io/karmada/pull/3778

I guess this pr solves the problem.

**Comment by MolisXYliu** [comment]
> @MolisXYliu Thanks for pointing this out. This is a known problem and there is similar issue: #3770 Related PR: #3778
> 
> I guess this pr solves the problem.

how can i use it?pull the latest karmada/karmada-operator  image or build this image from github code?

**Comment by calvin0327** [comment]
The PR https://github.com/karmada-io/karmada/pull/3778 is not merged, you may have to wait a while. 😅

**Comment by MolisXYliu** [comment]
> 

ok thank you very much! 👍

**Comment by RainbowMango** [comment]
I've asked @Poor12 to help with #3788.
@calvin0327 Please link this issue to #3788 if it addresses this issue. By adding a `Fixes xxx`

**Comment by MolisXYliu** [comment]
@calvin0327 sorry i saw the #3778 was merged and i pull the latest karmada/karmada-operator image and use it create kamada-demo. I wait 10 mins but no pod created.
the operator log is:
I0712 07:02:54.485164       1 operator.go:80] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0712 07:02:54.590289       1 request.go:622] Waited for 84.236853ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/batch/v1?timeout=32s
I0712 07:02:54.639926       1 request.go:622] Waited for 133.856006ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/batch/v1beta1?timeout=32s
I0712 07:02:54.690437       1 request.go:622] Waited for 184.35729ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/certificates.k8s.io/v1?timeout=32s
I0712 07:02:54.740005       1 request.go:622] Waited for 233.905017ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/certificates.k8s.io/v1beta1?timeout=32s
I0712 07:02:54.790302       1 request.go:622] Waited for 284.182241ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/networking.k8s.io/v1?timeout=32s
I0712 07:02:54.839446       1 request.go:622] Waited for 333.292005ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/networking.k8s.io/v1beta1?timeout=32s
I0712 07:02:54.890351       1 request.go:622] Waited for 384.177471ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/policy/v1beta1?timeout=32s
I0712 07:02:54.939651       1 request.go:622] Waited for 433.417735ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I0712 07:02:54.990124       1 request.go:622] Waited for 483.803113ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
I0712 07:02:55.039679       1 request.go:622] Waited for 533.324624ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/storage.k8s.io/v1?timeout=32s
I0712 07:02:55.089913       1 request.go:622] Waited for 583.536637ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/apiextensions.k8s.io/v1?timeout=32s
I0712 07:02:55.140703       1 request.go:622] Waited for 634.30867ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
I0712 07:02:55.190371       1 request.go:622] Waited for 683.94824ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.206.235:6443/apis/scheduling.k8s.io/v1?timeout=32s
I0712 07:02:55.194437       1 context.go:64] Starting "karmada"
I0712 07:02:55.194526       1 context.go:74] Started "karmada"
I0712 07:02:55.194616       1 internal.go:369] "Starting server" path="/metrics" kind="metrics" addr="[::]:8080"
I0712 07:02:55.194652       1 internal.go:369] "Starting server" kind="health probe" addr="[::]:8443"
I0712 07:02:55.194681       1 shared_informer.go:303] caches populated
I0712 07:02:55.194717       1 leaderelection.go:248] attempting to acquire leader lease karmada-system/karmada-operator...
I0712 07:02:55.196882       1 leaderelection.go:352] lock is held by karmada-operator-59fbd7f659-fmsll_8b4ccdf6-281b-4d9c-a5d6-c2595a790622 and has not yet expired
I0712 07:02:55.196910       1 leaderelection.go:253] failed to acquire lease karmada-system/karmada-operator
I0712 07:02:59.523475       1 leaderelection.go:352] lock is held by karmada-operator-59fbd7f659-fmsll_8b4ccdf6-281b-4d9c-a5d6-c2595a790622 and has not yet expired
I0712 07:02:59.523504       1 leaderelection.go:253] failed to acquire lease karmada-system/karmada-operator
I0712 07:03:02.333611       1 leaderelection.go:352] lock is held by karmada-operator-59fbd7f659-fmsll_8b4ccdf6-281b-4d9c-a5d6-c2595a790622 and has not yet expired
I0712 07:03:02.333635       1 leaderelection.go:253] failed to acquire lease karmada-system/karmada-operator
I0712 07:03:05.708498       1 leaderelection.go:352] lock is held by karmada-operator-59fbd7f659-fmsll_8b4ccdf6-281b-4d9c-a5d6-c2595a790622 and has not yet expired
I0712 07:03:05.708520       1 leaderelection.go:253] failed to acquire lease karmada-system/karmada-operator
I0712 07:03:08.416083       1 leaderelection.go:352] lock is held by karmada-operator-59fbd7f659-fmsll_8b4ccdf6-281b-4d9c-a5d6-c2595a790622 and has not yet expired
I0712 07:03:08.416105       1 leaderelection.go:253] failed to acquire lease karmada-system/karmada-operator
I0712 07:03:10.688015       1 leaderelection.go:258] successfully acquired lease karmada-system/karmada-operator
I0712 07:03:10.688195       1 recorder.go:103] "events: karmada-operator-59fbd7f659-7p6s9_1adba7a0-9d35-46e7-8af8-e3da26590bd3 became leader" type="Normal" object={Kind:Lease Namespace:karmada-system Name:karmada-operator UID:46b1036e-f8da-4281-a741-8528135f5566 APIVersion:coordination.k8s.io/v1 ResourceVersion:5947074 FieldPath:} reason="LeaderElection"
I0712 07:03:10.688319       1 controller.go:186] "Starting EventSource" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" source="kind source: *v1alpha1.Karmada"
I0712 07:03:10.688354       1 controller.go:194] "Starting Controller" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada"
I0712 07:03:10.688824       1 reflector.go:221] Starting reflector *v1alpha1.Karmada (0s) from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262
I0712 07:03:10.688836       1 reflector.go:257] Listing and watching *v1alpha1.Karmada from sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262
I0712 07:03:10.789281       1 shared_informer.go:303] caches populated
I0712 07:03:10.789344       1 shared_informer.go:303] caches populated
I0712 07:03:10.789443       1 controller.go:228] "Starting workers" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" worker count=5
I0712 07:04:03.055222       1 controller.go:49] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-12 07:04:03.05519423 +0000 UTC m=+68.597015075"
I0712 07:04:03.066135       1 controller.go:84] "Reconciling karmada" name="karmada-demo"
I0712 07:04:03.066192       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0712 07:04:03.145624       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0712 07:04:03.145645       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"
I0712 07:04:08.157739       1 controller.go:51] "Finished syncing karmada" karmada="test/karmada-demo" duration="5.102515994s"
I0712 07:04:08.157799       1 controller.go:49] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-12 07:04:08.157787967 +0000 UTC m=+73.699608812"
I0712 07:04:08.157859       1 controller.go:84] "Reconciling karmada" name="karmada-demo"
I0712 07:04:08.157902       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0712 07:04:08.290910       1 controller.go:51] "Finished syncing karmada" karmada="test/karmada-demo" duration="133.107233ms"
E0712 07:04:08.290981       1 controller.go:329] "Reconciler error" err="Operation cannot be fulfilled on karmadas.operator.karmada.io \"karmada-demo\": the object has been modified; please apply your changes to the latest version and try again" controller="karmada" controllerGroup="operator.karmada.io" controllerKind="Karmada" Karmada="test/karmada-demo" namespace="test" name="karmada-demo" reconcileID=4094fa1f-704d-4b70-8097-84ee61df46eb
I0712 07:04:08.296347       1 controller.go:49] "Started syncing karmada" karmada="test/karmada-demo" startTime="2023-07-12 07:04:08.296313278 +0000 UTC m=+73.838134130"
I0712 07:04:08.296466       1 controller.go:84] "Reconciling karmada" name="karmada-demo"
I0712 07:04:08.296506       1 planner.go:85] "Start execute the workflow" workflow=init karmada="test/karmada-demo"
I0712 07:04:08.312809       1 crd.go:48] "[prepare-crds] Running prepare-crds task" karmada="test/karmada-demo"
I0712 07:04:08.312835       1 crd.go:49] "[prepare-crds] Using crd folder" folder="/var/lib/karmada/1.6.0" karmada="test/karmada-demo"
I0712 07:04:12.323312       1 controller.go:51] "Finished syncing karmada" karmada="test/karmada-demo" duration="4.026970313s"
I0712 07:12:27.694914       1 reflector.go:559] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262: Watch close - *v1alpha1.Karmada total 17 items received
I0712 07:19:05.698392       1 reflector.go:559] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:262: Watch close - *v1alpha1.Karmada total 0 items received

how can i fix this problem?

**Comment by calvin0327** [comment]
@MolisXYliu Could you show your karmada cr yaml?

**Comment by calvin0327** [comment]
And does the pod of karmada operator can access the url https://github.com/karmada-io/karmada/releases/download/1.6.0/crds.tar.gz? 

Because the operator need to access the url to download the karmada cr pakage.

**Comment by MolisXYliu** [comment]
> 

I donload the code from github and exec the shell
````shell
 kubectl apply -f operator/config/crds/ 
````
and i download   crds.tar.gz how can i use the crds.tar.gz offline

**Comment by calvin0327** [comment]
> > 
> 
> I donload the code from github and exec the shell
> 
> ```shell
>  kubectl apply -f operator/config/crds/ 
> ```
> 
> and i download crds.tar.gz how can i use the crds.tar.gz offline @calvin0327

@MolisXYliu The cluster is offline env?

If you download the crds.tar.gz manually, you can copy the package to the path `/var/lib/karmada/1.6.0/crds/crds.tar.gz` of  karmada operator pod.

**Comment by MolisXYliu** [comment]
> > 
> > 
> > I donload the code from github and exec the shell
> > ```shell
> >  kubectl apply -f operator/config/crds/ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and i download crds.tar.gz how can i use the crds.tar.gz offline @calvin0327
> 
> @MolisXYliu The cluster is offline env?
> 
> If you download the crds.tar.gz manually, you can copy the package to the path `/var/lib/karmada/1.6.0/crds.tar.gz` of karmada operator pod.
> 
> I think we need to build offline image of karmada operator to address the problem.

thanks the pod created by th way my cluster is offline hao can i 

> > > 
> > 
> > 
> > I donload the code from github and exec the shell
> > ```shell
> >  kubectl apply -f operator/config/crds/ 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and i download crds.tar.gz how can i use the crds.tar.gz offline @calvin0327
> 
> @MolisXYliu The cluster is offline env?
> 
> If you download the crds.tar.gz manually, you can copy the package to the path `/var/lib/karmada/1.6.0/crds.tar.gz` of karmada operator pod.
> 
> I think we need to build offline image of karmada operator to address the problem.

thanks the pod created. by the way because my cluster is offline env .how  should I specify  the image name and version such as ：
registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.3-0   now the default is  registry.k8s.io/etcd:3.5.3-0

**Comment by calvin0327** [comment]
> 

You modity the karmada cr yaml:


```yaml
...
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
spec:
  components:
    etcd:
      local:
        imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
        imageTag: 3.5.3-0
...
```

**Comment by MolisXYliu** [comment]
> > 
> 
> @MolisXYliu you can modity the karmada cr yaml:
> 
> ```yaml
> ...
> apiVersion: operator.karmada.io/v1alpha1
> kind: Karmada
> metadata:
>   name: karmada-demo
>   namespace: test
> spec:
>   components:
>     etcd:
>       local:
>         imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
>         imageTag: 3.5.3-0
> ...
> ```

it works .thank you very much !!!

**Comment by MolisXYliu** [comment]
> > 
> 
> @MolisXYliu you can modity the karmada cr yaml:
> 
> ```yaml
> ...
> apiVersion: operator.karmada.io/v1alpha1
> kind: Karmada
> metadata:
>   name: karmada-demo
>   namespace: test
> spec:
>   components:
>     etcd:
>       local:
>         imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
>         imageTag: 3.5.3-0
> ...
> ```

when i speicy etcd image it works but other name such as karmada-aggregated-apiserver ,it run wrong wuch as
````yaml
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
spec:
  components:
    etcd:
      local:
        imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
        imageTag: 3.5.3-0
    karmada-aggregated-apiserver:
      local:
        imageRepository: karmada/karmada-aggregated-apiserver
        imageTag: v1.4.0
`
error validating data: ValidationError(Karmada.spec.components): unknown field "karmada-aggregated-apiserver" in io.karmada.operator.v1alpha1.Karmada.spec.components; if you choose to ignore these errors, turn validation off with --validate=false

please tell me all karmada image key thanks @calvin0327

**Comment by MolisXYliu** [comment]
sorry i have a new question i use this yaml to create karmada
````yaml
apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: karmada-demo
  namespace: test
spec:
  components:
    etcd:
      local:
        imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd
        imageTag: 3.5.3-0
    karmadaAPIServer:
      imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver
      imageTag: v1.25.4
    karmadaAggregatedAPIServer:
      imageRepository: karmada/karmada-aggregated-apiserver
      imageTag: v1.4.0
    karmadaControllerManager:
      imageRepository: karmada/karmada-controller-manager
      imageTag: v1
    karmadaScheduler:
      imageRepository: karmada/karmada-scheduler
      imageTag: v1.4.0
    karmadaWebhook:
      imageRepository: karmada/karmada-webhook
      imageTag: v1.4.0
    kubeControllerManager:
      imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager
      imageTag: v1.25.4
```
I saw oniy ths pod create 
````
NAME                                                 READY   STATUS    RESTARTS   AGE
karmada-demo-aggregated-apiserver-5586f4b9cd-cwqk9   1/1     Running   0          6m53s
karmada-demo-apiserver-57f59cf6c-bb7qd               1/1     Running   0          7m12s
karmada-demo-etcd-0                                  1/1     Running   0          7m15s
````
in the demo there are 7 pod ,why i only have 3?
@calvin0327  thanks
