### ISSUE TITLE
使用karmada下发cr到member集群里，cr的condition在member集群中做了更改，karmada无法感知么？

### ISSUE THREAD

**Issue by donkeywon** [karmada-io/karmada#3799]
**Please provide an in-depth description of the question you have**:
使用karmada下发cr到member集群里， member集群中安装了cr对应的operator，operator对member集群中的cr的condition字段做了更改，karmada控制面感知不到这个更改，有什么办法可以让karmada感知到么？是使用方式不对还是要自定义开发呢？
需要提供额外信息的话我可以贴出来

**What do you think about this question?**:

**Environment**:
- Karmada version: 1.6.1
- Kubernetes version: 1.23.4
- Others:

**Comment by chaunceyjiang** [comment]
自定义cr 需要你在karmada 控制平面创建一个 `ResourceInterpreterCustomization ` 资源，用来告诉karmada 如何解析你自定义的 cr 结构。


初步看你只关心 cr的 status 字段，所以你可以先只实现 `statusAggregation ` .

可以参考样例：
https://karmada.io/docs/userguide/globalview/customizing-resource-interpreter/#write-with-configuration

**Comment by donkeywon** [comment]
@chaunceyjiang 好的，我看下

**Comment by donkeywon** [comment]
@chaunceyjiang 想问下如果member集群修改了cr的metadata.annotations或spec.annotations，需要同步给karmada控制面的话，是使用retention解释器么？

**Comment by donkeywon** [comment]
测试了下发现metadata.annotation在member集群修改后不会被karmada覆盖，spec.annotation在member集群修改后会被karmada覆盖到之前的状态，使用retention解释器后可以阻止spec.annotations被karmada覆盖，保留member集群修改的内容，但是把member集群中修改的metadata或spec内容回写到karmada似乎做不到

**Comment by XiShanYongYe-Chang** [comment]
是的，在成员集群中修改，同步到Karmada控制面上目前是没有渠道的。可以问下这么做的具体场景是？

**Comment by donkeywon** [comment]
@XiShanYongYe-Chang 场景不合理，已经不考虑了，现在只对spec.annotation做了retention

**Comment by XiShanYongYe-Chang** [comment]
好的，感谢回复

**Comment by XiShanYongYe-Chang** [comment]
先关闭当前issue了，如果有问题可以随时再打开。
/close
