### ISSUE TITLE
Workstatus Controller Should Only Focus on Status and Only Update Object in Member Cluster by Execution Controller

### ISSUE THREAD

**Issue by lxtywypc** [karmada-io/karmada#3807]
**What would you like to be added**:
Make `workstatus-controller` only focus on reflecting object status, and all operations on objects in member clusters should be finished by `execution-controller`.  

**Why is this needed**:  
Like in #1362   
1. When two controllers are attempting to update the same resource, the confict would occur easily, and it is a little hard to do some retries in one reconcile because we are not sure which one would be a later one clearly.  
2. Even both `execution-controller` and `workstatus-controller` are able to sync objects in member clusters, only `execution-controller` have a chance to update the `Applied` `condition` in `work status`. That seems a bit unreasonable. How would it be if the `workstatus-controller` failed to sync the object in member cluster and this condition last a time? The object in member cluster is not as expected, and status is wrong(old) in fed control plane, but what the `condition` in `work status` tells us is the resource is applied.

**Comment by XiShanYongYe-Chang** [comment]
Hi @lxtywypc, thanks.
Recently, some issues in the community are also related to this issue. I'm glad you give feedback on this issue and made the corresponding code submission.

For the first point, is it a big conflict when two controllers update the same resource? Do you have any relevant data to support this?

For the second point, this is exactly the issue I mentioned earlier, such as other issues that have been raised: #3587 #3572. I hope the modifications you proposed can solve this issue.

/assign @lxtywypc 
In favor of #3808.

**Comment by lxtywypc** [comment]
@XiShanYongYe-Chang I'm sorry for replying late.  

We quite met a terrible conflict which blocked out rollout for a long time, but it is a little complex scene. I'm sorry for unable to describe it clearly. Maybe we could talk about it in WeChat group later.

**Comment by XiShanYongYe-Chang** [comment]
> We quite met a terrible conflict which blocked out rollout for a long time, but it is a little complex scene. I'm sorry for unable to describe it clearly. Maybe we could talk about it in WeChat group later.

Ok. thanks a lot~

**Comment by XiShanYongYe-Chang** [comment]
Hi @lxtywypc, I would like to ask another question.
If the parallelism of the worker is greater than 1, is it possible for conflicts to occur? Is the probability of conflicts lower compared to before the modification?

**Comment by lxtywypc** [comment]
Hi @XiShanYongYe-Chang 
> If the parallelism of the worker is greater than 1, is it possible for conflicts to occur? Is the probability of conflicts lower compared to before the modification?  

Not for the object in member cluster in theory. After the modification, only the `execution controller` is able to update the object in member cluster, and the event from both object in member cluster and work in fed control plane, to trigger updating, would be added to the same queue and refered to the same `work`, the same items would be deduplicated when enqueueing.   
The conflict in updating `work status` is possible for still the two controllers are able to update it. But the updating of the object in member cluster is from the unique source now, we could do some retries to make the updating successful, to reduce the updating `condition` in `work` from the `exectution controller` to prevent the confliction  as much as possible.

**Comment by RainbowMango** [comment]
> For the second point, this is exactly the issue I mentioned earlier, such as other issues that have been raised: https://github.com/karmada-io/karmada/issues/3587 https://github.com/karmada-io/karmada/issues/3572. I hope the modifications you proposed can solve this issue.

Do you think the #3808 solved the referring #3538, #3572?  If yes, we can add a `Fixes` to #3808.

**Comment by lxtywypc** [comment]
> Do you think the #3808 solved the referring #3538, #3572? If yes, we can add a `Fixes` to #3808.  

Hi @RainbowMango 
I think you might refer to #3587 and #3572.  
They seems to be two different ways to solve the same problem that how to process the status of `work` when `workstatus controller` synced a `work` failed. Like https://github.com/karmada-io/karmada/issues/3572#issuecomment-1641371525, the #3808 tends to take the way as #3587.  
The #3808 could solve the #3587, but I don't know if the #3572 could be considered as solved as well.
