### ISSUE TITLE
cluster-status-controller: exclude nodes that are not ready, unschedule or have taints

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#383]
**What would you like to be added**:
Exclude nodes that are not ready, unschedule or have taints and pods that are assigned to these nodes. This enhancement should be added after #365.

**Why is this needed**:
Now the `cluster-status-controller` will aggregate all pods and nodes resource without filtering. However, some nodes may be unschedule or not ready. If counting these resources, karmada scheduler will incorrectly calculate free resource and have a bad effect for scheduling. 

https://github.com/karmada-io/karmada/blob/763c2a10e7bac9397c2202053506569e015b3840/pkg/controllers/status/cluster_status_controller.go#L271-L302

**Comment by RainbowMango** [comment]
There is nothing to do with this issue, right? @Garrybest

**Comment by Garrybest** [comment]
Right, more work may be done in #521, this issue could be closed.
