### ISSUE TITLE
官方文档中统一授权的问题

### ISSUE THREAD

**Issue by Aksox** [karmada-io/karmada#3849]
**Please provide an in-depth description of the question you have**:
链接：https://karmada.io/zh/docs/userguide/bestpractices/unified-auth#step3-access-member1-cluster
这个 kubectl apply -f - <<EOF 操作缺少 --kubeconfig参数，不知道是使用控制面的config还是member1的config
**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
In favor of https://github.com/karmada-io/website/issues/437, close it first.
