### ISSUE TITLE
monitor cluster lifecycle

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#385]
**What would you like to be added**:
1. Add ClusterLifecycleContoller.
2. Use v1.NodeCondition instead of metav1.Condition for adding `LastHeartbeatTime`.

**Why is this needed**:
Now when we stop the agent, the cluster will always be ready. We should add a `cluster_lifecycle_controller` to manage the lifecyle of clusters. Also, the `cluster_status_controller` should also update its heart beat time so that the `cluster_lifecycle_controller` will catch the `NotReady` condition. [NodeLifecycleController](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/controller/nodelifecycle/node_lifecycle_controller.go) can be taken as a good reference.

**Comment by RainbowMango** [comment]
You got my mind, I've added this to v0.7 plan.

> Use v1.NodeCondition instead of metav1.Condition for adding LastHeartbeatTime.

Yeah, we need a field to record `LastHeartbeatTime`, but I don't think it's worth getting back to `v1.NodeCondition`.

**Comment by Garrybest** [comment]
> Yeah, we need a field to record `LastHeartbeatTime`, but I don't think it's worth getting back to `v1.NodeCondition`.

Good idea. What about newing a struct `ClusterCondition` like this? I found every api in kubernetes would define their own condition in `types.go`.

```go
// Define valid conditions of a member cluster.
const (
	// ClusterConditionReady means the cluster is healthy and ready to accept workloads.
	ClusterConditionReady ClusterConditionType = "Ready"
	// ClusterConditionNotReady means the cluster is unhealthy and should not accept workloads.
	ClusterConditionNotReady ClusterConditionType = "NotReady"
)

type ConditionStatus string

// These are valid condition statuses. "ConditionTrue" means a resource is in the condition.
// "ConditionFalse" means a resource is not in the condition. "ConditionUnknown" means kubernetes
// can't decide if a resource is in the condition or not. In the future, we could add other
// intermediate conditions, e.g. ConditionDegraded.
const (
	ConditionTrue    ConditionStatus = "True"
	ConditionFalse   ConditionStatus = "False"
	ConditionUnknown ConditionStatus = "Unknown"
)

// ClusterCondition contains condition information for a cluster.
type ClusterCondition struct {
	// Type of cluster condition.
	Type ClusterConditionType `json:"type"`
	// Status of the condition, one of True, False, Unknown.
	Status ConditionStatus `json:"status"`
	// Last time we got an update on a given condition.
	// +optional
	LastHeartbeatTime metav1.Time `json:"lastHeartbeatTime,omitempty"`
	// Last time the condition transit from one status to another.
	// +optional
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`
	// (brief) reason for the condition's last transition.
	// +optional
	Reason string `json:"reason,omitempty"`
	// Human readable message indicating details about last transition.
	// +optional
	Message string `json:"message,omitempty"`
}
```

**Comment by Garrybest** [comment]
Another solution: use `Lease` to get the `RenewTime` as a substitute for `LastHeartbeatTime `. Every `cluster-status-controller` should create a `lease` and try to renew its `RenewTime`. So that there is no need to change `metav1.Condition`.

**Comment by RainbowMango** [comment]
> I found every api in kubernetes would define their own condition in types.go like NodeCondition, PodCondition, DeploymentCondition, StatefulSetCondition .

That is the reason why Kubernetes will introduce a `metav1.Condition`, more and more Kubernetes API will adopt `metav1.Condition` in the future.

**Comment by RainbowMango** [comment]
Reopen as the lifecycle controller still not getting on board.
