### ISSUE TITLE
Cannot join a member cluster: Get error related to serviceAccount secret for impersonation

### ISSUE THREAD

**Issue by mrequena** [karmada-io/karmada#3850]
**Please provide an in-depth description of the question you have**:

I do:
$ karmadactl join cluster-abc --kubeconfig=$HOME/.kube/config --karmada-context=karmada-apiserver --cluster-kubeconfig=... --cluster-context=...
and I get the following error:
error: failed to get serviceAccount secret for impersonation from cluster(cluster-abc), error: failed to get serviceAccount secret, error: timed out waiting for the condition

In the member cluster, the following resources are created in namespace karmada-cluster:
NAME                          TYPE                                  DATA   AGE
secret/karmada-impersonator   kubernetes.io/service-account-token   0      87m
NAME                                  SECRETS   AGE
serviceaccount/karmada-impersonator   0         87m

I have other members cluster joined in Karmada. When I did the join for those clusters I did not have any issue:
$ kubectl get clusters -A
NAME              VERSION    MODE   READY   AGE
cluster-xxx       v1.24.1    Push   True    27d
cluster-xxx       v1.23.5    Push   True    65d
member-xxx     v1.19.10   Push   True    120d
member-xxx    v1.25.6    Push   True    35d
member-xxx    v1.25.6    Push   True    43d

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.5.0
- Kubernetes version: 
  - host of Karmada v1.24.3
  - member cluster (control-plane v1.25.3, nodes v1.24.3)
- Others: 
karmadactl version: version.Info{GitVersion:"v1.5.0", GitCommit:"51fbbb055d47331e83a6ca2e90b8a5312d6a7986", GitTreeState:"clean", BuildDate:"2023-02-28T12:02:41Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by XiShanYongYe-Chang** [comment]
From the secret information on the member cluster you provided, it appears that no token information has been generated for the secret because its data size is 0.
```
NAME TYPE DATA AGE
secret/karmada-impersonator kubernetes.io/service-account-token 0 87m
```

 Could you please check why the secret did not generate a token?

**Comment by XiShanYongYe-Chang** [comment]
You can refer to the document to create service-account-token-secrets: https://kubernetes.io/zh-cn/docs/concepts/configuration/secret/#service-account-token-secrets

**Comment by mrequena** [comment]
This secret is created by karmadactl when I do the "karmadactl join", not me. So, how can I check what is happening with the "karmadactl join"?
Thanks for your help!

**Comment by mrequena** [comment]
I created a ServiceAccount and Secret manually with the following yaml and the token is not generated. Should I also generate the token?
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karmada-xxx
  namespace: karmada-cluster
apiVersion: v1
kind: Secret
metadata:
  name: karmada-xxx
  namespace: karmada-cluster
  annotations:
    kubernetes.io/service-account.name: "karmada-xxx"
type: kubernetes.io/service-account-token
---

The doc says:
"After the Secret is created, a Kubernetes [controller](https://kubernetes.io/docs/concepts/architecture/controller/) fills in some other fields such as the kubernetes.io/service-account.uid annotation, and the token key in the data field, which is populated with an authentication token." 
But the token is not populated.

**Comment by mrequena** [comment]
I tried to create the token manually as it is explained here https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount
But I don't know how to use the output of "kubectl create token"

**Comment by XiShanYongYe-Chang** [comment]
Hi @mrequena 

> "After the Secret is created, a Kubernetes [controller](https://kubernetes.io/docs/concepts/architecture/controller/) fills in some other fields such as the kubernetes.io/service-account.uid annotation, and the token key in the data field, which is populated with an authentication token."

Under normal circumstances, operations within the cluster are expected to comply with this requirement. Have you disabled any controllers related to kube-controller-manager in the member cluster?

**Comment by XiShanYongYe-Chang** [comment]
> I tried to create the token manually as it is explained here https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount
> But I don't know how to use the output of "kubectl create token"

We use this approach in our program: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount

**Comment by XiShanYongYe-Chang** [comment]
Hi @mrequena, have you find the root cause?

**Comment by mrequena** [comment]
> Under normal circumstances, operations within the cluster are expected to comply with this requirement. Have you disabled any controllers related to kube-controller-manager in the member cluster?

Hi  @XiShanYongYe-Chang , I have access to the member cluster but I didn't installed it. Do you know what controllers should I look or ask for?

**Comment by mrequena** [comment]
It seems the member cluster renewed the certificates but was not in a proper state. After restarting the kube-controller-manager, the cluster was ok and I could join it to Karmada.
@XiShanYongYe-Chang , thank you so much for your help!

**Comment by XiShanYongYe-Chang** [comment]
👍 I'm glad to hear that your question has been resolved.
