### ISSUE TITLE
Some workloads cannot be scheduled by replica and resource requirements

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3858]
**What happened**:
Some workloads, like `Pod`, `DaemonSet` and etc, cannot be scheduled by replica and resource requirements due to the lack of `InterpretReplica` operation.
https://github.com/karmada-io/karmada/blob/cf90ffc64fbfa16083c8371905b4789fb4f98a6f/pkg/resourceinterpreter/default/native/replica.go#L18-L24

For example, I create a pod named `foo`:
```
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: nginx
    image: image.cestc.cn/ccos-test/nginx:1.19.0
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: "0"
        memory: "0"
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
  - name: busybox
    image: image.cestc.cn/ccos-test/busybox:1.32.0
    ports:
    - name: web
      containerPort: 81
      protocol: TCP
    command:
    - sleep
    - "86400"
```
it's resource binding has not replica and requirements, which will prevent the scheduler from knowing the information.
```
apiVersion: work.karmada.io/v1alpha2
kind: ResourceBinding
metadata:
  annotations:
    policy.karmada.io/applied-placement: '{"clusterTolerations":[{"key":"cluster.karmada.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"cluster.karmada.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"replicaScheduling":{"replicaSchedulingType":"Divided","replicaDivisionPreference":"Aggregated"}}'
  creationTimestamp: "2023-07-28T06:36:01Z"
  finalizers:
  - karmada.io/binding-controller
  generation: 2
  labels:
    propagationpolicy.karmada.io/name: test-pod
    propagationpolicy.karmada.io/namespace: default
  name: foo-pod
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Pod
    name: foo
    uid: 6bca8b86-d3a1-4acc-8573-0b5722c201fb
  resourceVersion: "5675183"
  uid: 1b152502-af3c-48fc-97f1-9bc4e00c592f
spec:
  clusters:
  - name: member1
  - name: member2
  - name: member3
  - name: single160138
  placement:
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
  resource:
    apiVersion: v1
    kind: Pod
    name: foo
    namespace: default
    resourceVersion: "5674969"
    uid: 6bca8b86-d3a1-4acc-8573-0b5722c201fb
  schedulerName: default-scheduler

```
**What you expected to happen**:
Currently it will be scheduled according to the number of pods that can be placed on the cluster rather than specific resource requirements. Expect specific resource requirements to take effect.
```
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: "0"
        memory: "0"
```

**How to reproduce it (as minimally and precisely as possible)**:
create and propagate a pod.

**Anything else we need to know?**:

**Environment**:
- Karmada version: all version
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
/remote-kind bug
/kind feature
I think it's more like a feature.

**Comment by RainbowMango** [comment]
> Some workloads, like Pod, DaemonSet and etc, cannot be scheduled by replica and resource requirements due to the lack of InterpretReplica operation.

The reason why we didn't support such resource types is we don't know if it is really needed by users.

For example, we haven't got feedback on propagating Pods with Karmada.
We can add them whenever this is a real case. Before that people can customized the behavior. 

Is it a real case by the way?

**Comment by whitewindmills** [comment]
> Is it a real case by the way?

For resources like virtual machines, which do not require advanced workloads to manage, using Pod is the most appropriate.

**Comment by RainbowMango** [comment]
I'd like to hear more use cases about the virtual machines, can you help to share some, like links, or even have a chat at a community meeting?

I'm just curious, not an objection.

**Comment by whitewindmills** [comment]
sorry, we don't have such use case now. for virtual machines, we propagate `VM` crd to member clusters first,  `vm-controller` of member clusters will process it and create directly pod. but the recent work on edge clusters made me notice the possibility of such user cases in the future, because the resource specifications of edge clusters are very low, and we will not deploy unnecessary services to increase its load, so it may be feasible to propagate directly vm pods to edge clusters. 
so this is my original intention for submitting this issue.
