### ISSUE TITLE
Resource can be managed by HPA in member clusters.

### ISSUE THREAD

**Issue by youhangwang** [karmada-io/karmada#386]
How to enable hpa in karmada?

**What would you like to be added**:
- Enable HPA in Karmada
- Resource can be managed by HPA in member clusters. Like the `retainReplicas` in kubefed v2.

I try to use the following ways to enale HPA in Karmada, but it doesn't work:

1. Use karmada API to deploy a deployment and use policy to propagate the deployment to member clusters. And enable the HPA in member cluster.
2. Use karmada API to deploy a deployment and use policy to propagate the deployment to member clusters. Also, deploy the hpa by using karmada API and the hpa will be deployed into member cluster automatically.

In both cases, the fed-deployment will overwrite the hpa desire replicas lead to the pods create and terminate over and over again...

I didn't find any docs about how to enable hpa in karmada and how to enable a feature like `retainReplicas` in kubefed v2. Is there anything wrong here to use the hpa?

**Why is this needed**:

**Comment by GitHubxsy** [comment]
I think we need smarter ways to preserve fields, not just Replicas.

**Comment by RainbowMango** [comment]
@YouHang We planed to develop this feature in [Q3](https://github.com/karmada-io/karmada/blob/master/ROADMAP.md#2021-q3).

I'll appreciate if you want to share your use case or your expectation with me. 
I guess this feature would be in v0.7.0 or v0.8.0
/milestone v0.7.0

**Comment by YouHang** [comment]
@RainbowMango 
What we need is quite simple:
1. fed hpa can propergate HPA resources into member clusters by using some specify policies. For example, part the min and max replicas in fed-hpa by the ratio of scale of each cluster.
2. once the fed hpa doesn't work. HPA in member cluster can still scale replicas in each cluster.
3. fed-develop will not override replicas once the hpa is enabled.

Also, it will be great if hpa can scale the replicas accross multi-clusters.

**Comment by YouHang** [comment]
@RainbowMango  Is there any design proposal about the karmada hpa?  I‘d like to do some contributions.

**Comment by RainbowMango** [comment]
> Is there any design proposal about the karmada hpa? I‘d like to do some contributions.

No design docs yet. And you are welcome to join the community!

**Comment by RainbowMango** [comment]
> part the min and max replicas in fed-hpa by the ratio of scale of each cluster.

Didn't get your point, sorry.

> once the fed hpa doesn't work. HPA in member cluster can still scale replicas in each cluster.

What do you mean `fed hpa` doesn't work? Do you mean the `karmada` control plane doesn't work(crash or something bad happens)?

> fed-develop will not override replicas once the hpa is enabled.

Yes, if the replica manages by HPA, then others can't update replicas, otherwise, it's hard to solve the conflicts.

**Comment by YouHang** [comment]
Yes, it means the karmada control plane or just the hpa controller in karmada control plane crash.

**Comment by RainbowMango** [comment]
/close
Please see #1360 and discuss there.
