### ISSUE TITLE
Is it  appropriate to change `--skipped-propagating-apis` into `--managed-propagating-apis`?

### ISSUE THREAD

**Issue by snowplayfire** [karmada-io/karmada#3866]
**What would you like to be added**:

**Why is this needed**:
It's more clear to know how many resources are managed by karmada, which is helpful to be aware of how much it has endured.

**Comment by snowplayfire** [comment]
@RainbowMango @XiShanYongYe-Chang  please have a look.

**Comment by RainbowMango** [comment]
`--skipped-propagating-apis` is a kind of `ignore list`, but the `--managed-propagating-apis` is a kind of `allowed list`, 
Do you mean people have to edit the configuration every time they add a new CRD?

**Comment by snowplayfire** [comment]
How about Hot reload `allowed list`?  The implementation method is open to further discussion.

**Comment by RainbowMango** [comment]
> which is helpful to be aware of how much it has endured

I'd like to hear more details about this requirement. We might have other solutions.

**Comment by RainbowMango** [comment]
How about talking about it at tomorrow's community meeting?

**Comment by snowplayfire** [comment]
> How about talking about it at tomorrow's community meeting?

ok

**Comment by RainbowMango** [comment]
I just added [an agenda](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.bdr7uobkel4t) for you.

**Comment by chaosi-zju** [comment]
It seems like there are four ways to achieve it:

1. add `--skipped-propagating-apis` as params of `karmada-controller-manager`: API is not intuitive to users、lack of management、lack of visualization
2. managed as a `allowed list` by RBAC: not intuitive to users too, somewhat tricky
3. add a new API: the workload involved may be a bit larger
4. managed as a `allowed list` in ConfigMap: similar to "add a new API" in basic principle, but not as clear as it is

So, I prefer to add a new API, which names like `PropagateAPIList`, then we can define the propagating-apis managed/skipped as a allow/ignore list in `spec` field, and we can observe how many resources are managed or how much it has endured in `status` field by `kubectl`. I favour it for its intuitive and visualization.

**Comment by majoyz** [comment]
Is anything updated for the issue? It seems the point is how to show objects that the karmada controlled. Can we just create a default propagationpolicy and make it show all resources the karmada controlled? The pp needn't to be in effect and it doesn't need to add new API. 
By the way, it seems detector won't process resource objects without matched propagationpolicy, is it right?

**Comment by RainbowMango** [comment]
> Can we just create a default propagationpolicy and make it show all resources the karmada controlled? The pp needn't to be in effect and it doesn't need to add new API.

What's the default PropagationPolicy look like? Who is responsible for `creating` it and `recording` the resource list?

> By the way, it seems detector won't process resource objects without matched propagationpolicy, is it right?

Yes, the unmatched resources will be put on a waiting list.

**Comment by RainbowMango** [comment]
/close
Please feel free to re-open it if you still need it.
