### ISSUE TITLE
Fix GitHub action warnings about `node1` and `set-output command`

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#3871]
**Task description**:

**Solution**:
There are two warnings raised when running [a7ul/tar-action@v1.1.0](https://github.com/karmada-io/karmada/blob/09259b1f10cadb612115a5e2769760790dde6647/.github/workflows/release.yml#L54C7-L54C7):

https://github.com/karmada-io/karmada/actions/runs/5723972944
```
The following actions uses node12 which is deprecated and will be forced to run on node16: a7ul/tar-action@v1.1.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

and

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Those can be fixed by updating `a7ul/tar-action` to [v1.1.3](https://github.com/a7ul/tar-action/releases/tag/v1.1.3).

```diff
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
index ab22a266b..6b33561b2 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,7 +51,7 @@ jobs:
       run: |
         mv ./charts/karmada/_crds ./charts/karmada/crds
     - name: Tar the crds
-      uses: a7ul/tar-action@v1.1.0
+      uses: a7ul/tar-action@v1.1.3
       with:
         command: c
         cwd: ./charts/karmada/

```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by chl178** [comment]
Hi @RainbowMango, I'm Chenhao a first-time contributor and would love to work on this issue. Looking forward to contributing to Karmada!

**Comment by RainbowMango** [comment]
Thanks @chl178 , you are welcome, feel free to reach me if you need help!
