### ISSUE TITLE
Resource template cannot be reconciled again due to cache modification

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3878]
**What happened**:
I deleted propagation policy `default/test-pp` to unbind from configmap `default/test-cm`, but find that configmap `default/test-cm` cannot be reconciled again. 
![image](https://github.com/karmada-io/karmada/assets/89241565/058aa0d4-0685-43c0-b75d-428b5142d287)

that means configmap `default/test-cm` cannot be matched by new propagation policy `default/test-pp-1`.
![image](https://github.com/karmada-io/karmada/assets/89241565/f441d211-203f-47b7-89cf-a2af4a9feee6)

**What you expected to happen**:
configmap `default/test-cm` can be matched by new propagation policy `default/test-pp-1`.

**How to reproduce it (as minimally and precisely as possible)**:
1. create such configmap(keep labels non-nil):
```
apiVersion: v1
data:
  a: b
kind: ConfigMap
metadata:
  labels:
    a: b
  name: test-cm
  namespace: default
```
2. create propagation policy.
3. delete propagation policy after configmap is propagated.
4. check if configmap can be reconcile again.

**Anything else we need to know?**:
`detector` deletes directly policy labels from cached resource template.
https://github.com/karmada-io/karmada/blob/d916d877a4942d9abf0467d65562d471acf8138d/pkg/detector/detector.go#L1117-L1131

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
[Do you mean ](https://github.com/karmada-io/karmada/blob/a2dc2e8bbb56196910f8443218ca86ec8169eca6/pkg/detector/detector.go#L1139)

> detector deletes directly policy labels from cached resource template.

Do you mean here actually updates the cache?

**Comment by whitewindmills** [comment]
> Do you mean here actually updates the cache?

here, `workload` is from the informer cache.
https://github.com/karmada-io/karmada/blob/d916d877a4942d9abf0467d65562d471acf8138d/pkg/detector/detector.go#L1131-L1131

**Comment by RainbowMango** [comment]
Yeah I get it, It mistakenly updated the cache, but I still don't understand why the update event would be ignored.

**Comment by whitewindmills** [comment]
it's ignored by the function `SpecificationChanged`.
https://github.com/karmada-io/karmada/blob/946fc72fade05336913fb9fd8aa7c32d690a666b/pkg/detector/detector.go#L306-L309
it removes uncessary fields and calls `reflect.DeepEqual` to compare if the remaining fields actually changed.
https://github.com/karmada-io/karmada/blob/946fc72fade05336913fb9fd8aa7c32d690a666b/pkg/detector/eventfilter.go#L9-L23

**Comment by RainbowMango** [comment]
Do you mean `oldObj` comes from cache and `newObj` is the updated object, since the labels have already been removed from the cache, so the `oldOjb` is always equal to `newOjb`?

**Comment by whitewindmills** [comment]
> since the labels have already been removed from the cache, so the oldOjb is always equal to newOjb?

yes

**Comment by RainbowMango** [comment]
Thanks. That makes sense now.
