### ISSUE TITLE
Add e2e case to cover policy cleanup

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#3884]
Through this issue(#3878), we found that there is a behavior of directly modifying cached resource in the `detector`, we need to add related E2E to cover these scenarios.

related pr: [#3879](https://github.com/karmada-io/karmada/pull/3879)

**Comment by XiShanYongYe-Chang** [comment]
Let's add a label and see if any buddies are willing to do it.
/help

**Comment by yike21** [comment]
/assign
Hi! @XiShanYongYe-Chang I'm willing to do it, and I will make it ASAP.

**Comment by XiShanYongYe-Chang** [comment]
@yike21 Thanks a lot~
