### ISSUE TITLE
Add repo index with latest version so helm charts will be synced

### ISSUE THREAD

**Issue by yizhang-zen** [karmada-io/karmada#3892]
**What happened**:
After I removed karmada repo and re-added it, there is no latest alpha version or v1.6.1/1.6.2 (see below). 

Can someone upload all latest versions to chart repo and update the [index](https://github.com/karmada-io/karmada/blob/master/charts/index.yaml)? So we can try out new version soon? Thank you!
```
[~/Code/karmada (master)] ➔ helm search repo karmada -l
NAME                  	CHART VERSION	APP VERSION	DESCRIPTION
karmada-charts/karmada	v1.6.0       	latest     	A Helm chart for karmada
karmada-charts/karmada	v1.5.0       	v1.1.0     	A Helm chart for karmada
karmada-charts/karmada	v1.4.0       	v1.1.0     	A Helm chart for karmada
karmada-charts/karmada	v1.3.0       	v1.1.0     	A Helm chart for karmada
karmada-charts/karmada	v1.2.2       	v1.1.0     	A Helm chart for karmada
karmada-charts/karmada	v1.2.1       	v1.1.0     	A Helm chart for karmada
karmada-charts/karmada	v1.2.0       	v1.1.0     	A Helm chart for karmada
```

```
Error: chart "karmada" version "v1.6.2" not found in https://raw.githubusercontent.com/karmada-io/karmada/master/charts repository
: unable to run: 'helm pull --untar --untardir /../../kustomize/base/charts --repo https://raw.githubusercontent.com/karmada-io/karmada/master/charts karmada --version v1.6.2'
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaosi-zju** [comment]
@yizhang-zen Thank you! I much appreciated this feedback, I will do it soon~

**Comment by chaosi-zju** [comment]
@yizhang-zen hello，I have submit the PR to update the helm index.yaml https://github.com/karmada-io/karmada/pull/3911

however, after it merged, it may be some other gap for you to try out new version, since https://github.com/karmada-io/karmada/issues/3912. (I will continue to follow up on this issue as well)

**Comment by RainbowMango** [comment]
@chaosi-zju rebuilt the charts and I just upload it to the artifacts of https://github.com/karmada-io/karmada/releases/tag/v1.6.2.
