### ISSUE TITLE
karmadactl init command support external etcd

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3897]
**What would you like to be added**:

Make `init` command of `karmadactl` to support using a external etcd.

**Why is this needed**:

Users may have existing etcd cluster which is under well maintenance by a team, so it's better to use such etcd cluster, rather than setup new one. (a poor one, maybe)

**Comment by RainbowMango** [comment]
/assign @tedli 
In favor of #3898 
Thanks @tedli .
