### ISSUE TITLE
 Failed calling webhook, failing closed cluster.karmada.io: failed calling webhook "cluster.karmada.io": expected response.uid="6a36df4b-6b85-439d-b616-11bae0ed42c8", got ""

### ISSUE THREAD

**Issue by hellocloudnative** [karmada-io/karmada#390]
`$ karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config

W0531 15:27:55.867711 5
Duplicate of #2007 join.go:452] failed to create cluster(). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
W0531 15:27:55.867807 502007 join.go:426] failed to create cluster(member1). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867827 502007 join.go:280] failed to create cluster object. cluster name: member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867840 502007 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""`

**Comment by hellocloudnative** [comment]
`$  karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config
W0531 15:27:55.867711  502007 join.go:452] failed to create cluster(). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
W0531 15:27:55.867807  502007 join.go:426] failed to create cluster(member1). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867827  502007 join.go:280] failed to create cluster object. cluster name: member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867840  502007 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""`

**Comment by hellocloudnative** [comment]
`$  karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config

W0531 15:27:55.867711  5
Duplicate of #02007 join.go:452] failed to create cluster(). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
W0531 15:27:55.867807  502007 join.go:426] failed to create cluster(member1). error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867827  502007 join.go:280] failed to create cluster object. cluster name: member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""
E0531 15:27:55.867840  502007 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": expected response.uid="c80156d3-23ff-403c-978f-ce3591cc495f", got ""`

**Comment by RainbowMango** [comment]
Have you deployed `karmada-webhook`?

**Comment by hellocloudnative** [comment]
I have deployed Karmada-Webhook
$  kubectl get pods  -n karmada-system
NAME                                               READY   STATUS    RESTARTS   AGE
etcd-0                                             1/1     Running   0          9m15s
karmada-apiserver-d445d4f75-w65tr                  1/1     Running   0          9m14s
karmada-controller-manager-bf8cc4f75-rdpgc         1/1     Running   0          8m55s
karmada-kube-controller-manager-77d8d4d78b-xj7zc   1/1     Running   0          8m56s
karmada-scheduler-779fd9c778-ts74w                 1/1     Running   0          8m54s
karmada-webhook-65fc87f89d-jjw5z                   1/1     Running   0          8m54s

**Comment by hellocloudnative** [comment]
@RainbowMango

**Comment by hellocloudnative** [comment]
I use   hack/local-up-karmada.sh

**Comment by RainbowMango** [comment]
Feel free to re-open it when you can reproduce it.
