### ISSUE TITLE
failed to apply manifests with resourceVersion should not be set on objects to be created

### ISSUE THREAD

**Issue by imsunv** [karmada-io/karmada#3903]
**Please provide an in-depth description of the question you have**:

I want to test karmada. but failed in first step.
i create ns in karmada host cluser, but failed to  propagation to the member.

➜  ~ k create ns demo                                                                                                                                                               
namespace/demo created
➜  ~ k get works.work.karmada.io -n karmada-es-k8s-test   
NAME                              APPLIED   AGE
demo-6654f4c4f6                   False     11s

Status:
  Conditions:
    Last Transition Time:  2023-08-05T13:18:00Z
    Message:               Failed to apply all manifests (0/1): resourceVersion should not be set on objects to be created
    Reason:                AppliedFailed
    Status:                False
    Type:                  Applied

it's a bug ? or  Is it a problem with my usage? 😊

**Environment**:
- Karmada version: 1.6
- Kubernetes version:  1.26
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Strange phenomenon, Karmada's E2E testing covers this use case. Can you show me the YAML file for the work you mentioned?

**Comment by imsunv** [comment]
It's really strange, too basic, and it makes me wonder if it's my own issue.  
I skip it just by set resourceVersion before create resource in the  execution_controller.go

`
		workload.SetResourceVersion("")
		err = c.ObjectWatcher.Create(clusterName, workload)
`

**Comment by XiShanYongYe-Chang** [comment]
Yes, the ResourceVersion field will be removed during the resource preparation process.

**Comment by lxtywypc** [comment]
Hi @imsunv   
Have you deployed `karmada-webhook` successfully?  
The `karmada-webhook` would remove the fields managed by `kube-controller-manager` of the resource template declared in `work.spec.workload.manifests`, and if the webhook not deployed successfully, these fields would be retained when creating/updating a `work`, that would cause the error you met.

**Comment by imsunv** [comment]
you are right, thanks for @lxtywypc  for help.
