### ISSUE TITLE
Adopters Path is broken

### ISSUE THREAD

**Issue by hrittikhere** [karmada-io/karmada#3918]
**What happened**:
For the https://github.com/karmada-io/karmada/blob/master/ADOPTERS.md, the list is broken with no reference to the adopters and the folder containing the image.

**What you expected to happen**:

As it's moved to this section: https://github.com/karmada-io/website/blob/main/docs/casestudies/adopters.md, we can remove this [file](https://github.com/karmada-io/karmada/blob/master/ADOPTERS.md) for cleaning the codebase and making sure things are managed well

**Comment by hrittikhere** [comment]
Maybe adding ref to the website repo is also good so open to suggestions

**Comment by RainbowMango** [comment]
> Maybe adding ref to the website repo is also good so open to suggestions

+1
/help

**Comment by RainbowMango** [comment]
@hrittikhere thanks for spotting, Let me know if you want to help with it.

**Comment by hrittikhere** [comment]
I can take this on and create a ref ✨

**Comment by RainbowMango** [comment]
/assign @hrittikhere 
Thanks.
