### ISSUE TITLE
Context naming 

### ISSUE THREAD

**Issue by theonlydoo** [karmada-io/karmada#392]
**What happened**:
Faulty context is returned by commands

**What you expected to happen**:
Context fetched from config file should be returned

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ karmada/hack/create-cluster.sh baremetal /root/standalone.yml 
kubeconfig file is existed, new config will append to it.
Creating cluster "baremetal" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Waiting ≤ 2m0s for control-plane = Ready ⏳ 
 • Ready after 30s 💚
Set kubectl context to "kind-baremetal"
You can now use your cluster with:

kubectl cluster-info --context kind-baremetal --kubeconfig /root/standalone.yml
```

```bash
$ kubectl cluster-info --context kind-baremetal --kubeconfig /root/standalone.yml
error: context "kind-baremetal" does not exist
```

**Anything else we need to know?**:
Thank's for developping such an ambitious tool :)

**Environment**:
- Karmada version: master
- Others: kubernetes 1.19.11

**Comment by RainbowMango** [comment]
Hi @theonlydoo Thanks for sharing feedback with us.

That because we have changed the context name here:
https://github.com/karmada-io/karmada/blob/bc7cfd8dc5bbfd629c918635fc455460d0f30408/hack/create-cluster.sh#L51-L53

There is no flag can define context when creating a cluster by kind:
```
# kind create cluster --help 
Creates a local Kubernetes cluster using Docker container 'nodes'

Usage:
  kind create cluster [flags]

Flags:
      --config string       path to a kind config file
  -h, --help                help for cluster
      --image string        node docker image to use for booting the cluster
      --kubeconfig string   sets kubeconfig path instead of $KUBECONFIG or $HOME/.kube/config
      --name string         cluster name, overrides KIND_CLUSTER_NAME, config (default kind)
      --retain              retain nodes for debugging when cluster creation fails
      --wait duration       wait for control plane node to be ready (default 0s)

Global Flags:
      --loglevel string   DEPRECATED: see -v instead
  -q, --quiet             silence all stderr output
  -v, --verbosity int32   info log verbosity
```

**Comment by RainbowMango** [comment]
Any idea to solve this issue? @theonlydoo 

Maybe we can suppress all outputs by `kind` and define ourselves output.

**Comment by lfbear** [comment]
It seems that kind will create cluster name, user name, and context name with the prefix 'kind-'. ([quick start
 of Kind](https://kind.sigs.k8s.io/docs/user/quick-start/#interacting-with-your-cluster)) Maybe we should not change the context name? with 'kind-'

**Comment by RainbowMango** [comment]
> Maybe we should not change the context name? with 'kind-'

That's an option.

**Comment by ikaven1024** [comment]
> There is no flag can define context when creating a cluster by kind:

@RainbowMango 
you can set cluster name in config file, using --config. 
FYI: https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster

**Comment by RainbowMango** [comment]
Hi @ikaven1024 Thanks. Here we are talking about is not the cluster name, but the `context` name, when creating the cluster we specified the cluster name by `--name` but kind will add the `kind-` prefix to the context name.

**Comment by RainbowMango** [comment]
@ikaven1024 I think we can do that but don't omit anything dumped from kind. 
Just giving the right prompt would be fine:
> echo kubectl cluster-info --context "${CLUSTER_NAME}" --kubeconfig "${KUBECONFIG}"

**Comment by RainbowMango** [comment]
Hi @ikaven1024 Are you going to send a PR for this?
/remove-kind bug
/kind cleanup
