### ISSUE TITLE
 Current client-go version (v0.26.1&v0.26.2) contains possible panic in discovery

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#3924]
**What happened**:

Possible panic when using client-go v0.26.0 - v0.26.3  for discovery.

client-go version for karmada:
- v1.5 ---v0.26.1
- v1.6 ---v0.26.3

kubernetes issue: https://github.com/kubernetes/kubernetes/issues/119840

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Panic can occur for

client-go v0.26.0 - v0.26.3
api server v1.27+

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
We have to update the client-go for release-1.5, right? Because release-1.5 now [using v0.26.1](https://github.com/karmada-io/karmada/blob/a53265c08f3393f1c11f3862ed03f24fded49422/go.mod#L36).

**Comment by liangyuanpeng** [comment]
>   We have to update the client-go for release-1.5, right? Because release-1.5 now [using v0.26.1](https://github.com/karmada-io/karmada/blob/a53265c08f3393f1c11f3862ed03f24fded49422/go.mod#L36).

Yes, let me update for release-1.5

**Comment by liangyuanpeng** [comment]
Closing by #3925 and #3930

**Comment by RainbowMango** [comment]
Many thanks to @liangyuanpeng for picking this.
/assign @liangyuanpeng
