### ISSUE TITLE
readme.md mismatch

### ISSUE THREAD

**Issue by theonlydoo** [karmada-io/karmada#393]
**What happened**:
readme says:

```
Local Karmada is running.
To start using your karmada, run:
  export KUBECONFIG=/var/run/karmada/karmada-apiserver.config
To start checking karmada components running status on the host cluster, please run:
  export KUBECONFIG="/root/.kube/karmada-host.config"
```

**What you expected to happen**:
```
$ cat /var/run/karmada/karmada-apiserver.config
cat: /var/run/karmada/karmada-apiserver.config: No such file or directory
```
```
$ kubectl config get-contexts
CURRENT   NAME                CLUSTER             AUTHINFO            NAMESPACE
*         karmada-apiserver   karmada-apiserver   karmada-apiserver   karmada-system
          karmada-host        kind-karmada-host   kind-karmada-host   
```

I'd like to recommend using the great [kubectx](https://github.com/ahmetb/kubectx) (also [kubens](https://github.com/ahmetb/kubectx/releases/download/v0.9.3/kubens_v0.9.3_linux_x86_64.tar.gz), from the same repo)

**How to reproduce it (as minimally and precisely as possible)**:
```
$ ./hack/local-up-karmada.sh 
```

**Comment by lfbear** [comment]
This bug has been fixed, please choose code from [master](https://github.com/karmada-io/karmada/tree/master) or [v0.6.0](https://github.com/karmada-io/karmada/tree/v0.6.0)

**Comment by RainbowMango** [comment]
> I'd like to recommend using the great kubectx (also kubens, from the same repo)

Good to know, just take a look at the two tools, that's sounds great!

How do you want to use it with karmada?

**Comment by theonlydoo** [comment]
I'd recommend it for the end user trying to switch context in karmada, since it [seems to appear](https://github.com/karmada-io/karmada/issues/399) that some context switching is needed. It's a bit easier than `kubectl config xx` commands
