### ISSUE TITLE
operator init operations may need bigger timeout

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/karmada#3935]
**What happened**:
When deploying Karmada using the operator, it's important to note that for the three components - karmada-etcd, karmada-apiserver, and karmada-aggregated-apiserver - their timeout is set to 30 seconds. In my environment (and even in most environments), if the images are not pre-pulled beforehand, the allotted time might not be sufficient. As a result, deployment could fail due to timeouts, necessitating the deletion of the Karmada resource before reattempting the deployment.
**What you expected to happen**:
Install success at once
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![83d4c1419dcaa875d2e74015433b0c5d](https://github.com/karmada-io/karmada/assets/19872346/efbb1ef3-6d0c-44b8-8505-60d8b0479914)
![0a71d6f83ce6c6e7d54441112e12d838](https://github.com/karmada-io/karmada/assets/19872346/a7f5cf1d-43fa-4ede-8fc8-1ed9ee49de43)
![7bf89d25c6f9cd31f726b821206899e9](https://github.com/karmada-io/karmada/assets/19872346/65d27f88-f33d-4017-8dee-a01cc28faa4e)
<img width="991" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/abeecb4c-73cf-4a06-86e7-6b36f70c5689">

**Comment by XiShanYongYe-Chang** [comment]
/cc @calvin0327 @Poor12 @lonelyCZ 
Hi, can you help take a look? Can we modify this time to be configurable?

**Comment by Vacant2333** [comment]
> Which version of karmadactl we are talking about? I remember we have introduced a flag(`--wait-component-ready-timeout`) for this:
> 
> ```shell
> -bash-5.0# karmadactl init --help 
> Install the Karmada control plane in a Kubernetes cluster.
> 
> Options:
>     --wait-component-ready-timeout=120:
> 	Wait for karmada component ready timeout. 0 means wait forever
> 
> Usage:
>   karmadactl init [options]
> 
> Use "karmadactl options" for a list of global command-line options (applies to all commands).
> ```
> 
> Please try with the karmadactl on master.

its install by operator, not karmadactl
https://github.com/karmada-io/karmada/blob/master/operator/README.md

**Comment by RainbowMango** [comment]
oh, sorry my bad.

**Comment by Vacant2333** [comment]
may we can update to 120s, i think its enough at most situations

**Comment by RainbowMango** [comment]
> may we can update to 120s, i think its enough at most situations

@Vacant2333 Can you show us which pieces of code we need to update? 
I agree that keeping the default timeout consistent between CLI/operator/chart.

**Comment by RainbowMango** [comment]
> I tend to separate pulling images from other installation operations, that is, pulling images first before performing other operations. And, user will get a install log like:

How to `separate pulling images`?

**Comment by Vacant2333** [comment]
> > I tend to separate pulling images from other installation operations, that is, pulling images first before performing other operations. And, user will get a install log like:
> 
> How to `separate pulling images`?

you can check my pr, there is 3 task need to be update

**Comment by chaosi-zju** [comment]
> > I tend to separate pulling images from other installation operations, that is, pulling images first before performing other operations. And, user will get a install log like:
> 
> How to `separate pulling images`?

This requires some exploration, simply thought, if it is just based on Kind, it can be done like this:

```shell
docker pull registry.k8s.io/etcd:3.5.9-0
kind load docker-image registry.k8s.io/etcd:3.5.9-0 --name karmada-host
```

But this is not a generic approach, for not all k8s is based on Kind, generic approach may need execute `crictl pull` on the node of  karmada-host, like:

```shell
docker exec -it karmada-host-control-plane bash
root@karmada-host-control-plane:/# crictl --debug pull registry.k8s.io/etcd:3.5.9-0   
DEBU[0000] get image connection                         
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:registry.k8s.io/etcd:3.5.9-0,Annotations:map[string]string{},},Auth:nil,SandboxConfig:nil,} 
DEBU[0078] PullImageResponse: &PullImageResponse{ImageRef:sha256:73deb9a3f702532592a4167455f8bf2e5f5d900bcc959ba2fd2d35c321de1af9,} 
Image is up to date for sha256:73deb9a3f702532592a4167455f8bf2e5f5d900bcc959ba2fd2d35c321de1af9
```

But this is just a bit of thinking and requires more exploration.
