### ISSUE TITLE
Fix Slow-Rate Attack bug

### ISSUE THREAD

**Issue by Rains6** [karmada-io/karmada#3945]
**What happened**:
In karmada, both ReadTimeout and WriteTimeout are not configured on the server, will lead to slow-rate attacks.

**What you expected to happen**:
Fix Slow-Rate Attack

**How to reproduce it (as minimally and precisely as possible)**:
eg：cmd/scheduler/app/scheduler.go line 209

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.7.0.alpha3
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
cc @zishen for help.

**Comment by zishen** [comment]
> cc @zishen for help.

ok

**Comment by zishen** [comment]
Yes, we do have this problem.
`slow attack` includes `slow post`,`slow headers` and `slow read`. One way to avoid this is to place restrictions on http requests.
 The k8s community is handled in the following way [here]( https://github.com/kubernetes/kubernetes/pull/103958) .
 I strongly recommend accepting this proposal.
@RainbowMango @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Hi @zishen You can assign this issue to yourself with the command `/assign`. 
I noticed that Kubernetes not only sets the `ReadTimeout` but also other values. When making modifications, we can consider setting all the necessary values comprehensively.

**Comment by zishen** [comment]
> Hi @zishen You can assign this issue to yourself with the command `/assign`. I noticed that Kubernetes not only sets the `ReadTimeout` but also other values. When making modifications, we can consider setting all the necessary values comprehensively.

ok,I'm gland to fix this bug.

/assign

**Comment by XiShanYongYe-Chang** [comment]
It seems that we don't need to sync it to the previous branch, I will update the label to cleanup
/kind cleanup
/remove-kind bug
