### ISSUE TITLE
Install operator by helm works bad

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/karmada#3956]
**Please provide an in-depth description of the question you have**:
Follow by  https://github.com/karmada-io/karmada/blob/master/operator/README.md#helm-install
and result:
<img width="1422" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/544f7bb5-1f08-44b7-a91a-6d984f3ae1c1">
seems like values.yaml missing `common`

**What do you think about this question?**:
after
`cd charts/karmada-operator`
`helm dependency build`
it will works.

we may need add `--dependency-update ` at the helm usage, it will be useful for first run

**Environment**:
- Karmada version: Latest
- Kubernetes version:
- Others:

**Comment by liangyuanpeng** [comment]
This PR is working for it https://github.com/karmada-io/karmada/pull/3856
