### ISSUE TITLE
karmada-search may crash due to `concurrent map read and map write`

### ISSUE THREAD

**Issue by tedli** [karmada-io/karmada#3960]
**What happened**:

`search` pod crashed, `fatal error: concurrent map read and map write`.

**What you expected to happen**:

If errors occurred, log detail, or if caused by concurrent map read and map write, add lock to avoid it.

**How to reproduce it (as minimally and precisely as possible)**:

No idea. :rofl:

**Anything else we need to know?**:

[search.log](https://github.com/karmada-io/karmada/files/12392927/search.log)

The log didn't point out exactly where caused this, it makes sense, because when we talk about concurrent map read and map write, it must be at least 2 place, reading or writing, so it's not caused by a particular line of code, it should be caused by some code happened at a same time.

https://github.com/karmada-io/karmada/blob/5f1664060f271de3a86a2416ea7eedf3990d919f/pkg/registry/search/storage/cache.go#L142-L159

My point of view is that, it may caused by line `152`, adding entry to annotations map, meanwhile other logic reading it, because `runtime.Object` is a reference, not a value.

**Environment**:
- Karmada version: v1.6.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
@tedli You are using v1.6.1, right?

**Comment by tedli** [comment]
> 

Yes.

**Comment by zishen** [comment]
From the log you provided, it seems that `goroutine 291924 [runnable]` and  `goroutine 291894 [running]` are operating  on the `annotations` map at the same time.

But I don't know what `goroutine 291924` does.

**Comment by tedli** [comment]
Hi @zishen ,
> You did two searches at the same time?

Did you mean two replicas of search deployment?

If so, no, only one replica.

**Comment by zishen** [comment]
> 

I mean the two searches request.
`httpserver` will enable multiple coroutines when processing requests.

**Comment by tedli** [comment]
Hi @zishen ,
> I mean the two searches request.

Maybe. This is my production setup, with front ui, so there may be multi request happens at same time.

By the way.
> But I don't know where goroutine 291924 comes from.

It seemed all goroutines were dumped, not only goroutines that caused this panic.
And I just guess it may caused by annotations map, but I'm not sure.
