### ISSUE TITLE
Add kubernetes event for Karmada Object

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#398]
**What would you like to be added**:
We should add enough events for karmada object state in controller-manager and scheduler.
**Why is this needed**:

controller

- [x] binding
- [x] cluster
- [x] execution
- [ ] mcs
- [ ] namespace
- [ ] propagationpolicy
- [ ] status

scheduler

- [ ] schedule

**Comment by RainbowMango** [comment]
Yes, you are right. Could you please add an agenda to the next meeting? Let's see where to start.
We can keep discussing this here.

**Comment by RainbowMango** [comment]
I wonder to know what kind of event would like to add.

**Comment by pigletfly** [comment]
such as controller-manager fails to reconcile a object(e.g. propagationpolicy), or scheduler fails to schedule

**Comment by RainbowMango** [comment]
Hi, what's the progress, and can we start now?

**Comment by pigletfly** [comment]
yes,I've created a task list.Then will do it one by one.

**Comment by RainbowMango** [comment]
Great! Looking forward to them.

**Comment by RainbowMango** [comment]
Any update? Do you need help? @pigletfly

**Comment by RainbowMango** [comment]
Hi @pigletfly 
Personally, I propose some events for `RB/CRB`. Please take a look.
```
const (
	eventReasonCleanupWorkFailed      = "CleanupWorkFailed"
	eventReasonSyncWorkFailed         = "SyncWorkFailed"
	eventReasonSyncWorkSucceed        = "SyncWorkSucceed"
	eventReasonAggregateStatusFailed  = "AggregateStatusFailed"
	eventReasonAggregateStatusSucceed = "AggregateStatusSucceed"
)
```

**Comment by RainbowMango** [comment]
Hi @wawa0210 
Could you design the event here before filing a PR? I'm afraid not all tasks listed on the issue really need report events.

**Comment by RainbowMango** [comment]
I guess we can reopen it once we get clear requirements.
/close
