### ISSUE TITLE
Documentation needed on propagationpolicies

### ISSUE THREAD

**Issue by theonlydoo** [karmada-io/karmada#399]
**What happened**:
```
$ kubectl create -f samples/nginx/propagationpolicy.yaml
error: unable to recognize "samples/nginx/propagationpolicy.yaml": no matches for kind "PropagationPolicy" in version "policy.karmada.io/v1alpha1
```
because of a context error:

```
 $ kubectx
✔ Switched to context "karmada-host".
 $  kubectl api-resources|rg propaga
 $ kubectx
✔ Switched to context "karmada-apiserver".
 $  kubectl api-resources|rg propaga
clusterpropagationpolicies        cpp          policy.karmada.io              false        ClusterPropagationPolicy
propagationpolicies               pp           policy.karmada.io              true         PropagationPolicy
```

**What you expected to happen**:
It's quite unclear to know when to use which context, is it possible to  have a summary table with what context is needed when/where? 
**How to reproduce it (as minimally and precisely as possible)**:
* use wrong context
* try and run a propagation policy creation

**Anything else we need to know?**:
Still a nice tool :)

**Comment by kevin-wangzefeng** [comment]
Thanks for your feedback. Will improve the document :)

**Comment by RainbowMango** [comment]
As mentioned at README:
The `karmada-apiserver` is the main kubeconfig to be used when interacting with karamda control plane, while `karmada-host` is only used for debugging karmada installation with host cluster

You don't need to care about `karmada-host`, unless the karmada components not working that you need to dig out.

**Comment by kevin-wangzefeng** [comment]
To have a quick answer here:
karmada-host is only used when you need to install/modify karmada components.
karmada-apiserver is the one you will use most often.

**Comment by theonlydoo** [comment]
thanks! I try and fill the documentation holes that I fall in sorry :)

**Comment by RainbowMango** [comment]
/close
We already have some documents at https://github.com/karmada-io/karmada/tree/master/docs/userguide.
Feel free to touch us if you need more.
