### ISSUE TITLE
`execution_controller` drop worker key

### ISSUE THREAD

**Issue by huiwq1990** [karmada-io/karmada#3999]
**What happened**:

When run e2e, the `karmadactl_test` unjoin case is failed which caseed by the `execution_controller`. The controller may drop the worker key,  and the controller could not remove the worker's finalizeer. After we restart `karmada-controller-manager`, the cluster 
is successfully deleted.

```
I0825 01:05:15.726234       1 execution_controller.go:183] Begin to sync work karmada-es-member2/karmadatest-56qnd-644999d4cf
I0825 01:05:15.726486       1 execution_controller.go:183] Begin to sync work karmada-es-member2/karmadatest-ckpjw-555559d95d
I0825 01:05:15.726237       1 execution_controller.go:183] Begin to sync work karmada-es-member2/karmadatest-xwtk6-7c8b8cf6f7
I0825 01:05:15.728635       1 execution_controller.go:183] Begin to sync work karmada-es-member2/karmadatest-nqf62-6cd8978c86
I0825 01:05:15.731557       1 worker.go:127] Dropping resource "karmada-es-member2/karmadatest-ckpjw-555559d95d" out of the queue: cluster(member2) not ready
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by lxtywypc** [comment]
It is a known problem, as mentioned in https://github.com/karmada-io/karmada/issues/3959.

**Comment by XiShanYongYe-Chang** [comment]
Hi @huiwq1990 We have already rolled back the relevant PR, so there is no longer this issue. 

Next, we will prioritize handling #3959. If you are interested, you are also welcome to participate in the discussion about the problem.

/close
