### ISSUE TITLE
karmadactl could give a bit more informations

### ISSUE THREAD

**Issue by theonlydoo** [karmada-io/karmada#400]
**What would you like to be added**:
so far, karmadactl provides join/unjoin features. Could it provide some information dump as well ?

**Why is this needed**:
It's counter intuitive to run kubectl get cluster while karmadactl is in the mix

**Comment by theonlydoo** [comment]
another tangible example would be to karmadactl get nodes cross clusters

**Comment by RainbowMango** [comment]
Hi @theonlydoo 
We introduced the kubectl plugin `kubectl-karmada`, you can use  it to get resources across clusters, e.g.
```
kubectl karmada get xxx
```

And the [karmada-aggregate-apiserver](https://github.com/karmada-io/karmada/discussions/1077) provide the REST API to access member clusters from Karmada control plane.

**Comment by RainbowMango** [comment]
/close
Feel free to re-open it if you want further discussion.
