### ISSUE TITLE
help wanted for document about karmadactl register

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4001]
**Please provide an in-depth description of the question you have**:

much appreciate for improving documentation about [karmadactl register](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_register) ~

- [ ] where is the `token` from ?
- [ ] why we need `CACertHashes` ?

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by chaosi-zju** [comment]
![image](https://github.com/karmada-io/karmada/assets/30589999/09964a37-0fd5-4203-8a21-dca13927c87b)

A confusing token pattern, which is not a common kubernetes token.

I stuck in fetching the token, the register step is over before it even starts (((;꒪ꈊ꒪;)))

**Comment by JadeFlute0127** [comment]
You can run the following command on your Karmadactl control surface: 
`karmadactl token create --print register command --kubeconfig/etc/karmada/karmada apiserver.com`
You will receive the token you want and the command line that needs to be run to join the Karmada cluster

**Comment by JadeFlute0127** [comment]
It seems that you are not quite familiar with the operating principle of Karmada and the mode of managing clusters. The documentation here may provide some help.

https://karmada.io/zh/docs/userguide/clustermanager/cluster-registration#overview-of-cluster-mode

**Comment by JadeFlute0127** [comment]
Did the above answer solve your problem? Maybe this issue can be closed?

**Comment by chaosi-zju** [comment]
> You can run the following command on your Karmadactl control surface: `karmadactl token create --print register command --kubeconfig/etc/karmada/karmada apiserver.com` You will receive the token you want and the command line that needs to be run to join the Karmada cluster.
> 
> like this : `karmadactl register 10.10.x.x:32443 --token t2jgtm.9nybj0526mjw1jbf --discovery-token-ca-cert-hash sha256:f5a5a43869bb44577dba582e794c3e3750f2050d62f1b1dc80fd3d6a371b6ed4`

Thank you very much!

**Comment by chaosi-zju** [comment]
I see your response just now, I am trying~

by the way, can you explain why we need `CACertHashes` ?

**Comment by JadeFlute0127** [comment]
> I see your response just now, I am trying~
> 
> by the way, can you explain why we need `CACertHashes` ?

In my opinion， accessing karmada-apiserver requires permission, CACertHashes is the certificate of access permission.

**Comment by JadeFlute0127** [comment]
> ```
> karmadactl token create --print-register-command --kubeconfig /etc/karmada/karmada-apiserver.config
> ```
> 
> I wanna, if there are multi context/cluster in `/etc/karmada/xxx.config`, how did `karmadactl` handle it ? Or, we must seperate the `kubeconfig` of `karmada-apiserver` to single file?

Kubectl can specify the cluster context through the context option to determine which cluster to communicate with.

Of course, dividing them into separate config files is also a feasible method

**Comment by chaosi-zju** [comment]
> Kubectl can specify the cluster context through the context option to determine which cluster to communicate with.

So, you mean karmadactl select context according to `current-context` of the kubeconfig?

**Comment by chaosi-zju** [comment]
> In my opinion， accessing karmada-apiserver requires permission, CACertHashes is the certificate of access permission.

Can I bother you about how to fetch this `CACertHashed`, I see the doc your provided didn't refered~

**Comment by chaosi-zju** [comment]
Thanks for the great help from @JadeFlute0127 ! 

/close

**Comment by chaosi-zju** [comment]
> **- [ ] why we need CACertHashes ?**

1. karmadactl use `token`+`InsecureSkipTLSVerify` to fetch `ConfigMap/cluster-info` from control-plane.

2. karmadactl pick `CA cert` of control-plane from `ConfigMap/cluster-info`.

3. If `CACertHashes` user specified match to `CA cert` of control-plane, it is secure, otherwise not secure.

***

**What is the relation between `CA cert` and `CACertHashes ` ?**

`CACertHashes` is the sha256 abstract of the Subject Public Key Information (SPKI) filed in `CA cert`.

Convert `CA cert` to `CACertHashes`: 

```console
openssl x509 -noout -pubkey -in /etc/karmada/pki/ca.crt | openssl pkey -pubin -outform der | sha256sum
```
