### ISSUE TITLE
documentation suggestions

### ISSUE THREAD

**Issue by theonlydoo** [karmada-io/karmada#401]
**What would you like to be added**:
* Add a disclaimer that the currently described process in README is creating kind clusters instances where the nginx deployment example will be deployed
* Add a comprehensible example of a kind-karmada managing two existing clusters
* Maybe split documentation in different use cases where you can follow the example with kind and then go further in some other pages and deploy karmada on your Kubernetes clusters.

**Why is this needed**:
After trying karmada, it has an aftertaste of "something's missing" :)

**Comment by RainbowMango** [comment]
Thanks, @theonlydoo and @leonharetd .

**Comment by RainbowMango** [comment]
Thanks again for giving us the feedback, In the past release, we have been writing the docs, and now it is available at karmada.io, still working on it though. 

Still looking forward to hearing more concrete suggestions.
/close
