### ISSUE TITLE
failed to install low version karmadactl by "export INSTALL_CLI_VERSION=1.3.0 "

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4012]
**What happened**:

I want to install low version `karmadactl` following the [doc](https://karmada.io/docs/installation/install-cli-tools)：

![image](https://github.com/karmada-io/karmada/assets/30589999/d633c871-1624-4372-87dd-7bb66c3b47a4)

but no effect, it yet installed latest version `karmadactl`:

```shell
➜  karmada git:(dev) ✗ export INSTALL_CLI_VERSION=1.3.0                                                                   
➜  karmada git:(dev) ✗ curl -s https://raw.githubusercontent.com/karmada-io/karmada/master/hack/install-cli.sh | sudo bash
sudo: unable to resolve host node1: Name or service not known
[INFO]  Downloading metadata https://api.github.com/repos/karmada-io/karmada/releases/latest
[INFO]  Using 1.6.2 as release
[INFO]  Downloading hash https://github.com/karmada-io/karmada/releases/download/v1.6.2/karmadactl-linux-amd64.tgz.sha256
[INFO]  Downloading binary https://github.com/karmada-io/karmada/releases/download/v1.6.2/karmadactl-linux-amd64.tgz
[INFO]  Verifying binary download
[INFO]  Installing karmadactl to /usr/local/bin/karmadactl
mv: overwrite '/usr/local/bin/karmadactl'? #  
```

**What you expected to happen**:

low version `karmadactl` should be installed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by whitewindmills** [comment]
@chaosi-zju
`bash` starts a new shell to execute the `install-cli.sh` script, that causes `INSTALL_CLI_VERSION` to be invisible to it. so this is a documentation error, you can use the following command:
```shell
curl -s https://raw.githubusercontent.com/karmada-io/karmada/master/hack/install-cli.sh | sudo INSTALL_CLI_VERSION=1.3.0 bash
```
outputs:
![image](https://github.com/karmada-io/karmada/assets/89241565/1f65bec6-2b0b-4950-9031-3faa88072f91)

**Comment by chaosi-zju** [comment]
You are absolutely right, thank you very much~
