### ISSUE TITLE
replicaschedulingpolicy  Don't take effect

### ISSUE THREAD

**Issue by hellocloudnative** [karmada-io/karmada#402]
**What happened**:
```shell
$ kubectl config use-context karmada-apiserver
$ kubectl create -f deployment.yaml
$ kubectl create -f propagationpolicy_simple.yaml
$ kubectl create -f replicaschedulingpolicy_simple.yaml
```
propagationpolicy_simple.yaml
```shell
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: example-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
```
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

replicaschedulingpolicy_simple.yaml
```
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: foo
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  totalReplicas: 30
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [member1]
        weight: 1
      - targetCluster:
          clusterNames: [member2]
        weight: 2
```
```
$  kubectl config use-context member1
Switched to context "member1".
$ kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   10/10   10           10          2m50s
$ kubectl config use-context member2
Switched to context "member2".
$kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   10/10   10           10          2m57s
```

**What you expected to happen**:
member1   10    pod
member2   20   pod

**Anything else we need to know?**:

**Environment**:
- Karmada version: v0.6
- Others:  kubernetes 1.21.1

**Comment by RainbowMango** [comment]
cc @mrlihanbo

**Comment by garfcat** [comment]
The ReplicaSchedulingPolicy  does not set default namespace for resource selector,  so can not match any ReplicaSchedulingPolicy when ensure work.


`unc getMatchedReplicaSchedulingPolicy(policies []v1alpha1.ReplicaSchedulingPolicy, resource *unstructured.Unstructured) []v1alpha1.ReplicaSchedulingPolicy {
    ....
	for _, policy := range policies {

                **_//  namespace is not the same_**

		if util.ResourceMatchSelectors(resource, policy.Spec.ResourceSelectors...) {
			resourceMatches = append(resourceMatches, policy)
		}
	}
   ....
	return resourceMatches
}`

**Comment by RainbowMango** [comment]
@garfcat right, that probably the reason.
Maybe we can update the match rules like :
```diff
diff --git a/pkg/util/selector.go b/pkg/util/selector.go
index 5f82fb2..0b4dee9 100644
--- a/pkg/util/selector.go
+++ b/pkg/util/selector.go
@@ -17,7 +17,7 @@ import (
 func ResourceMatches(resource *unstructured.Unstructured, rs v1alpha1.ResourceSelector) bool {
        if resource.GetAPIVersion() != rs.APIVersion ||
                resource.GetKind() != rs.Kind ||
-               resource.GetNamespace() != rs.Namespace {
+               (len(rs.Namespace) > 0 && resource.GetNamespace() != rs.Namespace) {
                return false
        }
```

@garfcat would you like to fix it?

**Comment by garfcat** [comment]
> @garfcat right, that probably the reason.
> Maybe we can update the match rules like :
> 
> ```diff
> diff --git a/pkg/util/selector.go b/pkg/util/selector.go
> index 5f82fb2..0b4dee9 100644
> --- a/pkg/util/selector.go
> +++ b/pkg/util/selector.go
> @@ -17,7 +17,7 @@ import (
>  func ResourceMatches(resource *unstructured.Unstructured, rs v1alpha1.ResourceSelector) bool {
>         if resource.GetAPIVersion() != rs.APIVersion ||
>                 resource.GetKind() != rs.Kind ||
> -               resource.GetNamespace() != rs.Namespace {
> +               (len(rs.Namespace) > 0 && resource.GetNamespace() != rs.Namespace) {
>                 return false
>         }
> ```
> 
> @garfcat would you like to fix it?

sure  , the most direct way is to modify it like this

**Comment by RainbowMango** [comment]
/assign @garfcat 
Thanks~~~

**Comment by RainbowMango** [comment]
Hi @hellocloudnative 
@garfcat sent a PR fixed the case, can you help confirm if it works for you?

**Comment by hellocloudnative** [comment]
我可以提交一个上游嘛，给我一个机会。

**Comment by hellocloudnative** [comment]
I can submit upstream. Give me a chance
thank you

**Comment by RainbowMango** [comment]
> I can submit upstream. Give me a chance
> thank you

Sure, since this task has been done, I can reserve a `good-first` issue for you. Hold on, I will cc you on a new issue.
