### ISSUE TITLE
A confusing event "No policy match for resource"

### ISSUE THREAD

**Issue by wu0407** [karmada-io/karmada#4038]
**Please provide an in-depth description of the question you have**:
 The karmada controller `ResourceDetector` watch all resource and try to find a policy that matches this resource. If resources do not match any policy then it sends a "ApplyPolicyFailed" and "No policy match for resource" event for this resource.
That event made me confused, Is there any problem with this resource?

https://github.com/karmada-io/karmada/blob/5a583c2c9f53ad726a941c620e1031b4b3f8af9c/pkg/detector/policy.go#L77-L82

**What do you think about this question?**:
If no policy matches this resource there is no need to send an event.

**Environment**:
- Karmada version: 1.6.2
- Kubernetes version: v1.23
- Others:

**Comment by RainbowMango** [comment]
I think it's unnecessary for this place to emit a `negative event(Warning)`, it's pretty common that a `resource template` is applied ahead of a `PropagationPolicy`, a warning event probably panics users.

Once the `resource template` has been propagated by a PropagationPolicy, there would be [a positive event](https://github.com/karmada-io/karmada/blob/5a583c2c9f53ad726a941c620e1031b4b3f8af9c/pkg/detector/detector.go#L387), and for exceptions, there would be another event(`ApplyPolicyFailed`).

So my opinion is just remove this line, like:
```diff
diff --git a/pkg/detector/policy.go b/pkg/detector/policy.go
index 801520236..5be5a540a 100644
--- a/pkg/detector/policy.go
+++ b/pkg/detector/policy.go
@@ -5,7 +5,6 @@ import (
        "fmt"
        "time"

-       corev1 "k8s.io/api/core/v1"
        apierrors "k8s.io/apimachinery/pkg/api/errors"
        "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
        "k8s.io/apimachinery/pkg/labels"
@@ -15,7 +14,6 @@ import (

        policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
        workv1alpha2 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha2"
-       "github.com/karmada-io/karmada/pkg/events"
        "github.com/karmada-io/karmada/pkg/metrics"
        "github.com/karmada-io/karmada/pkg/util"
        "github.com/karmada-io/karmada/pkg/util/fedinformer/keys"
@@ -75,8 +73,6 @@ func (d *ResourceDetector) propagateResource(object *unstructured.Unstructured,
        }

        if d.isWaiting(objectKey) {
-               // reaching here means there is no appropriate policy for the object
-               d.EventRecorder.Event(object, corev1.EventTypeWarning, events.EventReasonApplyPolicyFailed, "No policy match for resource")
                return nil
        }
```

@wu0407 Does that make sense? Would you like to send a PR for it?

**Comment by wu0407** [comment]
I will do later

**Comment by RainbowMango** [comment]
OK. Thanks. no rush. 
/assign @wu0407
