### ISSUE TITLE
Allow member cluster operators to modify resources propagated through Karmada

### ISSUE THREAD

**Issue by yelshall** [karmada-io/karmada#4067]
**Please provide an in-depth description of the question you have**:
## Setup
The current Karmada setup I have is as follows:
- Karmada cluster deployed on a host cluster
- One member cluster registered in push mode
- An operator is deployed on the member cluster that manages certain custom resources. The operator was deployed on the member cluster before the Karmada cluster was installed.

I deployed the CRD for the custom resource on the Karmada cluster and created a propagationPolicy for the custom resource to be propagated to the member cluster. 
## Test
I deployed a custom resource through the Karmada cluster for it to be propagated to the member cluster.

### Expectation
- Custom resource should be modified by the operator in the member cluster accordingly.

### Result
- Custom resource is modified by the operator in the member cluster.
- However, Karmada control plane recognizes the difference between the member cluster resource and the resource template deployed on the Karmada cluster and changes it back to the original state.

**What do you think about this question?**:
Considering the situation above, what are ways that we can have operators on the member cluster modify resources without the Karmada cluster reconciling the resource back to the original state?

Solutions that were explored:
- `conflictResolution` label: that does not work because this label is for when the deployment already exists in the member cluster.

Would modifying the [resource interpreter options ](https://github.com/karmada-io/karmada/blob/84b971a501ba82c53a5ad455c2fe84d842cd7d4e/pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go#L103-L105) help in this case?
**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.26.7
- Others: n/a

**Comment by XiShanYongYe-Chang** [comment]
Hi @yelshall , thanks for your feedback.

> Would modifying the [resource interpreter options ](https://github.com/karmada-io/karmada/blob/84b971a501ba82c53a5ad455c2fe84d842cd7d4e/pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go#L103-L105)help in this case?

Yes, you can use the resource interpreter to achieve your desired goals.

The Retain operation provided by the resource interpreter can retain some information of the member cluster during the process of controlling updates to the member cluster, and this behavior can be extended by users.

There are relevant introduction documents here:
https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#customized-interpreter

**Comment by RainbowMango** [comment]
> Would modifying the [resource interpreter options ](https://github.com/karmada-io/karmada/blob/84b971a501ba82c53a5ad455c2fe84d842cd7d4e/pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go#L103-L105)help in this case?

The resource interpreter's 'Retain' hook is designed for this case.
