### ISSUE TITLE
Enable preemption feature in development environment

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4068]
**Task description**:

The [PropagationPolicyPreemption feature gate](https://github.com/karmada-io/karmada/blob/5c77f4516eb9c27c0ce38ed25a389ab9e56d8122/pkg/features/features.go#L22-L23) was introduced in release 1.7, now is [disabled by default](https://github.com/karmada-io/karmada/blob/5c77f4516eb9c27c0ce38ed25a389ab9e56d8122/pkg/features/features.go#L36), now it's time to enable it in development environment that launched by `hack/local-up-karmada.sh`.

**Solution**:

```diff
$ git diff 
diff --git a/artifacts/deploy/karmada-controller-manager.yaml b/artifacts/deploy/karmada-controller-manager.yaml
index efa296499..67d0f14be 100644
--- a/artifacts/deploy/karmada-controller-manager.yaml
+++ b/artifacts/deploy/karmada-controller-manager.yaml
@@ -30,6 +30,7 @@ spec:
             - --cluster-status-update-frequency=10s
             - --secure-port=10357
             - --failover-eviction-timeout=30s
+            - --feature-gates=PropagationPolicyPreemption=true
             - --v=4
           livenessProbe:
             httpGet:
```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by codrAlxx** [comment]
I would love to work on this issue and contribute.

**Comment by RainbowMango** [comment]
Thanks @codrAlxx.

**Comment by codrAlxx** [comment]
Hello @RainbowMango, could you please check and let me know if you have any comments? I would love to contribute further.
