### ISSUE TITLE
karmadactl cant init when i follow the user guide

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/karmada#4073]
**What happened**:
i cant init by the user guide
<img width="948" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/bfe516d6-e829-4aa3-80fc-5d377f04e84f">

<img width="1440" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/c1f1c9f3-4dc8-4068-97ff-9a442d3d3d09">

**What you expected to happen**:
init the karmada

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
may the karmadactl or the docs need update, i must specify the crd files

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by Vacant2333** [comment]
<img width="1440" alt="image" src="https://github.com/karmada-io/karmada/assets/19872346/648c3903-d0fd-414a-b5f1-9207bc0b940d">
and looks like i must specify  the default image, else it will be xxxx:<nil>

**Comment by RainbowMango** [comment]
> and looks like i must specify the default image, else it will be xxxx:

I guess you are using a self-built version of `karmadactl`, if it is the case you have to specify the image for each component.

If you are using the official release of `karmadactl`, each component has a default image version.
```
    --karmada-controller-manager-image='docker.io/karmada/karmada-controller-manager:v1.7.0':
	Karmada controller manager image
```

**Comment by Vacant2333** [comment]
> > and looks like i must specify the default image, else it will be xxxx:
> 
> I guess you are using a self-built version of `karmadactl`, if it is the case you have to specify the image for each component.
> 
> If you are using the official release of `karmadactl`, each component has a default image version.
> 
> ```
>     --karmada-controller-manager-image='docker.io/karmada/karmada-controller-manager:v1.7.0':
> 	Karmada controller manager image
> ```

yes 😂 when I realized that, i close the issue
