### ISSUE TITLE
Have to manually remove the karmadactl in order to update

### ISSUE THREAD

**Issue by Affan-7** [karmada-io/karmada#4091]
**What happened**:
I already had the karmadactl v1.6.2 installed. I tried to update it using this [one click installation method](https://karmada.io/docs/installation/install-cli-tools#one-click-installation). Because I already had the karmadactl installed the script exited after this message `mv: overwrite '/usr/local/bin/karmadactl'?`. It didn't allowed to specify whether to overwrite the file or not.

**What you expected to happen**:
It should update the karmadactl by force moving the karmadactl binary.

**How to reproduce it (as minimally and precisely as possible)**:
Run the command twice specified in the  [one click installation method](https://karmada.io/docs/installation/install-cli-tools#one-click-installation).

**Suggestion**:
We should remove the `-i` flag for the `mv` command and add the `-f` flag, because it's highly unlikely that it will cause problems by accidental overwrites.

**Comment by Yan-Daojiang** [comment]
I think this is because the pipe (|) redirects the script's standard input to the pipe's output, which can cause some interactive commands (like mv) to not work correctly because they cannot read user input from the terminal.

**Comment by Yan-Daojiang** [comment]
I think you can save it as a shell script using curl and then run it through bash, or you can directly clone the repository and then use `sudo bash hack/install-cli.sh` to install. This will make the interactive installation work.

**Comment by Yan-Daojiang** [comment]
`-f` might lead to direct overwriting, if need it to be interactive,  redirect the standard input of the `mv` command to `/dev/tty`. I'm a newbie to karmada and I've started a small PR to fix this issue.

**Comment by RainbowMango** [comment]
/assign @Yan-Daojiang 
In favor of #4092 

/remove-kind bug
/kind cleanup
