### ISSUE TITLE
karmadactl adds the unregister command to delete pull mode clusters

### ISSUE THREAD

**Issue by yanfeng1992** [karmada-io/karmada#4102]
**What would you like to be added**:

Can a command be added to karmadactl, such as unregister, to delete the pull mode cluster?

I think this command needs to have the following functionality

1. unregister is executed on the pull cluster
2. delete the cluster object in the karmada control plane
3. delete related resources on the pull cluster

**Why is this needed**:

There is no good way to unmanage the cluster in pull mode.

**Comment by Affan-7** [comment]
https://karmada.io/docs/next/userguide/clustermanager/cluster-registration/#unregister-cluster

I hope this will help.

**Comment by yanfeng1992** [comment]
What do you think about this problem? Do we need to provide a cli to execute on the member to implement unjoin of the pull cluster?
Now in our environment, the unjoin of the pull cluster is implemented in this way
step1: Delete the cluster object in hub karmada on member
step2: Undeploy the karmada-agent

cc @RainbowMango @lonelyCZ

**Comment by lonelyCZ** [comment]
> unregister is executed on the pull cluster
> delete the cluster object in the karmada control plane

It could need `delete` Cluster permission in pull cluster, which seems not secure.
