### ISSUE TITLE
Why we drop the singleton kubeconfig file and turn to context

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#411]
**What would you like to be added**: 
After the version 0.6.0, we change original behavior, to add `context` to kube config file rather than generate a standalone one.

That's make a mass. 
I like to open 3 terminal each for `karmade host`, `karmade api-server` and `member`
but with `context`, when I switch `context` in one terminal, all changed, that's really mass me.

**Why is this needed**:

**Comment by XiShanYongYe-Chang** [comment]
I have the same doubts, and I use alias like this to resolve the mass:
```
alias kh='kubectl config use-context karmada-host;kubectl'
alias kk='kubectl config use-context karmada-apiserver;kubectl'
alias km1='kubectl --kubeconfig /root/.kube/member1.config '
alias km2='kubectl --kubeconfig /root/.kube/member2.config '
```

**Comment by RainbowMango** [comment]
@vincent-pli any comments or can we close this issue now?

**Comment by vincent-pli** [comment]
Sure
