### ISSUE TITLE
make verify cmd failed

### ISSUE THREAD

**Issue by gy95** [karmada-io/karmada#412]
**What happened**:
run `make verify` cmd failed, the generated codes output packge is not correct. 
the reason is that `make verify` cmd will first generate needed codes using scripts `verify-codegen.sh` and `verify-crdgen.sh`, and then static check codes using script `verify-staticcheck.sh`. When generating codes using cmd `deepcopy-gen XXXXXX --output-package=github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1`, generated codes output dir is wrong. 

And the output package rule is as follows:
`-o, --output-base string               Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/home/xxx/src/go/`
if we dont set `GOPATH` first, the output package will be `./` so the following code static check will fail.

So we should Set `GOPATH` before verify codes.

**What you expected to happen**:
cmd succeed
**How to reproduce it (as minimally and precisely as possible)**:
just run `make verify`
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
Does this still necessary since we have added the `GOPATH`?
https://github.com/karmada-io/karmada/blob/bd0d3b8a0c80c776f725909623adec4dea09687c/hack/update-codegen.sh#L13

**Comment by gy95** [comment]
> GOPATH=$(go env GOPATH | awk -F ':' '{print $1}')

we should export variable `GOPATH`, I try executing cmd without export variable `GOPATH` and it is failed also

**Comment by RainbowMango** [comment]
Set `GOPATH` is a mandatory prerequisite. I can't reproduce on my side.
Can you help share more details reproduce steps?

**Comment by gy95** [comment]
> Set `GOPATH` is a mandatory prerequisite. I can't reproduce on my side.
> Can you help share more details reproduce steps?

`-o, --output-base string Output base; defaults to $GOPATH/src/ or ./ if $GOPATH is not set. (default "/home/xxx/src/go/`

on my machine, `GOPATH` doesn't exist in env variables(file `/etc/profile`), so `make verify` will fail, And after i run this command `export GOPATH=/root/go`, `make verify` succeed.

So we should export `GOPATH` env variable in our source codes

**Comment by gy95** [comment]
And according to the golang official docs, https://golang.org/doc/install, Set `GOPATH` as env variable is not enforced
