### ISSUE TITLE
kubectl karmada unjoin cluster failed with arg --cluster-kubeconfig

### ISSUE THREAD

**Issue by AndyEWang** [karmada-io/karmada#4120]
**Please provide an in-depth description of the question you have**:

Refer to doc https://karmada.io/zh/docs/userguide/clustermanager/cluster-registration#unregister-cluster-by-cli to unjoin a cluster but **failed**.

```
# kubectl karmada unjoin test --kubeconfig karmada-apiserver.conf --cluster-kubeconfig cluster.kubeconfig
error: context "test" does not exist
```

It succeeds without --cluster-kubeconfig.
```
# kubectl karmada unjoin test --kubeconfig karmada-apiserver.conf
I1011 01:53:45.846310    7578 unjoin.go:235] Waiting for the cluster object test to be deleted
I1011 01:53:46.845749    7578 unjoin.go:235] Waiting for the cluster object test to be deleted
I1011 01:53:47.845285    7578 unjoin.go:235] Waiting for the cluster object test to be deleted
I1011 01:53:48.846477    7578 unjoin.go:235] Waiting for the cluster object test to be deleted
I1011 01:53:49.845573    7578 unjoin.go:235] Waiting for the cluster object test to be deleted
```

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: 1.22
- Others:

**Comment by RainbowMango** [comment]
Hi @AndyEWang Thanks for spotting. 

> error: context "test" does not exist

This output shows that the context named `test` does not exist. 

Could you please help to show the content of the `cluster.kubeconfig` to confirm the `test` context?
You can get the content by :
```
$ kubectl config view --kubeconfig=./cluster.kubeconfig   # please confirm the file path.
```

**Comment by AndyEWang** [comment]
I use the default kubernetes admin config. 
```
# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED

```

**Comment by RainbowMango** [comment]
After going through the code, the root cause is that the `unjoin` command will take the cluster name as the default context:
https://github.com/karmada-io/karmada/blob/8e5f192bf816c7e5cc1d6b2fbf64047cc54247ab/pkg/karmadactl/unjoin/unjoin.go#L106-L109

So, could you please set another flag `--cluster-context=kubernetes-admin@kubernetes` and have a try?

**Comment by AndyEWang** [comment]
@RainbowMango it works with --cluster-context=kubernetes-admin@kubernetes. Thanks.
BTW, can we only use --kubeconfig to unjoin a cluster? Or --cluster-kubeconfig must be given?

**Comment by RainbowMango** [comment]
> BTW, can we only use --kubeconfig to unjoin a cluster? Or --cluster-kubeconfig must be given?

Yes, you can just specify `--kubeconfig`, actually `--cluster-kubeconfig` is an optional flag, but if it is specified, the `unjoin` could clean up more resources that were created during the `join` process.

As mentioned by https://karmada.io/docs/userguide/clustermanager/cluster-registration/: 

> And the --cluster-kubeconfig is used to clean up the secret created at the join phase.
