### ISSUE TITLE
How to use _crds in helm charts

### ISSUE THREAD

**Issue by huangyutongs** [karmada-io/karmada#4126]
**Please provide an in-depth description of the question you have**:
How to install the chart crds resource in the warehouse https://github.com/karmada-io/karmada/tree/master/charts/karmada
After deploying karmada through this chart and joining the cluster, it prompts that there are no clusters resources.
![image](https://github.com/karmada-io/karmada/assets/48778924/0481e8cd-ac6c-4992-bddd-9592ba39cf13)

**Environment**:
- Karmada version:  v1.7.0
- Kubernetes version:  v1.24.2
- Others:

**Comment by RainbowMango** [comment]
Can you help to confirm if Karmada has been successfully installed? You can do that by checking if all components are running.

Karmada components will be installed in `karmada-system` namespaces, you can check them by:
```
$ kubectl get deployments -n karmada-system --kubeconfig=<remember to use the kubeconfig for `host` cluster>
```

**Comment by huangyutongs** [comment]
hi,Karmada installed successfully, but I seem to have missed all the crds
![image](https://github.com/karmada-io/karmada/assets/48778924/6c1f5354-d5ea-4d4e-b5b2-1f374d30491e)

**Comment by huangyutongs** [comment]
> Can you help to confirm if Karmada has been successfully installed? You can do that by checking if all components are running.
> 
> Karmada components will be installed in `karmada-system` namespaces, you can check them by:
> 
> ```
> $ kubectl get deployments -n karmada-system --kubeconfig=<remember to use the kubeconfig for `host` cluster>
> ```

Karmada installed successfully, but I seem to have missed all the crds
![image](https://github.com/karmada-io/karmada/assets/48778924/93a0ff95-6883-4892-a62b-54e33c0cbd81)

**Comment by huangyutongs** [comment]
> Can you help to confirm if Karmada has been successfully installed? You can do that by checking if all components are running.
> 
> Karmada components will be installed in `karmada-system` namespaces, you can check them by:
> 
> ```
> $ kubectl get deployments -n karmada-system --kubeconfig=<remember to use the kubeconfig for `host` cluster>
> ```
hi, Karmada installed successfully, but I seem to have missed all the crds
![image](https://github.com/karmada-io/karmada/assets/48778924/b6f73537-9f5c-457b-af1b-0ebca47c350e)

**Comment by RainbowMango** [comment]
> hi, Karmada installed successfully, but I seem to have missed all the crds

No, please confirm if you are using the right kubeconfig on the above `karmadactl join xxx --kubeconfig=`, the kubeconfig should be Karmada. 

You can do that by:
```
$ kubectl config view --kubeconfig=/root/.kube/config
```

**Comment by huangyutongs** [comment]
> > hi, Karmada installed successfully, but I seem to have missed all the crds
> 
> No, please confirm if you are using the right kubeconfig on the above `karmadactl join xxx --kubeconfig=`, the kubeconfig should be Karmada.
> 
> You can do that by:
> 
> ```
> $ kubectl config view --kubeconfig=/root/.kube/config
> ```
Thank you very much for the tip, I neglected to get the kubeconfig of karmada and used the kubeconfig of the host cluster,
```kubectl get secret -n karmada-system karmada-kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d```

**Comment by huangyutongs** [comment]
@RainbowMango There is another question. I have to add host resolution to connect to karmada apiserver. Is there any other method?
```
cat /etc/hosts
10.43.41.61 karmada-apiserver.karmada-system.svc.cluster.local
```

**Comment by RainbowMango** [comment]
Do you mean you want to expose the service of `karmada apiserver` outside the host cluster, so that you can access it from, for example, your host machine? 
If yes, it is exactly similar to exposing a Kubernetes service, you can do that by leveraging for example Load Balancer.

**Comment by huangyutongs** [comment]
> Do you mean you want to expose the service of `karmada apiserver` outside the host cluster, so that you can access it from, for example, your host machine? If yes, it is exactly similar to exposing a Kubernetes service, you can do that by leveraging for example Load Balancer.

ok i know what to do
