### ISSUE TITLE
operator/config/samples/karmada.yaml may be not valid

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4128]
**What happened**:

When installing karmada by operator, karmada provided a sample `karmada.yaml`.

we do like this:

```console

cd path/to/karmada

helm install karmada-operator -n karmada-system  --create-namespace --dependency-update ./charts/karmada-operator --debug

kubectl apply -f https://raw.githubusercontent.com/karmada-io/karmada/release-1.7/operator/config/crds/operator.karmada.io_karmadas.yaml

kubectl apply -f operator/config/samples/karmada.yaml
```

there will report `karmada.yaml` has syntax error：

![image](https://github.com/karmada-io/karmada/assets/30589999/2f9d4cda-25f6-4cdb-b740-fbe15dd28a37)

I wanna if others think it is a problem, or these configurations have some special purpose?

**What you expected to happen**:

install success

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): latest
- Others:

**Comment by zhzhuang-zju** [comment]
cc @calvin0327  Hi~ have you made some progress? if not, can I take this?

**Comment by zhzhuang-zju** [comment]
@calvin0327 Hi~ Since you haven't replied yet, I’ll take it first~ Of course, if you have some ideas and suggestions too,  be free to share them here
/assign

**Comment by zhzhuang-zju** [comment]
As can be seen from the error log, karmada does not have the ```spec.components.etcd.local.volumeData.volumeClaim.metadata.name``` field. Looking at the code, we can see that the metadata in the structure definition contains the name field, so the problem should be in the process of generating crd from the structure.
https://github.com/karmada-io/karmada/blob/cf1dbf0e16940a2871ef4e918ebad38c2432e446/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L109-L119

It can be seen from the historical submission records that the above conversion process is completed using the ```controller-gen``` tool through command ```controller-gen crd paths=./operator/pkg/apis/operator/... output:crd:dir=./operator/config/crds```. 

Referring to https://github.com/kubernetes-sigs/controller-tools/pull/557, embedded ObjectMeta in the CRD get's properly generated if the generator option ```generateEmbeddedObjectMeta=true``` is passed, so we should change the command accordingly and add generator option ```generateEmbeddedObjectMeta=true```.

**Comment by chaosi-zju** [comment]
@zhzhuang-zju great job~

**Comment by chaosi-zju** [comment]
@zhzhuang-zju would you like to push a PR to fix it?

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju would you like to push a PR to fix it?
 
Of course, I'd love to~
