### ISSUE TITLE
Cherrypick #4139: EnqueueAffectedBindings and enqueueAffectedCRBs add schedulerNameFilter

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4142]
**Which PR needs cherry-picks:**

PR #4139

**Which release branches need this patch:**

- [x] release-1.7 #4150 
- [x] release-1.6 #4149 

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by Yan-Daojiang** [comment]
Hi, I want to try it.
/assign

**Comment by XiShanYongYe-Chang** [comment]
@Yan-Daojiang thanks a lot!

**Comment by RainbowMango** [comment]
/close
All tasks have been resolved. 
Thanks @Yan-Daojiang for the help.
