### ISSUE TITLE
Karmada Client-go example needed

### ISSUE THREAD

**Issue by xuyao18** [karmada-io/karmada#4159]
**Please provide an in-depth description of the question you have**:
Hi , guys ! I am using karmada to control my kuerbernetes clusters . I want to call karmada api by golang just like calling kubernetes API.  Could you provide some example code or document  about karmada-api ?

**What do you think about this question?**:

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.23.5
- Others:

**Comment by RainbowMango** [comment]
Unfortunately, we don't have such a document yet.

But if you are familiar with client-go, the following resources might help:
- The generated `clientset`, `informers`, and `listers` are located at https://github.com/karmada-io/karmada/tree/master/pkg/generated.
- The example code can be found in Karmada E2E tests, we use it a lot in the Karmada project : https://github.com/karmada-io/karmada/blob/a98d5fdfa19bcb7cf504a278bdcebcc910e0f6ad/test/e2e/suite_test.go#L123

**Comment by RainbowMango** [comment]
> Hi , guys ! I am using karmada to control my kuerbernetes clusters .

Are you using Karmada in production now? Or in the progress of evaluating?

**Comment by xuyao18** [comment]
We are trying to import karmada's cluster management ability as a part of our prodcut.  In near future , it will be used in production . Comparing to other multi-cluster management projects, karmada is a fantastic project.

**Comment by RainbowMango** [comment]
Glad to hear that.
The Karmada community is willing to cooperate with enterprises and provide technical support. If you need it, feel free to contact me(qdurenhongcai@gmail.com), I'm glad to guide you on how to get support and get involved in the community.

**Comment by liangyuanpeng** [comment]
Here is some simple code:

```golang
package main

import (
	"context"

	karmada "github.com/karmada-io/karmada/pkg/generated/clientset/versioned"
	"github.com/karmada-io/karmada/pkg/karmadactl/util/apiclient"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

var (
	karmadaClient *karmada.Clientset
)

func main() {
	ctrl.SetLogger(zap.New())

	restConfig, err := apiclient.RestConfig("", "/etc/mykarmada/karmada-apiserver.config")
	if err != nil {
		panic(err)
	}
	karmadaClient, err = karmada.NewForConfig(restConfig)
	if err != nil {
		panic(err)
	}
	clusters, err := karmadaClient.ClusterV1alpha1().Clusters().List(context.TODO(), v1.ListOptions{})
	if err != nil {
		panic(err)
	}
}
```

@xu
