### ISSUE TITLE
Helm templates when use "custom" certs not work properly

### ISSUE THREAD

**Issue by 22RC** [karmada-io/karmada#4173]
**What happened**:
when use the following values:
```
certs:
  mode: "custom"
```
install failed because the templates https://github.com/karmada-io/karmada/blob/v1.7.1/charts/karmada/templates/pre-install-job.yaml contains a typo (space character) in line 154.

I'll try to open a PR  asap.

**What you expected to happen**:

It will be nice to rendering manifest :)

**How to reproduce it (as minimally and precisely as possible)**:

use the values metioned in "What happened"

**Anything else we need to know?**:

**Environment**:
- Karmada version: chart v1.7.0 (also in master branch of repo)
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Thanks @22RC for spotting.
Let's assign it to you in favor of #4175.
/assign @22RC

**Comment by RainbowMango** [comment]
Seems this issue was introduced by #3815. 
@Poor12 Can you help to confirm if this is a problem?

**Comment by Poor12** [comment]
Thanks @22RC for finding. It is indeed a problem.
