### ISSUE TITLE
karmada certificate ip 10.254.0.1 

### ISSUE THREAD

**Issue by yanfeng1992** [karmada-io/karmada#4186]
**Please provide an in-depth description of the question you have**:

Does 10.254.0.1 in the karmada certificate have any special function?

https://github.com/karmada-io/karmada/blob/edeb94b4f6d8ceee2c136552d13e0f673f977483/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L316

**What do you think about this question?**:

I think it should be removed

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by yanfeng1992** [comment]
cc @RainbowMango @prodanlabs

**Comment by RainbowMango** [comment]
> Does 10.254.0.1 in the karmada certificate have any special function?

No. I'm not sure why it was introduced. I think we can try to remove it.

Can you help to have a try?

**Comment by yanfeng1992** [comment]
close by https://github.com/karmada-io/karmada/pull/4192
