### ISSUE TITLE
Let karmada cluster sync CRD from member clusters

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#419]
**What would you like to be added**:
Let Karmada cluster sync `CRD` from member cluster

**Why is this needed**:
Karmada cluster will create template and sync to member cluster, that's great. 
but for `CRD` scenario, if there is no such CRD in the karmada cluster but has installed in the member cluster, that is a mass that user need apply such `CRD`s both in karmada cluster and member cluster.

**Comment by RainbowMango** [comment]
That might be an interesting feature. Can we have a chat about this in next week's meeting?

**Comment by GitHubxsy** [comment]
Sounds cool.

**Comment by vincent-pli** [comment]
Sure, thanks @RainbowMango

**Comment by mrlihanbo** [comment]
Sounds cool. Need to consider the scenario of pull mode cluster

**Comment by RainbowMango** [comment]
> Sure, thanks @RainbowMango

@vincent-pli I haven't seen the agenda on [today's meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#).

**Comment by vincent-pli** [comment]
Missing the meeting, block by a full day tough training, sorry for that @RainbowMango

**Comment by RainbowMango** [comment]
No worries. We can still discuss this here.

**Comment by pigletfly** [comment]
Brilliant idea.I think we can provide a field to tell karmada if there is a existed workload in member cluster, should it be adopted or just leave it alone.

**Comment by merryzhou** [comment]
hi，I am also interested in this feature, any news？

**Comment by RainbowMango** [comment]
Hi @merryzhou 
No, if I remember right, we haven't discussed it yet. I don't know if @vincent-pli is still interested in this topic. 

@merryzhou maybe you can lead the effort to move this forward. I get your back.

My idea is to provide a controller (just like the [namespace controller](https://github.com/karmada-io/karmada/blob/master/docs/userguide/configure-controllers.md)) to propagate the CRD to member clusters automatically. 

By the way, I'm preparing the draft roadmap of 2022, this feature will be included there.

**Comment by merryzhou** [comment]
> @merryzhou maybe you can lead the effort to move this forward

ok, I'd like to have a try.

> My idea is to provide a controller (just like the [namespace controller](https://github.com/karmada-io/karmada/blob/master/docs/userguide/configure-controllers.md)) to propagate the CRD to member clusters automatically.

I think this issue is about sync CRD from member clusters, not propagate the CRD to member clusters?

**Comment by merryzhou** [comment]
> Sync CRD from Karmada to member clusters should have higher priority at least.

we can open a new issue  about this。

**Comment by RainbowMango** [comment]
I'm going to close this as its lacks activities for a long time.

Please feel free to re-open it if anyone thinks it is needed.

/close
