### ISSUE TITLE
them command `karmadactl exec` does not work well

### ISSUE THREAD

**Issue by jwcesign** [karmada-io/karmada#4197]
**What happened**:
After launching the testing environment, the command `karmadactl exec` doesn't work well.
It will have the following error:
![image](https://github.com/karmada-io/karmada/assets/19745536/38f1cfba-84cb-4365-8900-43109733daba)

This problem comes out after PR is merged: https://github.com/karmada-io/karmada/pull/4183

**What you expected to happen**:
the command `karmadactl exec` works fine.

**How to reproduce it (as minimally and precisely as possible)**:
1. Launch the testing environment with `hack/local-up-karmada.sh`
2. Run the command `ls` in the member cluster's pod with `karmadactl exec`.

**Anything else we need to know?**:
none

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): latest
- Others: none

**Comment by wawa0210** [comment]
/assign

I can try to fix this issue

**Comment by jwcesign** [comment]
Hi @wawa0210,
Thank you for your assistance. I have submitted a PR regarding this matter(mostly focus on solving it temporarily.), but I haven't been able to identify the root cause yet.

If you manage to determine the root cause and come up with a better solution, we would greatly appreciate it.

**Comment by wawa0210** [comment]
> Hi @wawa0210, Thank you for your assistance. I have submitted a PR regarding this matter(mostly focus on solving it temporarily and e2e, https://github.com/karmada-io/karmada/pull/4206/files#), but I haven't been able to identify the root cause yet.
> 
> If you manage to determine the root cause and come up with a better solution, we would greatly appreciate it.

Sorry, if you are following up, I will not follow up.
