### ISSUE TITLE
execute "make update" occurred "Please download and install the platform appropriate Protobuf package for your OS"

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4213]
**What happened**:

I installed latest version `protoc`, when I execute `make update`, it reported error：
```
Generating with controller-gen
Generating protobuf requires protoc 3.0.0-beta1 or newer. Please download and
install the platform appropriate Protobuf package for your OS: 

  https://github.com/protocolbuffers/protobuf/releases

WARNING: Protobuf changes are not being validated
```

**What you expected to happen**:

execute `make update` successful without error message

**How to reproduce it (as minimally and precisely as possible)**:
1. install latest version protoc：https://github.com/protocolbuffers/protobuf/releases
2. `make update` or `hack/update-estimator-protobuf.sh` 

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- Protoc version: libprotoc 25.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
The warning message is raised at  https://github.com/karmada-io/karmada/blob/fd03daa313a3bd05154f6937fe7a3207496a48d0/hack/update-estimator-protobuf.sh#L20-L28

> I installed latest version protoc, when I execute make update, it reported error

Which version you are using?

**Comment by chaosi-zju** [comment]
latest version

```bash
$ protoc --version
libprotoc 25.0
```
