### ISSUE TITLE
karmada apiserver start error in local up karmada 

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#424]
root@karmada-host-control-plane:/# kubectl get pods -n karmada-system
NAME                                 READY   STATUS             RESTARTS   AGE
etcd-0                               1/1     Running            0          18m
karmada-apiserver-68674c4654-bg6wb   0/1     CrashLoopBackOff   1          15s
root@karmada-host-control-plane:/# kubectl logs karmada-apiserver-68674c4654-bg6wb -n karmada-system
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
Error: invalid port value 8080: only zero is allowed

**Comment by lfbear** [comment]
Did you startup karmada only using `hack/local-up-karmada.sh`?

**Comment by chestarss** [comment]
> Did you startup karmada only using `hack/local-up-karmada.sh`?

Yes, I only execute `hack/local-up-karmada.sh`

**Comment by lfbear** [comment]
ok, could you provide more info, such as environment and install process log

**Comment by chestarss** [comment]
> ok, could you provide more info, such as environment and install process log

make: 进入目录“/home/admin/karmada”
VERSION=latest hack/docker.sh karmada-controller-manager
Sending build context to Docker daemon  276.2MB
Step 1/4 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/4 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> f641953c7d82
Step 3/4 : ADD karmada-controller-manager /bin/
 ---> Using cache
 ---> 864e5827df2c
Step 4/4 : CMD ["/bin/karmada-controller-manager"]
 ---> Using cache
 ---> d6c94798f1ca
Successfully built d6c94798f1ca
Successfully tagged swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:latest
VERSION=latest hack/docker.sh karmada-scheduler
Sending build context to Docker daemon  276.2MB
Step 1/4 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/4 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> f641953c7d82
Step 3/4 : ADD karmada-scheduler /bin/
 ---> Using cache
 ---> 3250a0008aa8
Step 4/4 : CMD ["/bin/karmada-scheduler"]
 ---> Using cache
 ---> 14e25bd1cbe9
Successfully built 14e25bd1cbe9
Successfully tagged swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest
VERSION=latest hack/docker.sh karmada-webhook
Sending build context to Docker daemon  276.2MB
Step 1/4 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/4 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> f641953c7d82
Step 3/4 : ADD karmada-webhook /bin/
 ---> Using cache
 ---> d950373d50f3
Step 4/4 : CMD ["/bin/karmada-webhook"]
 ---> Using cache
 ---> 9affab45d319
Successfully built 9affab45d319
Successfully tagged swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:latest
VERSION=latest hack/docker.sh karmada-agent
Sending build context to Docker daemon  276.2MB
Step 1/4 : FROM alpine:3.7
 ---> 6d1ef012b567
Step 2/4 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> f641953c7d82
Step 3/4 : ADD karmada-agent /bin/
 ---> Using cache
 ---> 213a514fbee2
Step 4/4 : CMD ["/bin/karmada-agent"]
 ---> Using cache
 ---> c6f1d9cc590a
Successfully built c6f1d9cc590a
Successfully tagged swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-agent:latest
make: 离开目录“/home/admin/karmada”
Image: "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:latest" with ID "sha256:d6c94798f1ca1988942914596cabde86b5eb5ed3a78f53750bf67c3e496c5da2" found to be already present on all nodes.
Image: "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest" with ID "sha256:14e25bd1cbe93e3ead35477d9f343ae19bbcd16e9053a662c868d870fab2505a" found to be already present on all nodes.
Image: "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:latest" with ID "sha256:9affab45d319a8ccf49f68e6dc448cecdc3f53f3eba8c9fd261fe473412278e7" found to be already present on all nodes.
Generating a 2048 bit RSA private key
...............................................................+++
............+++
writing new private key to '/root/.karmada/server-ca.key'
-----
2021/06/08 11:11:44 [INFO] generate received request
2021/06/08 11:11:44 [INFO] received CSR
2021/06/08 11:11:44 [INFO] generating key: rsa-2048
2021/06/08 11:11:44 [INFO] encoded CSR
2021/06/08 11:11:44 [INFO] signed certificate with serial number 346798346652158308038911375558342939603762790623
namespace/karmada-system created
serviceaccount/karmada-controller-manager created
serviceaccount/karmada-scheduler created
serviceaccount/karmada-webhook created
clusterrole.rbac.authorization.k8s.io/karmada-controller-manager created
clusterrolebinding.rbac.authorization.k8s.io/karmada-controller-manager created
secret/karmada-cert-secret created
secret/kubeconfig created
secret/webhook-cert created
statefulset.apps/etcd created
service/etcd-client created
service/etcd created
wait the etcd ready...
pod/etcd-0 condition met
deployment.apps/karmada-apiserver created
service/karmada-apiserver created
wait the karmada-apiserver ready...
error: timed out waiting for the condition on pods/karmada-apiserver-6975c5fdd-rkj4d
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-6975c5fdd-rkj4d
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-6975c5fdd-rkj4d
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-6975c5fdd-rkj4d
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-75b5b5fcb5-9np4l
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-75b5b5fcb5-9np4l
kubectl wait --for=condition=Ready --timeout=200s pods -l app=karmada-apiserver -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/karmada-apiserver-7c5f86cc58-7zwpb

**Comment by chestarss** [comment]
> ok, could you provide more info, such as environment and install process log

karmada-system       karmada-apiserver-6975c5fdd-fc94l                    0/1     ImagePullBackOff   0          49s


`crictl pull k8s.gcr.io/kube-apiserver:v1.19.1`  timeout



so i use china cache registry for gcr
crictl pull registry.aliyuncs.com/google_containers/kube-apiserver:v1.19.1


root@karmada-host-control-plane:/# kubectl get deployment karmada-apiserver -o yaml -n karmada-system|grep 'image:'
        image: registry.aliyuncs.com/google_containers/kube-apiserver:v1.19.1

**Comment by chestarss** [comment]
my mistake
