### ISSUE TITLE
Add option to add additional SANs to api-server cert during deployment.

### ISSUE THREAD

**Issue by maaft** [karmada-io/karmada#4259]
**What would you like to be added**:

I'd like to expose karmada api-server via ingress. Therefore, I need to have the ability to add additional SANs (domains, IPs) to the certificate of karmada api-server.

**Why is this needed**:

Although it is currently possible by self-generated certificates which can be specified during deployment, it would be much more convenient to do this via a simple configuration option `--additional-sans=karmada.example.com,15.22.142.212`

_Also still wondering if I'm doing something fundamentally wrong here. This project is years old and I cannot believe that until now no-one had the need to actually schedule workload across clusters by talking to a publicly available karmada api-server_

**Comment by jwcesign** [comment]
I am not sure it's possible to do like this.
cc @chaosi-zju  to check

**Comment by chaosi-zju** [comment]
Hi @maaft, you mean add `--additional-sans` to `karmadactl init` ?

**Comment by maaft** [comment]
@chaosi-zju yes, and also make this option available via helm.

**Comment by jwcesign** [comment]
helm also?

**Comment by maaft** [comment]
> @maaft may be helm is already support this feature.

oh really? I had a brief look but maybe didn't see it. Could you point me to the option when you find it? That'd be great!

**Comment by chaosi-zju** [comment]
https://github.com/karmada-io/karmada/blob/98e655fc552b2987c3f2d2a061007889ce8be536/charts/karmada/values.yaml#L90-L104

you can customize you own SANs in helm `value.yaml`

**Comment by liangyuanpeng** [comment]
If I understand correctly, karmadactl init already supports it, please check  `karmadactl init --cert-external-dns` 

Remind me if i missed something.

**Comment by maaft** [comment]
oh perfect! Thank you very much! Maybe "How to expose Karmada API-Server" should be section of docs.

Have great day everyone!

Closing for now
