### ISSUE TITLE
join member error in local up mode 

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#427]
`karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config`

W0609 12:31:43.465975  578613 join.go:452] failed to create cluster(). error: Internal error occurred: failed calling webhook "cluster.karmada.io": Post "https://karmada-webhook.karmada-system.svc:443/validate-cluster?timeout=3s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
W0609 12:31:43.466058  578613 join.go:426] failed to create cluster(member1). error: Internal error occurred: failed calling webhook "cluster.karmada.io": Post "https://karmada-webhook.karmada-system.svc:443/validate-cluster?timeout=3s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
E0609 12:31:43.466068  578613 join.go:280] failed to create cluster object. cluster name: member1, error: Internal error occurred: failed calling webhook "cluster.karmada.io": Post "https://karmada-webhook.karmada-system.svc:443/validate-cluster?timeout=3s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")
E0609 12:31:43.466075  578613 join.go:91] Error: Internal error occurred: failed calling webhook "cluster.karmada.io": Post "https://karmada-webhook.karmada-system.svc:443/validate-cluster?timeout=3s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")

**Comment by chestarss** [comment]
root@karmada-host-control-plane:/# `kubectl logs -f karmada-webhook-65fc87f89d-cgh95 -n karmada-system`
I0609 03:42:32.533159       1 options.go:49] Set default value: Options.LeaderElection.ResourceLock = endpointsleases
I0609 03:42:32.533228       1 options.go:54] Set default value: Options.LeaderElection.LeaseDuration = 15s
I0609 03:42:32.533233       1 options.go:59] Set default value: Options.LeaderElection.RenewDeadline = 10s
I0609 03:42:32.533236       1 options.go:64] Set default value: Options.LeaderElection.RetryPeriod = 2s
I0609 03:42:33.039277       1 webhook.go:70] registering webhooks to the webhook server
I0609 04:31:43.465234       1 log.go:184] http: TLS handshake error from 10.244.0.1:57164: remote error: tls: bad certificate




I0609 04:37:23.108021       1 log.go:184] http: TLS handshake error from 10.244.0.1:43759: remote error: tls: bad certificate

**Comment by lfbear** [comment]
@chestarss It seems that the karmada has NOT installed totally, I suggest you reinstall karmada, before that you need to delete the container named 'karmada-host-control-plane'

**Comment by chestarss** [comment]
> @chestarss It seems that the karmada has NOT installed totally, I suggest you reinstall karmada, before that you need to delete the container named 'karmada-host-control-plane'

okay, it works 

reason:
install script every execute alway generate cert key file,  etcd before start use old cert, apiserver use new cert .
