### ISSUE TITLE
External schedulers can directly reference Karmada’s existing scheduling capabilities

### ISSUE THREAD

**Issue by wangyang0616** [karmada-io/karmada#4279]
**What would you like to be added**:
During the scheduling process, filtering, scoring, select cluster, and assign replicas are performed in sequence. 
Filtering and scoring have been plugged in. The external scheduler can directly reference this part of the strategy. 

We hope that select cluster and assign replicas can also support reference by external schedulers.

**Why is this needed**:
Similar to kube-scheduler, the scheduling strategy of karmada-scheduler supports direct reference to third-party schedulers for extended development. For example: APIEnablement, ClusterAffinity, ClusterEviction, ClusterLocality, SpreadConstraint, TaintToleration.

However, some scheduling strategies cannot be directly referenced by the third-party scheduler, such as the scheduling capabilities under `pkg/scheduler/core`.

When third-party schedulers extend customized scheduling strategies based on Karmada, this part of the scheduling capabilities cannot be directly referenced and inherited.

**Comment by RainbowMango** [comment]
In addition to the `pkg/scheduler/core` part, what modules your scheduler hope to reference?
Given I don't know how exactly your schedule want to reference the code, can you provide more details about what you want Karmada to do?
