### ISSUE TITLE
One command to build multi-clusters by karmada helm chart

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4305]
**What would you like to be added**:

A script using just one command to build multi-clusters by karmada helm chart

**Why is this needed**:

There are sevaral scenarios:

**1) scenario one**

I am a real user of karmada, **I has several real clusters in prod environment**, I want to build multi-clusters by karmada.

It is not fit for me to use `hack/local-up-karmada.sh`, it just mocked some KinD clusters.

I tend to install karmada by helm chart on given clusters, so I should install karmada on control plane and then join member clusters. **But it is so hard for me to finish the whole process**, especially in pull mode, I have to settle the certs of karmada-agent.

**I want just one command to finish the whole process**, I need just provided my kubeconfig path and specify how many clusters I want, after one command, the whole clusters builded success, just like:

```console
NAME      VERSION   MODE   READY   AGE   APIENDPOINT
member1   v1.27.3   Push   True    45s   https://172.18.0.3:6443
member2   v1.27.3   Pull   True    2s    
member3   v1.27.3   Push   True    41s   https://172.18.0.4:6443
```

**2) scenario two**

I am new to Karmada, I want to try karmada, **I am familiar with helm chart.**

I just want to try the features of karmada, I don't have any patience for karmada installation.

I want just one command script to help me **create clusters first and then build the control plane and member cluster success.**

Besides, I am behind firewall, pulling images is a trouble to me when installing, I don't want to waste time to solve it by config proxy, I can only accept fetch the image to local node in advance.

**3) scenario true**

I am a Developer or Tester, our project is based on Karmada, I want to construct a variety of complex multi-cluster scenarios.

So, I want a installation script which can specify the number of push mode clusters or pull mode clusters.

For example, I need 5 push mode clusters and 3 pull mode clusters, by executing one command, the member clusters installed success.

**Comment by chaunceyjiang** [comment]
> One command to build multi-clusters by karmada helm chart 

Why not use karmadactl init?

**Comment by liangyuanpeng** [comment]
duplicate #4306

**Comment by chaosi-zju** [comment]
>  Why not use karmadactl init?

supposing I have 10 cluster, I want to install karmada control plane at No.1 cluster, and join push mode member cluster at No.2~No.5 cluster, and join pull mode member cluster at No.6~No.10 cluster, however karmadactl neither can achieve one command to build multi-cluster, the user should execute the command step by step.

besides, some user tend to use helm, since we provided this install method, why not improve it.

besides, I often hear users feedback the failure, even diss the helm installtion method in wechat group, it actually not friendly using to users.

**Comment by chaosi-zju** [comment]
> duplicate #4306

thanks for finding~ There was a problem with the network and duplicate submissions were made

**Comment by RainbowMango** [comment]
> scenario one

I don't think the script is the official tooling for users to install Karmada in a production scenario.

> scenario two
I am new to Karmada, I want to try karmada, I am familiar with helm chart.

In this case, the developer can go with the recommended quick start guide which is the community maintains for developers.

> 3) scenario true
I am a Developer or Tester, our project is based on Karmada, I want to construct a variety of complex multi-cluster scenarios.
So, I want a installation script which can specify the number of push mode clusters or pull mode clusters.

This is not a real-world use case, Karmada installation and cluster registration are different operations.
