### ISSUE TITLE
Sync karmada v1.7.0 API to `api` repo

### ISSUE THREAD

**Issue by calvin0327** [karmada-io/karmada#4314]
We want to use the preemption functionality of pp, but the version of api is still v1.6.0

So, we need sync the karmada v1.70  to api repo. thanks.

**Comment by liangyuanpeng** [comment]
Here is the PR of working for it:
- https://github.com/karmada-io/api/pull/20

**Comment by RainbowMango** [comment]
1. The PR is ready and you can help to review/approve: https://github.com/karmada-io/api/pull/20

> We want to use the preemption functionality of pp,

Warning!
[This proposal](https://github.com/karmada-io/karmada/pull/4289) is trying to deprecate the preemption feature. The proposal is now under reviewing, please leave your comments there.
