### ISSUE TITLE
Question about karmada design

### ISSUE THREAD

**Issue by Colstuwjx** [karmada-io/karmada#432]
**What would you like to be added**:
Allows directly deployment apps on member clusters, rather than **deploy on host cluster + propagate to member cluster**

**Why is this needed**:
At sometimes, I couldn't sure about which cluster is the main cluster ( which the load balancer traffic to ), as the result, I can't just follow the default rule: deploy app on host cluster, and then propagate to member cluster.

Do we support deploy app on one member cluster, and then propagate it to another member cluster?

**Comment by kevin-wangzefeng** [comment]
This would be supported by aggregated kube-api endpoint, which is already in our roadmap.

**Comment by RainbowMango** [comment]
/close
As the [Aggregated Kubernetes API](https://github.com/karmada-io/karmada/blob/master/docs/userguide/aggregated-api-endpoint.md) is ready now.
