### ISSUE TITLE
Unexpected Setting Concurrency  as 1 in Binding Status Controller

### ISSUE THREAD

**Issue by lxtywypc** [karmada-io/karmada#4339]
**What happened**:  
Because of missing `forType` in `binding-status controller`, the concurrency of the controller would be always set as 1.  

**What you expected to happen**:  
The concurrency of `binding-status controller` could inherit from the concurrency of `binding` declared in global options.  

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:  
If a controller is built WITHOUT concurrency options, AND it HAS a `forType`, the concurrency of the controller would inherit from the concurrency for `forType` declared in global options.  

https://github.com/karmada-io/karmada/blob/01b086d2e1a231d470cbf2742b2667d87d656e2d/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go#L354-L370   

Up to now, all the concurrency of controllers in `Karmada` inherit from the global options. And all controllers except `binding-status controller` has a `forType`. So only `binding-status controller` would has a concurrency as `1`.  

There are two ways to solve the problem:  
1. Add a `forType` with a fake predicate to inherit concurrency from global options and keep the same performance at the same time.  
2. Add concurrency options when building the `binding-status controller`.  

This problem occurs after we seprate `binding-status controller` from `binding controller`. On the latest `master` branch, this problem is fixed after the #4138 coincidentally, but in the earlier version it still exists.  

It might be hard to cherry-pick #4138 straightly because it seems a fix for feature `hpaReplicasSyncer`, that might not necessary in earlier version.  

I would try to raise a PR to solve it in first way soon. But it would bring differences on commit history between `master` branch and other branches of eralier version, I wonder if it is acceptable, or what the recommend way is.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
In favor of #4340 
/assign @lxtywypc

**Comment by XiShanYongYe-Chang** [comment]
#4340 has been merged.
/close
