### ISSUE TITLE
Incorrect file header copyright in lifted files

### ISSUE THREAD

**Issue by kevin-wangzefeng** [karmada-io/karmada#4345]
**Task description**:

Lifted files shall keep the original license and copyright.
The copyright description in the following two files are not correct. 
https://github.com/karmada-io/karmada/blob/master/pkg/util/lifted/federatedhpa.go#L2
https://github.com/karmada-io/karmada/blob/master/pkg/util/lifted/federatedhpa_test.go#L2

**Solution**:

1. Fix the wrong description
2. hack/verify-license.sh should be aware of the lifted files cases.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by zhzhuang-zju** [comment]
I completed Solution1 in PR #4344, but Solution2 is not yet completed. Anyone who is interested can participate together~

**Comment by XiShanYongYe-Chang** [comment]
`hack/verify-license.sh` script will validate the files and check for those without a header copyright. Currently, all files under the lift directory have been added with a header copyright correctly. If there are any files in this directory that do not have a header copyright during subsequent iterations, the validation will fail. 

Therefore, the current script meets the requirements.

**Comment by sagnik3788** [comment]
@XiShanYongYe-Chang is this issue solved

**Comment by XiShanYongYe-Chang** [comment]
Hi @sagnik3788, this issue has been solved, thanks for your reminding.
/close
