### ISSUE TITLE
openshift apiserver support

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#435]
**What would you like to be added**:
karmada-apiserver support base openshift-apiserver, which include some crd like project, deploymentConfig etc. 

**Why is this needed**:
base openshift resource manager

**Comment by RainbowMango** [comment]
I'm sorry I didn't catch your meaning.  What's your use case?

**Comment by chestarss** [comment]
> I'm sorry I didn't catch your meaning. What's your use case?

我这边使用的openshift, 应用创建依赖openshift中的Project和DeploymentConfig资源，这两个资源是openshift apiserver内置的资源，标准的k8s没有，所以想能否支持下 karmada-apiserver 可选使用 openshift-apiserver启动。

**Comment by chestarss** [comment]
当然通过CRD方式把openshift 特有的内置资源注册到karmada控制面上的k8s-apiserver里也可以解决问题。
目前我没有找到这些内置资源的CRD定义yaml.

**Comment by RainbowMango** [comment]
> 当然通过CRD方式把openshift 特有的内置资源注册到karmada控制面上的k8s-apiserver里也可以解决问题。

+1

**Comment by chestarss** [comment]
> > 当然通过CRD方式把openshift 特有的内置资源注册到karmada控制面上的k8s-apiserver里也可以解决问题。
> 
> +1

请教下原生内置资源怎么导出类似CRD的定义yaml格式

**Comment by RainbowMango** [comment]
```
kubectl get customresourcedefinitions.apiextensions.k8s.io xxxx -o yaml
```
This might works.

**Comment by chestarss** [comment]
> ```
> kubectl get customresourcedefinitions.apiextensions.k8s.io xxxx -o yaml
> ```
> 
> This might works.

试过了，这个只是对后期注册的crd生效，对apiserver内置的资源没用

**Comment by RainbowMango** [comment]
可以到OpenShift 社区问问看。
/close
