### ISSUE TITLE
Migrate webhook server into controller-manager

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#437]
**What would you like to be added**:

**Why is this needed**:

It will simplify the karmada installation.

**Comment by RainbowMango** [comment]
That makes sense. fewer components, fewer problems.

**Comment by RainbowMango** [comment]
We can have a talk at the community meeting.

**Comment by RainbowMango** [comment]
/close
Please reopen and talk about this if you think still necessary. 

I can't see more benefits except simplifying installation, but if we really do so, can't imagine what would happen for `karmada-webhook` running in election mode.
