### ISSUE TITLE
insecureSkipTLSVerification is true,but  cluster.spec.secret.caBundle must be set, it's unexpected

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#4370]
**What happened**:
Use karmadactl get pods, Print error `cluster(xxx) is inaccessible, please check authorization or network`, I check karmada-aggregated-apiserver log:
![image](https://github.com/karmada-io/karmada/assets/18431718/05ae3531-df32-41db-8e51-604f7fb3a7bd)

It seems that if caBundle not set,   karmadactl get pods must be failed
<img width="871" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/70a66b79-10da-4b60-b353-d80c99bf971d">

**What you expected to happen**:
if insecureSkipTLSVerification = true, command line `karmadactl get pods`   should be executed successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.8.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
/cc @jwcesign 
Can you help take a look?

**Comment by jwcesign** [comment]
Hi @CharlesQQ ,

Did you modify the cluster's certificate-related secret? By default, there is a ca-cert.

**Comment by CharlesQQ** [comment]
> Hi @CharlesQQ ,
> 
> Did you modify the cluster's certificate-related secret? By default, there is a ca-cert.

yes, I create secret manual， We use token connect to apiserver

**Comment by jwcesign** [comment]
> yes, I create secret manual， We use token connect to apiserver

It makes sense. Would you mind helping out by submitting a PR to fix this issue?

**Comment by CharlesQQ** [comment]
> > yes, I create secret manual， We use token connect to apiserver
> 
> It makes sense. Would you mind helping out by submitting a PR to fix this issue?

of cause
