### ISSUE TITLE
“kubectl get cluster” query cluster status still ready when m cluster shutdown

### ISSUE THREAD

**Issue by guanxingfeng** [karmada-io/karmada#439]
**What happened**:
1.when m cluster shutdown，“kubectl get cluster” query cluster status still ready 
2.the lastTransitionTime in conditions is not update Regularly
![image](https://user-images.githubusercontent.com/25924966/121797268-cc7b9300-cc51-11eb-8af0-b510a6dd8f33.png)
3.what is difference between push and pull？I change  m1 mode to pull，but not see the difference Currently.
![image](https://user-images.githubusercontent.com/25924966/121797411-a1de0a00-cc52-11eb-8b60-664c237d9173.png)

**What you expected to happen**:
cluster status not ready

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:karmada-apiserver version v1.19.1
- Others: k8s v1.20.2 ，deployed by kind

**Comment by RainbowMango** [comment]
> the lastTransitionTime in conditions is not update Regularly

The `lastTransitionTime` records the `last` transition time, the time will be update only when status change, such as `Ready` to `NotReady`.

> what is difference between push and pull？I change m1 mode to pull，but not see the difference Currently.

Please refer to the API document:
https://github.com/karmada-io/karmada/blob/738c148401d54fd8f4532269094297bc26553744/pkg/apis/cluster/v1alpha1/types.go#L85-L93

**Comment by Garrybest** [comment]
#421 and its further PR are related to this issue. When lease is added, controller-manager will check the ready condition.

**Comment by RainbowMango** [comment]
/close
In favor of #421
