### ISSUE TITLE
add cluster taint, expect pod be evicted, but failed

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#4402]
**What happened**:
Add cluster taint with  comand `karmadactl  taint clusters xxx testkey=testvalue:NoExecute`
<img width="323" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/df1e252d-3fa5-46d4-8621-02da0ee9bb03">

however, pod not be evicted, rb update failed

describe rb message is:
<img width="1214" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/dbade7d4-cb7a-461c-9cfb-06afbd36a7bc">
rb.spec info is:
<img width="495" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/6c40d68d-432a-4112-b75e-d491b89a92ac">

print taint_manager log is:
<img width="1318" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/099f4968-8c85-4da6-8524-99986ac5f59b">

**What you expected to happen**:
pod evicted successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1.  deploy the application to cluster xxx
2. add taint `karmadactl  taint clusters xxx testkey=testvalue:NoExecute`
3. describe rb 
4. check taint_manager log

**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.8.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:   kubernetes  v1.18.2

**Comment by XiShanYongYe-Chang** [comment]
Thanks @CharlesQQ 
Let me take a look.

**Comment by CharlesQQ** [comment]
it seems that lock Missing field `creationTimestamp`
https://github.com/karmada-io/karmada/blob/08651832925a3eb238b6d56770400943d1307a2b/pkg/apis/work/v1alpha2/binding_types_helper.go#L153-L167

**Comment by XiShanYongYe-Chang** [comment]
I feel that yes, it is necessary to specify this value when adding. Can you help test it?

**Comment by CharlesQQ** [comment]
> I feel that yes, it is necessary to specify this value when adding. Can you help test it?

sure

**Comment by CharlesQQ** [comment]
I add log
![image](https://github.com/karmada-io/karmada/assets/18431718/d1ed39e3-c249-400b-a9cf-faad4dcc307f)

**Comment by CharlesQQ** [comment]
creationTimestamp field shoule be pointer type
https://github.com/karmada-io/karmada/blob/c7c393f564f65f427725d74a9d4a956b2026ff64/pkg/apis/work/v1alpha2/binding_types.go#L252-L259

**Comment by XiShanYongYe-Chang** [comment]
This issue has been discussed in the Kubernetes community before: https://github.com/kubernetes/kubernetes/issues/86811. The direct solution is to set `metav1.Time` as a pointer. However, the K8s community did not choose to do so considering[ backward compatibility](https://github.com/kubernetes/kubernetes/issues/86811#issuecomment-588276966). Instead, they resolved this issue through [a feature PR](https://github.com/kubernetes/kubernetes/pull/95423) in version v1.20.

For Karmada, if the image version of `kube-apiserver` used by the user is v1.20 or above, there will be no such issue. However, for previous versions, the problem mentioned in the issue will occur. Modifying `metav1.Time` to a pointer type is recommended and this change has almost no NPE in Karmada. Therefore, I suggest making this modification.

**Comment by XiShanYongYe-Chang** [comment]
In favor of #4407
/assign @CharlesQQ
