### ISSUE TITLE
Fail to register a cluster to Karmada with 'Pull' mode

### ISSUE THREAD

**Issue by CrossainQi** [karmada-io/karmada#4413]
**What happened**:
Register a cluster to Karmada with Pull mode failed, error:
~~~sh
# karmadactl register <master ip>:32443 --token kkn3i2.0py402a9it6ijohi --discovery-token-ca-cert-hash sha256:9b21070b423bee97b2ddf058d08516db0c4968e9f04d90bc490499e4cab1545c
[preflight] Running pre-flight checks
[preflight] All pre-flight checks were passed
[karmada-agent-start] Waiting to perform the TLS Bootstrap
W1213 17:01:45.194690   55277 register.go:349] Failed to remove bootstrapKubeConfigFile: remove /etc/karmada/bootstrap-karmada-agent.conf: no such file or directory
error: couldn't validate the identity of the API Server: Get "https://<master ip>:32443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": Forbidden
~~~
**What you expected to happen**:
The cluster was registered successfully to Karmada
**How to reproduce it (as minimally and precisely as possible)**:
- Deploy 2 single-node k3s clusters.
- Deploy Karmada to one node via `kubectl karmada init` command.
- Excute `karmadactl token create --print-register-command --kubeconfig /etc/karmada/karmada-apiserver.config` on the node.
- Excute the output of above command on another node.
**Anything else we need to know?**:

**Environment**:
- Karmada version: 1.8.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 
~~~sh
karmadactl version: version.Info{GitVersion:"v1.8.0", GitCommit:"c8811b66304614a3bcfcc21a31ffda8c83781682", GitTreeState:"clean", BuildDate:"2023-11-30T19:03:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
~~~
- Others:

**Comment by liangyuanpeng** [comment]
> karmadactl register <master ip>:32443

You need to change `<master ip>` to the really IP.

**Comment by CrossainQi** [comment]
> > couldn't validate the identity of the API Server: Get "https://:32443
> 
> You need to change `<master ip>` to the really IP.

`<master ip>` represents a real IP, should i deploy karmada on all of the clusters?

**Comment by liangyuanpeng** [comment]
> should i deploy karmada on all of the clusters?

Not need for it,  what is your K3s version and any more log here?

**Comment by CrossainQi** [comment]
> > should i deploy karmada on all of the clusters?
> 
> Not need for it, what is your K3s version and any more log here?

I found a http_proxy was set on the cluster, after I unset the proxy the cluster was successfully registered to Karmada, I will close this issue, thanks!

**Comment by XiShanYongYe-Chang** [comment]
@liangyuanpeng @CrossainQi Thank you for your communication.
Let me modify the label.
/kind question
/remove-kind bug
