### ISSUE TITLE
support  canary release

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#4421]
**What would you like to be added**:
1. karmada allow pause work object propagate to member cluster until  user want to 
2. during propagation is paused,  user changed the overriepolicy By API, such as  `annotationsOverrider` field
3. user set and allow new work object be to propagated to member cluster

**Why is this needed**:
Our canary release strategy is declare by  deployment.metedata.annotation,  process is  controller by our owner custom controller;
So before the latest deployment is synced to member cluster, deployment.metedata.annotation must be set

**Comment by chaosi-zju** [comment]
Hi @CharlesQQ, I am very interested in your feature

Actually, rather than just implement this feature, I am more interested in how you use canary release strategy by in karmada.

Can you share more info with me on how using canary release strategy in karmada? Thanks very much~

**Comment by chaunceyjiang** [comment]
I believe it's time to push forward with this feature. This is a feature that has been discussed for a long time. 
@RainbowMango @XiShanYongYe-Chang @CharlesQQ

**Comment by chaosi-zju** [comment]
> I believe it's time to push forward with this feature. This is a feature that has been discussed for a long time.

is there any related issue or meeting notes?

**Comment by XiShanYongYe-Chang** [comment]
> I believe it's time to push forward with this feature. This is a feature that has been discussed for a long time.

I agree with this.

**Comment by CharlesQQ** [comment]
> Hi @CharlesQQ, I am very interested in your feature
> 
> Actually, rather than just implement this feature, I am more interested in how you use canary release strategy by in karmada.
> 
> Can you share more info with me on how using canary release strategy in karmada? Thanks very much~

This has nothing to do with karmada, it's related to deployment Annotation,  as Annotation‘s value changed, customer controller calculate newRS's replicas and oldRS's Replicas;  before deployment synced to member cluster, Annotation's value must be changed by our owner controller, so needed paused sync work feature

<img width="340" alt="image" src="https://github.com/karmada-io/karmada/assets/18431718/4d5700a1-0173-4b93-8370-d99c211e3179">

**Comment by zach593** [comment]
After reading the proposal https://github.com/karmada-io/karmada/pull/5118/files, I have some questions.
Of course, the proposal focuses on cluster-level pauses, so how to implement application-level pauses mentioned in this issue? To be determined?

Using pp/cpp for application-level pauses is OK, but not good enough.
pp/cpp may be owned by the cluster administrator and the application owner cannot touch them. Even if we can let the application owner operate pp/cpp, one pp/cpp per application will make us lose the large-scale scope management ability of pp/cpp

**Comment by XiShanYongYe-Chang** [comment]
Hi @zach593 thanks for your feedback. We can continue to iterate on this feature.

How do you use PP/CPP now?

**Comment by zach593** [comment]
> How do you use PP/CPP now?

pp/cpp owned by the cluster administrator, the application owners can only touch the workload(resource template).

we don't need this pause function at the moment, it's just that I personally have doubts about this design. @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
@zach593 Thanks for your use case.

We designed it with this in mind, and we plan to orchestrate applications in the future through the new CRD API. For some current user stories, the suspension field in PP/CPP can meet the requirements. If the field cannot meet the user requirements in the future, the field may be deprecated.

**Comment by CharlesQQ** [comment]
close

**Comment by XiShanYongYe-Chang** [comment]
#5217 can cover this feature.
Thanks all. If you have more requirements, you can submit a new issue.

**Comment by JiaShuai0209** [comment]
> > Hi [@CharlesQQ](https://github.com/CharlesQQ), I am very interested in your feature
> > Actually, rather than just implement this feature, I am more interested in how you use canary release strategy by in karmada.
> > Can you share more info with me on how using canary release strategy in karmada? Thanks very much~
> 
> This has nothing to do with karmada, it's related to deployment Annotation, as Annotation‘s value changed, custom controller calculate newRS's replicas and oldRS's Replicas; before deployment synced to member cluster, Annotation's value must be changed by our owner controller, so needed paused sync work feature
> 
> <img alt="image" width="340" src="https://private-user-images.githubusercontent.com/18431718/290756175-4d5700a1-0173-4b93-8370-d99c211e3179.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2Mzg2ODQsIm5iZiI6MTc2MTYzODM4NCwicGF0aCI6Ii8xODQzMTcxOC8yOTA3NTYxNzUtNGQ1NzAwYTEtMDE3My00YjkzLTgzNzAtZDk5YzIxMWUzMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDA3NTk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNzA5ZmQyZTk2MGIxOWI5NTY5ZjgwYzNlZThlNDJhMTQ0MTliMmJkY2UwMmI3ZGY5YjQxMGYyNTc5NjQ1ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Zqj_d_AZVrQa6sOnKPFqQQCsns1Gz7a4JkSeB2UxqQU">
> ![灰度发布](https://github.com/karmada-io/karmada/assets/18431718/8c7c5a8c-8ace-46ae-adf8-0af1e939dda8)

hi, is partition in this picture means like partion in cloneset update strategy? if true, i think https://github.com/karmada-io/karmada/issues/5217 can not cover this feature because it just suspend syncing work to member cluster. so all pods of workload can not be updated rather than partition of pods can not be updated
