### ISSUE TITLE
The status of ResourceBinding/ClusterResourceBinding and Work should present the status of resource applied

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#443]
**What would you like to be added**:
I try to propagate a `CR` who's CRD is not installed in the target cluster, and I get nothing(no error, no warning) from the `ResourceBinding/ClusterResourceBinding` or `Work`, the `status` for such resource is empty.

I have no idea it's failed until I check the log of `karmade controller management`.

I think we need mark these failed at least in the `status`.

**Why is this needed**:

**Comment by qianjun1993** [comment]
I also find that there is no info in status when the scheduler failed , but in fact the struct of conditions exists in status which is not used。So, I try to add same logic to add error info into conditions during scheduling。Maybe my plan can also help you.

**Comment by pigletfly** [comment]
karmada-controller-manager should update work status ,and also record a event.xref: https://github.com/karmada-io/karmada/issues/398

**Comment by RainbowMango** [comment]
Yes, both event and status(or conditions) are necessary. 

> So, I try to add same logic to add error info into conditions during scheduling and will submit the modification

@qianjun1993 Thanks, I guess you mean #452.

**Comment by RainbowMango** [comment]
/close
We have added `Scheduled` and `FullyApplied` conditions to RB/CRB.
