### ISSUE TITLE
argocd ComparisonError <string>:100: bad argument #1 to ipairs (table expected, got nil) stack traceback: [G]: in function 'ipairs' <string>:100: in main chunk [G]: ?

### ISSUE THREAD

**Issue by linuxme** [karmada-io/karmada#4449]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
Deploying workload rollout through argocd results in an error as follows：
ComparisonError
<string>:100: bad argument #1 to ipairs (table expected, got nil) stack traceback: [G]: in function 'ipairs' <string>:100: in main chunk [G]: ?

![image](https://github.com/karmada-io/karmada/assets/1657557/d90ea28e-eb9c-49d2-abef-97889460128a)

Please take a look, thx

**Environment**:
- Karmada version: v1.8
- Kubernetes version: 1.26.5
- Others:  argo-rollout:v1.5.1  argo server:v2.4.28

**Comment by RainbowMango** [comment]
Thanks for spotting. Seems this is the same issue tracked by #3617 and continue the discussion there.
