### ISSUE TITLE
[GoodFirst]Fix redundant log

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#445]
**Task description**:
There is a log at `karmada-controller-manager`:
```
I0616 01:29:44.872798       1 cluster_controller.go:192] Created execution space(&Namespace{ObjectMeta:{karmada-es-member3   /api/v1/namespaces/karmada-es-member3 370e36e7-6828-48d7-93db-bae6ba306767 267 0 2021-06-16 01:29:44 +0000 UTC <nil> <nil> map[] map[] [] []  [{karmada-controller-manager Update v1 2021-06-16 01:29:44 +0000 UTC FieldsV1 {"f:status":{"f:phase":{}}}}]},Spec:NamespaceSpec{Finalizers:[kubernetes],},Status:NamespaceStatus{Phase:Active,Conditions:[]NamespaceCondition{},},}) for cluster(member3).
```

The log intended to record the namespace `name` not the whole `namespace` object. 
https://github.com/karmada-io/karmada/blob/402d5884c9a49f9712db146fd663463e365d78d2/pkg/controllers/cluster/cluster_controller.go#L192

**Solution**:
Log the namespace name instead of namespace object, like this:
```diff
diff --git a/pkg/controllers/cluster/cluster_controller.go b/pkg/controllers/cluster/cluster_controller.go
index a2c47df..003cf1d 100644
--- a/pkg/controllers/cluster/cluster_controller.go
+++ b/pkg/controllers/cluster/cluster_controller.go
@@ -189,7 +189,7 @@ func (c *Controller) createExecutionSpace(cluster *v1alpha1.Cluster) error {
                        klog.Errorf("Failed to create execution space for cluster(%s): %v", cluster.Name, err)
                        return err
                }
-               klog.V(2).Infof("Created execution space(%s) for cluster(%s).", executionSpace, cluster.Name)
+               klog.V(2).Infof("Created execution space(%s) for cluster(%s).", executionSpaceName, cluster.Name)
        }

        return nil
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by gy95** [comment]
just only need to modify the one code?

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by RhnSharma** [comment]
I would like to take this one.
