### ISSUE TITLE
The deployment was not cleaned after the cluster resumed from hibernation

### ISSUE THREAD

**Issue by vincentgoat** [karmada-io/karmada#4455]
**What happened**:
Hi, 
Here are the steps:
1. Prepare 2 clusters
[demo.zip](https://github.com/karmada-io/karmada/files/13715283/demo.zip)

2. Create a deployment with 4 replicas(details are in the attached file)
3. Put cluster01 to sleep and check the workload changes.
4. After all the deployments are scheduled to cluster02, restore cluster01 and check the workload changes.
5. The deployment on cluster01 has not been cleaned up, it is not the case we expected to happen.

**What you expected to happen**:
The deployment on cluster01 will be cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Please @zhzhuang-zju help to take a look.

> Put cluster01 to sleep and check the workload changes.

I talked to @vincentgoat , `cluster sleep` means cluster disconnect...

**Comment by zhzhuang-zju** [comment]
> Please @zhzhuang-zju help to take a look.
> 
> > Put cluster01 to sleep and check the workload changes.
> 
> I talked to @vincentgoat , `cluster sleep` means cluster disconnect...

Received, I will reproduce it locally first

**Comment by zhzhuang-zju** [comment]
Hi @vincentgoat I built a local karmada cluster using the master branch and v1.9.0-preview2. The end result was that the deployment was cleaned after the cluster resumed from hibernation.
Here are the steps:
1. create a deployment and propagate them
```shell
(base) ➜  karmada git:(v1.9.0-preview2) ✗ ka get work -A
NAMESPACE            NAME                              WORKLOAD-KIND        APPLIED   AGE
karmada-es-member1   deploy-01-f97b94866               Deployment           True      6s
karmada-es-member2   deploy-01-f97b94866               Deployment           True      6s
(base) ➜  karmada git:(v1.9.0-preview2) ✗ km1 get pods -A |grep de
default              deploy-01-56d9698576-h2m26                      1/1     Running   0               27s
default              deploy-01-56d9698576-n2czl                      1/1     Running   0               27s
(base) ➜  karmada git:(v1.9.0-preview2) ✗ km2 get pods -A |grep de
default              deploy-01-56d9698576-b7mfq                      1/1     Running   0          33s
default              deploy-01-56d9698576-g4q84                      1/1     Running   0          33s
```
2. disconnect cluster member1
```
(base) ➜  karmada git:(v1.9.0-preview2) ✗ docker ps 
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS         PORTS                       NAMES
fa8e579fd809   kindest/node:v1.27.3   "/usr/local/bin/entr…"   9 minutes ago   Up 8 minutes   127.0.0.1:42277->6443/tcp   karmada-host-control-plane
dcd757f17178   kindest/node:v1.27.3   "/usr/local/bin/entr…"   9 minutes ago   Up 8 minutes   127.0.0.1:42147->6443/tcp   member2-control-plane
9faa31e95100   kindest/node:v1.27.3   "/usr/local/bin/entr…"   9 minutes ago   Up 8 minutes   127.0.0.1:36435->6443/tcp   member3-control-plane
38fbf773fd8e   kindest/node:v1.27.3   "/usr/local/bin/entr…"   9 minutes ago   Up 8 minutes   127.0.0.1:36405->6443/tcp   member1-control-plane
(base) ➜  karmada git:(v1.9.0-preview2) ✗ docker stop 38fbf773fd8e
38fbf773fd8e
```
3. Observe the change of replicas in cluster member2. Because the parameter `tolerationSeconds: 300` is set, you need to wait 5 minutes before there is a change.
```shell
(base) ➜  karmada git:(v1.9.0-preview2) ✗ km2 get pods -A |grep deploy 
default              deploy-01-56d9698576-b7mfq                      1/1     Running   0          7m9s
default              deploy-01-56d9698576-fqfw9                      1/1     Running   0          8s
default              deploy-01-56d9698576-g4q84                      1/1     Running   0          7m9s
default              deploy-01-56d9698576-tptvr                      1/1     Running   0          8s
```
4. resumed member1, and the deployment was cleaned
```shell
(base) ➜  karmada git:(v1.9.0-preview2) ✗ docker start 38fbf773fd8e
38fbf773fd8e
(base) ➜  karmada git:(v1.9.0-preview2) ✗ km1 get pods -A -w|grep deploy
default              deploy-01-56d9698576-h2m26                      1/1     Running   1 (11s ago)   7m35s
default              deploy-01-56d9698576-n2czl                      1/1     Running   1 (11s ago)   7m35s
default              deploy-01-56d9698576-n2czl                      1/1     Terminating        1 (59s ago)   8m23s
...
default              deploy-01-56d9698576-h2m26                      0/1     Terminating        1 (60s ago)   8m24s
(base) ➜  karmada git:(v1.9.0-preview2) ✗ ka get work -A                       
NAMESPACE            NAME                              WORKLOAD-KIND        APPLIED   AGE
karmada-es-member2   deploy-01-f97b94866               Deployment           True      9m14s
```
5. watch logs of karmada controller manager
`shell
(base) ➜  karmada git:(v1.9.0-preview2) ✗ kh logs karmada-controller-manager-685f8c9d6d-7bqjf -nkarmada-system|grep Deleted
I1220 03:14:25.187515       1 objectwatcher.go:210] Deleted resource(kind=Deployment, default/deploy-01) on cluster: member1
`

**Comment by zhzhuang-zju** [comment]
@vincentgoat  Can you provide more detailed information? For example, how long does it take to check whether the deployment has been cleared after recovery?

**Comment by zhzhuang-zju** [comment]
We have verified that the deployment will be cleaned after the cluster resumed from hibernation, but I feel it is necessary to test this scenario in `e2e` testing.
