### ISSUE TITLE
HelmRelease resource was not propagated to clusters

### ISSUE THREAD

**Issue by CrossainQi** [karmada-io/karmada#4457]
**What happened**:
HelmRelease resource was not propagated to clusters
**What you expected to happen**:
HelmRelease resource waspropagated to clusters
**How to reproduce it (as minimally and precisely as possible)**:
- Deploy flux crds on karmada cluster
- Deploy flux-controllers on clusters
- Build helmrepo and helmrelease yamls and deploy them on karmada cluster
- Builld PropagationPolicy yamls and deploy them on karmada cluster.
**Anything else we need to know?**:
flux-controllers on clusters
~~~sh
# kubectl get po -n flux-system
NAME                                           READY   STATUS    RESTARTS   AGE
helm-controller-57c87f4bb9-5bps8               1/1     Running   0          38m
image-reflector-controller-7d4bb5454-tbdt7     1/1     Running   0          38m
source-controller-774f679857-prg9w             1/1     Running   0          38m
kustomize-controller-6f89bc5987-6sk69          1/1     Running   0          38m
notification-controller-5d5b74d7f9-gknjz       1/1     Running   0          38m
image-automation-controller-84d894cf64-vqpm6   1/1     Running   0          38m
~~~

helmrelease and helmrepo yamls
~~~yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: alkaid-repo
spec:
  interval: 1m
  url: https://ecr-sh.yun.internal.cn/chartrepo/alkaid
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubevirt-vnc-operator
  namespace: vnc
spec:
  interval: 5m
  chart:
    spec:
      chart: kubevirt-vnc-operator
      version: 1.1.13
      sourceRef:
        kind: HelmRepository
        name: alkaid-repo
~~~

propagationpolicy
~~~yaml
# vnc-propagationpolicy.yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helm-repo
spec:
  resourceSelectors:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmRepository
      name: alkaid-repo
  placement:
    clusterAffinity:
      clusterNames:
        - qph-k3s01
        - qph-k3s02
        - qph-k3s03
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: helm-release
spec:
  resourceSelectors:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: kubevirt-vnc-operator
      namespace: vnc
  placement:
    clusterAffinity:
      clusterNames:
        - qph-k3s01
        - qph-k3s02
        - qph-k3s03
~~~

helmrepo on cluster
~~~sh
# kubectl get helmrepo
NAME          URL                                                  AGE   READY   STATUS
alkaid-repo   https://ecr-sh.yun.internal.cn/chartrepo/alkaid   14m   True    stored artifact: revision 'sha256:c10585fe1d185ed9d9397ec2582f1a056cf84a8c04c3a1864d6f73eed943482d'
~~~
helmrelease on cluster
~~~sh
# kubectl get helmrelease -A
No resources found
~~~

helmrelease on karmada cluster
~~~sh
# k get helmrelease -A
NAMESPACE   NAME                    AGE   READY   STATUS
vnc         kubevirt-vnc-operator   17m
~~~

**Environment**:
- Karmada version: v1.8.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): 
~~~sh
karmadactl version: version.Info{GitVersion:"v1.8.0", GitCommit:"c8811b66304614a3bcfcc21a31ffda8c83781682", GitTreeState:"clean", BuildDate:"2023-11-30T19:03:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
~~~
- Others: 
~~~sh
# helm pull alkaid-repo/kubevirt-vnc-operator
# ls
kubevirt-vnc-operator-1.1.13.tgz
~~~

**Comment by CrossainQi** [comment]
update: I set the namespace option in propagationpolicy yaml like below then to find helmrelease resource appears on my child cluster. but the status of helmrelease is abnormal like below, is there any suggestions?
~~~sh
# kubectl get helmrelease -A
NAMESPACE   NAME                    AGE     READY   STATUS
vnc         kubevirt-vnc-operator   3m20s   False   HelmChart 'vnc/vnc-kubevirt-vnc-operator' is not ready: latest generation of object has not been reconciled

~~~

**Comment by RainbowMango** [comment]
> update: I set the namespace option in propagationpolicy yaml like below then to find helmrelease resource appears on my child cluster

Yeah, the `PropagationPolicy` can only propagate the resources in the current namespace. See [what's the difference between PropagationPolicy and ClusterPropagationPolicy](https://karmada.io/docs/faq/#what-is-the-difference-between-propagationpolicy-and-clusterpropagationpolicy) for more details.

> but the status of helmrelease is abnormal like below, is there any suggestions?

I'm not sure, just a guess, the status of `HelmRelease` is managed by `flux` or `kubevirt-vnc-operator` in the member cluster. I don't know what's going on there. Karmada just sync the status back, and would not update it.
