### ISSUE TITLE
Add `karmadactl annotate` command

### ISSUE THREAD

**Issue by Affan-7** [karmada-io/karmada#4466]
**What would you like to be added**:
Add the `karmadactl annotate` command.

**Why is this needed**:
Users may want to use the `annotate` command from the karmadactl. Currently the karmadactl doesn't support the `annotate` command, so users would have to switch to the `kubectl` to run it. Adding the annotate command into the karmadactl will enhance the user experience and take karmadactl one step closer to become independent of kubectl.

Part of #4291.

**Design**:
The karmadactl will communicate with the Karmada API server to add, remove or update the annotations. A user must specify a single member cluster using `--cluster` flag to perform this action.

**Comment by Affan-7** [comment]
Hi @RainbowMango,

What do you think of it?

**Comment by zhzhuang-zju** [comment]
@Affan-7 Hi~Command `kubectl annotate` is used to add or update the annotations of one or more resources. Can you introduce what you think is the function of `karmadactl annotate` in multi-cluster scenarios and its enhancements compared to `kubectl annotate`? When you start your development work, you can first introduce your design, such as what are the input parameters and their meaning and assignment.

**Comment by Affan-7** [comment]
@zhzhuang-zju

Just updated the description. I would love to hear your thoughts.

>Design:
The karmadactl will communicate with the Karmada API server to add, remove or update the annotations. A user must specify a single member cluster using --cluster flag to perform this action.

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju
> 
> Just updated the description. I would love to hear your thoughts.
> 
> > Design:
> > The karmadactl will communicate with the Karmada API server to add, remove or update the annotations. A user must specify a single member cluster using --cluster flag to perform this action.

Thank you for providing your thoughts. However, as `annotate` is a command that can modify resources, I do not recommend using it directly on member clusters. In fact, when updating the annotations on one or more resources directly on a member cluster, Karmada will re-modify them to their previous state. Like
```shell
(base) ➜  karmada git:(crypt) ✗ ka annotate deployment deploy-01 description='my frontend'
deployment.apps/deploy-01 annotated
(base) ➜  karmada git:(crypt) ✗ ka get deployment deploy-01 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: my frontend
...
(base) ➜  karmada git:(crypt) ✗ km2 get deployment deploy-01 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: my frontend
...
(base) ➜  karmada git:(crypt) ✗ km2 annotate --overwrite deployment deploy-01 description='test'
deployment.apps/deploy-01 annotated
(base) ➜  karmada git:(crypt) ✗ km2 get deployment deploy-01 -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: my frontend
...
```
We can also find that when annotating control plane resources, the modifications have been synchronized to the member clusters, so it seems that there is no need to implement the annotate command specifically for the member clusters.

**Comment by Affan-7** [comment]
@zhzhuang-zju

Do you have a better idea to implement the annotations or we should close the issue?

**Comment by zhzhuang-zju** [comment]
@Affan-7  Previously, at a weekly meeting, we discussed how to improve the karmadactl experience and found that users are more interested in commands for Karmada’s unique scenarios, such as promote, or commands with enhanced capabilities relative to kubectl. So I think you can think about it from the above two perspectives. This is more difficult than simply applying kubectl's capabilities to karmada. I haven't have a good idea yet. If there is any progress on my side, I will ping you as soon as possible.
