### ISSUE TITLE
work should be recreated when it has been deleted

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#447]
**What happened**:
When the work has been deleted, it will not recreated by binding controller.
```bash
kubectl create -f propagationpolicy.yaml
kubectl create -f deployment.yaml
kubectl delete work -n karmada-es-member1 default-nginx-deployment
```
Now something has been wrong, the work no longer exists. However, the workload still seems to be normal.
```
[root@garrybest ~]# kubectl get deployments.apps
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/2     2            2           5h31m
```

**What you expected to happen**:
The `work` should be recreated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
> Now something has been wrong, the work no longer exists.

Why? Does the work object be removed manually?

**Comment by Garrybest** [comment]
> Why? Does the work object be removed manually?

Yes, we found it happens when work is removed manually.

**Comment by RainbowMango** [comment]
Does this issue still exist in master?

**Comment by Garrybest** [comment]
Yes, but it's not a big problem. We hardly remove it manually.

**Comment by XiShanYongYe-Chang** [comment]
Hi @Garrybest , I test this on my side with the latest version(v1.1.0), it works ok:
```
# kubectl get work -A
NAMESPACE            NAME                              APPLIED   AGE
karmada-es-member1   web-6f9c988bc9                    True      2s  # I delete it manually, and it recreated.
karmada-es-member1   web-7b7cc5b9ff                    True      25m
```

**Comment by Garrybest** [comment]
Thanks @XiShanYongYe-Chang. I made a mistake cause I am using the older version of karmada. 😅
