### ISSUE TITLE
Replace distribution/distribution dependencies

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#4471]
**What would you like to be added**:
Replace dependencies `github.com/distribution/distribution/v3` with `distribution/reference`.

**Why is this needed**:
Currently Karmada depends on [github.com/distribution/distribution/v3](https://github.com/distribution/distribution) at [pkg/util/imageparser](https://github.com/karmada-io/karmada/blob/2ffe976180c7e691ffb433a3e67fe6a9863c44d3/pkg/util/imageparser/parser.go#L24), but now the referencing package `reference` has been moved to a dedicated repo(https://github.com/distribution/reference), we should update the reference in go.mod:
https://github.com/karmada-io/karmada/blob/2ffe976180c7e691ffb433a3e67fe6a9863c44d3/go.mod#L7 to avoid security concerns.

**Special notes**:
- This task should wait for #4463, otherwise conflicts.
- Pin to the latest release of `distribution/reference`: [v0.5.0](https://github.com/distribution/reference/releases/tag/v0.5.0).

**Comment by whitewindmills** [comment]
okay, I'll do that after your PR.
/assign
