### ISSUE TITLE
Webhook server alerts 'remote error: tls: bad certificate'

### ISSUE THREAD

**Issue by tpiperatgod** [karmada-io/karmada#4478]
**What happened**:

I wrote a new webhook server followed by [customresourceinterpreter example](https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter). Then I deployed it in a self-defined namespace, and I built it with `webhook-cert` (a copy of `karmada-webhook-cert` under the `karmada-system` namespace) and `kubeconfig` (a copy of `kubeconfig` under the `karmada-system` namespace), but it runs with: `remote error: tls: bad certificate`.

While deploying the webhook server with the default `karmada-webhook-cert` and `kubeconfig` secrets under the `karmada-system` namespace, it runs fine.

I'm not sure if this is a bug or not, please feel free to correct my configuration errors if they exist.

As well the `url` in my resourceinterpreterwebhookconfiguration is correct, it's adapted to the namespace where the webhook-server is located, also the `caBundle` is copied from karmada ca.crt.

**What you expected to happen**:

I expected the webhook server to work in any namespace.

**How to reproduce it (as minimally and precisely as possible)**:

1. change the namespace of the interpreter-webhook-example workload
2. copy the karmada-webhook-cert and kubeconfig from karmada-system into a specific namespace
3. change the url in resourceinterpreterwebhookconfiguration with new webhook server svc
4. apply the crd

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.8.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.8.0
- Others: golang 1.20\ k8s v1.23.10

**Comment by XiShanYongYe-Chang** [comment]
Hi @tpiperatgod, Are the other control plane components of Karmada deployed in the `karmada-system` namespace?

**Comment by XiShanYongYe-Chang** [comment]
I tested it locally using `kind`, and it worked fine. I deployed the webhook in the test namespace.

![image](https://github.com/karmada-io/karmada/assets/78244870/ff875252-dbf1-4bb9-8b51-446a8c7e370a)

![image](https://github.com/karmada-io/karmada/assets/78244870/03d7b7b0-58f5-4031-af7c-e13213388a4c)

**Comment by XiShanYongYe-Chang** [comment]
After modifying the path of the URL to the domain name: 
```
https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload
```
I reproduced the error you pointed out. 

This error is reported by the server. When checking the logs of the client (karmada-controller-manager), I found that it shows an error as follows:

```log
W1226 12:45:27.230961       1 customized.go:171] Failed calling webhook examples/workloads.example.com: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
E1226 12:45:27.230999       1 detector.go:801] Failed to customize replicas for workload.example.io/v1alpha1, Kind=Workload(nginx), Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
E1226 12:45:27.231012       1 detector.go:441] Failed to build resourceBinding for object: workload.example.io/v1alpha1, kind=Workload, default/nginx. error: Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
```

From the logs, it can be seen that the domain name used for access is no longer within the target range, so the client has disconnected.

In the testing environment of Karmada, this is controlled in script `hack/deploy-karmada.sh`: 

https://github.com/karmada-io/karmada/blob/303f2cd24bf5d750c2391bb6699ac89d78b3c43f/hack/deploy-karmada.sh#L155

If you want to access the webhook service in another namespace using a domain name, please use the correct certificate.

**Comment by tpiperatgod** [comment]
> After modifying the path of the URL to the domain name:
> 
> ```
> https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload
> ```
> 
> I reproduced the error you pointed out.
> 
> This error is reported by the server. When checking the logs of the client (karmada-controller-manager), I found that it shows an error as follows:
> 
> ```
> W1226 12:45:27.230961       1 customized.go:171] Failed calling webhook examples/workloads.example.com: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
> E1226 12:45:27.230999       1 detector.go:801] Failed to customize replicas for workload.example.io/v1alpha1, Kind=Workload(nginx), Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
> E1226 12:45:27.231012       1 detector.go:441] Failed to build resourceBinding for object: workload.example.io/v1alpha1, kind=Workload, default/nginx. error: Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.test.svc.cluster.local:443/interpreter-workload?timeout=3s": tls: failed to verify certificate: x509: certificate is valid for kubernetes.default.svc, *.etcd.karmada-system.svc.cluster.local, *.karmada-system.svc.cluster.local, *.karmada-system.svc, localhost, not karmada-interpreter-webhook-example.test.svc.cluster.local
> ```
> 
> From the logs, it can be seen that the domain name used for access is no longer within the target range, so the client has disconnected.
> 
> In the testing environment of Karmada, this is controlled in script `hack/deploy-karmada.sh`:
> 
> https://github.com/karmada-io/karmada/blob/303f2cd24bf5d750c2391bb6699ac89d78b3c43f/hack/deploy-karmada.sh#L155
> 
> If you want to access the webhook service in another namespace using a domain name, please use the correct certificate.

thx, I'll try it.

**Comment by XiShanYongYe-Chang** [comment]
/assign

Let me add some notes to the README document.

**Comment by tpiperatgod** [comment]
Does it make sense to add a new command to update the certificate and reload the Karmada components?

**Comment by XiShanYongYe-Chang** [comment]
> Does it make sense to add a new command to update the certificate and reload the Karmada components?

I don't have much understanding of certificates. Can certificates be regenerated and hot-reloaded? My idea is that we may need to plan ahead.

Ask @chaosi-zju for help.

> Or is the recommended way to use `deinit` and then `init --cert-external-dns=''`?

I understand that this approach is feasible.
