### ISSUE TITLE
how to get karmada control panel prometheus metrics if I want  to use servicemonitor or podmonitor

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4481]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
I  did not find any port in service or karmada control panel pod to provider metrics
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by 13567436138** [comment]
![image](https://github.com/karmada-io/karmada/assets/31508490/f871a449-22e8-43d4-ba90-db56d68057a1)
为啥没权限呢，不是5443端口么

**Comment by 13567436138** [comment]
是不是什么开关没开

**Comment by chaunceyjiang** [comment]
@Poor12 Could you help answer this question?


I haven't used metrics from `karamda-apiserver`, I've only used metrics from `karmada-scheduler`. There wasn't anything special about how I configured it - I just used a normal `servicemonitor`.

**Comment by Poor12** [comment]
I am afraid karmada-apiserver's certificate is incorrect.
