### ISSUE TITLE
karmadactl 命令安装的集群，怎么升级

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4487]
**Please provide an in-depth description of the question you have**:
karmadactl 命令安装的集群，怎么升级
**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Karmada当前没有提供karmadactl升级方式。

**Comment by 13567436138** [comment]
只能用helm升级么

**Comment by 13567436138** [comment]
operator怎么升级
