### ISSUE TITLE
如何通过karmada控制面apiserver代理访问成员集群

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#451]
比如分发文件到成员集群中的pod, 希望能通过控制面的apiserver代理到实际的目标集群。

**Comment by RainbowMango** [comment]
如果 `join` 集群时使用的KUBECONFIG文件中带了Proxy信息，那么Karmada就会使用代理于成员集群通信。

**Comment by GitHubxsy** [comment]
我理解@chestarss   的意思是，想通过 karmada-apiserver统一入口 访问成员集群。 
扩展Kubernetes API方式
	CustomResourceDefinition 扩展 Kubernetes API
	通过聚合层（Aggregation Layer）扩展 Kubernetes API
	设置 Konnectivity 服务（egressSelector ）
		https://github.com/kubernetes-sigs/apiserver-network-proxy
	代理模式
		kubectl 代理
			kubectl proxy --port=8080
			curl http://localhost:8080/api/
		apiserver proxy
                      http://kubernetes_master_address/api/v1/namespaces/namespace_name/services/service_name[:port_name]/proxy

以上是几种扩展kubernetes API的方式。也许有用。 @chestarss  你有更好的想法吗？

**Comment by chestarss** [comment]
> 我理解@chestarss 的意思是，想通过 karmada-apiserver统一入口 访问成员集群。
> 扩展Kubernetes API方式
> 
> 1. CustomResourceDefinition 扩展 Kubernetes API
> 2. 通过聚合层（Aggregation Layer）扩展 Kubernetes API
> 3. 设置 Konnectivity 服务（egressSelector ）
>    https://github.com/kubernetes-sigs/apiserver-network-proxy
> 4. 代理模式
> 
> * kubectl 代理
>   ```
>     	kubectl proxy --port=8080
>     	curl http://localhost:8080/api/
>   ```
> * apiserver proxy
>   ```
>                   http://kubernetes_master_address/api/v1/namespaces/namespace_name/services/service_name[:port_name]/proxy
>   ```
> 
> 以上是几种扩展kubernetes API的方式。也许有用。 @chestarss 你有更好的想法吗？

正常情况访问 https://karmada-apiserver/api/v1/namespaces 返回控制面的ns列表。
如果要获取成员某个集群的ns列表，api扩展支持下类似
https://karmada-apiserver/api/v1/namespaces?cluster=member1
https://karmada-apiserver/api/v1/namespaces?cluster=member2

**Comment by RainbowMango** [comment]
Yeah, that's the [planed feature](https://github.com/karmada-io/karmada/blob/master/ROADMAP.md#2021-q3) `Aggregated K8s API endpoint`.

No clear solution yet.

**Comment by wuzhengxuan** [comment]
> 我理解@chestarss 的意思是，想通过 karmada-apiserver统一入口 访问成员集群。
> 扩展Kubernetes API方式
> 
> 1. CustomResourceDefinition 扩展 Kubernetes API
> 2. 通过聚合层（Aggregation Layer）扩展 Kubernetes API
> 3. 设置 Konnectivity 服务（egressSelector ）
>    https://github.com/kubernetes-sigs/apiserver-network-proxy
> 4. 代理模式
> 
> * kubectl 代理
>   ```
>     	kubectl proxy --port=8080
>     	curl http://localhost:8080/api/
>   ```
> * apiserver proxy
>   ```
>                   http://kubernetes_master_address/api/v1/namespaces/namespace_name/services/service_name[:port_name]/proxy
>   ```
> 
> 以上是几种扩展kubernetes API的方式。也许有用。 @chestarss 你有更好的想法吗？

如果在karmada创建了deployment，从karmada获取成员集群所有pod的信息，后续是否有考虑支持呢

**Comment by RainbowMango** [comment]
> 如果在karmada创建了deployment，从karmada获取成员集群所有pod的信息，后续是否有考虑支持呢

不仅pod信息，成员集群所有资源信息都会提供查询接口或组件，相关设计正在进行中。如果有任何意见或建议都可以提出来。

针对Pod，可以有更具体的支持，比如查看运行日志，远程登入等。

**Comment by RainbowMango** [comment]
/close
Continue the discussion on https://github.com/karmada-io/karmada/discussions/1077.
