### ISSUE TITLE
The problem of using karmadactl plug-in to install karmada in kind cluster

### ISSUE THREAD

**Issue by gitlayzer** [karmada-io/karmada#4523]
Does this error require me to modify some kernel parameters?

I0109 03:29:06.472887       1 webhook.go:106] karmada-webhook version: version.Info{GitVersion:"v1.8.1", GitCommit:"7b1f8dcbb6f44b6ecfa8a62c4b6a3618c8887e81", GitTreeState:"clean", BuildDate:"2023-12-19T01:51:48Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
I0109 03:29:06.476219       1 webhook.go:138] Registering webhooks to the webhook server
I0109 03:29:06.476898       1 internal.go:360] "Starting server" kind="health probe" addr="[::]:8000"
I0109 03:29:06.477078       1 shared_informer.go:341] caches populated
I0109 03:29:06.477146       1 server.go:50] "starting server" path="/metrics" kind="metrics" addr="[::]:8080"
I0109 03:29:06.477174       1 internal.go:581] "Stopping and waiting for non leader election runnables"
I0109 03:29:06.477211       1 server.go:43] "shutting down server" path="/metrics" kind="metrics" addr="[::]:8080"
I0109 03:29:06.477268       1 internal.go:585] "Stopping and waiting for leader election runnables"
I0109 03:29:06.477277       1 internal.go:591] "Stopping and waiting for caches"
I0109 03:29:06.477283       1 internal.go:595] "Stopping and waiting for webhooks"
I0109 03:29:06.477288       1 internal.go:599] "Wait completed, proceeding to shutdown the manager"
E0109 03:29:06.477294       1 webhook.go:165] webhook server exits unexpectedly: too many open files
E0109 03:29:06.477316       1 run.go:74] "command failed" err="too many open files"

**Comment by gitlayzer** [comment]
Already found the relevant processing method [Karmada](https://karmada.io/zh/docs/next/troubleshooting/trouble-shooting/)

**Comment by gitlayzer** [comment]
If you are using Kind, you can configure the following parameters directly to the host of the Kind cluster, so that the Webhook can run normally.

sysctl fs.inotify.max_user_watches=16384
sysctl -w fs.inotify.max_user_watches=100000
sysctl -w fs.inotify.max_user_instances=100000

**Comment by RainbowMango** [comment]
Yeah, it's a common issue, and that's why it present on the trouble shooting issues.
