### ISSUE TITLE
failed to use "update-estimator-protobuf.sh" to generated proto code?

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4529]
**What happened**:

when I updated `pkg/estimator/pb/types.go`, I change `MaxAvailableReplicasRequest` to following:

```go
// MaxAvailableReplicasRequest represents the request that sent by gRPC client to calculate max available replicas.
type MaxAvailableReplicasRequest struct {
	// Cluster represents the cluster name.
	// +required
	Cluster string `json:"cluster" protobuf:"bytes,1,opt,name=cluster"`
	// ReplicaRequirements represents the requirements required by each replica.
	// +required
	ReplicaRequirements ReplicaRequirements `json:"replicaRequirements" protobuf:"bytes,2,opt,name=replicaRequirements"`
	// Namespace namespace
	// +optional
	Namespace string `json:"namespace" protobuf:"bytes,3,opt,name=namespace"`
}
```

then I use `hack/update-estimator-protobuf.sh` to generate proto code, it did nothing?

Beg for help about how to use `hack/update-estimator-protobuf.sh` to generate proto code, it did nothing?

**What you expected to happen**:

generate proto code successful.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by chaosi-zju** [comment]
@Garrybest can you help this question?

**Comment by RainbowMango** [comment]
@chaosi-zju Please check if the files are generated at $GOPATH/src/github.com/karmada-io/karmada.

**Comment by chaosi-zju** [comment]
yes

**Comment by chaosi-zju** [comment]
> Please check if the files are generated at $GOPATH/src/github.com/karmada-io/karmada.

@RainbowMango you are right, I have found it

**Comment by RainbowMango** [comment]
So, please make sure `karmada-io/karmada` repo is cloned at `$GOPATH/src/github.com/`.

**Comment by chaosi-zju** [comment]
> So, please make sure `karmada-io/karmada` repo is cloned at `$GOPATH/src/github.com/`.

I think this is so troublesome, I submit a  PR #4530, what do you think about this modification？
