### ISSUE TITLE
Local-up-karmada.sh delete all kind cluster, this will delete user kind clusters.

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#4543]
Local-up-karmada.sh delete all kind cluster, this will delete user kind clusters.

/remove-kind feature
/kind cleanup

Create this issue to increase visibility.

Releated PR:

- https://github.com/karmada-io/karmada/pull/4462
- https://github.com/karmada-io/karmada/pull/3762
- https://github.com/karmada-io/karmada/pull/4542

**Comment by zhzhuang-zju** [comment]
/close
As all tasks have been finished.
