### ISSUE TITLE
Extend the Cluster.Status.APIEnablements.Resources

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#459]
**What would you like to be added**:
I suggest to extend the current definition for 
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/apis/cluster/v1alpha1/types.go#L143

from plain string to structure like this:
```
Resources struct {
  	// name is the plural name of the resource.
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// kind is the kind for the resource (e.g. 'Foo' is the kind for a resource 'foo')
	Kind string `json:"kind" protobuf:"bytes,3,opt,name=kind"`
}
```

Since we let user define resource propagated with `Kind` as:
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/apis/policy/v1alpha1/propagation_types.go#L58-L81

Think about the case, if we want to guard in scheduler phase to avoid deploy a resource to target cluster which has no related `CRD` installed we need to check the `APIEnablements` in `cluster.status`, but only `GVR` there and no `GVK`, it's expensive to map `GVK` to `GVR` in scheduler phase. 
**Why is this needed**:

**Comment by RainbowMango** [comment]
That makes sense to me.
cc @kevin-wangzefeng @mrlihanbo How do you think?

@vincent-pli 
By the way, are you trying to add the filter for `karmada-scheduler`?

**Comment by mrlihanbo** [comment]
That makes sense to me.

**Comment by vincent-pli** [comment]
Yes, I'm trying @RainbowMango

**Comment by RainbowMango** [comment]
Alternative 1(Proposed by this issue):
```golang
// APIResource specifies the name of a resource.
type APIResource struct {
	// Name is the plural name of the resource. (e.g. '')
	// +required
	Name string `json:"name"`
	// Kind is the kind for the resource (e.g. 'Deployment' is the kind for resource 'deployments')
	// +required
	Kind string `json:"kind"`
}
```
My concern about this alternative is the `Name` might never be used by now, it will be a redundant field.

Alternative 2:
```
// APIResource specifies the name of a resource.
type APIResource struct {
	// Kind is the kind for the resource (e.g. 'Deployment' is the kind for resource 'deployments')
	// +required
	Kind string `json:"kind"`
}
```
This alternative only collects the `Kind` and if there is a need for other information(such as `Name`, `ShortNames`, etc..), we can add them then and won't violate API compatibility.

@kevin-wangzefeng @vincent-pli What's your preference?

**Comment by vincent-pli** [comment]
I'm ok for both, but there is a little weird only has `Kind` field in a structure named `APIResource` . anyway, both is fine for me.
@RainbowMango

**Comment by vincent-pli** [comment]
So, any update? @RainbowMango

**Comment by RainbowMango** [comment]
Let's give some time to @kevin-wangzefeng .

**Comment by kevin-wangzefeng** [comment]
I'd suggest this one:
```go
// APIResource specifies the name of a resource.
type APIResource struct {
	// Name is the plural name of the resource. 
	// +required
	Name string `json:"name"`
	// Kind is the kind for the resource (e.g. 'Deployment' is the kind for resource 'deployments')
	// +required
	Kind string `json:"kind"`
}
```

**Comment by RainbowMango** [comment]
OK. @vincent-pli let's do it.

**Comment by vincent-pli** [comment]
Do I need also change the code here? @RainbowMango 
https://github.com/karmada-io/api/blob/a5e12cb59b9603773f743fe679a2a2aaff36b4e7/cluster/v1alpha1/types.go#L138
