### ISSUE TITLE
Is there a way to replicate existing CRD resources from the cluster where the Karmada control plane is located into the Karmada control plane?

### ISSUE THREAD

**Issue by fizos** [karmada-io/karmada#4606]
Is there a convenient way to synchronize the existing CRDs installed in a Kubernetes cluster to the Karmada control plane when transforming the cluster into a Karmada control plane?

**Comment by RainbowMango** [comment]
Maybe `karmadactl promote` can help:
```
karmadactl promote <kind>.<version>.<group> <name>  -C cluster1 --auto-create-policy=false
```
Please have a try and let us know if it works for you.

**Comment by fizos** [comment]
The operation failed due to an error: the CustomResourceDefinition.v1.apiextensions.k8s.io or DestinationRule does not exist in the cluster.

I have a single cluster where Istio was installed prior to the Karmada control plane. My objective is to copy the Istio CRDs into Karmada, without the need for reinstalling these CRDs again.

**Comment by RainbowMango** [comment]
> The operation failed due to an error: the CustomResourceDefinition.v1.apiextensions.k8s.io or DestinationRule does not exist in the cluster.

Just a guess, you might have to specify `--cluster-kubeconfig=` flag if you didn't set the KUBECONFIG to the target member cluster, that is:
```
karmadactl promote <kind>.<version>.<group> <name>  -C cluster1 --auto-create-policy=false --cluster-kubeconfig=<member cluster kubeconfig>
```
If it still not work, please share more details of your operations, so that we can try to reproduce it on my side.

**Comment by fizos** [comment]
Command execution successful, returned "Resource "apiextensions.k8s.io/v1, Resource=customresourcedefinitions"(destinationrules.networking.istio.io) is promoted successfully."
Thank you！
