### ISSUE TITLE
karmada中部署karmada可行么

### ISSUE THREAD

**Issue by 13567436138** [karmada-io/karmada#4614]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
karmada中部署karmada可行么
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
这有可能是行不通的，detector 分发资源时会过滤掉 karmada 的 CRD 资源，比如说 PropagationPolicy 等，你可以把这个限制去掉试试。

你的具体场景是什么呢？我们可以根据具体的场景来进行讨论，然后挖掘出一些有价值的需求。

**Comment by 13567436138** [comment]
灾备karmada
