### ISSUE TITLE
Add autoscaling/v1alpha1 import alias

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#4619]
**Task description**:

Add `autoscaling/v1alpha1` import alias.

**Solution**:

Just like this:

https://github.com/karmada-io/karmada/blob/f03b5e9803e4738706bb6fcf807350a55a4ad703/hack/.import-aliases#L54-L61

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by ipsum-0320** [comment]
I want to give a try.

/assign

**Comment by XiShanYongYe-Chang** [comment]
@ipsum-0320 Thanks~

**Comment by ipsum-0320** [comment]
> @ipsum-0320 Thanks~

@XiShanYongYe-Chang hi, I just want to confirm if my plan is correct.

1. add `"github.com/karmada-io/karmada/pkg/apis/autoscaling/v1alpha1": "autoscalingv1alpha1"` to the file `hack/.import-aliases`;
2. execute the bash file `hack/update-import-aliases.sh`;

hope your reply!

**Comment by XiShanYongYe-Chang** [comment]
Hi @ipsum-0320, it is correct.

**Comment by ipsum-0320** [comment]
> Hi @ipsum-0320, it is correct.

thanks a lot! This is my first step towards open source, and I will continue to work hard next.

**Comment by ipsum-0320** [comment]
@XiShanYongYe-Chang  I have commit the PR, any question?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang I have commit the PR, any question?

Ok, I have left some comments.
