### ISSUE TITLE
Cannot create workload that has a long name

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#463]
**What happened**:
When a workload has a long name, it cannot be created in the member cluster because it has a label associated with `work` whose name is more than 63 characters. In kubernetes, label must be 63 characters or less according to [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set). The name of `work` contains name, namespace and kind of a workload so its name must be longer than the workload itself.

**What you expected to happen**:
The workload in member cluster must be created. I think we could move all label keys in `constants.go` into object annotations which does not have a length limit.

**How to reproduce it (as minimally and precisely as possible)**:
Create a configmap whose name is `e1d4477a478c4797b03d22281718bd50-actor-configmap`. It cannot be create successfully in member cluster. The agent will logs some errors: 
`Failed to create resource in the given member cluster karmada-large-scale-test-member1, err is ConfigMap "e1d4477a478c4797b03d22281718bd50-actor-configmap" is invalid: metadata.labels: Invalid value: "default-e1d4477a478c4797b03d22281718bd50-actor-configmap-configmap": must be no more than 63 characters`.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
I wonder if it, a resource takes a long name, is a usual scenario?
There is another approach that wants to restrict the resource name as tracked by #209

**Comment by Garrybest** [comment]
> I wonder if it, a resource takes a long name, is a usual scenario?

It happens in my scenario because most of the workload are AI training jobs that have a random uuid and other infos. If the name is more than 40 characters, the name of `work` is likely to be more than 63 characters. Meanwhile, I don't find any usage of label selectors with these labels so maybe it can be moved into annotations. What do you think? @RainbowMango

**Comment by RainbowMango** [comment]
> I think we could move all label keys in constants.go into object annotations

Move all label keys?

**Comment by Garrybest** [comment]
> > I think we could move all label keys in constants.go into object annotations
> 
> Move all label keys?

To fix this issue we now may only need to move label `work.karmada.io/name` to annotations. If we want to keep consistency, we can move other labels such as `work.karmada.io/namespace`, "resourcebinding.karmada.io/name" into annotations too. @RainbowMango

**Comment by RainbowMango** [comment]
I guess what you mean is moving all labels that added to the [Mainifest](https://github.com/karmada-io/karmada/blob/83b9682fd2149e1086746a0d2bd7158c09b97c8c/pkg/apis/work/v1alpha1/work_types.go#L39) to annotations, right?

The constants have the `label` suffix, we should take care of them together.

**Comment by Garrybest** [comment]
How about discussing this issue at tomorrow meeting? @RainbowMango

**Comment by RainbowMango** [comment]
We don't have a meeting tomorrow.

What you are talking about is the labels on `Manifest`, not on `Work`/`ResourceBinding`/`PropagationPolicy`, right?

/priority important-soon

**Comment by Garrybest** [comment]
Right, this problem will be solved if the labels in `Manifest ` are moved into annotations.
