### ISSUE TITLE
When installing karmada using the operator, provide a way to annotate karmadaAPIServer services

### ISSUE THREAD

**Issue by endrec** [karmada-io/karmada#4634]
**What would you like to be added**:

The current schema provides a `spec.components.karmadaAPIServer.annotations` field, but this is only used for the created pod, and not the service.
It would be useful to specify annotations on the service as well, either by populating service annotations using this same field, or by introducing a new field `serviceAnnotations`.

**Why is this needed**:

Annotations on `service` resources are used by different add-ons. 
In my current use case I'd like to expose karmada-api to argoCD, but our argoCD runs in a different cluster, even in a different cloud. I can see two ways to achieve this:
- use `serviceType: LoadBalancer` and annotate the service with `external-dns.alpha.kubernetes.io/hostname`, or
- create an `Ingress`. I'm using Google's built in ingress controller, which needs an annotation on the service to enable HTTPS traffic to the backend. (Nginx uses an annotation on the ingress to achieve the same.)

**Comment by RainbowMango** [comment]
It's a reasonable use case, thanks for the spotting.
cc operator authors here . @calvin0327 and also @chaosi-zju

**Comment by calvin0327** [comment]
This case does make sense,  introducing a field `serviceAnnotations` is easy to implement the feature, but i don't know whether it's the best way? @chaosi-zju what do you think?

**Comment by RainbowMango** [comment]
Hi @endrec the feature that enables annotate karmadaAPIServer services has been included in v1.10. Don't know if you noticed that~ And looking forward to any feedback.
