### ISSUE TITLE
The new GVR remedy.karmada.io/v1alpha1 should to be added to SkippedResourceConfig.GroupVersionDisabled list

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4659]
**What happened**:

The new GVR `remedy.karmada.io/v1alpha1` should to be added to SkippedResourceConfig.GroupVersionDisabled list

**What you expected to happen**:

the new GVR should also be added to this function:

https://github.com/karmada-io/karmada/blob/4f75b3c577fdc79e5dcee5b56733265abc55b674/pkg/util/apigroup.go#L52-L72

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/assign @chaosi-zju 

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
@chaosi-zju Thanks~
I think it's more like a feature, how do you think?

**Comment by chaosi-zju** [comment]
> @chaosi-zju Thanks~ I think it's more like a feature, how do you think?

reasonable~

**Comment by chaosi-zju** [comment]
@XiShanYongYe-Chang so how to change this label ?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang so how to change this label ?

The modification method is the same as that of pr.

/kind feature
/remove-kind bug
