### ISSUE TITLE
typo error for karmada charts

### ISSUE THREAD

**Issue by warjiang** [karmada-io/karmada#4665]
**What happened**:
some typo errors in readme of charts 

**What you expected to happen**:
agent.imagePullSecrets should be corrected as `agent.image.pullSecrets`
![image](https://github.com/karmada-io/karmada/assets/6478745/70653d27-0971-4cdb-b998-43c47a55d158)

**How to reproduce it (as minimally and precisely as possible)**:
just check `values.yaml` and `readme` file
**Anything else we need to know?**:
NA
**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @warjiang thanks for your contribution!

Can you separate the solution of this issue from#4667 and submit a separate PR? If the code is processed separately, it is easier to promote code merging.

**Comment by warjiang** [comment]
> Hi @warjiang thanks for your contribution!
> 
> Can you separate the solution of this issue from#4667 and submit a separate PR? If the code is processed separately, it is easier to promote code merging.

For sure, i have already sperate the pr: https://github.com/karmada-io/karmada/issues/4665#issuecomment-1972326908.

**Comment by XiShanYongYe-Chang** [comment]
> For sure, i have already sperate the pr: [#4665 (comment)](https://github.com/karmada-io/karmada/issues/4665#issuecomment-1972326908).

Thanks a lot!

**Comment by XiShanYongYe-Chang** [comment]
In favor of #4673 
/assign @warjiang

**Comment by XiShanYongYe-Chang** [comment]
I think it's more appropriate to use the cleanup label. I updated it.
/kind cleanup
/remove-kind bug
