### ISSUE TITLE
add image pullSecrets for cfssl and kubeclt in charts

### ISSUE THREAD

**Issue by warjiang** [karmada-io/karmada#4666]
add imagePullSecret for cfssl and kubectl in case of private registry.
**Task description**:
add imagePullSecret for cfssl and kubectl , just like other images
**Solution**:
may be follow the implementation of  `webhook.image` or others
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by XiShanYongYe-Chang** [comment]
In favor of #4667
/assign @warjiang 
/kind feature
