### ISSUE TITLE
Cannot enble search add-on

### ISSUE THREAD

**Issue by danielepolencic** [karmada-io/karmada#4684]
It's not possible to enable the add-on with karmadactl:

```bash
$ echo $KUBECONFIG
/tmp/karmada/karmada-apiserver.config
```

```bash
$ kubectl get cluster
NAME      VERSION   MODE   READY   AGE
worker1   v1.28.7   Push   True    12m
```

```bash
$ kubectl karmada addons enable karmada-search
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
```

Same error for:

```bash
$ kubectl karmada --kubeconfig /tmp/karmada/karmada-apiserver.config addons enable karmada-search
```

This is on Karmada 1.9:

```bash
$ kubectl karmada version
karmadactl version: version.Info{GitVersion:"v1.9.0", GitCommit:"a03aa846cfd2c1978b166660d6f592a1c10aeb3d", GitTreeState:"clean", BuildDate:"2024-02-29T08:14:53Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"darwin/arm64"}
```

**Comment by RainbowMango** [comment]
@danielepolencic It's Great to meet you here, I followed you on Twitter, and thanks for sharing so many fantastic articles.
Are you going to share something about karmada-search? I'm glad to help with it.

For this issue, just a guess, you might need to ensure the operation is made towards the `karmada-host` cluster instead of the `karmada-apiserver`, since all the addons are installed on the host cluster.

```
$ kubectl karmada --kubeconfig=<host cluster kubeconfig> addons enable karmada-search
```

**Comment by danielepolencic** [comment]
I tried that too, but I see the same error.

I'm working on a [three-part educational series with Loft](https://www.vcluster.com/building-a-multi-tenant-kubernetes-platform/) and discussed Hierarchical Namespace Controller VS vCluster VS Karmada as three different approaches to multi-tenancy.

Episode 1 featured Karmada's architecture and trade-offs. In the last episode, I'd like to dig deeper and control workloads from the main Karmada instance — hence the need to set up the search add-on.

Also, thank you for the kind words!

**Comment by liangyuanpeng** [comment]
Try to:

```shell
kubectl karmada --kubeconfig <host cluster kubeconfig> --karmada-kubeconfig <karmada apiserver kubeconfig> addons enable karmada-search
```

**Comment by danielepolencic** [comment]
@liangyuanpeng this did the trick!

```
I0306 20:25:53.082159   99652 enable_option.go:210] Successfully enable addon karmada-search
```

**Comment by liangyuanpeng** [comment]
Error prompts will be a good improvement point. Anyone who is interested can create an issue to track functional improvements.

/kind support
/remove-kind bug

**Comment by liangyuanpeng** [comment]
Considering that this block user usage, perhaps it is reasonable to classify it as a bug.

**Comment by RainbowMango** [comment]
> Error prompts will be a good improvement point. Anyone who is interested can create an issue/PR to track it.

Do you mean we should dump which kubeconfig is missing? 
@liangyuanpeng

**Comment by liangyuanpeng** [comment]
@RainbowMango Yes, i have create https://github.com/karmada-io/karmada/pull/4717 to work for it.

**Comment by RainbowMango** [comment]
/assign @liangyuanpeng 
In favor of #4717.
