### ISSUE TITLE
`kubectl karmada join` does not support `--context --as --as-group`

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#4695]
**What would you like to be added**:
support for these 3 flags

**Why is this needed**:
otherwise I need to setup a special context and `use-context` to be able to use `join`

**Comment by RainbowMango** [comment]
For the `--context`, karmadactl(same as kubectl karmada) provides the two flags to specify the context for both karmada and member cluster:
```
    --cluster-context='':
	Name of cluster context in kubeconfig. The current context is used by default.
    --karmada-context='':
	The name of the kubeconfig context to use
```
Given `karmadatl join` might need two kubeconfigs, just one `--context` might be misleading as it can't represent which kubeconfig it applies to. 

Please let us know if the two flags meet your needs. Maybe I didn't understand your use case yet.

**Comment by RainbowMango** [comment]
For the `--as` and `--as-group`, I guess you mean the two flags in kubectl:
```bash
    --as='':
	Username to impersonate for the operation. User could be a regular user or a service account in a namespace.

    --as-group=[]:
	Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
```

I'd like to hear more details about the use case if you don't mind. We also need to consider which kubeconfig the two flags will be applied.

**Comment by grosser** [comment]
I'd need to impersonate admin on the host cluster, so `--cluster-as`

**Comment by grosser** [comment]
hmmm no the host cluster would be `--karmada-as` :)

**Comment by RainbowMango** [comment]
Yes, `--karmada-as` and `--karmada-as-group` are sounds good to me.
cc @XiShanYongYe-Chang What do you think?

**Comment by XiShanYongYe-Chang** [comment]
These two flags look good, but I don't understand one thing. Why do you need to use impersonate to join a cluster in Karmada?

**Comment by grosser** [comment]
I need to be cluster admin to join the cluster, our default context is
read-only.

**Comment by XiShanYongYe-Chang** [comment]
> I need to be cluster admin to join the cluster, our default context is read-only.

Is this safe? Should the admin user be the one to join the cluster?

**Comment by grosser** [comment]
It needs to be the admin user since the read-only user can't do it. We do
the same ATM by adding a new context first and then use use-context.

**Comment by XiShanYongYe-Chang** [comment]
> It needs to be the admin user since the read-only user can't do it. 

So you need to have the read-only user act as the admin user to join the cluster, is that correct?

> We do the same ATM by adding a new context first and then use use-context.

Sorry, I didn't quite understand that sentence. Can you explain it a little more?

**Comment by grosser** [comment]
A: yes
B: atm we make define a `foo-admin` context that connects to the same user that we otherwise want to assume, so I think with `--as` support things should just work

**Comment by grosser** [comment]
I can give it a try

**Comment by RainbowMango** [comment]
kindly ping @grosser are you still working on this? Do you need any help?

**Comment by grosser** [comment]
ah sry never got around to it 😞 
best don't add a milestone, I'll give it another try when I find some time

**Comment by RainbowMango** [comment]
no rush, take your time :)

**Comment by grosser** [comment]
https://github.com/karmada-io/karmada/pull/5016 for the --karmada-as-* flags
... getting the context set was more complicated so leaving that for another PR

**Comment by XiShanYongYe-Chang** [comment]
> getting the context set was more complicated so leaving that for another PR

Is it possible to submit them in one PR? Currently, only the flag is submitted, and there is no corresponding processing logic. I'm afraid that they are not in the same version, which may cause misunderstanding to the user.

**Comment by grosser** [comment]
the PR adds the --as-* and sets them on the client, I though that would do the trick ?
(context flag + setting it on the client can be a standalone PR)

**Comment by XiShanYongYe-Chang** [comment]
In favor of #5016 
/assign @grosser 

> the PR adds the --as-* and sets them on the client, I though that would do the trick ?

Hi @grosser, I think it will be ok, have you tested with the PR?

**Comment by XiShanYongYe-Chang** [comment]
Thanks @grosser ~
You have completed the tasks in this issue. Let me close this issue. Feel free to re-open this issue if you need any help.
/close
