### ISSUE TITLE
Add some labels to namespaces and ClusterRoles

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#4696]
**What would you like to be added**:
set `managed-by: karmada` label on namespaces and cluster-roles
... but ideally user-configureable labels so we can set "team=foo,project=bar"

**Why is this needed**:
we need labels on the namespaces and cluster-roles since we have a validating webhook that blocks
users from adding them without saying who owns them
we can add exceptions for karmada, but we'd at least need some `managed-by: karmada` label

**Comment by XiShanYongYe-Chang** [comment]
Hi @grosser thanks for your feedback, do you mean the resources propagated to the member clusters? Can you expand on your use case?

**Comment by grosser** [comment]
yes, the propagated resources

for example cluster role `karmada-controller-manager:karmada-<member-cluster>`
and the `karmada-es-<member-cluster>` namespace

**Comment by XiShanYongYe-Chang** [comment]
> set managed-by: karmada label on namespaces and cluster-roles

I understand that for the time being, this is satisfactory.

> for example cluster role karmada-controller-manager:karmada-<member-cluster>
> and the karmada-es-<member-cluster> namespace

Is this a label added to the resource? Can you give me a yaml template?

Are these values set directly by the user or does Karmada actively set them for these resources?

**Comment by grosser** [comment]
that would be labels to be added to the resources karmada creates

```
apiVersion: v1
kind: Namespace
metadata:
  labels:
    project: foo
  name: karmada-es-<member-cluster>
```

**Comment by grosser** [comment]
karmada creates these resources, so we need it to set them too
otherwise our validation webhook will deny the create request

**Comment by grosser** [comment]
1: afaik yes, most likely more things like clusterrolebinding too, but we did not get that far since it always crashed before, so ideally everything you can find, but we can start with these 2 and then see what is missing
2: app.kubernetes.io/managed-by from [well known labels](https://kubernetes.io/docs/reference/labels-annotations-taints/) would make more sense to me, but either is fine
3: they are internal labels we use, so would need some "labels" field so we can store them, afaik we can ignore that for now

**Comment by XiShanYongYe-Chang** [comment]
When should we add these labels, and how can we customize them? 

I don't have specific ideas yet, can you talk about your ideas?

**Comment by grosser** [comment]
Add when resources are created. For now no customization.

**Comment by a7i** [comment]
There are other resources such as Secrets, ServiceAccount as well.

I tried creating this PR here: https://github.com/karmada-io/karmada/pull/4620

but `karmada.io/managed: true` applies to all "normal" workload propagation as well. So we need a distinct label that identifies resources created for karmada itself. For example when we join a new cluster, the following are created:
- Namespace
- ClusterRole/ClusterRoleBinding
- ServiceAccount
- Secrets

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i Let me see if I understand you correctly. 

You are talking about adding two labels to Karmada resources. One is created by the Karmada system and the other is propagated by users through Karmada. Am I right? Or are the types of labels not limited to these two?

**Comment by a7i** [comment]
Hi @XiShanYongYe-Chang I am only interested in ones "created by the Karmada system".

As far as ones "propagated by users through Karmada", we have other labels that we could use (e.g.`clusterpropagationpolicy.karmada.io/name`)

**Comment by XiShanYongYe-Chang** [comment]
Thanks @a7i @grosser, I think I've been misunderstanding what you were saying before. By the comment in #3262, I think I understand the context,

Is the content described in the current issue to add the label `karmada.io/managed` to the resources created by the karmada system?

**Comment by grosser** [comment]
yes

**Comment by XiShanYongYe-Chang** [comment]
Ok! Would you like to contribute?

**Comment by grosser** [comment]
https://github.com/karmada-io/karmada/pull/4620 is a good start
and then we can try more, help appreciated if you know where/how to fix :)

**Comment by XiShanYongYe-Chang** [comment]
Hi @grosser, #4620 has been merged, do you have other tasks to do in the plan?

**Comment by grosser** [comment]
afaik all good now, will reopen if I see more gaps :)

**Comment by XiShanYongYe-Chang** [comment]
> afaik all good now, will reopen if I see more gaps :)

Thanks for your response.
