### ISSUE TITLE
Does  karmada can  prevent removal of these managed resources

### ISSUE THREAD

**Issue by CharlesQQ** [karmada-io/karmada#4709]
**What would you like to be added**:
Under normal circumstances,  delete resource  in  karmada  control plane， resource in mamber cluster will be deleted;
Is there any way to prevent removal of these managed resources?

**Why is this needed**:
Like  kubefed Annotation `kubefed.io/orphan: true`; this feature is useful to  rollback  when  resource  migrate to karmada; 
refer to (https://github.com/kubernetes-retired/kubefed/blob/master/docs/userguide.md)

**Comment by RainbowMango** [comment]
That sounds like a reasonable feature. I'd like to know when and how this feature would be used.

The Kubefed annotation `kubefed.io/orphan: true` is added to the `federated resources`, corresponding to Karmada `PropagationPolicy`. I tend to extend the API instead of introducing an annotation.

**Comment by XiShanYongYe-Chang** [comment]
I propose a simple idea. Add a new API, call it `RemovePolicy`, and define the target resource and the corresponding deletion policy in its resources, such as whether to keep the resources in the member cluster, or delete the resources in the member cluster synchronously, how much the deletion delay is, etc.

The idea is very rough, throw bricks lead jade.

**Comment by CharlesQQ** [comment]
|  That sounds like a reasonable feature. I'd like to know when and how this feature would be used.

Used to migrate some services from karmda. If the services migrated to karmada do not meet expectations, provide a rollback capability.

**Comment by CharlesQQ** [comment]
> I propose a simple idea. Add a new API, call it RemovePolicy, and define the target resource and the corresponding deletion policy in its resources, such as whether to keep the resources in the member cluster, or delete the resources in the member cluster synchronously, how much the deletion delay is, etc.

I agreed @RainbowMango idea, Add a new API might be too complicated

**Comment by XiShanYongYe-Chang** [comment]
Hi everyone, let's use umbrella issue #5577 to track this requirement.
/close
