### ISSUE TITLE
How to renew a certificate when it expires or needs to be replaced

### ISSUE THREAD

**Issue by x-7** [karmada-io/karmada#4723]
How to renew  certificates  when they expires or needs to be replaced。

my config:
i deploy karmada with helm .
i use "certs.mode.auto" mode.
my memeber clusters are in push model.

**Environment**: prod
- Karmada version:latest
- Kubernetes version: latest
- Others:

**Comment by watermeion** [comment]
any updates?

**Comment by watermeion** [comment]
how about this issue? Any update?
