### ISSUE TITLE
cosign install failed

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#4727]
**What happened**:

cosign install failed, https://github.com/karmada-io/karmada/actions/runs/8355006523

tracing at https://github.com/sigstore/cosign-installer/issues/158

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
Thanks @liangyuanpeng

**Comment by liangyuanpeng** [comment]
/reopen 
/assign

Still happen on signing image

**Comment by RainbowMango** [comment]
We have to backport both #4733 and #4736, right?

**Comment by RainbowMango** [comment]
Just sent #4745, #4746, and #4747 .
