### ISSUE TITLE
karmada promote ConfigMap make ownerReferences disappears

### ISSUE THREAD

**Issue by weidalin** [karmada-io/karmada#4728]
**Please provide an in-depth description of the question you have**:
Hello, I tried to promote resources from a member cluster for Karmada to manage.

I have two ConfigMaps with owner relationships in the member1 cluster. The second ConfigMap, named cm2, has its ownerReferences pointing to the first ConfigMap named cm1. When I use:
```
karmadactl promote configmap cm1 -C member1  
karmadactl promote configmap cm2 -C member1  
```
Karmada can successfully take over the management of these two ConfigMaps. However, the ownerReferences field in cm2 disappears. Is there any way to keep the ownerReferences while handing over the resources for Karmada to manage?
**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by weidalin** [comment]
@XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Let me take a look.
/assign

**Comment by XiShanYongYe-Chang** [comment]
> I have two ConfigMaps with owner relationships in the member1 cluster. The second ConfigMap, named cm2, has its ownerReferences pointing to the first ConfigMap named cm1.

Hi @weidalin, can you give me a yaml demo? Let me have a test.

**Comment by weidalin** [comment]
thank, this is my yaml, app env cm 10620  is set owner to app cm atms-app-conf-dy-1031-cp
app cm 
```
# app cm
apiVersion: v1
data:
  app-yaml: |
    metadata:
      appenvcmname: "10620"
      appid: 10620
      nodes:
      - deploymentname: dy-1031-cp-v1
        hwusage:
          hwname: null
          hwtype: CPU
        mmntver: 0
        name: v1
        status: ""
        traffic: 100
        type: ""
      - deploymentname: dy-1031-cp-v2
        mmntver: 0
        name: v2
        status: ""
        traffic: 0
        type: default
    status: normal
kind: ConfigMap
metadata:
  annotations:
    atms-app/cluster: executor-local
  labels:
    atms-app/creator: ATMS
  name: atms-app-conf-dy-1031-cp
  namespace: lwd-test
  resourceVersion: "50187386"
  uid: 06d49692-7195-4b46-8fce-2b370f50eaf4 # atfer apply it will generate a new uid
```
app env cm 
```
# app env cm
apiVersion: v1
data:
  test: "0"
kind: ConfigMap
metadata:
  labels:
    atms-app/cm-type: atms-env
    atms-app/creator: ATMS
  name: "10620"
  namespace: lwd-test
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: atms-app-conf-dy-1031-cp
    uid: 02e20613-4c16-4b99-a642-2b5d0a46c52d   # replace by new uid
  resourceVersion: "128387054"
  uid: e47e2824-39f7-4dad-b010-1e52135991ac
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @weidalin When `configmap` is promoted to the karmada control plane, a new uid will be generated, which means that it is no longer the same configmap as the configmapin the member cluster.

If `ownerReferences` is also promoted, configmap will be deleted directly.

**Comment by XiShanYongYe-Chang** [comment]
I would like to know what impact it will have on your business if the owner relationship is not premote to the karmada control plane. 

If we want to restore the owner relationship on the control plane, you may need to actively do something, such as parsing the owner relationship during the promote process.

To elaborate more, during the resource distribution process, the owner will also be lost for the same reason. If necessary, we may need to consider these two things together.

**Comment by weidalin** [comment]
Understood, thank you for your answer. Because we have set owner relationship in our previous business, deleting app-cm Configmap can automatically delete app-env-cm Configmap . If the owner relationship can also be propagated, our logic after migration does not need to change. Of course, if there is no owner relationship, we can also delete the app-cm Configmap and then proactively delete the app-env-cm Configmap. Thank you again, Karmada is a nice work.
