### ISSUE TITLE
Is the length of work manifests  always one? 

### ISSUE THREAD

**Issue by lcw2** [karmada-io/karmada#4730]
**Please provide an in-depth description of the question you have**:
```
work := &workv1alpha1.Work{
		ObjectMeta: workMeta,
		Spec: workv1alpha1.WorkSpec{
			Workload: workv1alpha1.WorkloadTemplate{
				Manifests: []workv1alpha1.Manifest{
					{
						RawExtension: runtime.RawExtension{
							Raw: workloadJSON,
						},
					},
				},
			},
		},
	}
```
 resourcebinding  have only a resourceTemplate,  resourcebinding -> work , the  length of manifests is one too? 

I want to know  whether the length of manifests is always 1,    in what situation will his quantity exceed 1?

**Comment by XiShanYongYe-Chang** [comment]
In Karmada's current usage, the manifest length is always 1. However, this does not guarantee that it will always be 1 in the future. Have you come across any specific use cases?

**Comment by lcw2** [comment]
we want to propogation deployment with  different namespace, for example ,  apply a deployment with namespace default in master cluster ,  but this deployment  with namespace test in member cluster A.    I found it's ok to propagation deployment with different namespace, but  resourcebinding aggregate status from work， which  have problem.

**Comment by lcw2** [comment]
<img width="779" alt="image" src="https://github.com/karmada-io/karmada/assets/43213497/acc0db9d-66ac-4c1d-87b4-91c76a2e8755">
because find index from manifests, must use namespace

**Comment by XiShanYongYe-Chang** [comment]
Yes. Currently, resources cannot be propagated across NSs.

**Comment by XiShanYongYe-Chang** [comment]
Hi @lcw2 Do you have any more questions?

By the way, are you going to use Karmada?

**Comment by lcw2** [comment]
no more questions.
I'm  going to use karmada.
