### ISSUE TITLE
Does Karmada have an API for Java?

### ISSUE THREAD

**Issue by wmxchn** [karmada-io/karmada#4732]
During the development of the project, Karmada needs to be redeveloped using java language.

**Comment by liangyuanpeng** [comment]
> Does Karmada have an API for Java?

 FYI: 
- https://github.com/karmada-io/api/issues/11

**Comment by XiShanYongYe-Chang** [comment]
Looks like a duplicate problem, close it first.

Please feel free to reopen it when you enter the problem.

/close
