### ISSUE TITLE
Karmada API to get all deployments and Create a new deployment

### ISSUE THREAD

**Issue by srikanthjeeva** [karmada-io/karmada#4734]
I have tried the following APIs. But these apis are getting data from K8S cluster.  

`# to get all deployment: GET: /apis/apps/v1/deployments`
`# to create deployment: POST : /apis/apps/v1/namespaces/default/deployments`

But these above APIs are not interacting with Karmada but returning the results from K8S Cluster that is hosting karmada. 

what API can i use to get the same data from Karmada? I'm looking for the Rest API similar to `karmadactl get deploy`

**Comment by XiShanYongYe-Chang** [comment]
Hi @srikanthjeeva, maybe you need to switch the context in kubeconfig to use `karmada-apiserver` instead of `karmada-host`:

![image](https://github.com/karmada-io/karmada/assets/78244870/4b78b94b-30c8-404c-bf73-ea3e40f70c15)

**Comment by srikanthjeeva** [comment]
hi @XiShanYongYe-Chang  - Ya. everything works fine when i use kubectl or karmadactl. But how can i do this from my Python application. I'm looking for a Rest API or a Python Module to create deployment with Karmada.

**Comment by XiShanYongYe-Chang** [comment]
> But how can i do this from my Python application. I'm looking for a Rest API or a Python Module to create deployment with Karmada.

Hi @srikanthjeeva I haven't used python to connect to Karmada, but I think it is the same way to access kubernetes rest api, you can find out how to use python to connect to kubernetes.

Looking forward to hearing your feedback!

**Comment by liangyuanpeng** [comment]
@srikanthjeeva 
You need to connect to karmada-apiserver, and it's export at node port of 32443. And then you  can got the data from karamada.

**Comment by srikanthjeeva** [comment]
Thanks all!  Was able to make a deployment by calling the following API

```
Request:
POST https://node:32443/apis/apps/v1/namespaces/default/deployments
BODY:
{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"name":"k-test1","annotations":{"propagationpolicy.karmada.io/name":"pp-all","propagationpolicy.karmada.io/namespace":"default"},"labels":{"app":"baas-edit","propagationpolicy.karmada.io/name":"pp-all","propagationpolicy.karmada.io/namespace":"default","propagationpolicy.karmada.io/permanent-id":"id"},"namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"baas-edit"}},"template":{"metadata":{"labels":{"app":"baas-edit"}},"spec":{"schedulerName":"default-scheduler","containers":[{"name":"nginx-container","imagePullPolicy":"Always","image":"nginx","resources":{}}]}}}}

```

 to karmada K8s Cluster.
