### ISSUE TITLE
work objects failing to delete should add events to work objects

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#4735]
**What would you like to be added**:
when I delete a `work` and the work cannot be deleted I can see errors in karmada controller, but not on the work object
```
karmada-controller-manager-cd7f455f8-5qhqr karmada-controller-manager 2024-03-20T20:59:12.504465003Z E0320 20:59:12.504327       1 controller.go:329] "Reconciler error" err="admission webhook \"foo\" denied the request: user system:serviceaccount:karmada-cluster:karmada is not allowed to delete /v1, Resource=namespaces: 'bar'." controller="work" controllerGroup="work.karmada.io" controllerKind="Work" Work="karmada-es/bar-57896c7dbb" 
```

vs:
```
describe work -n karmada-es-sandbox-eks znowflake-57896c7dbb
Events:       <none>
```

**Why is this needed**:
debugging stuck work items should be more intuitive

**Comment by XiShanYongYe-Chang** [comment]
Hi @grosser, You mean adding an event for the work object, right?

**Comment by grosser** [comment]
yes!

**Comment by XiShanYongYe-Chang** [comment]
It makes sense to me!

I would like to know where the error is mentioned in the issue, this will make it clear where we should add the event in the code.

**Comment by grosser** [comment]
the error was from controller-manager logs

**Comment by XiShanYongYe-Chang** [comment]
> the error was from controller-manager logs

Which line in the code exactly? Sorry I didn't find it.

**Comment by grosser** [comment]
found it here, sadly not in karmada codebase ...
```
find . -type f -name 'controller.go' -exec awk 'FNR == 329 {print FILENAME ": " $0}' {} \;
./vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go: 		log.Error(err, "Reconciler error")
```

**Comment by XiShanYongYe-Chang** [comment]
This may not be able to add the event for `Work` object.

**Comment by grosser** [comment]
thx for taking a look, I'll close then since it seems too much work for the small gain

**Comment by XiShanYongYe-Chang** [comment]
> ems too much work for the small gain

Thanks, if you can find a way to add events, feel free to contribute code. :)
