### ISSUE TITLE
Disablement of propagation policy for specific object in specific cluster

### ISSUE THREAD

**Issue by kutsyk** [karmada-io/karmada#4744]
**Disablement of propagation policy for specific object in specific cluster**:

We have a simple K8S service that has next objects:
1. deployment - `depl.yml`
2. service - `svc.yml`
3. configmap - `configmap.yml` that contains configurations for `depl.yaml`

Let's say we have 50 clusters and there is an incident that impact 1 cluster - `bad-cluster`.

**Question:** Is it possible to **pause** syncing of configurations for `configmap` in `bad-cluster` without pausing it for other 49 clusters?

We need that so service owner/administrator can debug different configurations during firefighting and that will not disrupt other cluster configurations.

**Question:** Additionally, if it is possible, will we have metrics/logs that will point that `configmap.yaml` object in cluster `bad-cluster` is not syncing with main source?

**Environment**:
- Kubernetes version: 1.23+

**Comment by RainbowMango** [comment]
> Let's say we have 50 clusters and there is an incident that impact 1 cluster - bad-cluster.

What kind of incident are we talking about? Can Karmada talk to the cluster's apiserver by applying the configuration?

- If yes, generally speaking, Karmada would still sync the configuration to that cluster.
- If no, Karmada will skip syncing from that cluster. (Actually, that cluster will be filed out by the scheduler).

**Comment by kutsyk** [comment]
HI @RainbowMango , I've figured out how things can work with more practical examples on my side, nothing more is needed, thanks. 

I'll close this issue
