### ISSUE TITLE
e2e case keep failing after introduced cluster lifecycle controller

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#477]
**Which jobs are failing**:
e2e test

**Which test(s) are failing**:
The [namespace autoprovision](https://github.com/karmada-io/karmada/blob/e1db428290b535e1a49e722ebaa26659f996f64d/test/e2e/namespace_test.go#L89)
```
[namespace auto-provision] namespace auto-provision testing when delete a namespace from karmada apiserver 
  namespace should be removed from member clusters
```

Also blocks #475 
https://github.com/karmada-io/karmada/pull/475/checks?check_run_id=2927796598

**Since when has it been failing**:
After #454

**Reason for failure**:

**Anything else we need to know**:

**Comment by RainbowMango** [comment]
cc @Garrybest Can you help to take a look?

You can reproduce it on your side by:
```
# hack/karmada-bootstrap.sh
# export KUBECONFIG=/root/.kube/karmada.config
# hack/run-e2e.sh
```

**Comment by Garrybest** [comment]
Sure, let me take a look.

**Comment by Garrybest** [comment]
How about testing #475 again? I found #476 has passed all tests. @RainbowMango

**Comment by RainbowMango** [comment]
I re-tested #475 twice but all failed. 
I can re-test it again.

**Comment by RainbowMango** [comment]
The master CI failed again, but this time the failing case is `basic propagation testing`.
https://github.com/karmada-io/karmada/runs/2928252931

The #475 failed as well, and the failing case is `basic cluster propagation testing`.
https://github.com/karmada-io/karmada/pull/475/checks?check_run_id=2928266824

**Comment by Garrybest** [comment]
I guess that the namespace `karmada-cluster`, where the lease is stored, has not been created in advance before. @RainbowMango 

https://github.com/karmada-io/karmada/blob/e1db428290b535e1a49e722ebaa26659f996f64d/pkg/util/cluster.go#L15
