### ISSUE TITLE
docs: the ClusterEviction plugin was not add to the document

### ISSUE THREAD

**Issue by Vacant2333** [karmada-io/karmada#4803]
**Task description**:
https://github.com/karmada-io/website/blob/main/docs/developers/customize-karmada-scheduler.md?plain=1#L18
the `ClusterEviction` plugin was not add to the document

**Solution**:
find out that what the plugin do, and update the en and zh-ch docs

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by XiShanYongYe-Chang** [comment]
Hi @seanlaii, you may send a PR in the [website](https://github.com/karmada-io/website) repo.

If you encounter any problems during the modification, you can give us feedback in the comments.

**Comment by XiShanYongYe-Chang** [comment]
Hi @Vacant2333 can you help take a review for https://github.com/karmada-io/website/pull/588
