### ISSUE TITLE
请教权限认证问题导致karmada资源创建异常原因

### ISSUE THREAD

**Issue by hhwode** [karmada-io/karmada#4806]
**Please provide an in-depth description of the question you have**:
通过二进制部署karmada集群，可以执行成员集群注册。但是，当使用Karmadactl进行查询时，会出现一条错误消息（error: cluster(kas-test-57-v1) is inaccessible, please check authorization or network），并且PropagationPolicy的创建也异常。只有kube-apiserver有日志打印，而karmada-aggregated-apiserver没有日志输出。是缺哪个权限配置异常导致无法创建它吗，文档中所提及的权限也都加上了 
参考文档：https://karmada.io/zh/docs/installation/install-binary
**What do you think about this question?**:
The following is the log of the operation output
- kubectl get clusters.cluster.karmada.io 
NAME             VERSION   MODE   READY   AGE
ks-test-57-v1   v1.19.3   Push   True    2s

- karmadactl get nodes --v=6
I0407 17:34:52.195599 1933672 loader.go:395] Config loaded from file:  /root/.kube/config
I0407 17:34:52.196461 1933672 cert_rotation.go:137] Starting client certificate rotation controller
I0407 17:34:52.205469 1933672 round_trippers.go:553] GET https://xxx:6443/apis/cluster.karmada.io/v1alpha1/clusters 200 OK in 9 milliseconds
I0407 17:34:52.210182 1933672 round_trippers.go:553] GET https://xxx:6443/apis/cluster.karmada.io/v1alpha1/clusters/kas-test-57-v1 200 OK in 2 milliseconds
I0407 17:34:52.210987 1933672 loader.go:395] Config loaded from file:  /root/.kube/config
I0407 17:34:52.221877 1933672 round_trippers.go:553] GET https://xxx:6443/apis/cluster.karmada.io/v1alpha1/clusters/kas-test-57-v1/proxy/api 403 Forbidden in 10 milliseconds
error: cluster(kas-test-57-v1) is inaccessible, please check authorization or network

- kubectl apply -f propagationpolicy.yaml --v=6
I0407 17:35:29.163355 1933953 loader.go:372] Config loaded from file:  /root/.kube/config
I0407 17:35:29.163894 1933953 cert_rotation.go:137] Starting client certificate rotation controller
I0407 17:35:29.180874 1933953 round_trippers.go:553] GET https://xxx:6443/openapi/v2?timeout=32s 200 OK in 16 milliseconds
I0407 17:35:29.286434 1933953 round_trippers.go:553] GET https://xxx:6443/apis/policy.karmada.io/v1alpha1/namespaces/default/propagationpolicies/nginx-propagation 404 Not Found in 3 milliseconds
I0407 17:35:29.295751 1933953 round_trippers.go:553] POST https://xxx:6443/apis/policy.karmada.io/v1alpha1/namespaces/default/propagationpolicies?fieldManager=kubectl-client-side-apply 500 Internal Server Error in 9 milliseconds
I0407 17:35:29.295864 1933953 helpers.go:219] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \"propagationpolicy.yaml\": Internal error occurred: failed calling webhook \"propagationpolicy.karmada.io\": failed to call webhook: forbidden: User \"system:anonymous\" cannot post path \"/mutate-propagationpolicy\"",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "failed calling webhook \"propagationpolicy.karmada.io\": failed to call webhook: forbidden: User \"system:anonymous\" cannot post path \"/mutate-propagationpolicy\""
      }
    ]
  },
  "code": 500
}]
F0407 17:35:29.295893 1933953 helpers.go:118] Error from server (InternalError): error when creating "propagationpolicy.yaml": Internal error occurred: failed calling webhook "propagationpolicy.karmada.io": failed to call webhook: forbidden: User "system:anonymous" cannot post path "/mutate-propagationpolicy"

**Environment**:
- Karmada version: v1.9
- Kubernetes version: v1.23.3
- Others: os-ubuntu-22.04

**Comment by amacharya** [comment]
Hello,

https://github.com/karmada-io/karmada/issues/4963

Can you help me with this?
