### ISSUE TITLE
Add status for PropagationPolicy and ClusterPropagationPolicy

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#483]
**What would you like to be added**:

add status field in PropagationPolicy and ClusterPropagationPolicy

**Why is this needed**:
As  `resourceDetector.Reconcile`  is run by AsyncWorker with a interval of time.Microsecond

https://github.com/karmada-io/karmada/blob/0941887e0599c8b7cabdd1b25c1926bf18d718fe/cmd/controller-manager/app/controllermanager.go#L114-L115

when we create a PropagationPolicy and match objects, the logic below will run multiple times.

https://github.com/karmada-io/karmada/blob/0941887e0599c8b7cabdd1b25c1926bf18d718fe/pkg/util/detector/detector.go#L158-L182

If the status is added, when policy matches object and resourcebinding is created, then needn't run match again.

**Comment by pigletfly** [comment]
then it's possible to move reconcile login in detector back to PropagationPolicy controller.

**Comment by RainbowMango** [comment]
> when we create a PropagationPolicy and match objects, the logic below will run multiple times.

[The code](https://github.com/karmada-io/karmada/blob/1a94afc7229de70b2f489f9da99c466ab0c3fd70/pkg/util/detector/detector.go#L137) is supposed to be called to reconcile the resource template change. Why it will be run multiple times? Especially when `PropagationPolicy` creating?

**Comment by RainbowMango** [comment]
How about adding an agenda to the next meeting? It's not an urgent issue, right?

**Comment by pigletfly** [comment]
yes,It's not an urgent one.

**Comment by RainbowMango** [comment]
I'm going to close this issue now as we don't have a plan for it yet.

/close
