### ISSUE TITLE
Introduce a mechanism to actively trigger rescheduling

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#4840]
**What would you like to be added**:

Introducing a mechanism of actively triggering rescheduling. 

**Why is this needed**:

Proposal of introducing a rebalance mechanism to actively trigger rescheduling of resource.

Assuming the user has propagated the workloads to member clusters, in some scenarios the current replicas distribution
is not the most expected, such as:

* replicas migrated due to cluster failover, while now cluster recovered.
* replicas migrated due to application-level failover, while now each cluster has sufficient resources to run the replicas.
* as for `Aggregated` schedule strategy, replicas were initially distributed across multiple clusters due to resource
  constraints, but now one cluster is enough to accommodate all replicas.

Therefore, the user desires for an approach to trigger rescheduling so that the replicas distribution can do a rebalance.

***

### The issue is created to track all related activities：

**Proposal：** 
 * - [x] #4698

**Implementation：** 
 * - [x] Scheduler: #4848
 * - [x] WorkloadRebalancer：#4841
 * - [x] ~Webhook: #4859~
 * - [x] bugfix: #4875
 * - [x] Support update: #4860
 * - [x] Support auto delete: #4894

**UT**
 * - [x] #4876

**E2E Test：**
 * - [x] #4869
 * - [x] #4961 

**Doc of Best Practice：**
 * - [x] **en** tutorial: https://github.com/karmada-io/website/pull/608
 * - [x] **zh** tutorial: https://github.com/karmada-io/website/pull/627
 * - [x] **en** user guide: https://github.com/karmada-io/website/pull/612
 * - [x] **zh** user guide: https://github.com/karmada-io/website/pull/628

**Comment by RainbowMango** [comment]
We need a document for this feature that is missing from this umbrella issue.

**Comment by RainbowMango** [comment]
FYI
Add two tasks for the zh documents.

**Comment by RainbowMango** [comment]
/close
since all tasks have been addressed.
