### ISSUE TITLE
Is there a way to retain ConfigMap in member cluster?

### ISSUE THREAD

**Issue by tpiperatgod** [karmada-io/karmada#4842]
**Please provide an in-depth description of the question you have**:
After propagation through Karmada, member clusters are unable to modify configmap resources to the point where certain cluster-based configurations cannot be applied.

**What do you think about this question?**:
I want to be able to modify a configmap resource in the member cluster propagated by karmada, is there any way to do that?
**Environment**:
- Karmada version: 1.8
- Kubernetes version: 1.25
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @tpiperatgod, I recommend you use the resource interpreter for your purposes, you can use [retain ](https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#retain)operation to retain the fields of cm in the member cluster.

**Comment by tpiperatgod** [comment]
Thanks, can you give me an example of how to use the retain operation to retain the cm resource? I've read this section before and realized that cm is not in the default support list.

**Comment by XiShanYongYe-Chang** [comment]
You can customize it with a [webhook](https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter) or [a lua script](https://github.com/karmada-io/karmada/tree/master/pkg/resourceinterpreter/default/thirdparty). You can choose one.

**Comment by tpiperatgod** [comment]
> You can customize it with a [webhook](https://github.com/karmada-io/karmada/tree/master/examples/customresourceinterpreter) or [a lua script](https://github.com/karmada-io/karmada/tree/master/pkg/resourceinterpreter/default/thirdparty). You can choose one.

Yes, this is one way I know ...... But I think it's too heavy, is it possible to take the resource out of the propagation management by adding an annotation or something like that?

**Comment by tpiperatgod** [comment]
Add: I don't want to retain all configmap resources, but some specific configmap resources.

**Comment by XiShanYongYe-Chang** [comment]
> But I think it's too heavy, is it possible to take the resource out of the propagation management by adding an annotation or something like that?

Annotation seems convenient, but it is not easy to iterate.

> Add: I don't want to retain all configmap resources, but some specific configmap resources.

The current support granularity is really not that small. I think it makes sense to support this.

**Comment by tpiperatgod** [comment]
Anyway, I implemented it the webhook way, thanks!

**Comment by XiShanYongYe-Chang** [comment]
> Add: I don't want to retain all configmap resources, but some specific configmap resources.

If necessary, you can raise an issue to track the task. If convenient, you can provide your user story to promote the task.
