### ISSUE TITLE
create cluster failed on macos because of the sed cmd

### ISSUE THREAD

**Issue by likakuli** [karmada-io/karmada#486]
**What happened**:

Failed to create cluster because there are several sed cmd in the shell script. On macos, the default sed is not the same as it in linux.

**What you expected to happen**:

All the script work successfully across platform.

**How to reproduce it (as minimally and precisely as possible)**:

./hack/local-up-karmada.sh

**Anything else we need to know?**:

**Environment**: MacOS
- Karmada version: v0.6.0
- Others: We can resolve the network problem on macos using the docker-connector. https://github.com/wenjunxiao/mac-docker-connector

**Comment by RainbowMango** [comment]
cc @mrlihanbo @lfbear

**Comment by lfbear** [comment]
Got it, `sed` on macOS is the first block, it seems that we should slave solve all problems on macOS on schedule.

**Comment by likakuli** [comment]
By the way, use sed -i'' -e s/old/new/g can work both on mac and linux.

**Comment by algebra2k** [comment]
I had the same problem and I have fixed it

**Comment by RainbowMango** [comment]
> I had the same problem and I have fixed it

How?

**Comment by algebra2k** [comment]
> > I had the same problem and I have fixed it
> 
> How?

Just like:
```bash
 if [[ "$OSTYPE" == "darwin"* ]]; then # Macos
         sed -i "" "s/{{ca_crt}}/${karmada_ca}/g" "${TEMP_PATH}"/karmada-cert-secret-tmp.yaml
 else
         sed -i "s/{{ca_crt}}/${karmada_ca}/g" "${TEMP_PATH}"/karmada-cert-secret-tmp.yaml
 fi
 ```
I was thinking that this could be extracted as a util function, such as `util::sed $1 $2`.

**Comment by RainbowMango** [comment]
/assign @lfbear 
As @lfbear sent a PR for this.
