### ISSUE TITLE
Update controller-gen version from v0.13.0 to v0.14.0

### ISSUE THREAD

**Issue by seanlaii** [karmada-io/karmada#4873]
Task description:

We need to bump the controller-gen version to v0.14.0 when we upgrade Go version to v1.22 to avoid this [issue](https://github.com/kubernetes-sigs/controller-tools/issues/888).

**Comment by XiShanYongYe-Chang** [comment]
Good job, thanks.

If you were willing to claim this task, you can assign it to yourself.

**Comment by seanlaii** [comment]
Sure, I'd be happy to take on this task when upgrading to Go version 1.22. Thanks!

**Comment by RainbowMango** [comment]
Thanks for the notice. I wonder if the controller-gen@v0.14.x can work with Go 1.21?

**Comment by seanlaii** [comment]
Oh, it's a great question. It seems to work. I created a PR for upgrading it. Thanks!

**Comment by XiShanYongYe-Chang** [comment]
In favor of #4874 
/assign @seanlaii
