### ISSUE TITLE
[GoodFirst] replace wait.Poll with wait.PollImmediate from testing

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#492]
**Task description**:
We currently using `wait.Poll` to detect the expected condition, like:
https://github.com/karmada-io/karmada/blob/25f28f5006c6afc8a94ed2abebcca28353f7abca/test/e2e/namespace_test.go#L46

But [wait.Poll][1] always wait for the interval before the run of 'condition', that may slow down the testing, e.g.
```
I0705 03:28:45.593288   28490 overridepolicy_test.go:440] Waiting for deployment(karmadatest-9bh/deploy-67j) present on cluster(member1)
I0705 03:28:50.597660   28490 overridepolicy_test.go:440] Waiting for deployment(karmadatest-9bh/deploy-67j) present on cluster(member2)
I0705 03:28:55.602511   28490 overridepolicy_test.go:440] Waiting for deployment(karmadatest-9bh/deploy-67j) present on cluster(member3)
```
From the logs above, we can see that [wait.Poll][1] consumed 5s for each condition, which is a huge waste.

**Solution**:
Change [wait.Poll][1] to [wait.PollImmediate][2] which will always check 'condition' before waiting for the interval from all [E2E testing code base][3].

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

[1]: https://github.com/karmada-io/karmada/blob/25f28f5006c6afc8a94ed2abebcca28353f7abca/test/e2e/namespace_test.go#L46
[2]: https://github.com/karmada-io/karmada/blob/25f28f5006c6afc8a94ed2abebcca28353f7abca/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go#L440
[3]: https://github.com/karmada-io/karmada/tree/master/test

**Comment by RhnSharma** [comment]
I would like to take this one.
