### ISSUE TITLE
Cascading policy for propagated resources

### ISSUE THREAD

**Issue by buji-code** [karmada-io/karmada#4925]
I was wondering whether the Karmada propagation policy can support cascading by default, meaning that the main resource that is being propagated won't get finalized until its propagated descendants do. I can see that Karmada supports cascading using [DeleteOptions](https://karmada.io/docs/reference/karmada-api/common-definitions/delete-options/), yet it is not robust enough in case you want to enforce cascading.
Thanks

- Karmada version: v1.9.1
- Kubernetes version: v.1.27

**Comment by XiShanYongYe-Chang** [comment]
Hi @buji-code, thanks for your feedback.

What do you mean by cascade? Can you give an example?

**Comment by buji-code** [comment]
For example: let’s say I have a CR name my-foo from type Foo. I defined a
propagation policy to propagate Foo objects to cluster-a.

Now I have my-foo in Karmada and my-foo in cluster-a. When I delete my-foo
from Karmada, I expect it not to be removed until my-foo from cluster-a is
being deleted.

**Comment by XiShanYongYe-Chang** [comment]
Thanks for the explanation, I understand what you are saying we are doing, refer to #4788
