### ISSUE TITLE
cherry-picks: 4899 let kube version of artifaces/deploy/karmada-apiserver versionsupport configuration. 

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#4929]
**Which PR needs cherry-picks:**

PR #4899

PR is changing the files of `artifacts/deploy` and `hack`,  it need to cherry pick the change to release branch and then it can be work for workflow `APIServer compatibility`

/assign

**Which release branches need this patch:**

- [x] release-1.8 https://github.com/karmada-io/karmada/pull/5132
- [x] release-1.9 https://github.com/karmada-io/karmada/pull/5133
- [x] release-1.10 https://github.com/karmada-io/karmada/pull/5134

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by Akash-Singh04** [comment]
Hey is this issue still open? I would like to work on it

**Comment by liangyuanpeng** [comment]
@Akash-Singh04  ready to go, please feel free to pick it up :)

**Comment by liangyuanpeng** [comment]
kindly ping  @Akash-Singh04

**Comment by Akash-Singh04** [comment]
working on this, will be done by EOD

**Comment by Akash-Singh04** [comment]
@liangyuanpeng #5134 #5133 #5132 have been made, kindly review them and let me know if any further changes are required
