### ISSUE TITLE
`ResourceInterpreterCustomization` for `Prune`

### ISSUE THREAD

**Issue by a7i** [karmada-io/karmada#4945]
**What would you like to be added**:
Currently, `Prune` is only supported for built-in, and there are use-cases where we could use Prune for custom resources.

**Why is this needed**:
[this blog](https://xinzhao.me/posts/guide-to-karmada-resource-interpreter-webhook/) does a good job of covering the interpreters and based on the image, we may want to exclude labels/annotations before Work is created
![image](https://github.com/karmada-io/karmada/assets/9448877/578a53c6-ad09-4e1c-882f-82cb903f7399)

**Comment by XiShanYongYe-Chang** [comment]
@a7i Thanks for your feedback, I think this is an interesting feature point.

Before we start discussing how to do this, let's invite some ideas from people who might be interested in this.

/cc @chaunceyjiang @whitewindmills @RainbowMango @yike21 @iawia002

**Comment by XiShanYongYe-Chang** [comment]
> we may want to exclude labels/annotations before Work is created

Hi @a7i I'd like to know under what circumstances this would be necessary. Because after communicating with @RainbowMango, I realized that `retain` can be used to handle the conflict between the Karmada control plane and member clusters.

**Comment by a7i** [comment]
Prune would be to strip certain fields (e.g. label) from being propagated. With Retain, the label still goes to the member cluster but the value is essentially ignored.

One use-case is that we use a label to determine if a workload should be duplicated in all member clusters or not (the label is matched by the policy labelSelector). There is no need for this label to get propagated to the member clusters.

**Comment by XiShanYongYe-Chang** [comment]
Thanks for the use case. I think it makes sense.
cc @RainbowMango

**Comment by RainbowMango** [comment]
It seems to make sense, I'll get back to it later.

**Comment by whitewindmills** [comment]
> One use-case is that we use a label to determine if a workload should be duplicated in all member clusters or not (the label is matched by the policy labelSelector). There is no need for this label to get propagated to the member clusters.

make sense.

**Comment by RainbowMango** [comment]
> One use-case is that we use a label to determine if a workload should be duplicated in all member clusters or not (the label is matched by the policy labelSelector). There is no need for this label to get propagated to the member clusters.

It seems a reasonable use case that you label resources and let PropagationPolicy match them. 
But I have several questions:
1. I know there is no need for this label to get propagated, but that doesn't do any harm, right?
2. Can we prune the unnecessary label by OverridePolicy? I'm wondering if this is an option.

**Comment by chaunceyjiang** [comment]
🤔 It seems that using OverridePolicy can cove this.

**Comment by a7i** [comment]
Using Lua gives more flexibility and control than `PlaintextOverrider` but at the moment, using a ClusterOverridePolicy will work for us. Thank you

/close

**Comment by RainbowMango** [comment]
Oh, seems you like Lua.

But, by the way, the `LabelAnnotationOverrider` and `LabelAnnotationOverrider` might be more straightforward than PlaintextOverrider.

**Comment by a7i** [comment]
It's growing on me :)
