### ISSUE TITLE
Can karmada host cluster be a member cluster too ?

### ISSUE THREAD

**Issue by Patrick0308** [karmada-io/karmada#4979]
**Please provide an in-depth description of the question you have**:

**What do you think about this question?**:
Can karmada host cluster be a member cluster too ?
If a cluster is not only karmada host but member, is there some problem or risk ? Please let me know.

**Environment**:
- Karmada version: 1.9.0
- Kubernetes version:
- Others:

**Comment by chaunceyjiang** [comment]
> Can karmada host cluster be a member cluster too ?

Yes. We are currently doing this as well. So far, no problems have been found.
