### ISSUE TITLE
Add local e2e test script

### ISSUE THREAD

**Issue by B1F030** [karmada-io/karmada#5000]
**What would you like to be added**:
Two optional methods:
1. Add a section in Makefile like this:
```
.PHONY: test-integration
test-integration: ...
```

2. Add a new script named `local-e2e.sh`, like `run-e2e.sh`.

**Why is this needed**:
1. Now we only have `run-e2e.sh` script for github ci, but it will be convenient to have a e2e test script for local environment.
2. Also, we can reduce the pressure on github ci, because we don't need to commit everytime to trigger e2e test, if we can run test in local environment.
3. Now after running the `run-e2e.sh` script, it will generate some logs, and trigger `pre-run-e2e.sh` & `post-run-e2e.sh` to create & delete extra components, which is not necessary for local environment(because it's designed for github ci environment). So we need another script for local e2e test.

**Comment by B1F030** [comment]
@zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
> Now we only have run-e2e.sh script for github ci, but it will be convenient to have a e2e test script for local environment.

@B1F030 Can you remind me what difficulties you encountered using run-e2e.sh locally?

**Comment by B1F030** [comment]
> @B1F030 Can you remind me what difficulties you encountered using run-e2e.sh locally?

Updated.

**Comment by B1F030** [comment]
> Hi @B1F030, we actually has the ability to run e2e locally

Thanks! Really appreciate it.

**Comment by liangyuanpeng** [comment]
/kind support 
/remove-kind feature
/close 

feel free to reopen if still have some problem.
