### ISSUE TITLE
[github action problem] Received request to deprovision: The request was cancelled by the remote provider

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#5001]
karmada job is cancel by github action:

- https://github.com/karmada-io/karmada/actions/runs/9296482517
- https://github.com/karmada-io/karmada/actions/runs/9297158845

releated: 

- https://github.com/actions/runner-images/issues/9959

**Comment by RainbowMango** [comment]
We don't seem to be affected too much, isn't?

**Comment by RainbowMango** [comment]
> https://github.com/karmada-io/karmada/actions/runs/9296482517

This job succeeds after a re-run.

**Comment by liangyuanpeng** [comment]
> We don't seem to be affected too much

yes, i'm closing it

**Comment by RainbowMango** [comment]
Thanks for the notice. I subscribed the linked issue, I'll pay attention to CI and retry those being affected before the issue closes.
