### ISSUE TITLE
Unschedulable result treated as failure during max replica estimation

### ISSUE THREAD

**Issue by mszacillo** [karmada-io/karmada#5011]
**What happened**:
While testing CRD scheduling with the accurate estimator + resourcequota plugin enabled, I noticed that Karmada would still schedule applications to a cluster's namespace even if that namespace did not have sufficient resources available. 

**What you expected to happen**:
When using accurate estimator with resourcequota plugin enabled, Karmada should not schedule replicas to clusters that do not have sufficient namespaced resources. 

**Why does this happen**:

1. When finding selected clusters, Karmada scheduler will loop through all enabled estimators and get the minimum score for each cluster during [calAvailableReplicas](https://github.com/karmada-io/karmada/blob/master/pkg/scheduler/core/util.go#L71).

2. When estimating using `accurate estimator`,  the ResourceQuota plugin can return Unschedulable. This means that the replica's resource requirements are greater than the available resources on the desired namespace. Unschedulable **does not** get treated as a success, so the estimator will keep the score for that cluster as math.MaxInt32 (2147483647) in [RunEstimateReplicasPlugins](https://github.com/karmada-io/karmada/blob/master/pkg/estimator/server/framework/runtime/framework.go#L124). 

3. Since accurate estimator returns math.MaxInt32 as the cluster score when unschedulable, the cluster scores will default to the generic estimator. This can result in incorrect scheduling.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable accurate estimator with the ResourceQuotaEstimate feature gate set to true. 

2. Fill the desired amespace on one of your member clusters (lets say member A) to capacity, so that the replica cannot be scheduled. 

3. Apply the resource to Karmada control-plane. Looking at logs, you should see the scheduler rely on generic scheduler scores rather than using the accurate estimator scores. 

**Environment**:
- Karmada version: v1.9.0

**Comment by chaosi-zju** [comment]
Does this mean that when the accurate estimator gives results, it needs to distinguish whether it cann't give results or gives unschedulable results. If it is not schedulable, the cluster should be filtered out instead of being handled by other estimators.

**Comment by chaosi-zju** [comment]
> Does this mean that when the accurate estimator gives results, it needs to distinguish whether it cann't give results or gives unschedulable results. If it is not schedulable, the cluster should be filtered out instead of being handled by other estimators?

If were that, then I think we may shall sort the estimators by priority, if high priority estimator give not schedulable result, we don't need to call low priority estimator. This reminds me of a previous pending PR: #4398, as it tried to resolve the probleam:

> If the accurate estimator is enabled and karmada-scheduler-estimator components also are enabled, the accurate estimator should be prior to ResourceModeling rather than using the minumal value of them.

**Comment by wengyao04** [comment]
> Does this mean that when the accurate estimator gives results, it needs to distinguish whether it cann't give results or gives unschedulable results. If it is not schedulable, the cluster should be filtered out instead of being handled by other estimators?

Hi, there are 
- general estimator
  - estimate based on resource model if resourceModel is enabled
  - estimate based on cluster summary
- accurate estimator
  - estimator caches nodes/pods 
  - support plugins (we currently have resource quota plugin)
  
When I implement the resource quota plugin, I categorize replica zero as unscheduable and returns an error. But I think I the replica should be the minimum replica of general estimator and accurate estimator

**Comment by chaosi-zju** [comment]
Hi @wengyao04, thank you for your explanation.

***

>  I categorize replica zero as unscheduable and returns an error

that's to say, according to current implementation:

https://github.com/karmada-io/karmada/blob/37dd12f459fcd709b0c407787e5cf96de79e3396/pkg/scheduler/core/util.go#L75-L89

When running accurate estimator, by calling `res, err := estimator.MaxAvailableReplicas(ctx, clusters, spec.ReplicaRequirements)`, it will return `err != nil` and continue to run next estimator.

That is actually what I say `it needs to distinguish whether it cann't give results or gives unschedulable results`, it seems like in this case we gives unschedulable results (replica zero), but the result `err != nil` is more like cann't give results. This seems a bit contradictory.

***

> But I think I the replica should be the minimum replica of general estimator and accurate estimator

So you think that, just looking at this issue, the estimator priority is irrelevant to the resolution. You prefer keep choosing minimum replica unchanged (Or say you think these two estimator is of same priority)?

**Comment by RainbowMango** [comment]
> When I implement the resource quota plugin, I categorize replica zero as unscheduable and returns an error. But I think I the replica should be the minimum replica of general estimator and accurate estimator

agree.
`Unschedulable` still can be treated as success with available replica 0.
