### ISSUE TITLE
EndpointSlice should add annotations to show the cluster name which the karmada endpointslice is associated

### ISSUE THREAD

**Issue by zhoukejie-web** [karmada-io/karmada#5038]
In v1.10.0 karmada endpointslice remove some labels, such as `work.karmada.io/namespace` .
So we can only judge endpointslice asscociated clusters by spliting endpointslice name. 
That maybe is not a good way to get cluster info from endpointslice name,  the best way to acquire cluster info from eps annotation.
![image](https://github.com/karmada-io/karmada/assets/55874487/517d5126-1ac9-4755-b214-f767511a0ab3)

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/assign
