### ISSUE TITLE
Do not delete the work when PropagationPolicy is deleted

### ISSUE THREAD

**Issue by qianjun1993** [karmada-io/karmada#505]
**What would you like to be added**:
Do  not delete the work in member clusters when the related propagationPolicy is deleted
**Why is this needed**:
The users may delete the propagationPolicy (or even the crd) and then they may find that the all the related works in member are deleted. It may be unexpected 。

So I think, that the work may not be deleted when the  propagationPolicy is missing， and will be deleted  when the workload itself  is deleted.

**Comment by algebra2k** [comment]
I think we should provide a strategy where the user chooses whether to cascade the deletion when deleting a propagation.

**Comment by jrkeen** [comment]
I think the strategy might be similar to the k8s DeleteOptions.
Here's an example that orphans dependents:
```
kubectl proxy --port=8080
curl -X DELETE localhost:8080/apis/apps/v1/namespaces/default/replicasets/my-repset \
  -d '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Orphan"}' \
  -H "Content-Type: application/json"
```

**Comment by RainbowMango** [comment]
We need a more detailed solution. Sounds good to me.
Looking forward to someone who can lead this feature.

**Comment by jrkeen** [comment]
Add "PlacementRetained" in PropagationSpec.
```go

type PropagationSpec struct {
        ...
	// PlacementRetained represents the rule for select clusters to retain resources when PropagationPolicy is deleting.
	// +optional
	PlacementRetained *ClusterRetained `json:"placementRetained,omitempty"`
        ...
}

// ClusterRetained represents the filter to select clusters.
type ClusterRetained struct {
	// LabelSelector is a filter to select member clusters by labels.
	// If non-nil and non-empty, only the clusters match this filter will be selected.
	// +optional
	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty"`

	// FieldSelector is a filter to select member clusters by fields.
	// If non-nil and non-empty, only the clusters match this filter will be selected.
	// +optional
	FieldSelector *FieldSelector `json:"fieldSelector,omitempty"`

	// ClusterNames is the list of clusters to be selected.
	// +optional
	ClusterNames []string `json:"clusterNames,omitempty"`

	// ExcludedClusters is the list of clusters to be ignored.
	// +optional
	ExcludeClusters []string `json:"exclude,omitempty"`
}
```
When resources are deleting in karmada, work will judge whether to delete resources in the member cluster according to PlacementRetained.
Add annotations in work similar to resourcebinding.
![image](https://user-images.githubusercontent.com/39866845/127465218-7756e1cd-7d2e-47e0-b816-52bbce001c28.png)
At present, we have implemented and used.

**Comment by RainbowMango** [comment]
@jrkeen 
Thanks for the awesome proposal. You want to `retain`  the resources from `part` of the clusters.
Is that your use case?

**Comment by jrkeen** [comment]
> @jrkeen
> Thanks for the awesome proposal. You want to `retain` the resources from `part` of the clusters.
> Is that your use case?

Yes, I hope to choose clusters to retain according to policy.

**Comment by RainbowMango** [comment]
> Yes, I hope to choose clusters to retain according to policy.

Why? What kind of workload you are propagating? I wonder if there is a particular reason for that.

**Comment by algebra2k** [comment]
My understanding is that the purpose of ClusterRetain is to provide the user with an option to select some clusters not to delete workloads created by karmada when deleting a propagation, either by label selector or some other method.

**Comment by jrkeen** [comment]
> My understanding is that the purpose of ClusterRetain is to provide the user with an option to select some clusters not to delete workloads created by karmada when deleting a propagation, either by label selector or some other method.

Yes, your idea fits in with mine.

**Comment by RainbowMango** [comment]
@jrkeen @qianjun1993 @phantooom let's have a chat at today's meeting, ok? I know you all have a solution for this.
