### ISSUE TITLE
Update CI for release-1.10 on master

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#5060]
**Task description**:

karmada 1.10 is live, so we need to update the CI for release-1.10, basically, you need to delete release-1.7 and add the last release-1.10

https://github.com/karmada-io/karmada/blob/5e8152ab2e987ae80e43264ad383cd873cc5e3bc/.github/dependabot.yml#L20-L36

https://github.com/karmada-io/karmada/blob/5e8152ab2e987ae80e43264ad383cd873cc5e3bc/.github/workflows/ci-schedule-compatibility.yaml#L20

cc some people who may be interested @Akash-Singh04 

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by 08AHAD** [comment]
/assign
Please assign me this issue.

**Comment by 08AHAD** [comment]
I am facing problem in pull request

**Comment by Akash-Singh04** [comment]
Sure, will work on this!

**Comment by XiShanYongYe-Chang** [comment]
Thanks @Akash-Singh04 
ref #5062

**Comment by Akash-Singh04** [comment]
@XiShanYongYe-Chang Kindly review the PR and let me know if any further changes are required

**Comment by 08AHAD** [comment]
[https://github.com/karmada-io/karmada/pull/5063](url)

**Comment by 08AHAD** [comment]
I have also reaaranged the code that is asked later please review my PR @liangyuanpeng

**Comment by liangyuanpeng** [comment]
@08AHAD  @Akash-Singh04 

Thank you for your enthusiasm! Since this is a good first issue, I hope to follow the first-come-first-served principle (first assigner) . So I may choose the PR submitted by @08AHAD .  If @08AHAD  doesn't follow through, someone else can take over and finish the job.

we have other issue can choice, https://github.com/karmada-io/karmada/issues/4929 is ready to go @Akash-Singh04  if you are Interested in this :)
