### ISSUE TITLE
Failed work objects stay behind even if the resource is deleted

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#5076]
**What happened**:
- I saw a pod failed to propagate `Failed to apply all manifests (0/1):`
- I tried to check on the pod, but it was deleted in host cluster (the cluster we propagate from)
- I saw the work object hangs around for ~1d (it's not forever but not sure what the exact cutoff is and when it's triggered, maybe karmada restart)

**What you expected to happen**:
- work object is deleted when host resource is deleted

**How to reproduce it (as minimally and precisely as possible)**:
- create failed work object (for example propagate a pod but not the requires service-account)
- delete host object
- see work object still existing

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.10.1

**Comment by XiShanYongYe-Chang** [comment]
Hi @grosser, thanks for your feedback. Is this an inevitable problem?

Can you provide your test yaml? I'll try it.

**Comment by wu0407** [comment]
more relate issue https://github.com/karmada-io/karmada/issues/3873

**Comment by grosser** [comment]
we stopped propagating these failing pods, so not an issue for now ... will reopen once we need this again
