### ISSUE TITLE
请问estimator.pb.generated.proto与generated.pb.go文件如何生成

### ISSUE THREAD

**Issue by yangchuan37326** [karmada-io/karmada#5160]
请问estimator.pb.generated.proto与generated.pb.go文件如何生成，我使用的karmada-1.6版本，执行hack/generate-proto.sh脚本，并没有生成这两个文件。执行结果如下：
topological order bytes
topological order encoding/base64
topological order encoding/json
topological order errors
topological order fmt
topological order github.com/gogo/protobuf/proto
topological order github.com/gogo/protobuf/sortkeys
topological order github.com/google/gofuzz
topological order go/ast
topological order go/doc
topological order go/parser
topological order go/token
topological order gopkg.in/inf.v0
topological order io
topological order k8s.io/apimachinery/pkg/conversion
topological order k8s.io/apimachinery/pkg/conversion/queryparams
topological order k8s.io/apimachinery/pkg/fields
topological order k8s.io/apimachinery/pkg/labels
topological order k8s.io/apimachinery/pkg/selection
topological order k8s.io/apimachinery/pkg/types
topological order k8s.io/apimachinery/pkg/util/errors
topological order k8s.io/apimachinery/pkg/util/json
topological order k8s.io/apimachinery/pkg/util/naming
topological order k8s.io/apimachinery/pkg/util/runtime
topological order k8s.io/apimachinery/pkg/util/sets
topological order k8s.io/apimachinery/pkg/watch
topological order k8s.io/klog/v2
topological order math
topological order math/big
topological order math/bits
topological order net/url
topological order os
topological order reflect
topological order runtime/debug
topological order sigs.k8s.io/structured-merge-diff/v4/value
topological order sort
topological order strconv
topological order strings
topological order sync
topological order sync/atomic
topological order time
topological order unsafe
topological order k8s.io/apimachinery/pkg/runtime/schema
topological order k8s.io/apimachinery/pkg/util/intstr
topological order k8s.io/apimachinery/pkg/api/resource
topological order k8s.io/apimachinery/pkg/runtime
topological order k8s.io/apimachinery/pkg/apis/meta/v1
topological order k8s.io/api/core/v1
topological order github.com/karmada-io/karmada/pkg/estimator/pb
2024/07/09 18:39:37 karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto:10:1: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto is unused.
2024/07/09 18:39:38 karmada/vendor/k8s.io/api/core/v1/generated.proto:12:1: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto is unused.

**Comment by chaosi-zju** [comment]
您好，您在执行什么操作时缺少这两个文件，您安装时应该不需要手动生成代码

**Comment by yangchuan37326** [comment]
您好，我在pkg.estimator.pb.type.go中增加了一个字段，想要重新生成proto和pb.go文件

**Comment by chaosi-zju** [comment]
v1.6版本应该没有你说的`hack/generate-proto.sh`脚本: https://github.com/karmada-io/karmada/tree/release-1.6/hack

我们生成代码现在是用 `hack/update-estimator-protobuf.sh` 或者 直接 `make update`

**Comment by yangchuan37326** [comment]
上面描述写错了，我执行的也是hack/update-estimator-protobuf.sh这个脚本。
我用1.9版本去执行报错karmada/hack/util.sh: line 82: `util::get_target_source': not a valid identifier，是对操作系统有什么要求吗。
另外有官方群可以加入吗

**Comment by RainbowMango** [comment]
1.6 版本已经停止维护了，为什么还在用？是之前上线的吗？

**Comment by yangchuan37326** [comment]
之前上线的版本，我们目前也在升级。 目前我使用1.9版本执行hack/update-estimator-protobuf.sh也没有执行成功，我目前正在尝试换一个操作系统去执行脚本

**Comment by RainbowMango** [comment]
@yangchuan37326 可以通过微信（qduyushu）联络我，可以帮你拉到微信群。
