### ISSUE TITLE
Supplement the karmadactl cert unit test section

### ISSUE THREAD

**Issue by tiansuo114** [karmada-io/karmada#5171]
Supplement the karmadactl cert unit test section
**What would you like to be added**:
Adds a test condition for the cert unit test that detects the presence of a certificate file in the specified directory
**Why is this needed**:
This section describes how to check and ensure that the file directory for creating a certificate is correct

**Comment by liangyuanpeng** [comment]
Thanks you! 
/assign @tiansuo114

**Comment by liangyuanpeng** [comment]
please open a PR for it if you're ready for it.

**Comment by tiansuo114** [comment]
> please open a PR for it if you're ready for it.

Ok, I have submitted the modification of this issue to pr, please see details in [here](https://github.com/karmada-io/karmada/pull/5175)

**Comment by XiShanYongYe-Chang** [comment]
The relate pr has been merged.
/close
