### ISSUE TITLE
The certificate of the member cluster has expired.

### ISSUE THREAD

**Issue by chaunceyjiang** [karmada-io/karmada#5173]
**What happened**:

``` shell
# karmadactl join memberAAA  --cluster-kubeconfig=XXX          --cluster-context=memberAAA

```

I have joined one of my k8s clusters, `memberAAA`, to Karmada and it has been working normally for a while. However, I noticed that the cluster `memberAAA` in Karmada is always showing NotReady. After investigation, it turns out that the certificate in `kubeconfig` has expired.

**What you expected to happen**:

Since the `kubeconfig` of the joined k8s cluster is provided by users, we cannot control when its certificate expires. Therefore, I hope there could be some information displayed on the `cluster` object in Karmada indicating when the certificate of this `kubeconfig` used by this cluster will expire.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by whitewindmills** [comment]
if I remember correctly, the kubeconfig is only used during the joining process. after joined, Karmada manages the member cluster through the RBAC established on the member cluster. so even if the certificate expires, this should not affect Karmada.

**Comment by RainbowMango** [comment]
> Karmada manages the member cluster through the RBAC established on the member cluster.

Yes, Karmada uses a non-expire token. 

/remove-kind bug
