### ISSUE TITLE
 How to use the pull mode to allow other clusters to join the Karmada through an external IP? Here, the IP is internal, how can it be changed to external?

### ISSUE THREAD

**Issue by Schwarao** [karmada-io/karmada#5176]
![image](https://github.com/karmada-io/karmada/assets/56160281/5561e6a1-94a4-4ab1-b63a-1eb6a209dd47)

How to use the pull mode to allow other clusters to join the Karmada through an external IP? Here, the IP is internal, how can it be changed to external?

**Comment by liangyuanpeng** [comment]
Do you tried to change the ip to external IP for registry cluster?

**Comment by Schwarao** [comment]
Do you mean to modify it directly in/etc/karma/karma apiserver. config?

**Comment by liangyuanpeng** [comment]
@Schwarao  HI, it would be great for the people coming here in the future people if you share the answer here and if you resolved it.
