### ISSUE TITLE
I want to view the information of all pods issued by Karmada through a command, and I want to know which cluster it is located on. Why is it not displayed here?

### ISSUE THREAD

**Issue by Schwarao** [karmada-io/karmada#5181]
root@iZ7xv0rsn26hoaeu2z3aabZ:~# kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get pods -A -o wide
NAMESPACE   NAME     READY   STATUS      RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
default     cvd      0/1     Completed   0          17h   <none>   <none>   <none>           <none>
default     cvd2     0/1     Completed   0          13h   <none>   <none>   <none>           <none>
default     cvd22    1/1     Running     0          17m   <none>   <none>   <none>           <none>
default     cvd222   1/1     Running     0          16m   <none>   <none>   <none>           <none>

**Comment by RainbowMango** [comment]
Please try with `karmadactl` instead of `kubectl`.

**Comment by Schwarao** [comment]
@RainbowMango  ok，thanks，so
May I ask how to install Karmada scheduler estimator? (I know we need to use the./deploy scheduler estimator. sh script to deploy)
Here is my Karmada cluster:
![image](https://github.com/user-attachments/assets/eedd466f-b664-449b-8f90-eee0509e9d37)

**Comment by chaosi-zju** [comment]
Usage: `hack/deploy-scheduler-estimator.sh <HOST_CLUSTER_KUBECONFIG> <HOST_CLUSTER_NAME> <MEMBER_CLUSTER_KUBECONFIG> <MEMBER_CLUSTER_NAME>`

Example: `hack/deploy-scheduler-estimator.sh ~/.kube/karmada.config karmada-host ~/.kube/members.config ali`

**Comment by RainbowMango** [comment]
/close 
As no further questions, and the new questions on #5187
