### ISSUE TITLE
Timeout Issue with kubectl karmada init on Azure VMs

### ISSUE THREAD

**Issue by RimDammak** [karmada-io/karmada#5201]
Hello guys,

I'm encountering an issue with configuring Karmada on my Kubernetes cluster, which is set up on Azure with three VMs.

I've followed the Karmada installation instructions with **KREW** and used `kubectl karmada init` to set up Karmada as the control plane, but the process keeps timing out. 

Here are the steps I have taken:

1. Set up a Kubernetes cluster on Azure using three VMs:
   - **Master Node Public IP**
   - **Worker Node Public IP**
2. Configured the Kubernetes cluster successfully using the following Ansible command:
   ```yaml
   shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --control-plane-endpoint="{{ hostvars['master'].ansible_host }}:6443"
   ```
3. Opened all ports in the Network Security Groups (NSGs). 

4. Attempted to initialize Karmada with the following command:
   ```sh
   kubectl karmada init --karmada-apiserver-advertise-address='172.211.10.223'
   ```
Despite these steps, the initialization process times out.

**Environment:**
- **OS**: Ubuntu Server 22.04 LTS

**Logs and Error Messages:**
### `rd@master:~$ kubectl karmada init --karmada-apiserver-advertise-address='172.211.10.223'
I0715 11:12:42.789239   13039 deploy.go:250] kubeconfig file: , kubernetes: https://172.211.10.223:6443
I0715 11:12:42.838945   13039 deploy.go:270] karmada apiserver ip: [172.211.10.223]
I0715 11:12:44.014758   13039 cert.go:246] Generate ca certificate success.
I0715 11:12:45.687074   13039 cert.go:246] Generate karmada certificate success.
I0715 11:12:48.695746   13039 cert.go:246] Generate apiserver certificate success.
I0715 11:12:49.861633   13039 cert.go:246] Generate front-proxy-ca certificate success.
I0715 11:12:50.395911   13039 cert.go:246] Generate front-proxy-client certificate success.
I0715 11:12:54.352942   13039 cert.go:246] Generate etcd-ca certificate success.
I0715 11:12:56.766361   13039 cert.go:246] Generate etcd-server certificate success.
I0715 11:12:58.945505   13039 cert.go:246] Generate etcd-client certificate success.
I0715 11:12:58.945786   13039 deploy.go:366] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.10.2/crds.tar.gz
Downloading...[ 100.00% ]
Download complete.
I0715 11:12:59.499551   13039 deploy.go:608] Create karmada kubeconfig success.
I0715 11:12:59.529480   13039 idempotency.go:267] Namespace karmada-system has been created or updated.
I0715 11:12:59.720884   13039 idempotency.go:291] Service karmada-system/etcd has been created or updated.
I0715 11:12:59.720913   13039 deploy.go:432] Create etcd StatefulSets
I0715 11:13:03.766733   13039 deploy.go:441] Create karmada ApiServer Deployment
I0715 11:13:03.813922   13039 idempotency.go:291] Service karmada-system/karmada-apiserver has been created or updated.
error: wait for Deployment(karmada-system/karmada-apiserver) rollout: context deadline exceeded: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline`

Thank you!

---

**Comment by XiShanYongYe-Chang** [comment]
Hi @chaosi-zju, can you help take a look?
cc @chaosi-zju

**Comment by chaosi-zju** [comment]
Hi @RimDammak, this maybe same problem as:
* https://github.com/karmada-io/karmada/issues/5143#issuecomment-2216866212
* #5105

You can refer to above related issue for more messages, simply put, I suspect that there is something to do with the container network of your cloud environment, which makes the `karmada-system/karmada-apiserver` unable to connect to `karmada-system/etcd-0`.

***

Besides, as I talked in https://github.com/karmada-io/karmada/issues/5105#issuecomment-2198068986,  you can do a test to check whether your kubernetes container network has problem:
* deploy a simple nginx deployment and a service
* deploy another simple ubuntu deployment and enter the container of ubuntu pod and check whether you can connect to nginx service from ubuntu container by nginx service name~

**Comment by RimDammak** [comment]
Hi everyone,

I wanted to update you on the issue I was experiencing with Karmada initialization. After troubleshooting, I figured out that the problem was related to the CNI (Container Network Interface) configuration.

I was initially using Calico as the CNI plugin, and it was causing connectivity issues between the Karmada API server and etcd. I switched to Flannel as the CNI plugin, and this resolved the problem.

   I applied the Flannel configuration with the following command:
   ```yaml
   kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
   ```
   Switching to Flannel worked perfectly, and Karmada was able to initialize without any issues.

**Comment by RimDammak** [comment]
Hi everyone,

I wanted to update you on the issue I was experiencing with Karmada initialization. After troubleshooting, I figured out that the problem was related to the CNI (Container Network Interface) configuration.

I was initially using Calico as the CNI plugin, and it was causing connectivity issues between the Karmada API server and etcd. I switched to Flannel as the CNI plugin, and this resolved the problem.

   I applied the Flannel configuration with the following command:
   ```yaml
   kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
   ```
   Switching to Flannel worked perfectly, and Karmada was able to initialize without any issues.

**Comment by chaosi-zju** [comment]
> Hi everyone,
> 
> I wanted to update you on the issue I was experiencing with Karmada initialization. After troubleshooting, I figured out that the problem was related to the CNI (Container Network Interface) configuration.
> 
> I was initially using Calico as the CNI plugin, and it was causing connectivity issues between the Karmada API server and etcd. I switched to Flannel as the CNI plugin, and this resolved the problem.
> 
> I applied the Flannel configuration with the following command:
> 
> ```yaml
> kubectl apply -f https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
> ```
> 
> Switching to Flannel worked perfectly, and Karmada was able to initialize without any issues.

Thank you very much for your feedback ! Your solution must help more people in this kind of issue~ ٩(๑❛ᴗ❛๑)۶
