### ISSUE TITLE
I don't know if this is a bug or a feature

### ISSUE THREAD

**Issue by IonBoleac** [karmada-io/karmada#5205]
**What happened**: 
To get all the member clusters I must run the `kubectl get cluster` command but if i want, for example, to get all provisioned pods i must run `kubectl karmada get pod -A`. When I run `kubectl karmada get cluster` this is the output:

```bash
      cluster(microk8s): the server doesn't have a resource type "cluster"
      cluster(microk8s-cluster): the server doesn't have a resource type "cluster"
```

 Why is there this separation? Why instead doesn't it do that when I want to interact with the multi-cluster orchestrator I can do it only through the `karmada` plugin? 

PS. I set the env var KUBECONFIG to the karmada.config file

**Environment**:
- Karmada: I installed the control plane on one of the two clusters that I want to control. I used the `kubectl karmada init --kubeconfig $HOME/.kube/config`.
- kubectl karmada version: version.Info{GitVersion:"v1.10.2", GitCommit:"8d9ab95083086a2e81acf4e6ef2f37ec852bddec", GitTreeState:"clean", BuildDate:"2024-07-02T03:25:21Z", GoVersion:"go1.21.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by XiShanYongYe-Chang** [comment]
Hi @IonBoleac, thanks for your feedback!

Currently, the query of these resources is separated. The separation principle is as follows: For Karmada resources, the kubectl command is used to query the resources. For resources in member clusters, the kubectl karmada command is used to query the resources.

Now, we are planning to [implement kubectl karmada to query all the above resources](https://github.com/karmada-io/karmada/issues/4291). You can pay attention to it. If you are convenient, you are also welcome to participate in the development or review of the code.

Let me update the labels.
/remove-kind bug
/kind question

**Comment by IonBoleac** [comment]
Hello @XiShanYongYe-Chang thanks for your quick answer!

Can you tell me some examples of this response: 
      Currently, the query of these resources is separated. The separation principle is as follows: For Karmada resources, the kubectl command is used to query the resources. For resources in member clusters, the kubectl karmada command is used to query the resources.

I asked this because I know that kubectl karmada is used to get all the resources of the multi-cluster cluster and kubectl is used to get all the resources for only one cluster. Obviously setting opportunity the KUBECONFIF variable.

**Comment by XiShanYongYe-Chang** [comment]
> I asked this because I know that kubectl karmada is used to get all the resources of the multi-cluster cluster and kubectl is used to get all the resources for only one cluster. Setting opportunity the KUBECONFIF variable.

Yeah, you're right.

> I think that I don't understand very well this separation.

In fact, there is no special reason. It's an evolving tool. It is convenient to obtain resources on different member clusters through kubectl karmada. Later, we learned from user experience feedback that if we can query resources on the karmada control plane through kubectl karmada, would be more user friendly, so we decided to do that.

**Comment by IonBoleac** [comment]
@XiShanYongYe-Chang Thanks very much for the responde. BTW i'd like to help the community to improve karmada. Can I do this?

**Comment by XiShanYongYe-Chang** [comment]
> BTW i'd like to help the community to improve karmada. Can I do this?

Of course, you're more than welcome to contribute to the community.

Hi @zhzhuang-zju, do you have a mission description for that? We can split some sub-tasks to let people choose the tasks they are interested in.

**Comment by zhzhuang-zju** [comment]
@IonBoleac Very welcome~ I'm combing through the sub-task items with @hulizhe right now, which may take a while. I'll let you know as soon as the task is posted~

**Comment by XiShanYongYe-Chang** [comment]
Let's close it first.
/close
