### ISSUE TITLE
Encountered issues while installing scheduler estimator

### ISSUE THREAD

**Issue by Schwarao** [karmada-io/karmada#5207]
![image](https://github.com/user-attachments/assets/cb32cbb5-d7e9-4a1c-b6e1-f21f5af60afd)
What is this error？
![image](https://github.com/user-attachments/assets/a7b900ed-d279-4efa-8204-f0cb2c89efaf)

**Comment by chaosi-zju** [comment]
This should be the problem that the secret names of our different installation methods are inconsistent. 

You might installed karmada by karmadactl, could you try karmadactl method to install scheduler-estimator?


```shell
$ karmadactl addons enable karmada-scheduler-estimator --cluster=aliyun--member-kubeconfig ~/.kube/config --member-context aliyun
```

**Comment by Schwarao** [comment]
> This should be the problem that the secret names of our different installation methods are inconsistent.
> 
> You might installed karmada by karmadactl, could you try karmadactl method to install scheduler-estimator?
> 
> ```shell
> $ karmadactl addons enable karmada-scheduler-estimator --cluster=aliyun --member-kubeconfig ~/.kube/config --member-context aliyun
> ```

Yes, I installed Karmada using the VNet Karmada tool, so do I need to delete these four pods first

**Comment by chaosi-zju** [comment]
> Yes, I installed Karmada using the VNet Karmada tool, so do I need to delete these four pods first

which four pods? 

You does need to delete `Deployment/karmada-scheduler-estimator-aliyun` and `Service/karmada-scheduler-estimator-aliyun` in `karmada-system` namespace

**Comment by chaosi-zju** [comment]
@XiShanYongYe-Chang  What do you think about this problem? Do we need to regard it as a bug and fix it?

Supposing we installed karmada by karmadactl or helm, we cann't use `hack/deploy-scheduler-estimator.sh` to install estimator because some secret name between different installation methods is inconsistent.

same problem may exist between other installation methods.

**Comment by Schwarao** [comment]
> 你怎么看这个问题？我们是否需要将其视为错误并修复它？
> 
> 假设我们通过 karmadactl 或 helm 安装了 karmada，我们不能用于安装估算器，因为不同安装方法之间的某些秘密名称不一致。`hack/deploy-scheduler-estimator.sh`
> 
> 其他安装方法之间可能存在相同的问题。

Yes, this is a problem, and it seems that the installation guide does not provide connections for other installation methods

**Comment by XiShanYongYe-Chang** [comment]
Thanks~

Firstly, I don't think this is a problem, but it would be best if we could standardize the naming across different installation methods.

**Comment by Schwarao** [comment]
@chaosi-zju  Can you tell me how to solve this?
![image](https://github.com/user-attachments/assets/95f02ea9-7e7a-4ef8-be05-bb26407beeae)

this is secret:
![image](https://github.com/user-attachments/assets/38374d12-c4d5-42e3-9ea4-45ab5bab5e2c)

and this is the deployment about this pod:
![image](https://github.com/user-attachments/assets/e0735d96-1a1c-4bb1-bc0a-47ef1cf0a131)

**Comment by chaosi-zju** [comment]
can you provide the command and its output of how you installed estimator?

**Comment by Schwarao** [comment]
> can you provide the command and its output of how you installed estimator?

![image](https://github.com/user-attachments/assets/b593e970-df71-462c-963d-9c14c99362ae)

**Comment by chaosi-zju** [comment]
why you use `karmada-apiserver.config` as `--member-kubeconfig` parameter?

attention:

```shell
-C, --cluster='':
        Name of the member cluster that enables or disables the scheduler estimator.

 --member-context='':
        Member cluster's context which to deploy scheduler estimator

--member-kubeconfig='':
    Member cluster's kubeconfig which to deploy scheduler estimator
```

**Comment by Schwarao** [comment]
> why you use as parameter?`karmada-apiserver.config``--member-kubeconfig`
> 
> attention:
> 
> ```shell
> -C, --cluster='':
>         Name of the member cluster that enables or disables the scheduler estimator.
> 
>  --member-context='':
>         Member cluster's context which to deploy scheduler estimator
> 
> --member-kubeconfig='':
>     Member cluster's kubeconfig which to deploy scheduler estimator
> ```
> 
> `-C` parameter should be the object name, while should be member cluster kubeconfig.`Cluster``--member-kubeconfig`

I changed the command to the following: Karamadactl addons enable Karamada search Karamada scheduler estimator - C aliyun -- member kubconfig~/. kube/config -- context aliyun
But it's still the same mistake as above

**Comment by chaosi-zju** [comment]
try: `kubectl get clusters` and provide me with output

**Comment by Schwarao** [comment]
> try: and provide me with output`kubectl get clusters`

![image](https://github.com/user-attachments/assets/df25489c-b78f-452e-a4de-52dc8f5b9a4a)

![image](https://github.com/user-attachments/assets/6a32459f-269f-4b05-8e54-e171e8dadaae)

![image](https://github.com/user-attachments/assets/ae45cbd9-d4ec-4dee-aa5e-2ece40ce7c08)

**Comment by chaosi-zju** [comment]
![image](https://github.com/user-attachments/assets/aa8d5c7f-4307-46a5-80ff-48e44b340028)
> I changed the command to the following: Karamadactl addons enable Karamada search Karamada scheduler estimator - C aliyun -- member kubconfig~/. kube/config -- context aliyun
![image](https://github.com/user-attachments/assets/208b1ad6-b5ab-439e-9f87-70a17f8b0573)

你上面尝试了三次，每次敲的命令都不一样，我感觉你每次参数都不太对，没按规范来
* 从图片看，你的集群名叫ali，应该使用 `-C ali` 或 `--cluster ali`
* 你成员集群 kubeconfig 似乎是 ~/. kube/config，应该使用 `--member-kubeconfig ~/. kube/config`
* 从前面的聊天记录看，你成员集群的 context 似乎叫 aliyun，应该使用 `--member-context aliyun`

我建议你将控制面集群里创建的老的 `Deployment/karmada-scheduler-estimator-aliyun` 卸载干净，然后重新执行下面的命令：
```shell
karmadactl addons enable karmada-scheduler-estimator --cluster ali --member-kubeconfig ~/. kube/config --member-context aliyun
```

> 抱歉，我们原则上不使用中文沟通，但我怕还是描述不清楚导致沟通低效

**Comment by Schwarao** [comment]
> ![image](https://private-user-images.githubusercontent.com/30589999/349427082-aa8d5c7f-4307-46a5-80ff-48e44b340028.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDY3MjEsIm5iZiI6MTcyMTIwNjQyMSwicGF0aCI6Ii8zMDU4OTk5OS8zNDk0MjcwODItYWE4ZDVjN2YtNDMwNy00NmE1LTgwZmYtNDhlNDRiMzQwMDI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDljYTFhMjQzMTU3ODY5YWY0YjY2NmI3ZjQ0OWExNWU3N2IwNTEzYTdhY2VmZjYzZjc4MjUzZWUxYTBmN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Ti0yigpdwbccuzSOPOxaetxuXf9vbw1UiyDbQKfItk)
> 
> > I changed the command to the following: Karamadactl addons enable Karamada search Karamada scheduler estimator - C aliyun -- member kubconfig~/. kube/config -- context aliyun
> > ![image](https://private-user-images.githubusercontent.com/30589999/349427247-208b1ad6-b5ab-439e-9f87-70a17f8b0573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDY3MjEsIm5iZiI6MTcyMTIwNjQyMSwicGF0aCI6Ii8zMDU4OTk5OS8zNDk0MjcyNDctMjA4YjFhZDYtYjVhYi00MzllLTlmODctNzBhMTdmOGIwNTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4NTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZTA1M2YyMzk3MDgxZDhkNmUwZjVjNWU4NTVjN2MyOWViNTM1YTQ1NzIzMzA4OGYwM2VlNGE5ZWI1ODc5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gqBI-rDrq3j8BL3CkgvfYWYbl8paP39SgG4exEFAeT8)
> 
> 你上面尝试了三次，每次敲的命令都不一样，我感觉你每次参数都不太对，没按规范来
> 
> * 从图片看，你的集群名叫ali，应该使用 `-C ali` 或 `--cluster ali`
> * 你成员集群 kubeconfig 似乎是 ~/. kube/config，应该使用 `--member-kubeconfig ~/. kube/config`
> * 从前面的聊天记录看，你成员集群的 context 似乎叫 aliyun，应该使用 `--member-context aliyun`
> 
> 我建议你将控制面集群里创建的老的 `Deployment/karmada-scheduler-estimator-aliyun` 卸载干净，然后重新执行下面的命令：
> 
> ```shell
> karmadactl addons enable karmada-scheduler-estimator --cluster ali --member-kubeconfig ~/. kube/config --member-context aliyun
> ```
> 
> > 抱歉，我们原则上不使用中文沟通，但我怕还是描述不清楚导致沟通低效

it's ok
![image](https://github.com/user-attachments/assets/e5fbeb33-6695-4b19-b4d1-8dfaa1f234f0)

**Comment by chaosi-zju** [comment]
Congratulations~ 👍

**Comment by XiShanYongYe-Chang** [comment]
It seems that the issue has been answered, let's close it first.
/close
