### ISSUE TITLE
The installation of karmadactl isn't working efficiently.

### ISSUE THREAD

**Issue by chouchongYHMing** [karmada-io/karmada#5208]
**What happened**:
The shell , which is "curl -s https://raw.githubusercontent.com/karmada-io/karmada/master/hack/install-cli.sh | sudo bash", wasn't  successfully executed on my macbook. So I downloaded the tgz manually.

**What you expected to happen**:
I think the shell should be  updated so that we can get the karmadactl for once. That wii be more friendly.

**Environment**:
karmadactl version : 1.10.2

**Comment by chaosi-zju** [comment]
Hi @chouchongYHMing, sorry to hear that.

The normal output should be like this:
```shell
$ curl -s https://raw.githubusercontent.com/karmada-io/karmada/master/hack/install-cli.sh | sudo bash                                           
[INFO]  Downloading metadata https://api.github.com/repos/karmada-io/karmada/releases/latest
[INFO]  Using 1.10.2 as release
[INFO]  Downloading hash https://github.com/karmada-io/karmada/releases/download/v1.10.2/karmadactl-linux-amd64.tgz.sha256
[INFO]  Downloading binary https://github.com/karmada-io/karmada/releases/download/v1.10.2/karmadactl-linux-amd64.tgz
[INFO]  Verifying binary download
[INFO]  Installing karmadactl to /usr/local/bin/karmadactl
mv: overwrite '/usr/local/bin/karmadactl'? y
```

what output is in your environment?

**Comment by chaosi-zju** [comment]
Do you have network problem to connect to `raw.githubusercontent.com`?

you can check like this:

```shell
$ ping raw.githubusercontent.com
PING raw.githubusercontent.com (185.199.111.133) 56(84) bytes of data.
64 bytes from cdn-185-199-111-133.github.com (185.199.111.133): icmp_seq=1 ttl=52 time=65.1 ms
64 bytes from cdn-185-199-111-133.github.com (185.199.111.133): icmp_seq=2 ttl=52 time=65.0 ms
64 bytes from cdn-185-199-111-133.github.com (185.199.111.133): icmp_seq=3 ttl=52 time=64.9 ms
^C
--- raw.githubusercontent.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 64.947/65.009/65.083/0.056 ms
```

**Comment by chouchongYHMing** [comment]
About the first comment, after the shell, my output is nothing.
About the second, I do can't connect to "raw.githubusercontent.com", but I can connect to"google.com", is that the key point?

**Comment by chaosi-zju** [comment]
> About the second, I do can't connect to "raw.githubusercontent.com", but I can connect to"google.com", is that the key point?

the shell is latest and no problem, but it requires downloading binary file from `raw.githubusercontent.com`, you would be stuck if you have network problem with `raw.githubusercontent.com`
