### ISSUE TITLE
Scheduler: Cluster Accurate Replica Estimator For Adjusting Replicas

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#521]
# Backgroud
Now karmada-scheduler does not know whether the member cluster has enough resource that the workload requests for. The field `ResourceSummary` in CR `Cluster` can only represent the total resource of one cluster, but cannot be a precise judgement for a workload scheduling. Actually, only the karmada-agent in cluster `PULL` mode, or the karmada-controller-manager in cluster `PUSH` mode can have all the corresponding member cluster's resource detail because they have the kubeconfig and start a synced informer. Therefore, karmada-scheduler is not able to schedule a workload by cluster free resource.

# User Story
- Case 1:  Imagine that we have 1 workload and 2 member clusters, and the `ReplicaDivisionPreference` is `Aggregated`.
  - Condition: 
    - Cluster A has 10 nodes and each has 8 cpu remaining.
    - Cluster B has 2 nodes and each has 16 cpu remaining.
    - Workload has 1 replica and requests for 12 cpu.
  - Result:
    - Workload will be scheduled to Cluster A because it has more cpu remaining in total. However, it won't work because there is no node that could match the 12-cpu request.
    - Only Cluster B can handle the workload's request but its total resource does not have a competitiveness.
- Case 2: Imagine that 1 workload has a `NodeSelector` of "key=value", and the `ReplicaDivisionPreference` is `Aggregated`.
  - Cluster A has 10 nodes and each has 16 cpu remaining.
  - Cluster B has 2 nodes, which have a label of "key=value" and each node has 16 cpu remaining.
  - Workload has 1 replica with a `NodeSelector` of "key=value" and requests for 12 cpu.
  - Result:
    - Workload will be scheduled to Cluster A because it has more cpu remaining in total. However, it won't work because there is no node that could match the `NodeSelector`.
    - Only Cluster B can handle the workload's request but its total resource does not have a competitiveness.

# Design
To solve this problem, we could change the way that we calculate the cluster available replicas. Note that it is now calculated by resource summary of a cluster.

https://github.com/karmada-io/karmada/blob/9495cf398f6f45140c9211edc994b6a392b076d3/pkg/scheduler/core/generic_scheduler.go#L331-L331

So I try to modify this function as a interface to calculate the cluster available replicas more precisely. Here's the architecture design diagram.
![design](https://user-images.githubusercontent.com/22949305/128149331-a2c0ffcd-4543-4234-affe-93f0e1ac4ced.png)

## Scheduler
First, the existing plugins such as `ClusterAffinity`, `APIInstalled` and `TaintToleration` will select the clusters. 

Based on this prefilter result, when assigning replicas, the scheduler could try to calculate cluster max available replicas by starting `gRPC` requests concurrently to replica-estimator. At last, the replica-estimator will return how many replicas that the cluster could afford. We could implement this by modifying function `calClusterAvailableReplicas` to a interface.

https://github.com/karmada-io/karmada/blob/9495cf398f6f45140c9211edc994b6a392b076d3/pkg/scheduler/core/generic_scheduler.go#L331-L331

## Cluster Accurate Replica Estimator
Abviously, when a cluster is joined into karmada control plane, the corresponding replica-estimator should be created and start a informer to watch pods and nodes in member cluster. 

Meanwhile, it must also start a `gRPC` server to serve the incoming scheduler request for filtering whether this cluster have enough resource to run `spec.replicas` pods. The result will return for scheduler judgement.

## The `gRPC` Request
The `gRPC` Request must contain some resource claims as follows.

1. PodRequest
2. NodeAffinity
3. NodeSelector
4. Tolerations

These claims usually exist in `PodSpec` field and represent their requests for nodes.

# Some Issues
- Should we add cluster-resource-prescheduler into karmada-agent? 
  - It seems resonable that karmada-agent has cached pods and nodes in member cluster. 
  - However, since the karmada-agent is deployed in member cluster, it is difficult to do a `gRPC` service discovery because karmada-scheduler is deployed in host cluster.
  - Maybe it can be deployed into *karmada-host* cluster.
- Pending pods cannot be calculated precisely because it has not been scheduled. Is there a better way to fix this problem? 
- Gang scheduling and group scheduling can be another problem, because we don't know which node it will be scheduled to.

**Comment by RainbowMango** [comment]
The `cluster-resource-prescheduler` is a goroutine for a specified cluster, right? Each `cluster-resource-prescheduler` holds/manages the resource details information, right?

**Comment by RainbowMango** [comment]
cc @kevin-wangzefeng @GitHubxsy

**Comment by Garrybest** [comment]
> The `cluster-resource-prescheduler` is a goroutine for a specified cluster, right?

Not exactly, it could be an independent module separated from the scheduler, or an goroutine intergrated into `karmada-agent`, as long as the scheduler could request.

> Each cluster-resource-prescheduler holds/manages the resource details information, right?

Indeed, it is the eyes of a cluster.

**Comment by algebra2k** [comment]
I think this scenario can be made more generic, similar to kubelet admission to double-check scheduling decisions.

**Comment by likakuli** [comment]
1. PodAntiAffinity and user custom predicate strategy also need to be considered.
2. Resources that already allocated by previous schedule cycle but pod not scheduled (include pending pods and pod not create yet) need also be calculated, otherwise the result will be incorrect the next schedule cycle.

**Comment by Garrybest** [comment]
Thanks @likakuli, it's an interesting suggestion for me.

1. `PodAntiAffinity` should be considered, but what does `user custom predicate strategy` mean? Do you mean custom scheduling filter plugins in member clusters?

2. I think you mean when we schedule the workload from karmada, but the respective pods have not been created yet or not been scheduled by `kube-scheduler`? So the estimation may have a loss. I agree, but actually I have no idea about the solution because the estimator doesn't actually know the scheduling result of `kube-scheduler`. I think it's hard.

Note that now this module just started with a low-hanging fruit for estimator from scratch, still needs more improvement. Glad to hear your voice.

**Comment by likakuli** [comment]
> 1. `PodAntiAffinity` should be considered, but what does `user custom predicate strategy` mean? Do you mean custom scheduling filter plugins in member clusters?

Yeah, I mean the custom scheduling filter plugins in member cluster. Filter and score plugin in member cluster also need to be considered in `karmada-scheduler` filter stage except APIInstalled. 



> 2\. I think you mean when we schedule the workload from karmada, but the respective pods have not been created yet or not been scheduled by `kube-scheduler`?

Yes

I agree with you that it's hard to know the exact value. There are a lot of things need to do to improve the scheduler feature. 😄
