### ISSUE TITLE
Error in setup e2e test environment

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#522]
**What happened**:
Some errors occurred in the CI workflow: 'setup e2e test environment'

https://github.com/karmada-io/karmada/runs/3042846907#step:4:231
```
Waiting for kubeconfig file /home/runner/.kube/members.config and clusters member3 to be ready...
error: cannot rename the context "kind-member3", it's not in /home/runner/.kube/members.config
```

**What you expected to happen**:

No similar errors occurred

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v0.6.0
- Others:

**Comment by lfbear** [comment]
After merging member clusters Kube config to one file, it's no longer to use the 'file existing' way to judge whether the member cluster has been created.

**Comment by RainbowMango** [comment]
I don't understand why the failure is incidental?

**Comment by lfbear** [comment]
> I don't understand why the failure is incidental?

Me too, it seems the first time. Visually the 'member3-cluster' docker startup slowly than before

**Comment by mrlihanbo** [comment]
> slowly

The failure is incidental because we check the status of clusters after `make images`. In most scenario， there is enough time to create a kind cluster.
