### ISSUE TITLE
Error when using cluster proxy

### ISSUE THREAD

**Issue by spiritNO1** [karmada-io/karmada#5228]
I am testing the aggregated api service using kubectl, the following command can work and return normal value:
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/namespaces/test/pods/test_pod

and the following command can work too:
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/*/proxy/api/v1/namespaces/test/pods/

but the following command can not work, and the error is "Error from server (NotFound): the server could not find the requested resource":
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/*/proxy/api/v1/namespaces/test/pods/test_pod

**Comment by spiritNO1** [comment]
I find the reason, the cluster spec.apiEndpoint cannot with / at the end
the following is true: 
apiEndpoint: https://XXX:6443
and the following is wrong:
apiEndpoint: https://XXX:6443/

**Comment by spiritNO1** [comment]
![image](https://github.com/user-attachments/assets/ab233b7b-995a-40f7-a7d7-a9360f01ffb9)
![image](https://github.com/user-attachments/assets/63286a7e-af60-400f-9178-fffe1058eb41)
urlStr is parsed from cluster spec.apiEndpoint

**Comment by RainbowMango** [comment]
Good for you! @spiritNO1 and thanks for the information.

cc @XiShanYongYe-Chang here to see if we need some enhancement.

**Comment by XiShanYongYe-Chang** [comment]
Hi @spiritNO1, I tested it and found it to be okay.

![image](https://github.com/user-attachments/assets/fb73a52f-8021-4074-b3b1-70b43be76ae7)

**Comment by spiritNO1** [comment]
@XiShanYongYe-Chang  apiEndpoint of the cluster config should with '/' at the end

**Comment by spiritNO1** [comment]
@XiShanYongYe-Chang  apiEndpoint of the cluster config should with '/' at the end

**Comment by XiShanYongYe-Chang** [comment]
> apiEndpoint of the cluster config should with '/' at the end

Thanks, I get it.

Would you like to contribute?

**Comment by spiritNO1** [comment]
@XiShanYongYe-Chang Very glad to
