### ISSUE TITLE
What's the usage of get_macos_ipaddress? Why necessary in mac?

### ISSUE THREAD

**Issue by vie-serendipity** [karmada-io/karmada#5230]
**Please provide an in-depth description of the question you have**:
This might be a newbie question. I want to know why get_macos_ipaddress is necessary in macos?
What's the difference between linux and macos in this aspect?
https://github.com/karmada-io/karmada/blob/bf2a6044a0de3a6219933dbd029e005cfaf7569c/hack/util.sh#L667C1-L669C39

**What do you think about this question?**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by chaosi-zju** [comment]
I am not much clear about the backgroud of `get_macos_ipaddress`.

But, the network does make a difference between linux and macos, you can refer to 

* https://github.com/docker/for-mac/issues/2670
* https://stackoverflow.com/questions/69143270/cannot-access-docker-host-from-macos

That is, unlike Docker on Linux, Docker for macOS does not expose container networks directly on the macOS host.
* Linux:   linux host  ----(`docker0` interface)----> docker container networks
* MacOS:   mac host ----> Virtual Machine ----(`docker0` interface)----> docker container networks

However, I am not sure the `get_macos_ipaddress` function is a common way to resolve this problem, after all, if you use [docker-mac-net-connect](https://github.com/chipmk/docker-mac-net-connect), you can mask the difference between the two on this issue.
