### ISSUE TITLE
[lfx-mentorship-2024-September-November] Enhance Karmada controller-manager and schedule testing coverage

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5235]
**CNCF LFX mentorship**
https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/2024/03-Sep-Nov/README.md

Mentor: @XiShanYongYe-Chang 

**What would you like to be added:**

Karmada would like to improve the UT coverage of the code to better maintain the quality of the code and reduce the introduction of defects.

Increase the UT coverage rate to 50% to 60% (currently, the UT coverage rate is [28.26%](https://app.codecov.io/gh/karmada-io/karmada) ).

The entire Karmada repository is a bit large for one project, so we will split it into two projects. The current project needs to improve UT coverage in the following directory:

```
pkg/controllers
pkg/dependenciesdistributor
pkg/descheduler
pkg/detector
pkg/estimator
pkg/scheduler
pkg/resourceinterpreter
pkg/util
```

The above directories mainly contain the `karmada-controller-manager` and `karmada-scheduler` components of Karmada.

I hope that the students who apply for this project can give the UT coverage rate of each directory plan to achieve, we will move towards these specific goals.

**Why is this needed:**

**Comment by yashpandey06** [comment]
Hey @XiShanYongYe-Chang ,hey looks like a great learning ground for me ,I would like to contribute to this issue under LFX Mentorship program.

**Comment by Harsh4902** [comment]
@XiShanYongYe-Chang I want to work on this. Can you provide some pretests?

**Comment by XiShanYongYe-Chang** [comment]
Just for reference: We can get the code coverage of different files under the current master branch from [here](https://app.codecov.io/gh/karmada-io/karmada/tree/master/).

**Comment by mani1911** [comment]
Hey @XiShanYongYe-Chang this seems apt for me to learn and I would love to contribute to this

**Comment by XiShanYongYe-Chang** [comment]
Hello everyone, thank you all very much for your active contributions, the Karmada community warmly welcomes everyone to participate in open-source contributions. You can see that the number of our LFX project spots is less than the number of applicants, which means that the final number of selected participants will be quite small. However, I hope everyone can understand that this is not because you are not good enough. On the contrary, being able to actively participate in open-source contributions, you are all very excellent. Therefore, even if you are not selected for this LFX event in the end, please don't be disappointed. There will still be LFX events to apply for in the future, and I hope everyone can continue to participate and pay attention to the Karmada community.

**Comment by XiShanYongYe-Chang** [comment]
This task will be tracked by #5470 
Thanks all.
/close
