### ISSUE TITLE
rbac错误

### ISSUE THREAD

**Issue by ayewwww** [karmada-io/karmada#5278]
**What happened**:
"status": "Failure",
  "message": "groups \"system:serviceaccounts\" is forbidden: User \"system:serviceaccount:karmada-cluster:karmada-impersonator\" cannot impersonate resource \"groups\" in API group \"\" at the cluster scope",
kubectl --kubeconfig karmada-apiserver.config get --raw /apis/cluster.karmada.io/v1alpha1/clusters/{clustername}/proxy/api/v1/nodes
这个我使用curl模拟总是报权限错误
![image](https://github.com/user-attachments/assets/28f3929f-9d3f-4600-8651-da0839b8ac48)
![image](https://github.com/user-attachments/assets/73107603-6966-408a-b59b-e6055a9c00d2)

**What you expected to happen**:
能够通过karmada apiserver访问到成员集群节点信息
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by songant** [comment]
@dekaihu 请教一下，你这个问题解决了吗，我也碰见这个问题了
