### ISSUE TITLE
命名空间删除不掉

### ISSUE THREAD

**Issue by ayewwww** [karmada-io/karmada#5284]
**What happened**:
![image](https://github.com/user-attachments/assets/e6d3ad0f-13e8-4f1f-8240-1f8bf9a7ead3)

**What you expected to happen**:
正常删除
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @ayewwww, have you fix your questions?

/kind question
/remove-kind bug

**Comment by RainbowMango** [comment]
The kubectl command explained why part of the namespace(`Name`, `default`, `kube-public`, `kube-system`) failed to delete.
And the others are terminating.

Please feel free to leave comments if you have any further questions.
/close
