### ISSUE TITLE
Expected patch operations may be missed when AggregateStatus

### ISSUE THREAD

**Issue by chaosi-zju** [karmada-io/karmada#5285]
**Background**:

Previously, we use `Patch` method to update resource template status, it is introduced in [use Patch() instead of Update() when updating workload status because error rate is too high](https://github.com/karmada-io/karmada/pull/4094).

Yet, `Patch` has two forms, that is `JSONPatchType` and `MergePatchType`, we once choose `JSONPatchType` for the reason of https://github.com/karmada-io/karmada/issues/4093#issuecomment-1768004382.

**What happened**:

When updating resource template status in `AggregateStatus` process, we get `oldStatus` from **cache** and send patch request directly to apiserver, so, here may be such extreme cases:

1. in first `Reconcile`, we got new status `{xx-field: 4}`, and finished the patch request, **supposing the cache is also updated to `{xx-field: 4}`**.
2. in second `Reconcile`, we got old status `{xx-field: 4}` and new status `{xx-field: 2}`, and finished the patch request to apiserver, however, **supposing now haven't had time to update to cache yet**.
3. in third `Reconcile`, we got old status from cache, that is still `{xx-field: 4}`, **supposing the new status is also `{xx-field: 4}`**, here is no diff filed between the old and new, so we got empty `JSONPatchType` patchBytes and keep `xx-field` unchanged.

Finally, the status is `{xx-field: 2}`, but we expect it to be `{xx-field: 4}`.

**What you expected to happen**:

we expect patch operations not be missed when `AggregateStatus`, especially if the cache update is not timely.

**How to reproduce it (as minimally and precisely as possible)**:

Appear occasionally, but it is difficult to reproduce.

**Anything else we need to know?**:

* this problem appeared twice in latest week.
* related failed CI log: https://github.com/karmada-io/karmada/issues/5136#issuecomment-2255391438

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): latest
- Others:

**Comment by chaosi-zju** [comment]
@zach593 @chaunceyjiang

**Comment by chaosi-zju** [comment]
In my opinion, we need to judge whether to use `JSONPatchType` or `MergePatchType` according to the scene.

If we only modified one or more sub field of `status`, and intentionally keep other fields unchanged, it is more suit to use `JSONPatchType`.

But if we can construct the whole `status` basing on new status, and don't care what the old status looks like, we should use `MergePatchType`.

In this case, if we change the `Patch` form to `MergePatchType`, the problem gone.

**Comment by whitewindmills** [comment]
indeed, using patch is incorrect.
> In this case, if we change the Patch form to MergePatchType, the problem gone.

but I don't get this, why is it gone? in either case, they do not verify the version, which may cause data to be overwritten.

**Comment by chaosi-zju** [comment]
> but I don't get this, why is it gone? 

we build the resource's `status` completely according to the new `aggregateStatus` of binding every time (no need to consider the old `status`)

so essentially,  `new merge old` = `new replace old`.

> in either case, they do not verify `resourceVersion`, which may cause data to be overwritten.

yes, but if we verify `resourceVersion`, it fall back to the issue #4093 commented.

**Comment by lxtywypc** [comment]
This is quite a potential problem.  

> yes, but if we verify resourceVersion, it fall back to the issue https://github.com/karmada-io/karmada/issues/4093 commented.  
And this is what we worried about.  

How about adding a new trigger to `binding-status-controller`? We could watch the status of resources, so we would be able to correct the status after the cache synced completly, as well when other controllers patched it unexpectedly.  

But I'm not sure if it would bring some side-effect.   

And maybe we quite need to review the architecture of Karmada, to solve somne related problems, for example, unnecessary updating operation, explosion of works, and potential risk of plenty of conflict.  

/cc @zach593

**Comment by whitewindmills** [comment]
no better resolutions, but some questions. :cowboy_hat_face:

> Appear occasionally, but it is difficult to reproduce.

since it's difficult to reproduce, how do you ensure that it's resolved?

> If we only modified one or more sub field of status, and intentionally keep other fields unchanged, it is more suit to use JSONPatchType.

> But if we can construct the whole status basing on new status, and don't care what the old status looks like, we should use MergePatchType.

from the code implementation point of view, it creates a patch by replacing the entire status. so even if you replace `JSON Patch` with `JSON Merge Patch`, it will change nothing.
https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/controllers/status/common.go#L125-L133
https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/util/helper/patch.go#L90-L123

BTW, the patch method we choose is determined by the modified field type and usage scenario. in this scenario, they make no difference. this is my humble opinion. maybe using update is the best way. we need to work on reducing the probability of conflict instead of choosing other modification methods. and the most effective way to reduce the probability of conflicts is to avoid reading data from the client cache.

for a comparison of JSON patch and JSON merge patch, see [JSON Patch and JSON Merge Patch](https://erosb.github.io/post/json-patch-vs-merge-patch/).

**Comment by zach593** [comment]
@chaosi-zju Sorry, I didn't fully understand the problem scenario.

The `return nil` on the `deepEqual()` check in the `helper.GenReplaceFieldJSONPatch()` function is the only place in this jsonpatch implementation that could be inconsistent due to slow caching
If the code in the helper function would pass the check, the old state would not be used, and the actual patch []byte returned should replace the entire state field according to the latest state. So why does replacing jsonpatch with mergepatch solve the problem?

**Comment by chaosi-zju** [comment]
hi @zach593

> If the code in the helper function would pass the check, the old status would not be used, and the actual patch []byte returned should replace the entire status field according to the latest state. 

supposing `oldStatus=4`, `realStatus=2`, `newStatus=4`

1. because `reflect.DeepEqual(oldStatus, newStatus)`, then `return nil`, and skip patch action, this is not expected, we expect to update status=4
2. even if we remove `reflect.DeepEqual(oldStatus, newStatus)` judgement, we direclty call `patchBytes, err := helper.GenReplaceFieldJSONPatch("/status", oldStatus, newStatus)`, then the `patchBytes` is `{}`, we cann't achieve updating status to 4.

> So why does replacing jsonpatch with mergepatch solve the problem?

just like:

```go
        oldStatus, _, _ := unstructured.NestedFieldNoCopy(resource.Object, "status")
	newStatus, _, _ := unstructured.NestedFieldNoCopy(newObj.Object, "status")

	patchBytes, err := helper.GenFieldMergePatch("status", oldStatus, newStatus)
	if err != nil {
		klog.Errorf("Failed to gen patch bytes for resource(%s/%s/%s, Error: %v", gvr, resource.GetNamespace(), resource.GetName(), err)
		return err
	}

	_, err = dynamicClient.Resource(gvr).Namespace(resource.GetNamespace()).
		Patch(context.TODO(), resource.GetName(), types.MergePatchType, patchBytes, metav1.PatchOptions{}, "status")
	if err != nil {
		klog.Errorf("Failed to update resource(%s/%s/%s), Error: %v", gvr, resource.GetNamespace(), resource.GetName(), err)
		return err
	}
```

then we send patch request `status=4` to apiserver, and apiserver update status from 2 to 4.

**Comment by zach593** [comment]
> 1. because `reflect.DeepEqual(oldStatus, newStatus)`, then `return nil`, and skip patch action, this is not expected, we expect to update status=4

> The `return nil` on the `deepEqual()` check in the `helper.GenReplaceFieldJSONPatch()` function is the only place in this jsonpatch implementation that could be inconsistent due to slow caching.

I lost some description when editing, there's should be a sentence after that: This check will never be reached because there is a check just before entering the helper.

https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/controllers/status/common.go#L125-L133

**Comment by zach593** [comment]
> just like:
> 
> ```go
>         oldStatus, _, _ := unstructured.NestedFieldNoCopy(resource.Object, "status")
> 	newStatus, _, _ := unstructured.NestedFieldNoCopy(newObj.Object, "status")
> 
> 	patchBytes, err := helper.GenFieldMergePatch("status", oldStatus, newStatus)
> 	if err != nil {
> 		klog.Errorf("Failed to gen patch bytes for resource(%s/%s/%s, Error: %v", gvr, resource.GetNamespace(), resource.GetName(), err)
> 		return err
> 	}
> 
> 	_, err = dynamicClient.Resource(gvr).Namespace(resource.GetNamespace()).
> 		Patch(context.TODO(), resource.GetName(), types.MergePatchType, patchBytes, metav1.PatchOptions{}, "status")
> 	if err != nil {
> 		klog.Errorf("Failed to update resource(%s/%s/%s), Error: %v", gvr, resource.GetNamespace(), resource.GetName(), err)
> 		return err
> 	}
> ```
> 
> then we send patch request `status=4` to apiserver, and apiserver update status from 2 to 4.

Is this the fix in your enviorment? like what I throught, you removed the deepEqual check. If you also remove the deepEqual check in the jsonpatch helper function, the problem you met should gone.

**Comment by chaosi-zju** [comment]
hi @whitewindmills 

> since it's difficult to reproduce, how do you ensure that it's resolved?

through theoretical analysis (((;꒪ꈊ꒪;)))

> from the code implementation point of view, it creates a patch by replacing the entire status. so even if you replace JSON Patch with JSON Merge Patch, it will change nothing.

No, it does have change, please see my above comment: https://github.com/karmada-io/karmada/issues/5285#issuecomment-2261946001

> the most effective way to reduce the probability of conflicts is to avoid reading data from the client cache.

I agree with your this comment, but in our this `AggregateStatus` case:
* status changes frequently.
* when we refresh the status, we do not need to consider the old status in essence. In fact, it is enough to submit the new status to the apiserver to directly replace the old status. (we don't need to think about probability of conflict and using the update method)

**Comment by chaosi-zju** [comment]
> If you also remove the deepEqual check in the jsonpatch helper function, the problem you met should gone.

Sorry, I didn't get your mean.

Do you mean you still use previuos `JSONPatchType`, but remove `DeepEqual` in following two place:

https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/controllers/status/common.go#L125-L130

https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/util/helper/patch.go#L90-L93

you think then it can also fix this problem? 

If so, I think it can not, because the output of `GenReplaceFieldJSONPatch` is the diff fields of the `oldStatus` and `newStatus`, but it actually is equal. no `add/replace/delete` request is send to apiserver.

**Comment by whitewindmills** [comment]
> because the output of GenReplaceFieldJSONPatch is the diff fields of the oldStatus and newStatus

no, it's not fields diffs, codes here.
https://github.com/karmada-io/karmada/blob/1432ecaf7822c21546916634455483089425b7bc/pkg/util/helper/patch.go#L90-L123

**Comment by chaosi-zju** [comment]
Hi @zach593 

> no, it's not fields diffs, codes here.

oh, I got your mean! you are right.

I run the test case and found, just like if the old status and new status are all like follows:

```go
appsv1.DeploymentStatus{
	ObservedGeneration: 2,
	Replicas:           2,
	UpdatedReplicas:    2,
	ReadyReplicas:      2,
	AvailableReplicas:  2,
}
```

then `GenReplaceFieldJSONPatch` will return following value (in addition that we remove the `DeepEqual` line):

```json
[{"op":"replace","path":"/status","value":{"observedGeneration":2,"replicas":2,"updatedReplicas":2,"readyReplicas":2,"availableReplicas":2}}]
```

I mistakenly thought it returned a diff of two status subfields.

So, if we just remove the two `DeepEqual` judgement, `JSONPatchType` is enough to solve this problem.

What do you think? @whitewindmills @XiShanYongYe-Chang

**Comment by zach593** [comment]
@chaosi-zju 

Just like @whitewindmills said and I quote:

> maybe using update is the best way. we need to work on reducing the probability of conflict instead of choosing other modification methods. and the most effective way to reduce the probability of conflicts is to avoid reading data from the client cache.

There are several ways to eliminate conflicts, using dynamic clients to get the latest object before comparison, or always performing patch operations, they can achieve the goal, but obviously both have costs.

I guess we need to collect more user cases or ideas before deciding on the optimization direction.

**Comment by chaosi-zju** [comment]
> using dynamic clients to get the latest object before comparison, or always performing patch operations, they can achieve the goal, but obviously both have costs.

I agree with you

> I guess we need to collect more user cases or ideas

this use case maybe difficult to collect.

I have a idea, we propagate 100 deployments to member clusters, each deployment is controllered by `FedHPA`, then constantly increasing or decreasing the pressure of the workload to trigger the status changement. Then we count the metrics of `DeepEqual` and `Reconcile`, if `DeepEqual` has small proportion, then we use `always performing patch` will not have much performance impact

**Comment by chaosi-zju** [comment]
Hi @lxtywypc, in your description:

> We could watch the status of resources

I think is difficult to watch the status resource template, because it can be a lot of Kind, even be user customized `CRD`, from code perspective, it is hard to build a `watch` mechanism

**Comment by lxtywypc** [comment]
Hi @chaosi-zju 

> I think is difficult to watch the status of resource template  

That is right but of course the `detector` completely has owned the ability. We could use a generic event and pass it through a channel between `detector` and `binding-status-controller`.  

I'm not sure what the cost is, it is just an option.

**Comment by zach593** [comment]
> I have a idea, we do a test: we propagate 100 deployments to member clusters, each deployment is controlled by `FedHPA`, then constantly increasing or decreasing the pressure of the workload to trigger the status changement. Then we count the metrics of `DeepEqual` and `Reconcile`, if `DeepEqual` has small proportion, then we use `always performing patch` will not have much performance impact

`always performing patch` will cause the controller to update all workloads multiple times when karmada-controller-manager is restarted.

**Comment by RainbowMango** [comment]
> In this case, if we change the Patch form to MergePatchType, the problem gone.

Is that true? 
I kind of agree with @whitewindmills (as mentioned above https://github.com/karmada-io/karmada/issues/5285#issuecomment-2261900339) that there is nothing to do with Patch methods, the problem seems due to the outdated cache data.

**Comment by chaosi-zju** [comment]
I did a test like this:

Before test, I add two metrics to record how many times `AggregateStatus` called and how many times `DeepEqual(oldStatus, newStatus)` meets.

Then I applied 200 `deployments` to three clusters, and the result is `AggregateStatus : DeepEqual` = 752 : 73

```shell
# TYPE deep_equal_aggragated_status counter
deep_equal_aggragated_status{event="deepEqual",result="success"} 73
deep_equal_aggragated_status{event="reconcile",result="success"} 752
```

Then I restarted the karmada-controller-manager (by delete pod way), and the new result is `AggregateStatus : DeepEqual` = 1294 : 1066

```shell
# TYPE deep_equal_aggragated_status counter
deep_equal_aggragated_status{event="deepEqual",result="success"} 1066
deep_equal_aggragated_status{event="reconcile",result="success"} 1294
```

`always patch` indeed cause many patch requests.

**Comment by chaosi-zju** [comment]
> > In this case, if we change the Patch form to MergePatchType, the problem gone.
> 
> Is that true? I kind of agree with @whitewindmills (as mentioned above [#5285 (comment)](https://github.com/karmada-io/karmada/issues/5285#issuecomment-2261900339)) that there is nothing to do with Patch methods, the problem seems due to the outdated cache data.

this is cleared in this comment: https://github.com/karmada-io/karmada/issues/5285#issuecomment-2262155614

**Comment by chaosi-zju** [comment]
I did a test like this:

Before test, I add two metrics to record how many times `AggregateStatus` called and how many times `DeepEqual(oldStatus, newStatus)` meets.

Then I applied 200 `deployments` to three clusters, and the result is `AggregateStatus : DeepEqual` = 752 : 73

```shell
# TYPE deep_equal_aggragated_status counter
deep_equal_aggragated_status{event="deepEqual",result="success"} 73
deep_equal_aggragated_status{event="reconcile",result="success"} 752
```

Then I restarted the karmada-controller-manager (by delete pod way), and the new result is `AggregateStatus : DeepEqual` = 1294 : 1066

```shell
# TYPE deep_equal_aggragated_status counter
deep_equal_aggragated_status{event="deepEqual",result="success"} 1066
deep_equal_aggragated_status{event="reconcile",result="success"} 1294
```

`always patch` indeed cause many patch requests.
