### ISSUE TITLE
Test Coverage for the function in pool.go 

### ISSUE THREAD

**Issue by yashpandey06** [karmada-io/karmada#5294]
### Issue Description

**Title**:  Test Coverage `pkg/metrics`

**Description**:
This issue aims to enhance test coverage for the `PoolCollectors` function in `pkg/metrics/pool.go` and its associated metric recording functions (`RecordPoolGet` and `RecordPoolPut`). The following test cases have been implemented:

1. **Test PoolCollectors()**: 
   - Verify that the function returns the correct Prometheus collectors (`poolGetCounter`, `poolPutCounter`).
   - Ensure the correct number and presence of expected collectors.

2. **Test RecordPoolGet(name string, created bool)**:
   - Validate the recording of pool get operations.
   - Test scenarios for both `created` values (`true` and `false`).

3. **Test RecordPoolPut(name string, destroyed bool)**:
   - Validate the recording of pool put operations.
   - Test scenarios for both `destroyed` values (`true` and `false`).

These tests ensure the accuracy and reliability of metric recording, contributing to overall code quality.

**Comment by yashpandey06** [comment]
I aim to enhance test coverage and contribute to **Karmada** by building a solid test infrastructure that ensures integrity and code quality. Additionally, I want to work under the LFX Mentorship for the upcoming season for the same .

**Comment by yashpandey06** [comment]
> /assign yashpandey06

Hey, thanks for assigning this to me .

Just for updates , I will be submitting my LFX mentorship application soon.

**Comment by XiShanYongYe-Chang** [comment]
Let me close this issue first.
/close
