### ISSUE TITLE
PolicyMarkedLabels and policyMarkedAnnotations of rb/crb may be lost when deleting the old pp/cpp and binding a new one

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/karmada#5307]
**What happened**:
Through investigating failed [e2e test: delete the old ClusterPropagationPolicy to unbind and create a new one](https://github.com/karmada-io/karmada/actions/runs/10242265387/job/28331814043) , I found that the rb's annotation `clusterpropagationpolicy.karmada.io/name` was lost during the process of unbinding the old cpp and binding a new one.
The overall process can be roughly divided into the following steps:

① delete the old cpp and create a new one
② `detector` delete the labels and annotations associated with cpp in resource template 
③ `detector` delete the labels and annotations associated with cpp in rb
④ `resource template` bind to the new cpp
⑤ update the labels and annotations associated with cpp in rb

In practice, steps 3 and 5 occur synchronously, so it's possible that what step 3 deletes are the labels and annotations updated by step 5, ultimately leading to the loss of rb/crb's `policyMarkedLabels` and `policyMarkedAnnotations`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Since step 3 often completes before steps 4 and 5, the occurrence of this issue is relatively rare. To increase the likelihood of it happening, a delay can be added in step 3.
https://github.com/karmada-io/karmada/blob/b4b6d692ca963c3d53de4a61077f4380613be0a5/pkg/detector/detector.go#L1186-L1199
and then, running command `ginkgo -v --race --trace -p  --focus="delete the old ClusterPropagationPolicy to unbind and create a new one" ./test/e2e/` will reproduce the issue.

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by whitewindmills** [comment]
great analysis, do you have any idea to fix this?

**Comment by whitewindmills** [comment]
it's a good answer.

**Comment by XiShanYongYe-Chang** [comment]
In favor of #5319 
/assign

**Comment by XiShanYongYe-Chang** [comment]
I'm sorry, I made the wrong assign.
/assign @zhzhuang-zju 
/unassign
