### ISSUE TITLE
DependentObjectReference needs the api group

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#5312]
**What would you like to be added**:
api group for DependentObjectReference
... ideally also helper methods like GroupVersionKind()

**Why is this needed**:
- to do a full api request I need the group too
- to distinguish between "configmap" and "configmap.myinternalstyem.goo" I need a group

**Comment by XiShanYongYe-Chang** [comment]
Hi @grosser, sorry for replying late.
Do you mean adding a helper method to provide a way to query the gvk?

**Comment by grosser** [comment]
oh thx, I read that wrong ... I though it's just the `v1` part and does not include the group

**Comment by grosser** [comment]
FYI solution was: `schema.FromAPIVersionAndKind(dependency.APIVersion, dependency.Kind)`
