### ISSUE TITLE
Deployment cannot be scheulded

### ISSUE THREAD

**Issue by yanweininenine** [karmada-io/karmada#532]
**What happened**:
Nginx deploy cannot be scheulded
# kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/4     0            0           16h
# kubectl get pp -o yaml
  spec:
    placement:
      clusterAffinity:
        clusterNames:
        - k8s2
    resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
# kubectl get cluster
NAME   VERSION   MODE   READY   AGE
k8s2   v1.20.0   Push   True    14h

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1、delete ns karmada-cluster in member cluster
# kubectl delete ns karmada-cluster
2、delete cluster in karmada
#kubectl delete cluster k8s2
3、rejoin k8s2
#karmadactl join k8s2 --cluster-kubeconfig=/home/work/context/k8s2-config
4、apply nginx deploy

**Anything else we need to know?**:

**Environment**:
- Karmada version: 0.7.0
- Others:

**Comment by yanweininenine** [comment]
# kubectl logs karmada-scheduler-779fd9c778-7zrcr -n karmada-system
I0714 07:04:22.255182       1 scheduler.go:164] Starting karmada scheduler
I0715 10:04:00.526863       1 scheduler.go:569] Found cluster(k8s2) failure and failover flag is true
I0715 10:04:00.526957       1 scheduler.go:602] Start traveling all ResourceBindings
I0715 10:04:00.526970       1 scheduler.go:622] Start traveling all ClusterResourceBindings
I0715 11:15:13.010398       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.015618       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.025877       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.046135       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.086429       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.166772       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.327044       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:13.647311       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:14.287599       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:15.567860       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:18.128133       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:23.248411       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:33.488693       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:15:53.969002       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:16:34.929259       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
I0715 11:17:56.849625       1 scheduler.go:422] Start scheduling binding(default/nginx-deployment)
E0715 11:17:56.849698       1 scheduler.go:542] no clusters fit
I0715 13:00:29.854139       1 scheduler.go:569] Found cluster(k8s2) failure and failover flag is true
I0715 13:00:29.854211       1 scheduler.go:602] Start traveling all ResourceBindings
I0715 13:00:29.854228       1 scheduler.go:622] Start traveling all ClusterResourceBindings

**Comment by yanweininenine** [comment]
# kubectl logs karmada-controller-manager-bf8cc4f75-p95gc -n karmada-system
W0716 04:02:42.132926       1 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
E0716 04:02:43.618927       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:03:09.744322       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:03:24.465236       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:03:36.579837       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:03:53.450930       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:04:01.064311       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:04:13.985381       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:04:45.772630       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:04:52.877821       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:04:59.403284       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:05:17.430159       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:05:26.974397       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:05:57.691159       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:06:17.220998       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:06:19.778742       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:06:36.308234       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:06:49.689608       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:07:06.698474       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:07:28.357713       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:07:32.139838       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:07:57.551186       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:08:16.521717       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized
E0716 04:08:20.650667       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized

**Comment by yanweininenine** [comment]
After deleting the  kcm and ks pod
# kubectl delete pod karmada-controller-manager-bf8cc4f75-p95gc -n karmada-system
pod "karmada-controller-manager-bf8cc4f75-p95gc" deleted
# kubectl delete pod karmada-scheduler-779fd9c778-7zrcr -n karmada-system
pod "karmada-scheduler-779fd9c778-7zrcr" deleted

The deploy can be scheduled normaly
# kubectl get deploy -o wide
NAME    READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES   SELECTOR
nginx   4/4     4            4           17h   nginx        nginx    app=nginx

**Comment by RainbowMango** [comment]
I'm thinking why you delete the `karmada-cluster` namespace on member cluster and then `delete cluster in karmada`.
Are you doing the thing `karmadactl unjoin`?

**Comment by RainbowMango** [comment]
Hi @yanweininenine 
Didn't get your response for a long time. I'm going to close it now.
As far as I know, the `Deployment` propagating functionality is covered by our E2E testing. 
Feel free to re-open it if you want further discussion.
