### ISSUE TITLE
[flaky test] remedy testing test with nil decision matches remedy [It] Create an immediately type remedy, then remove it

### ISSUE THREAD

**Issue by whitewindmills** [karmada-io/karmada#5323]
#### Which jobs are flaking:
https://github.com/karmada-io/karmada/actions/runs/10286135505/job/28492375474?pr=5316
#### Which test(s) are flaking:
remedy testing test with nil decision matches remedy [It] Create an immediately type remedy, then remove it

**Comment by whitewindmills** [comment]
@XiShanYongYe-Chang could you help take a look. retrying does not solve this problem. Blocking PR https://github.com/karmada-io/karmada/pull/5316
/assign @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Thanks @whitewindmills 
This flake maybe has been fixed.
