### ISSUE TITLE
Aggregate apiserver cannot patch pod when using "matchAllClusters"

### ISSUE THREAD

**Issue by spiritNO1** [karmada-io/karmada#5327]
Today I patch pod using aggregated apiserver, and i use wildcards * to match all clusters. But it responses 406. After a while I add log and find the problem:
In the function requestWithResourceNameHandlerFunc, it will first find the cluster of requested resource, and then handle the request. But when search the cluster of resource, the param of the function is req.Method, I think it should be "GET"
![image](https://github.com/user-attachments/assets/b0215e61-4b52-40f5-b4ab-927347400d54)
I change the code to this, and solve it.
![Uploading image.png…]()

**Comment by chaunceyjiang** [comment]
Can you share your reproduction steps? @spiritNO1

**Comment by XiShanYongYe-Chang** [comment]
> Can you share your reproduction steps? @spiritNO1

Hi @spiritNO1 I also want to know what this step is, can you provide it?
