### ISSUE TITLE
bump go version to 1.15

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#537]
**What would you like to be added**:

**Why is this needed**:

**Comment by RainbowMango** [comment]
As far as I know, there are no clear rules for people to select the Golang version.

I think we can follow kubernetes.
We are using kubernetes@v1.20.x which [depends on Golang 1.15](https://github.com/kubernetes/kubernetes/blob/8a62859e515889f07e3e3be6a1080413f17cf2c3/build/dependencies.yaml#L100-L102).
