### ISSUE TITLE
Request to be a Member of Karmada community

### ISSUE THREAD

**Issue by idouba** [karmada-io/karmada#5377]
I'm requesting to be a Member of Karmada community.

In the past several years I lead one Karmada based [product  ](https://www.huaweicloud.com/product/ucs.html), and perform
- Some code review in inner developing system
- Some design review offline or in in inner developing system
- Some feature design offline or in in inner developing system

with the process of product design and developing.

I hope more closely cooperate with Karmada community, feedback design and code to Karmada in the future, and bring Karmada to more production environment.

**Comment by XiShanYongYe-Chang** [comment]
Hi @idouba, We usually submit member applications in the [community repository](https://github.com/karmada-io/community/issues).
