### ISSUE TITLE
[Summer OSPP 2024]  karmadactl init supports configuration file

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/karmada#5387]
# What would you like to be added

As the community grows, karmada has more and more components and the configuration required is becoming more and more complex. Karmada hopes to transfer configuration items to the configuration file instead of more and more flags.

At the same time, it is hoped that a function that can list all container images used in the karmadactl init process can be implemented.

Releated:
- https://github.com/karmada-io/karmada/issues/3464
- https://github.com/karmada-io/karmada/issues/4086

This is part of https://github.com/karmada-io/karmada/issues/4879

# Project link

https://summer-ospp.ac.cn/org/prodetail/245c40186?lang=zh&list=pro

# Desired outcomes

- [x] proposal  https://github.com/karmada-io/karmada/pull/5277
- [x] implement the feature for `karmadactl config images list`    https://github.com/karmada-io/karmada/pull/5306
- [x] implement the feature for karmadactl init with configuration file  https://github.com/karmada-io/karmada/pull/5357
- [x] tests  https://github.com/karmada-io/karmada/pull/5744
- [x] blog/doc for the feature https://github.com/karmada-io/website/pull/690
- [x] sub task https://github.com/karmada-io/karmada/pull/5321
- [x] update proposal  to cleanup unnecessarily field of `metadata` (included in #5306)

**Comment by tiansuo114** [comment]
https://github.com/karmada-io/website/pull/690

Here is the documentation for karmadactl changes Supplement pr

**Comment by tiansuo114** [comment]
https://github.com/karmada-io/website/pull/690

Here is the documentation for karmadactl changes Supplement pr
@liangyuanpeng

**Comment by RainbowMango** [comment]
@tiansuo114 Congrats! All tasks have been done. Thank you for your hard work!

/close

**Comment by tiansuo114** [comment]
> # What would you like to be added
> As the community grows, karmada has more and more components and the configuration required is becoming more and more complex. Karmada hopes to transfer configuration items to the configuration file instead of more and more flags.
> 
> At the same time, it is hoped that a function that can list all container images used in the karmadactl init process can be implemented.
> 
> Releated:
> 
> * [Config file for karmadactl #3464](https://github.com/karmada-io/karmada/issues/3464)
> * [karmadactl support list images #4086](https://github.com/karmada-io/karmada/issues/4086)
> 
> This is part of #4879
> 
> # Project link
> https://summer-ospp.ac.cn/org/prodetail/245c40186?lang=zh&list=pro
> 
> # Desired outcomes
> * [x]  proposal  [docs: add proposal of karmadactl init support config file #5277](https://github.com/karmada-io/karmada/pull/5277)
> * [x]  implement the feature for `karmadactl config images list`    [Add GitHub tests for karmadactl init --config command #5306](https://github.com/karmada-io/karmada/pull/5306)
> * [x]  implement the feature for karmadactl init with configuration file  [Feature: karmadactl init supports deployment through configuration files #5357](https://github.com/karmada-io/karmada/pull/5357)
> * [x]  tests  [Add tests for deploying Karmada services using the configuration file with the karmadactl init --config command.(closed) #5744](https://github.com/karmada-io/karmada/pull/5744)
> * [x]  blog/doc for the feature [add karmadactl init --config & karmadactl config documents website#690](https://github.com/karmada-io/website/pull/690)
> * [x]  sub task [Support multiple label selection ability in EtcdNodeSelectorLabels #5321](https://github.com/karmada-io/karmada/pull/5321)
> * [x]  update proposal  to cleanup unnecessarily field of `metadata` (included in [Add GitHub tests for karmadactl init --config command #5306](https://github.com/karmada-io/karmada/pull/5306))

The PR related to tests has been changed to the PR at https://github.com/karmada-io/karmada/pull/5306. Should we update the documentation to reflect this?
@liangyuanpeng

**Comment by liangyuanpeng** [comment]
> The PR related to tests has been changed to the PR at https://github.com/karmada-io/karmada/pull/5306. Should we update the documentation to reflect this?
@liangyuanpeng

sure, i updated it, thank you!

**Comment by tiansuo114** [comment]
> > The PR related to tests has been changed to the PR at #5306. Should we update the documentation to reflect this?
> > @liangyuanpeng
> 
> sure, i updated it, thank you!

Thank you very much, Mentor, for your guidance over the past few months in completing the OSPP tasks. I am truly grateful for all the help you've provided, and I hope to receive even more guidance from you in future PRs
