### ISSUE TITLE
install karmada on exist cluster error

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#539]
**What happened**:
in my mac pc, i have kubeconfig and context

`./remote-up-karmada.sh ~/.kube/config k8s-test              
Generating a 2048 bit RSA private key
.............+++
..............................+++
writing new private key to '/Users/zl/.karmada/server-ca.key'
-----
2021/07/19 11:41:40 [INFO] generate received request
2021/07/19 11:41:40 [INFO] received CSR
2021/07/19 11:41:40 [INFO] generating key: rsa-2048
2021/07/19 11:41:41 [INFO] encoded CSR
2021/07/19 11:41:41 [INFO] signed certificate with serial number 187690599662846851313142022052868865686257444434
namespace/karmada-system created
serviceaccount/karmada-controller-manager created
serviceaccount/karmada-scheduler created
serviceaccount/karmada-webhook created
clusterrole.rbac.authorization.k8s.io/karmada-controller-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/karmada-controller-manager unchanged
Password:
sed: 1: "/var/folders/3q/7klqgj0 ...": invalid command code f
`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: 0.7.0
- Others:

**Comment by lfbear** [comment]
Adapt for macOS in local(kind) environment is processing https://github.com/karmada-io/karmada/pull/538

**Comment by lfbear** [comment]
@chestarss Could you try it again using the code of origin/master

**Comment by chestarss** [comment]
> @chestarss Could you try it again using the code of origin/master

it works

**Comment by RainbowMango** [comment]
Thanks.
/close
Feel free to open an issue if you have any further questions. :)
