### ISSUE TITLE
Add the --dry-run function to the karmadactl init command

### ISSUE THREAD

**Issue by tiansuo114** [karmada-io/karmada#5407]
**What would you like to be added**:
Add the --dry-run function to the karmadactl init command

**Why is this needed**:
While writing the Open Source Summer project, I noticed that a considerable number of kubeadm test cases use kubeadm's dry-run feature for testing, and I think if karmadactl tool can have this feature, it will be very helpful for users to use the test environment and future developers to develop

**Comment by XiShanYongYe-Chang** [comment]
Hi @tiansuo114, we create and delete kind cluster in E2E use this logic:
https://github.com/karmada-io/karmada/blob/ac589d6921d73136cc869e326ed8107ce5c990d7/test/e2e/suite_test.go#L225-L279
