### ISSUE TITLE
support deploy multicluster by order

### ISSUE THREAD

**Issue by AdrianMachao** [karmada-io/karmada#5410]
## support deploy multicluster by order

If application A want to deploy to cluser 1 and 2, he want to deploy by order 1->2 instead of  at same time. In some case
1. cluser1 and cluster2 has different  business attributes
2. some cluster is unhealthy, if cluster1 down, i need to change deploy target cluster, cluster1,2 -> cluster2, when cluster1 recover, we need reverse it, clutser2 -> cluster1,2

there is one propoal, we don't change deploy targrt, add mask in annotation of application A only in duplicate or static weighted schedule policy, for example

```apiVersion: policy.karmada.io/v1alpha1
  kind: PropagationPolicy
  metadata:
    name: nginx-propagation
    annotation:
      application.karmada.io/placement-mask=member1
  spec:
    resourceSelectors:
      - apiVersion: apps/v1
        kind: Deployment
        name: nginx
    placement:
      clusterAffinity:
        clusterNames:
          - member1
          - member2
      replicaScheduling:
        replicaSchedulingType: Divided
        weightPreference:
          staticWeightList:
            - targetCluster:
                clusterNames:
                  - member1
              weight: 1
            - targetCluster:
                clusterNames:
                  - member2
              weight: 1
```
in this case, we only deploy cluster1

**Comment by AdrianMachao** [comment]
> Hi @AdrianMachao, thanks you for your excellent idea~
> 
> yet, I have some questions.
> 
> > some cluster is unhealthy, if cluster1 down, i need to change deploy target cluster, cluster1,2 -> cluster2, when cluster1 recover, we need reverse it, clutser2 -> cluster1,2
> 
> In your this case, “if cluster1 down”, we have `failover` feature to automatically perform migrations, see: https://karmada.io/docs/next/userguide/failover/failover-overview/
> 
> "when cluster1 recover", we have `rebalance` feature to manually trigger a fresh reschedule, see: https://karmada.io/docs/next/userguide/scheduling/workload-rebalancer
> 
> Do you know the above features and whether they can meet your demands?

I know those feature, for some scene, like unit of Unit based architecture, echo cluster process different unit traffic, we can't  use those feature.
for more, we can extend more deploy mode.

**Comment by AdrianMachao** [comment]
> > there is one propoal, we don't change deploy targrt, add mask in annotation of application A only in duplicate or static weighted schedule policy, in this case, we only deploy cluster1
> 
> If expect to support deploying multicluster in order, maybe we can utilize the [suspend](https://github.com/karmada-io/karmada/pull/5118) feature. like
> 
> ```yaml
> apiVersion: policy.karmada.io/v1alpha1
> kind: PropagationPolicy
> metadata:
>   name: nginx-propagation
> spec:
>   resourceSelectors:
>     - apiVersion: apps/v1
>       kind: Deployment
>       name: nginx
>   placement:
>     clusterAffinity:
>       clusterNames:
>         - member1
>         - member2
>     replicaScheduling:
>       replicaSchedulingType: Divided
>       weightPreference:
>         staticWeightList:
>           - targetCluster:
>               clusterNames:
>                 - member1
>             weight: 1
>           - targetCluster:
>               clusterNames:
>                 - member2
>             weight: 1
>   suspension:
>     dispatchingOnClusters:
>       clusterNames:
>         - member2
> ```
> 
> The above `PropagationPolicy` will pause synchronization from the Karmada control plane to member cluster member2 until member2 is removed from the `dispatchingOnClusters` list. Therefore, it's possible to first deploy the member1 cluster. Once member1 is deployed, member2 can be removed from the `dispatchingOnClusters` list, allowing the deployment of the member2 cluster to begin.

thanks, that is what I want

**Comment by zhzhuang-zju** [comment]
@AdrianMachao Since your issue has been resolved, I'll close it now.
/close

**Comment by zhzhuang-zju** [comment]
@AdrianMachao Has your company or team already begun using Karmada?

**Comment by AdrianMachao** [comment]
> @AdrianMachao Has your company or team already begun using Karmada?

we are  trying to  use karmada instead of fed v2, we have do some modify of fed v2 and try to find those feature in karmada.

**Comment by zhzhuang-zju** [comment]
> could you tell me which company you're from and how you use Karmada in your scenarios?

@AdrianMachao  We'd like to confirm if your company has been already listed among our [adopters](https://karmada.io/adopters). And we'd always love to establish connections with users to listen to voices, provide support, and so on.

**Comment by AdrianMachao** [comment]
> > could you tell me which company you're from and how you use Karmada in your scenarios?
> 
> @AdrianMachao We'd like to confirm if your company has been already listed among our [adopters](https://karmada.io/adopters). And we'd always love to establish connections with users to listen to voices, provide support, and so on.

sorry is not very convenient to tell you my company, we haven't decide to use karmada or not for there is no strong demand .  It depend on the follow-up planning to upgrade to  karmada or not.

**Comment by zhzhuang-zju** [comment]
> sorry is not very convenient to tell you my company, we haven't decide to use karmada or not for there is no strong demand . It depend on the follow-up planning to upgrade to karmada or not. 

Never mind, if you encounter any issues with karmada later, we'll be happy to help~
