### ISSUE TITLE
Add the Ability to Specify Namespace of Scheduler Estimator Services for Karmada Scheduler

### ISSUE THREAD

**Issue by jabellard** [karmada-io/karmada#5448]
**What would you like to be added**:
When the scheduler estimator feature is enabled for the Karmada scheduler component, we can then provision scheduler estimator instances for member clusters that will provide the scheduler with more accurate information regarding resources for those member clusters. 

To gain that information, given some member cluster, the scheduler needs to contact the service for that member cluster's scheduler estimator deployment. As of today, it uses a naming convention for discovering those services. By default, given some member cluster `m1`, it will look for a service named `karmada-scheduler-estimator-m1` in the `karmada-system` namespace.
The service name prefix is [configurable](https://github.com/karmada-io/karmada/blob/release-1.10/cmd/scheduler/app/options/options.go#L139), but the namespace is [not](https://github.com/karmada-io/karmada/blob/release-1.10/pkg/estimator/client/cache.go#L104). This feature request is for providing the ability to configure the namespace in which the scheduler should try to discover the service.

**Why is this needed**:
At Bloomberg, we're currently building a managed Karmada platform and want to use the Karmada operator to manage the entire lifecycle of managed Karmada instances. Each tenant's control plane will live in a namespace in our host/management cluster. As such, we would also like to keep scheduler estimator instances scoped to their respective tenancy's namespace to avoid polluting the `karmada-system` namespace with instances across all managed tenancies.

**Comment by RainbowMango** [comment]
> The service name prefix is [configurable](https://github.com/karmada-io/karmada/blob/release-1.10/cmd/scheduler/app/options/options.go#L139), but the namespace is [not](https://github.com/karmada-io/karmada/blob/release-1.10/pkg/estimator/client/cache.go#L104). This feature request is for providing the ability to configure the namespace in which the scheduler should try to discover the service.

Yeah, I think it's a reasonable use case. What do you think? @whitewindmills @Garrybest

**Comment by whitewindmills** [comment]
+1

**Comment by Garrybest** [comment]
Nice catch. I think it's useful.

**Comment by jabellard** [comment]
@whitewindmills , I already looked into how to implement this change and have a PR I want to push.

**Comment by jabellard** [comment]
@RainbowMango , just pushed a [PR](https://github.com/karmada-io/karmada/pull/5478) for this.
