### ISSUE TITLE
Issue with Deploying Submariner Broker in Karmada Control Plane Cluster

### ISSUE THREAD

**Issue by halekammoun** [karmada-io/karmada#5460]
**Please provide an in-depth description of the question you have**:
Hello ,

I've initialized the Karmada control plane in a cluster using a Minikube profile and added member clusters also using Minikube profiles. After successfully joining the members, I attempted to connect them by deploying the broker in the control plane cluster. Unfortunately, I encountered the following error during the deployment:
```bash
Error deploying Submariner operator: error awaiting Deployment ready: error waiting for controller deployment to come up: rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout
```
![image](https://github.com/user-attachments/assets/70c43b7c-5dda-43d9-b6ac-2c2244228c3b)

I'm using subctl version: v0.18.0. Does anyone have experience with this issue or suggestions on how to resolve it?
Any help would be greatly appreciated.

Thank you!

**Comment by RainbowMango** [comment]
I guess you are not supposed to deploy broke on `karmada-apiserver`, but you should deploy it to the cluster where the karmada running on, in your case it should be the Minikube cluster.

You might need to change the `--kubeconfig` to Minikube cluster.

**Comment by halekammoun** [comment]
Thank you for the clarification!
 It works perfectly now, I really appreciate your guidance!
![image](https://github.com/user-attachments/assets/354d41de-5566-45a9-b181-95f890ddf70b)

**Comment by halekammoun** [comment]
i'm a student, just to learn karmada and i'm trying to apply it in my internship ^^
