### ISSUE TITLE
Error from server: net/http: TLS handshake timeout" when deploying ANP

### ISSUE THREAD

**Issue by axif0** [karmada-io/karmada#5461]
**Please provide an in-depth description of the question you have**:
When attempting to access the API endpoint of the Pull mode cluster (member3) through the Karmada control plane, I can't get the API endpoint used by the proxy through the karmada control plane. I tried deploying apiserver-network-proxy [(ANP)](https://karmada.io/docs/userguide/clustermanager/working-with-anp/)

![image](https://github.com/user-attachments/assets/e1645086-c17e-4297-84c4-f1c6e413b863)
![image](https://github.com/user-attachments/assets/f58bfd43-11a1-40ab-948a-2e394e8e3e1a)
![image](https://github.com/user-attachments/assets/e9c552e0-45ac-46e0-878f-0d5a3b837332)
![image](https://github.com/user-attachments/assets/aec87b9b-3c4c-42e4-9842-780eddadd410)

**What do you think about this question?**:
But  I found Error from server: net/http: TLS handshake timeout . Can you please tell me how can I set corrected `--proxy-server-address` and `--cluster-api-endpoint ` and fix this issue?

**Comment by whitewindmills** [comment]
you configured the wrong proxy-agent CA certificate. you need to check whether the certificates between proxy-server and proxy-agent are legal and match.
NOTE: `agent-identifiers` should be consistent with the ip address of `--cluster-api-endpoint`, should be `172.18.0.2`?
