### ISSUE TITLE
is there have dashboard for karmada-apiserver 

### ISSUE THREAD

**Issue by chestarss** [karmada-io/karmada#548]
is there have dashboard for karmada-apiserver 
**What would you like to be added**:

**Why is this needed**:

**Comment by RainbowMango** [comment]
I don't know if there is any dashboard for `kube-apiserver`. If there is one, it can be used for `karmada-apiserver` too.

Do you know any dashboard? @chestarss

**Comment by chestarss** [comment]
我尝试过用k8s dashboard, 标准的部署都是和apiserver在一个集群里部署的，而karmada-apiserver其实没有node,无法直接在控制面中部署，我也尝试在host集群里部署，然后改dashboard所连的apiserver为karmada-apiserver, 目前还没走通有些报错，可能和rbac权限有关

**Comment by RainbowMango** [comment]
> 我也尝试在host集群里部署，然后改dashboard所连的apiserver为karmada-apiserver,

应该是这样。我还没试过。报什么错，可以发出来看下。

**Comment by RainbowMango** [comment]
/close
The dashboard is onboarded. https://github.com/karmada-io/dashboard
