### ISSUE TITLE
service propagation removes status field in host cluster

### ISSUE THREAD

**Issue by grosser** [karmada-io/karmada#5489]
**What happened**:

- create svc in host (load balancer that stores the lb name in the status)
- add propagation to 1 member cluster
- karmada updates status to `{loadBalancer: {}}`

**What you expected to happen**:

it not to touch the status

**Anything else we need to know?**:

I can see 2 requests by karmada:
- 1 from ClaimPolicyForObject adding annotation and label
- 1 from ??? removing the status (sending the full service object but not the status) to status subresource
![image](https://github.com/user-attachments/assets/3a492f83-3b52-4ea3-bd56-8e4d5f2c9dbd)

tried disabling service import/export/mcs but still happens

**Environment**:
- Karmada version: v1.11.0

**Comment by grosser** [comment]
cause is here https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/common.go#L106

**Comment by a7i** [comment]
To add context: this is a unique _non-federated_ setup where we have controllers (i.e. aws-load-balancer controller) running in the karmada control-plane. So the control-plane status is getting updated by the member cluster service status.

PR linked allows skipping collection of resource status or we could utilize the built-in AggregateStatus interpreter for each resource kind.

**Comment by RainbowMango** [comment]
/assign @a7i 
In favor of #5490

**Comment by XiShanYongYe-Chang** [comment]
I modified the label.
/kind feature
/remove-kind bug

**Comment by RainbowMango** [comment]
> cause is here https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/common.go#L106

Yeah, it looks like it.
But this is the expected behavior that Karmada defaults to aggregate status to `resource template`.  #5490 provides a mechanism to disable this feature.
