### ISSUE TITLE
karmadactl: `karmadactl exec -C` Command Fails with Unknown Shorthand Flag Error

### ISSUE THREAD

**Issue by mohamedawnallah** [karmada-io/karmada#5522]
**What happened**:
While testing the `multiclusterservice` webhook (#5517) following the [Karmada Native Service Docs](https://karmada.io/docs/tutorials/access-service-across-clusters#access-the-backend-pods-from-member2-cluster), running the command:
```bash
karmadactl exec -C member2 curl-6894f46595-c75rc -it -- sh
```
results in:
```
error: unknown shorthand flag: 'C' in -C
```
Upon investigation in [pkg/karmadactl/exec.go](https://github.com/karmada-io/karmada/blob/4ac95b95a146488d53ee18048c09afd400129161/pkg/karmadactl/exec/exec.go#L113), it appears that the shorthand flag `-C` was removed (replaced by an empty string) in commit 914d57c from PR #5398.

**What you expected to happen**:
The command should execute successfully without the unknown flag error. That said I'm not 100% sure if the removal of the shorthand flag `-C` is expected.

**How to reproduce it (as minimally and precisely as possible)**:
Run the command:
```bash
karmadactl exec -C member2 curl-6894f46595-c75rc -it -- sh
```
or simply:
```bash
karmadactl exec -C
```

**Environment**:
  - Karmada version: `v1.11.0` 
  - `karmadactl` version: 
  ```
  version.Info{GitVersion:"v1.11.0", GitCommit:"e579560af57f9d370295b94b3a33b102f464413a", GitTreeState:"clean", BuildDate:"2024-08-31T12:08:15Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

  
  cc: @hulizhe, @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
@mohamedawnallah For the command `exec`, the flag `--cluster` is a new addition. Some community users are confused by the shared shorthand `C` for both `--cluster` and `--clusters`, so the newly added flags `cluster` and `clusters` do not provide a shorthand.

**Comment by zhzhuang-zju** [comment]
Of course, this does result in users having to type more. I am trying to reduce the amount of typing required by implementing autocompletion.

**Comment by mohamedawnallah** [comment]
Sounds good! Since those flags were introduced in the Karmada v1.11 release, should we update the documentation to reflect this? I'd be happy to submit a PR to the [karmada-io/website](https://github.com/karmada-io/website) repository if this is considered a valid issue. :)Sounds good! Since those flags were introduced in the Karmada v1.11 release, should we update the documentation to reflect this by replacing the shorthand flag `C`? I'd be happy to submit a PR to the [karmada-io/website](https://github.com/karmada-io/website) repository if this is considered a valid issue. :)

**Comment by zhzhuang-zju** [comment]
very welcome~ You can cc me as long as you are ready.

**Comment by mohamedawnallah** [comment]
Awesome!! Will close this issue now and reference it in the PR Karmada website.
