### ISSUE TITLE
Too many duplicated tcp connections from aggregated apiserver to one member cluster

### ISSUE THREAD

**Issue by lcw2** [karmada-io/karmada#5574]
**What happened**:
<img width="646" alt="image" src="https://github.com/user-attachments/assets/8e92704d-8f1c-470f-b0eb-31b589622578">
As the requests to access the aggregated API server increase, the number of connections will grow more, sometimes, the number of connection is 3000

**What you expected to happen**:
a hostIP should have a tcp connection

**How to reproduce it (as minimally and precisely as possible)**:
Execute tosfedctl get pods requests concurrently, then monitor the number of connections.

**Anything else we need to know?**:
I think the root case is,  

<img width="947" alt="image" src="https://github.com/user-attachments/assets/4ad7db08-9437-42a4-b81e-d4d682ef9360">

every reqeust will create a httptransport, so can't reuse a TCP connection.

**Environment**:
- Karmada version: 0.9 
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @lcw2, thanks for your feedback. Would you like to try to modify the logic to reuse TCP connections?

In addition, can you provide your detailed test procedure, I want to test it too.

**Comment by lcw2** [comment]
run this  script:
`#!/bin/bash
while true
do
  tosfedctl --kubeconfig xxxxxxx get pods 
  sleep 0.1
done`
1)  docker ps | grep aggregated-apiserver
2) docker inspect <containerID> | grep Pid
3) nsenter -n -t <Pid>
4) netstat -anp | grep <IP of member's cluster  >

**Comment by XiShanYongYe-Chang** [comment]
@lcw2 Thanks a lot~

**Comment by yanfeng1992** [comment]
ping @lcw2 Any progress?

**Comment by lcw2** [comment]
@yanfeng1992  I'm coding, wait two days.   I think should't disable keepalive.

**Comment by lcw2** [comment]
@yanfeng1992  I'm coding ,  wait some days.
