### ISSUE TITLE
Deploy `karmada-agent` in `karmada-host`

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#559]
What about deploying `karmada-agent` in `karmada-host`? Now it is deployed in member cluster, which means it is managed by member cluster. It has two problems:

1. The agents are not managed by a cluster so it is hard to ops, e.g., upgrading and monitoring centrally.
2. The agents may be evicted when the member cluster is busy. 

So what about deploying it in `karmada-host`, which is a independent cluster that dedicated to karmada.

**Comment by RainbowMango** [comment]
> What about deploying karmada-agent in karmada-host? 

That's an interesting approach, as far as I know, there is no restriction about where the `karmada-agent` should be deployed.
The `karmada-agent` is essentially a controller, it should work as far as it can reach both the member cluster and karmada control plane.

Looking forward to hearing your feedback, I think it totally doable.

**Comment by Garrybest** [comment]
Cool, I got you. Now it is deployed with `in-cluster` mode. 
https://github.com/karmada-io/karmada/blob/a1206fec251edf91799c6ea2fbcd74798321ef32/artifacts/agent/karmada-agent.yaml#L18
We could specify config by using "--kubeconfig". So indeed everything has been done. Thanks for your
answer. @RainbowMango 
https://github.com/karmada-io/karmada/blob/a1206fec251edf91799c6ea2fbcd74798321ef32/pkg/util/membercluster_client.go#L87
