### ISSUE TITLE
Fix typo in operator file name

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#5658]
**Task description**:
Fix the typo(`mainfests.go` --> `manifests.go`) in the following file name:
- https://github.com/karmada-io/karmada/blob/master/operator/pkg/controlplane/apiserver/mainfests.go
- https://github.com/karmada-io/karmada/blob/master/operator/pkg/controlplane/etcd/mainfests.go
- https://github.com/karmada-io/karmada/blob/master/operator/pkg/controlplane/metricsadapter/mainfests.go
- https://github.com/karmada-io/karmada/blob/master/operator/pkg/controlplane/search/mainfests.go
- https://github.com/karmada-io/karmada/blob/master/operator/pkg/controlplane/webhook/mainfests.go

**Note: This task should wait for #5536 to avoid conflicts.**

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by husnialhamdani** [comment]
Hi @RainbowMango, I interested to work on this

**Comment by RainbowMango** [comment]
Sure, go for it.
/assign @husnialhamdani

**Comment by MAVRICK-1** [comment]
@RainbowMango If no one is working on this, can I take it on?

**Comment by RainbowMango** [comment]
This task has been assigned to @husnialhamdani, and I think he is waiting for https://github.com/karmada-io/karmada/pull/5536.

**Comment by RainbowMango** [comment]
Hi @husnialhamdani Let's get started, as most of work in #5536 has been addressed by #5699 and #5720.
