### ISSUE TITLE
General-estimator will get wrong number of available replicas in some special scenarios

### ISSUE THREAD

**Issue by LivingCcj** [karmada-io/karmada#5683]
In karmada scheduler，the general-estimator will use the resource summary of each member to calculate the member cluster could place max available replicas.
However the `resourceSummary.allocatable`  will be changed, because the resource summary of member cluster is not be deep copied, and the quantity of `resourceSummary.Allocatable` is saved with infDecAmount form, the `getMaximumReplicasBasedOnClusterSummary` function will change it's value
#https://github.com/karmada-io/karmada/blob/201409c98ccfb69cd9016972f4077e507ec4ad27/pkg/estimator/client/general.go#L155-L194

So that, the general-estimator will give an incorrect result
**Environment**:
- Karmada version: v1.9.1
- kubernetes version: v1.20.10

**Comment by RainbowMango** [comment]
/assign @LivingCcj 
in favor of #5685 

Thanks for reporting and helping. I will take a look.

**Comment by RainbowMango** [comment]
> So that, the general estimator will give an incorrect result

As I mentioned at https://github.com/karmada-io/karmada/pull/5685#issuecomment-2421876875.
I agree that it's dangerous to share a pointer and modify it unexpectedly, can you explain in more detail about why this would result in an incorrect result? Do you mean the same ResourceSummary will be used in the next call of [maxAvailableReplicas](https://github.com/karmada-io/karmada/blob/e9e8653c8898605ec57c7e006293864657ef1bc5/pkg/estimator/client/general.go#L56)?
