### ISSUE TITLE
Is it available to install Karmada with the original API server?

### ISSUE THREAD

**Issue by vie-serendipity** [karmada-io/karmada#5694]
**Please provide an in-depth description of the question you have**:
For now, installing karmada needs to install and deploy new api server and kcm. The new API server can decouple the cluster's original resources and resources to be propagated, that's a great design. But it's a little complicated, I want to know is it possible to install karmada just using original KAS and KCM?
**What do you think about this question?**:
I think adding an aggregated API server directly to the existing API server and deploy other components might work. Are there any attempts or blogs to follow on this exact topic?
**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

**Comment by RainbowMango** [comment]
Please refer to [Can I install Karmada in a Kubernetes cluster and reuse the kube-apiserver as Karmada apiserver?](https://karmada.io/docs/faq/#can-i-install-karmada-in-a-kubernetes-cluster-and-reuse-the-kube-apiserver-as-karmada-apiserver).
