### ISSUE TITLE
scheduler: score plugin does not work

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#571]
**What happened**:
Score plugin does not work, the plugin list is nil. Here is the bug code.
https://github.com/karmada-io/karmada/blob/3a8a0afa0de6fccf42aa7cd48c8048b587cb052d/pkg/scheduler/framework/runtime/framework.go#L42-L48

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
We don't have a score plugin by now. But if you add a new score plugin at 
https://github.com/karmada-io/karmada/blob/df355a2267613127ddc0039bf4b7f4b39b642249/pkg/scheduler/framework/plugins/registry.go#L10-L17

and here
https://github.com/karmada-io/karmada/blob/df355a2267613127ddc0039bf4b7f4b39b642249/pkg/scheduler/scheduler.go#L104

It should work, isn't?

**Comment by RainbowMango** [comment]
/assign @Garrybest 
as he has sent a PR for this.

**Comment by Garrybest** [comment]
Right, this plugin should work when someone adds a new score plugin, however it does not work for now. Actually, I think `clusteraffinity`, `tainttoleration` and `apiinstalled` can be considered as a score plugin because they implement `Score` interface. Maybe they should not implement it if they have nothing to do with scoring. @RainbowMango

**Comment by RainbowMango** [comment]
Oh, I get your point, the thing is if a plugin implemented both `ScorePlugin` and `FilterPlugin`, it will be treated as a `FilterPlugin` because here:
https://github.com/karmada-io/karmada/blob/c971b0b6140e97a198c531ef267d19a1d779ef97/pkg/scheduler/framework/runtime/framework.go#L42-L48 

Here is a  mutually exclusive logic(`if-else`) not `if-if`.

> Maybe they should not implement it if they have nothing to do with scoring.

Let me think about it.

**Comment by RainbowMango** [comment]
> Maybe they should not implement it if they have nothing to do with scoring.

That depends on how we organize the plug-ins. I can't see significant benefits, IMO, we can consider it when we have a real score plug-in.
