### ISSUE TITLE
Are All APIs Included in the OpenAPI Swagger JSON File?

### ISSUE THREAD

**Issue by mohamedawnallah** [karmada-io/karmada#5748]
**Please provide an in-depth description of the question you have**:

Are all available APIs correctly represented in the [OpenAPI Swagger JSON file](https://github.com/karmada-io/karmada/blob/master/api/openapi-spec/swagger.json)? It seems some APIs might be missing, as there appear to be discrepancies between the APIs listed in the Swagger JSON file and the output from the following `kubectl` command:

<img width="722" alt="Screenshot 2024-10-27 at 11 15 22 PM" src="https://github.com/user-attachments/assets/a823eeb5-1965-44aa-8720-4b4fa74795bf">

```bash
dev@test:~$ kubectl --kubeconfig=$HOME/.kube/karmada.config --context=karmada-apiserver get --raw /apis/search.karmada.io/v1alpha1 | jq
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "search.karmada.io/v1alpha1",
  "resources": [
    {
      # missing
      "name": "proxying", 
      "singularName": "proxying",
      "namespaced": false,
      "kind": "Proxying",
      "verbs": [
        "create",
        "delete",
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "resourceregistries",
      "singularName": "resourceregistry",
      "namespaced": false,
      "kind": "ResourceRegistry",
      "verbs": [
        "create",
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "update",
        "watch"
      ],
      "storageVersionHash": "fCsl2+C1ckI="
    },
    {
      "name": "resourceregistries/status",
      "singularName": "",
      "namespaced": false,
      "kind": "ResourceRegistry",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      # missing
      "name": "search",
      "singularName": "search",
      "namespaced": false,
      "kind": "Search",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

**What do you think about this question?**:

Could you please confirm whether all APIs should be reflected in the Swagger JSON file, or if there is anything I'm missing?

**Comment by mohamedawnallah** [comment]
cc @XiShanYongYe-Chang, @zhzhuang-zju

**Comment by XiShanYongYe-Chang** [comment]
Hi @mohamedawnallah The APIs in the OpenAPI Swagger JSON File are complete.

Some of the missing APIs (search/proxy and search/search) you mentioned are really just used as proxy queries, and no real resource entities exist, so they don't exist in the OpenAPI Swagger JSON File.

**Comment by mohamedawnallah** [comment]
Thanks it is clear now! Gonna close this issue for now...
