### ISSUE TITLE
karmadactl pull mode join error

### ISSUE THREAD

**Issue by JamesBonddu** [karmada-io/karmada#5757]
```sh
[root@demo-master-01 ~]# karmadactl register host:32443 --token xxx--discovery-token-ca-cert-hash xxx
[preflight] Running pre-flight checks
[preflight] All pre-flight checks were passed
[karmada-agent-start] Waiting to perform the TLS Bootstrap
[karmada-agent-start] Waiting to construct karmada-agent kubeconfig

Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**What happened**:
![image](https://github.com/user-attachments/assets/4ef4acac-d73f-471e-8088-c34773158919)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.11.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
```sh
karmadactl version: version.Info{GitVersion:"v1.11.1", GitCommit:"5efee1388a2f3d75bc4590348b776587e76e3527", GitTreeState:"clean", BuildDate:"2024-09-14T09:57:01Z", GoVersion:"go1.22.7", Compiler:"gc", Platform:"linux/amd64"}

```
- Others:

**Comment by zhzhuang-zju** [comment]
@JamesBonddu Hi, has there been any progress on this issue?

**Comment by JamesBonddu** [comment]
> @JamesBonddu您好，这个问题有进展吗？

no, i rebuild it

**Comment by RainbowMango** [comment]
OK. 
Let's close it as seems we are not going to dig into it anymore.
/close

**Comment by xiaokangwang1992** [comment]
I have the same error, so, can anyone help me? My member cluster registers by accessing port 32443 of the control plane on GCP.

```
root@hgxcn25:~# karmadactl register 35.189.*.*:32443 --token **** --discovery-token-ca-cert-hash ****
[preflight] Running pre-flight checks
[preflight] All pre-flight checks were passed
[karmada-agent-start] Waiting to perform the TLS Bootstrap
Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**Comment by RainbowMango** [comment]
@xiaokangwang1992 Please open a new issue and provide us with detailed context, such as which version Karmada? How you installed it?

**Comment by RainbowMango** [comment]
I see #6327
