### ISSUE TITLE
Add Support for Custom Certificates in Karmada Operator

### ISSUE THREAD

**Issue by jabellard** [karmada-io/karmada#5784]
**What would you like to be added**:
Today, when creating a `Karmada` instance to be managed by the operator, it's not possible to use custom certificates for the instance. This feature request is for providing the ability to use custom certificates when creating a `Karmada` instance.
For reference, the helm chart already has [support](https://github.com/karmada-io/karmada/blob/release-1.11/charts/karmada/values.yaml#L127) for this feature. 

**Why is this needed**:
At Bloomberg, we're currently building a managed Karmada platform and want to use the Karmada operator to manage the entire lifecycle of managed `Karmada` instances. To fulfill some of our use cases, we would like to have the ability of specifying custom certificates when creating a `Karmada` instance.

**Comment by jabellard** [comment]
@RainbowMango , I'm working on a proposal for this feature request, and look forward to hearing your thoughts and feedback on it.

**Comment by RainbowMango** [comment]
Great, thanks for your excellent job!

I guess we can have this feature. But I can't tell clearly why people need custom certificates, or what's the benefit?

In addition to providing support for custom certificates, should we also consider the custom the way operator generates the certificates? Like, let the operator generate the expected certificates they want.

**Comment by jabellard** [comment]
> Great, thanks for your excellent job!
> 
> I guess we can have this feature. But I can't tell clearly why people need custom certificates, or what's the benefit?
> 
> In addition to providing support for custom certificates, should we also consider the custom the way operator generates the certificates? Like, let the operator generate the expected certificates they want.

@RainbowMango , thanks for your initial comments and questions. I just submitted this [proposal](https://github.com/karmada-io/karmada/pull/5794) which contains all the details, and would love to hear your thoughts on it.
