### ISSUE TITLE
如何自定义开发clusters资源对象

### ISSUE THREAD

**Issue by weixinqing** [karmada-io/karmada#5806]
**Please provide an in-depth description of the question you have**:
karmada的clusters资源对象信息无法满足工作需求，因此单独进行了开发，看了一下集群并没有clusters的crd，但是通过api-resources能看到clusters，因此我就在源码pkg/apis/cluster/v1alpha1/types.go文件里对spec部分做了新的字段添加和定义。
如下所示：
```
type ClusterStatus struct {
	// KubernetesVersion represents version of the member cluster.
	// +optional
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`

	// +optional
	KubernetesInfo string `json:"KubernetesInfo,omitempty"`
       ....
}
```
同时也对`KubernetesInfo`字段的值进行赋值
**What do you think about this question?**:
添加完字段后，也执行了hack/update-codegen.sh生成新的定义。但是构建完生成karmada-aggregated-apiserver二进制文件并替换karmada集群的karmada-aggregated-apiserver镜像后，使用`kubectl --kubeconfig=/etc/karmada/karmada-apiserver.conf get clusters -oyaml`并不能看到KubernetesInfo字段，所以请问下是我的构建流程有问题吗？我对karmada二次开发不是很熟悉，文档也翻看了很久，看了一段时间还没有找到问题原因
**Environment**:
- Karmada version: v1.11.1
- Kubernetes version: v1.25.16
- Others:

**Comment by XiShanYongYe-Chang** [comment]
你是否也同时修改了 internal 版本：pkg/apis/cluster/types.go。其他步骤看起来问题不大。

> 我对karmada二次开发不是很熟悉，文档也翻看了很久，看了一段时间还没有找到问题原因

修改Cluster定义应该已经是侵入式修改，不算二次开发了。如果对Karmada社区的API有诉求，也可以通过issue或者社区会议的形式提交到社区来交流下，看看能否直接将修改贡献到上游来。

另外方便问下，你们已经在测试或生产中使用Karmada了么？

**Comment by weixinqing** [comment]
> 你是否也同时修改了 internal 版本：pkg/apis/cluster/types.go。其他步骤看起来问题不大。
> 
> > 我对karmada二次开发不是很熟悉，文档也翻看了很久，看了一段时间还没有找到问题原因
> 
> 修改Cluster定义应该已经是侵入式修改，不算二次开发了。如果对Karmada社区的API有诉求，也可以通过issue或者社区会议的形式提交到社区来交流下，看看能否直接将修改贡献到上游来。
> 
> 另外方便问下，你们已经在测试或生产中使用Karmada了么？

是的，也修改 internal 的cluster版本。如下所示：
1、修改pkg/apis/cluster/types.go，增加KubernetesInfo字段
```
type ClusterStatus struct {
	// KubernetesVersion represents version of the member cluster.
	// +optional
	KubernetesVersion string

	// +optional
	KubernetesInfo string
        ...
}
```
2、修改pkg/apis/cluster/v1alpha1/types.go
```
type ClusterStatus struct {
	// KubernetesVersion represents version of the member cluster.
	// +optional
	KubernetesVersion string `json:"kubernetesVersion,omitempty"`

	// +optional
	KubernetesInfo string `json:"KubernetesInfo,omitempty"`
       ....
}
```
3、pkg/controllers/status/cluster_status_controller.go文件对KubernetesInfo字段进行赋值定义。最后使用hack/update-codegen.sh生成新定义，但是集群查看此资源依然没有生效。
目前在测试环境使用karmada，客户有一些定制需求，因此进行了一些单独开发。我理解这并非通用需求，因此暂未向社区贡献出来。

**Comment by XiShanYongYe-Chang** [comment]
可以先确认Cluster API是否修改成功：
使用 `kubectl explain cluster.status` 查看下是否有目标字段没？

若存在目标字段，说明对字段的更新逻辑可能存在问题。

**Comment by weixinqing** [comment]
> kubectl explain cluster.status

感谢大佬的支持，现在可以了

**Comment by XiShanYongYe-Chang** [comment]
方便问下你们是哪个公司么？

**Comment by RainbowMango** [comment]
非常不建议定制API，这将造成严重的兼容性问题，严重影响后续的版本升级。建议与社区交流使用场景，以便获取推荐的实践。

**Comment by weixinqing** [comment]
> 非常不建议定制API，这将造成严重的兼容性问题，严重影响后续的版本升级。建议与社区交流使用场景，以便获取推荐的实践。

感谢建议，我看看有没有更好的方式对其进行封装
