### ISSUE TITLE
Submariner on kind

### ISSUE THREAD

**Issue by LavredisG** [karmada-io/karmada#5877]
When following docs to install submariner and the example for <a href=https://karmada.io/docs/next/userguide/service/multi-cluster-service> multi-cluster-service</a>, I don't get the same result (that is, member clusters can't communicate with each other). I created kind clusters on my own and not using hack scripts. For it to work, do I have to disable default kind CNI and install something like Calico on my own? Or the issue is not CNI-related? I tried to study your hack scripts and didn't find anything related to setting your own CNI, so just asking to make sure if that is the case for my issue.

**Comment by XiShanYongYe-Chang** [comment]
Hi @LavredisG According to your description, I suspect that the submariner is not properly installed and the network of the two Kind clusters is not connected. You are advised to refer to the submariner's kind guide: https://submariner.io/getting-started/quickstart/kind/.
