### ISSUE TITLE
Cherry-pick #5865: Fixed the corner case where the reconciliation of aggregating status might be missed in case of component restart

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#5880]
**Which PR needs cherry-picks:**

PR #5865

**Which release branches need this patch:**

- [x] release-1.11 #5882
- [x] release-1.10 #5883
- [x] release-1.9 #5884 

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by liangyuanpeng** [comment]
/assign

prs:
- https://github.com/karmada-io/karmada/pull/5882
- https://github.com/karmada-io/karmada/pull/5883
- https://github.com/karmada-io/karmada/pull/5884

**Comment by XiShanYongYe-Chang** [comment]
Thanks @liangyuanpeng 
/close
