### ISSUE TITLE
Request to be a Member of the Karmada community

### ISSUE THREAD

**Issue by anujagrawal699** [karmada-io/karmada#5891]
**What this PR does / why we need it**:
* I have reviewed the community membership guidelines
* I have read the Contributor Guide
* I have enabled 2FA on my GitHub account
* I have subscribed to the Karmada mailing list
* Member for more than 3 months
* 49 PR merged
* Active in Karmada community and attended Karmada biweekly meetings for the same
* Completed LFX mentorship program in 2024
* Contributed significant test coverage improvements to the codebase
* Knowledgeable about the codebase, particularly in testing frameworks and implementation

PRs: https://github.com/karmada-io/karmada/pulls/anujagrawal699
Issues: https://github.com/karmada-io/karmada/issues/created_by/anujagrawal699

Sponsor 1: @zhzhuang-zju 
Sponsor 2: @Vacant2333 

**Which issue(s) this PR fixes**: 
Fixes #

**Comment by XiShanYongYe-Chang** [comment]
Hi @anujagrawal699, sorry, I forgot to tell you, you need to submit an issue in the [community ](https://github.com/karmada-io/community/issues)repository.

**Comment by anujagrawal699** [comment]
> Hi @anujagrawal699, sorry, I forgot to tell you, you need to submit an issue in the [community ](https://github.com/karmada-io/community/issues)repository.

Okay!
