### ISSUE TITLE
Karmadactl incosistent displays

### ISSUE THREAD

**Issue by LavredisG** [karmada-io/karmada#5915]
**What happened**:

Following the guide (https://karmada.io/docs/tutorials/autoscaling-with-resource-metrics/) for cross-cluster autoscaling, right after deploying workloads we are supposed to be able to view pods/services from the karmada-apiserver as per my understanding:

![image](https://github.com/user-attachments/assets/21a46b58-f95e-4380-adbd-0fe56bb9b476)

However, trying that on my system there are some issues:
1) I can't list pods from apiserver with karmadactl/kubectl
2) while an nginx-service is listed, it only appears to be on a cluster named Karmada (there is no such cluster), instead of member1 and member2 clusters as appearing on the example.

These are the results on my setup:

![image](https://github.com/user-attachments/assets/2ae4683b-c36b-474f-8f12-81c4d51f5723)

![image](https://github.com/user-attachments/assets/276e3524-8135-47c2-922c-baef37f9fb95)

**What you expected to happen**:
To have similar results as the example

**How to reproduce it (as minimally and precisely as possible)**:
Setup: 2 member clusters (member1, member2), and one host cluster on which karmada has been installed (kind for cluster deployment)

**Comment by zhzhuang-zju** [comment]
Hi, @LavredisG  `karmadactl` has changed a bit in release 1.11, introducing `operation-scope` to control the operation scope of commands. `karmadactl get` commands are scoped to the Karmada control plane by default, if you want to be able to work on both the Karmada control plane and member clusters, you can set `--operation-scope=all`, like
```bash
karmadactl get pods --operation-scope=all
```

**Comment by zhzhuang-zju** [comment]
> while an nginx-service is listed, it only appears to be on a cluster named Karmada (there is no such cluster)

As for cluster Karmada, it is used to indicate that the resource is located in the karmada control plane to distinguish it from member clusters.

**Comment by LavredisG** [comment]
> > while an nginx-service is listed, it only appears to be on a cluster named Karmada (there is no such cluster)
> 
> As for cluster Karmada, it is used to indicate that the resource is located in the karmada control plane to distinguish it from member clusters.

What about when I execute it on a member cluster as in the last screenshot? Shouldn't it display member1/member2 instead?

**Comment by zhzhuang-zju** [comment]
> What about when I execute it on a member cluster as in the last screenshot? Shouldn't it display member1/member2 instead?

The kubeconfig that karmadactl interfaces with is the karmada control plane kubeconfig. If you wish to view the resources of a member cluster, you can do so with the following command:
```shell
# only get the resources in member1
karmadactl get pods --operation-scope members --clusters member1
# get the resources in member1 and member2
karmadactl get pods --operation-scope members --clusters member1,member2
# get the resources in Karmada control plane and member1 and member2
karmadactl get pods --operation-scope all --clusters member1,member2
```
That is, `--operation-scope` is used to control the operation scope of the command, and `--clusters` is used to specify the list of member clusters.
BTW, karmadactl in release 1.12 provides `auto-completion`, which effectively reduces typing.

**Comment by LavredisG** [comment]
Oh ok I see, thought that it changes based on the context just like kubectl does. Thank you for your replies!

**Comment by zhzhuang-zju** [comment]
@LavredisG `karmadactl` has undergone significant changes in release1.11 and release1.12, aimed at enhancing the operational completeness of karmadactl. We warmly welcome you to share any issues or suggestions you encounter during usage. Your feedback is crucial for the community's continuous effort to refine and improve `karmadactl`. 
For this issue, I understand that the documentation needs to be updated accordingly. Are you interested in submitting a PR for this change?

**Comment by LavredisG** [comment]
> @LavredisG `karmadactl` has undergone significant changes in release1.11 and release1.12, aimed at enhancing the operational completeness of karmadactl. We warmly welcome you to share any issues or suggestions you encounter during usage. Your feedback is crucial for the community's continuous effort to refine and improve `karmadactl`. For this issue, I understand that the documentation needs to be updated accordingly. Are you interested in submitting a PR for this change?

I could probably fix some of these instances in the docs examples, not sure if I can find all of them though.

**Comment by zhzhuang-zju** [comment]
> I could probably fix some of these instances in the docs examples, not sure if I can find all of them though.

That's okay, we can fix the problem you found in https://karmada.io/docs/tutorials/autoscaling-with-resource-metrics/ first, and then come back later if we find another problem

**Comment by LavredisG** [comment]
I think I can close this issue for now since --operation-scope seems to resolve the issue.
