### ISSUE TITLE
Difference between SuspendDispatching and PropagationInstructionSuppressed in work

### ISSUE THREAD

**Issue by vie-serendipity** [karmada-io/karmada#5973]
**Please provide an in-depth description of the question you have**:
I noticed there are two ways to stop propagating resources of work: `SuspendDispatching` and `PropagationInstructionSuppressed.` But as I understand it, their meanings are similar, why not unify them?
**What do you think about this question?**:
Maybe deprecate `PropagationInstructionSuppressed.`

**Comment by XiShanYongYe-Chang** [comment]
Hi @vie-serendipity good catch!

> Maybe deprecate PropagationInstructionSuppressed.

Maybe deprecate PropagationInstructionSuppressed, please refer to https://github.com/karmada-io/karmada/issues/5386, do you have any good suggestions?

**Comment by vie-serendipity** [comment]
Thanks, I got the context and I shared my thoughts in https://github.com/karmada-io/karmada/issues/5386.

**Comment by RainbowMango** [comment]
> Maybe deprecate PropagationInstructionSuppressed.

Thanks @vie-serendipity for the reminder, I think that's exactly what we are going to do.
