### ISSUE TITLE
Fix ETCD PKI provisioning Issue in Karmada Operator

### ISSUE THREAD

**Issue by jabellard** [karmada-io/karmada#5975]
**What happened**:
When provisioning a Karmada instance to be managed by the Karmada operator, there's support for both in-cluster and external ETCD modes. When external ETCD mode is used, the operator should skip setting up an in-cluster ETCD instance, which entails setting up PKI for the  instance and deploying it as a stateful set. However, currently, in external ETCD mode, the operator will skip deploying the stateful set, but will still generate PKI, which is an issue. In external ETCD mode, all tasks relevant to setting up an in-cluster instance should be skipped.

**What you expected to happen**:
In external ETCD mode, all tasks relevant to setting up an in-cluster ETCD instance, including setting up PKI for the instance, should be skipped.

**How to reproduce it (as minimally and precisely as possible)**:
Try to provision a new control plane using an external ETCD instance via the Karmada operator.

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.12
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others: N/A

**Comment by jabellard** [comment]
Hey @RainbowMango . I just submitted a [PR](https://github.com/karmada-io/karmada/pull/5976) for this. Can you please take a look?

**Comment by RainbowMango** [comment]
> However, currently, in external ETCD mode, the operator will skip deploying the stateful set, but will still generate PKI, which is an issue. In external ETCD mode, all tasks relevant to setting up an in-cluster instance should be skipped.

I agree that in external ETCD mode, we don't need to generate PKI for in-cluster ETCD.
But, just out of curiosity, would generating PKI bring any serious problems?

**Comment by RainbowMango** [comment]
/assign @jabellard 
In favor of #5976

**Comment by jabellard** [comment]
> > However, currently, in external ETCD mode, the operator will skip deploying the stateful set, but will still generate PKI, which is an issue. In external ETCD mode, all tasks relevant to setting up an in-cluster instance should be skipped.
> 
> I agree that in external ETCD mode, we don't need to generate PKI for in-cluster ETCD. But, just out of curiosity, would generating PKI bring any serious problems?

Great question. The name of the secret that holds the cert for the external ETCD instance must adhere to a convention that's enforced by the operator. If we don't skip generating PKI for an in-cluster instance in external mode, then the operator will overwrite the data in that secret with data for the cert it needlessly generates.

**Comment by RainbowMango** [comment]
Oh, that sounds bad. That means people can not use the external ETCD when provisioning a Karmada instance, isn't it?

**Comment by jabellard** [comment]
> Oh, that sounds bad. That means people can not use the external ETCD when provisioning a Karmada instance, isn't it?

Yeah. That's the issue.

**Comment by RainbowMango** [comment]
That's surprising, this issue was supposed to be discovered earlier when we implemented this feature at #5242.
Don't get me wrong, I'm saying that didn't mean to blame anyone, just want to know what we missed during the previous development process.

**Comment by RainbowMango** [comment]
By the way, are you back from Christmas vacation? I know a lot of guys will take 1~2 weeks off.

**Comment by jabellard** [comment]
> That's surprising, this issue was supposed to be discovered earlier when we implemented this feature at #5242. Don't get me wrong, I'm saying that didn't mean to blame anyone, just want to know what we missed during the previous development process.

I agree. I was also surprised to see that. E2E testing worked perfectly fine before we  imposed the naming convention at some point for the external secret so that it has the exact same name as the secret that would be generated in in-cluster mode. I think this slipped through around that time.

**Comment by jabellard** [comment]
> By the way, are you back from Christmas vacation? I know a lot of guys will take 1~2 weeks off.

Found some free time today to do some coding. Will be back from vacation first week of next year.

**Comment by RainbowMango** [comment]
>  E2E testing worked perfectly fine before we imposed the naming convention at some point for the external secret so that it has the exact same name as the secret that would be generated in in-cluster mode. I think this slipped through around that time.

OK. I will investigate it further and then back to #5976. I want to know exactly which PR breaks this.

**Comment by zhzhuang-zju** [comment]
@jabellard  I combs through this issue and please correct me if there is anything incorrect or incomplete.

 In #5699, the API `ExternalEtcd.SecretRef` was introduced, at which point the naming requirement for the secret name is `{{karmada-name}}-karmada-apiserver-etcd-client-cert`.
In #5720, the relevant capability was implemented, but the naming requirement for the secret name was changed to `{{karmada-name}}-etcd-cert`, which is the same as the name of the local ETCD secret automatically generated by the operator.
In the task `NewUploadCertsTask`, automatically generated certificates will be uploaded to the corresponding secret, see
https://github.com/karmada-io/karmada/blob/e8a6ab3a56ed63b101f3eecebeefaf0a32338ae1/operator/pkg/tasks/init/upload.go#L246-L260
https://github.com/karmada-io/karmada/blob/e8a6ab3a56ed63b101f3eecebeefaf0a32338ae1/operator/pkg/util/naming.go#L37-L40

This results in the content of the secret specified by `ExternalEtcd.SecretRef` being overwritten. Furthermore, because the task `NewUploadCertsTask` occurs relatively early in the process, the ETCD certificates actually used by subsequent component initializations are the ones automatically generated by the operator.

**Comment by RainbowMango** [comment]
Thanks @zhzhuang-zju for the clarification. The issue was leaked due to a lack of E2E test coverage.
