### ISSUE TITLE
WorkloadRebalancer doesn't get deleted after TTL.

### ISSUE THREAD

**Issue by deefreak** [karmada-io/karmada#5985]
**What happened**:
A WorkloadRebalancer created with a TTL(Time To Live) field in the spec is not getting deleted after TTL has reached.

**What you expected to happen**:
WorkloadRebalancer should get deleted after TTL.

**How to reproduce it (as minimally and precisely as possible)**:
Create a workloadRebalancer with .spec.ttlSecondsAfterFinished . Verify that it is not deleted after TTL has been passed.

**Anything else we need to know?**:
NA

**Possible Cause**:
I debugged this and found few issues with the code of the [workloadrebalancer_controller.go](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go) file.

- The controller reconciles when the workloadrebalancer is created or the spec changes. [See here](https://github.com/karmada-io/karmada/blob/8fa7c2cc7df1a8d4061f6cfea035cb0625694605/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go#L59). 
- We are checking for the **rebalance.Status.FinishTime == nil** before setting the rebalancer.Status = *newStatus [here](https://github.com/karmada-io/karmada/blob/8fa7c2cc7df1a8d4061f6cfea035cb0625694605/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go#L93). So, line 93 always evaluates to true and it never reconciles again and the workload rebalancer doesn't get deleted.

**Environment**:
- Karmada version: 1.11
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

**Comment by RainbowMango** [comment]
cc @chaosi-zju

**Comment by RainbowMango** [comment]
> We are checking for the rebalance.Status.FinishTime == nil before setting the rebalancer.Status = *newStatus [here](https://github.com/karmada-io/karmada/blob/8fa7c2cc7df1a8d4061f6cfea035cb0625694605/pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go#L93). So, line 93 always evaluates to true and it never reconciles again and the workload rebalancer doesn't get deleted.

It looks like a fundamental use case. @chaosi-zju can you help to recall why it wasn't discovered in previous development?

**Comment by RainbowMango** [comment]
That's possible.
I reviewed the #4894 several rounds:
- May 14
- May 17
- May 20
- May 21
- May 23
- May 24

But I didn't ask for a final test report and didn't review the E2E tests part which was reviewed by @XiShanYongYe-Chang.
That reminds me I should always ask for a test report and review the coverage of E2E tests.

**Comment by RainbowMango** [comment]
/assign @chaosi-zju 
in favor of #5989 

Great thanks to @deefreak for reporting this issue. 

I think this issue should be backported to release-1.11 and release-1.12 after fixed on the master.

**Comment by deefreak** [comment]
> > That reminds me I should always ask for a test report and review the coverage of E2E tests.
> 
> Because when I finally submitted the code, I had already added the e2e case, so there was no manual verification.
> 
> But the e2e case was just right confirm the rebalancer works first and then add TTL for automatic cleanup, rather than directly create a rebalancer with TTL.

Yea , something like this I saw in the test case. 
Initially, I just made this work by reconciling the workloadrebalancer on status updates as well. 
Yesterday, while raising the issue, went through the code again and found that this nil check is something that is messing up with the logic.

**Comment by RainbowMango** [comment]
Opened #5992 to track the backport tasks.
@deefreak welcome to help~

**Comment by deefreak** [comment]
@RainbowMango raised 3 PRs
