### ISSUE TITLE
I won't install: Descheduler For Rescheduling

### ISSUE THREAD

**Issue by Schwarao** [karmada-io/karmada#5988]
I'm trying to install now: Descheduler For Rescheduling
。 But I don't know why the pod of karmada-descheduler won't be installed successfully.
Here's my install command: bash hack/deploy-scheduler-estimator.sh /home/rongqigang/.kube/k8s-16.conf k8s-16 /home/rongqigang/.kube/k8s-ali.conf k8s-ali
。
What else do I need to do?

![image](https://github.com/user-attachments/assets/f078dd79-18c6-47bf-8da0-0c6d68acf720)
![image](https://github.com/user-attachments/assets/bf2e050e-01a6-4440-9be1-eff057858820)
![image](https://github.com/user-attachments/assets/9b879624-dccc-4000-9cd8-a53481789517)

**Comment by XiShanYongYe-Chang** [comment]
Hi @Schwarao it seems that there is no err information.
Ask @zhzhuang-zju to help take a look.
/cc @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
@Schwarao Let me know again, are you planning to install the `descheduler`? If so, then it's not installed using the `hack/deploy-scheduler-estimator.sh` as it is for installing the `karmada-scheduler-estimator`.

**Comment by Schwarao** [comment]
> 请再次告诉我，您打算安装 ？如果是这样，则不会使用 进行安装，因为它用于安装 .`descheduler``hack/deploy-scheduler-estimator.sh``karmada-scheduler-estimator`
Yes, may I ask how to install and enable: karmada-descheduler

**Comment by Schwarao** [comment]
> > Yes, may I ask how to install and enable: karmada-descheduler
> 
> You need to tell us first how you installed karmada?
> 
> local up scipt? helm chart? operator ? or karmadactl?

Here's the command I installed:
sudo kubectl karmada init 
--etcd-init-image=alpine:3.19.2 
--karmada-aggregated-apiserver-image=karmada/karmada-aggregated-apiserver:v1.10.1  
--karmada-controller-manager-image=karmada/karmada-controller-manager:v1.10.1 
--karmada-scheduler-image=karmada/karmada-scheduler:v1.10.1 
--karmada-webhook-image=karmada/karmada-webhook:v1.10.1 
--karmada-apiserver-image=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.28.11 
--kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers 
--crds=crds.tar.gz

**Comment by Schwarao** [comment]
> so try:
> 
> `sudo kubectl karmada addons enable karmada-descheduler`

What parameters should I add?
![image](https://github.com/user-attachments/assets/affb4a95-6293-4201-b860-d8545fc19dcb)

**Comment by Schwarao** [comment]
--kubeconfig= This parameter is not to select the config of the location where I want to install the cluster, not karmada-config

**Comment by Schwarao** [comment]
it's ok，thanks

![image](https://github.com/user-attachments/assets/e71f14db-378e-4509-b52d-5d77488d8db5)

**Comment by zhzhuang-zju** [comment]
thanks @chaosi-zju 
We might be able to improve [official documentation](https://karmada.io/docs/installation/#install-karmada-by-karmada-command-line-tool) to make the installation of related components easier.   Are you interested in this? @Schwarao

**Comment by Schwarao** [comment]
Yes, I think it's probably not that clear in the documentation



> thanks @chaosi-zju We might be able to improve [official documentation](https://karmada.io/docs/installation/#install-karmada-by-karmada-command-line-tool) to make the installation of related components easier. Are you interested in this? @Schwarao

**Comment by zhzhuang-zju** [comment]
> Yes, I think it's probably not that clear in the documentation

thanks, take your time and feel free to ask any questions during the process

**Comment by Schwarao** [comment]
> > Yes, I think it's probably not that clear in the documentation
> 
> thanks, take your time and feel free to ask any questions during the process

Is there anything I can help with

**Comment by zhzhuang-zju** [comment]
Hah, my fault for not being clear. If possible, you can submit a PR to improve this documentation, or act as a reviewer for the changes.

**Comment by Schwarao** [comment]
> Hah, my fault for not being clear. If possible, you can submit a PR to improve this documentation, or act as a reviewer for the changes.

ok
