### ISSUE TITLE
Backport #5989: Fix WorkloadRebalancer can not be removed after TTL

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#5992]
**Which PR needs cherry-picks:**

PR #5989

**Which release branches need this patch:**

- [x] release-1.10 (@deefreak, https://github.com/karmada-io/karmada/pull/5993)
- [x] release-1.11 (@deefreak, https://github.com/karmada-io/karmada/pull/5994)
- [x] release-1.12 (@deefreak, https://github.com/karmada-io/karmada/pull/5995)

**How to cherry-pick PRs:**

The `hack/cherry_pick_pull.sh` script can help you initiate a cherry-pick
automatically, please follow the instructions at [this guideline](https://karmada.io/docs/contributor/cherry-picks). 

The script will send the PR for you, please remember `copy the release notes` from
the original PR by to the new PR description part.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a **separate line**.

Then, the issue will be assigned to you.

**Useful References:**

- Release timeline: https://karmada.io/docs/releases
- How to cherry-pick PRs: https://karmada.io/docs/contributor/cherry-picks

**Anything else we need to know:**

**Comment by deefreak** [comment]
@RainbowMango Raised 3 pull requests for this 
https://github.com/karmada-io/karmada/pull/5993
https://github.com/karmada-io/karmada/pull/5994
https://github.com/karmada-io/karmada/pull/5995

**Comment by RainbowMango** [comment]
Thank you and welcome @deefreak.

**Comment by RainbowMango** [comment]
/close
as all tasks done.
