### ISSUE TITLE
Avoid unnecessary scheduling to host clusters

### ISSUE THREAD

**Issue by JackZxj** [karmada-io/karmada#605]
**What would you like to be added**:
Do you plan to avoid unnecessary scheduling to host clusters? 
For example：
I created a deployment on cluster1 and cluster2, but I found that an additional deployment was created on the host cluster.

**Why is this needed**:
The deployment on host cluster is unexpected and unnecessary.

**Comment by RainbowMango** [comment]
> Do you plan to avoid unnecessary scheduling to host clusters?

The Karmada scheduler schedules workload according to a PropagationPolicy or ClusterPropagationPolicy, it never take `host` as a default cluster.

I guess you haven't deployed `karmada-apiserver` in your host cluster and re-used the `kube-apiserver` in the `host`.

**Comment by JackZxj** [comment]
> The Karmada scheduler schedules workload according to a PropagationPolicy or ClusterPropagationPolicy, it never take `host` as a default cluster.
> 
> I guess you haven't deployed `karmada-apiserver` in your host cluster and re-used the `kube-apiserver` in the `host`.

I didn't notice that during the previous test. And I retested it just now. It really won't be deployed as you said. Maybe I  accidentally deployed the wrong one when I didn't know, which led to my misunderstanding. 

Thanks for your answer!
