### ISSUE TITLE
ERROR: wait service external IP timeout, please check the load balancer IP of service: karmada-apiserver

### ISSUE THREAD

**Issue by magnate3** [karmada-io/karmada#606]
**What happened**:

hack/remote-up-karmada.sh ~/.kube/config kubernetes-admin@kubernetes
Apply dynamic rendered apiserver service in /tmp/tmp.IgJEX4iVVL/karmada-apiserver.yaml.
deployment.apps/karmada-apiserver created
service/karmada-apiserver unchanged
wait the karmada-apiserver ready...
pod/karmada-apiserver-6c77c684fb-kt47k condition met
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...
wait the external ip of karmada-apiserver ready...

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
hack/remote-up-karmada.sh ~/.kube/config kubernetes-admin@kubernetes
**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by magnate3** [comment]
solve the problem by this way:
env CLUSTER_IP_ONLY=true hack/remote-up-karmada.sh ~/.kube/config kubernetes-admin@kubernetes

**Comment by RainbowMango** [comment]
Thanks for your feedback.
/close
as issue has been solved.
