### ISSUE TITLE
local-up-karmada.sh is not compatible with apple m1/macos

### ISSUE THREAD

**Issue by fleeto** [karmada-io/karmada#616]
**What happened**:  

~~~plaintext
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 139
Command Output: qemu: uncaught target signal 11 (Segmentation fault) - core dumped
~~~

**What you expected to happen**:

Keep running until the job is finished successfully.

**How to reproduce it (as minimally and precisely as possible)**:

Run `hack/local-up=karmada.sh` in MacOS with M1 Macbook Air 

Reference: [Kind #2078](https://github.com/kubernetes-sigs/kind/issues/2078)

**Anything else we need to know?**:

K8s v1.9.11 should fix this problem, but the version number is hardcoded in `artifacts/deploy/*.yaml` and `hack/*.sh`

**Comment by RainbowMango** [comment]
Hi @lfbear 
What's the update for this issue? Does this issue still exist?

**Comment by lfbear** [comment]
It does, it needs to upgrade the version for the `kind` image. I'll test later on my m1 macbook.

**Comment by lfbear** [comment]
@RainbowMango test on my m1 MacBook has passed, this issue has been solved.

**Comment by RainbowMango** [comment]
OK. then we can close it.
/close
