### ISSUE TITLE
Unable to connect to the server: dial tcp 10.107.140.104:5443: i/o timeout

### ISSUE THREAD

**Issue by magnate3** [karmada-io/karmada#620]
**What happened**:
when i do env CLUSTER_IP_ONLY=true hack/remote-up-karmada.sh 81.k8s.conf kubernetes-admin@kubernetes
Karmada API Server's IP is: 10.107.140.104, host cluster type is: remote
Cluster "karmada-apiserver" set.
User "karmada-apiserver" set.
Context "karmada-apiserver" modified.
deployment.apps/karmada-kube-controller-manager created
Unable to connect to the server: dial tcp 10.107.140.104:5443: i/o timeout

I solve the problem with the follow ing step 

_in the k8s cluster A , do  ip route add  10.107.242.83/32 via   nodeip.
in fact,  int the k8s clusterB , through kubectl get svc  -o wide -n  karmada-system, you can see  10.107.242.83 is the CLUSTER-IP of service  karmada-apiserver_

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by RainbowMango** [comment]
So, what's your quesion?

**Comment by RainbowMango** [comment]
I get it, it's a useful use case. Thanks for the feedback.

/close
