### ISSUE TITLE
karmada api可以获取其他集群的信息么

### ISSUE THREAD

**Issue by yanlingsishao** [karmada-io/karmada#628]
通过karmada api能不能直接获取其他集群下的资源，我当前只能查cluster，但这个信息很少，针对子集群下其他资源可以直接在karmada查看么

**Comment by XiShanYongYe-Chang** [comment]
可以参考 #451 的评论。

**Comment by RainbowMango** [comment]
@yanlingsishao 
Feel free to reopen if you have further questions.
I'm going to close this issue now since it duplicated with #451.
/close
