### ISSUE TITLE
如果资源在成员集群，无法分发资源

### ISSUE THREAD

**Issue by yanlingsishao** [karmada-io/karmada#629]
我在成员集群上有一个资源，请问有办法分发到其他成员集群上么

**Comment by RainbowMango** [comment]
可以为这个资源创建一个Policy(PropagationPolicy或ClusterPropagationPolicy)，先让Karmada把这个资源管起来。再修改Policy扩展到其他成员集群。

PS：
如果这个资源同时依赖其他资源，需要一并管理。

**Comment by algebra2k** [comment]
I feel that this scenario is somewhat like to **Cloud Burst**? For example, my workload is currently in a private-cloud, when the traffic peak or resources are about to be exhausted, or when I want to conduct a promotion, I know in advance that I want to expand the workload. at this time, I will expand my load level to the public cloud cluster, but the public cloud cluster is not joined to karmada. Can we generalize this scenario?

**Comment by GitHubxsy** [comment]
> I feel that this scenario is somewhat like to **Cloud Burst**? For example, my workloads is currently run in a private-cloud, when the traffic peak or resources are about to be exhausted, or when I want to conduct a promotion, I know in advance that I want to expand the workloads. at this time, I will horizontal expansion my workloads to the public-cloud cluster, but the public-cloud cluster is not joined to karmada. I think we can make this scene more universal.

Your description looks like a multi-cluster hpa. However, we still need the central controller to detect when horizontal scaling is triggered and scale-out to a proper cluster.

**Comment by JarHMJ** [comment]
> 可以为这个资源创建一个Policy(PropagationPolicy或ClusterPropagationPolicy)，先让Karmada把这个资源管起来。再修改Policy扩展到其他成员集群。
> 
> PS：
> 如果这个资源同时依赖其他资源，需要一并管理。

需要先在karmada的控制平面先创一个资源么？然后再通过Policy分发。

有没有把成员集群的资源同步到控制平面的操作？

**Comment by RainbowMango** [comment]
可以使用`kubectl karmada promote`先把资源交给karmada管理，再进行分发。
