### ISSUE TITLE
the member cluster state is Unknown

### ISSUE THREAD

**Issue by magnate3** [karmada-io/karmada#634]
**What happened**:
[root@bogon karmada]# kubectl get clusters
NAME     VERSION   MODE   READY     AGE
251k8s             Push   Unknown   76m
k8s81              Pull   Unknown   2d1h
k8s82              Push   Unknown   30m

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by magnate3** [comment]
I find out the reason that the network betwwen agent pod and api server is not accessabile  .so should add routes and nat to sovle the problem.
[root@bogon karmada]# kubectl get clusters
NAME     VERSION   MODE   READY     AGE
 
k8s82    v1.18.0   Push   True      73m

**Comment by RainbowMango** [comment]
/close
@magnate3 Glad to hear that you've solved the problem. Feel free to contact us if you have further questions.
