### ISSUE TITLE
Wrong in MergeAnnotations

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#650]
in https://github.com/karmada-io/karmada/blob/master/pkg/util/objectwatcher/retain.go#L37, we shouldn't overwrite desiredObj's  annotations with clusterObj's.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by XiShanYongYe-Chang** [comment]
We now merge clusterObj's annotation to desiredObj's annotations.

Do you mean with old annotation `aa: bb`, desired annotation is `aa: cc`, the updated annotation still is `aa: bb`.

**Comment by pigletfly** [comment]
Exactly

**Comment by RainbowMango** [comment]
That makes sense. @pigletfly I wonder to know is there anything bad happened? :)

**Comment by pigletfly** [comment]
The annotation value is not correct,if the value is used by a controller,then it never ends

**Comment by RainbowMango** [comment]
I'm lost from this issue. Who can give an example of how to reproduce?

**Comment by RainbowMango** [comment]
/close
in favor of #1012
