### ISSUE TITLE
Proposal: get member clusters resource aggregation by `karmadactl`

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#666]
**What would you like to be added**:

Add command for `karmadactl`, such as `karmadactl get pod`, `karmadactl get deploy` to aggregate the pod or deployment resource in member clusters 

**Why is this needed**:

In the management of multi-clusters, switching between multi-clusters continuously is boring and fallible. I hope the control plane tools will minimize switching frequency and let us watch the resource conveniently.

**Comment by lfbear** [comment]
Implementation design:
1. get clusters connection from cluster.karmada.io/v1alpha1 and secret in karmada-cluster
2. get resources through the connection
3. aggregate the resource data and compare with resourcebindings

**Comment by RainbowMango** [comment]
> get clusters connection from cluster.karmada.io/v1alpha1 and secret in karmada-cluster

For `push` mode cluster, yes we can. But what about the `pull` mode cluster?

**Comment by lfbear** [comment]
> > get clusters connection from cluster.karmada.io/v1alpha1 and secret in karmada-cluster
> 
> For `push` mode cluster, yes we can. But what about the `pull` mode cluster?

I have no idea for `pull` mode, cuz `karmadactl` can not launch the connection, maybe the karmada-agent cloud sync summary data scheduled and cache them in the control plane?

**Comment by RainbowMango** [comment]
If you just want to `get` the resources propagated by Karmada, maybe we can get the information from `Work`. We don't really need to access member clusters.

**Comment by lfbear** [comment]
The very beginning, I think so too, and since I migrated some applications to Karmada, I found that:
1. Getting the real-time pod status is so important, that much like that I applied for deployment but still wanted to get pod status.
2. The `ADOPTION` flag in the sample above will tell us which is uncertain, that probably only gain by comparing with resources in member clusters

**Comment by lfbear** [comment]
There are 3 types of resources to be judge:
1. managed by Karmada completely
2. should be managed by Karmada, but actually not. such as the resources that existed before using Karmada
3. the resources not managed by Karmada

**Comment by Garrybest** [comment]
Hi, lfbear. Any news? I'm willing to have a try. @lfbear

**Comment by lfbear** [comment]
Testing, I'm reviewing the code, the PR will create next week.

**Comment by lfbear** [comment]
We found some data can not gain when implemented, this version will add:
New field for all: `CLUSTER` is the member cluster
New field for workload: `ADOPTION` is the flag(Y/N), it is a bit inconvenient for `get pod`, maybe soon later
Not Implemented field: `LAST-UPDATE`

**Comment by lfbear** [comment]
@Garrybest @RainbowMango You can have a try eg.`karmadactl get deploy` [QAQ-rookie:feature/karmada-get](https://github.com/QAQ-rookie/karmada/tree/feature/karmada-get), before trying please keep the kubeconfig file of Karmada control plane in `~/.kube/karmada.config` or `export KARMADACONFIG=[PATH of Karmada control plane kubeconfig]`
