### ISSUE TITLE
Why put the core logic codes int pkg/util?

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#670]
**What happened**:
When I read Karmada source code, I spent long time to find the controller core logic codes. Usually the controller source code in pkg/controllers, why move the codes to pkg/util?

**Comment by RainbowMango** [comment]
Which controller we are talking about?

**Comment by lonelyCZ** [comment]
> Which controller we are talking about?

like resourceDetector. Why put it into pkg/util specially?

**Comment by RainbowMango** [comment]
It's technical debt.

I think we can move it under `pkg/` directory.

> why not `pkg/controllers`?

Because the `resource detecor` is not the normal controller that reconciling objects, and cannot be disabled.

**Comment by pigletfly** [comment]
ref: https://github.com/karmada-io/karmada/pull/649#issuecomment-904461121.

**Comment by RainbowMango** [comment]
/assign @pigletfly 
Since #679
