### ISSUE TITLE
Docs: add description to cluster url

### ISSUE THREAD

**Issue by NanPaiUncle3** [karmada-io/karmada#675]
**Task description**:
在这个页面 docs/working-with-argocd.md 的 172.x.x.x ip地址，希望可以加个简单的说明
**Solution**:
对ip的来源加以简单说明，以便于用户理解
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by RainbowMango** [comment]
@NanPaiUncle3 
Can you propose a clear solution?
