### ISSUE TITLE
环境中存在kind工具，安装karmada提示找不到kind,部署失败

### ISSUE THREAD

**Issue by zhuyaguang** [karmada-io/karmada#677]
**What happened**:
运行 hack/local-up-karmada.sh 脚本，提示kind未找到
![image](https://user-images.githubusercontent.com/8857976/131210756-14353edd-e591-445b-aa11-9f5c29c8c2ac.png)

hack/karmada-bootstrap.sh 脚本 安装失败
![image](https://user-images.githubusercontent.com/8857976/131210838-fd0709d7-2408-4ff6-b44f-02e8c995a516.png)

**What you expected to happen**:
karmada 安装成功
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
按文档部署

**Comment by lfbear** [comment]
1. The message in the red box can be ignored, there is the step that clears the old version for `kind`.
2. Seems something wrong with git, please try to update your git version

**Comment by RainbowMango** [comment]
+1

/close
Feel free to open it if you have further questions.

/remove-kind bug
/kind question
