### ISSUE TITLE
[GoodFirst] Switch runner back to GitHub Action

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#681]
**Task description**:
We switch runner to `self-hosted` by #567, now it's time to switch it back since GitHub Action [has fixed the problem](https://github.com/karmada-io/karmada/issues/566#issuecomment-908246380).

**Solution**:
Undo #567.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by yuswift** [comment]
Maybe prow is another option.

**Comment by Hrishikesh156** [comment]
can you pls assign this issue to me

**Comment by RainbowMango** [comment]
> can you pls assign this issue to me

Glad to see you have assigned it to you. Thanks for doing this by the way.
