### ISSUE TITLE
[GoodFirst] Modify .gitignore to ingore karmada bninary

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#691]
**Task description**:

Current `.gitignore`  file ingore karmada binary like this:
https://github.com/karmada-io/karmada/blob/e6efe45d8974028ef30cf5f394126f768def9bd5/.gitignore#L20-L25
but this also ignores files with the same name in the recursive directory, for example: `cmd/karmadactl`. Therefore, only files in the current directory need to be ignored.

**Solution**:

Modify like this:
```diff
diff --git a/.gitignore b/.gitignore
index 50b210d..1538eb3 100644
--- a/.gitignore
+++ b/.gitignore
@@ -18,8 +18,8 @@
 .vscode/

 # karamada binary
-karmada-agent
-karmada-controller-manager
-karmada-scheduler
-karmada-webhook
-karmadactl
+/karmada-agent
+/karmada-controller-manager
+/karmada-scheduler
+/karmada-webhook
+/karmadactl
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by Onyinye91-ctrl** [comment]
@XiShanYongYe-Chang  Please i will take this issue I am taking this issue
