### ISSUE TITLE
Request preferred alias verification

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#692]
**What would you like to be added**:
The `Kubernetes` community defined a group of preferred [import aliases](https://github.com/kubernetes/kubernetes/blob/b0836a65f294d879d0000c81faa5d5149f91cf73/hack/.import-aliases), and provide a [verify-import-aliases.sh](https://github.com/kubernetes/kubernetes/blob/b0836a65f294d879d0000c81faa5d5149f91cf73/hack/verify-import-aliases.sh) to verify the codebase.

I think it's a very useful tool to keep code clean and easy to maintain. So, after talking with the tool main author @dims,  I'd like to introduce it to the Karmada project. For the preferred import aliases, we also want to define some aliases specific to the Karmada project, like `v1alpha1work`, `v1alpha1policy`, and so on.

**Why is this needed**:

*Note:* Anybody who interests in this could take the issue and help.

**Comment by ESonata** [comment]
I can try to take this issue

**Comment by RainbowMango** [comment]
Hi @ESonata 
Thanks for your help.
You can get some info from [this discussion](https://kubernetes.slack.com/archives/CHGFYJVAN/p1623298145099200).

**Comment by ESonata** [comment]
Hi @RainbowMango
I have Read  [this discussion](https://kubernetes.slack.com/archives/CHGFYJVAN/p1623298145099200).
Do you want to reimplement the function of preferredimports.go instead of copying it directly into the project?

**Comment by RainbowMango** [comment]
No, I want to `import` not re-implement or copy. Don't know if we can do that.

**Comment by ESonata** [comment]
How about running preferredimports.go in the external library (k8s.io/kubernetes) in the script and specifying our .import-aliases path?
`
go run "$GOPATH"/pkg/mod/k8s.io/kubernetes@v1.21.3/cmd/preferredimports/preferredimports.go ${IMPORT_ALIASES} ${INCLUDE_PATH} ${ROOT_PATH} 
`

**Comment by RainbowMango** [comment]
Yeah, something like this. We can install(go get/install) the `preferredimports` command or just `go run`. And we should have a `.import-aliases` in our repo.

**Comment by RainbowMango** [comment]
Hi @ESonata ,
I guess you know what gonna happen after the verification script gets onboard. Yeah, we need to unify the import aliases, so if you'd like to help fix them, you can start now. And after that, we'll put the verification on the the [check list](https://github.com/karmada-io/karmada/blob/0cdba3efa308be3979f304407a7a60d97eb80669/.github/workflows/ci.yml#L18-L21).

**Comment by ESonata** [comment]
OK.

**Comment by RainbowMango** [comment]
Hi @ESonata 

I wonder if you would like to fix the legacy import aliases in the current codebase according to new-added verification?

**Comment by ESonata** [comment]
OK.I will fit it. @RainbowMango
