### ISSUE TITLE
Add E2E test of ReplicaSchedulingStrategy

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#694]
To supplement the E2E test of `ReplicaSchedulingStrategy`:
https://github.com/karmada-io/karmada/blob/7694ba2f7d6634aedc983748f4c79d7f8d456094/pkg/apis/policy/v1alpha1/propagation_types.go#L104-L107
https://github.com/karmada-io/karmada/blob/7694ba2f7d6634aedc983748f4c79d7f8d456094/pkg/apis/policy/v1alpha1/propagation_types.go#L195-L218
I propose the following test points:

* [x] Field `ReplicaScheduling` is nill, indicating duplicated. The current test case has covered this situation.
* [ ] `ReplicaSchedulingType` value is `Duplicated`.
* [x] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Aggregated`. The scheduling result varies according to cluster resources. Therefore, the e2e test is not performed.
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is nil.
* [ ]  `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is not nil.
* [ ] `ReplicaSchedulingType` value is `Duplicated`, triggering rescheduling when replicas of `Deployment` have changed.
* [x] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Aggregated`, triggering rescheduling when replicas of `Deployment` have changed. The scheduling result varies according to cluster resources. Therefore, the e2e test is not performed.
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is nil. Triggering rescheduling when replicas of `Deployment` have changed. 
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is not nil. Triggering rescheduling when replicas of `Deployment` have changed. 

@qianjun1993 Please have a look.

**Comment by qianjun1993** [comment]
Good idea.
