### ISSUE TITLE
Add some metrics for scheduler

### ISSUE THREAD

**Issue by qianjun1993** [karmada-io/karmada#695]
Add some metrics for scheduler。

I propose the following metrics:

- [x] scheduleAttempts.  The number of attempts to schedule resourceBinding. It may be  specified by the schedule type and result 
- [x] e2eSchedulingLatency. The e2e scheduling latency in seconds of an attempts to schedule resourceBinding. It also may be specified by the schedule type and result
- [x] SchedulingAlgorithmLatency. The scheduling algorithm latency of generic_scheduler in seconds. It may be specified by the four steps(Filter、Score、Select、AssignReplicas)
- [x] SchedulerQueueIncomingBindings。The number of binding added to scheduling queues by event type
- [ ] BindingSchedulingDuration. The duration from each binding added to  scheduling queues to it is scheduled 
- [ ] BindingSchedulingAttempts. The scheduling attempts of each binding.

The first four are easy to realize， but the last two may need some reform of the scheduling queues. 
Also welcome for other metrics.

**Comment by RainbowMango** [comment]
Yes. It's time to add some metrics.
Can you also propose the metrics type and name? A sample metrics would be better.

**Comment by qianjun1993** [comment]
`	scheduleAttempts = metrics.NewCounterVec(
		&metrics.CounterOpts{
			Subsystem:      SchedulerSubsystem,
			Name:           "schedule_attempts_total",
			Help:           "Number of attempts to schedule resourceBinding",
			StabilityLevel: metrics.ALPHA,
		}, []string{"result", "scheduleType"})

	e2eSchedulingLatency = metrics.NewHistogramVec(
		&metrics.HistogramOpts{
			Subsystem:      SchedulerSubsystem,
			Name:           "e2e_scheduling_duration_seconds",
			Help:           "E2e scheduling latency in seconds",
			Buckets:        metrics.ExponentialBuckets(0.001, 2, 15),
			StabilityLevel: metrics.ALPHA,
		}, []string{"result", "scheduleType"})

	SchedulingAlgorithmLatency = metrics.NewHistogramVec(
		&metrics.HistogramOpts{
			Subsystem:      SchedulerSubsystem,
			Name:           "scheduling_algorithm_duration_seconds",
			Help:           "Scheduling algorithm latency in seconds(exclude scale scheduler)",
			Buckets:        metrics.ExponentialBuckets(0.001, 2, 15),
			StabilityLevel: metrics.ALPHA,
		}, []string{"scheduleStep"})

	SchedulerQueueIncomingBindings = metrics.NewCounterVec(
		&metrics.CounterOpts{
			Subsystem:      SchedulerSubsystem,
			Name:           "queue_incoming_Bindings_total",
			Help:           "Number of Bindings added to scheduling queues by event type.",
			StabilityLevel: metrics.ALPHA,
		}, []string{"event"})
	
       BindingSchedulingDuration = metrics.NewHistogramVec(
		&metrics.HistogramOpts{
			Subsystem: SchedulerSubsystem,
			Name:      "binding_scheduling_duration_seconds",
			Help:      "E2e latency for a binding being scheduled which may include multiple scheduling attempts.",
			// Start with 10ms with the last bucket being [~88m, Inf).
			Buckets:        metrics.ExponentialBuckets(0.01, 2, 20),
			StabilityLevel: metrics.ALPHA,
		},
		[]string{"attempts"})

	BindingSchedulingAttempts = metrics.NewHistogram(
		&metrics.HistogramOpts{
			Subsystem:      SchedulerSubsystem,
			Name:           "binding_scheduling_attempts",
			Help:           "Number of attempts to successfully schedule a binding.",
			Buckets:        metrics.ExponentialBuckets(1, 2, 5),
			StabilityLevel: metrics.ALPHA,
		})
`

**Comment by RainbowMango** [comment]
Hey guys, let's do it！ 

Seems @kerthcet wants help. @qianjun1993 You might want to share some tasks with @kerthcet.

@qianjun1993 Can you pick one metric to kick-off? We have a lot of works to do, that's more than these metrics.

Let's discuss the metrics in the PR.

**Comment by kerthcet** [comment]
I have already introduced the first three subtasks, still in progress. @RainbowMango

**Comment by qianjun1993** [comment]
@kerthcet  thanks for your help. I have also already implemented a version of the first four tasks. Maybe we can have a discuss about these metrics.

**Comment by kerthcet** [comment]
> @kerthcet thanks for your help. I have also already implemented a version of the first four tasks. Maybe we can have a discuss about these metrics.

Since I'm out of band these days, I'm happy to see that. I'll keep tracking.

**Comment by RainbowMango** [comment]
Out of band?

We have a meeting today, I'm glad to meet you there and have a quick chat.
I really want this in the coming release.

**Comment by kerthcet** [comment]
sorry，spelling mistake,  out of bandwidth instead , I'm happy to participate in the meeting.

**Comment by RainbowMango** [comment]
Hi, how is this going now?

**Comment by kerthcet** [comment]
since @qianjun1993 is following this issue, I didn't pay close attention to.

**Comment by qianjun1993** [comment]
I have propose a pr for the first four metrics. The last two may need more time since it may changes the structure of scheduler queue

**Comment by kerthcet** [comment]
I'm glad to work on the last two subtasks if possible. @qianjun1993

**Comment by qianjun1993** [comment]
Thanks for your help @kerthcet

**Comment by RainbowMango** [comment]
/close

Please reopen it if we still need it.
