### ISSUE TITLE
Automatically Propagate Relevant Resources TODO List

### ISSUE THREAD

**Issue by mrlihanbo** [karmada-io/karmada#705]
The PR #703 has given a new proposal about automatically propagate relevant resources. Here is the TODO List about the proposal.(Now only support deployment)

- [x] API update:  (#704)
 `ResourceBinding` API changes to add `PropagateDeps` and `RequiredBy`.
`PropagationPolicy` API changes to add `PropagateDeps`.
- [x] add dependenciesInterpreter 
- [x] add dependencies distributor to  automatically propagate dependent resources, i.e, generate attached resource bindings for dependent resources. Support secret and configmap in the first stage.
- [ ] add UT test

**Comment by RainbowMango** [comment]
@mrlihanbo 
Please confirm the split tasks are still valid.
