### ISSUE TITLE
work will not be deleted under some circumstances

### ISSUE THREAD

**Issue by Garrybest** [karmada-io/karmada#708]
**What happened**:
The `works.work.karmada.io` will not be deleted after we delete workload during the controller restarted. That is to say, if the controller has something wrong, e.g. evicted or crashed, if the workload is deleted by users during this period, the work would never be deleted.

**What you expected to happen**:
The orphan `works.work.karmada.io` should be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Create 1 deployment and separate it to 3 clusters.
```bash
# kubectl create -f plc.yaml 
propagationpolicy.policy.karmada.io/weighted created
# kubectl create -f dp.yaml  
deployment.apps/nginx created
# kubectl get deployments.apps 
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   10/10   10           10          14s
```

Stop the controller.
```bash
# kubectl --context karmada-host scale --replicas=0 -n karmada-system deployment karmada-controller-manager 
deployment.apps/karmada-controller-manager scaled
```

Delete the workload.
```bash
# kubectl delete deployments.apps nginx 
deployment.apps "nginx" deleted
```

Restart the controller.
```bash
# kubectl --context karmada-host scale --replicas=1 -n karmada-system deployment karmada-controller-manager 
deployment.apps/karmada-controller-manager scaled
```

Get the work. They should not exist but still are still in karamda. They will not be deleted any more unless we delete them manually.
```bash
# kubectl get works.work.karmada.io -A                                                                      
NAMESPACE            NAME               AGE
karmada-es-member1   nginx-687f7fb96f   92s
karmada-es-member2   nginx-687f7fb96f   92s
karmada-es-member3   nginx-687f7fb96f   92s
```

Meanwhile, the `resourcebindings.work.karmada.io` does not exist.
```bash
# kubectl get resourcebindings.work.karmada.io 
No resources found in default namespace.
```

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by Garrybest** [comment]
May be associated with #425.

**Comment by RainbowMango** [comment]
> May be associated with #425.

Yes, I think so. Any ideas about the solution?

**Comment by Garrybest** [comment]
What about scaning all `works.work.karmada.io` and removing the orphan ones when the `karmada-controller-manager` starts?

**Comment by mrlihanbo** [comment]
> What about scaning all `works.work.karmada.io` and removing the orphan ones when the `karmada-controller-manager` starts?

What about adding finalizers when binding created and remove finalizers when deleted?

**Comment by Garrybest** [comment]
> What about adding finalizers when binding created and remove finalizers when deleted?

I agree, sounds elegant. @mrlihanbo

**Comment by RainbowMango** [comment]
> What about adding finalizers when binding created and remove finalizers when deleted?

Do you mean to add a finalizer to ResourceBinding, and 'resource binding controller' takes the responsibility to remove it after all work be deleted?

**Comment by shuaizi** [comment]
be interested，could you explain it in detail？ @mrlihanbo

**Comment by shuaizi** [comment]
i think just add an ownerReferences  when building works  will also take effect，

for example，

```
apiVersion: work.karmada.io/v1alpha1
kind: Work
metadata:
  creationTimestamp: "2021-09-15T06:54:07Z"
  finalizers:
  - karmada.io/execution-controller
  generation: 1
  labels:
    resourcebinding.karmada.io/name: nginx-deployment
    resourcebinding.karmada.io/namespace: default
  name: nginx-687f7fb96f
  namespace: karmada-es-karmada-host
  ownerReferences:
  - apiVersion: work.karmada.io/v1alpha1
    controller: true
    kind: ResourceBinding
    name: nginx-deployment
    uid: d2fb60e4-53e5-4ec9-97c6-1b1d18ae29df
  resourceVersion: "340697"
  selfLink: /apis/work.karmada.io/v1alpha1/namespaces/karmada-es-karmada-host/works/nginx-687f7fb96f
  uid: 558ca910-9c29-4d00-b88b-c42fecf7e7b2
```


for current version,  the ResourceBinding already has been configured the ownerReferences of the workloads，
so when user try to delete a workload ，k8s will deal with ResourceBinding and Work based on cascading deletion.
 
and the work also has a  finalizers，
```
finalizers:
  - karmada.io/execution-controller
```

execution-controller will just watch it， and deal with the workloads in member cluster(s),  so everything works as expected?

**Comment by shuaizi** [comment]
have a try   /assign  @shuaizi

**Comment by Garrybest** [comment]
Well, I don't think so. `OwnerReferences` cannot cross namespace. See #425. @shuaizi

**Comment by XiShanYongYe-Chang** [comment]
@shuaizi I think maybe you should add some logic to find orphan work and delete it, because now can gc resource across namespace, according to the #425 .

**Comment by shuaizi** [comment]
got it
