### ISSUE TITLE
Introduce `version` command to karmada components

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#716]
**What would you like to be added**:
Add `version` command to following components:
- [x] karmada-controller-manager (#717)
- [ ] karmada-scheduler
- [ ] karmada-webhook
- [ ] karmada-agent
- [ ] karmada-scheduler-estimator

@algebra2k has gave a good example for `karmadactl` at #285.

**Why is this needed**:

**Comment by lonelyCZ** [comment]
Do I try to take this issue?

**Comment by RainbowMango** [comment]
@lonelyCZ  sure thing, go ahead.
