### ISSUE TITLE
Quickstart optimization

### ISSUE THREAD

**Issue by lfbear** [karmada-io/karmada#720]
**What would you like to be added**:

Add a NEW script to start an environment for Quickstart. It contains all infrastructure, control plane, and some samples for test. And organize the flow of installation and integrate scripts.

**Why is this needed**:

Reduce the difficulty of quickstart

**Comment by lfbear** [comment]
Flows of the installation:
1. Basic preparation and system adaptation
2. Create K8s clusters(host and member clusters) by kind (remote installation skip)
3. Build docker images and load to kind-cluster
4. Install control plane to host-cluster
    - Install RBAC, and generate certificate and key
    - Install Karmada components in host-cluster (etcd, api-server, controller-manager, webhook)
    - Install CRD in Karmada cluster
5.  Install Karmada-agent (optional)
6. Join member cluster to Karmada

**Comment by RainbowMango** [comment]
Are you going to add a `new` script?

**Comment by lfbear** [comment]
> Are you going to add a `new` script?

I hope to add a new one or use `hack/karmada-bootstrap.sh`, and this script used for both CI and quickstart

**Comment by RainbowMango** [comment]
Can we rename `hack/karmada-bootstrap.sh` to `hack/local-up-karmada.sh`?

**Comment by lfbear** [comment]
Or should we collect usage scenarios for installation?
I think it can be one script for CI and quickstart, another for the production installation.
And I really feel `karmada-bootstrap.sh` is better than `local-up-karmada.sh`, the former is more conspicuous
