### ISSUE TITLE
'make verify' gets many checking-imports error, dose ci works fine?

### ISSUE THREAD

**Issue by shuaizi** [karmada-io/karmada#724]
**What happened**:

checkout master code (commit: 0c8a0201603b8059435b1d2768340f3306307428) 
and just execute `make verify`, it output lots of  errors  like "ERROR wrong alias for import ..."
 
`$ make verify
hack/verify-all.sh
Generating with deepcopy-gen
Generating with register-gen
Generating with client-gen
Generating with lister-gen
Generating with informer-gen
diffing hack/../hack/../pkg against freshly generated codegen
hack/../hack/../pkg up to date.
Generating with controller-gen
diffing hack/../hack/../charts/_crds/bases against freshly generated files
hack/../hack/../charts/_crds/bases up to date.
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
Congratulations!  All Go source files have passed staticcheck.
go get: installing executables with 'go get' in module mode is deprecated.
	To adjust and download dependencies of the current module, use 'go get -d'.
	To install using requirements of the current module, use 'go install'.
	To install ignoring the current module, use 'go install' with a version,
	like 'go install example.com/cmd@latest'.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
checking-imports:
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/cmd/agent/app/agent.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/apis/cluster/v1alpha1/types.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/apis/policy/v1alpha1/propagation_types.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/apis/work/v1alpha1/binding_types.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/clusterdiscovery/clusterapi/clusterapi.go
ERROR wrong alias for import "k8s.io/apimachinery/pkg/api/errors" should be apierrors in file /root/workspaces/karmada/pkg/controllers/binding/binding_controller.go
ERROR wrong alias for import "k8s.io/apimachinery/pkg/api/errors" should be apierrors in file /root/workspaces/karmada/pkg/controllers/binding/cluster_resource_binding_controller.go
ERROR wrong alias for import "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1" should be policyv1alpha1 in file /root/workspaces/karmada/pkg/controllers/binding/common.go
ERROR wrong alias for import "k8s.io/api/coordination/v1" should be coordinationv1 in file /root/workspaces/karmada/pkg/controllers/cluster/cluster_controller.go
ERROR wrong alias for import "k8s.io/api/core/v1" should be v1 in file /root/workspaces/karmada/pkg/controllers/cluster/cluster_controller.go
ERROR wrong alias for import "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1" should be clusterv1alpha1 in file /root/workspaces/karmada/pkg/controllers/cluster/cluster_controller.go
ERROR wrong alias for import "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1" should be clusterv1alpha1 in file /root/workspaces/karmada/pkg/controllers/execution/execution_controller.go
ERROR wrong alias for import "k8s.io/apimachinery/pkg/api/errors" should be apierrors in file /root/workspaces/karmada/pkg/controllers/hpa/hpa_controller.go

... 

!!! Please see hack/.import-aliases for the preferred aliases for imports.
`

**What you expected to happen**:

`make verify` just return success

**How to reproduce it (as minimally and precisely as possible)**:

checkout master code (now head commit is: 0c8a0201603b8059435b1d2768340f3306307428) 
and just execute `make verify`

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by shuaizi** [comment]
`make test` also output lots of  "no test files"，need to Supplement test cases later ？

**Comment by RainbowMango** [comment]
Thanks for pointing it out. Yes, we've discussed it at [here](https://github.com/karmada-io/karmada/issues/692#issuecomment-916775683) and @ESonata will fix it.

We will add the verification to the CI after we fixed all the invalid aliases.

**Comment by RainbowMango** [comment]
> `make test` also output lots of "no test files"，need to Supplement test cases later ？

I'd say we are always welcome to contribute. :)

**Comment by RainbowMango** [comment]
/remove-kind bug
/close
Since the verification has onboard now.
