### ISSUE TITLE
Use cluster lister instead of map to implement scheduler cache

### ISSUE THREAD

**Issue by dddddai** [karmada-io/karmada#727]
While reading karmada source, I found that the event handler below maintains a map to implement scheduler cache, which contains all member clusters

https://github.com/karmada-io/karmada/blob/08ddb58cfd276c1c30d4a740558cbdeb4a4a5f18/pkg/scheduler/scheduler.go#L142-L148
https://github.com/karmada-io/karmada/blob/08ddb58cfd276c1c30d4a740558cbdeb4a4a5f18/pkg/scheduler/cache/cache.go#L11-L22

Actually there is no need to use an extra map for caching because the cluster lister (indexer of `memclusterInformer`) has already preserved all member clusters.

**What would you like to be added**:
Remove unnecessary handler and use cluster lister instead of map to implement scheduler cache.

Besides, IMHO `AddCluster`,`UpdateCluster` and `DeleteCluster` are not necessary any more because the indexer would synchronize automatically, shall we delete these methods in `Cache` interface?

**Why is this needed**:
Remove unnecessary handler and improve performance

**Comment by Garrybest** [comment]
Half Agree. The cluster lister may take the replacement. But we still need event handler in #721.

**Comment by dddddai** [comment]
@Garrybest, thanks for your reply, yes the event handler should be preserved for extension, I'm willing to submit a PR to fix this.
