### ISSUE TITLE
Add protobuf verification script

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#729]
**What would you like to be added**:
We've added `hack/generate-proto.sh` at #638, now we need a script to verify if the generated `protobuf` is always up to date.

So, propose following changes:
- rename `hack/generate-proto.sh` to `hack/update-estimator-protobuf.sh`
- add `hack/verify-estimator-protobuf.sh`

**Why is this needed**:
Refer to https://github.com/karmada-io/karmada/pull/725#discussion_r708235428.

**Comment by RainbowMango** [comment]
cc @Garrybest How do you think?

**Comment by Garrybest** [comment]
No problem. @RainbowMango
