### ISSUE TITLE
 Karmada scheduler does not perform failover

### ISSUE THREAD

**Issue by zghyy** [karmada-io/karmada#744]
**What happened**:
I am trying out some of the functions supported by karmada. So I created three clusters, one of them (cluster127) has karmada deployed on it, and the other two (cluster128, cluster129) are member clusters.
The distribution of resources, differentiated configuration and other functions can all be done, but during the test failure migration, I found that it does not seem to be able to automatically migrate.

The test content:
I created the nginx resource object as a distributed resource, created a PropagationPolicy to select two member clusters (cluster128, cluster129), and created a ReplicaSchedulePolicy to control the total number of resources to 15, and the weight assigned to cluster128:cluster129 = 4:1 .
After configuring this information, 12 Pods are allocated on cluster128, and 3 Pods are allocated on cluster129

**What you expected to happen**:
I directly delete the karmada-cluster namespace in cluster129 to exit the connection between the cluster and the control interface or restart cluster129 directly. These are all examples to simulate an error in the 129 cluster. Since the failover flag of karmada-schedule is true, it means that failover is enabled. The normal situation should be that the scheduler will find that cluster129 has failed, and will migrate the pod on 129 to other clusters, but what I thought did not happen

I also checked the log of the scheduler on the karmada control plane. The above mentioned `Found cluster(cluster129) failure and failover flag is true`, but the Pod migration that I wanted did not happen.

**How to reproduce it (as minimally and precisely as possible)**:
The following three paragraphs are the three yaml configuration files I mentioned above
nginx-deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: default
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 7
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image:  nginx:1.17
```
nginx-propagation.yaml
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
    - apiVersion: v1
      kind: Service
      name: nIn the following paragraph, I intercepted some scheduler logsginx-service
      namespace: default
  placement:
    clusterAffinity:
      clusterNames:
        - cluster128
        - cluster129
```
nginx-replicaSchedule.yaml
```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: ReplicaSchedulingPolicy
metadata:
  name: nginx-rsp
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
  totalReplicas: 15
  preferences:
    staticWeightList:
      - targetCluster:
          clusterNames: [cluster128]
        weight: 4
      - targetCluster:
          clusterNames: [cluster129]
        weight: 1
```
After deploying the above, I went to cluster 129 to simulate a failure, that is, disconnected from the control plane in an abnormal way.
Although the way to disconnect from the control plane is not formal, it is also to simulate sudden problems

In the following paragraph, I intercepted some scheduler logs
```bash
I0918 09:08:59.953555       1 scheduler.go:496] update event for cluster cluster129
I0918 09:08:59.953620       1 scheduler.go:501] Found cluster(cluster129) failure and failover flag is true
I0918 09:08:59.953644       1 scheduler.go:534] Start traveling all ResourceBindings
I0918 09:08:59.953667       1 scheduler.go:545] Add expired ResourceBinding in queue successfully
I0918 09:08:59.953679       1 scheduler.go:554] Start traveling all ClusterResourceBindings
I0918 09:08:59.953783       1 scheduler.go:593] begin rescheduling ResourceBinding default nginx-deployment
I0918 09:08:59.954085       1 generic_scheduler.go:612] Reserved bindingClusters : [cluster128]
I0918 09:08:59.954130       1 generic_scheduler.go:613] Candidate bindingClusters: []
W0918 09:08:59.954168       1 generic_scheduler.go:620] ignore reschedule binding as insufficient available cluster
I0918 09:08:59.954203       1 scheduler.go:601] end rescheduling ResourceBinding default: nginx-deployment
I0918 09:08:59.954227       1 scheduler.go:368] Reschedule binding(default/nginx-deployment) as cluster failure
I0918 09:10:51.301235       1 reflector.go:530] pkg/generated/informers/externalversions/factory.go:103: Watch close - *v1alpha1.Cluster total 4 items received
I0918 09:12:42.058727       1 reflector.go:530] pkg/generated/informers/externalversions/factory.go:103: Watch close - *v1alpha1.ResourceBinding total 20 items received
I0918 09:13:05.456482       1 scheduler.go:382] begin scheduling ResourceBinding default/nginx-deployment
I0918 09:13:05.456746       1 generic_scheduler.go:69] feasible clusters found: [0xc0007b6000]
I0918 09:13:05.456798       1 generic_scheduler.go:75] feasible clusters scores: [{cluster128 0}]
I0918 09:13:05.460017       1 scheduler.go:424] ResourceBinding default/nginx-deployment scheduled to clusters [{cluster128 0}]
I0918 09:13:05.486314       1 scheduler.go:410] end scheduling ResourceBinding default/nginx-deployment: <nil>
I0918 09:13:05.486393       1 scheduler.go:358] Start scheduling binding(default/nginx-deployment)
I0918 09:13:05.489403       1 scheduler.go:371] Don't need to schedule binding(default/nginx-deployment)
I0918 09:13:05.546629       1 scheduler.go:371] Don't need to schedule binding(default/nginx-deployment)
I0918 09:13:05.578087       1 scheduler.go:371] Don't need to schedule binding(default/nginx-deployment)

```

**Anything else we need to know?**:
I don't know if this is a bug, or I'm using the wrong way, I hope to get an answer

**Environment**:
- Karmada version:v 0.8.0 release
- Others:

**Comment by XiShanYongYe-Chang** [comment]
Hi @zghyy ,
`ReplicaSchedulingPolicy` will be discarded, the corresponding functions have been moved to `PropagationPolicy.PropagationSpec.ReplicaScheduling`, you can try again using the following method:

```yaml
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx
      namespace: default
    - apiVersion: v1
      kind: Service
      name: nIn the following paragraph, I intercepted some scheduler logsginx-service
      namespace: default
  placement:
    clusterAffinity:
      clusterNames:
        - cluster128
        - cluster129
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference: 
        staticWeightList:
        - targetCluster:
             clusterNames: [cluster128]
          weight: 4
        - targetCluster:
            clusterNames: [cluster129]
          weight: 1
```

**Comment by RainbowMango** [comment]
Hi @zghyy
The precondition of  `fail-over` functionality is that the `karmada-scheduler` could select `successor` clusters without violating the schedule rules.

In the `nginx-propagation`(PropagationPolicy) above, you have declared the workload should deploy on `cluster128` and `cluster129`, and declared the weight for each cluster, so the scheduler can't do anything.

By the way, the `ReplicaSchedulingPolicy` will be deprecated soon, the functionality has been migrated to [ReplicaScheduling](https://github.com/karmada-io/karmada/blob/fd89085dac265d7c7fed1d8465538e7a37f60007/pkg/apis/policy/v1alpha1/propagation_types.go#L107)

[here](https://github.com/karmada-io/karmada/blob/master/test/e2e/failover_test.go) is the `E2E` test for fail-over testing, you may be interested in.

**Comment by zghyy** [comment]
> Hi @zghyy ,
> `ReplicaSchedulingPolicy` will be discarded, the corresponding functions have been moved to `PropagationPolicy.PropagationSpec.ReplicaScheduling`, you can try again using the following method:
> 
> ```yaml
> apiVersion: policy.karmada.io/v1alpha1
> kind: PropagationPolicy
> metadata:
>   name: nginx-propagation
>   namespace: default
> spec:
>   resourceSelectors:
>     - apiVersion: apps/v1
>       kind: Deployment
>       name: nginx
>       namespace: default
>     - apiVersion: v1
>       kind: Service
>       name: nIn the following paragraph, I intercepted some scheduler logsginx-service
>       namespace: default
>   placement:
>     clusterAffinity:
>       clusterNames:
>         - cluster128
>         - cluster129
>     replicaScheduling:
>       replicaSchedulingType: Divided
>       replicaDivisionPreference: Weighted
>       weightPreference: 
>         staticWeightList:
>         - targetCluster:
>              clusterNames: [cluster128]
>           weight: 4
>         - targetCluster:
>             clusterNames: [cluster129]
>           weight: 1
> ```

I used the same method you mentioned when I wanted to declare the weights of the two clusters, but it didn't work. I declared 10 copies in nginx-deployment.yaml, and finally I saw 10 copies on each cluster. Then I found ReplicaSchedulingPolicy, and it is valid.

Just now I used the yaml file you gave, but still failed to declare the weight to the cluster. 
(my kubernetes version is 1.17.2)

**Comment by zghyy** [comment]
> Hi @zghyy
> The precondition of `fail-over` functionality is that the `karmada-scheduler` could select `successor` clusters without violating the schedule rules.
> 
> In the `nginx-propagation`(PropagationPolicy) above, you have declared the workload should deploy on `cluster128` and `cluster129`, and declared the weight for each cluster, so the scheduler can't do anything.
> 
> By the way, the `ReplicaSchedulingPolicy` will be deprecated soon, the functionality has been migrated to [ReplicaScheduling](https://github.com/karmada-io/karmada/blob/fd89085dac265d7c7fed1d8465538e7a37f60007/pkg/apis/policy/v1alpha1/propagation_types.go#L107)
> 
> [here](https://github.com/karmada-io/karmada/blob/master/test/e2e/failover_test.go) is the `E2E` test for fail-over testing, you may be interested in.

Ok i will check it out

**Comment by jwcesign** [comment]
I recently attempted this and found that the migration will occur, thus resolving the issue.
If this issue recurs, please don't hesitate to create a new one.

/close
