### ISSUE TITLE
Is it necessary to add Dockerfile using Multi-Stage Docker Builds for karmada?

### ISSUE THREAD

**Issue by snowplayfire** [karmada-io/karmada#745]
**What would you like to be added**:

**Why is this needed**:

**Comment by RainbowMango** [comment]
Looking forward to hearing your use case. 

[multi-stage](https://docs.docker.com/develop/develop-images/multistage-build/).

**Comment by snowplayfire** [comment]
For example, karmada-controller-manager Dockerfile uses locally compiled binary, but our development environment may be different.

Multi-Stage Dockerfile which has `compile` and `build image` may be needed. 

If needed, I can provide it.
