### ISSUE TITLE
local-up-karmada.sh should be runable without root privilege

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#748]
**What would you like to be added**:
The [hack/local-up-karmada.sh](https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh) now requires root privilege. We should figure out why it requires `root` privilege and try to improve it.

**Why is this needed**:
Not all users using `root` even in developing environment.

**Comment by RainbowMango** [comment]
cc @kerthcet @lfbear

**Comment by lfbear** [comment]
I try to list somewhere required root privilege
- install kubectl
- create_signing_certkey and create_certkey (when 'CERT_DIR' can not be written)

**Comment by kerthcet** [comment]
I thought the [quick-start](https://github.com/karmada-io/karmada#quick-start) missed the join process of `member clusters`, I reviewed the [pr](https://github.com/karmada-io/karmada/pull/733/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L184-L187), some commands are discarded.   Am I right?

**Comment by lfbear** [comment]
Yes, It is indeed removed from README, for easy to get started, the code has been implemented [here](https://github.com/karmada-io/karmada/pull/733/files#diff-7d4ed29e538a24039777bfeb879e1113db1ba39d013476732c1f1b14639ab6eaR111-R114)

**Comment by kerthcet** [comment]
add a few comments:
1. docker daemon also required root privilege unless configed:
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=cluster%2Fimages%2Fkarmada-controller-manager%2FDockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=swr.ap-southeast-1.myhuaweicloud.com%2Fkarmada%2Fkarmada-controller-manager%3Alatest&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
```
[Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/), however we should also add a group with root privilege.

**Comment by kerthcet** [comment]
I have some advices. Whether we can introduce two installation modes:
1. root privilege: fresh install like what it is.
2. non-root privilege: only install karmada cluster without `kubectl`, `kind` and so on. But we'll add some validation whether it's ready or not.

I have worked it out with non-root privilege, no other suites installed at the same time, e.g. `kubectl`, `kind`, `git`, `golang`, they have been installed before already.

**Comment by kerthcet** [comment]
> I think it's ok for non-root privilege and root privilege installation modes.
> I have seen PR #761 Please note
> https://github.com/karmada-io/karmada/blob/master/hack/local-up-karmada.sh#L49, without installing `kubectl`, do we need to check the version of `kubectl` in case the following program is abnormal

good idea, if my suggestion is accepted, I'll work on this pr then. thanks.
