### ISSUE TITLE
ResourceBinding aggregated status is not updated after unjoinning a target cluster

### ISSUE THREAD

**Issue by dddddai** [karmada-io/karmada#768]
**What happened**:
ResourceBinding aggregated status is not updated after unjoinning a target cluster

**What you expected to happen**:
ResourceBinding aggregated status(along with workload status) should be updated after unjoinning a target cluster

**How to reproduce it (as minimally and precisely as possible)**:
1.Set up environment
```sh
root@myserver:~/karmada# hack/local-up-karmada.sh

root@myserver:~/karmada# hack/create-cluster.sh member1 $HOME/.kube/karmada.config

root@myserver:~/karmada# kubectl config use-context karmada-apiserver

root@myserver:~/karmada# karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config

root@myserver:~/karmada# kubectl apply -f samples/nginx

root@myserver:~/karmada# kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           16m
```

2.Unjoin member1
```sh
root@myserver:~/karmada# karmadactl unjoin member1

root@myserver:~/karmada# kubectl get clusters
No resources found
```

3.Check the ResourceBinding aggregated status and Deployment status
```sh
root@myserver:~/karmada# kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           16m
```
Both ResourceBinding aggregated status and Deployment status show there is still one ready pod.

**Anything else we need to know?**:
Turns out ResourceBindingController would always fail to `ensureWork` and requeue the request since the target cluster has been removed, which makes itself has no chance to aggregate status.

Related snippet:
https://github.com/karmada-io/karmada/blob/c3cf3a3053baacd2512fd868a65a81d07c2c0c31/pkg/controllers/binding/binding_controller.go#L95-L102
Here is the karmada-controller-manager log.
```
E0926 09:09:13.420846       1 binding_controller.go:97] Failed to transform resourceBinding(default/nginx-deployment) to works. Error: Cluster.cluster.karmada.io "member1" not found.
E0926 09:11:57.314073       1 overridemanager.go:50] Failed to get member cluster: member1, error: Cluster.cluster.karmada.io "member1" not found
E0926 09:11:57.314168       1 common.go:78] Failed to apply overrides for Deployment/default/nginx, err is: Cluster.cluster.karmada.io "member1" not found
E0926 09:11:57.314186       1 binding_controller.go:97] Failed to transform resourceBinding(default/nginx-deployment) to works. Error: Cluster.cluster.karmada.io "member1" not found.
E0926 09:17:24.998822       1 overridemanager.go:50] Failed to get member cluster: member1, error: Cluster.cluster.karmada.io "member1" not found
E0926 09:17:24.998878       1 common.go:78] Failed to apply overrides for Deployment/default/nginx, err is: Cluster.cluster.karmada.io "member1" not found
```
**Environment**:
- Karmada version: v0.8.0
- Others:

**Comment by dddddai** [comment]
I suppose this could be a bug instead of an intention, isn't it? If so, I'm willing to fix this :)

**Comment by RainbowMango** [comment]
Yeah, I think it's a bug too. But any idea about how to fix it?

**Comment by dddddai** [comment]
> Yeah, I think it's a bug too. But any idea about how to fix it?

Please see https://github.com/dddddai/karmada/commit/b13b355ba62692a6e68458ccf3f26a8f0b5b4f39, ResourceBindingController should aggregate status no matter if ensured work or not, WDYT?
I have tested this patch and it works.

**Comment by XiShanYongYe-Chang** [comment]
Is it possible to put the `aggregate status` to  an independent controller?

**Comment by dddddai** [comment]
> Is it possible to put the `aggregate status` to an independent controller?

Agree, `aggregate status` should be separated from `ResourceBindingController`, like `ExecutionController` with `WorkStatusController` and `ClusterController` with `ClusterStatusController`

**Comment by RainbowMango** [comment]
/assign @dddddai 
As https://github.com/karmada-io/karmada/issues/768#issuecomment-927313417, and appreciate!
