### ISSUE TITLE
Question: why keep the vendor folder?

### ISSUE THREAD

**Issue by iawia002** [karmada-io/karmada#811]
**Please provide an in-depth description of the question you have**:

[Go modules](https://github.com/golang/go/wiki/Modules) already guaranteed that you will be able to build your packages deterministically by locking down the dependencies version into `go.sum`. So why do we still need to submit the vendor folder to the code base?

**What do you think about this question?**:

Maybe we can remove the vendor folder? Without submitting the vendor folder, it's more convenient for developers to submit/review code without caring about the vendor file changes. And our code base can be cleaner.

**Comment by RainbowMango** [comment]
> Do we have a need for the netless build? If not, I think all these extra operations are really unnecessary.

Yes, I think we should support the build without a network.
