### ISSUE TITLE
About networks

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#818]
**Please provide an in-depth description of the question you have**:
1.How realizes the loadbance of multiple clusters?
2.How to realize the flow control of multiple clusters in use overridepolicy?For example,how to control flow when overridepolicy is used to achieve grayscale publishing?
**What do you think about this question?**:
 \

**Environment**:
- Karmada version:0.9.0
- Kubernetes version:\
- Others:\

**Comment by RainbowMango** [comment]
/close 
in favor of [MultiClusterIngress feature](https://github.com/karmada-io/karmada/blob/master/docs/multi-cluster-ingress.md).
