### ISSUE TITLE
Feature: Propose 'FullyApplied' condition for RB/CRB

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#820]
**What would you like to be added**:
Propose a new condition `FullyApplied` for RB/CRB.

```diff
diff --git a/pkg/apis/work/v1alpha2/binding_types.go b/pkg/apis/work/v1alpha2/binding_types.go
index 10cd0bdf..c56d5a33 100644
--- a/pkg/apis/work/v1alpha2/binding_types.go
+++ b/pkg/apis/work/v1alpha2/binding_types.go
@@ -135,6 +135,13 @@ type AggregatedStatusItem struct {
        AppliedMessage string `json:"appliedMessage,omitempty"`
 }

+// Conditions definition
+const (
+       // FullyApplied represents the condition that the resource referencing by ResourceBinding or ClusterResourceBinding
+       // has been applied to all scheduled clusters.
+       FullyApplied string = "FullyApplied"
+)
+
 // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

 // ResourceBindingList contains a list of ResourceBinding.

```
**Why is this needed**:
Currently, we have [Applied](https://github.com/karmada-io/karmada/blob/cceed5c9f81d2643f65ef0452c1b34b17cdcecee/pkg/apis/work/v1alpha2/binding_types.go#L130) field which represents if the resource is applied to a `single` cluster. But the RB/CRB lacks an overall status/conditions to represent if the resource is applied to `all of the scheduled clusters`. 

@pigletfly @lfbear 
The condition will be used by GitOpts utilities (like ArgoCD) to observe healthy status.

**Comment by lonelyCZ** [comment]
Hi, @RainbowMango 
Could This field  be set true if `Applied` of all aggregatedStatusItems are true?

**Comment by RainbowMango** [comment]
> Hi, @RainbowMango Could This field be set true if `Applied` of all aggregatedStatusItems are true?

This is one of the condition, another one is `len(spec.Clusters) == len(status.aggregatedStatus)`.

**Comment by RainbowMango** [comment]
/assign @lonelyCZ 
Thanks and go for it.
