### ISSUE TITLE
Feature: Propose a Scheduled condition for RB/CRB

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#821]
**What would you like to be added**:
Proposing a condition `Scheduled` for RB/CRB.

```diff
diff --git a/pkg/apis/work/v1alpha2/binding_types.go b/pkg/apis/work/v1alpha2/binding_types.go
index 10cd0bdf..ca292ab4 100644
--- a/pkg/apis/work/v1alpha2/binding_types.go
+++ b/pkg/apis/work/v1alpha2/binding_types.go
@@ -135,6 +135,12 @@ type AggregatedStatusItem struct {
        AppliedMessage string `json:"appliedMessage,omitempty"`
 }

+// Conditions definition
+const (
+       // Scheduled represents the condition that the ResourceBinding or ClusterResourceBinding has been scheduled.
+       Scheduled string = "Scheduled"
+)
+
 // +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

 // ResourceBindingList contains a list of ResourceBinding.

```

**Why is this needed**:
After `karmada-scheduler` finishes the schedule, there is no status update, the controller has to `guess` if the scheduling process is done by 
https://github.com/karmada-io/karmada/blob/c3cf3a3053baacd2512fd868a65a81d07c2c0c31/pkg/controllers/binding/binding_controller.go#L62-L68.

In some situations, as describes in [this discussion](https://github.com/karmada-io/karmada/issues/768#issuecomment-943319617), it will block the controller reconciling.

**Comment by RainbowMango** [comment]
> So the scheduled condition is set to True when the binding is scheduled by scheduler successfully, I'm wondering is there a case that it should be set from True to False?

Good question, my answer is `no`. 

> Do you mean scheduler should clean up the removed cluster from binding but not set the scheduled condition to False?

This proposal only focuses on the new condition, with no context of how to deal with the scenario ` cluster unjoined`. 
Yes, it might be used by next step(deal with the `cluster unjoined`)

**Comment by dddddai** [comment]
> my answer is no.

Thanks for your reply, got it, I will do this job
/assign
