### ISSUE TITLE
Reschedule bindings on cluster change

### ISSUE THREAD

**Issue by dddddai** [karmada-io/karmada#829]
**What happened**:
Unjoined clusters still remain in `binding.spec.clusters`

**What you expected to happen**:
Unjoined clusters should be deleted from `binding.spec.clusters`

**How to reproduce it (as minimally and precisely as possible)**:
1.Set up environment(script v0.8)
```sh
root@myserver:~/karmada# hack/local-up-karmada.sh

root@myserver:~/karmada# hack/create-cluster.sh member1 $HOME/.kube/karmada.config

root@myserver:~/karmada# kubectl config use-context karmada-apiserver

root@myserver:~/karmada# karmadactl join member1 --cluster-kubeconfig=$HOME/.kube/karmada.config

root@myserver:~/karmada# kubectl apply -f samples/nginx

root@myserver:~/karmada# kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           47h
```

2.Unjoin member1
```sh
root@myserver:~/karmada# karmadactl unjoin member1

root@myserver:~/karmada# kubectl get clusters
No resources found
```

3.Check `binding.spec.clusters`
```sh
root@myserver:~/karmada# kubectl describe rb
......
Spec:
  Clusters:
    Name:  member1
......
```

**Anything else we need to know?**:
Is it an expected behavior? If not, who is supposed to take the responsibility to delete unjoined clusters from binding? Scheduler or other controllers (like cluster controller)?

**Environment**:
- Karmada version:v0.8.0
- Others:

**Comment by XiShanYongYe-Chang** [comment]
> I have another question: does the scheduler perform `Failover` after **unjoining a target cluster**? I don't know cuz I have not practiced this

No.

**Comment by XiShanYongYe-Chang** [comment]
When there have cluster delete event, a rescheduling should maybe need to triggere.

How do @RainbowMango think?

**Comment by dddddai** [comment]
> Agree. But no idea how to solve that issue now.

How about removing applied placement annotation of binding on cluster add/delete? It will make the scheduler reschedule the binding as `ReconcileSchedule`
https://github.com/karmada-io/karmada/blob/8e1e16e95081d7431852c6a46ea372ff79a50b5e/pkg/scheduler/scheduler.go#L824-L828

**Comment by mrlihanbo** [comment]
Looking forward to seeing the progress of this issue

**Comment by RainbowMango** [comment]
@mrlihanbo The #967 is waiting for your review.

**Comment by mrlihanbo** [comment]
> @mrlihanbo The #967 is waiting for your review.

I will review the pr now

**Comment by dddddai** [comment]
> Looking forward to seeing the progress of this issue

Hi @mrlihanbo, before implementing this we have to answer the 4 questions above

**Comment by dddddai** [comment]
Hello @RainbowMango, any ideas about [these quetions](https://github.com/karmada-io/karmada/issues/829#issuecomment-951926061)?

**Comment by RainbowMango** [comment]
> Shall we reschedule bindings when cluster field/label changed? (because the updated cluster might (not) fit the propagation policy)

I think we should take this scenario very carefully, it might bring drastic changes. Take Kubernetes as an example, after a pod has been scheduled to a node it will not get re-scheduled even in case of the node label change.

**Comment by RainbowMango** [comment]
> Should FailoverSchedule work when unjoining a cluster?

I think we should re-schedule the workload after one of the bonded clusters is unjoined. It doesn't have to be `FailoverSchedule`(not sure).

**Comment by RainbowMango** [comment]
> What does SpreadConstraint.MinGroups mean? Does it mean we should not propagate the resource unless group count >= MinGroups?

Yes, you are right. The `SpreadConstraint.MinGroups` restrict minimum cluster groups, if the scheduler can not find enough cluster groups, the schedule should trigger failure.

> If yes, shall we delete all binding.spec.clusters when unjoining a cluster which causes
group count < MinGroups?

I don't think so, just like [the answer above](https://github.com/karmada-io/karmada/issues/829#issuecomment-982226082), it's too dangerous, at least for now.

**Comment by dddddai** [comment]
I see, so I guess we should reschedule workloads only when cluster joined/unjoined, right?

**Comment by RainbowMango** [comment]
Let's focus on the scenario of cluster-unjoin for now. The workload should be re-scheduled after one of the bound clusters is unjoined. If no more clusters fit the propagation policy, just remove the `unjoined` cluster from the binding object.

**Comment by mrlihanbo** [comment]
> ld be re-scheduled after one of the bound clusters is unjoined. If no more clusters fit the propagation policy, just remove the `unjoined` clu

There exist a scenario if workload should be re-scheduled after one of the bound clusters is unjoined:
- User specify cluster A, B, C in policy. 
- Only cluster A and B are joined when first  schedule, so the schedule result will be [A, B].
- Then, the cluster C is joined.
- if cluster A is not ready and trigger reschedule, the new schedule result will be [B, C]

we should make sure that the behavior is what we expected.

**Comment by mrlihanbo** [comment]
> I see, so I guess we should reschedule workloads only when cluster joined/unjoined, right?

@dddddai I took a glance at the `FailoverSchedule` func. Maybe we can do it in this func. Just a suggestion.

**Comment by dddddai** [comment]
> @dddddai I took a glance at the `FailoverSchedule` func. Maybe we can do it in this func. Just a suggestion.

Thanks for digging into it, that's exactly what I did in #1049, the behavior of `Reschedule` is the same as `FailoverSchedule`

**Comment by mrlihanbo** [comment]
> > @dddddai I took a glance at the `FailoverSchedule` func. Maybe we can do it in this func. Just a suggestion.
> 
> Thanks for digging into it, that's exactly what I did in #1049, the behavior of `Reschedule` is the same as `FailoverSchedule`

Good job, I will review the pr ASAP.

**Comment by huone1** [comment]
let me work it with you @dddddai

**Comment by dddddai** [comment]
@huone1 Thank you!

**Comment by duanmengkk** [comment]
Just a the issue mentioned #1644 ,On the scenario of a new cluster join,should the RB be reschedule? @dddddai

**Comment by dddddai** [comment]
I was thinking so. Would ask @RainbowMango for comments.

**Comment by duanmengkk** [comment]
I think it's similar to kubernetes, just as deschedule(https://github.com/kubernetes-sigs/descheduler) said , the descheduler should   responsible for handle rescheduling of cluster status changing,cluster join and cluster unjoin.
