### ISSUE TITLE
Adopt conversion-gen to generate conversion function

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#846]
**What would you like to be added**:
Adopt [conversion-gen](https://github.com/kubernetes/code-generator/tree/master/cmd/conversion-gen) to generate functions that convert between different API versions.

**Why is this needed**:
Currently, the `ResourceBinding` and `ClusterResourceBinding` API serve `v1alpha1` and `v1alpha2`, and implemented the conversion functions([v1alpha1 conversion](https://github.com/karmada-io/karmada/blob/master/pkg/apis/work/v1alpha1/binding_types_conversion.go), [v1alpha2 conversion](https://github.com/karmada-io/karmada/blob/master/pkg/apis/work/v1alpha2/binding_types_conversion.go)) by manual.

It'll much helpful if we can generate the conversion functions automatically.
/help

**Comment by iawia002** [comment]
> Currently, the `ResourceBinding` and `ClusterResourceBinding` API serve `v1alpha1` and `v1alpha2`, and implemented the conversion functions([v1alpha1 conversion](https://github.com/karmada-io/karmada/blob/master/pkg/apis/work/v1alpha1/binding_types_conversion.go), [v1alpha2 conversion](https://github.com/karmada-io/karmada/blob/master/pkg/apis/work/v1alpha2/binding_types_conversion.go)) by manual.

In the discussion of #773, I misunderstood something. If you want to generate this kind of thing, conversion-gen doesn’t seem to be able to do it. conversion-gen is a tool for auto-generating functions that convert between internal and external types, not two versions of an API, I'm not so familiar with conversion-gen, how does conversion-gen know how to convert two versions of an API?

**Comment by iawia002** [comment]
> 	// WARNING: in.ReplicaResourceRequirements requires manual conversion: does not exist in peer-type
	// WARNING: in.Replicas requires manual conversion: does not exist in peer-type

How do we add those manual conversions, if we can configure that, maybe it works.

**Comment by Akash-Singh04** [comment]
Hey is this issue still open?If so,  I would like to work on it

**Comment by RainbowMango** [comment]
This is probably not an ideal task for a new contributor. Actually this task has been delayed for a long time, and I think we'd better close it for now and re-open it once there is an evidence we really need it.
/close

Thank you @Akash-Singh04, all the same.
