### ISSUE TITLE
Submariner not work follow the current quick start document

### ISSUE THREAD

**Issue by vincent-pli** [karmada-io/karmada#847]
I follow the quick start document for `Submariner`: https://github.com/karmada-io/karmada/blob/master/docs/working-with-submariner.md

I found it not work, root cause is there is no `Gateway Engine` installed: node with label `submariner.io/gateway=true` will be treat as where `Gateway Engine` should be installed, but there is no such label in `karmada` env prepared.

am I missing something?

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by vincent-pli** [comment]
Actually I adopt `hack/local-up-karmada.sh` to build env for `karmada`.
in https://submariner.io/getting-started/quickstart/kind/,  i guess they hide the details(I mean label the node) in the `make clusters`, but I can not make sure... @XiShanYongYe-Chang

**Comment by vincent-pli** [comment]
Yes, I noticed that, but seems `Summariner` exchange cross-cluster request by `Gateway Engine`. @XiShanYongYe-Chang 
The process should be:
```
1. Curl service-a.default.svc.clusterset.local
2. CoreDNS forward the request to Lighthouse DNS server
3. Lighthouse DNS server resolve it to IP based in ServiceImport(CRD, treat it as a standard SVC) and related EnepointSlices
4. Then the request target to the IP will be route to Gateway Engine based in router rules created by Rroute Agent
5. Gateway Engine will send the request to another Gateway Engine in the target cluster
6. To the target SVC
7. Done
```

**Comment by XiShanYongYe-Chang** [comment]
Thank you for your analysis.

We use submariner to connect the network between clusters, then use **MCS** feature to discovery Multiple Clusters Service, now clusters created by hack/local-up-karmada.sh can make it. So we can use new clusters created by hack/create-cluster.sh for testing.

Perhaps we can use the script to create karmada without creating a member cluster, and then add the new cluster.

**Comment by XiShanYongYe-Chang** [comment]
/close

Turn this off first, and if you have any questions,  we can reopen it.
