### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#883]
**Please provide an in-depth description of the question you have**:
After deploying Karmada in an offline environment yestorday,I had a fer questions:
1.  When deployed to an existing K8s cluster, can Karmada share a etcd with K8s,why deploy Karmada's own  etcd?
2.  After join the cluster self as a member,the propragation policy cannot be deployt to the cluster

**Environment**:
- Karmada version:0.9.0
- Kubernetes version:1.21.2
- Others:

**Comment by RainbowMango** [comment]
/close
Seems the original question has been answered. 
About the difference between Rancher and Kubersphere, you can refer to #289 and discuss it there. Thanks.
