### ISSUE TITLE
Provide some example for `karmadactl get`

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#896]
**What would you like to be added**:
There is only  a template that is not clear. What resource we can get?
```
[root@master67 karmada]# karmadactl get -h
Display one or many resources

Usage:
  karmadactl get [NAME | -l label | -n namespace]  [flags]

Flags:
```

**Why is this needed**:
There aren't cluster when I execute `karmadactl get cluster`. Is it a bug or not supported?
```
[root@master67 karmada]# kubectl get cluster
NAME       VERSION   MODE   READY   AGE
member68   v1.19.1   Push   True    3d5h
[root@master67 karmada]# karmadactl get cluster
[cluster] from server (NotFound)
```

**Comment by learner0810** [comment]
@lonelyCZ not supported
![企业微信截图_da74e77f-3e4f-4fdd-bec1-1f7d68e857b9](https://user-images.githubusercontent.com/39400425/139813475-504a4d70-e74d-4598-870f-cb9c7506cb4e.png)

**Comment by lonelyCZ** [comment]
@learner0810 ,Thank you! 
`karmadactl get` has been added in master head, but there aren't clear usage examples.

**Comment by learner0810** [comment]
Yes, master has been added. I saw the 0.9 version @lonelyCZ
