### ISSUE TITLE
Old schedule result will be retained when new ReconcileSchedule  fails

### ISSUE THREAD

**Issue by qianjun1993** [karmada-io/karmada#900]
**What happened**:
When users change the  associated policy workload， Karmada-scheduler will try a ReconcileSchedule  to reschedule the workload. It shares the same logic with first Scheduler。 When the new schedule fails, the old schedule result will be retained in the resourceBinding .

 For example, a deployment  is assigned to cluster A with 5 replicas. user wants to change it to cluster B , so he changes the policy. Cluster B has no enough resource, so the new schedule fails。 At that time,  the result of cluster A still exist in  resourceBinding, so pods in cluster A will not be deleted . 

**What you expected to happen**:
After the ReconcileSchedule or ResourceExpandSchedule fails, the old schedule result should be cleaned  in the resourceBinding.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Others:

**Comment by BDXGD** [comment]
I would like to try it.

**Comment by qianjun1993** [comment]
A detailed solution may need more discussion. In fact, sometimes clean all the old schedule result is not suitable.

**Comment by BDXGD** [comment]
Yes, I guess feasible solutions include deleting Pod resources, or migrating a part of Pods to cluster B(in your example), or Karmada's default solution. 
But without the user's consent, no matter what kind of strategy is not suitable. 
IMO, it needs to interact with the users, let the user choose which strategy(add some parameters to the when using command line).

**Comment by BDXGD** [comment]
Yes, I guess feasible solutions include deleting Pod resources, or migrating a part of Pods to cluster B(in your example), or Karmada's default solution. 
But without the user's consent, no matter what kind of strategy is not suitable. 
IMO, it needs to interact with the users, let the users choose which strategy, or add some parameters to the command line when using it.

**Comment by XiShanYongYe-Chang** [comment]
Due to the long periods of inactivity, close it first. Please feel free to reopen it if you think it is necessary.
/close
