### ISSUE TITLE
skipped Event api does not take effect

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#906]
**What happened**:

When I set `--skipped-propagating-apis` to `karmada-controller-manager` such as:

```
- --skipped-propagating-apis=v1/Event
```

It dose not take effect. In `karmada-controller-manager` logs file, still have Event info with `detector`:

```
detector.go:721] Add object(events.k8s.io/v1, kind=Event, default/serviceimports.multicluster.x-k8s.io-customresourcedefinition.16b3b14e05fa7351) to waiting list, length of list is: 207
```
 
**What you expected to happen**:

The setting take effect.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version: **master branch**
- Others:

**Comment by dddddai** [comment]
The flag works fine in my environment, you specified **`v1/Event` but not `events.k8s.io/v1/Event`**

**Comment by XiShanYongYe-Chang** [comment]
Hi @dddddai , the log contains both `v1/Event` and `events.k8s.io/v1/Event`:

```log
I1102 09:41:59.395795       1 detector.go:202] Reconciling object: events.k8s.io/v1, kind=Event, karmadatest-gbc/hello-2h9-serviceexport.16b3b1526f3ffe0f
I1102 09:41:59.495415       1 detector.go:202] Reconciling object: v1, kind=Event, karmadatest-gbc/hello-2h9-serviceexport.16b3b1526f3ffe0f
```

**Comment by XiShanYongYe-Chang** [comment]
```
# kubectl  get events -n karmada-es-member1 nginx-687f7fb96f.16b3b640ae370302 -oyaml
apiVersion: v1
kind: Event
lastTimestamp: "2021-11-02T11:11:18Z"
message: Sync work (nginx-687f7fb96f) to cluster(member1) successful.
...
```

**Comment by XiShanYongYe-Chang** [comment]
I try with `--skipped-propagating-apis=events.k8s.io/v1/Event`, but it doesn't work on my side.

**Comment by dddddai** [comment]
That's flaky, there's no such log in my environment

> ```
> # kubectl  get events -n karmada-es-member1 nginx-687f7fb96f.16b3b640ae370302 -oyaml
> apiVersion: v1
> kind: Event
> lastTimestamp: "2021-11-02T11:11:18Z"
> message: Sync work (nginx-687f7fb96f) to cluster(member1) successful.
> ...
> ```

BTW, why is there a event in `karmada-es-member1`? 
Only works exist in this namespace, don't they? Please correct me if I'm wrong

**Comment by XiShanYongYe-Chang** [comment]
> why is there a event in `karmada-es-member1`?

Yeah, I create a deployment and propagate it to member clusters:

```
# kubectl  get work -A
NAMESPACE            NAME               AGE
karmada-es-member1   nginx-687f7fb96f   31m
karmada-es-member2   nginx-687f7fb96f   31m
```

**Comment by dddddai** [comment]
Do you clean up the deploy and propagation policy before adding the flag and recreate them after adding it?

**Comment by dddddai** [comment]
Let me fetch upstream and try again...

**Comment by pigletfly** [comment]
Event belongs to corev1.I use `- --skipped-propagating-apis=v1/Node,Event,Pod,PersistentVolume,ConfigMap,Endpoints,PersistentVolumeClaim;apiextensions.k8s.io/v1;events.k8s.io/v1beta1;discovery.k8s.io/v1beta1;rbac.authorization.k8s.io/v1` works for me

**Comment by pigletfly** [comment]
@XiShanYongYe-Chang can you try config above ?

**Comment by dddddai** [comment]
Oh, after I fetched upstream, this happens, I suspect it's because this [commit](https://github.com/karmada-io/karmada/commit/ecce805dc8d259294bb50264064d0f51f2fd7397#diff-a111978a679a9f03e49c67a43ecb913299d153e59ce48d2d30f5029f27ab601aL113) deletes `skippedResourceConfig.Parse` when initializing `karmada-controller-manager`, which makes the flag NOT work

[This change](https://github.com/karmada-io/karmada/commit/ecce805dc8d259294bb50264064d0f51f2fd7397#diff-7292b71e568298dfde17a9ca8290781b6b4ed66188df8faadbd3d66a0f56344bR9) doesn't make sense to me.

**Comment by RainbowMango** [comment]
Right, #881 omitted the `parse()` action, so all configurations made by `--skipped-propagating-apis` are ignored.
cc @learner0810

**Comment by learner0810** [comment]
@RainbowMango This issue has been fixed. @XiShanYongYe-Chang I'm really sorry for the trouble caused to you by this problem

**Comment by RainbowMango** [comment]
No worries, I didn't notice it as well.

**Comment by XiShanYongYe-Chang** [comment]
> I'm really sorry for the trouble caused to you by this problem

It's okay, I just wanted to try this feature. :)
