### ISSUE TITLE
Look at the source code encountered doubts

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#915]
**Please provide an in-depth description of the question you have**:
These is  a namespace field in the ResourceSelector struct ,What does this field mean? I don't understand the nodes....  
![image](https://user-images.githubusercontent.com/31329928/140242921-97e2ddae-9c50-4d75-bf2b-6b49a12f2ee9.png)
What does 'target' mean? Is it 'namespace' of 'Deployment' or 'Namespace' of the candidate cluster?  
And what does 'parent' mean?  
I think it's a little confusing here....
@RainbowMango Can you help me explain it..Thank you very much.

**Comment by 2hangchen** [comment]
A couple of questions:
1. What if the resources in the candidate cluster cannot satisfy the Request during distribution?

**Comment by mrlihanbo** [comment]
1. It is the 'namespace' of 'Deployment' in karmada-apiserver.
2. `parent` means the the resource which refers to the `ResourceSelector`, which can be `propagationpolicy`, `clusterpropagationpolicy`, `overridepolicy`, `clusteroverridepolicy`.    
for example, if you create a `propagationpolicy` in `test` namespace, the detector will match resource in `test` namespace for the `propagationpolicy`.

**Comment by 2hangchen** [comment]
> 1. It is the 'namespace' of 'Deployment' in karmada-apiserver.
> 2. `parent` means the the resource which refers to the `ResourceSelector`, which can be `propagationpolicy`, `clusterpropagationpolicy`, `overridepolicy`, `clusteroverridepolicy`.
>    for example, if you create a `propagationpolicy` in `test` namespace, the detector will match resource in `test` namespace for the `propagationpolicy`.

I've verified it here,  it's true. Thx.
