### ISSUE TITLE
refactor ObjectWatcher interface

### ISSUE THREAD

**Issue by pigletfly** [karmada-io/karmada#921]
**What would you like to be added**:
refactor ObjectWatcher interface into
```
type ObjectWatcher interface {
	Create(clusterName string, desireObj *unstructured.Unstructured) error
	Update(clusterName string, desireObj, clusterObj *unstructured.Unstructured) error
	Delete(clusterName string, desireObj *unstructured.Unstructured) error
	NeedsUpdate(clusterName string, desiredObj, clusterObj *unstructured.Unstructured) (bool, error)
}
```
**Why is this needed**:

the ObjectWatcher interface now is 

https://github.com/karmada-io/karmada/blob/9f2835d3f29ef56c817963181e3ef1a3bbb1d003/pkg/util/objectwatcher/objectwatcher.go#L29-L34

there is a clusterv1alpha1.Cluster object, if cluster version changed,all reference should be changed as well.It's more convenient to just pass a string.

**Comment by RainbowMango** [comment]
ask @mrlihanbo for comment.

**Comment by mrlihanbo** [comment]
I pass a clusterv1alpha1.Cluster object because we need to construct a `dynamicClusterClient`. Maybe you need to refactor `ClientSetFunc`.

**Comment by pigletfly** [comment]
> I pass a clusterv1alpha1.Cluster object because we need to construct a `dynamicClusterClient`. Maybe you need to refactor `ClientSetFunc`.
 yes ClientSetFunc will be refactored as well.
```
NewClusterDynamicClientSet(clusterName string, client client.Client)
```
