### ISSUE TITLE
[GoodFirst] Skip Event api in detector

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/karmada#924]
**Task description**:

Generally, `Event` resources do not need to be propagated to member clusters. There are many related logs in `karmada-contoller` logs:

```log
I1102 09:41:59.395795       1 detector.go:202] Reconciling object: events.k8s.io/v1, kind=Event, karmadatest-gbc/hello-2h9-serviceexport.16b3b1526f3ffe0f
I1102 09:41:59.495415       1 detector.go:202] Reconciling object: v1, kind=Event, karmadatest-gbc/hello-2h9-serviceexport.16b3b1526f3ffe0f
```

So we can skip `Event` resources in detector.

**Solution**:

Modify file `artifacts/deploy/controller-manager.yaml` like this:

```diff
--- a/artifacts/deploy/controller-manager.yaml
+++ b/artifacts/deploy/controller-manager.yaml
@@ -28,6 +28,7 @@ spec:
             - --kubeconfig=/etc/kubeconfig
             - --bind-address=0.0.0.0
             - --cluster-status-update-frequency=10s
+            - --skipped-propagating-apis=events.k8s.io/v1/Event
             - --secure-port=10357
             - --v=4
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by dddddai** [comment]
I guess `v1/Event` should be skipped as well

`- --skipped-propagating-apis=v1/Event;events.k8s.io/v1/Event`

**Comment by RainbowMango** [comment]
The `Event` should be ignored by default, not by `--skipped-propagating-apis`.

**Comment by XiShanYongYe-Chang** [comment]
Turn it off for now, and come up with a definite solution I will reopen.

/close

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang @dddddai 
How about this:
```diff
diff --git a/pkg/util/apigroup.go b/pkg/util/apigroup.go
index c54a557d..c176a238 100644
--- a/pkg/util/apigroup.go
+++ b/pkg/util/apigroup.go
@@ -32,6 +32,9 @@ func NewSkippedResourceConfig() *SkippedResourceConfig {
        r.DisableGroup(clusterv1alpha1.GroupVersion.Group)
        r.DisableGroup(policyv1alpha1.GroupVersion.Group)
        r.DisableGroup(workv1alpha1.GroupVersion.Group)
+
+       // disable event by default
+       r.DisableGroup("events.k8s.io")
        return r
 }

```

**Comment by pigletfly** [comment]
we should reconsider which resources should be ignored by default.I skipped
```v1/Node,Event,Pod,PersistentVolume,Endpoints,PersistentVolumeClaim;apiextensions.k8s.io/v1;events.k8s.io/v1beta1;discovery.k8s.io/v1beta1;rbac.authorization.k8s.io/v1``` in my cluster.

**Comment by dddddai** [comment]
> @XiShanYongYe-Chang @dddddai How about this:
> 
> ```diff
> diff --git a/pkg/util/apigroup.go b/pkg/util/apigroup.go
> index c54a557d..c176a238 100644
> --- a/pkg/util/apigroup.go
> +++ b/pkg/util/apigroup.go
> @@ -32,6 +32,9 @@ func NewSkippedResourceConfig() *SkippedResourceConfig {
>         r.DisableGroup(clusterv1alpha1.GroupVersion.Group)
>         r.DisableGroup(policyv1alpha1.GroupVersion.Group)
>         r.DisableGroup(workv1alpha1.GroupVersion.Group)
> +
> +       // disable event by default
> +       r.DisableGroup("events.k8s.io")
>         return r
>  }
> ```

@RainbowMango Yes, and I think we should decide which resources(besides `Event`) to be skipped by default as @pigletfly said

**Comment by XiShanYongYe-Chang** [comment]
Just as @dddddai said, both `v1/Event` and `events.k8s.io` need to be disabled.

Currently, `Event` needs to be skipped. Other resources can be added to default later if necessary. What do you think? @dddddai @pigletfly @RainbowMango

**Comment by dddddai** [comment]
> Currently, Event needs to be skipped. Other resources can be added to default later if necessary. What do you think? @dddddai @pigletfly @RainbowMango

Yes it makes sense to me, may I work on this? :)

**Comment by RainbowMango** [comment]
Sure, go for it. And thanks @dddddai
