### ISSUE TITLE
Are there apis that provide in addition to custom resources, such as karmadactl's join, unjoin, and other restAPI implementations

### ISSUE THREAD

**Issue by 2hangchen** [karmada-io/karmada#944]
**Please provide an in-depth description of the question you have**:
Are there apis that provide in addition to custom resources, such as karmadactl's join, unjoin, and other restAPI implementations

**Comment by RainbowMango** [comment]
Sorry, didn't get what you mean.

**Comment by 2hangchen** [comment]
> Sorry, didn't get what you mean.

在那天的社区会议中看到了前端的展示demo，集群列表等信息是可以通过apiserver提供的cluster.karmada.io下的restapi获取到，那么karmadactl命令行相关的命令，比如join，unjoin等命令有没有提供相关的restapi接口给前端调用

**Comment by RainbowMango** [comment]
Good question! I guess it is pretty reasonable to add some to support join/unjoin by API.
No clear ideas about how to do it.

**Comment by 2hangchen** [comment]
> Good question! I guess it is pretty reasonable to add some to support join/unjoin by API. No clear ideas about how to do it.

I tried an implementation yesterday that implemented karamdactl's commands as an http server component installed on the karmada control panel ,and verified.Like this:  
1. Implement an HTTP server  
![image](https://user-images.githubusercontent.com/31329928/141228801-d15e2ba2-e08c-45a9-adb7-d45f75f8e141.png)
2. Make a container  
![image](https://user-images.githubusercontent.com/31329928/141228934-e4f3f764-9e41-4a45-9b4f-c34dd33cc31d.png)
3.  Modifying deploy script //todo

**Comment by RainbowMango** [comment]
Impressive! I see you introduced another component (`backendapi`), I guess it serves not only the KarmadaUI, but also other systems. 

We are also thinking about providing more APIs by the `karmada-apiserver` (the benefit is we can share the same entry), but don't have an ideal solution yet. We have discussed similar things at https://github.com/karmada-io/karmada/issues/451.

**Comment by RainbowMango** [comment]
Looking forward to meeting you at the community meeting to talk about it.

**Comment by 2hangchen** [comment]
> Impressive! I see you introduced another component (`backendapi`), I guess it serves not only the KarmadaUI, but also other systems.
> 
> We are also thinking about providing more APIs by the `karmada-apiserver` (the benefit is we can share the same entry), but don't have an ideal solution yet. We have discussed similar things at #451.

#451 This describe looks not easy to impimplement,I think it's possible to spin off a service(server) that either provides a restapi implementation of karmadactl's commands or acts as a pass-through proxy for karmada-apiserver.where all http requests are processed.

**Comment by 2hangchen** [comment]
> > Impressive! I see you introduced another component (`backendapi`), I guess it serves not only the KarmadaUI, but also other systems.
> > We are also thinking about providing more APIs by the `karmada-apiserver` (the benefit is we can share the same entry), but don't have an ideal solution yet. We have discussed similar things at #451.
> 
> #451 This describe looks not easy to impimplement,I think it's possible to spin off a service(server) that either provides a restapi implementation of karmadactl's commands and acts as a pass-through proxy for karmada-apiserver.where all http requests are processed.

It acts like a kubect proxy ,but can do more than a proxy.

**Comment by RainbowMango** [comment]
Sorry @2hangchen, I missed this from my radar. Maybe we can talk about it at 
[Community Meeting](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit).

**Comment by RainbowMango** [comment]
Feel free to add an agenda.
