### ISSUE TITLE
[E2E]: Add test case cover job scheduling

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#955]
**What would you like to be added**:
#898 introduced a feature that `Job` could be scheduled just like `Deployment`, but the test case of E2E still missing.

**Why is this needed**:

**Comment by RainbowMango** [comment]
/help
@XiShanYongYe-Chang

**Comment by lonelyCZ** [comment]
I happen to want to understand the mechanics of E2E test, I would like to try it.
/assign

**Comment by XiShanYongYe-Chang** [comment]
@lonelyCZ Thank you, looking forward to your contribution.
