### ISSUE TITLE
Whether multiple loops needs to be optimized through data structure or other processing?

### ISSUE THREAD

**Issue by BDXGD** [karmada-io/karmada#972]
**What would you like to be added**:
I found that there are a lot of Brute Force like multiple loops are used.
I wonder if some data structures or other methods should be used to optimize?

**Comment by RainbowMango** [comment]
Can you give an example?
And what data structure you'd like to introduce?

It'd be great if the code gets more readable and easy to maintain.

**Comment by BDXGD** [comment]
This PR is only a part of program optimization. Others, such as brute force matching, we use hash tables (or some other data structures) optimize time. 

When the amount of data becomes larger, the effect of optimization will gradually be reflected.

**Comment by jwcesign** [comment]
The implementation is complete, so we can now close this issue.

/close
