### ISSUE TITLE
Namespace filter rules

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/karmada#985]
**What would you like to be added**:
For now, karmada takes namespaces that start with `karmada-` prefix as reserved namespace, resources under these namespaces will not be propagated by default.
https://github.com/karmada-io/karmada/blob/b0742b2c9c6f1a9cd7840ee9ddf9a6aa501d7281/pkg/detector/detector.go#L287-L290

Given several users met this issue(they use `karmada-test`, `karmada-dev`, etc.) and get confused, so I think we should take some actions, like:
- [ ] Add documents about this rule. (#1050, @Phil-sun )
- [x] Consider changing the rule, e.g. making a reserve list and only namespaces on the list will be ignored.  (#989, @JarHMJ)
  * karmada-system
  * karmada-cluster
  * karmada-es-*
  * ~~karmada-e2e-* (reserved for testing)~~

**Why is this needed**:

**Comment by Phil-sun** [comment]
Hi!@RainbowMango, I would like to do it.

**Comment by RainbowMango** [comment]
Thanks @Phil-sun, but no rush. The solution is not yet finalized. 

Hold on for a while, let's see if other comments.

/assign @Phil-sun 
assign it to you first.

**Comment by Phil-sun** [comment]
Ok, I also will  think it deeply whether there is an another solution! :)

**Comment by jameszhangyukun** [comment]
Hi!@RainbowMango, I would like to do it.

**Comment by RainbowMango** [comment]
Thank you @jameszhangyukun, (appreciated), but this has been assigned to @Phil-sun .

**Comment by JarHMJ** [comment]
hi@RainbowMango I have already commit this PR [989](https://github.com/karmada-io/karmada/pull/989) to resolve the issue。Please review

**Comment by RainbowMango** [comment]
Hi @JarHMJ Thanks for your contribution, but I just realized that this issue has been claimed by @Phil-sun.

So we can't move #989 forward @Phil-sun ok with it.

**Comment by Phil-sun** [comment]
Hi ！@RainbowMango  Since this work has been done, I'm ok with it.

**Comment by RainbowMango** [comment]
Thanks @Phil-sun. You can help review the PR that's also a form of contribution.

**Comment by Phil-sun** [comment]
With Pleasure! :)

**Comment by RainbowMango** [comment]
/assign @Phil-sun @JarHMJ 
as you are working together on this issue.
