### ISSUE TITLE
There are only unit tests for pkg/... in ci

### ISSUE THREAD

**Issue by lonelyCZ** [karmada-io/karmada#993]
**What happened**:
https://github.com/karmada-io/karmada/blob/5b068c31da1ae96e1d302b36404f44821f2415a7/Makefile#L98-L99

There are only unit tests for pkg/... in ci, but we have unit tests in cmd/...

So, if necessary, I would like to add it.

**What you expected to happen**:
Run unit test for cmd/... in ci

**Environment**:
- Karmada version: master
- Others:

**Comment by RainbowMango** [comment]
Yeah, all unit tests should be covered by CI. Thanks.
